import {spawn as nativeSpawn} from 'node:child_process';import {openSync,closeSync,writeSync} from 'node:fs';import {fullWrite} from './data-support.mjs';
export const TERM_GRACE=2000;export const OBSERVATION_GRACE=1000;
export async function captureScope(paths,body,io={open:openSync,close:closeSync}){const descriptors=[];let primary={present:false};const secondary=[];let value;try{for(const path of paths)descriptors.push(io.open(path,'wx',0o600));value=await body(descriptors);}catch(reason){primary={present:true,value:reason};}finally{for(const fd of descriptors){try{io.close(fd);}catch(reason){secondary.push({present:true,value:reason});}}}return{primary,secondary,value};}
export function abbreviated(reason){return{present:true,kind:reason===null?'null':typeof reason,value:typeof reason==='boolean'||typeof reason==='string'&&reason.length<=128||typeof reason==='number'&&Number.isFinite(reason)?reason:null,objectDetail:'NOT_INSPECTED',identity:'RAW_REFERENCE_RETAINED_NOT_SERIALIZED'};}
export async function ownChild(config,hooks={}){
 const clock=hooks.clock??(()=>performance.now());const now=clock();if(!Number.isFinite(now)||now>=config.deadline-config.reserveMilliseconds-config.timeoutMilliseconds-TERM_GRACE-OBSERVATION_GRACE)throw Error('child preadmission');
 const row={schema:3,role:config.role??'case',ownerPid:process.pid,clockDomain:'owner:'+process.pid,pid:null,admitted:true,created:false,spawned:false,exited:false,closed:false,code:null,signal:null,exitCode:null,exitSignal:null,stdoutBytes:0,stderrBytes:0,stdoutClosed:false,stderrClosed:false,stdoutEnded:false,stderrEnded:false,state:'ADMITTED',captureComplete:false,captureTruncated:false,termRequested:false,killRequested:false,primary:{present:false},secondary:[],trace:[]};
 const descriptors=[];let child,timeout,killTimer,graceTimer,writing=true,reported=false,resolveObservation,resolveRetirement;const observation=new Promise(resolve=>{resolveObservation=resolve});const retirement=new Promise(resolve=>{resolveRetirement=resolve});let retirementObserved=false;
 const event=(kind,fields={})=>{if(row.trace.length>=64){fail(Error('process trace cap'));return;}row.trace.push({seq:row.trace.length+1,at:Math.floor(performance.now()*1000),kind,...fields});};
 const fail=reason=>{if(!row.primary.present)row.primary={present:true,value:reason};};
 const secondary=reason=>{if(row.secondary.length<16)row.secondary.push({present:true,value:reason});else fail(Error('secondary cap'));};
 const finish=state=>{if(reported)return;reported=true;row.state=state;clearTimeout(timeout);clearTimeout(killTimer);clearTimeout(graceTimer);resolveObservation();};
 const check=()=>{if(row.closed&&row.exited&&row.stdoutClosed&&row.stderrClosed){if(!retirementObserved){retirementObserved=true;resolveRetirement();}if(!reported){row.captureComplete=row.stdoutEnded&&row.stderrEnded&&!row.captureTruncated;event('retired');finish('RETIRED');}}};
 const unknown=()=>{if(reported)return;writing=false;row.captureTruncated=true;row.captureComplete=false;for(const name of ['stdout','stderr'])try{child?.[name]?.pause();}catch(reason){secondary(reason);}if(!row.primary.present)fail(Error('retirement observation unknown'));event('unknown');finish('STOP_UNKNOWN');};
 const stop=()=>{if(!child||row.closed||row.termRequested)return;row.termRequested=true;event('term');try{child.kill('SIGTERM');}catch(reason){secondary(reason);}killTimer=setTimeout(()=>{if(reported)return;if(!row.closed){row.killRequested=true;event('kill');try{child.kill('SIGKILL');}catch(reason){secondary(reason);}}graceTimer=setTimeout(()=>{check();if(!reported)unknown();},OBSERVATION_GRACE);},TERM_GRACE);};
 event('admit');
 try{
  descriptors.push((hooks.open??openSync)(config.stdout,'wx',0o600));descriptors.push((hooks.open??openSync)(config.stderr,'wx',0o600));
  timeout=setTimeout(()=>{fail(Error('child deadline'));if(child&&!row.closed)stop();else if(!reported){graceTimer=setTimeout(unknown,OBSERVATION_GRACE);}},config.timeoutMilliseconds);
  child=(hooks.spawn??nativeSpawn)(config.node,config.args,{cwd:config.cwd,env:config.env,stdio:['ignore','pipe','pipe']});
  child.once('error',reason=>{fail(reason);stop();});child.once('spawn',()=>{row.spawned=true;event('spawn',{pid:child.pid??null});});child.once('exit',(code,signal)=>{row.exited=true;row.exitCode=code;row.exitSignal=signal;event('exit',{code,signal});check();});child.once('close',(code,signal)=>{row.closed=true;row.code=code;row.signal=signal;event('close',{code,signal});check();});
  row.created=true;row.pid=child.pid??null;event('created',{pid:row.pid});
  for(const [index,name]of [[0,'stdout'],[1,'stderr']]){const stream=child[name];stream.once('end',()=>{row[name+'Ended']=true;event(name+'End');check();});stream.once('close',()=>{row[name+'Closed']=true;event(name+'Close');check();});stream.on('error',reason=>{fail(reason);stop();});stream.on('data',chunk=>{if(!writing)return;try{if(chunk.length>config.channelBytes-row[name+'Bytes']){row.captureTruncated=true;throw Error('capture cap');}fullWrite(descriptors[index],chunk,hooks.write??writeSync);row[name+'Bytes']+=chunk.length;}catch(reason){fail(reason);row.captureTruncated=true;writing=false;stop();}});}
  try{hooks.afterSpawn?.(row);const after=clock();if(!Number.isFinite(after)||after>=config.deadline-config.reserveMilliseconds)throw Error('postspawn clock/deadline');const value=hooks.publish?.(row);if(value!==undefined)throw Error('publication hook is synchronous');}catch(reason){fail(reason);stop();}
  await observation;
 }catch(reason){fail(reason);if(child&&!reported){stop();await observation;}else if(!child){clearTimeout(timeout);row.state='NO_HANDLE';}}
 finally{writing=false;for(const fd of descriptors)try{(hooks.close??closeSync)(fd);}catch(reason){secondary(reason);}if(row.state!=='STOP_UNKNOWN'){clearTimeout(timeout);clearTimeout(killTimer);clearTimeout(graceTimer);}}
 const emergency={state:row.state,ownerPid:row.ownerPid,pid:row.pid,knownExit:row.exited,knownClose:row.closed,captureComplete:row.captureComplete,captureTruncated:row.captureTruncated,primary:row.primary.present?abbreviated(row.primary.value):{present:false},secondaryCount:row.secondary.length,ownedHandleRetained:row.state==='STOP_UNKNOWN'&&Boolean(child)};
 return{record:row,ownership:{child,retirement,retirementObserved:()=>retirementObserved,retained:row.state==='STOP_UNKNOWN'},emergency};
}
