import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
const root=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash';
const author=repo+'/tests/compatibility/bash-function-pipestatus-native-reference-20260829/v2';
const actual=author+'/actual-run-v1';
const node='/Users/kjopek/.nvm/versions/node/v22.22.2/bin/node';
const mode=process.argv[2],capture=fs.mkdtempSync('/tmp/native26-actual-audit-'+mode+'-');
const log=fs.openSync(capture+'/events.jsonl','wx',0o600);
const start=fs.statSync('/tmp/native26-actual-audit-bootstrap-20260829.stdout').birthtimeMs,deadline=start+900000;
const event=row=>{fs.writeSync(log,JSON.stringify({at:new Date().toISOString(),...row})+'\n');fs.fsyncSync(log);};
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function read(file,max=4194304){const stat=fs.lstatSync(file);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=max);const fd=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const before=fs.fstatSync(fd);assert(before.ino===stat.ino&&before.dev===stat.dev);const bytes=fs.readFileSync(fd),after=fs.fstatSync(fd);assert(bytes.length===stat.size&&after.size===before.size&&after.mtimeMs===before.mtimeMs);return bytes;}finally{fs.closeSync(fd);}}
function write(name,value){fs.writeFileSync(root+'/'+name,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});}
function emit(value){const bytes=JSON.stringify(value,null,2)+'\n';process.stdout.write(bytes);fs.writeSync(3,bytes);}
async function child(label,executable,args,timeout=30000){assert(Date.now()<deadline);const stdout=fs.openSync(capture+'/'+label+'.stdout','wx',0o600),stderr=fs.openSync(capture+'/'+label+'.stderr','wx',0o600);let exit=false,errorPresent=false;try{const proc=spawn(executable,args,{cwd:repo,stdio:['ignore',stdout,stderr],env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});const done=new Promise(resolve=>{proc.on('error',()=>{errorPresent=true;});proc.on('exit',(code,signal)=>{exit=true;event({event:'exit',pid:proc.pid,label,code,signal});});proc.on('close',(code,signal)=>resolve({code,signal}));});event({event:'enrolled',pid:proc.pid,label,executable,args});let expired=false;const timer=setTimeout(()=>{expired=true;proc.kill('SIGKILL');},Math.min(timeout,deadline-Date.now()));const result=await done;clearTimeout(timer);fs.fsyncSync(stdout);fs.fsyncSync(stderr);event({event:'close',pid:proc.pid,label,...result,exit,errorPresent,expired});assert(exit&&!errorPresent&&!expired&&result.signal===null,'CAPTURE_OR_RETIREMENT_STOP');return{...result,stdout:capture+'/'+label+'.stdout',stderr:capture+'/'+label+'.stderr'};}finally{fs.closeSync(stdout);fs.closeSync(stderr);}}
async function git(label,args){const result=await child(label,'/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false','-c','core.hooksPath=/dev/null','-c','commit.gpgsign=false','-c','core.abbrev=40',...args]);assert.equal(result.code,0,label);return read(result.stdout);}
async function main(){assert(Date.now()<deadline);event({event:'owner-start',pid:process.pid,mode,capture});
if(mode==='inspect'){
 write('ROLE-PLAN.json',{start:new Date(start).toISOString(),deadline:new Date(deadline).toISOString(),limits:{knownOS:32,peak:3,capture:50331648,work:201326592},planned:[{role:'apply_patch bootstrap and implementation',count:2},{role:'inspect owner and committed handoff Git',count:2},{role:'bounded metadata reader',count:1},{role:'prepare owner and syntax helper',count:2},{role:'seal owner Git add/commit',count:3},{role:'audit owner + PURE DATA helper',count:2},{role:'publication owner Git add/commit/status',count:4}],plannedKnown:16,reserve:16,PUREAuditHelpers:1,controls:8,expectedPeak:2,Bash:0,Workers:0,oldPIDProbes:0});
 const handoff=await git('handoff',['show','5861ec9a8750de90bf38f93a2cd0df66198e8d9f:'+path.relative(repo,actual+'/HANDOFF.md')]);assert(handoff.equals(read(actual+'/HANDOFF.md')));write('HANDOFF.raw',handoff.toString());
 const files=fs.readdirSync(actual).sort().map(name=>{const stat=fs.lstatSync(actual+'/'+name);return{name,bytes:stat.size,regular:stat.isFile(),mode:stat.mode&511};});write('LOCATORS.json',{files,capture});emit({capture,files,handoff:handoff.toString()});
}else if(mode==='prepare'){
 const raw=read(actual+'/SEAL.json');assert.equal(raw.length,67586);assert.equal(hash(raw),'98b005cf2ed86002f08da295161cd6b54546ee509164be9b549ba926546fbf42');
 const seal=JSON.parse(raw);assert.equal(seal.files.length,125);for(const pin of seal.files){assert(!pin.path.startsWith('/')&&!pin.path.split('/').includes('..'));const bytes=read(actual+'/'+pin.path);assert.equal(bytes.length,pin.bytes);assert.equal(hash(bytes),pin.sha256);assert.equal(fs.lstatSync(actual+'/'+pin.path).mode&511,pin.mode);}
 const sourceFailures=[];for(const name of ['schema','schema-v2']){const file='/tmp/native26-actual-audit-'+name+'-20260829.stderr',bytes=read(file);sourceFailures.push({path:file,bytes:bytes.length,sha256:hash(bytes),disposition:'retired source-helper ENOENT guessed captured/F02.json instead of manifest captured/F02.json.data; original exit1 preserved, no native finding'});}write('SOURCE-HELPER-FAILURES.json',sourceFailures);
 const syntax=await child('audit-syntax',node,['--check',root+'/audit.mjs']);assert.equal(syntax.code,0);
 write('PRESEAL.json',{at:new Date().toISOString(),source:'5861ec9a8750de90bf38f93a2cd0df66198e8d9f',actualSeal:{bytes:67586,sha256:'98b005cf2ed86002f08da295161cd6b54546ee509164be9b549ba926546fbf42'},files:['owner.mjs','audit.mjs','ROLE-PLAN.json'].map(name=>{const bytes=read(root+'/'+name);return{path:name,bytes:bytes.length,sha256:hash(bytes)};}),membership:{observations:26,artifactFiles:125,captureFiles:109,sourcePinRecords:154,tools:4,controls:['C01 valid binary frame','C02 wrong magic','C03 missing final NUL','C04 extra field','C05 length mismatch','C06 noncanonical base64','C07 mismatched ID','C08 invalid status and raw-hash tamper']},boundary:'PURE DATA only; no source-helper or product module imports, process/Worker/native calls or old PID probes; one audit helper',reviewRoles:{plannedThroughPublication:20,ceiling:32,peak:2,additionalSourceReadersFromReserve:4,priorTwoFailures:'not rescored'},qualifications:['expected bytes/hash before JSON/frame decode','recorded owner exit0 is ROOT report, not independent approval-service/exit telemetry','receiptPublished false in persisted rows precedes later credit; authenticate journal + RESULTS separately']});emit({capture,presealSha256:hash(read(root+'/PRESEAL.json'))});
}else if(mode==='seal'){
 await git('stage-preseal',['add','--',path.relative(repo,root)]);const commit=await git('commit-preseal',['commit','--only','-m','test: preseal native26 actual-observation DATA audit','--',path.relative(repo,root)]);emit({capture,commit:commit.toString().match(/\[main ([a-f0-9]{40})\]/)?.[1]});
}else if(mode==='audit'){
 const preseal=JSON.parse(read(root+'/PRESEAL.json'));for(const expected of preseal.files){const bytes=read(root+'/'+expected.path);assert.equal(bytes.length,expected.bytes);assert.equal(hash(bytes),expected.sha256);}const result=await child('pure-audit',node,[root+'/audit.mjs'],60000);write('AUDIT-EXECUTION.json',{...result,capture});assert.equal(result.code,0);emit({capture,stdout:read(result.stdout).toString()});
}else if(mode==='publish'){
 const files=[];let bytes=0;for(const name of fs.readdirSync(root).sort()){const data=read(root+'/'+name);bytes+=data.length;files.push({path:name,bytes:data.length,sha256:hash(data)});}assert(bytes<201326592);write('PUBLICATION-SNAPSHOT.json',{at:new Date().toISOString(),bytes,entries:files.length,files,capture});await git('stage-results',['add','--',path.relative(repo,root)]);const commit=await git('commit-results',['commit','--only','-m','test: publish independent native26 observation audit','--',path.relative(repo,root)]);const status=await git('owned-status',['status','--porcelain=v1','--untracked-files=normal','--',path.relative(repo,root)]);assert.equal(status.length,0);emit({capture,commit:commit.toString().match(/\[main ([a-f0-9]{40})\]/)?.[1],receiptSha256:hash(read(root+'/RECEIPT.json')),cleanOwned:true,bytes,at:new Date().toISOString()});
}else throw Error('mode');}
try{await main();event({event:'owner-complete',pid:process.pid,mode,code:0});}catch(reason){event({event:'primary',present:true,message:String(reason),stack:reason?.stack});console.error(reason);process.exitCode=1;}finally{fs.closeSync(log);}
