import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const root=path.dirname(new URL(import.meta.url).pathname);
const author='/Users/kjopek/Workspace/safe-bash/tests/compatibility/bash-function-pipestatus-native-reference-20260829/v2';
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function read(file,max=4194304){const stat=fs.lstatSync(file);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=max);const bytes=fs.readFileSync(file);assert.equal(bytes.length,stat.size);return bytes;}
function output(name,value){fs.writeFileSync(root+'/'+name,value,{flag:'wx',mode:0o600});}
try{
const readyBytes=read(author+'/READY-SEAL.json');assert.equal(hash(readyBytes),'7cad2e981d9008e90f64bc04d528ecc9da02458bd46859382d1028020c925b47');const ready=JSON.parse(readyBytes);
for(const pin of ready.files){assert(!pin.path.split('/').includes('..'));const file=author+'/'+pin.path,bytes=read(file);assert.equal(bytes.length,pin.bytes);assert.equal(hash(bytes),pin.sha256);assert.equal(fs.lstatSync(file).mode&511,pin.mode);}
const presealBytes=read(author+'/materialized/PRESEAL.json');assert.equal(hash(presealBytes),'b082c051f1e1599af1a5789786c20a6d89d882dda67b6d2430062c84779bf901');
const source=read(author+'/controller.mjs').toString();assert.equal(hash(Buffer.from(source)),'2ba3f93d171b5a719e67de47d83cf873682b029466abd1869924aff4b21771d0');
const start=source.indexOf(' const admission=await import('),end=source.indexOf(" authenticateSeal(executable+'/PRESEAL.json');await tools();json('CONTROL-RESULT.json'");assert(start>0&&end>start);
const original=source.slice(start,end);assert.equal((original.match(/await test\('D\d\d'/g)||[]).length,12);assert.equal(original.split("root+'/control-work'").length,2);
const body=original.replace("root+'/control-work'","reviewRoot+'/work'");
const tools=JSON.parse(read(author+'/materialized/TOOLS.json'));
const fixtures=["process.stdout.write(Buffer.from([0,65,10]));process.stderr.write('err');","process.on('SIGTERM',()=>{});process.stdout.write('ready');setInterval(()=>{},1000);"];
const inputs={author,sourceCommit:'62c262a0c673908388748d7133a001978da4f968',readySha256:hash(readyBytes),executablePresealSha256:hash(presealBytes),controller:{sha256:hash(Buffer.from(source)),start,end,originalBodySha256:hash(Buffer.from(original)),relocatedBodySha256:hash(Buffer.from(body)),relocation:"ONLY scratch root+'/control-work' -> reviewRoot+'/work'; assertions/fixtures unchanged"},files:ready.files,tools,fixtures:fixtures.map(text=>({text,bytes:Buffer.byteLength(text),sha256:hash(Buffer.from(text))})),roles:{controller:1,harmlessNodeChildren:2,expectedPeak:3,includes:'outer supervisor + review controller + one sequential fixture child; author source group observer uses no process spawn',Bash:0,Workers:0,asyncLoaders:0},controls:['D01','D02','D03','D04','D05','D06','D07','D08','D09','D10','D11','D12','N01','N02','N03','N04','N05','N06','N07','N08']};
output('INPUTS.json',JSON.stringify(inputs,null,2)+'\n');
const prefix=`import fs from 'node:fs';\nimport path from 'node:path';\nimport crypto from 'node:crypto';\nimport assert from 'node:assert/strict';\nimport {pathToFileURL} from 'node:url';\nconst reviewRoot=path.dirname(new URL(import.meta.url).pathname),root=${JSON.stringify(author)},executable=root+'/materialized',runRoot='/private/tmp/safe-bash-function-pipestatus-observations-20260829-v2';\nconst node='/Users/kjopek/.nvm/versions/node/v22.22.2/bin/node';\nconst deadline=JSON.parse(fs.readFileSync(reviewRoot+'/START.json')).at;\nconst deadlineMs=Date.parse(deadline)+1200000;\nconst checkTime=()=>assert(Date.now()<deadlineMs,'REVIEW_DEADLINE');\nconst hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');\nfunction read(file,max=4194304){const stat=fs.lstatSync(file);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=max);const bytes=fs.readFileSync(file);assert.equal(bytes.length,stat.size);return bytes;}\nconst parse=file=>JSON.parse(read(file));\nfunction json(name,value){const file=reviewRoot+'/'+name;fs.mkdirSync(path.dirname(file),{recursive:true,mode:448});fs.writeFileSync(file,JSON.stringify(value,null,2)+'\\n',{flag:'wx',mode:384});}\nconst inputs=parse(reviewRoot+'/INPUTS.json');\nfunction authenticate(){for(const pin of inputs.files){const bytes=read(root+'/'+pin.path);assert.equal(bytes.length,pin.bytes);assert.equal(hash(bytes),pin.sha256);assert.equal(fs.lstatSync(root+'/'+pin.path).mode&511,pin.mode);}}\nasync function tools(){for(const pin of [...inputs.tools.toolPins,inputs.tools.environmentLauncher,inputs.tools.wrapperTool].filter(Boolean)){const stat=fs.lstatSync(pin.path);assert(stat.isFile()&&stat.size===pin.bytes&&(stat.mode&511)===pin.mode);const digest=crypto.createHash('sha256');let count=0;for await(const bytes of fs.createReadStream(pin.path,{highWaterMark:65536})){count+=bytes.length;assert(count<=pin.bytes);digest.update(bytes);}assert.equal(count,pin.bytes);assert.equal(digest.digest('hex'),pin.sha256);}}\ntry{checkTime();authenticate();await tools();\n`;
const appendix=read(root+'/novel.fragment.data').toString();
const footer=`\nauthenticate();await tools();json('RESULT.json',{schema:'native26-independent-preexecution-v1',results,assertionCount,pass:results.filter(row=>row.status==='PASS').length,fail:results.filter(row=>row.status==='FAIL').length,nativeStarts:0,fixtureChildren:2,at:new Date().toISOString()});console.log(JSON.stringify({pass:results.filter(row=>row.status==='PASS').length,fail:results.filter(row=>row.status==='FAIL').length,assertionCount}));if(results.some(row=>row.status==='FAIL'))process.exitCode=1;\n}catch(reason){json('PRIMARY.json',{present:true,type:typeof reason,message:String(reason),stack:reason?.stack});console.error(reason);process.exitCode=1;}\n`;
output('review.mjs',(prefix+body+appendix+footer).replace('Math.min(deadline,Date.now()+20000)','Math.min(deadlineMs,Date.now()+20000)'));
output('PRESEAL.md',`# Native26 independent preexecution controls\n\nPost-author/source inspection; before control execution. No native GO.\n\nCandidate 62c262a0c673908388748d7133a001978da4f968; ready ${hash(readyBytes)}; executable ${hash(presealBytes)}. All ready files authenticated before any imported helper. No entry import. Stream hashes of exact declared Node/Bash/env/zsh tool files are DATA, never version/execution.\n\nOne independent Node controller repeats D01–D12 exact test bodies with output/scratch relocated only and review deadline supplied numerically; 106 prior-author assertions not pre-counted as independent passes. Eight separately sealed novel DATA groups N01–N08. Exactly two harmless Node fixtures in D09, sequential; no extra fixtures. Supervisor + controller + fixture =3 direct roles, within peak4. Syntax/admission/admin roles sequential. Overall48 known roles and20min starting START.json (bootstrap slightly earlier),64MiB capture/256MiB work. Reserve12 admin roles; stop on known retirement/capture/integrity/cap faults. D09 group checks target only this fresh fixture's owned group; no old PID probes or universal census claim.\n\nChanges to extraction: single scratch relocation, output json redirected independently, deadline number adapter; assertion/fixture text otherwise identical. Generated source and exact insertion domains bound INPUTS/SEAL. No author files altered. Root GO/review/preprovision templates remain PENDING. No native observations/PIPESTATUS semantics accepted.\n`);
console.log(JSON.stringify({at:new Date().toISOString(),files:ready.files.length,bodySha256:inputs.controller.originalBodySha256,reviewSha256:hash(read(root+'/review.mjs'))}));
}catch(reason){console.error(reason);process.exitCode=1;}
