import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const repo='/Users/kjopek/Workspace/safe-bash';
const author=path.join(repo,'tests/compatibility/bash-function-pipestatus-native-reference-20260829/v2');
const mode=process.argv[2];
const capture=mode==='publish'?fs.mkdtempSync('/tmp/native26-preflight-review-publication-'):path.join(root,'capture');
fs.mkdirSync(capture,{recursive:true});
const events=fs.openSync(path.join(capture,mode+'.events.jsonl'),'wx');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const event=value=>{fs.writeSync(events,JSON.stringify({at:new Date().toISOString(),...value})+'\n');fs.fsyncSync(events);};
function read(file,max=2097152){const stat=fs.lstatSync(file);if(!stat.isFile()||stat.size>max)throw Error('bounded regular input');const bytes=fs.readFileSync(file);if(bytes.length!==stat.size)throw Error('read drift');return bytes;}
function write(name,value){fs.writeFileSync(path.join(root,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});}
async function child(label,exe,args,input,timeout=60000){const out=path.join(capture,label+'.stdout'),err=path.join(capture,label+'.stderr');const stdout=fs.openSync(out,'wx'),stderr=fs.openSync(err,'wx');event({event:'capture-open',label});let failurePresent=false,failure,exitSeen=false;try{const proc=spawn(exe,args,{cwd:repo,stdio:[input===undefined?'ignore':'pipe',stdout,stderr],env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});const done=new Promise(resolve=>{proc.on('error',error=>{failurePresent=true;failure=error;});proc.on('exit',(code,signal)=>{exitSeen=true;event({event:'exit',label,pid:proc.pid,code,signal});});proc.on('close',(code,signal)=>resolve({code,signal}));});event({event:'enrolled',label,pid:proc.pid,exe,args});if(input!==undefined){proc.stdin.on('error',error=>{failurePresent=true;failure=error;});proc.stdin.end(input);}let timedOut=false;const timer=setTimeout(()=>{timedOut=true;proc.kill('SIGKILL');},timeout);const result=await done;clearTimeout(timer);fs.fsyncSync(stdout);fs.fsyncSync(stderr);event({event:'close',label,pid:proc.pid,...result,exitSeen,timedOut,failurePresent});if(!exitSeen||timedOut||failurePresent||result.signal!==null)throw Error('known retirement STOP '+String(failure));return {...result,stdout:out,stderr:err};}finally{fs.closeSync(stdout);fs.closeSync(stderr);event({event:'capture-closed',label});}}
const node='/Users/kjopek/.nvm/versions/node/v22.22.2/bin/node';
const git='/usr/bin/git';
const options=['-c','gc.auto=0','-c','maintenance.auto=false','-c','core.hooksPath=/dev/null','-c','commit.gpgsign=false','-c','core.abbrev=40'];
async function main(){event({event:'owner-start',pid:process.pid,mode});if(mode==='inspect'){
  write('START.json',{at:new Date().toISOString(),grant:{minutes:20,knownOS:48,peak:4,capture:67108864,work:268435456},scope:'preexecution SOURCE/DATA and sealed harmless Node controls only; no Bash'});
  const names=fs.readdirSync(author).sort();const files=[];for(const name of names){const file=path.join(author,name),stat=fs.lstatSync(file);if(stat.isFile())files.push({name,bytes:stat.size});}write('LOCATORS.json',{author,files});
  const result=await child('committed-handoff',git,[...options,'show','62c262a0c673908388748d7133a001978da4f968:'+path.relative(repo,path.join(author,'HANDOFF.md'))]);if(result.code!==0)throw Error('handoff Git');const bytes=read(path.join(author,'HANDOFF.md'));if(!read(result.stdout).equals(bytes))throw Error('handoff identity');fs.writeFileSync(path.join(root,'HANDOFF.raw'),bytes,{flag:'wx'});
}else if(mode==='details'){
  const bytes=read(path.join(author,'READY-SEAL.json'));if(hash(bytes)!=='7cad2e981d9008e90f64bc04d528ecc9da02458bd46859382d1028020c925b47')throw Error('ready seal hash');const ready=JSON.parse(bytes);
  const files={};for(const name of ['CONTROL-PRESEAL.json','SOURCE-DELTA.json','APPROVAL-PROPOSAL.template.json','GO.template.json','REVIEW-ACCEPTANCE.template.json','controller.mjs','cohort.fragment.data']){const body=read(path.join(author,name));files[name]={bytes:body.length,sha256:hash(body),text:name==='controller.mjs'?undefined:body.toString()};}
  write('DETAILS.json',{ready,files});
  const controller=read(path.join(author,'controller.mjs'));fs.writeFileSync(path.join(root,'controller-inspection.source'),controller,{flag:'wx'});
}else if(mode==='syntax'){for(const name of ['supervise.mjs','review.mjs']){const result=await child('syntax-'+name,node,['--check',path.join(root,name)]);if(result.code!==0)throw Error('syntax '+name);}}
else if(mode==='seal'){const files={};for(const name of ['supervise.mjs','review.mjs','INPUTS.json','PRESEAL.md']){const bytes=read(path.join(root,name));files[name]={bytes:bytes.length,sha256:hash(bytes)};}write('SEAL.json',{at:new Date().toISOString(),files});let result=await child('stage-preseal',git,[...options,'add','--',path.relative(repo,root)]);if(result.code!==0)throw Error('stage');result=await child('commit-preseal',git,[...options,'commit','--only','-m','test: preseal independent native26 preflight controls','--',path.relative(repo,root)]);if(result.code!==0)throw Error('commit');}
else if(mode==='review'){const seal=JSON.parse(read(path.join(root,'SEAL.json')));for(const [name,pin]of Object.entries(seal.files)){const bytes=read(path.join(root,name));if(bytes.length!==pin.bytes||hash(bytes)!==pin.sha256)throw Error('seal drift');}const result=await child('review',node,[path.join(root,'review.mjs')],undefined,120000);write('EXECUTION.json',{...result,at:new Date().toISOString()});if(result.code!==0)process.exitCode=1;}
else if(mode==='publish'){write('PUBLICATION-LOCATION.json',{capture,at:new Date().toISOString()});let bytes=0,entries=0;const files=[];function visit(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name),stat=fs.lstatSync(file);entries++;if(stat.isDirectory())visit(file);else{if(!stat.isFile())throw Error('owned nonregular');bytes+=stat.size;files.push({path:path.relative(root,file),bytes:stat.size,sha256:hash(read(file,16777216))});}}}visit(root);const snapshot=Object.freeze({root,at:new Date().toISOString(),bytes,entries,files});if(bytes>268435456)throw Error('working cap');write('PUBLICATION-SNAPSHOT.json',snapshot);event({event:'immutable-local-snapshot',bytes,entries});let result=await child('stage-results',git,[...options,'add','--',path.relative(repo,root)]);if(result.code!==0)throw Error('stage');result=await child('commit-results',git,[...options,'commit','--only','-m','test: publish independent native26 preexecution review','--',path.relative(repo,root)]);if(result.code!==0)throw Error('commit');const commitText=read(result.stdout).toString();result=await child('owned-status',git,[...options,'status','--porcelain=v1','--untracked-files=normal','--',path.relative(repo,root)]);if(result.code!==0)throw Error('status');console.log(JSON.stringify({capture,code:0,commitText,ownedStatus:read(result.stdout).toString(),snapshot:{bytes,entries}}));}
else throw Error('unsupported explicit mode');}
try{await main();event({event:'owner-complete',pid:process.pid,mode,code:process.exitCode??0});}catch(error){event({event:'primary',present:true,message:String(error),stack:error?.stack});console.error(error);process.exitCode=1;}finally{fs.closeSync(events);}
