import {expect,it,vi} from "vitest";
import {createMemoryFileSystem} from "@poe-code/safe-fs";
import {PagedStorage} from "@poe-code/safe-fs/storage";
import type {PdfDisplayList,PdfSoftMask,PdfPaintOperation} from "../ast.js";
import {StoredOperationsWriter} from "../content/stored-operations.js";
import {renderDisplayListToSvg,encodeSvgSoftMaskChunks} from "./raster.js";
const geometry={width:17,height:13,origin:[-2,-3] as const};
function mask(subtype:PdfSoftMask["subtype"],transfer:boolean):PdfSoftMask{return {subtype,backdrop:{r:1,g:0.7,b:0.3},...(transfer?{transferMap:Uint8Array.from({length:256},(_,i)=>255-i)}:{}),operations:[{kind:"path",value:{segments:[{kind:"rect",x:0,y:0,width:11,height:9}],strokeWidth:1,fillColor:{r:0.8,g:0.2,b:0.1},fillAlpha:0.7}}]};}
for(const subtype of ["Alpha","Luminosity"] as const)for(const transfer of [false,true])for(const retained of [false,true])for(const scale of [0.7,1,2])it(`streams exact ${subtype} mask transfer=${transfer} retained=${retained} scale=${scale}`,async()=>{
 const original=mask(subtype,transfer),operation:PdfPaintOperation={kind:"path",value:{segments:[{kind:"rect",x:0,y:0,width:17,height:13}],strokeWidth:1,fillColor:{r:1,g:0,b:0},softMask:original}},display:PdfDisplayList={...geometry,pageIndex:0,rotation:0,glyphs:[],paths:[],images:[],annotations:[],operations:[operation]},svg=renderDisplayListToSvg(display,{scale}),start=svg.indexOf('<image'),expected=svg.slice(start,svg.indexOf('/>',start)+2);
 const fs=createMemoryFileSystem();await fs.mkdir('/scratch');const storage={fs,directory:'/scratch'},backing=new PagedStorage({fs,cwd:'/scratch',env:{},signal:new AbortController().signal},4);let input=original;
 try{if(retained){const writer=new StoredOperationsWriter(backing);for(const operation of original.operations)await writer.append(operation);input={...original,operations:[],storedOperations:writer.snapshot()};}const chunks=[];for await(const chunk of encodeSvgSoftMaskChunks(input,geometry,storage,{scale,tileSize:4,chunkBytes:31})){expect(chunk.buffer.byteLength).toBeLessThanOrEqual(31);chunks.push(chunk);}expect(new TextDecoder().decode(Buffer.concat(chunks))).toBe(expected);}finally{await backing.close();}expect(await fs.readdir('/scratch')).toEqual([]);
});
it('admits mask scratch before rendering and cleans on early return and cancellation',async()=>{const fs=createMemoryFileSystem();await fs.mkdir('/scratch');const storage={fs,directory:'/scratch'},input=mask('Alpha',false);await expect(encodeSvgSoftMaskChunks(input,geometry,storage,{maxPixelWorkingBytes:1}).next()).rejects.toMatchObject({code:'E_LIMIT'});expect(await fs.readdir('/scratch')).toEqual([]);const controller=new AbortController(),reason=new Error('cancel mask'),iterator=encodeSvgSoftMaskChunks(input,geometry,storage,{signal:controller.signal,tileSize:4,chunkBytes:32});await iterator.next();controller.abort(reason);await expect(iterator.next()).rejects.toBe(reason);expect(await fs.readdir('/scratch')).toEqual([]);for await(const ignored of encodeSvgSoftMaskChunks(input,geometry,storage,{tileSize:4,chunkBytes:32})){void ignored;break;}expect(await fs.readdir('/scratch')).toEqual([]);});
it('admits pixel staging before reading retained operations',async()=>{let reads=0;const input:PdfSoftMask={...mask('Alpha',false),operations:[],storedOperations:{kind:'stored-operations',position:0,count:1,effects:0,storage:{allocate(){return 0;},async write(){},async read(){reads++;throw Error('must not read');}}}},fs=createMemoryFileSystem();await fs.mkdir('/scratch');await expect(encodeSvgSoftMaskChunks(input,geometry,{fs,directory:'/scratch'},{maxStagingBytes:1,tileSize:4}).next()).rejects.toMatchObject({code:'E_LIMIT'});expect(reads).toBe(0);expect(await fs.readdir('/scratch')).toEqual([]);});
it('preserves retained operation read failures and cleans tile staging',async()=>{const reason=new Error('mask read failed'),input:PdfSoftMask={...mask('Alpha',false),operations:[],storedOperations:{kind:'stored-operations',position:0,count:1,effects:0,storage:{allocate(){return 0;},async write(){},async read(){throw reason;}}}},fs=createMemoryFileSystem();await fs.mkdir('/scratch');await expect(encodeSvgSoftMaskChunks(input,geometry,{fs,directory:'/scratch'},{tileSize:4}).next()).rejects.toBe(reason);expect(await fs.readdir('/scratch')).toEqual([]);});
it.each([32,128])('keeps mask I/O bounded with a slow sink at %i pixels',async dimension=>{const base=createMemoryFileSystem();await base.mkdir('/scratch');const readFile=vi.fn(async()=>{throw Error('whole-file read forbidden');}),writeFile=vi.fn(async()=>{throw Error('whole-file write forbidden');}),fs=new Proxy(base,{get(target,key){if(key==='readFile')return readFile;if(key==='writeFile')return writeFile;const value=Reflect.get(target,key,target);return typeof value==='function'?value.bind(target):value;}}),create=fs.createStagedFile!.bind(fs);let writes=0,outstanding=0,peak=0;vi.spyOn(fs,'createStagedFile').mockImplementation(async(...args)=>{const staged=await create(...args),writer=staged.writer!;return {...staged,writer:{...writer,async write(bytes,options){expect(outstanding).toBe(0);expect(bytes.byteLength).toBeLessThanOrEqual(64);outstanding=bytes.length;peak=Math.max(peak,outstanding);await Promise.resolve();await writer.write(bytes,options);writes++;outstanding=0;},finish:options=>writer.finish(options)}};});let output=0;for await(const bytes of encodeSvgSoftMaskChunks(mask('Luminosity',true),{width:dimension,height:dimension},{fs,directory:'/scratch'},{tileSize:16,chunkBytes:64,maxPixelWorkingBytes:16*16*4+64*6})){const before=writes;await Promise.resolve();expect(writes).toBe(before);expect(bytes.buffer.byteLength).toBeLessThanOrEqual(64);output+=bytes.length;}expect(output).toBeGreaterThan(100);expect(peak).toBeGreaterThan(0);expect(peak).toBeLessThanOrEqual(64);expect(readFile).not.toHaveBeenCalled();expect(writeFile).not.toHaveBeenCalled();expect(await fs.readdir('/scratch')).toEqual([]);});
it('preserves injected staging write failures and removes scratch',async()=>{const fs=createMemoryFileSystem();await fs.mkdir('/scratch');const create=fs.createStagedFile!.bind(fs),reason=new Error('write failure');vi.spyOn(fs,'createStagedFile').mockImplementation(async(...args)=>{const staged=await create(...args);return {...staged,writer:{...staged.writer!,async write(){throw reason;}}};});await expect(encodeSvgSoftMaskChunks(mask('Alpha',false),geometry,{fs,directory:'/scratch'},{tileSize:4}).next()).rejects.toBe(reason);expect(await fs.readdir('/scratch')).toEqual([]);});
