import {expect,it} from "vitest";
import {createMemoryFileSystem} from "@poe-code/safe-fs";
import {PagedStorage} from "@poe-code/safe-fs/storage";
import {PdfDocument} from "../document.js";
import {StoredPathWriter} from "../content/stored-path.js";
import type {PdfPaintOperation,PdfEvaluatedPath} from "../ast.js";
import {renderDisplayListToSvg,encodeSvgPathPaintChunks} from "./raster.js";
const cases=["0.1 0.3 0.8 rg 10 20 50 60 re f","2 w 10 20 m 70 80 l S","0 w 10 20 m 70 80 l S","[3 2] 1 d 2 w 10 20 m 70 80 l S","[0 4] 0 d 1 J 3 w 10 20 m 70 80 l S","[0 4] 1 d 2 J 2 j 3 w 10 20 50 60 re B*","q 2 0.3 0.5 1 5 7 cm [4 3] 2 d 2 w 5 5 m 30 40 l S Q","q 2 0.3 0.5 1 5 7 cm [0 4] 2 d 1 J 2 w 5 5 m 30 40 l S Q","10 20 m 20 60 60 60 70 20 c h B"];
it.each(cases.flatMap(content=>[false,true].map(stored=>({content,stored}))))("streams SVG paint stored=$stored $content",async({content,stored})=>{
 const doc=PdfDocument.create(),page=doc.addPage([100,100]);page.setRawContentStream(content);const display=PdfDocument.load(doc.save()).getPage(0).evaluateDisplayList(),original=display.operations![0]!;expect(original.kind).toBe("path");
 const expected=renderDisplayListToSvg(display).split("\n").filter(line=>line.startsWith("  <path")).join("\n"),fs=createMemoryFileSystem();await fs.mkdir("/scratch");const backing=new PagedStorage({fs,cwd:"/scratch",env:{},signal:new AbortController().signal},4);let operation=original as Extract<PdfPaintOperation,{kind:"path"}>;
 if(stored){const writer=new StoredPathWriter(backing);for(const segment of operation.value.segments)await writer.append(segment);const path:PdfEvaluatedPath={...operation.value,segments:[],storedSegments:await writer.finish()};if(path.dashArray?.length){const bytes=new Uint8Array(path.dashArray.length*8),view=new DataView(bytes.buffer);path.dashArray.forEach((n,i)=>view.setFloat64(i*8,n,true));const position=backing.allocate(bytes.length);await backing.write(position,bytes);operation={kind:"path",value:{...path,dashArray:undefined,storedDash:{position,storage:backing,length:path.dashArray.length,total:path.dashArray.reduce((a,b)=>a+b,0)}}};}else operation={kind:"path",value:path};}
 try{const chunks=[];for await(const bytes of encodeSvgPathPaintChunks(operation,100,{scale:1,chunkBytes:31})){expect(bytes.buffer.byteLength).toBeLessThanOrEqual(31);chunks.push(bytes);}expect(new TextDecoder().decode(Buffer.concat(chunks))).toBe(expected);}finally{await backing.close();}expect(await fs.readdir("/scratch")).toEqual([]);
});
it("preserves glyph labels and invisible glyph filtering",async()=>{const doc=PdfDocument.create();doc.addPage([100,100]).drawText("<&",{x:10,y:20,size:20});const display=PdfDocument.load(doc.save()).getPage(0).evaluateDisplayList();for(const operation of display.operations!){if(operation.kind!=="glyph")continue;const one={...display,operations:[operation],glyphs:[operation.value]},expected=renderDisplayListToSvg(one).split("\n").filter(line=>line.startsWith("  <path")).join("\n"),chunks=[];for await(const bytes of encodeSvgPathPaintChunks(operation,100))chunks.push(bytes);expect(new TextDecoder().decode(Buffer.concat(chunks))).toBe(expected);expect((await encodeSvgPathPaintChunks({kind:"glyph",value:{...operation.value,renderMode:3}},100).next()).done).toBe(true);}});

function stroke(): {kind:"path";value:PdfEvaluatedPath}{return {kind:"path",value:{segments:[{kind:"move",x:0,y:0},{kind:"line",x:100,y:0}],strokeColor:{r:0,g:0,b:0},strokeWidth:2}};}
async function consume(operation:Extract<PdfPaintOperation,{kind:"path"}>,options:Parameters<typeof encodeSvgPathPaintChunks>[2]={}){let total=0;for await(const bytes of encodeSvgPathPaintChunks(operation,100,options))total+=bytes.length;return total;}
it("charges complete paint markup against the output budget",async()=>{const operation=stroke(),length=await consume(operation);expect(await consume(operation,{maxOutputBytes:length,chunkBytes:1})).toBe(length);await expect(consume(operation,{maxOutputBytes:length-1})).rejects.toMatchObject({code:"E_LIMIT"});});
it.each([1024,4096])("streams %i generated dash entries under sink backpressure",async count=>{let reads=0,pending=0;const operation=stroke();operation.value={...operation.value,storedDash:{position:0,length:count,total:count,storage:{allocate(){throw Error("read only");},async write(){throw Error("read only");},async read(position,length){expect(pending).toBe(0);expect(length).toBeLessThanOrEqual(4096);expect(position+length).toBeLessThanOrEqual(count*8);reads++;const data=new Uint8Array(length),view=new DataView(data.buffer);for(let i=0;i<length;i+=8)view.setFloat64(i,1,true);return data;}}}};let total=0;for await(const bytes of encodeSvgPathPaintChunks(operation,100,{chunkBytes:31})){expect(bytes.buffer.byteLength).toBeLessThanOrEqual(31);pending=bytes.length;await Promise.resolve();total+=pending;pending=0;}expect(total).toBeGreaterThan(count*2);expect(reads).toBe(count/512*2);});
it("admits dash limits before reads and preserves source failures",async()=>{let reads=0;const reason=new Error("source failed"),operation=stroke();operation.value={...operation.value,storedDash:{position:0,length:100,total:100,storage:{allocate(){return 0;},async write(){},async read(){reads++;throw reason;}}}};await expect(consume(operation,{maxDashEntries:99})).rejects.toMatchObject({code:"E_LIMIT"});expect(reads).toBe(0);await expect(consume(operation)).rejects.toBe(reason);expect(reads).toBe(1);});
it("interrupts zero-dash contour expansion and supports early return",async()=>{const operation=stroke();operation.value={...operation.value,segments:[{kind:"move",x:0,y:0},{kind:"line",x:100000,y:0}],dashArray:[0,1],lineCap:1};const controller=new AbortController(),reason=new Error("cancel paint"),iterator=encodeSvgPathPaintChunks(operation,100,{signal:controller.signal,chunkBytes:32});expect((await iterator.next()).done).toBe(false);controller.abort(reason);await expect(iterator.next()).rejects.toBe(reason);const second=encodeSvgPathPaintChunks(operation,100);await second.next();await second.return();expect((await second.next()).done).toBe(true);});
it.each([{scale:0},{chunkBytes:0},{maxSegments:-1},{maxDashEntries:NaN},{maxOutputBytes:-1}])("rejects invalid paint options %j",async options=>{await expect(consume(stroke(),options)).rejects.toBeInstanceOf(RangeError);});
