import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
const scope = import.meta.dirname;
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const admit = (file, size, digest) => { const stat = fs.lstatSync(file); assert(stat.isFile() && stat.size === size && size <= 131072); const bytes = fs.readFileSync(file); assert.equal(sha(bytes), digest); return bytes; };
const packet = JSON.parse(admit(`${scope}/PACKET.json`, 20152, '86721fa44a10c997abd2fbeb56673cacf6221c5d2f9830c40c3682af777928ca'));
const previous = packet.preimportFiles;
const file = `${scope}/preimport.mjs`; const stat = fs.lstatSync(file); assert(stat.isFile() && stat.size < 32768);
const body = fs.readFileSync(file);
packet.preimportFiles = [{ path: fs.realpathSync(file), bytes: body.length, sha256: sha(body) }];
packet.previousUnexecutedProtocol = { packetSha256: '86721fa44a10c997abd2fbeb56673cacf6221c5d2f9830c40c3682af777928ca', helper: previous, correction: 'prior roles must be retired; helper appends its observed process.pid rather than requiring advance knowledge of its PID; no runtime execution or test rescore' };
packet.slots.knownStartsBeforePublication.rule = '6..26 actually observed retired prior starts plus this executing helper self-observation=7..27; coordinator observes helper exit/close before publication; no intervening OS starts';
packet.preimportCommand = { executable: packet.node.path, argv: [file, `${scope}/FINAL-PACKET.json`, { slot: 'finalPacketSha256', source: 'FINAL-RECEIPT.json.sha256' }, { slot: 'finalPacketBytes', source: 'FINAL-RECEIPT.json.bytes', type: 'positive decimal' }, { slot: 'freshRootGrantSha256', type: 'sha256' }, { slot: 'freshRootGrantBytes', type: 'positive decimal' }, { slot: 'observedPriorLedgerSha256', type: 'sha256' }, { slot: 'observedPriorLedgerBytes', type: 'positive decimal' }], capture: packet.slots.preimportCapture, cwd: packet.runtimeCommand.cwd, login: false, authority: 'SOURCE/DATA metadata check only; no automatic launch; authenticate helper bytes externally BEFORE Node entry' };
for (const entry of [...packet.publisherFiles, packet.preimportFiles]) admit(entry.path, entry.bytes, entry.sha256);
for (const entry of [packet.publisherBinding, packet.publisherPreseal, packet.runtimePreseal]) admit(entry.path, entry.bytes, entry.sha256);
for (const slot of packet.absentSlots) assert.equal(fs.existsSync(slot), false);
packet.finalAbsentCheckUTC = new Date().toISOString();
packet.preparationKnownRoles = { completedAtThisCheck: 15, finalPublicationGitRolesReserved: 2, maximumAfterCommit: 17, grantLimit: 20, peakKnown: 2, actualCalls: 0, fullCensus: 'UNOBSERVED', note: 'final two Git status/close outcomes are captured externally; reservation is not a preclaimed measurement' };
packet.preimportExecution = 'UNRUN; syntax checked only, no fabricated admission-control success';
const bytes = Buffer.from(JSON.stringify(packet, null, 2) + '\n');
fs.writeFileSync(`${scope}/FINAL-PACKET.json`, bytes, { flag: 'wx' });
const receipt = { path: `${scope}/FINAL-PACKET.json`, bytes: bytes.length, sha256: sha(bytes), issuedUTC: packet.issuedUTC, latestStartUTC: packet.latestStartUTC, expiresUTC: packet.expiresUTC, publisherBinding: packet.publisherBinding, publisherPreseal: packet.publisherPreseal, helper: packet.preimportFiles[0], actualAuthority: false, preparationElapsedSeconds: (Date.now() - Date.parse(packet.issuedUTC)) / 1000 };
assert(receipt.preparationElapsedSeconds < 420, 'Publication margin');
fs.writeFileSync(`${scope}/FINAL-RECEIPT.json`, JSON.stringify(receipt, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify(receipt));
