import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const own=path.dirname(fileURLToPath(import.meta.url));
const root='/Users/kjopek/Workspace/safe-bash';
const relativeAuthor='tests/shell/pipestatus-author-20260829/preexec-v1';
const author=root+'/'+relativeAuthor;
const sourceCommit='e7701a7a5d480c8e9851d035a6e7e71107652bfa';
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function read(filename,maximum=2097152){const stat=fs.lstatSync(filename);assert.ok(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=maximum);const bytes=fs.readFileSync(filename);assert.equal(bytes.length,stat.size);return bytes;}
function committed(name){const child=spawnSync('/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false','show',sourceCommit+':'+relativeAuthor+'/'+name],{cwd:root,encoding:null,maxBuffer:1048576});if(child.stderr?.length)process.stderr.write(child.stderr);assert.equal(child.status,0);assert.ok(child.stdout.length<1048576);const live=read(author+'/'+name);assert.ok(live.equals(child.stdout));return live;}
const checked=[];
async function pin(row){assert.equal(typeof row.path,'string');assert.ok(path.isAbsolute(row.path));const size=row.bytes??row.size;assert.ok(Number.isSafeInteger(size)&&size>=0);assert.match(row.sha256,/^[a-f0-9]{64}$/);const before=fs.lstatSync(row.path);assert.ok(before.isFile()&&!before.isSymbolicLink());assert.equal(before.size,size);if(typeof row.mode==='number')assert.equal(before.mode&4095,row.mode);const digest=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(row.path,{highWaterMark:65536}))digest.update(chunk);assert.equal(digest.digest('hex'),row.sha256);const after=fs.lstatSync(row.path);assert.equal(after.ino,before.ino);assert.equal(after.dev,before.dev);assert.equal(after.size,before.size);assert.equal(after.mtimeMs,before.mtimeMs);checked.push({path:row.path,bytes:size,sha256:row.sha256});}
const expectedNames=['PIPE_BOOTSTRAP_SHA','PIPE_GRANT','PIPE_GRANT_BYTES','PIPE_GRANT_SHA256','PIPE_SEAL','PIPE_SEAL_BYTES','PIPE_SEAL_SHA256'].sort();
function assignments(text){const names=[...text.matchAll(/\b(PIPE_[A-Z0-9_]+)=/g)].map(match=>match[1]).sort();assert.deepEqual(names,expectedNames);return names;}
const valid=expectedNames.map(name=>name+'=x').join(' ');assignments(valid);
const controls=[];
for(const [id,text]of [['M01-missing',expectedNames.filter(name=>name!=='PIPE_GRANT_SHA256').map(name=>name+'=x').join(' ')],['M02-extra',valid+' PIPE_EXTRA9=x'],['M03-duplicate',valid+' PIPE_SEAL_SHA256=x']]){assert.throws(()=>assignments(text),assert.AssertionError);controls.push({id,pass:true});}
const results=[];
const sealBytes=read(author+'/SEAL-v2.json');assert.equal(sealBytes.length,795793);assert.equal(hash(sealBytes),'f61b8fb41db61be3ed89fba296f5cbb9a6e8b4c80dd019202b065fe4f5a093d5');const seal=JSON.parse(sealBytes);
assert.equal(hash(read(path.resolve(own,'../PUBLICATION.json'))),'69ff0c8283f0cfebdde478b7ba3d251ab43022c9c68a433542c38de7c8ab61b3');
const bindingBytes=committed('BINDINGS-window-v1.json');const bindings=JSON.parse(bindingBytes);
const rows=[];function collect(value){if(!value||typeof value!=='object')return;if(typeof value.path==='string'&&typeof value.sha256==='string'&&Number.isSafeInteger(value.bytes??value.size))rows.push(value);for(const child of Object.values(value))if(child&&typeof child==='object')collect(child);}collect(bindings);
const unique=new Map(rows.map(row=>[row.path,row]));for(const row of [...seal.files,seal.archive,seal.node])unique.set(row.path,row);
for(const row of unique.values())await pin(row);
for(const required of [seal.node.path,seal.archive.path,'/bin/zsh','/usr/bin/shasum'])assert.ok(checked.some(row=>row.path===required),'missing pin '+required);
assert.equal(seal.sources.length,307);assert.equal(seal.archive.sha256,'6c60e2d766fa675b7972afdc0eb6f5304f99231abceff1daf5cb196b897346a5');results.push({id:'D01',pass:true,identityRecords:checked.length});
const commandBytes=committed('COMMAND-window-v1.txt');assert.equal(commandBytes.length,689);assert.equal(hash(commandBytes),'ecc2df67bf1cb05656014e3aa8f0c6c4c334545c7fea3faec1049cde3dc8e5d8');const command=commandBytes.toString();const terminal='exec /bin/zsh '+author+'/launch-v2.sh';assert.ok(command.trimEnd().endsWith(terminal));assert.equal(command.split(terminal).length,2);assignments(command);assert.ok(fs.readFileSync(author+'/launch-v2.sh','utf8').trimEnd().split('\n').at(-1).startsWith('exec "$NODE"'));results.push({id:'D02',pass:true,outerTerminalExec:true,exactSevenNames:expectedNames});
const grantBytes=read(author+'/GRANT-window-v1.template.json');assert.equal(grantBytes.length,247);assert.equal(hash(grantBytes),'72dcd3a7baf8bf0bd3da30752cd0639f154fae3975a7a532c743ca4700d2c04b');const grant=JSON.parse(grantBytes);assert.deepEqual(Object.keys(grant).sort(),['action','sealSha256','rootReceipt','started','deadline'].sort());assert.equal(grant.action,'execute-pipestatus-78-v1');assert.equal(grant.sealSha256,hash(sealBytes));assert.ok(!/^[a-f0-9]{40}$/.test(grant.rootReceipt));results.push({id:'D03',pass:true,inactiveTemplate:true});
const slots=[seal.actualRoot,seal.actualRoot+'-outer',seal.actualRoot+'.startup.stdout',seal.actualRoot+'.startup.stderr',seal.actualRoot+'.node.sha256'];for(const filename of slots){let absent=false;try{fs.lstatSync(filename);}catch(error){if(error.code==='ENOENT')absent=true;else throw error;}assert.equal(absent,true,'used slot '+filename);}results.push({id:'D04',pass:true,absentSlots:slots});
const latest=Date.parse('2026-08-29T16:55:00.000Z'),expiry=Date.parse('2026-08-29T17:25:00.000Z'),now=Date.now();assert.equal(grant.started,latest);assert.equal(grant.deadline,expiry);assert.equal(expiry-latest,1800000);assert.ok(now<=latest);assert.ok(now+1800000<=expiry);const admission=fs.readFileSync(author+'/admission.mjs','utf8');assert.ok(admission.includes('deadline-started !== 1800000'));assert.ok(admission.includes('deadline-180000'));results.push({id:'D05',pass:true,utc:new Date(now).toISOString(),latestStart:new Date(latest).toISOString(),absoluteExpiry:new Date(expiry).toISOString(),full1800Headroom:true});
const report={verdict:'ACCEPT_PROSPECTIVE_DELTA_NO_ACTIVATION',sourceCommit,results,controls,checked,priorFailure:'02b521dfa7cf28fc5cfbeb3fc8d422324715eece preserved exit1; no rescore',priorHoldPreserved:true,prior20ControlsNotRerun:true,helperSha256:hash(read(fileURLToPath(import.meta.url))),commandTemplateSha256:hash(commandBytes),command,grantTemplateSha256:hash(grantBytes),sealSha256:hash(sealBytes),bindingSha256:hash(bindingBytes),qualification:'512MiB sampled/quiescent logical work after install closure, between cases and final; not prewrite work enforcement/native peak/RSS/atomic snapshot/OSquota. Capture prewrite caps unchanged; detected excess STOP.',caps:{knownOS:93,peak:3,seconds:1800,publicationReserveSeconds:180,captureBytes:100663296,sampledWorkBytes:536870912},reviewCaps:{knownRolesConservativeInclusive:11,maximum:16,peak:2},productCalls:0,Workers:0,grantCreated:false,actualGO:false};
fs.writeFileSync(own+'/RESULT.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});fs.copyFileSync(author+'/COMMAND-window-v1.txt',own+'/COMMAND.template.txt',fs.constants.COPYFILE_EXCL);
fs.writeFileSync(own+'/REPORT.md',`# Qualified prospective PIPESTATUS delta\n\nACCEPT DATA/profile delta at ${new Date(now).toISOString()}, NOT actual authority. Five binding checks plus three matcher negatives pass. Original02b521 exit1 and35f4cbe7/20-control HOLD evidence unchanged. V2 matcher admits digits but retains exact seven-name/duplicate checks. No product or prior-control rerun.\n\nSource ${sourceCommit}; unchanged executable seal ${hash(sealBytes)}; command689 bytes/SHA256 ${hash(commandBytes)}. ${checked.length} identity records freshly checked; package not decoded; tools streamed. Five unused paths checked by lstat, not future reservation.\n\nLatest start2026-08-29T16:55:00.000Z; absolute expiry2026-08-29T17:25:00.000Z. Actual integer started at dispatch; deadline=started+1800000<=expiry; reserve180 seconds publication. No sleep, later clock renewal, stale grant reuse or late launch. Latest-start remains ROOT orchestration constraint, not new owner field.\n\nROOT/author must create a fresh exclusive five-field grant action/sealSha256/rootReceipt/started/deadline with an actual durable40hex ROOT authorization; bind exact absolute grant path, byte count and SHA256 into command placeholders. Preserve fixed seal path795793/hash and bootstrap hash; use complete terminal-exec command with repo cwd/login:false. Recheck unused slots and time at activation. This review creates no grant and supplies no actualGO.\n\n93knownOS/peak3;1800seconds incl180publication;96MiB prewrite capture;512MiB ROOT-approved sampled/quiescent logical work only, excessSTOP. Not prewrite work enforcement, native peak, RSS, atomic snapshot or OS quota. No live cache polling added. H01/H07 SOURCE-only;78cells/81exec/3invoke and installed/moved behavior remain UNRUN.\n`,{flag:'wx'});
const relative=path.relative(root,own);for(const args of [['add','--',relative],['commit','--only','-m','test: qualify versioned PIPESTATUS window DATA continuation','--',relative],['status','--porcelain','--',relative],['rev-parse','HEAD']]){const child=spawnSync('/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false',...args],{cwd:root,stdio:['ignore',1,2]});assert.equal(child.status,0);}
console.log(JSON.stringify({utc:new Date().toISOString(),resultSha256:hash(read(own+'/RESULT.json')),verdict:report.verdict,checks:5,matcherControls:3,identities:checked.length,command,activeChildren:0}));
