import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import threads from 'node:worker_threads';
import {types} from 'node:util';
import {syncBuiltinESMExports} from 'node:module';
import childProcess from 'node:child_process';
import net from 'node:net';import http from 'node:http';import https from 'node:https';import dgram from 'node:dgram';
const configPath=fileURLToPath(new URL('../node-policy.json',import.meta.url));const stat=fs.lstatSync(configPath);if(!stat.isFile()||stat.size>16384)throw Error('Node policy input');
const config=JSON.parse(fs.readFileSync(configPath,'utf8'));const main=threads.isMainThread;const NativeWorker=threads.Worker;let count=0;
const keys=(value,names)=>{if(value===null||typeof value!=='object'||types.isProxy(value))throw Error('Node policy data record');const descriptors=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(descriptors).length!==names.length||names.some(name=>!Object.hasOwn(descriptors,name)||!Object.hasOwn(descriptors[name],'value')))throw Error('Node policy exact own keys');return descriptors;};
const log=event=>{const text=Buffer.from(JSON.stringify(event)+'\n');const fd=fs.openSync(config.log,'a');try{let offset=0;while(offset<text.length){const size=fs.writeSync(fd,text,offset,text.length-offset);if(size===0)throw Error('policy capture zero');offset+=size;}}finally{fs.closeSync(fd);}};
if(main)log({kind:'node-policy-bootstrap'});
threads.Worker=class extends NativeWorker{constructor(entry,options){
 if(!main)throw Error('nested application Worker refused');
 const target=fileURLToPath(entry);if(target!==config.workerEntry||fs.realpathSync(target)!==target)throw Error('unbound Node Worker entry');
 keys(options,['workerData','env','argv','stdout','stderr','resourceLimits']);keys(options.env,[]);
 if(!Array.isArray(options.argv)||options.argv.length!==0||Reflect.ownKeys(options.argv).length!==1||options.stdout!==true||options.stderr!==true)throw Error('Node Worker stdio/argv');
 keys(options.resourceLimits,['maxOldGenerationSizeMb','maxYoungGenerationSizeMb','codeRangeSizeMb','stackSizeMb']);
 for(const [key,value]of Object.entries({maxOldGenerationSizeMb:32,maxYoungGenerationSizeMb:8,codeRangeSizeMb:8,stackSizeMb:4}))if(options.resourceLimits[key]!==value)throw Error('Node Worker limits');
 keys(options.workerData,['request','entry','identity','sab']);const data=options.workerData;
 if(!config.adapters.includes(data.entry)||typeof data.identity!=='string'||!types.isSharedArrayBuffer(data.sab)||data.sab.byteLength!==197056)throw Error('Node Worker authority/SAB');
 keys(data.request,['profile','selector','source','program','filename','cwd','argv','env','grants','limits']);
 if(data.request.profile!=='NP1-CJS-WRQ-L-SYNC-1'||typeof data.request.program!=='string'||Buffer.byteLength(data.request.program)>262144)throw Error('Node Worker request');
 if(++count>config.maximum)throw Error('Node Worker cumulative limit');
 super(entry,options);const identity=count;this.once('exit',code=>log({kind:'node-worker-exit',id:identity,code}));log({kind:'node-worker-create',id:identity,entry:target});
 }};
const denied=()=>{throw Error('NODE_PUBLIC_NO_SUBPROCESS_OR_NETWORK');};
for(const key of ['spawn','spawnSync','exec','execSync','execFile','execFileSync','fork'])childProcess[key]=denied;
for(const target of [net,http,https])for(const key of ['connect','createConnection','createServer','request','get'])if(key in target)target[key]=denied;
dgram.createSocket=denied;globalThis.fetch=denied;syncBuiltinESMExports();
