import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const profile=path.resolve('tests/compatibility/bash-ere-native-reference-20260829/preflight-v2'),own=profile+'/actual-v1',directory=profile+'/materialized';
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const ensure=(value,reason)=>{if(!value)throw Error(reason);};
function read(filename,pin){const fd=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const stat=fs.fstatSync(fd);ensure(stat.isFile()&&stat.nlink===1&&stat.size<=1048576,'FILE_TYPE_SIZE');if(pin?.mode!==undefined)ensure((stat.mode&511)===pin.mode,'FILE_MODE');if(pin?.bytes!==undefined)ensure(stat.size===pin.bytes,'FILE_SIZE');const bytes=fs.readFileSync(fd),after=fs.fstatSync(fd);ensure(bytes.length===stat.size&&stat.ino===after.ino&&stat.size===after.size&&stat.mtimeMs===after.mtimeMs,'READ_RACE');if(pin?.sha256)ensure(hash(bytes)===pin.sha256,'HASH');return bytes;}finally{fs.closeSync(fd);}}
const observationBytes=read(own+'/OBSERVATIONS.json',{sha256:'d77e2767f6b36a9ec710224ef31faa53ec388304b5616a4818e18657bf1cb274'}),observed=JSON.parse(observationBytes);
const check=()=>ensure(Date.now()<=observed.actualDeadline,'INCLUSIVE_DEADLINE');check();
ensure(observed.allObservationsQualified&&observed.qualificationErrors.length===0&&observed.observations.length===12&&observed.results.completed===12,'QUALIFICATION');
const root=observed.root;const expectedFiles=new Set(observed.files.map(item=>item.path)),expectedDirectories=new Set(observed.directories.map(item=>item.path));let observedFileCount=0,observedDirectoryCount=0;
function verifyRuntime(absolute,relative=''){for(const name of fs.readdirSync(absolute).sort()){const filename=absolute+'/'+name,rel=relative?relative+'/'+name:name,stat=fs.lstatSync(filename);ensure(!stat.isSymbolicLink(),'RUNTIME_SYMLINK');if(stat.isDirectory()){ensure(expectedDirectories.has(rel),'NEW_RUNTIME_DIRECTORY');observedDirectoryCount++;verifyRuntime(filename,rel);}else{ensure(expectedFiles.has(rel),'NEW_RUNTIME_FILE');const pin=observed.files.find(item=>item.path===rel),bytes=read(filename,pin);ensure(read(own+'/runtime/'+rel,{bytes:pin.bytes,mode:384,sha256:pin.sha256}).equals(bytes),'COPY_BYTES');observedFileCount++;}check();}}
verifyRuntime(root);ensure(observedFileCount===expectedFiles.size&&observedDirectoryCount===expectedDirectories.size,'RUNTIME_MEMBERSHIP');
const sealBytes=read(directory+'/PRESEAL.json',{sha256:'211483cbe1b12ad505345da5396a227c7da9931743d035ed365f7cc74bb4d457'}),source=JSON.parse(sealBytes);for(const item of source.files)read(directory+'/'+item.path,item);
const tools=JSON.parse(read(directory+'/TOOLS.json',source.files.find(item=>item.path==='TOOLS.json'))),admission=await import('../materialized/admission.mjs');const toolAfter=[];for(const pin of [...tools.toolPins,tools.environmentLauncher,tools.wrapperTool]){admission.pinned(pin.path,pin);toolAfter.push({path:pin.path,bytes:pin.bytes,mode:pin.mode,sha256:pin.sha256,at:new Date().toISOString()});check();}
const files=[];let workBytes=0,adminCaptureBytes=0;function inventory(absolute,relative=''){for(const name of fs.readdirSync(absolute).sort()){const filename=absolute+'/'+name,rel=relative?relative+'/'+name:name;if(['raw/seal.stdout','raw/seal.stderr'].includes(rel))continue;const stat=fs.lstatSync(filename);ensure(!stat.isSymbolicLink(),'PUBLICATION_SYMLINK');if(stat.isDirectory())inventory(filename,rel);else{const bytes=read(filename);files.push({path:rel,bytes:bytes.length,mode:stat.mode&511,sha256:hash(bytes)});workBytes+=bytes.length;if(rel.startsWith('raw/'))adminCaptureBytes+=bytes.length;}check();}}
inventory(own);ensure(workBytes+observed.runtimeBytes<134217728&&adminCaptureBytes+observed.runtimeBytes<33554432,'STORAGE_CAP');
const report={schema:'ere12-actual-final-seal-v1',at:new Date().toISOString(),files,observationManifestSha256:hash(observationBytes),presealSha256:hash(sealBytes),toolAfter,runtimeMembership:{files:observedFileCount,directories:observedDirectoryCount,bytes:observed.runtimeBytes},workBytesBeforeSeal:workBytes,adminCaptureBytes,combinedObservedCaptureBytes:adminCaptureBytes+observed.runtimeBytes,knownDirectStartsIncludingCommit:35,conservativeExecutableRoleCharge:36,knownPeak:3,nativeCases:12,semanticPassCount:null,observationsQualified:12,qualificationErrors:[],ownerToolExit:'reported 0; transcript reference in TOOL-RETURN.json',allKnownProcessesRetired:true,sourceAndRuntimeIntegrityAfter:true,actualDeadline:observed.actualDeadline,attempt:'CONSUMED_NO_RETRY',next:'independent artifact audit and ROOT R01 adjudication'};
check();const bytes=Buffer.from(JSON.stringify(report,null,2)+'\n'),fd=fs.openSync(own+'/FINAL-SEAL.json',fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,0o600);try{fs.writeFileSync(fd,bytes);check();fs.fsyncSync(fd);}finally{fs.closeSync(fd);}check();console.log(JSON.stringify({finalSealSha256:hash(bytes),observationsSha256:hash(observationBytes),runtimeFiles:observedFileCount,runtimeDirectories:observedDirectoryCount,runtimeBytes:observed.runtimeBytes,workBytesBeforeSeal:workBytes,combinedCaptureBytes:report.combinedObservedCaptureBytes,knownDirectStarts:35,conservativeRoleCharge:36,at:report.at,deadline:report.actualDeadline}));
