import * as fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
const [repoArgument, ownArgument] = process.argv.slice(2);
assert(process.argv.length === 4);
const repo = fs.realpathSync(repoArgument), own = fs.realpathSync(ownArgument), prior = path.dirname(own);
assert(own === path.join(repo, 'tests/compatibility/final-composition-readiness-20260829/reconciliation-v2'));
assert(fs.fstatSync(1).isFile() && fs.fstatSync(2).isFile());
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const objectHash = (kind, bytes) => crypto.createHash('sha1').update(Buffer.from(kind + ' ' + bytes.length + '\0')).update(bytes).digest('hex');
const order = (left, right) => Buffer.compare(Buffer.from(left, 'utf8'), Buffer.from(right, 'utf8'));
function read(filename) { const before = fs.lstatSync(filename); assert(before.isFile() && before.size <= 16777216); const bytes = fs.readFileSync(filename), after = fs.lstatSync(filename); assert.equal(before.ino, after.ino); assert.equal(before.mtimeMs, after.mtimeMs); assert.equal(bytes.length, before.size); return bytes; }
function row(filename) { const bytes = read(filename); return { path: filename, bytes: bytes.length, mode: fs.lstatSync(filename).mode & 511, sha256: sha(bytes) }; }
function json(name, value) { const bytes = Buffer.from(JSON.stringify(value, null, 2) + '\n'); assert(bytes.length <= 16777216); fs.writeFileSync(path.join(own, name), bytes, { flag: 'wx', mode: 0o444 }); return row(path.join(own, name)); }
const oldRaw = read(path.join(prior, 'FINAL-COMPOSITION.json'));
assert.equal(sha(oldRaw), '2253d8b49e5d5122416fb736a4dfd876d50ffdbfcd19709dbbb30e4fd4113f83');
const old = JSON.parse(oldRaw), baselineRaw = read(path.join(repo, old.baseline.path)); assert.equal(sha(baselineRaw), old.baseline.sha256);
const baseline = JSON.parse(baselineRaw); assert.equal(baseline.inputs.length, 309);
const acceptedReadme = baseline.inputs.find(item => item.path === 'README.md');
const inputs = old.actualWorkingTreeUnion.rows.map(item => item.path === 'README.md' ? { path: item.path, mode: acceptedReadme.mode, blob: acceptedReadme.blob, bytes: acceptedReadme.bytes, sha256: acceptedReadme.sha256, origins: [{ feature: 'ROOT_SELECTED_ACCEPTED_PUBLIC309_README', baseline: baseline.computedTree, blob: acceptedReadme.blob }], actualWorkingPresent: true } : item).sort((left, right) => order(left.path, right.path));
assert.equal(inputs.length, 323); assert.equal(new Set(inputs.map(item => item.path)).size, 323);
const requests = [...new Set([baseline.priorTreeWitnesses.blob, ...baseline.inputs.map(item => item.blob), ...inputs.map(item => item.blob)])];
const outputFd = fs.openSync(path.join(own, 'objects.stdout'), 'wx'), errorFd = fs.openSync(path.join(own, 'objects.stderr'), 'wx');
const child = spawnSync('/usr/bin/git', ['cat-file', '--batch'], { cwd: repo, env: { PATH: '/usr/bin:/bin', HOME: repo, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', GIT_OPTIONAL_LOCKS: '0' }, input: requests.join('\n') + '\n', stdio: ['pipe', outputFd, errorFd], timeout: 60000 });
fs.closeSync(outputFd); fs.closeSync(errorFd); assert.equal(child.status, 0);
const capture = read(path.join(own, 'objects.stdout')), objects = new Map(); let offset = 0;
for (const identity of requests) { const end = capture.indexOf(10, offset), [actual, kind, sizeText] = capture.subarray(offset, end).toString().split(' '), size = Number(sizeText); assert.equal(actual, identity); assert.equal(kind, 'blob'); assert(Number.isSafeInteger(size) && size <= 16777216); const bytes = capture.subarray(end + 1, end + 1 + size); assert.equal(objectHash(kind, bytes), identity); objects.set(identity, bytes); offset = end + size + 2; } assert.equal(offset, capture.length);
const witnessesRaw = objects.get(baseline.priorTreeWitnesses.blob); assert.equal(sha(witnessesRaw), baseline.priorTreeWitnesses.sha256); assert.equal(witnessesRaw.length, baseline.priorTreeWitnesses.bytes);
const witnesses = new Map();
for (const item of [...JSON.parse(witnessesRaw), ...baseline.reconstructedTrees]) { const bytes = Buffer.from(item.base64, 'base64'); assert.equal(objectHash('tree', bytes), item.oid); witnesses.set(item.oid, bytes); }
function entries(bytes) { const rows = []; let cursor = 0; while (cursor < bytes.length) { const blank = bytes.indexOf(32, cursor), nul = bytes.indexOf(0, blank); assert(blank > cursor && nul > blank && nul + 21 <= bytes.length); const mode = bytes.subarray(cursor, blank).toString(), nameBytes = bytes.subarray(blank + 1, nul), name = nameBytes.toString(); assert(Buffer.from(name).equals(nameBytes) && !name.includes('/')); rows.push({ mode, name, blob: bytes.subarray(nul + 1, nul + 21).toString('hex') }); cursor = nul + 21; } return rows; }
const wholeRoot = witnesses.get(baseline.computedTree); assert(wholeRoot); assert.equal(objectHash('tree', wholeRoot), '3adc676a0ab638c9788ef007e465931d65d2c6fe');
let selectedPathChecks = 0;
for (const item of baseline.inputs) { let tree = baseline.computedTree, leaf; const parts = item.path.split('/'); for (let index = 0; index < parts.length; index++) { const bytes = witnesses.get(tree); assert(bytes, 'missing selected-path tree witness'); leaf = entries(bytes).find(entry => entry.name === parts[index]); assert(leaf); if (index < parts.length - 1) { assert.equal(leaf.mode, '40000'); tree = leaf.blob; } } assert.equal(leaf.blob, item.blob); assert.equal(leaf.mode, item.mode); const bytes = objects.get(item.blob); assert.equal(sha(bytes), item.sha256); assert.equal(bytes.length, item.bytes); selectedPathChecks++; }
function projection(rows) { const root = new Map(); for (const item of rows) { const components = item.path.split('/'); let directory = root; for (const name of components.slice(0, -1)) { if (!directory.has(name)) directory.set(name, new Map()); directory = directory.get(name); } directory.set(components.at(-1), item); } function encode(directory) { const selected = [...directory.entries()].sort(([left, leftValue], [right, rightValue]) => order(left + (leftValue instanceof Map ? '/' : ''), right + (rightValue instanceof Map ? '/' : ''))); const body = Buffer.concat(selected.map(([name, value]) => Buffer.concat([Buffer.from((value instanceof Map ? '40000' : value.mode) + ' ' + name + '\0', 'utf8'), Buffer.from(value instanceof Map ? encode(value) : value.blob, 'hex')]))); return objectHash('tree', body); } return encode(root); }
const baselineProjection = projection(baseline.inputs); assert.equal(baselineProjection, 'c5e49e70c295d7e354eba53d1a91141ad701e3f6');
const rootEntries = entries(wholeRoot), selectedTop = new Set(baseline.inputs.map(item => item.path.split('/')[0]));
const visitedTrees = [...witnesses].map(([identity, bytes]) => { const rows = entries(bytes), keys = rows.map(item => item.name + (item.mode === '40000' ? '/' : '')); return { identity, bytes: bytes.length, gitOrder: keys.every((key, index) => !index || order(keys[index - 1], key) < 0) }; });
assert(visitedTrees.every(item => item.gitOrder));
const differences = [];
for (const item of inputs) { const bytes = objects.get(item.blob); assert(bytes); assert.equal(sha(bytes), item.sha256); assert.equal(bytes.length, item.bytes); const current = read(path.join(repo, item.path)); if (sha(current) !== item.sha256) differences.push({ path: item.path, selectedSha256: item.sha256, currentSha256: sha(current), reason: item.path === 'README.md' ? 'ROOT selected accepted README; current unreviewed README retained untouched' : 'Working source changed after prior readiness; WAIT_PIPESTATUS gate remains closed' }); }
const reconciliation = json('TREE-RECONCILIATION.json', { wholeRepositoryTree: baseline.computedTree, wholeRootBytes: wholeRoot.length, wholeRootSha256: sha(wholeRoot), rootEntries, nonBuildRootEntries: rootEntries.filter(item => !selectedTop.has(item.name)), selectedPathChecks, witnessCount: witnesses.size, allWitnessTreesHashAndGitOrderVerified: true, baselineBuildInputProjectionTree: baselineProjection, explanation: 'The original root preserves non-shipping repository entries; the reviewer rebuilt only the 309 build inputs. Different pathname domains, not corrupt input bytes or an ordering disagreement.', encoding: { names: 'UTF-8, exact byte round-trip, slash separates tree levels', row: 'ASCII octal mode + ASCII space + UTF-8 basename + NUL + raw 20-byte SHA1 object ID', directoryMode: '40000', fileMode: '100644 as individually bound', order: 'unsigned UTF-8 basename bytes, compare directory names with trailing slash (Git tree ordering)', identity: 'SHA1(ASCII tree + space + decimal byte count + NUL + concatenated entry bytes)', inputList: 'full repository-relative UTF-8 pathname byte ordering; JSON.stringify of exact input rows for canonicalRowsSha256' }, preservedFailure: '../resolution.stderr', priorError: 'Reviewer compared a full-repository derived root with a selected-build-input projection' });
const candidate = json('CANDIDATE-INPUTS.json', { status: 'PROVISIONAL_WAIT_PIPESTATUS_CAUSE_NOT_FINAL_FREEZE', sourceCount: inputs.length, selectedReadme: { blob: acceptedReadme.blob, bytes: acceptedReadme.bytes, sha256: acceptedReadme.sha256 }, buildInputProjectionTree: projection(inputs), canonicalRowsSha256: sha(Buffer.from(JSON.stringify(inputs))), inputs, excludedTrackedPaths: old.trackedOutsideRequestedUnion, excludedCount: old.trackedOutsideRequestedUnion.length, workingDifferences: differences, noWorkingFilesChanged: true, fullRepositoryTreeClaim: false });
const producerRoot = path.join(repo, 'tests/compatibility/bash-ere-core-transport-rebind-20260829');
const producerSealRaw = read(path.join(producerRoot, 'author-v3/PRESEAL.json')); assert.equal(sha(producerSealRaw), 'f4c0bf3bc9b79c1e68d01c846291a3476fc78c4df57832c64937875ebe4a6975');
const producerSeal = JSON.parse(producerSealRaw), typeRaw = read(path.join(producerRoot, 'author-v3/TYPE-TOOLS.json')), typePin = producerSeal.files.find(item => item.path === 'TYPE-TOOLS.json'); assert.equal(sha(typeRaw), typePin.sha256);
const types = JSON.parse(typeRaw); assert.equal(types.rows.length, 115);
for (const item of types.rows) for (const filename of [item.origin, item.path]) { const actual = row(filename); assert.equal(actual.bytes, item.size); assert.equal(actual.mode, item.mode); assert.equal(actual.sha256, item.sha256); }
const tools = json('TYPE-AND-TOOL-BINDINGS.json', { typedFiles: 115, typedBytes: types.bytes, packages: types.packages, typedRows: types.rows, sourceTypeManifest: row(path.join(producerRoot, 'author-v3/TYPE-TOOLS.json')), exactExistingProducerPreseal: row(path.join(producerRoot, 'author-v3/PRESEAL.json')), tools: producerSeal.tools, fullToolManifest: row(path.join(producerRoot, 'COMPOSITION.json')), userConfig: row(path.join(producerRoot, 'user.npmrc')), globalConfig: row(path.join(producerRoot, 'global.npmrc')), toolQualification: '115 type files reauthenticated now at origin and isolated copy; Node/TypeScript/npm reuse exact prior pins and require contemporary verification at future launch; none executed', dependenciesAdded: 0 });
const future = '/private/tmp/safe-bash-final-composition-20260829', node = producerSeal.commands.compiler.executable;
const procedure = json('PROCEDURE.json', { status: 'READY_PROCEDURE_ONLY_WAIT_PIPESTATUS', candidate, tools, reconciliation, gates: ['Plato exact PIPESTATUS 78-cell/exit2 assertion cause and ROOT candidate verdict required before final input freeze', 'If candidate source changes, regenerate selected input/tool bindings; do not bless prior PIPESTATUS bytes by these hashes', 'Fresh ROOT build authorization and unchanged input/tool admission required before executing any command'], finalFreezeAuthorized: false, buildAuthorized: false, productAuthorized: false, outputRoot: future, sourceRoot: future + '/source', materialize: 'Only the 323 explicitly authenticated input rows; accepted README from its pinned Git blob; exclude 40 tracked extras without deleting or editing them', environment: { ...producerSeal.env, HOME: future + '/home', TMPDIR: future + '/tmp', npm_config_cache: future + '/cache' }, commands: { compiler: { executable: node, cwd: future + '/source', args: [producerSeal.commands.compiler.args[0], '-p', future + '/source/tsconfig.build.json', '--typeRoots', types.typeRoots], maximumInvocations: 1, requiredExit: 0 }, pack: { executable: node, cwd: future + '/source', args: [producerSeal.commands.pack.args[0], 'pack', '--offline', '--ignore-scripts', '--json', '--userconfig=' + path.join(producerRoot, 'user.npmrc'), '--globalconfig=' + path.join(producerRoot, 'global.npmrc'), '--pack-destination=' + future + '/package'], maximumInvocations: 1, requiresCompilerExitZero: true } }, artifactAdmission: { perDataFileMaximum: 16777216, noInheritedOutputCounts: true, completeEmitAndShippingInventoryRequired: true, archiveAndReceiptCommittedBeforeDecode: true, sameAuthenticatedBufferDecode: true }, noNewDependency: true });
const workflowPath = 'tests/integration/agent-bash-coherent-author-20260829/v2/workflows.mjs', workflow = read(path.join(repo, workflowPath)).toString();
const smoke = json('SMOKE-PROPOSAL.json', { status: 'UNRUN_FUTURE_PRODUCT_AUTHORITY_REQUIRED', source: row(path.join(repo, workflowPath)), selectedIds: ['C01','C02','C07','C12','C13','C14'], caseCount: 6, layouts: ['source-built','installed','physically-moved'], prospectiveObservations: 18, cases: [{ id: 'C01', covers: 'Public root/node export equality, explicit opt-in, default80 inventory, inert provider' }, { id: 'C02', covers: 'Strict shell quoting/conditional/printf-to-cat pipeline' }, { id: 'C07', covers: 'Memory FS and stdout/stderr redirection effects' }, { id: 'C12', covers: 'Mock curl redirect authorization, sensitive-header stripping, Memory FS output, disposal' }, { id: 'C13', covers: 'Public Git status/rev-parse/ls-files over ReadOnlyFileSystem, no repository mutation' }, { id: 'C14', covers: 'apply_patch through stdin, Memory FS effects, Git diff and preserved repository metadata' }], noNewCasesOrAssertions: true, noRealNetworkOrNativeOracle: true, noNodeEngineOrWorkers: true, noClaimAllCommandsOrFilesystems: true, excluded: ['Real/S3/WebDAV backend integration claims', 'Full public Node guest execution', 'Replacement for failed PIPESTATUS78 or CORE210'], existingRunnerCaution: 'Reuse existing public-API workflow bodies/fixture only; rebind source/package/grant to the eventual final candidate. Never execute the old runner with its hardcoded 3adc/1014 assumptions on a different package.' });
assert(workflow.includes("id === 'C01'") && workflow.includes("id === 'C14'"));
const files = fs.readdirSync(own).filter(name => fs.lstatSync(path.join(own, name)).isFile()).map(name => row(path.join(own, name)));
const bytes = files.reduce((sum, item) => sum + item.bytes, 0), captured = files.filter(item => /\.(stdout|stderr)$/.test(item.path)).reduce((sum, item) => sum + item.bytes, 0);
assert(bytes + 16777216 < 134217728 && captured + 16777216 < 25165824);
const receipt = json('RECEIPT.json', { at: new Date().toISOString(), status: 'RECONCILIATION_AND_PROCEDURE_READY_WAIT_PIPESTATUS', candidate, tools, reconciliation, procedure, smoke, helperFiles: 1, helperInvocations: 1, child: { executable: '/usr/bin/git', args: ['cat-file','--batch'], pid: child.pid, exit: child.status, signal: child.signal, capturedBytes: capture.length }, knownStartsThroughHelper: 12, maximumKnownStarts: 24, conservativePeak: 3, maximumPeak: 3, capturedBytes: captured, retainedLogicalBytes: bytes, publicationReserve: 16777216, captureMaximum: 25165824, workMaximum: 134217728, deadline: '2026-08-29T16:57:51Z', campaignEndpoint: '2026-08-29T18:02:36Z', priorFailuresPreserved: ['c314acb2 canonicalization/refused-helper evidence', '58ba544 TS2688 and failed emits', 'PIPESTATUS78 aggregate exit2 assertions; exact cause pending Plato'], product: 0, Workers: 0, compiler: 0, npm: 0, installs: 0, noFinalFreeze: true, noWorkingSourceEdits: true, exclusions: ['Git internal physical storage', 'allocated disk blocks', 'RSS'] });
console.log(JSON.stringify({ status: 'READY_WAIT_PIPESTATUS', baselineWholeTree: baseline.computedTree, baselineProjection, nonBuildRootNames: rootEntries.filter(item => !selectedTop.has(item.name)).map(item => item.name), candidateTree: projection(inputs), candidateInputsSha256: candidate.sha256, candidateCanonicalRowsSha256: sha(Buffer.from(JSON.stringify(inputs))), inputs: inputs.length, typedFiles: types.rows.length, excluded: old.trackedOutsideRequestedUnion.length, workingDifferences: differences, receiptSha256: receipt.sha256, candidate, receipt, knownStartsThroughHelper: 12, retainedBytes: bytes, capturedBytes: captured }));
