// Generated by scripts/generate-inventories.mjs; add one declarative descriptor file.
import type { CommandDescriptor } from "./descriptor.js";
import { freezeDescriptor } from "./descriptor.js";
import { csvclean } from "./commands/csvclean.js";
import { csvcut } from "./commands/csvcut.js";
import { csvformat } from "./commands/csvformat.js";
import { csvgrep } from "./commands/csvgrep.js";
import { csvjoin } from "./commands/csvjoin.js";
import { csvjson } from "./commands/csvjson.js";
import { csvlook } from "./commands/csvlook.js";
import { csvpy } from "./commands/csvpy.js";
import { csvsort } from "./commands/csvsort.js";
import { csvsql } from "./commands/csvsql.js";
import { csvstack } from "./commands/csvstack.js";
import { csvstat } from "./commands/csvstat.js";
import { in2csv } from "./commands/in2csv.js";
import { sql2csv } from "./commands/sql2csv.js";
export const commands: readonly CommandDescriptor[] = Object.freeze([csvclean, csvcut, csvformat, csvgrep, csvjoin, csvjson, csvlook, csvpy, csvsort, csvsql, csvstack, csvstat, in2csv, sql2csv].map(freezeDescriptor));
