// Generated by scripts/generate-inventories.mjs; add one declarative descriptor file.
import type { DatabaseDialectDescriptor } from "./databases/descriptor.js";
import { freezeDescriptor } from "./descriptor.js";
import { generic } from "./databases/generic.js";
import { mssql } from "./databases/mssql.js";
import { mysql } from "./databases/mysql.js";
import { oracle } from "./databases/oracle.js";
import { postgresql } from "./databases/postgresql.js";
import { sqlite } from "./databases/sqlite.js";
export const databases: readonly DatabaseDialectDescriptor[] = Object.freeze([generic, mssql, mysql, oracle, postgresql, sqlite].map(freezeDescriptor));
