// Generated by scripts/generate-inventories.mjs; add one declarative descriptor file.
import type { FormatDescriptor } from "./formats/descriptor.js";
import { freezeDescriptor } from "./descriptor.js";
import { csv } from "./formats/csv.js";
import { dbf } from "./formats/dbf.js";
import { fixed } from "./formats/fixed.js";
import { geojson } from "./formats/geojson.js";
import { json } from "./formats/json.js";
import { ndjson } from "./formats/ndjson.js";
import { xls } from "./formats/xls.js";
import { xlsx } from "./formats/xlsx.js";
export const formats: readonly FormatDescriptor[] = Object.freeze([csv, dbf, fixed, geojson, json, ndjson, xls, xlsx].map(freezeDescriptor));
