// Generated by scripts/generate-inventories.mjs; add one declarative descriptor file.
import type { SqlTransportProfile } from "./sql-transports/descriptor.js";
import { freezeDescriptor } from "./descriptor.js";
import { mariadb } from "./sql-transports/mariadb.js";
import { mariadb_mariadb } from "./sql-transports/mariadb_mariadb.js";
import { mssql } from "./sql-transports/mssql.js";
import { mssql_mssql } from "./sql-transports/mssql_mssql.js";
import { mysql } from "./sql-transports/mysql.js";
import { mysql_mysql2 } from "./sql-transports/mysql_mysql2.js";
import { oracle } from "./sql-transports/oracle.js";
import { oracle_oracledb } from "./sql-transports/oracle_oracledb.js";
import { postgresql } from "./sql-transports/postgresql.js";
import { postgresql_pg } from "./sql-transports/postgresql_pg.js";
export const sqlTransportProfiles: readonly SqlTransportProfile[] = Object.freeze([mariadb, mariadb_mariadb, mssql, mssql_mssql, mysql, mysql_mysql2, oracle, oracle_oracledb, postgresql, postgresql_pg].map(freezeDescriptor));
