// Generated by scripts/imagemagick-metadata.py. ImageMagick Studio LLC; see COPYING.ImageMagick and NOTICE.
export const imageMagickOptions: Readonly<Record<string, { arity: number; flags: string; source: string }>> = {
  "+alpha": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:625"
  },
  "-alpha": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:626"
  },
  "+background": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:627"
  },
  "-background": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:628"
  },
  "+format": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:629"
  },
  "-format": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:630"
  },
  "-quiet": {
    "arity": 0,
    "flags": "GlobalOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:631"
  },
  "+quiet": {
    "arity": 0,
    "flags": "GlobalOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:632"
  },
  "-regard-warnings": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:633"
  },
  "+regard-warnings": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:634"
  },
  "+repage": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:635"
  },
  "-repage": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:636"
  },
  "+size": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:637"
  },
  "-size": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:638"
  },
  "+virtual-pixel": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:639"
  },
  "-virtual-pixel": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:640"
  },
  "+blur": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:641"
  },
  "-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:642"
  },
  "+reshape": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:643"
  },
  "-reshape": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:644"
  },
  "+resize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:645"
  },
  "-resize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:646"
  },
  "(": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:647"
  },
  ")": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:648"
  },
  "{": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:649"
  },
  "}": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:650"
  },
  "--": {
    "arity": 1,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:651"
  },
  "+adaptive-blur": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:652"
  },
  "-adaptive-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:653"
  },
  "+adaptive-resize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:654"
  },
  "-adaptive-resize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:655"
  },
  "+adaptive-sharpen": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:656"
  },
  "-adaptive-sharpen": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:657"
  },
  "-adjoin": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:658"
  },
  "+adjoin": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:659"
  },
  "+affine": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:660"
  },
  "-affine": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:661"
  },
  "+affinity": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:662"
  },
  "-affinity": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:663"
  },
  "+mattecolor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:664"
  },
  "-mattecolor": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:665"
  },
  "+annotate": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:666"
  },
  "-annotate": {
    "arity": 2,
    "flags": "SimpleOperatorFlag | AlwaysInterpretArgsFlag",
    "source": "MagickCore/option.c:667"
  },
  "-antialias": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:668"
  },
  "+antialias": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:669"
  },
  "-append": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:670"
  },
  "+append": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:671"
  },
  "+attenuate": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:672"
  },
  "-attenuate": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:673"
  },
  "+authenticate": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:674"
  },
  "-authenticate": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:675"
  },
  "+auto-gamma": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:676"
  },
  "-auto-gamma": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:677"
  },
  "+auto-level": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:678"
  },
  "-auto-level": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:679"
  },
  "+auto-orient": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:680"
  },
  "-auto-orient": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:681"
  },
  "+auto-threshold": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:682"
  },
  "-auto-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:683"
  },
  "+average": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:684"
  },
  "-average": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:685"
  },
  "+backdrop": {
    "arity": 0,
    "flags": "NonMagickOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:686"
  },
  "-backdrop": {
    "arity": 1,
    "flags": "NonMagickOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:687"
  },
  "+bench": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:688"
  },
  "-bench": {
    "arity": 1,
    "flags": "GenesisOptionFlag",
    "source": "MagickCore/option.c:689"
  },
  "+bias": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:690"
  },
  "-bias": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:691"
  },
  "+bilateral-blur": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:692"
  },
  "-bilateral-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:693"
  },
  "-black-point-compensation": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:694"
  },
  "+black-point-compensation": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:695"
  },
  "+black-threshold": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:696"
  },
  "-black-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:697"
  },
  "+blend": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:698"
  },
  "-blend": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:699"
  },
  "+blue-primary": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:700"
  },
  "-blue-primary": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:701"
  },
  "-blue-shift": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:702"
  },
  "+blue-shift": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:703"
  },
  "+border": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:704"
  },
  "-border": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:705"
  },
  "+bordercolor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:706"
  },
  "-bordercolor": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:707"
  },
  "+borderwidth": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:708"
  },
  "-borderwidth": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:709"
  },
  "+box": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:710"
  },
  "-box": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:711"
  },
  "+brightness-contrast": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:712"
  },
  "-brightness-contrast": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:713"
  },
  "+cache": {
    "arity": 0,
    "flags": "GlobalOptionFlag",
    "source": "MagickCore/option.c:714"
  },
  "-cache": {
    "arity": 1,
    "flags": "GlobalOptionFlag",
    "source": "MagickCore/option.c:715"
  },
  "+canny": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:716"
  },
  "-canny": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:717"
  },
  "+caption": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:718"
  },
  "-caption": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:719"
  },
  "+cdl": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:720"
  },
  "-cdl": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:721"
  },
  "+channel": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:722"
  },
  "-channel": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:723"
  },
  "-channel-fx": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:724"
  },
  "+charcoal": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:725"
  },
  "-charcoal": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:726"
  },
  "+chop": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:727"
  },
  "-chop": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:728"
  },
  "+clahe": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:729"
  },
  "-clahe": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:730"
  },
  "+clamp": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:731"
  },
  "-clamp": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:732"
  },
  "-clip": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:733"
  },
  "+clip": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:734"
  },
  "+clip-mask": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:735"
  },
  "-clip-mask": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:736"
  },
  "-clip-path": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:737"
  },
  "+clip-path": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:738"
  },
  "+clone": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:739"
  },
  "-clone": {
    "arity": 1,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:740"
  },
  "+clut": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:741"
  },
  "-clut": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:742"
  },
  "+coalesce": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:743"
  },
  "-coalesce": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:744"
  },
  "+colorize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:745"
  },
  "-colorize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:746"
  },
  "+colormap": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:747"
  },
  "-colormap": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:748"
  },
  "+color-matrix": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:749"
  },
  "-color-matrix": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:750"
  },
  "+colors": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:751"
  },
  "-colors": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:752"
  },
  "+colorspace": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:753"
  },
  "-colorspace": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:754"
  },
  "+color-threshold": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:755"
  },
  "-color-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:756"
  },
  "-combine": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:757"
  },
  "+combine": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:758"
  },
  "+comment": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:759"
  },
  "-comment": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:760"
  },
  "+compare": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:761"
  },
  "-compare": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:762"
  },
  "+complex": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:763"
  },
  "-complex": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:764"
  },
  "+compose": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:765"
  },
  "-compose": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:766"
  },
  "+composite": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:767"
  },
  "-composite": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:768"
  },
  "+compress": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:769"
  },
  "-compress": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:770"
  },
  "+concurrent": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:771"
  },
  "-concurrent": {
    "arity": 0,
    "flags": "GenesisOptionFlag",
    "source": "MagickCore/option.c:772"
  },
  "+connected-components": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:773"
  },
  "-connected-components": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:774"
  },
  "-contrast": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:775"
  },
  "+contrast": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:776"
  },
  "+contrast-stretch": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:777"
  },
  "-contrast-stretch": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:778"
  },
  "+convolve": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:779"
  },
  "-convolve": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:780"
  },
  "+copy": {
    "arity": 2,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:781"
  },
  "-copy": {
    "arity": 2,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:782"
  },
  "+crop": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:783"
  },
  "-crop": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:784"
  },
  "+cycle": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:785"
  },
  "-cycle": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:786"
  },
  "+debug": {
    "arity": 0,
    "flags": "GlobalOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:787"
  },
  "-debug": {
    "arity": 1,
    "flags": "GlobalOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:788"
  },
  "+decipher": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:789"
  },
  "-decipher": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:790"
  },
  "+deconstruct": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:791"
  },
  "-deconstruct": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:792"
  },
  "-define": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:793"
  },
  "+define": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:794"
  },
  "+delay": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:795"
  },
  "-delay": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:796"
  },
  "+delete": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:797"
  },
  "-delete": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:798"
  },
  "+density": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:799"
  },
  "-density": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:800"
  },
  "+depth": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:801"
  },
  "-depth": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:802"
  },
  "+descend": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:803"
  },
  "-descend": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:804"
  },
  "+deskew": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:805"
  },
  "-deskew": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:806"
  },
  "+despeckle": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:807"
  },
  "-despeckle": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:808"
  },
  "+direction": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:809"
  },
  "-direction": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:810"
  },
  "+displace": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:811"
  },
  "-displace": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:812"
  },
  "-display": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:813"
  },
  "+display": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:814"
  },
  "+dispose": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:815"
  },
  "-dispose": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:816"
  },
  "+dissimilarity-threshold": {
    "arity": 0,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:817"
  },
  "-dissimilarity-threshold": {
    "arity": 1,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:818"
  },
  "+dissolve": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:819"
  },
  "-dissolve": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:820"
  },
  "-distort": {
    "arity": 2,
    "flags": "SimpleOperatorFlag | AlwaysInterpretArgsFlag",
    "source": "MagickCore/option.c:821"
  },
  "+distort": {
    "arity": 2,
    "flags": "SimpleOperatorFlag | AlwaysInterpretArgsFlag",
    "source": "MagickCore/option.c:822"
  },
  "+dither": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | QuantizeInfoOptionFlag",
    "source": "MagickCore/option.c:823"
  },
  "-dither": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | QuantizeInfoOptionFlag",
    "source": "MagickCore/option.c:824"
  },
  "+draw": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:825"
  },
  "-draw": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:826"
  },
  "+duplicate": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:827"
  },
  "-duplicate": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:828"
  },
  "-duration": {
    "arity": 1,
    "flags": "GenesisOptionFlag",
    "source": "MagickCore/option.c:829"
  },
  "+duration": {
    "arity": 1,
    "flags": "GenesisOptionFlag",
    "source": "MagickCore/option.c:830"
  },
  "+edge": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:831"
  },
  "-edge": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:832"
  },
  "+emboss": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:833"
  },
  "-emboss": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:834"
  },
  "+encipher": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:835"
  },
  "-encipher": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:836"
  },
  "+encoding": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:837"
  },
  "-encoding": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:838"
  },
  "+endian": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:839"
  },
  "-endian": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:840"
  },
  "+enhance": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:841"
  },
  "-enhance": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:842"
  },
  "+equalize": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:843"
  },
  "-equalize": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:844"
  },
  "+evaluate": {
    "arity": 2,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:845"
  },
  "-evaluate": {
    "arity": 2,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:846"
  },
  "+evaluate-sequence": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:847"
  },
  "-evaluate-sequence": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:848"
  },
  "-exit": {
    "arity": 0,
    "flags": "SpecialOptionFlag",
    "source": "MagickCore/option.c:849"
  },
  "+extent": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:850"
  },
  "-extent": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:851"
  },
  "+extract": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:852"
  },
  "-extract": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:853"
  },
  "+family": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:854"
  },
  "-family": {
    "arity": 1,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:855"
  },
  "+features": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:856"
  },
  "-features": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:857"
  },
  "-fft": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:858"
  },
  "+fft": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:859"
  },
  "+fill": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:860"
  },
  "-fill": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:861"
  },
  "+filter": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:862"
  },
  "-filter": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:863"
  },
  "+flatten": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:864"
  },
  "-flatten": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:865"
  },
  "+flip": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:866"
  },
  "-flip": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:867"
  },
  "-floodfill": {
    "arity": 2,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:868"
  },
  "+floodfill": {
    "arity": 2,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:869"
  },
  "+flop": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:870"
  },
  "-flop": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:871"
  },
  "+font": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:872"
  },
  "-font": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:873"
  },
  "+foreground": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:874"
  },
  "-foreground": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:875"
  },
  "+frame": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:876"
  },
  "-frame": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:877"
  },
  "+function": {
    "arity": 2,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:878"
  },
  "-function": {
    "arity": 2,
    "flags": "SimpleOperatorFlag | AlwaysInterpretArgsFlag",
    "source": "MagickCore/option.c:879"
  },
  "+fuzz": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:880"
  },
  "-fuzz": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:881"
  },
  "+fx": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | FireOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:882"
  },
  "-fx": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:883"
  },
  "-gamma": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:884"
  },
  "+gamma": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:885"
  },
  "+gaussian": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:886"
  },
  "-gaussian": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:887"
  },
  "+gaussian-blur": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:888"
  },
  "-gaussian-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:889"
  },
  "+geometry": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:890"
  },
  "-geometry": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:891"
  },
  "+gravity": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:892"
  },
  "-gravity": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:893"
  },
  "+grayscale": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:894"
  },
  "-grayscale": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:895"
  },
  "+green-primary": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:896"
  },
  "-green-primary": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:897"
  },
  "+hald-clut": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:898"
  },
  "-hald-clut": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:899"
  },
  "+highlight-color": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:900"
  },
  "-highlight-color": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:901"
  },
  "+hough-lines": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:902"
  },
  "-hough-lines": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:903"
  },
  "+icongeometry": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:904"
  },
  "-icongeometry": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:905"
  },
  "-iconic": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:906"
  },
  "+iconic": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:907"
  },
  "+identify": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:908"
  },
  "-identify": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:909"
  },
  "-ift": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:910"
  },
  "+ift": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:911"
  },
  "-immutable": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:912"
  },
  "+immutable": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:913"
  },
  "+implode": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:914"
  },
  "-implode": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:915"
  },
  "+insert": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:916"
  },
  "-insert": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:917"
  },
  "+illuminant": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:918"
  },
  "-illuminant": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:919"
  },
  "+integral": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:920"
  },
  "-integral": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:921"
  },
  "+intensity": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:922"
  },
  "-intensity": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:923"
  },
  "+intent": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:924"
  },
  "-intent": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:925"
  },
  "+interlace": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:926"
  },
  "-interlace": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:927"
  },
  "+interline-spacing": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:928"
  },
  "-interline-spacing": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:929"
  },
  "+interpolate": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:930"
  },
  "-interpolate": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:931"
  },
  "+interpolative-resize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:932"
  },
  "-interpolative-resize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:933"
  },
  "+interword-spacing": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:934"
  },
  "-interword-spacing": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:935"
  },
  "+kerning": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:936"
  },
  "-kerning": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:937"
  },
  "-kmeans": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:938"
  },
  "+kuwahara": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:939"
  },
  "-kuwahara": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:940"
  },
  "+label": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:941"
  },
  "-label": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:942"
  },
  "+lat": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:943"
  },
  "-lat": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:944"
  },
  "+layers": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:945"
  },
  "-layers": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:946"
  },
  "-level": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:947"
  },
  "+level": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:948"
  },
  "-level-colors": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:949"
  },
  "+level-colors": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:950"
  },
  "+limit": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:951"
  },
  "-limit": {
    "arity": 2,
    "flags": "GlobalOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:952"
  },
  "+linear-stretch": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:953"
  },
  "-linear-stretch": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:954"
  },
  "+liquid-rescale": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:955"
  },
  "-liquid-rescale": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:956"
  },
  "+list": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:957"
  },
  "-list": {
    "arity": 1,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:958"
  },
  "+local-contrast": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:959"
  },
  "-local-contrast": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:960"
  },
  "+log": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:961"
  },
  "-log": {
    "arity": 1,
    "flags": "GlobalOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:962"
  },
  "+loop": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:963"
  },
  "-loop": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:964"
  },
  "+lowlight-color": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:965"
  },
  "-lowlight-color": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:966"
  },
  "+magnify": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:967"
  },
  "-magnify": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:968"
  },
  "+map": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:969"
  },
  "-map": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:970"
  },
  "+mask": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:971"
  },
  "-mask": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:972"
  },
  "-matte": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:973"
  },
  "+matte": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:974"
  },
  "-maximum": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:975"
  },
  "+maximum": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:976"
  },
  "+mean-shift": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:977"
  },
  "-mean-shift": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:978"
  },
  "+median": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:979"
  },
  "-median": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:980"
  },
  "+metric": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:981"
  },
  "-metric": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:982"
  },
  "-minimum": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:983"
  },
  "+minimum": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:984"
  },
  "+mode": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:985"
  },
  "-mode": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:986"
  },
  "+modulate": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:987"
  },
  "-modulate": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:988"
  },
  "-moments": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:989"
  },
  "+moments": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:990"
  },
  "-monitor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:991"
  },
  "+monitor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:992"
  },
  "+monochrome": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:993"
  },
  "-monochrome": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:994"
  },
  "+morph": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:995"
  },
  "-morph": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:996"
  },
  "+morphology": {
    "arity": 2,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:997"
  },
  "-morphology": {
    "arity": 2,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:998"
  },
  "+mosaic": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:999"
  },
  "-mosaic": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1000"
  },
  "+motion-blur": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1001"
  },
  "-motion-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1002"
  },
  "+name": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1003"
  },
  "-name": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1004"
  },
  "+negate": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1005"
  },
  "-negate": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1006"
  },
  "-noise": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:1007"
  },
  "+noise": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1008"
  },
  "-noop": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:1009"
  },
  "+normalize": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1010"
  },
  "-normalize": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1011"
  },
  "-opaque": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1012"
  },
  "+opaque": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1013"
  },
  "+ordered-dither": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1014"
  },
  "-ordered-dither": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1015"
  },
  "+orient": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1016"
  },
  "-orient": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1017"
  },
  "+page": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1018"
  },
  "-page": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1019"
  },
  "+paint": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1020"
  },
  "-paint": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1021"
  },
  "+path": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1022"
  },
  "-path": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1023"
  },
  "+pause": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1024"
  },
  "-pause": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1025"
  },
  "-ping": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1026"
  },
  "+ping": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1027"
  },
  "+pointsize": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1028"
  },
  "-pointsize": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1029"
  },
  "+polaroid": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1030"
  },
  "-polaroid": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1031"
  },
  "+poly": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1032"
  },
  "-poly": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1033"
  },
  "+posterize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1034"
  },
  "-posterize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1035"
  },
  "+precision": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1036"
  },
  "-precision": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1037"
  },
  "+preview": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1038"
  },
  "-preview": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1039"
  },
  "+print": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1040"
  },
  "-print": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | AlwaysInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1041"
  },
  "+process": {
    "arity": 1,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1042"
  },
  "-process": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1043"
  },
  "+profile": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1044"
  },
  "-profile": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1045"
  },
  "+quality": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1046"
  },
  "-quality": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1047"
  },
  "+quantize": {
    "arity": 0,
    "flags": "QuantizeInfoOptionFlag",
    "source": "MagickCore/option.c:1048"
  },
  "-quantize": {
    "arity": 1,
    "flags": "QuantizeInfoOptionFlag",
    "source": "MagickCore/option.c:1049"
  },
  "-raise": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1050"
  },
  "+raise": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1051"
  },
  "+random-threshold": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1052"
  },
  "-random-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1053"
  },
  "+range-threshold": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1054"
  },
  "-range-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1055"
  },
  "-read": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1056"
  },
  "+read-mask": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1057"
  },
  "-read-mask": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1058"
  },
  "+recolor": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1059"
  },
  "-recolor": {
    "arity": 1,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:1060"
  },
  "+red-primary": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1061"
  },
  "-red-primary": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1062"
  },
  "+region": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1063"
  },
  "-region": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1064"
  },
  "+remap": {
    "arity": 0,
    "flags": "ListOperatorFlag | NeverInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1065"
  },
  "-remap": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1066"
  },
  "+remote": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1067"
  },
  "-remote": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1068"
  },
  "-render": {
    "arity": 0,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1069"
  },
  "+render": {
    "arity": 0,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1070"
  },
  "+resample": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1071"
  },
  "-resample": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1072"
  },
  "-respect-parenthesis": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1073"
  },
  "+respect-parenthesis": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1074"
  },
  "-respect-parentheses": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1075"
  },
  "+respect-parentheses": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1076"
  },
  "+reverse": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1077"
  },
  "-reverse": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1078"
  },
  "+roll": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1079"
  },
  "-roll": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1080"
  },
  "+rotate": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1081"
  },
  "-rotate": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1082"
  },
  "-rotational-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1083"
  },
  "+sample": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1084"
  },
  "-sample": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1085"
  },
  "+sampling-factor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1086"
  },
  "-sampling-factor": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1087"
  },
  "-sans0": {
    "arity": 0,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1088"
  },
  "+sans0": {
    "arity": 0,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1089"
  },
  "+sans1": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1090"
  },
  "-sans1": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1091"
  },
  "-sans": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1092"
  },
  "+sans": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1093"
  },
  "-sans2": {
    "arity": 2,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1094"
  },
  "+sans2": {
    "arity": 2,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1095"
  },
  "+scale": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1096"
  },
  "-scale": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1097"
  },
  "+scene": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1098"
  },
  "-scene": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1099"
  },
  "+scenes": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1100"
  },
  "-scenes": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1101"
  },
  "+screen": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1102"
  },
  "-screen": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1103"
  },
  "-script": {
    "arity": 1,
    "flags": "SpecialOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1104"
  },
  "+seed": {
    "arity": 0,
    "flags": "GlobalOptionFlag",
    "source": "MagickCore/option.c:1105"
  },
  "-seed": {
    "arity": 1,
    "flags": "GlobalOptionFlag",
    "source": "MagickCore/option.c:1106"
  },
  "+segment": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1107"
  },
  "-segment": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1108"
  },
  "+selective-blur": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1109"
  },
  "-selective-blur": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1110"
  },
  "+separate": {
    "arity": 0,
    "flags": "DeprecateOptionFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1111"
  },
  "-separate": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1112"
  },
  "+sepia-tone": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1113"
  },
  "-sepia-tone": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1114"
  },
  "+set": {
    "arity": 1,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:1115"
  },
  "-set": {
    "arity": 2,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1116"
  },
  "+shade": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1117"
  },
  "-shade": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1118"
  },
  "+shadow": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1119"
  },
  "-shadow": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1120"
  },
  "+shared-memory": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1121"
  },
  "-shared-memory": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1122"
  },
  "+sharpen": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1123"
  },
  "-sharpen": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1124"
  },
  "+shave": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1125"
  },
  "-shave": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1126"
  },
  "+shear": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1127"
  },
  "-shear": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1128"
  },
  "-sigmoidal-contrast": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1129"
  },
  "+sigmoidal-contrast": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1130"
  },
  "+silent": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1131"
  },
  "-silent": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1132"
  },
  "+similarity-threshold": {
    "arity": 0,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1133"
  },
  "-similarity-threshold": {
    "arity": 1,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1134"
  },
  "+sketch": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1135"
  },
  "-sketch": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1136"
  },
  "-smush": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1137"
  },
  "+smush": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1138"
  },
  "+snaps": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1139"
  },
  "-snaps": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1140"
  },
  "+solarize": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1141"
  },
  "-solarize": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1142"
  },
  "+sort-pixels": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1143"
  },
  "-sort-pixels": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1144"
  },
  "+sparse-color": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1145"
  },
  "-sparse-color": {
    "arity": 2,
    "flags": "SimpleOperatorFlag | AlwaysInterpretArgsFlag",
    "source": "MagickCore/option.c:1146"
  },
  "+splice": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1147"
  },
  "-splice": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1148"
  },
  "+spread": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1149"
  },
  "-spread": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1150"
  },
  "+statistic": {
    "arity": 2,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1151"
  },
  "-statistic": {
    "arity": 2,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1152"
  },
  "+stegano": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1153"
  },
  "-stegano": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1154"
  },
  "+stereo": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1155"
  },
  "-stereo": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1156"
  },
  "+stretch": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1157"
  },
  "-stretch": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1158"
  },
  "+strip": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1159"
  },
  "-strip": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1160"
  },
  "+stroke": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1161"
  },
  "-stroke": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1162"
  },
  "-strokewidth": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1163"
  },
  "+strokewidth": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1164"
  },
  "+style": {
    "arity": 0,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1165"
  },
  "-style": {
    "arity": 1,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1166"
  },
  "-subimage": {
    "arity": 0,
    "flags": "ListOperatorFlag",
    "source": "MagickCore/option.c:1167"
  },
  "-subimage-search": {
    "arity": 0,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1168"
  },
  "+subimage-search": {
    "arity": 0,
    "flags": "NonMagickOptionFlag | ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1169"
  },
  "+swap": {
    "arity": 0,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1170"
  },
  "-swap": {
    "arity": 1,
    "flags": "ListOperatorFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1171"
  },
  "+swirl": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1172"
  },
  "-swirl": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1173"
  },
  "-synchronize": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1174"
  },
  "+synchronize": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1175"
  },
  "-taint": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1176"
  },
  "+taint": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1177"
  },
  "+text-font": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1178"
  },
  "-text-font": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1179"
  },
  "+texture": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1180"
  },
  "-texture": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1181"
  },
  "+threshold": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1182"
  },
  "-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1183"
  },
  "+thumbnail": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1184"
  },
  "-thumbnail": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1185"
  },
  "+tile": {
    "arity": 0,
    "flags": "DrawInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1186"
  },
  "-tile": {
    "arity": 1,
    "flags": "DrawInfoOptionFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1187"
  },
  "+tile-offset": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1188"
  },
  "-tile-offset": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1189"
  },
  "-tint": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1190"
  },
  "+tint": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1191"
  },
  "+title": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1192"
  },
  "-title": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1193"
  },
  "+transform": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1194"
  },
  "-transform": {
    "arity": 0,
    "flags": "ReplacedOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:1195"
  },
  "-transparent": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1196"
  },
  "+transparent": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1197"
  },
  "+transparent-color": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1198"
  },
  "-transparent-color": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1199"
  },
  "+transpose": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1200"
  },
  "-transpose": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1201"
  },
  "+transverse": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1202"
  },
  "-transverse": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1203"
  },
  "+treedepth": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1204"
  },
  "-treedepth": {
    "arity": 1,
    "flags": "QuantizeInfoOptionFlag",
    "source": "MagickCore/option.c:1205"
  },
  "+trim": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1206"
  },
  "-trim": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1207"
  },
  "+type": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:1208"
  },
  "-type": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | SimpleOperatorFlag",
    "source": "MagickCore/option.c:1209"
  },
  "+undercolor": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1210"
  },
  "-undercolor": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1211"
  },
  "-unique": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1212"
  },
  "+unique": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1213"
  },
  "+unique-colors": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1214"
  },
  "-unique-colors": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1215"
  },
  "+units": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1216"
  },
  "-units": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1217"
  },
  "+unsharp": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1218"
  },
  "-unsharp": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1219"
  },
  "+update": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1220"
  },
  "-update": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1221"
  },
  "+use-pixmap": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1222"
  },
  "-use-pixmap": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1223"
  },
  "-verbose": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1224"
  },
  "+verbose": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1225"
  },
  "+version": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1226"
  },
  "-version": {
    "arity": 0,
    "flags": "NoImageOperatorFlag",
    "source": "MagickCore/option.c:1227"
  },
  "+view": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1228"
  },
  "-view": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1229"
  },
  "+vignette": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1230"
  },
  "-vignette": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1231"
  },
  "+visual": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1232"
  },
  "-visual": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1233"
  },
  "+watermark": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1234"
  },
  "-watermark": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1235"
  },
  "+wave": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1236"
  },
  "-wave": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1237"
  },
  "+wavelet-denoise": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1238"
  },
  "-wavelet-denoise": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1239"
  },
  "+weight": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1240"
  },
  "-weight": {
    "arity": 1,
    "flags": "DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1241"
  },
  "+white-balance": {
    "arity": 0,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1242"
  },
  "-white-balance": {
    "arity": 0,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1243"
  },
  "+white-point": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1244"
  },
  "-white-point": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag",
    "source": "MagickCore/option.c:1245"
  },
  "+white-threshold": {
    "arity": 1,
    "flags": "DeprecateOptionFlag",
    "source": "MagickCore/option.c:1246"
  },
  "-white-threshold": {
    "arity": 1,
    "flags": "SimpleOperatorFlag",
    "source": "MagickCore/option.c:1247"
  },
  "+window": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1248"
  },
  "-window": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1249"
  },
  "+window-group": {
    "arity": 0,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1250"
  },
  "-window-group": {
    "arity": 1,
    "flags": "NonMagickOptionFlag",
    "source": "MagickCore/option.c:1251"
  },
  "+word-break": {
    "arity": 0,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1252"
  },
  "-word-break": {
    "arity": 1,
    "flags": "ImageInfoOptionFlag | DrawInfoOptionFlag",
    "source": "MagickCore/option.c:1253"
  },
  "-write": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1254"
  },
  "+write": {
    "arity": 1,
    "flags": "NoImageOperatorFlag | NeverInterpretArgsFlag | FireOptionFlag",
    "source": "MagickCore/option.c:1255"
  },
  "+write-mask": {
    "arity": 0,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1256"
  },
  "-write-mask": {
    "arity": 1,
    "flags": "SimpleOperatorFlag | NeverInterpretArgsFlag",
    "source": "MagickCore/option.c:1257"
  }
};
export const imageMagickGrammarRevision = "imagemagick-7.1.2-31-register-v1";
export const imageMagickReference = {
  "id": "22c4ee96b8b19a680c4867e1c28169d3c25beb3397be597daf3ecfe5328ded4e",
  "executables": {
    "Magick++-config": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/Magick++-config",
      "sha256": "4d8e41149adeee78e5b0d9b0837b21267671a5167bcd694e55b69186ea40b5ea",
      "kind": "build-helper"
    },
    "MagickCore-config": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/MagickCore-config",
      "sha256": "4c6c9229bc0659580902caa2c35084e870eb74d5601c40d5d0c37baf54b9bd93",
      "kind": "build-helper"
    },
    "MagickWand-config": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/MagickWand-config",
      "sha256": "bbdcde8b84720c839fd8b3535449d4b75b6fa464beade3ecd2427057bc73b4cf",
      "kind": "build-helper"
    },
    "animate": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/animate",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "compare": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/compare",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "composite": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/composite",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "conjure": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/conjure",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "convert": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/convert",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "display": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/display",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "identify": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/identify",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "import": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/import",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "magick": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/magick",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "magick-script": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/magick-script",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "mogrify": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/mogrify",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "montage": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/montage",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    },
    "stream": {
      "path": "/opt/homebrew/Cellar/imagemagick/7.1.2-31/bin/stream",
      "sha256": "d5a0dee6582f6843bf30fcf567febe993ad45eb53dcba108a0572d5f0d454a73",
      "kind": "media"
    }
  }
} as const;
