[loader]
".hbs" = "text"
".md" = "text"
".log" = "text"

[test]
preload = ["./tests/setup.ts"]
include = [
  "src/**/*.test.ts",
  "tests/helpers/**/*.test.ts",
  "tests/integration/**/*.test.ts",
  "scripts/screenshot.test.ts"
]
pathIgnorePatterns = [
  "e2e/**",
  "**/*.e2e.test.ts",
  "dist/**",
  "packages/**/dist/**"
]
