import { recalculateWorkbook } from "./evaluator.js";
import { expect, it } from "vitest";
import { dateFinanceFunctionDescriptors } from "./date-finance-function-descriptors.js";
import { dateFunctions } from "./functions/dates.js";
import { calendarFunctions } from "./functions/calendars.js";
import { financialFunctions, financialSpecialForms } from "./functions/financial.js";
import { derivativeFunctions } from "./functions/derivatives.js";
// Independent literal census captured from the authenticated released descriptors.
const released = [
  [
    "DATE",
    "fff",
    "fn-date"
  ],
  [
    "DATEVALUE",
    "f",
    "fn-date"
  ],
  [
    "DATEDIF",
    "ffs",
    "fn-date"
  ],
  [
    "DAY",
    "f",
    "fn-date"
  ],
  [
    "DAYS360",
    "ff|f",
    "fn-date"
  ],
  [
    "EDATE",
    "ff",
    "fn-date"
  ],
  [
    "EOMONTH",
    "f|f",
    "fn-date"
  ],
  [
    "HOUR",
    "f",
    "fn-date"
  ],
  [
    "MINUTE",
    "f",
    "fn-date"
  ],
  [
    "MONTH",
    "f",
    "fn-date"
  ],
  [
    "NETWORKDAYS",
    "ff|?A",
    "fn-date"
  ],
  [
    "NOW",
    "",
    "fn-date"
  ],
  [
    "ODF.TIME",
    "fff",
    "fn-date"
  ],
  [
    "SECOND",
    "f",
    "fn-date"
  ],
  [
    "TIME",
    "fff",
    "fn-date"
  ],
  [
    "TIMEVALUE",
    "f",
    "fn-date"
  ],
  [
    "TODAY",
    "",
    "fn-date"
  ],
  [
    "WEEKDAY",
    "f|f",
    "fn-date"
  ],
  [
    "WEEKNUM",
    "f|f",
    "fn-date"
  ],
  [
    "WORKDAY",
    "ff|?A",
    "fn-date"
  ],
  [
    "YEAR",
    "f",
    "fn-date"
  ],
  [
    "YEARFRAC",
    "ff|f",
    "fn-date"
  ],
  [
    "UNIX2DATE",
    "f",
    "fn-date"
  ],
  [
    "DATE2UNIX",
    "f",
    "fn-date"
  ],
  [
    "ISOWEEKNUM",
    "f",
    "fn-date"
  ],
  [
    "ISOYEAR",
    "f",
    "fn-date"
  ],
  [
    "DAYS",
    "ff",
    "fn-date"
  ],
  [
    "ACCRINT",
    "ffff|fffb",
    "fn-financial"
  ],
  [
    "ACCRINTM",
    "fff|ff",
    "fn-financial"
  ],
  [
    "AMORDEGRC",
    "fffffff",
    "fn-financial"
  ],
  [
    "AMORLINC",
    "fffffff",
    "fn-financial"
  ],
  [
    "COUPDAYBS",
    "fff|fb",
    "fn-financial"
  ],
  [
    "COUPDAYS",
    "fff|fb",
    "fn-financial"
  ],
  [
    "COUPDAYSNC",
    "fff|fb",
    "fn-financial"
  ],
  [
    "COUPNCD",
    "fff|fb",
    "fn-financial"
  ],
  [
    "COUPNUM",
    "fff|fb",
    "fn-financial"
  ],
  [
    "COUPPCD",
    "fff|fb",
    "fn-financial"
  ],
  [
    "CUMIPMT",
    "ffffff",
    "fn-financial"
  ],
  [
    "CUMPRINC",
    "ffffff",
    "fn-financial"
  ],
  [
    "DB",
    "ffff|f",
    "fn-financial"
  ],
  [
    "DDB",
    "ffff|f",
    "fn-financial"
  ],
  [
    "DISC",
    "ffff|f",
    "fn-financial"
  ],
  [
    "DOLLARDE",
    "ff",
    "fn-financial"
  ],
  [
    "DOLLARFR",
    "ff",
    "fn-financial"
  ],
  [
    "DURATION",
    "fffff|f",
    "fn-financial"
  ],
  [
    "EFFECT",
    "ff",
    "fn-financial"
  ],
  [
    "EURO",
    "s",
    "fn-financial"
  ],
  [
    "EUROCONVERT",
    "fss|bf",
    "fn-financial"
  ],
  [
    "FV",
    "fff|ff",
    "fn-financial"
  ],
  [
    "FVSCHEDULE",
    "fA",
    "fn-financial"
  ],
  [
    "G_DURATION",
    "fff",
    "fn-financial"
  ],
  [
    "INTRATE",
    "ffff|f",
    "fn-financial"
  ],
  [
    "IPMT",
    "ffff|ff",
    "fn-financial"
  ],
  [
    "IRR",
    "A|f",
    "fn-financial"
  ],
  [
    "ISPMT",
    "ffff",
    "fn-financial"
  ],
  [
    "MDURATION",
    "fffff|f",
    "fn-financial"
  ],
  [
    "MIRR",
    "Aff",
    "fn-financial"
  ],
  [
    "NOMINAL",
    "ff",
    "fn-financial"
  ],
  [
    "NPER",
    "fff|ff",
    "fn-financial"
  ],
  [
    "NPV",
    null,
    "fn-financial"
  ],
  [
    "ODDFPRICE",
    "fffffffff",
    "fn-financial"
  ],
  [
    "ODDFYIELD",
    "fffffffff",
    "fn-financial"
  ],
  [
    "ODDLPRICE",
    "ffffffff",
    "fn-financial"
  ],
  [
    "ODDLYIELD",
    "ffffffff",
    "fn-financial"
  ],
  [
    "PMT",
    "fff|ff",
    "fn-financial"
  ],
  [
    "PPMT",
    "ffff|ff",
    "fn-financial"
  ],
  [
    "PRICE",
    "ffffff|f",
    "fn-financial"
  ],
  [
    "PRICEDISC",
    "ffff|f",
    "fn-financial"
  ],
  [
    "PRICEMAT",
    "fffff|f",
    "fn-financial"
  ],
  [
    "PV",
    "fff|ff",
    "fn-financial"
  ],
  [
    "RATE",
    "fff|fff",
    "fn-financial"
  ],
  [
    "RRI",
    "fff",
    "fn-financial"
  ],
  [
    "RECEIVED",
    "ffff|f",
    "fn-financial"
  ],
  [
    "SLN",
    "fff",
    "fn-financial"
  ],
  [
    "SYD",
    "ffff",
    "fn-financial"
  ],
  [
    "TBILLEQ",
    "fff",
    "fn-financial"
  ],
  [
    "TBILLPRICE",
    "fff",
    "fn-financial"
  ],
  [
    "TBILLYIELD",
    "fff",
    "fn-financial"
  ],
  [
    "VDB",
    "fffff|ff",
    "fn-financial"
  ],
  [
    "XIRR",
    "AA|f",
    "fn-financial"
  ],
  [
    "XNPV",
    "fAA",
    "fn-financial"
  ],
  [
    "YIELD",
    "ffffff|f",
    "fn-financial"
  ],
  [
    "YIELDDISC",
    "ffff|f",
    "fn-financial"
  ],
  [
    "YIELDMAT",
    "fffff|f",
    "fn-financial"
  ],
  [
    "OPT_BS",
    "sfffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_DELTA",
    "sfffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_RHO",
    "sfffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_THETA",
    "sfffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_GAMMA",
    "fffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_VEGA",
    "fffff|f",
    "fn-derivatives"
  ],
  [
    "OPT_BS_CARRYCOST",
    "sfffff|f",
    "fn-derivatives"
  ],
  [
    "CUM_BIV_NORM_DIST",
    "fff",
    "fn-derivatives"
  ],
  [
    "OPT_GARMAN_KOHLHAGEN",
    "sffffff",
    "fn-derivatives"
  ],
  [
    "OPT_FRENCH",
    "sfffffff",
    "fn-derivatives"
  ],
  [
    "OPT_JUMP_DIFF",
    "sfffffff",
    "fn-derivatives"
  ],
  [
    "OPT_EXEC",
    "sfffffff",
    "fn-derivatives"
  ],
  [
    "OPT_BJER_STENS",
    "sffffff",
    "fn-derivatives"
  ],
  [
    "OPT_MILTERSEN_SCHWARTZ",
    "sfffffffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_BAW_AMER",
    "sffffff",
    "fn-derivatives"
  ],
  [
    "OPT_RGW",
    "fffffff",
    "fn-derivatives"
  ],
  [
    "OPT_FORWARD_START",
    "sfffffff",
    "fn-derivatives"
  ],
  [
    "OPT_TIME_SWITCH",
    "sfffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_SIMPLE_CHOOSER",
    "fffffff",
    "fn-derivatives"
  ],
  [
    "OPT_COMPLEX_CHOOSER",
    "fffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_ON_OPTIONS",
    "sffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_EXTENDIBLE_WRITER",
    "sffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_2_ASSET_CORRELATION",
    "sfffffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_EURO_EXCHANGE",
    "fffffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_AMER_EXCHANGE",
    "fffffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_SPREAD_APPROX",
    "sffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_FLOAT_STRK_LKBK",
    "sfffffff",
    "fn-derivatives"
  ],
  [
    "OPT_FIXED_STRK_LKBK",
    "sffffffff",
    "fn-derivatives"
  ],
  [
    "OPT_BINOMIAL",
    "ssffffff|f",
    "fn-derivatives"
  ],
  [
    "ASCENSIONTHURSDAY",
    "|f",
    "fn-christian-date"
  ],
  [
    "ASHWEDNESDAY",
    "|f",
    "fn-christian-date"
  ],
  [
    "EASTERSUNDAY",
    "|f",
    "fn-christian-date"
  ],
  [
    "GOODFRIDAY",
    "|f",
    "fn-christian-date"
  ],
  [
    "PENTECOSTSUNDAY",
    "|f",
    "fn-christian-date"
  ],
  [
    "HDATE",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "HDATE_HEB",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "HDATE_DAY",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "HDATE_MONTH",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "HDATE_YEAR",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "HDATE_JULIAN",
    "|fff",
    "fn-hebrew-date"
  ],
  [
    "DATE2HDATE",
    "|f",
    "fn-hebrew-date"
  ],
  [
    "DATE2HDATE_HEB",
    "|f",
    "fn-hebrew-date"
  ],
  [
    "DATE2JULIAN",
    "|f",
    "fn-hebrew-date"
  ]
] as const;
it("retains all released signatures and implementations", () => {
  const implementation = { ...dateFunctions, ...calendarFunctions, ...financialFunctions, ...financialSpecialForms, ...derivativeFunctions };
  expect(Object.keys(dateFinanceFunctionDescriptors).sort()).toEqual(released.map(row => row[0]).sort());
  expect(Object.keys(implementation).sort()).toEqual(released.map(row => row[0]).sort());
  for (const [name, signature, group] of released) expect(dateFinanceFunctionDescriptors[name]).toMatchObject({ signature, group });
});

it("rejects descriptor arity before evaluating arguments", () => {
  const context = { signal: new AbortController().signal, environment: { env: {}, locale: "C", timezone: "UTC" }, limits: { inputBytes: 100000, outputBytes: 100000, cells: 100, sheets: 10, operations: 100, workbookWork: 100000 }, own() {} };
  for (const [name, signature] of released) {
    if (signature === null) continue;
    const minimum = signature.split("|")[0]!.length, maximum = signature.split("|").join("").length;
    for (const length of [maximum + 1, ...(minimum ? [minimum - 1] : [])]) {
      const formula = `=${name}(${Array.from({ length }, () => "1/0").join(",")})`;
      const result = recalculateWorkbook({ sheets: [{ id: "s", name: "S", cells: [{ row: 0, column: 0, formula, value: { kind: "blank" }, formulaDirty: true }] }] }, context);
      expect(result.sheets[0]!.cells[0]!.value, name).toEqual({ kind: "error", value: "#N/A" });
    }
  }
});
