import {lstatSync,readFileSync,writeFileSync,readdirSync,createReadStream,realpathSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {admitGrant} from '../budget.mjs';
const own=fileURLToPath(new URL('.',import.meta.url));
const prepared=dirname(own.slice(0,-1));
const repo='/Users/kjopek/Workspace/safe-bash';
const profileHash='dbb576cdb97945543ef15cb02548f3cbe12875cbeab4bb01af2d60addf5dbffa';
const reviewCommit='2e6d59787df9d1949d9e342fbd2769cb76240651';
const reviewHash='39244351bc27769439f7f881cdeb6b68b92f694eb9f21c316a9f0eff44acea69';
const reviewPath=repo+'/tests/compatibility/bash-l02-followup-independent-20260829/r4/REVIEW-ACCEPTANCE.json';
const started=Date.now(),deadline=started+300000;
function clock(){if(Date.now()>deadline)throw Error('preparation deadline');}
function digest(bytes){return createHash('sha256').update(bytes).digest('hex');}
function read(path,max){clock();const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>max)throw Error('regular bounded input');const bytes=readFileSync(path);if(bytes.length!==stat.size)throw Error('changed size');return bytes;}
async function binding(path,max){clock();const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>max||realpathSync(path)!==path)throw Error('regular exact input');const hash=createHash('sha256');let bytes=0;for await(const chunk of createReadStream(path,{highWaterMark:65536})){clock();bytes+=chunk.length;if(bytes>stat.size)throw Error('growing input');hash.update(chunk);}if(bytes!==stat.size)throw Error('short input');return {path,size:bytes,mode:stat.mode&511,sha256:hash.digest('hex')};}
function absent(path){clock();try{lstatSync(path);}catch(reason){if(reason?.code==='ENOENT')return;throw reason;}throw Error('output already present '+path);}
function write(name,bytes,max){clock();if(bytes.length>max)throw Error('output capacity');writeFileSync(join(own,name),bytes,{flag:'wx'});return {path:join(own,name),size:bytes.length,sha256:digest(bytes)};}
const reviewBytes=read(reviewPath,1250);if(reviewBytes.length!==1250||digest(reviewBytes)!==reviewHash)throw Error('explicit review receipt binding');
const profileBytes=read(join(prepared,'EXECUTION-PRESEAL.json'),1048576);if(digest(profileBytes)!==profileHash)throw Error('profile binding');const profile=JSON.parse(profileBytes);
const inputs=[];for(const row of profile.inputs){const actual=await binding(row.path,160000000);if(actual.size!==row.size||actual.sha256!==row.sha256)throw Error('source/tool changed');inputs.push(actual);}
const inventoryBytes=read(join(prepared,'CASE-INVENTORY.json'),1048576);if(digest(inventoryBytes)!==profile.inventorySha256)throw Error('inventory binding');const inventory=JSON.parse(inventoryBytes);const expected=new Map(),directoryNames=new Map([['',new Set()]]);
for(const cell of inventory.cases)for(const row of cell.files){const name=cell.folder+'/'+row.path;if(expected.has(name)||name.split('/').some(part=>!part||part==='.'||part==='..'))throw Error('inventory path');expected.set(name,row);const components=name.split('/');let parent='';for(let index=0;index<components.length;index++){directoryNames.get(parent).add(components[index]);if(index<components.length-1){parent=parent?parent+'/'+components[index]:components[index];if(!directoryNames.has(parent))directoryNames.set(parent,new Set());}}}
if(expected.size!==390||directoryNames.size>500)throw Error('fixed manifest bounds');
const caseRoot=join(prepared,'CASES');const actualCases=[];let total=0;
for(const [name,pinned]of expected){const actual=await binding(join(caseRoot,name),2097152);if(actual.size!==pinned.size||actual.mode!==pinned.mode||actual.sha256!==pinned.sha256)throw Error('case changed');total+=actual.size;if(total>8388608)throw Error('case bytes');actualCases.push(actual);}
if(actualCases.length!==390||total!==1381586)throw Error('full case set');
const directoryChecks=[];for(const [name,names]of directoryNames){clock();const directory=join(caseRoot,name),stat=lstatSync(directory);if(!stat.isDirectory()||stat.isSymbolicLink()||realpathSync(directory)!==directory)throw Error('fixed directory identity');const actual=readdirSync(directory).sort(),pinned=[...names].sort();if(actual.length!==pinned.length||actual.some((value,index)=>value!==pinned[index]))throw Error('unexpected directory entry');directoryChecks.push({path:directory,entries:actual});}
const future=join(prepared,'FUTURE-ACTUAL-01');const futureStat=lstatSync(future);if(!futureStat.isDirectory()||futureStat.isSymbolicLink()||realpathSync(future)!==future||readdirSync(future).length)throw Error('future directory not empty');
const unused=[join(prepared,'ROOT-GRANT.json'),...['outer.stdout','outer.stderr','admin-outer.stdout','admin-outer.stderr','bootstrap.stdout','bootstrap.stderr','owner.stdout','owner.stderr','admin.stdout','admin.stderr','ACTIVATION.json','RUNTIME-RESULT.json','OUTER-CLOSE.json','RESULT.json','STOP.json','EMERGENCY.json'].map(name=>join(future,name))];for(const file of unused)absent(file);
const templateBytes=read(join(prepared,'GRANT-TEMPLATE.json'),8192);const grant=JSON.parse(templateBytes);const keys=['schema','authorized','profileSha256','runId','reviewCommit','reviewReceiptSha256','issuedAt','latestStartAt','expiresAt','cases','Workers','wallMilliseconds','knownOS','captureBytes','workingBytes'];if(JSON.stringify(Object.keys(grant))!==JSON.stringify(keys))throw Error('template exact keys');Object.assign(grant,{authorized:true,reviewCommit,reviewReceiptSha256:reviewHash,issuedAt:'2026-08-29T17:00:00.000Z',latestStartAt:'2026-08-29T17:15:00.000Z',expiresAt:'2026-08-29T17:25:00.000Z'});if(grant.schema!==2||grant.profileSha256!==profileHash||grant.runId!=='ERE-L02-FOLLOWUP-r4')throw Error('template identity');admitGrant(grant,profileHash,Date.parse(grant.issuedAt));admitGrant(grant,profileHash,Date.parse(grant.latestStartAt));if(Date.now()>Date.parse(grant.latestStartAt))throw Error('launch window elapsed');
const grantBytes=Buffer.from(JSON.stringify(grant)+'\n');if(grantBytes.length>4096)throw Error('grant bound');const grantHash=digest(grantBytes),base64=grantBytes.toString('base64');
const handoffBytes=read(join(prepared,'HANDOFF.md'),30000);const candidates=handoffBytes.toString().split('\n').filter(line=>line.startsWith('    exec /usr/bin/env -i ')&&line.includes('/activation.mjs '));if(candidates.length!==1)throw Error('reviewed command');const original=candidates[0].slice(4);if(original.split('ROOT_GRANT_BASE64').length!==2||original.split('ROOT_GRANT_SHA').length!==2||!original.includes(profileHash)||!original.includes(prepared+'/activation.mjs'))throw Error('two exact placeholders');const command='set -C\n'+original.replace('ROOT_GRANT_BASE64',base64).replace('ROOT_GRANT_SHA',grantHash)+'\n';
const outputs={grant:write('PENDING-GRANT.json',grantBytes,4096),base64:write('PENDING-GRANT.base64.data',Buffer.from(base64+'\n'),8192),command:write('ACTIVATION-COMMAND.sh.data',Buffer.from(command),16384)};
const receipt={schema:2,startedAt:new Date(started).toISOString(),completedAt:new Date().toISOString(),status:Date.now()<Date.parse(grant.issuedAt)?'PENDING_FUTURE_ISSUED_AT_NOT_ACTIVE':'PENDING_ROOT_FINAL_GO_NOT_DISPATCHED',reviewCommit,reviewReceipt:{path:reviewPath,size:1250,sha256:reviewHash},profileSha256:profileHash,inputs,caseInputs:actualCases,caseFiles:390,caseBytes:total,fixedDirectoryChecks:directoryChecks,recursiveDiscovery:false,unusedPaths:unused,futureDirectoryEmpty:true,outputs,commandSource:{path:join(prepared,'HANDOFF.md'),sha256:digest(handoffBytes)},helper:await binding(fileURLToPath(import.meta.url),100000),grantKeys:keys,validation:'Existing admitGrant validated at issuedAt and latestStartAt as DATA only; no activation authorization installed',startup:'RESERVED_POSTCHECK_NOT_PREWRITE_ENFORCED_NO_EOF_CENSUS',Git:'SHARED_INDEX_OBJECT_TEMP_PHYSICAL_STORAGE_EXCLUDED_TRUSTED_UNOBSERVED',actualWorkers:0,productImports:0,dispatch:false,preservedFailure:'ec5d57a0400058cfa8422881154055cf134d42d4'};write('BINDING-RECEIPT.json',Buffer.from(JSON.stringify(receipt,null,2)+'\n'),524288);console.log(JSON.stringify({status:receipt.status,startedAt:receipt.startedAt,completedAt:receipt.completedAt,grant:outputs.grant,base64:outputs.base64,command:outputs.command,caseFiles:390,caseBytes:total,dispatch:false}));
