import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root='/Users/kjopek/Workspace/safe-bash',scope=import.meta.dirname,base=path.dirname(scope),started=new Date().toISOString();
const sha=body=>crypto.createHash('sha256').update(body).digest('hex');
function admitted(filename,identity){const stat=fs.lstatSync(filename);assert.ok(stat.isFile()&&!stat.isSymbolicLink());assert.equal(stat.size,identity.bytes);const body=fs.readFileSync(filename);assert.equal(sha(body),identity.sha256);return body;}
let count=0;function git(args,input,maximum=1048576){const prefix=path.join(scope,'capture','git-'+count++),out=fs.openSync(prefix+'.stdout','wx'),err=fs.openSync(prefix+'.stderr','wx');let result;try{result=spawnSync('/usr/bin/git',args,{cwd:root,env:{PATH:'/usr/bin:/bin',GIT_OPTIONAL_LOCKS:'0'},input,stdio:[input?'pipe':'ignore',out,err],timeout:10000});}finally{fs.closeSync(out);fs.closeSync(err);}assert.equal(result.status,0);assert.equal(result.signal,null);assert.ok(fs.statSync(prefix+'.stdout').size<=maximum);fs.appendFileSync(path.join(scope,'capture/events.jsonl'),JSON.stringify({pid:result.pid,args,status:result.status,signal:result.signal})+'\n');return fs.readFileSync(prefix+'.stdout');}
git(['status','--porcelain=v1','-z','--untracked-files=normal','--',path.relative(root,scope)]);git(['diff','--cached','--name-only','-z']);
const stageACommit='ab976f5ee31d0a793d6016f13cc46e6960ace2aa';const fixtureCommit='955e7eb7d7f49feb4cf288fcb58a6ba6125073f0';
const names=git(['ls-tree','-r','--name-only','-z',stageACommit,'--','tests/integration/agent-bash-coherent-author-20260829/stage-a-r2'],undefined,131072).toString().split('\0').filter(Boolean);const candidates=names.filter(name=>name.endsWith('/PRESEAL.json'));assert.equal(candidates.length,1);
const tuples=[{role:'stageAProducerPreseal',commit:stageACommit,path:candidates[0],bytes:47291,sha256:'8acc5e35686a4fa20bf1f8a871b2c23edff4cb29b09a9b9f1848ffc1332006db'},{role:'workflowFixtureV4Preseal',commit:fixtureCommit,path:'tests/integration/agent-bash-coherent-author-20260829/v4/PRESEAL.json',bytes:8922,sha256:'4911f32f621e33adf8cacd0eabbc13b0644586fc3efd36ca42abf3c85765734c'}];
const query=tuples.map(row=>row.commit+':'+row.path).join('\n')+'\n';const metadata=git(['cat-file','--batch-check=%(objectname) %(objecttype) %(objectsize)'],query).toString().trim().split('\n');for(const[index,row]of tuples.entries()){const match=/^([0-9a-f]{40}) blob ([0-9]+)$/.exec(metadata[index]);assert.ok(match);assert.equal(Number(match[2]),row.bytes);row.blob=match[1];}
fs.writeFileSync(path.join(scope,'LOCATOR-IDENTITIES.json'),JSON.stringify({started,tuples},null,2)+'\n',{flag:'wx'});
const bodies=git(['cat-file','--batch'],query,60000);let offset=0;for(const row of tuples){const end=bodies.indexOf(10,offset);assert.equal(bodies.subarray(offset,end).toString(),`${row.blob} blob ${row.bytes}`);const body=bodies.subarray(end+1,end+1+row.bytes);assert.equal(sha(body),row.sha256);assert.equal(bodies[end+1+row.bytes],10);offset=end+row.bytes+2;fs.writeFileSync(path.join(scope,row.role+'.json'),body,{flag:'wx'});const parsed=JSON.parse(body);console.log(JSON.stringify({role:row.role,identity:row,keys:Object.keys(parsed),files:parsed.files??parsed.harnessFiles??parsed.harness??parsed.fixtures??parsed.fixtureFiles}));}assert.equal(offset,bodies.length);
const retained=JSON.parse(fs.readFileSync(path.join(base,'stage-b/RETAINED-SOURCES.json')));for(const row of retained.filter(row=>/\/(resources|loader)\.mjs$/.test(row.path))){const text=row.text??row.body;assert.equal(sha(Buffer.from(text)),row.sha256);console.log(JSON.stringify({role:'helper',...row}));}
const fixture=admitted(path.join(base,'v4/workflows.mjs'),{bytes:15763,sha256:'6d8a19854a6e96986013ed3d94ee15dd774e225259dea922bf4749799c60d89b'}).toString().split('\n');console.log(JSON.stringify({role:'scripts',lines:fixture.map((text,index)=>({line:index+1,text})).filter(row=>row.line<73||(row.line>79&&row.line<101)||(row.line>115&&row.line<128))}));
fs.writeFileSync(path.join(scope,'INSPECT.json'),JSON.stringify({started,finished:new Date().toISOString(),gitChildren:count,productImports:0},null,2)+'\n',{flag:'wx'});
