import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
type Case={row:number;body:string;member:string;text?:string;style?:string|null|undefined;expected?:number;invalidTable?:boolean;nativeCompanion?:boolean};
const cases:Case[]=[
 ...[['',null],['Foo',null],['','Bar'],['Foo','Bar']].map(([text,style],i)=>({row:772+i,body:'',member:'add_paragraph',text:text as string,style})),
 {row:776,body:'',member:'add_table'},
 {row:777,body:'<w:p><w:r><w:t>First authored block</w:t></w:r></w:p><w:tbl><w:tblPr/><w:tblGrid><w:gridCol/></w:tblGrid><w:tr><w:tc><w:p><w:r><w:t>Middle authored cell</w:t></w:r></w:p></w:tc></w:tr></w:tbl><w:p><w:r><w:t>Last authored block</w:t></w:r></w:p>',member:'iter_inner_content'},
 ...['','<w:p/>','<w:p/><w:p/>','<w:p/><w:tbl/>','<w:p/><w:tbl/><w:p/>'].map((body,i)=>({row:778+i,body,member:'paragraphs',expected:[0,1,2,1,2][i],invalidTable:body.includes('<w:tbl/>')})),
 ...['','<w:tbl/>','<w:tbl/><w:tbl/>','<w:p/><w:tbl/>','<w:tbl/><w:tbl/><w:p/>'].map((body,i)=>({row:783+i,body,member:'tables',expected:[0,1,2,1,2][i],invalidTable:body.includes('<w:tbl/>')})),
 {row:788,body:'',member:'add_paragraph',text:'',style:null}
];
expect(cases.map(c=>c.row)).toEqual(Array.from({length:17},(_,i)=>772+i));
const companions:Case[]=cases.filter(c=>c.invalidTable).map(c=>({...c,body:c.body.split('<w:tbl/>').join('<w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="1440"/></w:tblGrid><w:tr><w:tc><w:p/></w:tc></w:tr></w:tbl>'),invalidTable:false,nativeCompanion:true}));
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const c of [...cases,...companions])for(const route of ['model','sdk','shell'] as const)
it(`${route} independently executes exact block-container witness R${c.row}; strict=${strict}; kind=${kind}; fixture=${c.nativeCompanion?'native-table-companion':'original'}`,async()=>{
 const parts=readPackage(await textFixture(c.body,{styles:{kind:'styles',xml:`<w:styles xmlns:w="${w}"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Bar"><w:name w:val="Bar"/></w:style></w:styles>`}},strict)),volume=Volume.fromJSON({'/input':'','/out':''});if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),mutation=c.member.startsWith('add_'),method=mutation||c.member==='iter_inner_content',operations=[{operation:`model.document.Document.${c.member}.${method?'call':'get'}`,receiver:ref('document'),arguments:c.member==='add_table'?{rows:2,cols:2,width:{value:2,unit:'in'}}:c.member==='add_paragraph'?{text:c.text,style:c.style}:{},resultHandle:'observed'}],sink={async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}},observe=(values:unknown[])=>{if(c.expected!==undefined)expect((values[0] as unknown[]).length).toBe(c.expected);else if(c.member==='iter_inner_content')expect((values[0] as {type:string}[]).map(v=>v.type)).toEqual(['Paragraph','Table','Paragraph']);};
 if(route==='model'){const doc=await api.Document(input,textContext);if(c.member==='add_paragraph'){const added=doc.add_paragraph(c.text,c.style);expect(added.equals(doc.paragraphs[0])).toBe(true);expect(added.part).toBe(doc.part);}else if(c.member==='add_table'){const added=doc.add_table(2,2,api.Inches(2));expect(added).toBeInstanceOf(api.Table);added.alignment=api.WD_TABLE_ALIGNMENT.CENTER;expect(doc.tables[0]!.alignment).toEqual(api.WD_TABLE_ALIGNMENT.CENTER);expect(added.part).toBe(doc.part);}else if(c.member==='iter_inner_content'){const iterator=doc.iter_inner_content();expect(iterator.next().value).toBeInstanceOf(api.Paragraph);expect(iterator.next().value).toBeInstanceOf(api.Table);expect(iterator.next().value).toBeInstanceOf(api.Paragraph);expect(iterator.next().done).toBe(true);}else observe([Reflect.get(doc,c.member)]);if(c.invalidTable)await expect(doc.save(sink)).rejects.toMatchObject({code:"invalid-package"});else await doc.save(sink);}else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);observe(batch.results.map(r=>r.value));if(c.invalidTable)await expect(batch.save(sink)).rejects.toMatchObject({code:"invalid-package"});else await batch.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' ${mutation?'--output /out':''} --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);observe(JSON.parse(result.stdout).data.results.map((r:{data:unknown})=>r.data));expect(await fs.readFile('/input')).toEqual(input);if(mutation)volume.writeFileSync('/out',await fs.readFile('/out'));else if(!c.invalidTable)await(await api.Document(input,textContext)).save(sink);}finally{await shell.dispose();}}
 if(c.invalidTable){expect(volume.readFileSync('/out')).toEqual(Buffer.from(''));expect((await api.validateDocument(input,textContext)).valid).toBe(false);expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));return;}
 const output=new Uint8Array(volume.readFileSync('/out') as Buffer),after=readPackage(output);assertPackageLinks(after);for(const[name,bytes]of parts)if(name!=='word/document.xml')expect(after.get(name),name).toEqual(bytes);const doc=await api.Document(output,textContext);if(c.member==='add_paragraph'){expect(doc.paragraphs).toHaveLength(1);expect(doc.paragraphs[0]!.text).toBe(c.text);expect(doc.paragraphs[0]!.style!.name).toBe(c.style??'Normal');expect(doc.paragraphs[0]!.runs).toHaveLength(c.text?1:0);}else if(c.member==='add_table'){expect(doc.tables).toHaveLength(1);const table=doc.tables[0]!;expect(table.rows.length).toBe(2);expect(table.columns.length).toBe(2);expect(table.columns.at(0).width?.twips).toBe(1440);expect(table.rows.at(0).cells[0]!.width?.twips).toBe(1440);expect(table.rows.at(0).cells[0]!.paragraphs).toHaveLength(1);}else{expect(after.get('word/document.xml')).toEqual(parts.get('word/document.xml'));if(c.member==='iter_inner_content'){expect(doc.paragraphs.map(p=>p.text)).toEqual(['First authored block','Last authored block']);expect(doc.tables[0]!.rows.at(0).cells[0]!.text).toBe('Middle authored cell');}}expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));
});
