import { Volume } from "memfs";
import { afterEach, expect, it } from "vitest";
import { MemoryFileSystem, Shell } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import * as api from "./index.js";
import { textContext, textFixture } from "../tests/fixtures/text.js";
import { readPackage } from "../tests/assertions.js";
import { useNativeProcess } from "../tests/native-process.js";

const program = `import * as api from 'docx';import {Volume} from 'memfs';process.stdout.write(JSON.stringify({ready:true})+'\\n');const {createInterface}=await import('node:readline');for await(const line of createInterface({input:process.stdin})){const request=JSON.parse(line);if(request.cleanup){globalThis.gc();console.log(JSON.stringify({cleaned:true}));continue}const input=new Uint8Array(Buffer.from(request.input,'base64')),signal=new AbortController().signal,memory=Volume.fromJSON({'/output':''}),context={limits:request.limits,signal,budget:new api.DocumentBudget(request.documentLimits,signal),encoding:{order:'input',compression:'store'},stdout:{async write(bytes){memory.appendFileSync('/output',bytes);}}};let response;try{if(request.route==='native-sdk'){const data=await api.editDocumentComments(input,{operation:'comments.remove',options:{comment:1,output:'-'}},context);response={ok:true,changed:data.changed};}else{const {MemoryFileSystem,Shell}=await import('@poe-platform/safe-bash');const {docxCommands}=await import('@poe-platform/safe-bash/commands/docx');const fs=new MemoryFileSystem();await fs.writeFile('/input',input);await fs.writeFile('/destination',new TextEncoder().encode('Retained destination'));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:request.limits,documentLimits:request.documentLimits})}));try{const result=await shell.exec('docx comments remove /input --comment 1 --output /destination --force --json');response={...JSON.parse(result.stdout),exitCode:result.exitCode};if(Buffer.compare(Buffer.from(input),Buffer.from(await fs.readFile('/input'))))throw Error('source changed');if(result.exitCode){if(new TextDecoder().decode(await fs.readFile('/destination'))!=='Retained destination')throw Error('destination changed');}else memory.writeFileSync('/output',await fs.readFile('/destination'));}finally{await shell.dispose();}}}catch(error){response={ok:false,code:error.code??error.name,error:error.stack};}console.log(JSON.stringify({response,output:Buffer.from(memory.readFileSync('/output')).toString('base64')}));}`;
const nativeRequest = useNativeProcess(["--expose-gc", "--input-type=module", "-e", program]);
afterEach(async () => { expect(await nativeRequest({ cleanup: true })).toEqual({ cleaned: true }); });

const encode = (value: string) => new TextEncoder().encode(value);
for (const strict of [false, true]) for (const kind of ["docx", "dotx"] as const)
for (const depth of [32, 8192]) for (const unknownAuthor of [false, true])
for (const route of ["sdk", "cli", "native-sdk", "native-cli"] as const)
it(`modern comment removal retains deep outside author ownership; strict=${strict}; kind=${kind}; depth=${depth}; unknown=${unknownAuthor}; route=${route}`, async () => {
  const word = strict ? "http://purl.oclc.org/ooxml/wordprocessingml/main" : "http://schemas.openxmlformats.org/wordprocessingml/2006/main", w14 = "http://schemas.microsoft.com/office/word/2010/wordml", w15 = "http://schemas.microsoft.com/office/word/2012/wordml";
  const comments = `<w:comments xmlns:w="${word}" xmlns:x="${w14}"><w:comment w:id="7" w:author="Archive"><w:p x:paraId="000000A1"><w:r><w:t>Remove selected</w:t></w:r></w:p></w:comment></w:comments>`, people = `<m:people xmlns:m="${w15}"><m:person m:author="Archive"><m:presenceInfo m:providerId="Office" m:userId="Retained"/></m:person></m:people>`;
  const seed = await api.readArchive(await textFixture('<w:p><w:r><w:t>Retained coast海🌊</w:t></w:r></w:p>', { comments: { kind: "comments", xml: comments }, thread: { kind: "commentsExtended", xml: `<m:commentsEx xmlns:m="${w15}"><m:commentEx m:paraId="000000A1" m:done="0"/></m:commentsEx>` }, people: { kind: "people", xml: people } }, strict, { kind }), textContext);
  const relationships = new api.DocumentXmlEditor(seed.members.find(member => member.name === "word/_rels/document.xml.rels")!.bytes);
  for (const [id, type] of [["thread", "commentsExtended"], ["people", "people"]]) relationships.setAttribute(relationships.root.children.find(node => node.attributes.some(attribute => attribute.localName === "Id" && attribute.value === id))!, "Type", `http://schemas.microsoft.com/office/2011/relationships/${type}`);
  const opaque = `${'<f:opaque>'.repeat(depth)}<f:leaf${unknownAuthor ? ' w:author="Archive"' : ''} f:retained="exact"/>${'</f:opaque>'.repeat(depth)}`, main = `<w:document xmlns:w="${word}" xmlns:f="urn:original:author-owner-depth" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="f"><w:body><w:p><w:r><w:t>Retained coast海🌊</w:t></w:r></w:p>${opaque}<!--retain--><?audit exact?></w:body></w:document>`;
  const limits = { ...textContext.limits, maxArchiveBytes: 1048576, maxEntryBytes: 1048576, maxTotalBytes: 1048576, maxRetainedBytes: 2147483648 }, documentLimits = { xmlDepth: 16384, retainedBytes: 2147483648, work: 2147483648 }, signal = new AbortController().signal, context = { limits, signal, budget: new api.DocumentBudget(documentLimits, signal), encoding: { order: "input", compression: "store" } as const };
  const memory = Volume.fromJSON({ "/input": "", "/output": "" }); await api.writeArchive({ ...seed, members: seed.members.map(member => member.name === "word/document.xml" ? { ...member, bytes: encode(main) } : member.name === "word/_rels/document.xml.rels" ? { ...member, bytes: relationships.serialize() } : member) }, { async write(bytes) { memory.appendFileSync("/input", bytes); } }, context.encoding, context);
  const input = new Uint8Array(memory.readFileSync("/input") as Buffer), original = input.slice(), before = readPackage(input, limits);
  if (route.startsWith("native-")) {
    const actual = await nativeRequest({ route, input: Buffer.from(input).toString("base64"), limits, documentLimits }) as { response: { ok: boolean; code?: string; errors?: { code: string }[] }; output: string };
    expect(actual.response, JSON.stringify(actual.response)).toMatchObject(unknownAuthor ? { ok: false } : { ok: true }); if (unknownAuthor) expect(actual.response.code ?? actual.response.errors?.[0]?.code).toBe("unsupported-edit"); memory.writeFileSync("/output", Buffer.from(actual.output, "base64"));
  } else if (route === "sdk") {
    const pending = api.editDocumentComments(input, { operation: "comments.remove", options: { comment: 1, output: "-" } }, { ...context, stdout: { async write(bytes) { memory.appendFileSync("/output", bytes); } } });
    if (unknownAuthor) await expect(pending).rejects.toMatchObject({ code: "unsupported-edit" }); else expect(await pending).toMatchObject({ changed: true, changes: [{ kind: "remove" }] });
  } else {
    const fs = new MemoryFileSystem(), destination = encode("Retained destination"); await fs.writeFile("/input", input); await fs.writeFile("/destination", destination); const shell = new Shell({ fs }).use(docxCommands({ engine: api.createDocxInspectionCommandEngine({ limits, documentLimits }) }));
    try { const result = await shell.exec("docx comments remove /input --comment 1 --output /destination --force --json"); expect(result.exitCode, result.stdout + result.stderr).toBe(unknownAuthor ? 1 : 0); expect(await fs.readFile("/input")).toEqual(input); if (unknownAuthor) { expect(JSON.parse(result.stdout)).toMatchObject({ ok: false, data: null, affected: 0, errors: [{ code: "unsupported-edit" }] }); expect(await fs.readFile("/destination")).toEqual(destination); } else memory.writeFileSync("/output", await fs.readFile("/destination")); } finally { await shell.dispose(); }
  }
  const output = new Uint8Array(memory.readFileSync("/output") as Buffer); if (unknownAuthor) expect(output).toHaveLength(0); else { const after = readPackage(output, limits); expect([...after.keys()]).toEqual([...before.keys()]); for (const [name, bytes] of before) if (!["word/comments.xml", "word/thread.xml", "word/people.xml"].includes(name)) expect(after.get(name), name).toEqual(bytes); expect(new api.DocumentXmlEditor(after.get("word/comments.xml")!).root.children).toHaveLength(0); expect(new api.DocumentXmlEditor(after.get("word/thread.xml")!).root.children).toHaveLength(0); expect(new api.DocumentXmlEditor(after.get("word/people.xml")!).root.children).toHaveLength(0); }
  expect(input).toEqual(original); expect(readPackage(input, limits)).toEqual(before); expect(before.get("word/document.xml")).toEqual(encode(main));
});
