import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { MemoryFileSystem, Shell } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const mc='http://schemas.openxmlformats.org/markup-compatibility/2006';
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const carrier of ['direct','choice','fallback','process'])for(const state of ['empty','paragraph','section','paragraph-section'])for(const route of ['model','sdk','shell'])
it(`${route} clears active body content through native XML owners; ${kind}; strict=${strict}; carrier=${carrier}; state=${state}`,async()=>{
 const content=(state.includes('paragraph')?'<w:p/>':'')+(state.includes('section')?'<w:sectPr/>':''),wrapped=carrier==='direct'?content:carrier==='process'?`<f:pass xmlns:f="urn:original:body-clear" xmlns:mc="${mc}" mc:Ignorable="f" mc:ProcessContent="f:pass">${content}</f:pass>`:`<mc:AlternateContent xmlns:mc="${mc}" xmlns:f="urn:original:body-clear" mc:Ignorable="f"><mc:Choice Requires="${carrier==='choice'?'w':'f'}">${carrier==='choice'?content:'<f:retain/>'}</mc:Choice><mc:Fallback>${carrier==='fallback'?content:'<f:retain/>'}</mc:Fallback></mc:AlternateContent>`,parts=readPackage(await textFixture(wrapped+'<!--body--><?audit keep?>',{},strict));
 if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));
 const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),mutation=state.includes('paragraph'),sink={async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}},operations=[{operation:'model.document.Document.paragraphs.get',receiver:ref('document'),arguments:{},resultHandle:'paragraphs'},...(mutation?[{operation:'model.text.paragraph.Paragraph.element.get',receiver:ref('paragraphs',0),arguments:{},resultHandle:'paragraphElement'},{operation:'model.XmlElementView.remove.call',receiver:ref('paragraphElement'),arguments:{}}]:[])];
 if(route==='model'){const doc=await api.Document(input,textContext),p=doc.paragraphs[0];if(p){p.element.remove();expect(()=>p.text).toThrow(api.StaleHandleError);}expect(doc.paragraphs).toHaveLength(0);await doc.save(sink);}else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);await batch.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' ${mutation?'--output /out':''} --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);if(mutation)volume.writeFileSync('/out',await fs.readFile('/out'));else await(await api.Document(input,textContext)).save(sink);expect(await fs.readFile('/input')).toEqual(input);}finally{await shell.dispose();}}
 const output=new Uint8Array(volume.readFileSync('/out') as Buffer),after=readPackage(output);assertPackageLinks(after);for(const[name,bytes]of parts)if(name!=='word/document.xml')expect(after.get(name),name).toEqual(bytes);const doc=await api.Document(output,textContext);expect(doc.paragraphs).toHaveLength(0);expect(doc.tables).toHaveLength(0);expect(doc.sections.length).toBe(state.includes('section')?1:0);const xml=new TextDecoder().decode(after.get('word/document.xml'));for(const token of ['<!--body-->','<?audit keep?>'])expect(xml.split(token)).toHaveLength(2);if(carrier!=='direct')expect(xml).toContain(carrier==='process'?'f:pass':'mc:AlternateContent');if(['choice','fallback'].includes(carrier))expect(xml.split('<f:retain/>')).toHaveLength(2);if(!mutation)expect(after.get('word/document.xml')).toEqual(parts.get('word/document.xml'));if(state.includes('section')){const ns=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w;expect(new api.DocumentXmlEditor(doc.sections.at(0).element.serialize()).root.namespace).toBe(ns);}expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));
});

for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const carrier of ['choice','fallback','process'])for(const state of ['paragraph','paragraph-section'])for(const route of ['model','sdk','shell'])
it(`${route} refuses opaque body carrier removal without dirtying; ${kind}; strict=${strict}; carrier=${carrier}; state=${state}`,async()=>{
 const content='<w:p/>'+(state.includes('section')?'<w:sectPr/>':''),wrapped=carrier==='process'?`<f:pass xmlns:f="urn:original:body-clear" xmlns:mc="${mc}" mc:Ignorable="f" mc:ProcessContent="f:pass">${content}</f:pass>`:`<mc:AlternateContent xmlns:mc="${mc}" xmlns:f="urn:original:body-clear" mc:Ignorable="f"><mc:Choice Requires="${carrier==='choice'?'w':'f'}">${carrier==='choice'?content:'<f:retain/>'}</mc:Choice><mc:Fallback>${carrier==='fallback'?content:'<f:retain/>'}</mc:Fallback></mc:AlternateContent>`,parts=readPackage(await textFixture(wrapped,{},strict)),volume=Volume.fromJSON({'/input':'','/out':''});
 if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),operations=[{operation:'model.document.Document.element.get',receiver:ref('document'),arguments:{},resultHandle:'root'},{operation:'model.XmlElementView.children.get',receiver:ref('root'),arguments:{},resultHandle:'children'},{operation:'model.XmlElementView.children.get',receiver:ref('children',0),arguments:{},resultHandle:'bodyChildren'},{operation:'model.XmlElementView.remove.call',receiver:ref('bodyChildren',0),arguments:{}}];
 if(route==='model'){const doc=await api.Document(input,textContext),before=doc.element.serialize();expect(()=>doc.element.children[0]!.children[0]!.remove()).toThrow(api.UnsupportedEditError);expect(doc.element.serialize()).toEqual(before);await doc.save({async write(bytes){volume.appendFileSync('/out',bytes);}});const after=readPackage(new Uint8Array(volume.readFileSync('/out') as Buffer));for(const[name,bytes]of parts)expect(after.get(name),name).toEqual(bytes);}else if(route==='sdk')await expect(api.applyStyleModelBatch(input,{version:1,operations},textContext)).rejects.toMatchObject({code:'unsupported-edit'});else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);await fs.writeFile('/out',new TextEncoder().encode('Original destination'));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(1);expect(JSON.parse(result.stdout).errors[0].code).toBe('unsupported-edit');expect(new TextDecoder().decode(await fs.readFile('/out'))).toBe('Original destination');expect(await fs.readFile('/input')).toEqual(input);}finally{await shell.dispose();}}expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));if(route!=='model')expect(volume.readFileSync('/out')).toEqual(Buffer.from(''));
});
