import {archiveSettings,InputTypeError,InvalidValueError,ResourceLimitError,type ArchiveContext} from './archive.js';
import {readDocumentArchive,type AdmittedDocumentArchive} from './admission.js';import {validateDocxInvocation} from './command.js';
import {DocumentBudget} from './budget.js';import {documentDialects} from './dialect.js';
import {closedRecord,decodeLocation,encodeLocation,SelectionError,type Location} from './location-token.js';
import {LocationIndex,pathContains} from './location-index.js';import {parseDocumentXml,type XmlElement} from './package-xml.js';
import {MarkupCompatibility,type CompatibilityContent} from './compatibility.js';import type {InspectionReference} from './inspection.js';
import {collectEquationProperties} from './equation-properties.js';import {admitEquationFragment,inspectEquationFragment,mathNamespace} from './equation-fragments.js';
import {DocumentArchiveEditor} from './package-write.js';import {DocumentXmlEditor,UnsupportedEditError} from './xml-write.js';
import {assertDocumentEditable,publishDocumentArchive,type PublicationContext,type PublicationInput} from './publication.js';
import type {DocxBinaryInput,DocxOperationArguments} from './operation-types.js';import type {ImageBinaryResolver} from './image-insertion.js';
import {assertOutsideRevisionRanges} from './revision-markup.js';import {measurePackageResourceSerialization} from './ancillary-resources.js';
export type EquationPropertyScope='equation'|'run'|'argument'|'display'|'global';
export interface EquationIssue{readonly code:string;readonly part:string;readonly path:readonly number[];readonly message:string}
export interface EquationAttribute{readonly namespace:string;readonly localName:string;readonly value:string}
export interface EquationProperty{readonly scope:EquationPropertyScope;readonly part:string;readonly path:readonly number[];readonly namespace:string;readonly localName:string;readonly attributes:readonly EquationAttribute[];readonly status:'stored'|'opaque';readonly issues:readonly EquationIssue[]}
export interface EquationDetails{readonly kind:'equations';readonly mode:'inline'|'display';readonly ownerPart:string;readonly root:{readonly namespace:string;readonly localName:string};readonly path:readonly number[];readonly mathPaths:readonly (readonly number[])[];readonly active:boolean;readonly properties:readonly EquationProperty[];readonly status:'bounded'|'opaque';readonly issues:readonly EquationIssue[]}
export interface EquationRecord{readonly kind:'equations';readonly location:Location<'part'>;readonly name:string;readonly properties:readonly [];readonly references:readonly InspectionReference[];readonly support:'edit'|'preserve';readonly details:EquationDetails}
export interface EquationListData{readonly items:readonly EquationRecord[];readonly globalProperties:readonly EquationProperty[]}
export interface EquationInspectionData extends EquationListData{readonly warnings:readonly {readonly code:string;readonly message:string}[]}
export type EquationBinaryResolver=ImageBinaryResolver;
export type EquationMutationOperation='equations.add'|'equations.replace';
export interface EquationMutationRequest<K extends EquationMutationOperation=EquationMutationOperation>{readonly operation:K;readonly options:DocxOperationArguments<K>;readonly input?:PublicationInput}
export interface EquationMutationData{readonly changed:boolean;readonly changes:readonly {readonly kind:'add'|'replace';readonly before:Location;readonly after:Location}[];readonly output:{readonly path:string|null;readonly bytes:number;readonly sha256:string}|null;readonly dryRun:boolean}
export interface EquationMutationContext extends PublicationContext{readonly binaryResolver?:EquationBinaryResolver;readonly admitPublication?:(planned:EquationMutationData)=>undefined}
export class UnsupportedEquationMutationError extends UnsupportedEditError{readonly locations:readonly Location[];constructor(readonly location:Location){super('Equation mutation cannot establish bounded faithful preservation.');this.locations=[location];}}
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
const xmlPart=(type:string)=>type.toLowerCase().endsWith('+xml')||['application/xml','text/xml'].includes(type.toLowerCase());
async function digest(bytes:Uint8Array,budget:DocumentBudget):Promise<string>{budget.charge('work',bytes.length);budget.charge('retainedBytes',bytes.length+128);const hash=await crypto.subtle.digest('SHA-256',new Uint8Array(bytes));budget.check('work',0);return [...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('');}
function location(sourceSha256:string,part:string,story:string,path:readonly number[],generation=0):Location<'part'>{const value={version:1 as const,sourceSha256,generation,part,story,path:[...path],range:null};return {kind:'part',value,token:encodeLocation(value),positions:{}};}
export async function equationDiagnosticLocation(input:Uint8Array,part:string,path:readonly number[],budget:DocumentBudget):Promise<Location<'part'>>{return location(await digest(input,budget),part,part,path);}
export interface RawEquationUnit{readonly node:XmlElement;readonly path:readonly number[]}
/** Physical outer-unit walk deliberately includes unselected and opaque content. */
export function collectEquationUnits(root:XmlElement,namespace:string,budget:DocumentBudget):RawEquationUnit[]{const result:RawEquationUnit[]=[];const visit=(node:XmlElement,path:readonly number[])=>{budget.charge('work',1);if(node.namespace===namespace&&['oMath','oMathPara'].includes(node.localName)){budget.charge('retainedBytes',64+path.length*8);result.push({node,path});return;}node.children.forEach((child,i)=>visit(child,[...path,i]));};visit(root,[]);return result;}
function exposed(view:MarkupCompatibility,budget:DocumentBudget):Set<XmlElement>{const result=new Set<XmlElement>();const visit=(content:readonly CompatibilityContent[])=>{for(const node of content){budget.charge('work',1);if('source' in node){result.add(node.source);budget.charge('retainedBytes',32);if(node.disposition==='understood')visit(node.content);}}};visit(view.content);return result;}
function at(root:XmlElement,path:readonly number[]):XmlElement|undefined{let node:XmlElement|undefined=root;for(const i of path)node=node?.children[i];return node;}
function ancestors(root:XmlElement,path:readonly number[]):XmlElement[]{const result=[root];let node=root;for(const i of path){node=node.children[i]!;result.push(node);}return result;}
function hostReasons(root:XmlElement,paragraphPath:readonly number[],namespace:string,view:MarkupCompatibility,budget:DocumentBudget):string[]{
 const reasons:string[]=[],w=namespace===mathNamespace(true)?documentDialects.strict.w:documentDialects.transitional.w,chain=ancestors(root,paragraphPath),paragraph=chain.at(-1)!;
 const native=['document','body','hdr','ftr','footnotes','footnote','endnotes','endnote','comments','comment','tbl','tr','tc','p'];
 if(paragraph.namespace!==w||paragraph.localName!=='p'||chain.some(n=>n.namespace===w?!native.includes(n.localName):n.namespace!=='http://schemas.openxmlformats.org/markup-compatibility/2006'||!['AlternateContent','Choice','Fallback'].includes(n.localName)))reasons.push('unsupported-equation-host');
 const transparentHost=chain.some(n=>n.namespace==='http://schemas.openxmlformats.org/markup-compatibility/2006'&&n.localName==='AlternateContent');if(!view.canEdit(paragraph)&&!(transparentHost&&exposed(view,budget).has(paragraph)))reasons.push('opaque-equation-host');
 const active=exposed(view,budget);const visit=(node:XmlElement,transparent=false)=>{budget.charge('work',1);if(node.namespace==='http://schemas.openxmlformats.org/markup-compatibility/2006'&&node.localName==='AlternateContent'){const selected=view.branches.find(b=>b.alternateContent===node)?.selected;selected?.children.forEach(child=>visit(child,true));return;}if(!active.has(node))return;if(node.namespace===w&&['sdt','fldSimple','fldChar','instrText','ins','del','moveFrom','moveTo','pPrChange','rPrChange','moveFromRangeStart','moveFromRangeEnd','moveToRangeStart','moveToRangeEnd'].includes(node.localName))reasons.push('compound-equation-host');if(!view.canEdit(node)&&!(transparent&&[w,namespace].includes(node.namespace))&&node.namespace!== 'http://schemas.openxmlformats.org/markup-compatibility/2006')reasons.push('opaque-equation-host');node.children.forEach(child=>visit(child,transparent));};visit(paragraph,transparentHost);
 try{assertOutsideRevisionRanges(root,paragraph,budget,view.branches);}catch(error){if(!(error instanceof UnsupportedEditError))throw error;reasons.push('review-equation-host');}
 return [...new Set(reasons)];
}
async function inventory(owned:Uint8Array,archive:AdmittedDocumentArchive,budget:DocumentBudget,context:ArchiveContext):Promise<EquationInspectionData>{
 let protectedDocument=false;try{assertDocumentEditable(archive,archiveSettings({...context,budget}));}catch(error){if(!(error instanceof UnsupportedEditError))throw error;protectedDocument=true;}
 const namespace=mathNamespace(archive.dialect==='strict'),index=new LocationIndex(archive,context.limits,archive.mainPart,archive.dialect,budget),sha=await digest(owned,budget),items:EquationRecord[]=[],globalProperties:EquationProperty[]=[];
 const edges:{owner:string;reference:InspectionReference;target:string|null}[]=[];for(const owner of ['/',...archive.package.parts.filter(p=>!p.content_type.toLowerCase().endsWith('relationships+xml')).map(p=>p.partname)])for(const edge of archive.package.relationships(owner)){budget.charge('work',1);budget.charge('retainedBytes',128);edges.push({owner,reference:{owner,id:edge.rId,type:edge.reltype,target:edge.target_ref,external:edge.is_external},target:edge.is_external?null:edge.target_part.partname});}
 for(const part of [...archive.package.parts].sort((a,b)=>compare(a.partname,b.partname))){await budget.checkpoint(1);if(!xmlPart(part.content_type))continue;const root=parseDocumentXml(part.bytes,{},budget).root,view=new MarkupCompatibility(root,undefined,budget),active=exposed(view,budget);const paragraphs=index.entries.filter(e=>e.kind==='paragraph'&&e.part===part.partname),stories=index.entries.filter(e=>e.kind==='story'&&e.part===part.partname);
  if(part.content_type.toLowerCase()==='application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml'&&root.namespace===documentDialects[archive.dialect].w&&root.localName==='settings')root.children.forEach((child,i)=>{if(child.namespace===namespace&&child.localName==='mathPr')globalProperties.push(...collectEquationProperties(child,namespace,part.partname,[i],budget,true));});
  for(const unit of collectEquationUnits(root,namespace,budget)){const host=paragraphs.filter(p=>pathContains(p.path,unit.path)).sort((a,b)=>b.path.length-a.path.length)[0],story=stories.filter(s=>pathContains(s.path,unit.path)).sort((a,b)=>b.path.length-a.path.length)[0]?.story??part.partname,properties=collectEquationProperties(unit.node,namespace,part.partname,unit.path,budget),issues=inspectEquationFragment(unit.node,namespace,budget,part.partname,unit.path),bounded=issues.length===0,reasons:string[]=[];
   if(!active.has(unit.node))reasons.push('inactive-equation');if(!host||ancestors(root,unit.path).slice(host.path.length+1,-1).some(n=>n.namespace!=='http://schemas.openxmlformats.org/markup-compatibility/2006'||!['AlternateContent','Choice','Fallback'].includes(n.localName)))reasons.push('unsupported-equation-host');else reasons.push(...hostReasons(root,host.path,namespace,view,budget));if(index.references.filter(ref=>ref.story===story).length>1)reasons.push('shared-equation-host');
   if(protectedDocument)reasons.push('protected-equation-document');
   for(const code of [...new Set(reasons)]){budget.charge('diagnosticBytes',160+part.partname.length);issues.push({code,part:part.partname,path:[...unit.path],message:'The stored equation has no admitted unambiguous editable paragraph host.'});}
   const mathPaths=unit.node.localName==='oMath'?[unit.path]:unit.node.children.flatMap((child,i)=>child.namespace===namespace&&child.localName==='oMath'?[[...unit.path,i]]:[]),references=edges.filter(e=>e.owner===part.partname||e.target===part.partname).map(e=>e.reference).sort((a,b)=>compare(a.owner,b.owner)||compare(a.id,b.id)||compare(a.type,b.type)||compare(a.target,b.target)),loc=location(sha,part.partname,story,unit.path);budget.charge('matches',1);budget.charge('retainedBytes',512+loc.token.length*2);
   items.push({kind:'equations',location:loc,name:part.partname,properties:[],references,support:bounded&&!reasons.length?'edit':'preserve',details:{kind:'equations',mode:unit.node.localName==='oMath'?'inline':'display',ownerPart:part.partname,root:{namespace:unit.node.namespace,localName:unit.node.localName},path:unit.path,mathPaths,active:active.has(unit.node),properties,status:bounded?'bounded':'opaque',issues}});
  }
 }
 const warnings=items.some(i=>i.support==='preserve')?[{code:'preserve-only-equations',message:'Some stored equations require faithful preservation and cannot be edited by this bounded profile.'}]:[];return {items,globalProperties,warnings};
}
export async function inspectDocumentEquations(input:Uint8Array,options:DocxOperationArguments<'equations.list'>,context:ArchiveContext):Promise<EquationInspectionData>{const settings=archiveSettings(context),invocation=validateDocxInvocation({operation:'equations.list',inputs:['document'],options},settings.budget),opts=invocation.options as DocxOperationArguments<'equations.list'>,budget=settings.budget.lower(Object.fromEntries((opts.limit??[]).map(l=>[l.name,l.value])));if(!(input instanceof Uint8Array))throw new InputTypeError('Expected archive bytes.');budget.check('compressedInput',input.length);budget.charge('retainedBytes',input.length);const owned=new Uint8Array(input),archive=await readDocumentArchive(owned,{...settings,budget}),data=await inventory(owned,archive,budget,{...settings,budget});budget.charge('retainedBytes',measurePackageResourceSerialization({version:1,operation:'equations.list',ok:true,data,warnings:data.warnings,errors:[],affected:0,locations:data.items.map(i=>i.location)},budget));return data;}
async function fragmentBytes(input:DocxBinaryInput,context:EquationMutationContext,budget:DocumentBudget):Promise<Uint8Array>{
 const settings=archiveSettings({...context,budget}),maxBytes=Math.min(settings.limits.maxEntryBytes,budget.limits.xmlPartBytes);closedRecord(input,['kind','base64','path','capability']);
 if(input.kind==='bytes'){closedRecord(input,['kind','base64']);const s=input.base64;if(typeof s!=='string'||s.length%4!==0)throw new InvalidValueError('Expected canonical equation bytes.');const size=s.length/4*3-(s.endsWith('==')?2:s.endsWith('=')?1:0);if(size>maxBytes)throw new ResourceLimitError('Equation fragment exceeds XML limit.');budget.charge('work',s.length);budget.charge('retainedBytes',size*3);let decoded:string;try{decoded=atob(s);if(btoa(decoded)!==s)throw new Error();}catch{throw new InvalidValueError('Expected canonical equation bytes.');}return Uint8Array.from(decoded,c=>c.charCodeAt(0));}
 if(input.kind!=='vfs')throw new InvalidValueError('Expected explicit equation binary input.');closedRecord(input,['kind','path','capability']);if(typeof input.path!=='string'||!input.path||typeof input.capability!=='string'||!input.capability)throw new InvalidValueError('Expected explicit equation path capability.');const resolver=context.binaryResolver;if(!resolver||resolver.capability!==input.capability)throw new UnsupportedEditError('Equation fragment requires a matching explicit VFS capability.');settings.signal.throwIfAborted();const source=await resolver.open(input.path,{signal:settings.signal,maxBytes}),chunks:Uint8Array[]=[];let size=0;for await(const chunk of source){budget.check('work',0);if(!(chunk instanceof Uint8Array))throw new InputTypeError('Expected equation byte fragments.');if(chunk.length>maxBytes-size)throw new ResourceLimitError('Equation fragment exceeds XML limit.');size+=chunk.length;budget.charge('retainedBytes',chunk.length+64);budget.charge('work',chunk.length+1);chunks.push(new Uint8Array(chunk));}budget.check('work',0);budget.charge('retainedBytes',size);const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return bytes;
}
async function mutate(input:Uint8Array,request:EquationMutationRequest,context:EquationMutationContext):Promise<EquationMutationData>{
 closedRecord(request,['operation','options','input']);if(!['equations.add','equations.replace'].includes(request.operation))throw new InvalidValueError('Expected equation mutation.');if(request.input!==undefined){closedRecord(request.input,['path','stat']);closedRecord(request.input.stat,['type','size','allocatedBytes','ioBlockSize','preferredIoBlockSize','mode','mtimeMs','atimeMs','ctimeMs','birthtimeMs','revision','identityScope','ino','dev','rdevMajor','rdevMinor','nlink','uid','gid']);}const identity=request.input?{path:request.input.path,stat:{...request.input.stat}}:undefined,settings=archiveSettings(context),invocation=validateDocxInvocation({operation:request.operation,inputs:[identity?.path??'document'],options:request.options},settings.budget),opts=invocation.options as DocxOperationArguments<'equations.add'>,budget=settings.budget.lower(Object.fromEntries((opts.limit??[]).map(l=>[l.name,l.value]))),scoped={...context,...settings,budget};if(!(input instanceof Uint8Array))throw new InputTypeError('Expected archive bytes.');budget.charge('retainedBytes',input.length);const owned=new Uint8Array(input),archive=await readDocumentArchive(owned,scoped),index=new LocationIndex(archive,settings.limits,archive.mainPart,archive.dialect,budget),sha=await digest(owned,budget),value=decodeLocation(opts.select);
 if(value.sourceSha256!==sha||value.generation!==0||value.range!==null)throw new SelectionError('stale-selection');
 const data=await inventory(owned,archive,budget,{...settings,budget}),record=request.operation==='equations.replace'?data.items.find(i=>i.location.token===opts.select):undefined;
 const paragraph=request.operation==='equations.add'?index.entries.find(e=>e.kind==='paragraph'&&e.part===value.part&&e.story===value.story&&e.path.length===value.path.length&&e.path.every((n,i)=>n===value.path[i])):record?index.entries.filter(e=>e.kind==='paragraph'&&e.part===value.part&&e.story===value.story&&pathContains(e.path,value.path)).sort((a,b)=>b.path.length-a.path.length)[0]:undefined;
 if(!paragraph||request.operation==='equations.replace'&&!record)throw new SelectionError('stale-selection');const before=request.operation==='equations.add'?{kind:'paragraph' as const,value,token:opts.select,positions:paragraph.positions}:record!.location;
 const member=archive.members.find(m=>'/'+m.name===value.part)!,editor=new DocumentArchiveEditor(archive,{},undefined,budget),xml=editor.xml(member.name),namespace=mathNamespace(archive.dialect==='strict');
 try{assertDocumentEditable(archive,scoped);}catch(error){if(!(error instanceof UnsupportedEditError))throw error;throw new UnsupportedEquationMutationError(before);}
 if(hostReasons(xml.root,paragraph.path,namespace,xml.compatibility,budget).length||index.references.filter(ref=>ref.story===paragraph.story).length>1||record?.support==='preserve')throw new UnsupportedEquationMutationError(before);
 const bytes=await fragmentBytes(opts.file,scoped,budget),fragment=admitEquationFragment(bytes,namespace,budget),node=at(xml.root,value.path)!;
 if(record&&(fragment.root.namespace!==record.details.root.namespace||fragment.root.localName!==record.details.root.localName))throw new UnsupportedEquationMutationError(before);
 const changed=request.operation==='equations.add'||xml.sourceXml(node)!==fragment.xml,path=request.operation==='equations.add'?[...value.path,node.children.length]:value.path;
 if(changed){if(request.operation==='equations.add')xml.appendEquationElement(node,fragment.xml);else xml.replaceEquationElement(node,fragment.xml);}
 const after=location(sha,value.part,value.story,path,1),changes=changed?[{kind:request.operation==='equations.add'?'add' as const:'replace' as const,before,after}]:[],planned:EquationMutationData={changed,changes,dryRun:opts.dryRun??false,output:opts.dryRun?null:{path:opts.inPlace?identity?.path??null:opts.output==='-'?null:opts.output??null,bytes:settings.limits.maxArchiveBytes,sha256:'0'.repeat(64)}};
 if(opts.json)budget.charge('retainedBytes',measurePackageResourceSerialization({version:1,operation:request.operation,ok:true,data:planned,affected:changes.length,locations:changes.map(c=>c.after),warnings:[],errors:[]},budget));
 if(context.admitPublication){const result=context.admitPublication(planned);if(result!==undefined){if(result&&typeof (result as Promise<unknown>).then==='function')void Promise.resolve(result).catch(()=>{});throw new InputTypeError('Equation publication admission must be synchronous.');}}
 const result=await publishDocumentArchive(editor.snapshot(),{...(identity?{input:identity}:{}),...(opts.output===undefined?{}:{output:opts.output}),...(opts.inPlace===undefined?{}:{inPlace:opts.inPlace}),...(opts.force===undefined?{}:{force:opts.force}),...(opts.dryRun===undefined?{}:{dryRun:opts.dryRun}),...(opts.json===undefined?{}:{json:opts.json})},scoped);return {...planned,output:result.published.length?{path:result.published[0]!.path,bytes:result.published[0]!.bytes,sha256:result.archiveSha256!}:null};
}
export async function addDocumentEquation(input:Uint8Array,request:EquationMutationRequest<'equations.add'>,context:EquationMutationContext):Promise<EquationMutationData>{closedRecord(request,['operation','options','input']);if(request.operation!=='equations.add')throw new InvalidValueError('Expected equation addition.');return mutate(input,request,context);}
export async function replaceDocumentEquation(input:Uint8Array,request:EquationMutationRequest<'equations.replace'>,context:EquationMutationContext):Promise<EquationMutationData>{closedRecord(request,['operation','options','input']);if(request.operation!=='equations.replace')throw new InvalidValueError('Expected equation replacement.');return mutate(input,request,context);}
/** Protects source-bound physical math and global properties during raw replacement. */
export async function assertEquationXmlReplacement(archive:AdmittedDocumentArchive,original:XmlElement,replacement:XmlElement,input:Uint8Array,part:string,budget:DocumentBudget,replacementBytes:Uint8Array):Promise<void>{
 const namespace=mathNamespace(archive.dialect==='strict'),global=archive.package.parts.find(p=>p.partname===part)?.content_type.toLowerCase()==='application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml',observations=(root:XmlElement)=>[...collectEquationUnits(root,namespace,budget),...(global&&root.namespace===documentDialects[archive.dialect].w&&root.localName==='settings'?root.children.flatMap((node,i)=>node.namespace===namespace&&node.localName==='mathPr'?[{node,path:[i]}]:[]):[])];
 const before=observations(original),after=observations(replacement);if(!before.length&&!after.length)return;const encodingChanged=parseDocumentXml(archive.members.find(m=>'/'+m.name===part)!.bytes,{},budget).encoding!==parseDocumentXml(replacementBytes,{},budget).encoding;const originalEditor=new DocumentXmlEditor(archive.members.find(m=>'/'+m.name===part)!.bytes,{},undefined,budget),replacementEditor=new DocumentXmlEditor(replacementBytes,{},undefined,budget);const context=(node:XmlElement):string=>{budget.charge('work',node.namespaces.size);const text=JSON.stringify([...node.namespaces])+node.children.map(context).join('');budget.charge('retainedBytes',text.length*2);return text;};const payload=(editor:DocumentXmlEditor,path:readonly number[])=>{const node=at(editor.root,path)!;return editor.sourceXml(node)+context(node);};
 for(let i=0;i<Math.max(before.length,after.length);i++){const a=before[i],b=after[i];if(!a||!b||a.path.length!==b.path.length||a.path.some((n,j)=>n!==b.path[j])||encodingChanged||payload(originalEditor,a.path)!==payload(replacementEditor,b.path))throw new UnsupportedEquationMutationError(await equationDiagnosticLocation(input,part,a?.path??[],budget));}
}
