import type {XmlElement} from './package-xml.js';import {DocumentBudget} from './budget.js';import type {EquationProperty,EquationPropertyScope} from './equations.js';
const wrappers=['accPr','barPr','boxPr','borderBoxPr','dPr','eqArrPr','fPr','funcPr','groupChrPr','limLowPr','limUppPr','mPr','naryPr','phantPr','radPr','sPrePr','sSubPr','sSubSupPr','sSupPr','rPr','argPr','ctrlPr','oMathParaPr'];
const native=['lit','nor','scr','sty','brk','aln','argSz','type','jc','mathFont','brkBin','brkBinSub','smallFrac','dispDef','lMargin','rMargin','defJc','preSp','postSp','interSp','intraSp','wrapIndent','wrapRight','intLim','naryLim','chr','pos','begChr','endChr','sepChr','grow','shp','baseJc','maxDist','objDist','rSp','rSpRule','cSp','cGp','cGpRule','mcs','mc','mcPr','count','hideTop','hideBot','hideLeft','hideRight','strikeH','strikeV','strikeBLTR','strikeTLBR','opEmu','noBreak','diff','alnScr','limLoc','subHide','supHide','transp','zeroAsc','zeroDesc','zeroWid','show','degHide','vertJc'];
const propertyChildren:Readonly<Record<string,readonly string[]>>={
 accPr:['chr','ctrlPr'],barPr:['pos','ctrlPr'],boxPr:['opEmu','noBreak','diff','brk','aln','ctrlPr'],borderBoxPr:['hideTop','hideBot','hideLeft','hideRight','strikeH','strikeV','strikeBLTR','strikeTLBR','ctrlPr'],dPr:['begChr','sepChr','endChr','grow','shp','ctrlPr'],eqArrPr:['baseJc','maxDist','objDist','rSpRule','rSp','ctrlPr'],fPr:['type','ctrlPr'],funcPr:['ctrlPr'],groupChrPr:['chr','pos','vertJc','ctrlPr'],limLowPr:['ctrlPr'],limUppPr:['ctrlPr'],mPr:['baseJc','rSpRule','cGpRule','rSp','cSp','cGp','mcs','ctrlPr'],mcs:['mc'],mc:['mcPr'],mcPr:['count'],naryPr:['chr','limLoc','grow','subHide','supHide','ctrlPr'],phantPr:['show','zeroWid','zeroAsc','zeroDesc','transp','ctrlPr'],radPr:['degHide','ctrlPr'],sPrePr:['ctrlPr'],sSubPr:['ctrlPr'],sSubSupPr:['alnScr','ctrlPr'],sSupPr:['ctrlPr'],rPr:['lit','nor','scr','sty','brk','aln'],argPr:['argSz'],oMathParaPr:['jc'],mathPr:['mathFont','brkBin','brkBinSub','smallFrac','dispDef','lMargin','rMargin','defJc','preSp','postSp','interSp','intraSp','wrapIndent','wrapRight','intLim','naryLim']};
const mathContext=new Set([...wrappers,...native,'mathPr','oMath','oMathPara','r','num','den','e','sub','sup','deg','lim','fn','mr',...wrappers.map(n=>n.slice(0,-2))]);
const wordProperties=new Set('rPr rPrChange rStyle rFonts b bCs i iCs caps smallCaps strike dstrike outline shadow emboss imprint noProof snapToGrid vanish webHidden color spacing w kern position sz szCs highlight u effect bdr shd fitText vertAlign rtl cs em lang eastAsianLayout specVanish oMath ins del moveFrom moveTo'.split(' '));
const compare=(a:string,b:string)=>a<b?-1:a>b?1:0;
/** Snapshots every stored property node without importing active Word behavior. */
export function collectEquationProperties(root:XmlElement,namespace:string,part:string,base:readonly number[],budget:DocumentBudget,global=false):EquationProperty[]{
 const result:EquationProperty[]=[];const w=namespace.includes('purl.oclc')?'http://purl.oclc.org/ooxml/wordprocessingml/main':'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
 const visit=(node:XmlElement,path:readonly number[],scope?:EquationPropertyScope,inert=false,context=true,parent='')=>{budget.charge('work',1+node.attributes.length);context&&=node.namespace===namespace&&mathContext.has(node.localName)||inert&&node.namespace===w||node.namespace===w&&node.localName==='rPr'&&(scope!==undefined||parent==='r');if(node.namespace===namespace&&wrappers.includes(node.localName)){const supported=node.localName==='rPr'?parent==='r':node.localName==='argPr'?['num','den','e','sub','sup','deg','lim','fn'].includes(parent):node.localName==='ctrlPr'?wrappers.includes(parent):parent===node.localName.slice(0,-2);context&&=supported;}if(node.namespace===namespace&&native.includes(node.localName))context&&=propertyChildren[parent]?.includes(node.localName)===true;let selected=scope;if(node.namespace===w&&node.localName==='rPr'&&parent==='r')selected='run';if(global)selected='global';else if(node.namespace===namespace&&wrappers.includes(node.localName))selected=node.localName==='oMathParaPr'?'display':node.localName==='rPr'?'run':node.localName==='argPr'?'argument':'equation';
  if(selected){const attributes=node.attributes.filter(a=>a.namespace!=='http://www.w3.org/2000/xmlns/').map(a=>({namespace:a.namespace,localName:a.localName,value:a.value})).sort((a,b)=>compare(a.namespace,b.namespace)||compare(a.localName,b.localName));const associated=inert||node.namespace===w&&['rPr','rPrChange'].includes(node.localName);const stored=context&&(associated&&node.namespace===w&&wordProperties.has(node.localName)&&attributes.every(a=>a.namespace===w)||node.namespace===namespace&&(wrappers.includes(node.localName)||native.includes(node.localName)||global&&node.localName==='mathPr')&&attributes.every(a=>a.namespace===namespace&&a.localName===(node.localName==='brk'?'alnAt':'val'))&&(!wrappers.includes(node.localName)&&node.localName!=='mathPr'||attributes.length===0));const issues=stored?[]:[{code:'opaque-equation-property',part,path:[...path],message:'Stored property metadata is outside recognized native names or attributes.'}];budget.charge('retainedBytes',256+attributes.reduce((n,a)=>n+(a.namespace.length+a.localName.length+a.value.length)*2,0)+path.length*8);if(issues.length)budget.charge('diagnosticBytes',160+part.length);result.push({scope:selected,part,path:[...path],namespace:node.namespace,localName:node.localName,attributes,status:stored?'stored':'opaque',issues});inert=associated;}
  node.children.forEach((child,i)=>visit(child,[...path,i],selected,inert,context&&!(node.namespace===w&&!wordProperties.has(node.localName)),node.localName));};visit(root,base);return result;
}
