import {expect,it} from 'vitest';import {Volume} from 'memfs';
import {inspectDocumentEquations,addDocumentEquation,replaceDocumentEquation} from './equations.js';
import {equationFixture,equationContext,inlineEquation} from '../tests/fixtures/equations.js';
import {openDocumentLocations} from './locations.js';
it.each([false,true])('groups physical equation units and preserves expression identity in dialect %s',async strict=>{const data=await inspectDocumentEquations(await equationFixture({strict}),{},equationContext);expect(data.items.map(x=>x.details.mode)).toEqual(['inline','display']);expect(data.items.map(x=>x.details.mathPaths.length)).toEqual([1,2]);expect(data.items.every(x=>x.details.active&&x.details.status==='bounded'&&x.support==='edit')).toBe(true);expect(data.items[1]!.details.properties.map(p=>p.localName)).toEqual(['oMathParaPr','jc']);});
it.each([false,true])('adds and replaces current whole units with original memfs output in dialect %s',async strict=>{const input=await equationFixture({strict}),paragraph=(await openDocumentLocations(input,equationContext)).list('paragraph')[0]!,volume=Volume.fromJSON({'/out':''}),context={...equationContext,encoding:{order:'input' as const,compression:'store' as const},stdout:{async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}}};const file={kind:'bytes' as const,base64:btoa(inlineEquation(strict,'b'))};const added=await addDocumentEquation(input,{operation:'equations.add',options:{select:paragraph.token,file,output:'-'}},context);expect(added.changed).toBe(true);expect(added.changes).toHaveLength(1);expect(added.changes[0]!.after.value.generation).toBe(1);const bytes=new Uint8Array(volume.readFileSync('/out') as Buffer),data=await inspectDocumentEquations(bytes,{},equationContext);expect(data.items).toHaveLength(3);volume.writeFileSync('/out','');const replaced=await replaceDocumentEquation(bytes,{operation:'equations.replace',options:{select:data.items[0]!.location.token,file,output:'-'}},context);expect(replaced.changed).toBe(true);expect((await inspectDocumentEquations(new Uint8Array(volume.readFileSync('/out') as Buffer),{},equationContext)).items).toHaveLength(3);});
it('rejects stale host before fragment capability acquisition',async()=>{let opens=0;const input=await equationFixture(),other=await equationFixture({body:'<w:p/>'}),token=(await openDocumentLocations(other,equationContext)).list('paragraph')[0]!.token;await expect(addDocumentEquation(input,{operation:'equations.add',options:{select:token,file:{kind:'vfs',path:'/fragment',capability:'owned'},dryRun:true}},{...equationContext,encoding:{order:'input',compression:'store'},binaryResolver:{capability:'owned',async *open(){opens++;yield new Uint8Array();}}})).rejects.toMatchObject({code:'stale-selection'});expect(opens).toBe(0);});
it('edits exposed transparent math branches while preserving inactive siblings',async()=>{const ns='http://schemas.openxmlformats.org/officeDocument/2006/math',body='<w:p xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:m="'+ns+'" xmlns:x="urn:original:opaque"><w:r><w:t>coast</w:t></w:r><mc:AlternateContent><mc:Choice Requires="m">'+inlineEquation()+'</mc:Choice><mc:Fallback><x:opaque>'+inlineEquation(false,'q')+'</x:opaque></mc:Fallback></mc:AlternateContent></w:p>',input=await equationFixture({body}),data=await inspectDocumentEquations(input,{},equationContext);expect(data.items.map(i=>[i.details.active,i.support])).toEqual([[true,'edit'],[false,'preserve']]);await expect(replaceDocumentEquation(input,{operation:'equations.replace',options:{select:data.items[0]!.location.token,file:{kind:'bytes',base64:btoa(inlineEquation(false,'z'))},dryRun:true}},{...equationContext,encoding:{order:'input',compression:'store'}})).resolves.toMatchObject({changed:true});});
it('bounds repeated physical equations without rescanning immutable protection XML per unit',async()=>{const input=await equationFixture({body:'<w:p>'+Array.from({length:20},()=>inlineEquation()).join('')+'</w:p>'});expect((await inspectDocumentEquations(input,{limit:[{name:'xmlNodes',value:700}]},equationContext)).items).toHaveLength(20);});
it.each([false,true])('censuses orphan global metadata and opaque foreign hosts in dialect %s',async strict=>{const {equationNamespace}=await import('../tests/fixtures/equations.js'),ns=equationNamespace(strict),w=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':'http://schemas.openxmlformats.org/wordprocessingml/2006/main',input=await equationFixture({strict,body:'<w:p/>',resources:[{name:'misc/settings.xml',type:'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml',bytes:'<w:settings xmlns:w="'+w+'" xmlns:m="'+ns+'"><m:mathPr><m:mathFont m:val="Original"/><m:mathFont/></m:mathPr></w:settings>'},{name:'misc/opaque.xml',type:'application/xml',bytes:'<x:opaque xmlns:x="urn:original:opaque">'+inlineEquation(strict)+'</x:opaque>'}]});const data=await inspectDocumentEquations(input,{},equationContext);expect(data.globalProperties.map(p=>p.localName)).toEqual(['mathPr','mathFont','mathFont']);expect(data.globalProperties.every(p=>p.scope==='global'&&p.status==='stored')).toBe(true);expect(data.items).toHaveLength(1);expect(data.items[0]!.support).toBe('preserve');expect(data.items[0]!.details.active).toBe(false);});
it.each(['<w:sdt><w:sdtContent>','<w:ins w:id="1" w:author="Original">','<w:fldSimple w:instr="Original">'])('refuses compound paragraph host before opening fragment %s',prefix=>{return (async()=>{const suffix=prefix.startsWith('<w:sdt>')?'</w:sdtContent></w:sdt>':prefix.startsWith('<w:ins w:id="1" w:author="Original">')?'</w:ins>':'</w:fldSimple>',input=await equationFixture({body:prefix+'<w:p>'+inlineEquation()+'</w:p>'+suffix}),paragraph=(await openDocumentLocations(input,equationContext)).list('paragraph')[0]!,data=await inspectDocumentEquations(input,{},equationContext);expect(data.items[0]!.support).toBe('preserve');let opens=0;await expect(addDocumentEquation(input,{operation:'equations.add',options:{select:paragraph.token,file:{kind:'vfs',path:'/fragment',capability:'owned'},dryRun:true}},{...equationContext,encoding:{order:'input',compression:'store'},binaryResolver:{capability:'owned',async open(){opens++;throw Error('unreachable');}}})).rejects.toMatchObject({code:'unsupported-edit',location:{token:paragraph.token}});expect(opens).toBe(0);})();});
it('owns input/options and bounds serialization and producer acquisition',async()=>{const input=await equationFixture(),pending=inspectDocumentEquations(input,{},equationContext);input.fill(0);expect((await pending).items).toHaveLength(2);await expect(inspectDocumentEquations(await equationFixture(),{scope:'body'} as never,equationContext)).rejects.toMatchObject({code:'usage'});await expect(inspectDocumentEquations(await equationFixture(),{limit:[{name:'serializedOutput',value:100}]},equationContext)).rejects.toMatchObject({code:'limit-exceeded'});await expect(inspectDocumentEquations(await equationFixture(),{},{...equationContext,signal:AbortSignal.abort()})).rejects.toMatchObject({code:'cancelled'});const source=await equationFixture(),select=(await openDocumentLocations(source,equationContext)).list('paragraph')[0]!.token,options={select,file:{kind:'bytes' as const,base64:btoa(inlineEquation())},dryRun:true};const mutation=addDocumentEquation(source,{operation:'equations.add',options},{...equationContext,encoding:{order:'input',compression:'store'}});options.file.base64='';options.select='changed';expect((await mutation).changed).toBe(true);});
it.each([addDocumentEquation,replaceDocumentEquation])('invalid operation stays an asynchronous rejection',utility=>{let pending:Promise<unknown>|undefined;expect(()=>{pending=utility(new Uint8Array(),{operation:'wrong',options:{}} as never,{} as never);}).not.toThrow();expect(pending).toBeInstanceOf(Promise);return expect(pending).rejects.toMatchObject({code:'usage'});});
it.each(['operation','path','stat'])('rejects own-data accessor %s without executing it',async field=>{let reads=0;const request={operation:'equations.add',options:{},input:{path:'/document',stat:{type:'file'}}};const object=field==='operation'?request:field==='path'?request.input:request.input.stat,key=field==='stat'?'type':field;Object.defineProperty(object,key,{get(){reads++;return field==='operation'?'equations.add':field==='path'?'/document':'file';},enumerable:true});await expect(addDocumentEquation(new Uint8Array(),request as never,{} as never)).rejects.toMatchObject({code:'usage'});expect(reads).toBe(0);});
it('unchanged replacement and fabricated inner display token respect whole physical units',async()=>{const {encodeLocation}=await import('./location-token.js'),input=await equationFixture(),data=await inspectDocumentEquations(input,{},equationContext),inline=data.items[0]!,display=data.items[1]!,context={...equationContext,encoding:{order:'input' as const,compression:'store' as const}},file={kind:'bytes' as const,base64:btoa(inlineEquation())};expect(await replaceDocumentEquation(input,{operation:'equations.replace',options:{select:inline.location.token,file,dryRun:true}},context)).toMatchObject({changed:false,changes:[],output:null});let opens=0;await expect(replaceDocumentEquation(input,{operation:'equations.replace',options:{select:encodeLocation({...display.location.value,path:display.details.mathPaths[0]!}),file:{kind:'vfs',path:'/fragment',capability:'owned'},dryRun:true}},{...context,binaryResolver:{capability:'owned',async *open(){opens++;yield new Uint8Array();}}})).rejects.toMatchObject({code:'stale-selection'});expect(opens).toBe(0);});
it('owns reused producer chunks and closes bounded or cancelled acquisition without publication',async()=>{const input=await equationFixture(),select=(await openDocumentLocations(input,equationContext)).list('paragraph')[0]!.token,bytes=new TextEncoder().encode(inlineEquation(false,'b')),context={...equationContext,encoding:{order:'input' as const,compression:'store' as const}},file={kind:'vfs' as const,path:'/fragment',capability:'owned'},buffer=new Uint8Array(bytes.length),middle=Math.floor(bytes.length/2);let closed=false,writes=0;const result=await addDocumentEquation(input,{operation:'equations.add',options:{select,file,dryRun:true}},{...context,binaryResolver:{capability:'owned',async *open(){try{buffer.set(bytes.subarray(0,middle));yield buffer.subarray(0,middle);buffer.fill(0);buffer.set(bytes.subarray(middle));yield buffer.subarray(0,bytes.length-middle);buffer.fill(0);}finally{closed=true;}}}});expect(result.changed).toBe(true);expect(closed).toBe(true);closed=false;await expect(addDocumentEquation(input,{operation:'equations.add',options:{select,file,limit:[{name:'xmlPartBytes',value:1024}],output:'-'}},{...context,stdout:{async write(){writes++;}},binaryResolver:{capability:'owned',async *open(){try{yield new Uint8Array(1025);}finally{closed=true;}}}})).rejects.toMatchObject({code:'limit-exceeded'});expect(closed).toBe(true);expect(writes).toBe(0);const controller=new AbortController();closed=false;await expect(addDocumentEquation(input,{operation:'equations.add',options:{select,file,output:'-'}},{...context,signal:controller.signal,stdout:{async write(){writes++;}},binaryResolver:{capability:'owned',async *open(){try{yield bytes.subarray(0,2);controller.abort();yield bytes.subarray(2);}finally{closed=true;}}}})).rejects.toMatchObject({code:'cancelled'});expect(closed).toBe(true);expect(writes).toBe(0);});

it.each([[false,'add'],[false,'replace'],[true,'add'],[true,'replace']] as const)('edits a native paragraph inside the selected transparent branch in dialect %s with %s',async (strict,operation)=>{const ns=strict?'http://purl.oclc.org/ooxml/officeDocument/math':'http://schemas.openxmlformats.org/officeDocument/2006/math',inactive='<w:p><w:r><w:t>reserve</w:t></w:r>'+inlineEquation(strict,'q')+'</w:p>',body='<mc:AlternateContent xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:m="'+ns+'"><mc:Choice Requires="m"><w:p>'+inlineEquation(strict)+'</w:p></mc:Choice><mc:Fallback>'+inactive+'</mc:Fallback></mc:AlternateContent>',input=await equationFixture({body,strict}),data=await inspectDocumentEquations(input,{},equationContext);expect(data.items.map(i=>[i.details.active,i.support])).toEqual([[true,'edit'],[false,'preserve']]);const paragraph=(await openDocumentLocations(input,equationContext)).list('paragraph')[0]!,volume=Volume.fromJSON({'/out':''}),context={...equationContext,encoding:{order:'input' as const,compression:'store' as const},stdout:{async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}}},file={kind:'bytes' as const,base64:btoa(inlineEquation(strict,'z'))};const result=operation==='add'?await addDocumentEquation(input,{operation:'equations.add',options:{select:paragraph.token,file,output:'-'}},context):await replaceDocumentEquation(input,{operation:'equations.replace',options:{select:data.items[0]!.location.token,file,output:'-'}},context);expect(result.changed).toBe(true);const output=new Uint8Array(volume.readFileSync('/out') as Buffer),{readDocumentArchive}=await import('./admission.js'),archive=await readDocumentArchive(output,equationContext),xml=new TextDecoder().decode(archive.members.find(m=>m.name==='word/document.xml')!.bytes);expect(xml).toContain('<mc:Fallback>'+inactive+'</mc:Fallback>');expect((await inspectDocumentEquations(output,{},equationContext)).items).toHaveLength(operation==='add'?3:2);});

it.each([false,true])('identical replacement retains zero affected no-op with allowEmpty %s',async allowEmpty=>{const input=await equationFixture(),data=await inspectDocumentEquations(input,{},equationContext),volume=Volume.fromJSON({'/out':''}),result=await replaceDocumentEquation(input,{operation:'equations.replace',options:{select:data.items[0]!.location.token,file:{kind:'bytes',base64:btoa(inlineEquation())},allowEmpty,output:'-'}},{...equationContext,encoding:{order:'input',compression:'store'},stdout:{async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}}});expect(result).toMatchObject({changed:false,changes:[]});expect(new Uint8Array(volume.readFileSync('/out') as Buffer)).toEqual(input);});

it.each([[false,'drawing'],[true,'drawing'],[false,'attribute'],[true,'attribute']] as const)('refuses unsupported paragraph namespace context before fragment acquisition in dialect %s for %s',async (strict,contextKind)=>{
 const drawingNamespace=strict?'http://purl.oclc.org/ooxml/drawingml/main':'http://schemas.openxmlformats.org/drawingml/2006/main';
 const body=contextKind==='drawing'?'<w:p><w:r><w:drawing><a:graphic xmlns:a="'+drawingNamespace+'"/></w:drawing></w:r>'+inlineEquation(strict)+'</w:p>':'<w:p xmlns:x="urn:original:metadata" x:flag="original">'+inlineEquation(strict)+'</w:p>';
 const input=await equationFixture({strict,body}),paragraph=(await openDocumentLocations(input,equationContext,'inventory')).list('paragraph')[0]!,data=await inspectDocumentEquations(input,{},equationContext),equation=data.items[0]!;
 let opens=0,writes=0;
 const context={...equationContext,encoding:{order:'input' as const,compression:'store' as const},stdout:{async write(){writes++;}},binaryResolver:{capability:'owned',async open(){opens++;throw Error('Fragment input must remain unopened.');}}};
 const file={kind:'vfs' as const,path:'/fragment',capability:'owned'};
 await expect(addDocumentEquation(input,{operation:'equations.add',options:{select:paragraph.token,file,output:'-'}},context)).rejects.toMatchObject({code:'unsupported-edit',location:{token:paragraph.token}});
 await expect(replaceDocumentEquation(input,{operation:'equations.replace',options:{select:equation.location.token,file,output:'-'}},context)).rejects.toMatchObject({code:'unsupported-edit',location:{token:equation.location.token}});
 expect(opens).toBe(0);expect(writes).toBe(0);
 expect(equation).toMatchObject({support:'preserve',details:{status:'bounded'}});
 expect(equation.details.issues).toEqual(expect.arrayContaining([expect.objectContaining({code:'opaque-equation-host'})]));
});
