import { expect, it } from "vitest";
import { Volume } from "memfs";
import { MemoryFileSystem, Shell } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import * as api from "./index.js";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";

for (const strict of [false, true]) for (const carrier of ["direct", "choice", "fallback", "process"] as const) for (const scenario of ["font", "paragraph", "base"] as const) for (const route of ["sdk", "shell"] as const)
it(`${route} edits declared ${scenario} fields on existing native numbering definition through ${carrier}; strict=${strict}`, async () => {
  const definition = '<w:style w:type="numbering" w:styleId="list"><w:name w:val="Original List"/><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="0"/></w:numPr></w:pPr><!--keep--></w:style>', inactive = '<w:style w:type="numbering" w:styleId="inactive"><w:name w:val="Inactive"/></w:style>', wrapped = carrier === "direct" ? definition : carrier === "process" ? `<f:pass>${definition}</f:pass><f:opaque>${inactive}</f:opaque>` : `<mc:AlternateContent><mc:Choice Requires="${carrier === "choice" ? "w" : "f"}">${carrier === "choice" ? definition : inactive}</mc:Choice><mc:Fallback>${carrier === "fallback" ? definition : inactive}</mc:Fallback></mc:AlternateContent>`;
  const input = await textFixture('<w:p><w:r><w:t>Keep 日本 עברית 🌊</w:t></w:r></w:p>', { styles: { kind: "styles", xml: `<w:styles xmlns:w="${w}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:direct-number" mc:Ignorable="f" mc:ProcessContent="f:pass"><w:style w:type="numbering" w:styleId="base"><w:name w:val="Original Base"/><w:rPr><w:b/></w:rPr></w:style>${wrapped}</w:styles>` } }, strict), memory = Volume.fromJSON({ "/out": "" }), patch = scenario === "font" ? { bold: false, font: "Original 日本 Serif", rtl: true, language: "he-IL" } : scenario === "paragraph" ? { keepWithNext: false, spaceBefore: { value: 0, unit: "pt" as const }, leftIndent: { value: -1, unit: "pt" as const } } : { base: "Original Base" }, sink = { async write(bytes: Uint8Array) { memory.appendFileSync("/out", bytes); } };
  if (route === "sdk") await api.editDocumentStyles(input, { operation: "styles.set", name: "Original List", ...patch, output: "-" }, { ...textContext, encoding: { order: "input", compression: "store" }, stdout: sink });
  else { const fs = new MemoryFileSystem(); await fs.writeFile("/input", input); const shell = new Shell({ fs }).use(docxCommands({ engine: api.createDocxInspectionCommandEngine({ limits: textContext.limits }) })); try { const flags = scenario === "font" ? "--bold false --font 'Original 日本 Serif' --rtl true --language he-IL" : scenario === "paragraph" ? "--keep-with-next false --space-before 0pt --left-indent=-1pt" : "--base 'Original Base'", result = await shell.exec(`docx styles set /input --name 'Original List' ${flags} --output - > /out`); expect(result.exitCode, result.stdout + result.stderr).toBe(0); memory.writeFileSync("/out", await fs.readFile("/out")); expect(await fs.readFile("/input")).toEqual(input); } finally { await shell.dispose(); } }
  const output = new Uint8Array(memory.readFileSync("/out") as Buffer), after = readPackage(output); assertPackageLinks(after); for (const [name, bytes] of readPackage(input)) if (name !== "word/styles.xml") expect(after.get(name), name).toEqual(bytes);
  const report = (await api.inspectDocumentStyles(output, { name: "Original List" }, textContext)).styles[0]!;
  if (scenario === "font") expect(report.direct).toMatchObject({ bold: false, font: "Original 日本 Serif", rtl: true, language: "he-IL" }); else if (scenario === "paragraph") expect(report.direct).toMatchObject({ keepWithNext: false, spaceBefore: 0, leftIndent: -1 }); else expect(report).toMatchObject({ base: "Original Base", effective: { bold: true } });
  const style = (await api.Document(output, textContext)).styles.at("Original List"); expect("font" in style).toBe(false); expect("base_style" in style).toBe(false); const xml = new TextDecoder().decode(after.get("word/styles.xml")); expect(xml).toContain('<w:numPr><w:ilvl w:val="0"/><w:numId w:val="0"/></w:numPr>'); expect(xml.split("<!--keep-->")).toHaveLength(2); if (carrier !== "direct") expect(xml.split(inactive)).toHaveLength(2);
});
