import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const carrier of ['direct','choice','fallback','process'] as const)for(const member of ['text','add_run'] as const)for(const route of ['model','sdk','shell'] as const)
it(`${route} admits paragraph ${member} null with native retention; strict=${strict}; kind=${kind}; carrier=${carrier}`,async()=>{
 const active='<w:p><w:pPr><w:keepNext/><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:b/></w:rPr><w:t>é 日本 עברית 🌊</w:t></w:r></w:p>',body=carrier==='direct'?active:carrier==='process'?`<f:pass>${active}</f:pass><f:opaque f:identity="retained"><w:p><w:r><w:t>Inactive</w:t></w:r></w:p></f:opaque>`:`<mc:AlternateContent><mc:Choice Requires="${carrier==='choice'?'w':'f'}"${carrier==='fallback'?' f:identity="retained"':''}>${carrier==='choice'?active:'<w:p><w:r><w:t>Inactive</w:t></w:r></w:p>'}</mc:Choice><mc:Fallback${carrier==='choice'?' f:identity="retained"':''}>${carrier==='fallback'?active:'<w:p><w:r><w:t>Inactive</w:t></w:r></w:p>'}</mc:Fallback></mc:AlternateContent>`,parts=readPackage(await textFixture(`<w:p xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:paragraph-null" mc:Ignorable="f" mc:ProcessContent="f:pass"/>`,{styles:{kind:'styles',xml:`<w:styles xmlns:w="${w}"><w:style w:type="paragraph" w:styleId="Survey"><w:name w:val="Survey"/></w:style></w:styles>`}},strict)),ns=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w,xml=new TextDecoder().decode(parts.get('word/document.xml'));
 const root=xml.slice(0,xml.indexOf('<w:body>')).replace('<w:document ', '<w:document xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:paragraph-null" mc:Ignorable="f" mc:ProcessContent="f:pass" ');parts.set('word/document.xml',new TextEncoder().encode(root+`<w:body>${body}</w:body></w:document>`));if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));
 const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),sink={async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}},operations=[{operation:'model.document.Document.paragraphs.get',receiver:ref('document'),arguments:{},resultHandle:'paragraphs'},{operation:`model.text.paragraph.Paragraph.${member}.${member==='text'?'set':'call'}`,receiver:ref('paragraphs',0),arguments:member==='text'?{value:null}:{text:null,style:null}}];
 if(route==='model'){const doc=await api.Document(input,textContext),p=doc.paragraphs[0]!,old=p.runs[0]!;if(member==='text'){p.text=null;expect(()=>old.text).toThrow(api.StaleHandleError);}else{const added=p.add_run(null,null);expect(added.text).toBe('');expect(added.equals(p.runs[1])).toBe(true);expect(old.text).toBe('é 日本 עברית 🌊');}await doc.save(sink);}else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);await batch.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const r=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --json`);expect(r.exitCode,r.stdout+r.stderr).toBe(0);expect(await fs.readFile('/input')).toEqual(input);volume.writeFileSync('/out',await fs.readFile('/out'));}finally{await shell.dispose();}}
 const output=new Uint8Array(volume.readFileSync('/out') as Buffer),after=readPackage(output);assertPackageLinks(after);for(const[name,bytes]of parts)if(name!=='word/document.xml')expect(after.get(name),name).toEqual(bytes);const p=(await api.Document(output,textContext)).paragraphs[0]!;expect(p.text).toBe(member==='text'?'':'é 日本 עברית 🌊');expect(p.runs).toHaveLength(member==='text'?0:2);expect(p.paragraph_format.keep_with_next).toBe(true);expect(p.alignment).toEqual(api.WD_PARAGRAPH_ALIGNMENT.CENTER);expect(p.element.namespace).toBe(ns);if(member==='add_run'){expect(p.runs[0]!.bold).toBe(true);expect(p.runs[1]!.text).toBe('');}if(carrier!=='direct')expect(new TextDecoder().decode(after.get('word/document.xml'))).toContain('f:identity="retained"');expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));
});
