import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { textContext, textFixture, w, r } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
type Case = {row:number; inner:string; member:string; value?:unknown; expected?:unknown; after?:string; style?:string|null|undefined};
const cases:Case[]=[
 ...[['<w:r/>',false],['<w:r><w:t>foobar</w:t></w:r>',false],['<w:hyperlink><w:r><w:t>abc</w:t><w:lastRenderedPageBreak/><w:t>def</w:t></w:r></w:hyperlink>',true],['<w:r><w:lastRenderedPageBreak/><w:lastRenderedPageBreak/></w:r>',true]].map(([inner,expected],i)=>({row:1309+i,inner:inner as string,member:'contains_page_break',expected})),
 ...['','<w:r/>','<w:hyperlink/>','<w:r/><w:hyperlink/><w:r/>','<w:r/><w:hyperlink/><w:r/><w:hyperlink/>','<w:hyperlink/><w:r/><w:hyperlink/><w:r/>'].map((inner,i)=>({row:1313+i,inner,member:'hyperlinks',expected:[0,0,1,1,2,2][i]})),
 ...[['',[]],['<w:r/>',['Run']],['<w:hyperlink/>',['Hyperlink']],['<w:r/><w:hyperlink/><w:r/>',['Run','Hyperlink','Run']],['<w:hyperlink/><w:r/><w:hyperlink/>',['Hyperlink','Run','Hyperlink']]].map(([inner,expected],i)=>({row:1319+i,inner:inner as string,member:'iter_inner_content',expected})),
 {row:1324,inner:'<w:pPr><w:pStyle w:val="Foobar"/></w:pPr>',member:'style',expected:'Foobar'},
 ...[['','Heading 1','<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>'],['<w:pPr/>','Heading 1','<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>'],['<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>','Heading 2','<w:pPr><w:pStyle w:val="Heading2"/></w:pPr>'],['<w:pPr><w:pStyle w:val="Heading1"/></w:pPr>','Normal','<w:pPr/>'],['',null,'<w:pPr/>']].map(([inner,value,after],i)=>({row:1325+i,inner:inner as string,member:'style',value,after:after as string})),
 ...['','<w:r/>','<w:r><w:lastRenderedPageBreak/></w:r>','<w:hyperlink><w:r><w:lastRenderedPageBreak/></w:r></w:hyperlink>','<w:r><w:lastRenderedPageBreak/></w:r><w:hyperlink><w:r><w:lastRenderedPageBreak/></w:r></w:hyperlink>','<w:hyperlink><w:r><w:lastRenderedPageBreak/></w:r></w:hyperlink><w:r/><w:r><w:lastRenderedPageBreak/></w:r><w:r/><w:hyperlink/>'].map((inner,i)=>({row:1330+i,inner,member:'rendered_page_breaks',expected:[0,0,1,1,2,2][i]})),
 ...[['',''],['<w:r/>',''],['<w:r><w:t/></w:r>',''],['<w:r><w:t>foo</w:t></w:r>','foo'],['<w:r><w:t>foo</w:t><w:t>bar</w:t></w:r>','foobar'],['<w:r><w:t>fo </w:t><w:t>bar</w:t></w:r>','fo bar'],['<w:r><w:t>foo</w:t><w:tab/><w:t>bar</w:t></w:r>','foo\tbar'],['<w:r><w:t>foo</w:t><w:br/><w:t>bar</w:t></w:r>','foo\nbar'],['<w:r><w:t>foo</w:t><w:cr/><w:t>bar</w:t></w:r>','foo\nbar'],['<w:r><w:t>click </w:t></w:r><w:hyperlink r:id="rId6"><w:r><w:t>here</w:t></w:r></w:hyperlink><w:r><w:t> for more</w:t></w:r>','click here for more']].map(([inner,expected],i)=>({row:1336+i,inner:inner!,member:'text',expected})),
 {row:1346,inner:'<w:r><w:t>must not appear in result</w:t></w:r>',member:'text',value:'foo\tbar\rbaz\n',expected:'foo\tbar\nbaz\n'},
 {row:1347,inner:'<w:pPr><w:jc w:val="center"/></w:pPr>',member:'alignment',expected:api.WD_PARAGRAPH_ALIGNMENT.CENTER},
 {row:1348,inner:'',member:'alignment',expected:null},
 ...[['',api.WD_PARAGRAPH_ALIGNMENT.LEFT,'<w:pPr><w:jc w:val="left"/></w:pPr>'],['<w:pPr><w:jc w:val="left"/></w:pPr>',api.WD_PARAGRAPH_ALIGNMENT.CENTER,'<w:pPr><w:jc w:val="center"/></w:pPr>'],['<w:pPr><w:jc w:val="left"/></w:pPr>',null,'<w:pPr/>'],['',null,'<w:pPr/>']].map(([inner,value,after],i)=>({row:1349+i,inner:inner as string,member:'alignment',value,after:after as string})),
 {row:1353,inner:'',member:'paragraph_format',expected:'ParagraphFormat'},
 {row:1354,inner:'<w:r><w:t>First native run</w:t></w:r><w:r><w:t>Second native run</w:t></w:r>',member:'runs',expected:2},
 ...[[null,null],['foobar',null],[null,'Strong'],['foobar','Strong']].map(([value,style],i)=>({row:1355+i,inner:'',member:'add_run',value,style})),
 ...[[null,null],['Foo',null],[null,'Bar'],['Foo','Bar']].map(([value,style],i)=>({row:1359+i,inner:'',member:'insert_paragraph_before',value,style})),
 ...[['',''],['<w:pPr/>','<w:pPr/>'],['<w:r><w:t>foobar</w:t></w:r>',''],['<w:pPr/><w:r><w:t>foobar</w:t></w:r>','<w:pPr/>']].map(([inner,after],i)=>({row:1363+i,inner:inner!,member:'clear',after:after!})),
 {row:1367,inner:'',member:'insert_paragraph_before',value:null,style:null}
];
expect(cases.map(c=>c.row)).toEqual(Array.from({length:59},(_,i)=>1309+i));
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const c of cases)for(const route of ['model','sdk','shell'] as const)
it(`${route} independently executes exact paragraph witness R${c.row}; strict=${strict}; kind=${kind}`,async()=>{
 const ns=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w,rels=strict?'http://purl.oclc.org/ooxml/officeDocument/relationships':r,styles='<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/></w:style><w:style w:type="paragraph" w:styleId="Foobar"><w:name w:val="Foobar"/></w:style><w:style w:type="paragraph" w:styleId="Bar"><w:name w:val="Bar"/></w:style><w:style w:type="character" w:styleId="Strong"><w:name w:val="Strong"/></w:style>',parts=readPackage(await textFixture(`<w:p${c.row===1367?' id="42"':''}>${c.inner}</w:p><w:p><w:r><w:rPr><w:i/></w:rPr><w:t>Untouched é 日本 עברית 🌊</w:t></w:r></w:p>`,{styles:{kind:'styles',xml:`<w:styles xmlns:w="${w}">${styles}<!--styles--></w:styles>`}},strict)),memory=Volume.fromJSON({'/input':'','/out':''});
 const relationshipEditor=new api.DocumentXmlEditor(parts.get('word/_rels/document.xml.rels')!);relationshipEditor.insertChildren(relationshipEditor.root,`<Relationship xmlns="http://schemas.openxmlformats.org/package/2006/relationships" Id="rId6" Type="${rels}/hyperlink" Target="https://example.invalid/original" TargetMode="External"/>`);parts.set('word/_rels/document.xml.rels',relationshipEditor.serialize());
 if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));
 await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){memory.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);
 const input=new Uint8Array(memory.readFileSync('/input') as Buffer),sink={async write(bytes:Uint8Array){memory.appendFileSync('/out',bytes);}},mutation=Object.hasOwn(c,'value')||c.member==='clear',method=['iter_inner_content','add_run','insert_paragraph_before','clear'].includes(c.member),args=c.member==='add_run'||c.member==='insert_paragraph_before'?{text:c.value,style:c.style}:Object.hasOwn(c,'value')?{value:c.value}:{},operations:{operation:string;receiver:ReturnType<typeof ref>;arguments:Record<string,unknown>;resultHandle?:string}[]=[{operation:'model.document.Document.paragraphs.get',receiver:ref('document'),arguments:{},resultHandle:'paragraphs'},{operation:`model.text.paragraph.Paragraph.${c.member}.${method?'call':mutation?'set':'get'}`,receiver:ref('paragraphs',0),arguments:args,...(!mutation||method?{resultHandle:'observed'}:{})}];
 if(c.member==='style'&&!mutation)operations.push({operation:'model.styles.style.BaseStyle.name.get',receiver:ref('observed'),arguments:{}});if(c.member==='paragraph_format')operations.push({operation:'model.text.parfmt.ParagraphFormat.element.get',receiver:ref('observed'),arguments:{},resultHandle:'formatElement'},{operation:'model.XmlElementView.tag.get',receiver:ref('formatElement'),arguments:{}});
 const observe=(values:unknown[])=>{if(c.member==='iter_inner_content')expect((values.at(-1) as {type:string}[]).map(v=>v.type)).toEqual(c.expected);else if(['hyperlinks','rendered_page_breaks','runs'].includes(c.member))expect((values.at(-1) as unknown[]).length).toBe(c.expected);else if(c.member==='paragraph_format')expect(values.at(-1)).toEqual({namespaceURI:ns,localName:'p'});else if(!mutation)expect(values.at(-1)).toEqual(c.expected);};
 if(route==='model'){const doc=await api.Document(input,textContext),p=doc.paragraphs[0]!;if(c.member==='add_run'){const run=p.add_run(c.value as string|null,c.style);expect(run).toBeInstanceOf(api.Run);expect(run.equals(p.runs[0])).toBe(true);}else if(c.member==='insert_paragraph_before'){const inserted=p.insert_paragraph_before(c.value as string|null,c.style);expect(inserted.equals(doc.paragraphs[0])).toBe(true);expect(p.equals(doc.paragraphs[1])).toBe(true);}else if(c.member==='clear')expect(p.clear()).toBe(p);else if(c.member==='iter_inner_content')expect([...p.iter_inner_content()].map(v=>v instanceof api.Run?'Run':'Hyperlink')).toEqual(c.expected);else if(c.member==='paragraph_format'){expect(p.paragraph_format).toBeInstanceOf(api.ParagraphFormat);expect(p.paragraph_format.equals(p.paragraph_format)).toBe(true);expect(p.paragraph_format.element.serialize()).toEqual(p.element.serialize());expect(p.paragraph_format.part).toBe(p.part);}else if(c.member==='style'&&!mutation)expect(p.style!.equals(doc.styles.at('Foobar'))).toBe(true);else if(mutation)Reflect.set(p,c.member,c.value);else observe([Reflect.get(p,c.member)]);await doc.save(sink);}
 else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);observe(batch.results.map(r=>r.value));await batch.save(sink);}
 else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' ${mutation?'--output /out':''} --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);observe(JSON.parse(result.stdout).data.results.map((r:{data:unknown})=>r.data));expect(await fs.readFile('/input')).toEqual(input);if(mutation)memory.writeFileSync('/out',await fs.readFile('/out'));else await(await api.Document(input,textContext)).save(sink);}finally{await shell.dispose();}}
 const output=new Uint8Array(memory.readFileSync('/out') as Buffer),after=readPackage(output);assertPackageLinks(after);for(const[name,bytes]of parts)if(name!=='word/document.xml')expect(after.get(name),name).toEqual(bytes);
 const doc=await api.Document(output,textContext),p=doc.paragraphs[0]!;expect(doc.paragraphs.at(-1)!.text).toBe('Untouched é 日本 עברית 🌊');expect(doc.paragraphs.at(-1)!.runs[0]!.italic).toBe(true);
 const snapshot=(bytes:Uint8Array)=>{const root=new api.DocumentXmlEditor(bytes).root;const visit=(node:typeof root):unknown=>({name:[node.namespace,node.localName],attributes:node.attributes.filter(a=>a.namespace!=='http://www.w3.org/2000/xmlns/'&&!(node.localName==='t'&&a.namespace==='http://www.w3.org/XML/1998/namespace'&&a.localName==='space'&&a.value==='preserve'&&node.text.trim()===node.text)).map(a=>[a.namespace,a.localName,a.value]).sort(),content:node.content.map(n=>n.kind==='element'?visit(n):n)});return visit(root);};
 if(c.after!==undefined)expect(snapshot(p.element.serialize())).toEqual(snapshot(new TextEncoder().encode(`<w:p xmlns:w="${ns}">${strict&&c.row===1349?c.after.replace('w:val="left"','w:val="start"'):c.after}</w:p>`)));
 if(c.member==='text'&&mutation){expect(p.text).toBe(c.expected);expect(p.runs.every(run=>run.bold===null&&run.italic===null)).toBe(true);}if(c.member==='add_run'){expect(p.text).toBe(c.value??'');expect(p.runs).toHaveLength(1);if(c.style)expect(p.runs[0]!.style!.equals(doc.styles.at(c.style))).toBe(true);else expect(p.runs[0]!.style).toBeNull();}if(c.member==='insert_paragraph_before'){expect(doc.paragraphs).toHaveLength(3);expect(p.text).toBe(c.value??'');expect(p.runs).toHaveLength(c.value?1:0);expect(p.style!.name).toBe(c.style??'Normal');expect(doc.paragraphs[1]!.text).toBe('');if(c.row===1367)expect([...doc.paragraphs[1]!.element.attributes].find(([name])=>name.localName==='id')?.[1]).toBe('42');}
 if(!mutation)expect(after.get('word/document.xml')).toEqual(parts.get('word/document.xml'));expect(memory.readFileSync('/input')).toEqual(Buffer.from(input));
});
