import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const carrier of ['direct','choice','fallback','process'] as const)for(const text of [null,'Survey é 日本 עברית 🌊'] as const)for(const style of [null,'Survey'] as const)for(const route of ['model','sdk','shell'] as const)
it(`${route} inserts a paragraph at the active native carrier boundary; strict=${strict}; kind=${kind}; carrier=${carrier}; text=${text}; style=${style}; source=R1359-R1362`,async()=>{
 const marker='<w:p><w:r><w:rPr><w:b/></w:rPr><w:t>é 日本 עברית 🌊</w:t></w:r><!--retain--><?audit keep?></w:p>',active=carrier==='direct'?marker:carrier==='process'?`<f:pass>${marker}</f:pass><f:opaque f:identity="retained"/>`:`<mc:AlternateContent><mc:Choice Requires="${carrier==='choice'?'w':'f'}"${carrier==='fallback'?' f:identity="retained"':''}>${carrier==='choice'?marker:'<w:p/>'}</mc:Choice><mc:Fallback${carrier==='choice'?' f:identity="retained"':''}>${carrier==='fallback'?marker:'<w:p/>'}</mc:Fallback></mc:AlternateContent>`,raw=await textFixture('<w:p/>',{styles:{kind:'styles',xml:`<w:styles xmlns:w="${w}"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Survey"><w:name w:val="Survey"/></w:style></w:styles>`}},strict),parts=readPackage(raw),ns=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w;parts.set('word/document.xml',new TextEncoder().encode(`<w:document xmlns:w="${ns}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:paragraph-owner" mc:Ignorable="f" mc:ProcessContent="f:pass"><w:body>${active}</w:body></w:document>`));if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));
 const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),sink={async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}},operations=[{operation:'model.document.Document.paragraphs.get',receiver:ref('document'),arguments:{},resultHandle:'paragraphs'},{operation:'model.text.paragraph.Paragraph.insert_paragraph_before.call',receiver:ref('paragraphs',0),arguments:{text,style},resultHandle:'inserted'}];
 if(route==='model'){const doc=await api.Document(input,textContext),p=doc.paragraphs[0]!,run=p.runs[0]!;const inserted=p.insert_paragraph_before(text,style);expect(inserted.equals(doc.paragraphs[0])).toBe(true);expect(p.equals(doc.paragraphs[1])).toBe(true);expect(run.equals(p.runs[0])).toBe(true);await doc.save(sink);}else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);await batch.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const r=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --json`);expect(r.exitCode,r.stdout+r.stderr).toBe(0);expect(await fs.readFile('/input')).toEqual(input);volume.writeFileSync('/out',await fs.readFile('/out'));}finally{await shell.dispose();}}
 const output=new Uint8Array(volume.readFileSync('/out') as Buffer),after=readPackage(output);assertPackageLinks(after);for(const[name,bytes]of parts)if(name!=='word/document.xml')expect(after.get(name),name).toEqual(bytes);const doc=await api.Document(output,textContext),p=doc.paragraphs[0]!;expect(doc.paragraphs).toHaveLength(2);expect(p.style!.equals(doc.styles.at(style??'Normal'))).toBe(true);expect(p.text).toBe(text??'');expect(p.runs).toHaveLength(text?1:0);expect(doc.paragraphs[1]!.text).toBe('é 日本 עברית 🌊');expect(doc.paragraphs[1]!.runs[0]!.bold).toBe(true);expect(doc.paragraphs[1]!.element.children.map(n=>n.localName)).toEqual(['r']);const saved=new TextDecoder().decode(after.get('word/document.xml'));for(const token of ['<!--retain-->','<?audit keep?>',...(carrier==='direct'?[]:['f:identity="retained"'])])expect(saved.split(token)).toHaveLength(2);expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));
});
