import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { insertParagraphBefore } from "./xml-write.js";
import { Shell, MemoryFileSystem } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage } from "../tests/assertions.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
async function fixture(strict:boolean,kind:string,carrier:string){
 const ns=strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w,active='<w:p><w:r><w:t>Active é 日本 עברית 🌊</w:t></w:r></w:p>',inactive='<w:p><w:r><w:t>Inactive original</w:t></w:r></w:p>',body=carrier==='process'?`<f:pass>${active}</f:pass><f:opaque>${inactive}</f:opaque>`:`<mc:AlternateContent><mc:Choice Requires="${carrier==='choice'?'w':'f'}">${carrier==='choice'?active:inactive}</mc:Choice><mc:Fallback>${carrier==='fallback'?active:inactive}</mc:Fallback></mc:AlternateContent>`,parts=readPackage(await textFixture('<w:p/>',{},strict));parts.set('word/document.xml',new TextEncoder().encode(`<w:document xmlns:w="${ns}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:paragraph-guard" mc:Ignorable="f" mc:ProcessContent="f:pass"><w:body>${body}<!--retain--><?audit keep?></w:body></w:document>`));if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);return {input:new Uint8Array(volume.readFileSync('/input') as Buffer),volume,ns,parts};
}
for(const strict of [false,true])for(const kind of ['docx','dotx'])for(const carrier of ['choice','fallback','process'])for(const route of ['model','sdk','shell'])
it(`${route} retains generic opaque-carrier insertion refusal after typed paragraph insertion; strict=${strict}; kind=${kind}; carrier=${carrier}`,async()=>{
 const f=await fixture(strict,kind,carrier),node={kind:'element',name:{namespaceURI:f.ns,localName:'p'}} as const,operations=[{operation:'model.document.Document.element.get',receiver:ref('document'),arguments:{},resultHandle:'root'},{operation:'model.XmlElementView.children.get',receiver:ref('root'),arguments:{},resultHandle:'rootChildren'},{operation:'model.XmlElementView.children.get',receiver:ref('rootChildren',0),arguments:{},resultHandle:'bodyChildren'},...(carrier==='process'?[]:[{operation:'model.XmlElementView.children.get',receiver:ref('bodyChildren',0),arguments:{},resultHandle:'carrierChildren'}]),{operation:'model.XmlElementView.insert.call',receiver:carrier==='process'?ref('bodyChildren',0):ref('carrierChildren',carrier==='choice'?0:1),arguments:{index:0,node}}];
 if(route==='model'){const doc=await api.Document(f.input,textContext),physical=doc.element.children[0]!.children[0]!,owner=carrier==='process'?physical:physical.children[carrier==='choice'?0:1]!;expect(()=>owner.insert(0,node)).toThrow(api.UnsupportedEditError);await doc.save({async write(bytes){f.volume.appendFileSync('/out',bytes);}});for(const[name,bytes]of f.parts)expect(readPackage(new Uint8Array(f.volume.readFileSync('/out') as Buffer)).get(name),name).toEqual(bytes);}else if(route==='sdk')await expect(api.applyStyleModelBatch(f.input,{version:1,operations},textContext)).rejects.toMatchObject({code:'unsupported-edit'});else{const fs=new MemoryFileSystem();await fs.writeFile('/input',f.input);await fs.writeFile('/out',new TextEncoder().encode('Original destination'));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const r=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(r.exitCode,r.stdout+r.stderr).toBe(1);expect(JSON.parse(r.stdout).errors[0].code).toBe('unsupported-edit');expect(await fs.readFile('/input')).toEqual(f.input);expect(new TextDecoder().decode(await fs.readFile('/out'))).toBe('Original destination');}finally{await shell.dispose();}}
 expect(f.volume.readFileSync('/input')).toEqual(Buffer.from(f.input));
});
for(const strict of [false,true])for(const carrier of ['choice','fallback','process'])for(const boundary of ['inactive','foreign','empty','multiple','nonparagraph','nonstring'] as const)
it(`typed paragraph insertion authority rejects ${boundary} without dirtying XML; strict=${strict}; carrier=${carrier}`,async()=>{
 const f=await fixture(strict,'docx',carrier),editor=new api.DocumentXmlEditor(f.parts.get('word/document.xml')!),container=editor.root.children[0]!.children[0]!,active=carrier==='process'?container.children[0]!:container.children[carrier==='choice'?0:1]!.children[0]!,inactive=carrier==='process'?editor.root.children[0]!.children[1]!.children[0]!:container.children[carrier==='choice'?1:0]!.children[0]!,target=boundary==='foreign'?new api.DocumentXmlEditor(f.parts.get('word/document.xml')!).root:boundary==='inactive'?inactive:active,paragraph=`<p xmlns="${f.ns}"/>`,markup=boundary==='empty'?'':boundary==='multiple'?paragraph+paragraph:boundary==='nonparagraph'?`<r xmlns="${f.ns}"/>`:boundary==='nonstring'?null:paragraph;
 expect(()=>editor[insertParagraphBefore](target,markup as string)).toThrow();expect(editor.serialize()).toEqual(f.parts.get('word/document.xml'));
});
