import { expect, it } from "vitest";
import { Volume } from "memfs";
import * as api from "./index.js";
import { paragraph, textContext, textFixture } from "../tests/fixtures/text.js";

it("preserves sparse relationship keys, ordering, snapshots and atomic mutations", async () => {
  const volume = Volume.fromJSON({ "/input": Buffer.from(await textFixture(paragraph("Buoy locations"))) });
  const doc = await api.Document(new Uint8Array(volume.readFileSync("/input") as Buffer), textContext);
  const rels = doc.styles.part.rels;
  const low = rels.add_relationship("urn:low", "https://example.test/low", "rId0", true);
  const far = rels.add_relationship("urn:far", "https://example.test/far", "rId99", true);
  expect(rels.length).toBe(2);
  expect([...rels]).toEqual(["rId0", "rId99"]);
  expect([...rels.keys()]).toEqual(["rId0", "rId99"]);
  expect([...rels.values()]).toEqual([low, far]);
  expect([...rels.items()]).toEqual([["rId0", low], ["rId99", far]]);
  expect(Object.isFrozen([...rels.items()][0])).toBe(true);
  expect(rels.at("rId0")).toBe(low);
  expect(rels.at("rId99")).toBe(far);
  expect(rels.get("rId1")).toBeNull();
  expect(() => rels.at("rId1")).toThrow(api.MissingKeyError);
  for (const key of [0, 99, false, null]) {
    expect(() => rels.get(key as unknown as string)).toThrow(api.InputTypeError);
    expect(() => rels.has(key as unknown as string)).toThrow(api.InputTypeError);
  }
  const snapshot = rels.copy();
  const internal = rels.get_or_add("urn:owned", doc.part);
  expect(rels.get_or_add("urn:owned", doc.part)).toBe(internal);
  expect(rels.related_parts.get(internal.rId)).toBe(doc.part);
  expect(rels.part_with_reltype("urn:owned")).toBe(doc.part);
  expect(rels.get_or_add_ext_rel("urn:far", "https://example.test/far")).toBe("rId99");
  expect(snapshot.size).toBe(2);
  expect(rels.length).toBe(3);
  const secondary = await api.PartView.load("/data/secondary.bin", "application/octet-stream", new Uint8Array([7]), doc.part.package);
  const source = secondary.rels.add_relationship("urn:copied", doc.part, "rId7");
  rels.set("rId7", source);
  const copied = rels.at("rId7");
  expect(copied.target_part).toBe(doc.part);
  expect(copied).not.toBe(source);
  expect(rels.setdefault("rId7", source)).toBe(copied);
  rels.update([["rId7", source]]);
  expect(rels.at("rId7")).toBe(copied);
  const before = rels.xml;
  expect(() => rels.update([["rId7", source], ["rId7", source]])).toThrow(api.InputTypeError);
  expect(() => rels.set("rId8", source)).toThrow(api.InputTypeError);
  expect(rels.xml).toBe(before);
  expect(rels.popitem()).toEqual(["rId7", copied]);
  expect(() => copied.target_part).toThrow(api.StaleHandleError);
  expect(rels.pop("rId99")).toBe(far);
  expect([...rels]).toEqual(["rId0", internal.rId]);
  expect(() => far.reltype).toThrow(api.StaleHandleError);
  rels.clear();
  expect(rels.length).toBe(0);
  expect([...rels]).toEqual([]);
  expect(() => low.rId).toThrow(api.StaleHandleError);
  expect(() => rels.popitem()).toThrow(api.MissingKeyError);
  expect(secondary.rels.at("rId7")).toBe(source);
  expect(volume.readFileSync("/input")).toEqual(Buffer.from(await textFixture(paragraph("Buoy locations"))));
});
