import { expect, it } from "vitest";
import { Volume } from "memfs";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import { textContext, textFixture } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";

for (const strict of [false, true]) for (const carrier of ["choice", "fallback", "process"] as const) for (const depth of [1, 2]) for (const route of ["sdk", "shell"] as const) for (const opaque of carrier === "process" ? [true, false] : [false]) for (const operation of ["format", "replace"] as const)
 it(`${route} ${operation} scalar ranges with inner run-property ${carrier} at depth ${depth}; opaque=${opaque}; strict=${strict}`, async () => {
  const wrap = (active: string, identity: string) => carrier === "process" ? opaque ? `<f:pass>${active}</f:pass><f:opaque f:identity="${identity}"><w:i/></f:opaque>` : `<f:pass f:identity="${identity}">${active}</f:pass>` : `<mc:AlternateContent><mc:Choice Requires="${carrier === "choice" ? "w" : "f"}"${carrier === "fallback" ? ` f:identity="${identity}"` : ""}>${carrier === "choice" ? active : '<w:i/>'}</mc:Choice><mc:Fallback${carrier === "choice" ? ` f:identity="${identity}"` : ""}>${carrier === "fallback" ? active : '<w:i/>'}</mc:Fallback></mc:AlternateContent>`;
  let property = '<w:b/>'; for (let i = 0; i < depth; i++) property = wrap(property, `retained-${i}`);
  const input = await textFixture(`<w:p xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:inner-properties" mc:Ignorable="f" mc:ProcessContent="f:pass"><w:r><w:rPr>${property}<w:rtl/><w:color w:val="224466"/></w:rPr><w:t>coast</w:t></w:r></w:p>`, {}, strict), locations = await api.openDocumentLocations(input, textContext), p = locations.at("paragraph", 1), select = locations.range(locations.at("run", 1, { owner: p.token }).token, 1, 4).token, memory = Volume.fromJSON({ "/out": "" });
  if (route === "sdk") { const context = { ...textContext, encoding: { order: "input" as const, compression: "store" as const }, stdout: { async write(bytes: Uint8Array) { memory.appendFileSync("/out", bytes); } } }; const result = operation === "format" ? api.formatDocumentRuns(input, { select, bold: false, output: "-" }, context) : api.replaceDocumentText(input, { find: "oas", with: "shore", all: true, bold: false, output: "-" }, context); if (opaque) await expect(result).rejects.toMatchObject({ code: "unsupported-edit" }); else await result; }
  else { const fs = new MemoryFileSystem(); await fs.writeFile("/input", input); const shell = new Shell({ fs }).use(docxCommands({ engine: api.createDocxInspectionCommandEngine({ limits: textContext.limits }) })); try { const result = await shell.exec(operation === "format" ? `docx runs set /input --select '${select}' --bold false --output - > /out` : "docx text replace /input --find oas --with shore --all --bold false --output - > /out"); expect(result.exitCode, result.stdout + result.stderr).toBe(opaque ? 1 : 0); if (opaque) expect(result.stderr).toContain("unsupported-edit"); expect(await fs.readFile("/input")).toEqual(input); memory.writeFileSync("/out", await fs.readFile("/out")); } finally { await shell.dispose(); } }
  if (opaque) { expect(memory.readFileSync("/out")).toHaveLength(0); return; }
  const output = new Uint8Array(memory.readFileSync("/out") as Buffer), before = readPackage(input), after = readPackage(output); assertPackageLinks(after); for (const [name, bytes] of before) if (name !== "word/document.xml") expect(after.get(name), name).toEqual(bytes);
  const doc = await api.Document(output, textContext); expect(doc.paragraphs[0]!.runs.map(r => [r.text, r.bold])).toEqual([["c", true], [operation === "format" ? "oas" : "shore", false], ["t", true]]); expect(doc.paragraphs[0]!.runs.every(r => r.font.rtl === true && r.font.color.rgb?.toString() === "224466")).toBe(true); const xml = new TextDecoder().decode(after.get("word/document.xml")); for (let i = 0; i < depth; i++) expect(xml.split(`f:identity="retained-${i}"`)).toHaveLength(2);
 });
