import { expect, it } from "vitest";
import { Volume } from "memfs";
import { Shell, MemoryFileSystem } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import * as api from "./index.js";
import { nativeStoryFixture } from "../tests/fixtures/native-parts.js";
import { textContext } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const mc="http://schemas.openxmlformats.org/markup-compatibility/2006",x="urn:example:docx:first-page-carrier";
const samples=[{name:"remove-true",stored:"1",value:false},{name:"enable-false",stored:"0",value:true},{name:"normalize-true",stored:"1",value:true}];
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const carrier of ["direct","choice","fallback","process"] as const)for(const sample of samples)for(const route of ["model","sdk","shell"] as const)
it(`${route} edits ${sample.name} in native first-page ${carrier}; ${kind}; strict=${strict}`,async()=>{
 const marker=`<w:titlePg w:val="${sample.stored}"/>`,inert='<x:inactive x:key="preserve"><x:payload>Never activate</x:payload></x:inactive>',leaf=carrier==="direct"?marker:carrier==="choice"?`<mc:AlternateContent><mc:Choice Requires="w">${marker}</mc:Choice><mc:Fallback>${inert}</mc:Fallback></mc:AlternateContent>`:carrier==="fallback"?`<mc:AlternateContent><mc:Choice Requires="x">${inert}</mc:Choice><mc:Fallback>${marker}</mc:Fallback></mc:AlternateContent>`:`<x:through>${marker}</x:through>`;
 const section=`<w:sectPr xmlns:mc="${mc}" xmlns:x="${x}" mc:Ignorable="x"${carrier==="process"?' mc:ProcessContent="x:through"':""} x:metadata="retain"><!--keep--><?audit keep?>${leaf}</w:sectPr>`,f=await nativeStoryFixture("document.Document",strict,kind,'<w:p><w:r><w:t>Untouched é 日本 עברית 🌊</w:t></w:r></w:p>'+section),parts=readPackage(f.input),volume=Volume.fromJSON({"/out":""}),sink={async write(bytes:Uint8Array){volume.appendFileSync("/out",bytes);}};
 const operations=[{operation:"model.document.Document.sections.get",receiver:ref("document"),arguments:{},resultHandle:"sections"},{operation:"model.section.Section.different_first_page_header_footer.set",receiver:ref("sections",0),arguments:{value:sample.value}},{operation:"model.section.Section.different_first_page_header_footer.get",receiver:ref("sections",0),arguments:{}}];
 if(route==="model"){const doc=await api.Document(f.input,textContext),owner=doc.sections[0]!;expect(owner.different_first_page_header_footer).toBe(sample.stored==="1");owner.different_first_page_header_footer=sample.value;expect(owner.different_first_page_header_footer).toBe(sample.value);expect(new TextDecoder().decode(owner.element.serialize())).not.toContain(marker);await doc.save(sink);}
 else if(route==="sdk"){const batch=await api.applyStyleModelBatch(f.input,{version:1,operations},textContext);expect(batch.results.at(-1)!.value).toBe(sample.value);await batch.save(sink);}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",f.input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);expect(JSON.parse(result.stdout).data.results.at(-1).data).toBe(sample.value);expect(await fs.readFile("/input")).toEqual(f.input);volume.writeFileSync("/out",await fs.readFile("/out"));}finally{await shell.dispose();}}
 const after=readPackage(new Uint8Array(volume.readFileSync("/out") as Buffer));assertPackageLinks(after);expect(after.size).toBe(parts.size);for(const[name,bytes]of parts)if(name!=="word/document.xml")expect(after.get(name),name).toEqual(bytes);const markup=new TextDecoder().decode(after.get("word/document.xml"));expect(markup).not.toContain(marker);expect(markup).toContain('x:metadata="retain"');expect(markup).toContain('<!--keep--><?audit keep?>');if(carrier==="choice"||carrier==="fallback")expect(markup).toContain(inert);if(carrier==="process")expect(markup).toContain('<x:through>');const doc=await api.Document(new Uint8Array(volume.readFileSync("/out") as Buffer),textContext);expect(doc.paragraphs[0]!.text).toBe("Untouched é 日本 עברית 🌊");expect(doc.sections[0]!.different_first_page_header_footer).toBe(sample.value);
});
