import {expect,it} from "vitest";
import * as api from "./index.js";
import {Volume} from "memfs";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import {textContext,textFixture} from "../tests/fixtures/text.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const row of [956,963] as const)for(const action of ["presence","part","relink"] as const)for(const route of ["model","sdk","shell"] as const)
it(`${route} executes original missing-ID R${row} structural presence/${action}; ${kind}; strict=${strict}`,async()=>{
 const storyKind=row===956?"footer":"header",variant=row===956?"default":"first",member=row===956?"footer":"first_page_header",type=row===956?"_Footer":"_Header",source=await textFixture(`<w:sectPr><w:${storyKind}Reference w:type="${variant}"/></w:sectPr>`,{},strict),archive=await api.readArchive(source,textContext),members=archive.members.map(m=>kind==="dotx"&&m.name==="[Content_Types].xml"?{...m,bytes:new TextEncoder().encode(new TextDecoder().decode(m.bytes).replace("wordprocessingml.document.main+xml","wordprocessingml.template.main+xml"))}:m),memory=Volume.fromJSON({"/input":"","/out":"Original destination"});await api.writeArchive({...archive,members},{async write(bytes){memory.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer),operations=[{operation:"model.document.Document.sections.get",receiver:ref("document"),arguments:{},resultHandle:"sections"},{operation:`model.section.Section.${member}.get`,receiver:ref("sections",0),arguments:{},resultHandle:"story"},{operation:`model.section.${type}.${action==="presence"?"is_linked_to_previous.get":action==="part"?"part.get":"is_linked_to_previous.set"}`,receiver:ref("story"),arguments:action==="relink"?{value:true}:{}}];
 if(route==="model"){const doc=await api.Document(input,textContext),section=doc.sections[0]!,story=Reflect.get(section,member) as api._Header|api._Footer,before=section.element.serialize();if(action==="presence")expect(story.is_linked_to_previous).toBe(false);else expect(()=>action==="part"?story.part:Reflect.set(story,"is_linked_to_previous",true)).toThrow(api.InvalidValueError);expect(section.element.serialize()).toEqual(before);}
 else if(route==="sdk"){const pending=api.applyStyleModelBatch(input,{version:1,operations},textContext);if(action==="presence"){const result=await pending;expect(result.results.at(-1)!.value).toBe(false);expect(result.affected).toBe(0);}else{await expect(pending).rejects.toBeInstanceOf(api.InvalidValueError);await expect(pending).rejects.toMatchObject({operationIndex:2});}}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' ${action==="presence"?"":"--output /out --force"} --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(action==="presence"?0:2);const envelope=JSON.parse(result.stdout);if(action==="presence")expect(envelope.data.results.at(-1).data).toBe(false);else expect(envelope.errors[0]).toMatchObject({code:"usage",operationIndex:2});expect(envelope.affected).toBe(0);expect(await fs.readFile("/input")).toEqual(input);expect(new TextDecoder().decode(await fs.readFile("/out"))).toBe("Original destination");}finally{await shell.dispose();}}
 expect(memory.readFileSync("/input")).toEqual(Buffer.from(input));expect(memory.readFileSync("/out","utf8")).toBe("Original destination");
});
