import { expect, it } from "vitest";
import { Volume } from "memfs";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { textContext, textFixture } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
const p=(text:string,boundary=false)=>`<w:p>${boundary?'<w:pPr><w:sectPr/></w:pPr>':""}<w:r><w:t>${text}</w:t></w:r></w:p>`;
const table=(text:string)=>`<w:tbl><w:tblGrid><w:gridCol/></w:tblGrid><w:tr><w:tc>${p(text)}</w:tc></w:tr></w:tbl>`;
const variants=[{row:886,member:"even_page_footer",type:"_Footer"},{row:887,member:"even_page_header",type:"_Header"},{row:888,member:"first_page_footer",type:"_Footer"},{row:889,member:"first_page_header",type:"_Header"},{row:890,member:"footer",type:"_Footer"},{row:891,member:"header",type:"_Header"}] as const;
const cases=[{row:873},{row:874},{row:875},{row:876},...variants,{row:892}];
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const c of cases)for(const route of ["model","sdk","shell"] as const)
it(`${route} independently executes exact section container witness R${c.row}; ${kind}; strict=${strict}`,async()=>{
 const count=c.row===873||c.row===874?2:c.row===875||c.row===876?3:1,body=c.row===892?p("P1")+table("T2")+p("P3",true)+table("T4")+p("P5")+p("P6",true)+p("P7")+p("P8")+p("P9")+'<w:sectPr/>':Array.from({length:count-1},()=>'<w:p><w:pPr><w:sectPr/></w:pPr></w:p>').join("")+'<w:sectPr/>';
 const parts=readPackage(await textFixture(body,{},strict));if(kind==="dotx")parts.set("[Content_Types].xml",new TextEncoder().encode(new TextDecoder().decode(parts.get("[Content_Types].xml")).replace("wordprocessingml.document.main+xml","wordprocessingml.template.main+xml")));
 const volume=Volume.fromJSON({"/input":"","/out":""});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date("2026-01-02T03:04:06Z")}))},{async write(bytes){volume.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(volume.readFileSync("/input") as Buffer),sink={async write(bytes:Uint8Array){volume.appendFileSync("/out",bytes);}},operations:Record<string,unknown>[]=[{operation:"model.document.Document.sections.get",receiver:ref("document"),arguments:{},resultHandle:"sections"}];
 if(c.row===873)operations.push({operation:"model.section.Sections.__len__.get",receiver:ref("sections"),arguments:{}});
 else if(c.row===874)operations.push({operation:"model.section.Sections.__iter__.call",receiver:ref("sections"),arguments:{}});
 else if(c.row===875)for(let index=0;index<3;index++)operations.push({operation:"model.section.Sections.__getitem__.get",receiver:ref("sections"),arguments:{index}});
 else if(c.row===876)operations.push({operation:"model.section.Sections.__getitem__.slice",receiver:ref("sections"),arguments:{start:1,end:9}});
 else if("member"in c)operations.push({operation:`model.section.Section.${c.member}.get`,receiver:ref("sections",0),arguments:{},resultHandle:"story"},{operation:`model.section.${c.type}.is_linked_to_previous.get`,receiver:ref("story"),arguments:{}});
 else for(let section=0;section<3;section++){operations.push({operation:"model.section.Section.iter_inner_content.call",receiver:ref("sections",section),arguments:{},resultHandle:`blocks${section}`});for(let index=0;index<3;index++)if(section===0&&index===1||section===1&&index===0){operations.push({operation:"model.table.Table.rows.get",receiver:ref(`blocks${section}`,index),arguments:{},resultHandle:`rows${section}`},{operation:"model.table._Rows.__getitem__.get",receiver:ref(`rows${section}`),arguments:{index:0},resultHandle:`row${section}`},{operation:"model.table._Row.cells.get",receiver:ref(`row${section}`),arguments:{},resultHandle:`cells${section}`},{operation:"model.table._Cell.text.get",receiver:ref(`cells${section}`,0),arguments:{}});}else operations.push({operation:"model.text.paragraph.Paragraph.text.get",receiver:ref(`blocks${section}`,index),arguments:{}});}
 const observe=(values:unknown[])=>{if(c.row===873)expect(values.at(-1)).toBe(2);else if(c.row===874||c.row===876){const items=values.at(-1) as {type:string}[];expect(items).toHaveLength(2);expect(items.map(i=>i.type)).toEqual(["Section","Section"]);}else if(c.row===875)expect((values.slice(1) as {type:string}[]).map(i=>i.type)).toEqual(["Section","Section","Section"]);else if("member"in c){expect((values[1] as {type:string}).type).toBe(c.type);expect(values.at(-1)).toBe(true);}else expect(values.filter(v=>typeof v==="string")).toEqual(["P1","T2","P3","T4","P5","P6","P7","P8","P9"]);};
 if(route==="model"){const doc=await api.Document(input,textContext);if(c.row<=876){expect(doc.sections.length).toBe(count);const list=c.row===876?doc.sections.slice(1,9):c.row===875?[doc.sections[0]!,doc.sections[1]!,doc.sections[2]!]:[...doc.sections];expect(list).toHaveLength(c.row===876?2:count);for(const[index,section]of list.entries()){expect(section).toBeInstanceOf(api.Section);expect(section.part).toBe(doc.part);expect(section.equals(doc.sections[index+(c.row===876?1:0)])).toBe(true);expect(section.element.localName).toBe("sectPr");}}else if("member"in c){const owner=doc.sections[0]!,story=Reflect.get(owner,c.member) as api._Header|api._Footer;expect(story).toBeInstanceOf(api[c.type]);expect(story.section).toBe(owner);expect(story.is_linked_to_previous).toBe(true);}else{expect(doc.sections.length).toBe(3);expect([...doc.sections].map(s=>[...s.iter_inner_content()].map(b=>b instanceof api.Paragraph?b.text:b.rows[0]!.cells[0]!.text))).toEqual([["P1","T2","P3"],["T4","P5","P6"],["P7","P8","P9"]]);}await doc.save(sink);}
 else if(route==="sdk"){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);observe(batch.results.map(r=>r.value));expect(batch.affected).toBe(0);await batch.save(sink);}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);observe(JSON.parse(result.stdout).data.results.map((r:{data:unknown})=>r.data));expect(JSON.parse(result.stdout).affected).toBe(0);expect(await fs.readFile("/input")).toEqual(input);expect(new TextDecoder().decode(await fs.readFile("/out"))).toBe("Original destination");await(await api.Document(input,textContext)).save(sink);}finally{await shell.dispose();}}
 const after=readPackage(new Uint8Array(volume.readFileSync("/out") as Buffer));assertPackageLinks(after);expect(after.size).toBe(parts.size);for(const[name,bytes]of parts)expect(after.get(name),name).toEqual(bytes);expect(volume.readFileSync("/input")).toEqual(Buffer.from(input));
});
