import { expect, it } from "vitest";
import { Volume } from "memfs";
import { MemoryFileSystem, Shell } from "virtual-bash";
import { docxCommands } from "virtual-bash/commands/docx";
import * as api from "./index.js";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage } from "../tests/assertions.js";

const fields = [ ...["paragraph", "character", "table", "numbering"].map(type => ({ type, member: "name", owner: "BaseStyle", tag: "name" })), ...["paragraph", "character", "table"].map(type => ({ type, member: "base_style", owner: "CharacterStyle", tag: "basedOn" })), { type: "paragraph", member: "next_paragraph_style", owner: "ParagraphStyle", tag: "next" } ];
for (const strict of [false, true]) for (const field of fields) for (const carrier of ["direct", "choice", "fallback", "process"] as const) for (const reset of [false, true]) for (const route of ["model", "sdk", "shell"] as const)
it(`${route} changes ${field.type} ${field.member} through native ${carrier} reset=${reset}; strict=${strict}`, async () => {
  const wrap = (active: string) => carrier === "direct" ? active : carrier === "process" ? `<f:pass>${active}</f:pass><f:opaque f:identity="retained"/>` : `<mc:AlternateContent><mc:Choice Requires="${carrier === "choice" ? "w" : "f"}"${carrier === "fallback" ? ' f:identity="retained"' : ""}>${carrier === "choice" ? active : ""}</mc:Choice><mc:Fallback${carrier === "choice" ? ' f:identity="retained"' : ""}>${carrier === "fallback" ? active : ""}</mc:Fallback></mc:AlternateContent>`;
  const selected = `<w:style w:type="${field.type}" w:styleId="selected">${field.member === "name" ? wrap('<w:name w:val="Original Selected"/>') : '<w:name w:val="Original Selected"/>'}${field.member !== "name" ? wrap(`<w:${field.tag} w:val="original"/>`) : ""}<w:rPr><w:i/></w:rPr><!--keep--><?audit keep?></w:style>`, input = await textFixture('<w:p><w:r><w:t>Keep 日本 עברית</w:t></w:r></w:p>', { styles: { kind: "styles", xml: `<w:styles xmlns:w="${w}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:definition" mc:Ignorable="f" mc:ProcessContent="f:pass">${["original", "revised"].map(id => `<w:style w:type="${field.type}" w:styleId="${id}"><w:name w:val="${id}"/></w:style>`).join("")}${selected}</w:styles>` } }, strict), memory = Volume.fromJSON({ "/out": "" }), sink = { async write(bytes: Uint8Array) { memory.appendFileSync("/out", bytes); } }, newValue = reset ? null : field.member === "name" ? "Revised Selected" : { resultHandle: "revised" }, expected = field.member === "name" ? reset ? null : "Revised Selected" : reset ? field.member === "base_style" ? null : "Original Selected" : "revised";
  const operations = [ { operation: "model.document.Document.styles.get", receiver: { resultHandle: "document" }, arguments: {}, resultHandle: "styles" }, { operation: "model.styles.styles.Styles.__getitem__.call", receiver: { resultHandle: "styles" }, arguments: { key: "Original Selected" }, resultHandle: "selected" }, { operation: "model.styles.styles.Styles.__getitem__.call", receiver: { resultHandle: "styles" }, arguments: { key: "revised" }, resultHandle: "revised" }, { operation: `model.styles.style.${field.owner}.${field.member}.set`, receiver: { resultHandle: "selected" }, arguments: { value: newValue } } ];
  if (route === "model") { const document = await api.Document(input, textContext), style = document.styles.at("Original Selected") as api.ParagraphStyle; Reflect.set(style, field.member, reset ? null : field.member === "name" ? "Revised Selected" : document.styles.at("revised")); const value = Reflect.get(style, field.member); expect(field.member === "name" ? value : value?.name ?? null).toBe(expected); await document.save(sink); }
  else if (route === "sdk") { const result = await api.applyStyleModelBatch(input, { version: 1, operations }, textContext); await result.save(sink); }
  else { const fs = new MemoryFileSystem(); await fs.writeFile("/input", input); const shell = new Shell({ fs }).use(docxCommands({ engine: api.createDocxInspectionCommandEngine({ limits: textContext.limits }) })); try { const result = await shell.exec(`docx batch /input --ops-json '${JSON.stringify({ version: 1, operations })}' --output - > /out`); expect(result.exitCode, result.stdout + result.stderr).toBe(0); memory.writeFileSync("/out", await fs.readFile("/out")); expect(await fs.readFile("/input")).toEqual(input); } finally { await shell.dispose(); } }
  const output = new Uint8Array(memory.readFileSync("/out") as Buffer), document = await api.Document(output, textContext), style = [...document.styles].find(s => s.style_id === "selected")!; expect(style).toBeDefined(); const value = Reflect.get(style, field.member); expect(field.member === "name" ? value : value?.name ?? null).toBe(expected);
  const before = readPackage(input), after = readPackage(output); for (const [name, bytes] of before) if (name !== "word/styles.xml") expect(after.get(name), name).toEqual(bytes); const xml = new TextDecoder().decode(after.get("word/styles.xml")); expect(xml).toContain('<w:rPr><w:i/></w:rPr>'); expect(xml.split("<!--keep-->")).toHaveLength(2); expect(xml.split("<?audit keep?>")).toHaveLength(2); if (carrier !== "direct") expect(xml.split('f:identity="retained"')).toHaveLength(2);
});
