import { spawn } from "node:child_process";
import { expect, it } from "vitest";

for (const strict of [false, true]) for (const depth of [32, 4096])
for (const owner of ["rPr", "pPr"]) for (const history of ["none", "active", "inert"])
it(`preserving replacement scans property history at admitted depth; strict=${strict}; depth=${depth}; owner=${owner}; history=${history}`, async () => {
  const script = `import {Volume} from 'memfs';import * as api from ${JSON.stringify(new URL("./index.ts", import.meta.url).href)};
let data='';for await(const chunk of process.stdin)data+=chunk;const q=JSON.parse(data),memory=Volume.fromJSON({'/input':'','/output':''}),signal=new AbortController().signal,limits={maxArchiveBytes:1048576,maxEntryBytes:524288,maxTotalBytes:1048576,maxMembers:16,maxPathBytes:256,maxDepth:32,maxExtraBytes:0,maxCommentBytes:32,maxRetainedBytes:67108864,chunkSize:65536},context=()=>({signal,limits,budget:new api.DocumentBudget({xmlDepth:8192,work:2**31,retainedBytes:2**31},signal)}),enc=s=>new TextEncoder().encode(s),dec=b=>new TextDecoder().decode(b),w=q.strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':'http://schemas.openxmlformats.org/wordprocessingml/2006/main',r=q.strict?'http://purl.oclc.org/ooxml/officeDocument/relationships':'http://schemas.openxmlformats.org/officeDocument/2006/relationships',leaf=q.history==='active'?'<w:'+q.owner+'Change w:id="1" w:author="Original"><w:'+q.owner+'/></w:'+q.owner+'Change>':q.history==='inert'?'<f:ignored><w:'+q.owner+'Change w:id="1" w:author="Original"><w:'+q.owner+'/></w:'+q.owner+'Change></f:ignored>':'<w:originalProperty preserved="yes"/>',props='<w:'+q.owner+'>'+'<w:originalContainer>'.repeat(q.depth)+leaf+'</w:originalContainer>'.repeat(q.depth)+'</w:'+q.owner+'>',text='<w:r>'+(q.owner==='rPr'?props:'')+'<w:t>Coast é 日本 עברית 🌊</w:t></w:r>',body='<w:p>'+(q.owner==='pPr'?props:'')+text+'</w:p>',files={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/main.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="main" Type="'+r+'/officeDocument" Target="main.xml"/></Relationships>','main.xml':'<w:document xmlns:w="'+w+'" xmlns:f="urn:original:property-review-depth" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="f"><w:body>'+body+'<w:sectPr/></w:body></w:document>'};
await api.writeArchive({comment:new Uint8Array(),members:Object.entries(files).map(([name,text])=>({name,bytes:enc(text),directory:false,modified:new Date('1980-01-01T00:00:00Z')}))},{async write(bytes){memory.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},context());const input=new Uint8Array(memory.readFileSync('/input'));let response;
try{const result=await api.replaceDocumentText(input,{find:'Coast',with:'Shore',first:true,output:'-'},{...context(),encoding:{order:'input',compression:'store'},stdout:{async write(bytes){memory.appendFileSync('/output',bytes);}}}),members=new Map((await api.readArchive(new Uint8Array(memory.readFileSync('/output')),context())).members.map(m=>[m.name,m.bytes]));response={ok:true,changed:result.changed,text:(await api.extractDocumentText(new Uint8Array(memory.readFileSync('/output')),context())).text,exactProperties:dec(members.get('main.xml')).includes(props),exactOtherParts:Object.entries(files).filter(([name])=>name!=='main.xml').every(([name,text])=>dec(members.get(name))===text)};}catch(error){response={ok:false,code:error.code??null,error:String(error),published:memory.readFileSync('/output').length};}response.unchanged=Buffer.from(input).equals(memory.readFileSync('/input'));console.log(JSON.stringify(response));`;
  const response = await new Promise<string>((resolve, reject) => {
    const child = spawn(process.execPath, ["--import", "tsx", "--input-type=module", "-e", script], { stdio: ["pipe", "pipe", "pipe"] });
    let stdout = "", stderr = "";
    child.stdout.on("data", bytes => { stdout += String(bytes); });
    child.stderr.on("data", bytes => { stderr += String(bytes); });
    child.on("error", reject);
    child.on("close", code => { if (code !== 0) reject(new Error(stderr)); else resolve(stdout); });
    child.stdin.end(JSON.stringify({ strict, depth, owner, history }));
  });
  const result = JSON.parse(response) as { error?: string };
  if (history === "active") expect(result, result.error).toMatchObject({ ok: false, code: "unsupported-edit", published: 0, unchanged: true });
  else expect(result, result.error).toEqual({ ok: true, changed: true, text: "Shore é 日本 עברית 🌊", exactProperties: true, exactOtherParts: true, unchanged: true });
});
