import {expect,it} from "vitest";
import sharp,{decodeImage,readImageMetadata} from "@poe-code/image-ast";
import {build} from "esbuild";
import {Miniflare} from "miniflare";
import {fileURLToPath} from "node:url";
import {runSipsCli} from "./index.js";

for(const publication of ["direct","symlink"] as const)it(`mutates large images using external Worker input, scratch and ${publication} output`,async()=>{
 const bytes=await sharp({create:{width:513,height:1024,channels:3,background:"blue"}}).bmp().toBuffer();
 const args=["-f","horizontal","-p","1025","514","-s","format","png","-s","description","caller backed","/in","-o","/out"],files=new Map([["/in",bytes]]),expected=await runSipsCli(args,files),expectedBytes=files.get("/out")!;
 const bundle=await build({stdin:{resolveDir:fileURLToPath(new URL("../../../",import.meta.url)),sourcefile:"sips-mutation-worker.ts",contents:`
 import {createSipsCommand} from './packages/safe-bash-command-sips/src/index.ts';
 import {createCommandArguments} from 'safe-bash-contracts/command';
 import {FsError} from '@poe-code/safe-fs/contracts';
 export default {async fetch(request,env){const {args,size,publication}=await request.json();let guarded=0,stagingClosed=0,admitted=0,reads=0,sourceClosed=0,scratchOpened=0,scratchClosed=0,outputBytes=0,maxAllocation=0,stdout='',stderr='';const scope={};
 const stat=(id,size=0,type='file')=>({type,size,mode:420,mtimeMs:1,atimeMs:1,ctimeMs:1,identityScope:scope,opaqueIdentity:id,opaqueVersion:'1'});
 const fs={capabilities:{retainedRead:true,atomicFilePublication:true,atomicFileStaging:true,retainedStagingWrite:true,retainedStagingCleanup:true,synchronousFollowedStagingResolution:true,guardedStagingPublication:true,atomicStagingAncestry:true,atomicStagedFileMutation:true},async capabilitiesFor(){return this.capabilities;},async stat(path){if(path==='/in')return stat('input',size);if(path==='/')return stat('root',0,'directory');throw new FsError('ENOENT',{path});},async lstat(path){if(path==='/out'&&publication==='symlink')return stat('link',0,'symlink');if(path==='/in')return stat('input',size);throw new FsError('ENOENT',{path});},async removeFileConditional(){},
 async openReadFile(){return {async stat(){return stat('input',size);},async read(position,length){if(length>16384||admitted!==size)throw new Error('input admission or transfer');reads++;const response=await env.SOURCE.fetch('https://source/?position='+position+'&length='+length);return new Uint8Array(await response.arrayBuffer());},async close(){sourceClosed++;}};},
 async open(){const id=++scratchOpened;let size=0;return {capabilities:{positionedRead:true,positionedWrite:true},async stat(){return stat('scratch-'+id,size);},async write(bytes,position){if(bytes.length>16384)throw new Error('large scratch write');await env.SCRATCH.fetch('https://scratch/?id='+id+'&position='+position,{method:'PUT',body:bytes});size=Math.max(size,position+bytes.length);return bytes.length;},async read(bytes,position){if(bytes.length>16384)throw new Error('large scratch read');const response=await env.SCRATCH.fetch('https://scratch/?id='+id+'&position='+position+'&length='+bytes.length);bytes.set(new Uint8Array(await response.arrayBuffer()));return bytes.length;},async close(){scratchClosed++;await env.SCRATCH.fetch('https://scratch/?id='+id,{method:'DELETE'});}};},
 async prepareStagingResolution(path,options){if(path!=='/out'||!options.followFinalSymlink)throw new Error('resolution intent');return {path:'/resolved',parent:stat('root',0,'directory'),destination:null,ancestors:[{path:'/',stat:stat('root',0,'directory')}],traversed:[],validate(){guarded++;return true;}};},
 async createStagedFile(){return {writer:{async write(chunk){if(chunk.length>16384)throw new Error('large staged output');await env.OUTPUT.fetch('https://output/',{method:'PUT',body:chunk});outputBytes+=chunk.length;},async finish(){return stat('staged',outputBytes);}},cleanup:{async remove(){},async close(){stagingClosed++;}}};},
 async removeStagedFile(){throw new Error('lost retained cleanup');},
 async publishStagedFile(staging,path,options){if(publication!=='symlink'||path!=='/resolved'||options.destination!==null||options.preserveIdentity!==false||options.ancestors.length!==1||options.commitGuard()!==true)throw new Error('guarded publication receipt');await env.OUTPUT.fetch('https://output/',{method:'POST'});},
 async publishFileConditional(path,chunks,options){if(publication!=='direct')throw new Error('unguarded symlink publication');if(path!=='/out'||options.expected!==null)throw new Error('publication receipt');let complete=false;try{for await(const chunk of chunks){if(chunk.length>16384)throw new Error('large output');await env.OUTPUT.fetch('https://output/',{method:'PUT',body:chunk});outputBytes+=chunk.length;}await env.OUTPUT.fetch('https://output/',{method:'POST'});complete=true;}finally{if(!complete)await env.OUTPUT.fetch('https://output/',{method:'DELETE'});}},
 readFile(){throw new Error('whole input');},writeFile(){throw new Error('whole output');}};
 const Native=Uint8Array;globalThis.Uint8Array=new Proxy(Native,{construct(target,args){const value=args[0],length=typeof value==='number'?value:value?.byteLength??value?.length??0;maxAllocation=Math.max(maxAllocation,length);if(length>65536)throw new Error('unbounded image allocation '+length);return Reflect.construct(target,args);}});
 try{const arguments_=createCommandArguments(args),result=await createSipsCommand().execute({command:'sips',args:arguments_.args,argumentValues:arguments_,cwd:'/',env:{},fs,signal:new AbortController().signal,stdin:(async function*(){})(),inputBudget:{maxBytes:size,check(bytes){admitted=bytes;if(bytes>size)throw new Error('input budget');}},stdout:{async write(bytes){stdout+=new TextDecoder().decode(bytes);}},stderr:{async write(bytes){stderr+=new TextDecoder().decode(bytes);}}});
 return Response.json({...result,stdout,stderr,guarded,stagingClosed,reads,sourceClosed,scratchOpened,scratchClosed,outputBytes,maxAllocation,nodeGlobals:typeof process!=='undefined'||typeof Buffer!=='undefined'});
 }finally{globalThis.Uint8Array=Native;}}};`},bundle:true,write:false,platform:"browser",conditions:["workerd"],format:"esm",metafile:true,logLevel:"silent"});
 expect(Object.values(bundle.metafile!.outputs).flatMap(output=>output.imports)).toEqual([]);
 const scratch=new Map<string,Uint8Array>(),output:Uint8Array[]=[];let published=false;
 const runtime=new Miniflare({modules:true,compatibilityDate:"2026-07-01",cf:false,script:bundle.outputFiles[0]!.text,serviceBindings:{
 SOURCE:async(request:Request)=>{const url=new URL(request.url),position=Number(url.searchParams.get("position")),length=Number(url.searchParams.get("length"));return new Response(bytes.slice(position,position+length));},
 SCRATCH:async(request:Request)=>{const url=new URL(request.url),id=url.searchParams.get("id")!,key=id+":"+url.searchParams.get("position");if(request.method==="DELETE"){for(const key of scratch.keys())if(key.startsWith(id+":"))scratch.delete(key);return new Response();}if(request.method==="PUT"){scratch.set(key,new Uint8Array(await request.arrayBuffer()));return new Response();}return new Response(scratch.get(key)?.slice(0,Number(url.searchParams.get("length"))));},
 OUTPUT:async(request:Request)=>{if(request.method==="POST")published=true;else if(request.method==="DELETE")output.length=0;else output.push(new Uint8Array(await request.arrayBuffer()));return new Response();}
 }});
 try{const response=await runtime.dispatchFetch("https://sips/",{method:"POST",body:JSON.stringify({args,size:bytes.length,publication})});if(response.status!==200)throw new Error(await response.text());const result=await response.json() as {guarded:number;stagingClosed:number;exitCode:number;stdout:string;stderr:string;reads:number;sourceClosed:number;scratchOpened:number;scratchClosed:number;outputBytes:number;maxAllocation:number;nodeGlobals:boolean};
 expect({exitCode:result.exitCode,stdout:result.stdout,stderr:result.stderr}).toEqual(expected);expect(published).toBe(true);if(publication==="symlink")expect(result.guarded).toBeGreaterThanOrEqual(1);else expect(result.guarded).toBe(0);expect(result.stagingClosed).toBe(publication==="symlink"?1:0);expect(result.reads).toBeGreaterThan(64);expect(result.sourceClosed).toBe(1);expect(result.scratchOpened).toBe(2);expect(result.scratchClosed).toBe(2);expect(scratch.size).toBe(0);expect(result.maxAllocation).toBeLessThanOrEqual(65536);expect(result.nodeGlobals).toBe(false);
 const actual=new Uint8Array(result.outputBytes);let position=0;for(const chunk of output){actual.set(chunk,position);position+=chunk.length;}expect(position).toBe(actual.length);expect(decodeImage(actual)).toEqual(decodeImage(expectedBytes));const {size:ignoredActual,...actualMetadata}=readImageMetadata(actual),{size:ignoredExpected,...expectedMetadata}=readImageMetadata(expectedBytes);expect(actualMetadata).toEqual(expectedMetadata);
 }finally{await runtime.dispose();}
},15000);
