export const cases: readonly { args: readonly string[]; input: string }[] = [
  { args: ["."], input: "a: 1\n" },
  { args: [".a"], input: 'a: "hello"\n' },
  { args: ["-r=false", ".a"], input: 'a: "hello"\n' },
  { args: ["-o=json", "-I=0", "."], input: "[1,# comment\n2]" },
  { args: ["-n", "-o=json", "-I=0", '.a = 1 | .b = "yes"'], input: "ignored: true" },
  { args: ["-n", '{"a": [1, 2], "b": true}'], input: "" },
  { args: ["-p=json", ".a"], input: '{"a":"hello"}' },
  { args: ["-p=json", "-o=json", "-I=0", "."], input: '{"a":9007199254740993}\n{"b":2}' },
  { args: ["-p=yaml", "-I4", "."], input: "a:\n  b: [1, 2]" },
  { args: ["-I0", "."], input: "a:\n  b: [1, 2]" },
  { args: ["-e", "."], input: "false\n---\ntrue\n---\nnull" },
  { args: ["-e", "."], input: "false\n---\nnull" },
  { args: ["-e", "select(false)"], input: "a: 1" },
  { args: ["-e", "."], input: '""' },
  { args: ["eval", "-o=json", "-I0", "[.]"], input: "a: 1\n---\na: 2" },
  { args: ["eval-all", "-o=json", "-I0", "[.]"], input: "a: 1\n---\na: 2" },
  { args: ["ea", "-o=json", "-I0", "select(documentIndex == 0) * select(documentIndex == 1)"], input: "a: 1\n---\nb: 2" },
  { args: ["e", ".a = .b"], input: "a: 0\nb: 2" },
  { args: [".a |= . + 1"], input: "a: 2" },
  { args: [".a = (1,2)"], input: "a: 0" },
  { args: [".a |= (1,2)"], input: "a: 0" },
  { args: ["(.a, .b) = 3"], input: "a: 0\nb: 2" },
  { args: ['(.items[] | select(.name == "x")).enabled = true'], input: "items: [{name: x}, {name: y}]" },
  { args: ['.a = "new"'], input: "# head\na: 'old' # inline\nb: &base {x: 1}\nc: *base\n" },
  { args: [".a = 9007199254740993"], input: "a: 0" },
  { args: [".a += 1"], input: "a: 9007199254740993" },
  { args: [".a | tag"], input: "a: !thing 1" },
  { args: [".a | type"], input: "a: 1" },
  { args: ['.a tag = "!!str"'], input: "a: 12" },
  { args: [".a = 2"], input: "a: !thing 1 # inline" },
  { args: [".a =c 2"], input: "a: !thing 1" },
  { args: ["."], input: "a: 1\na: 2" },
  { args: [".a"], input: "a: 1\na: 2" },
  { args: ["."], input: "" },
  { args: ["."], input: "---\n" },
  { args: ["--output-format=json", "--indent=0", "."], input: "a: 1" },
  { args: ["-p", "json", "-p", "yaml", "."], input: "a: 1" },
  { args: ["-n", ".a = 1", "/absent"], input: "" },
  { args: ["-i", ".a = 1", "-"], input: "a: 0" },
  { args: ["-o"], input: "" },
  { args: ["-o=bad", "."], input: "" },
  { args: ["--unknown"], input: "" },
  { args: ["-x"], input: "" },
  { args: ["-I=bad"], input: "" },
  { args: ["-n=false", "-o=json", "-I0", "."], input: "a: 1" },
];
