import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.dirname(new URL(import.meta.url).pathname);
const capture=fs.openSync(root+'/FINALIZE.capture.data','wx',0o600);
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const assert=(value,message)=>{if(!value)throw Error(message);};
let complete=false;
try{
 fs.writeSync(capture,JSON.stringify({event:'START',at:new Date().toISOString(),children:0})+'\n');
 const controls=JSON.parse(fs.readFileSync(root+'/CONTROL-SEAL.json'));for(const row of controls.files){const bytes=fs.readFileSync(root+'/'+row.path);assert(bytes.length===row.bytes&&hash(bytes)===row.sha256,'POST_CONTROL_INTEGRITY');}
 for(const role of ['source','evidence']){const manifest=JSON.parse(fs.readFileSync(root+'/'+role+'/MANIFEST.json'));for(const row of manifest.rows){const bytes=fs.readFileSync(root+'/'+role+'/'+row.capture);assert(bytes.length===row.bytes&&hash(bytes)===row.sha256,'POST_PACKET_INTEGRITY');}}
 const result=JSON.parse(fs.readFileSync(root+'/RESULT.json'));const rows=result.results.filter(row=>['C11','C12','N04'].includes(row.id)).map(row=>{const observation=row.row??row.detail.row;const term=observation.signals.find(row=>row.signal==='SIGTERM'),kill=observation.signals.find(row=>row.signal==='SIGKILL');return {id:row.id,status:observation.status,signal:observation.signal,stop:observation.stop,retired:observation.retired,group:observation.group,termToKillMs:kill?kill.at-term.at:null,termToFinishMs:term?observation.finished-term.at:null,observations:observation.groupObservations};});
 const summary={status:'REVIEW_COMPLETE_TWO_BOUNDARY_FINDINGS',sourceCommit:'a5fd225af5f9985ae805f48ab1b1790a9c3fbc7f',evidenceCommit:'f9fe59338cf01863735ee67bef5ae03ef993d053',presealSha256:'384950a91459ff0ee66449a0604313b7af5af162b252426fe53ce787706a4dda',templateSha256:'d63d67428d19804b43177fe7d1671bb89c12496b16de78fc11c65fe6ffa12ff9',authorControlIdentities:12,novelIdentities:10,matchedObservations:result.results.filter(row=>row.matched).length,matchedDoesNotMeanLaunchAcceptance:true,actualNodeProcessesIncludingControlOwner:5,wrapperShellRoles:3,knownDistinctControlPids:7,metadataAndPublicationSeparate:true,lifecycle:rows,nativeEntry:0,bash:0,eligibleUnrun:37,withheldUnrun:3,goResolved:false,acceptReceiptCreated:false,findings:['R1 emergency terminal publication skips overall deadline','R2 actual tool-shell startup differs from clean-env derivative'],postIntegrity:'ALL_BOUND_FILES_UNCHANGED',workDeletion:'NONE; owned evidence retained',processBudget:{grant:64,visibleRoleStartsThroughPlannedSuccessfulPublication:51,editWrapperAdditionalConservativeAllowance:4,totalConservative:55,peakKnown:3,notKernelCensus:true}};
 fs.writeFileSync(root+'/FINAL-SUMMARY.json',JSON.stringify(summary,null,2)+'\n',{flag:'wx'});fs.writeSync(capture,JSON.stringify({event:'COMPLETE',children:0,status:summary.status})+'\n');console.log(JSON.stringify({status:summary.status,lifecycle:rows,matchedObservations:22,actualNodeProcesses:5,native:0}));complete=true;
}catch(error){fs.writeSync(capture,JSON.stringify({event:'STOP',message:error.message})+'\n');process.exitCode=1;}finally{fs.closeSync(capture);}
if(complete){const rows=[];function walk(directory,prefix=''){for(const name of fs.readdirSync(directory).sort()){const filename=path.join(directory,name),relative=prefix?prefix+'/'+name:name,stat=fs.lstatSync(filename);if(stat.isDirectory())walk(filename,relative);else{assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<16*1024*1024,'SEAL_FILE');const bytes=fs.readFileSync(filename);rows.push({path:relative,bytes:bytes.length,mode:stat.mode&511,sha256:hash(bytes)});}}}walk(root);const bytes=rows.reduce((sum,row)=>sum+row.bytes,0);assert(bytes<16*1024*1024,'LOGICAL_WORK_BOUND');fs.writeFileSync(root+'/SEAL.json',JSON.stringify({schema:'independent-functional-reference-v2-review-seal',rows,logicalBytesExcludingSeal:bytes,selfExcluded:true},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({sealedFiles:rows.length,logicalBytes:bytes}));}
