import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { read, hash, bind, archiveAdmission, verifyPackage } from './data.mjs';
import { validateSelection } from './core.mjs';

const owned = path.resolve('tests/compatibility/bash-ere-core-public-pilot-preparation-20260829/runtime-author-v1');
const previousPath = path.resolve(owned, '../PILOT-PRESEAL.json');
const previousBytes = read(previousPath);
assert.equal(hash(previousBytes), '819acd62efb035279d61aaced782abe4c5779f3dc1a5983a0db694d4bc3fc7d7');
const previous = JSON.parse(previousBytes);
validateSelection(previous.cells);
const producer = path.resolve('tests/compatibility/bash-ere-core-transport-rebind-20260829/author-v3');
const shipping = JSON.parse(read(path.join(producer, 'output/SHIPPING.json'))).rows;
const compositionBytes = read(path.resolve(producer, '../COMPOSITION.json'));
assert.equal(hash(compositionBytes), 'f8004c83c2316ce33e5e93719961b56847c87b6c47b79566b2810c92e8ef72f9');
const composition = JSON.parse(compositionBytes);
const npmRoot = '/Users/kjopek/.nvm/versions/node/v22.22.2/lib/node_modules/npm';
const toolMap = new Map();
const collect = value => { if (!value || typeof value !== 'object') return; if (typeof value.path === 'string' && typeof value.sha256 === 'string' && Number.isSafeInteger(value.size) && value.path.startsWith(npmRoot + '/')) toolMap.set(value.path, value); for (const child of Object.values(value)) collect(child); };
collect(composition.tools.npm.rows.map(row => ({ ...row, path: path.join(npmRoot, row.path) })));
assert.equal(toolMap.size, 2027);
const tools = [previous.node, ...toolMap.values()].map(({ path: filename, size, mode, sha256 }) => ({ path: filename, size, mode, sha256 }));
for (const row of tools) bind(row);
bind(previous.archive);
archiveAdmission(previous.archive, read(previous.archive.path, 909885));
const root = path.join(owned, 'FUTURE-PILOT-01');
assert(!fs.existsSync(root));
const layouts = previous.layouts.map(layout => {
  const manifest = JSON.parse(read(layout.manifest.path));
  const prefix = path.relative(layout.app, layout.packageRoot) + '/';
  const rows = layout.name === 'source-built' ? manifest.rows.filter(row => row.path.startsWith(prefix)).map(row => ({ ...row, path: row.path.slice(prefix.length) })) : shipping;
  verifyPackage(layout.packageRoot, rows);
  const app = path.join(root, layout.name);
  return { name: layout.name, app, origin: layout.name === 'moved' ? path.join(root, 'move-origin') : app, packageRoot: path.join(app, 'node_modules/virtual-bash'), source: layout.packageRoot, shipping: rows, nativeRoot: path.join(root, `native-${layout.name}`), consumerManifest: JSON.stringify({ private: true, type: 'module', dependencies: layout.name === 'source-built' ? {} : { 'virtual-bash': `file:${previous.archive.path}` } }) + '\n' };
});
const cells = previous.cells.map(cell => {
  const layout = layouts.find(row => cell.id.startsWith(row.name + '/'));
  const inherited = JSON.parse(read(cell.inheritedCell.path));
  assert.deepEqual(inherited.definition, cell.definition);
  const priorLayout = previous.layouts.find(row => row.name === layout.name);
  const publicEntry = path.relative(priorLayout.packageRoot, inherited.modulePath);
  assert.equal(publicEntry, 'dist/index.js');
  const spec = { id: cell.id, definition: cell.definition, limits: cell.inheritedLimits, node: previous.node.path, modulePath: path.join(layout.packageRoot, publicEntry), workerPath: path.join(layout.packageRoot, 'dist/commands/regex-execution/ere/transport/worker-entry.js') };
  return { ...cell, executable: true, layout: layout.name, app: layout.app, publicEntry, config: path.join(layout.app, 'cells', `${cell.definition.id}.json`), configSha256: hash(Buffer.from(JSON.stringify(spec) + '\n')), stdout: path.join(root, 'captures', cell.id.replace('/', '-') + '.stdout'), stderr: path.join(root, 'captures', cell.id.replace('/', '-') + '.stderr') };
});
validateSelection(cells);
const asset = filename => { const file = path.join(owned, filename); const bytes = read(file); return { path: file, size: bytes.length, mode: fs.lstatSync(file).mode & 0o777, sha256: hash(bytes) }; };
const assets = ['core.mjs', 'observer.mjs', 'process-owner.mjs', 'data.mjs', 'cell.mjs', 'coordinator.mjs'].map(asset);
const cellAssets = assets.filter(row => ['core.mjs', 'observer.mjs', 'data.mjs', 'cell.mjs'].includes(path.basename(row.path)));
const retainedInputBytes = previous.layouts.reduce((sum, row) => sum + row.bytes, 0) + previous.archive.size + previousBytes.length;
const components = { retainedInputBytes, freshPackages: layouts.reduce((sum, row) => sum + row.shipping.reduce((subtotal, item) => subtotal + item.size, 0), 0), nativeMutableReservations: 67108864, allCaptureMaximum: 67108864, onePublicationCaptureCopy: 67108864, metadataAndAuthorPacket: 8388608, finalPublicationMiscellaneous: 4194304 };
const logicalBytes = Object.values(components).reduce((sum, value) => sum + value, 0);
assert(logicalBytes <= 268435456);
const roles = [{ role: 'trusted-outer-owner', count: 1 }, { role: 'capture-bootstrap-shell', count: 1 }, { role: 'coordinator-node', count: 1 }, { role: 'offline-npm-node', count: 2 }, { role: 'public-cell-node', count: 24 }, { role: 'publication-verifier-node', count: 1 }, ...['git-preindex', 'git-add', 'git-check', 'git-commit', 'git-show', 'git-postindex'].map(role => ({ role, count: 1 }))];
const profile = { schema: 'ORDINARY_PUBLIC_PILOT_RUNTIME_AUTHOR_V1', status: 'SOURCE_PURE_PENDING_DIFFERENT_REVIEW_NO_ACTIVATION', prepared: new Date().toISOString(), root, sourceCommit: previous.sourceCommit, sourceReview: previous.sourcePureReview, producerReview: '5c2ef0795ca402344b5b0d28869b64db46d73b86', previousProfileSha256: hash(previousBytes), archive: previous.archive, node: previous.node, npm: path.join(npmRoot, 'bin/npm-cli.js'), tools, assets, cellAssets, layouts, cells, retainedInputBytes, counters: { definitions: 8, layouts: 3, cells: 24, shellExecCalls: 24, regexVisits: 30, workersMaximum: 24, nativeChildrenMaximum: 26, knownOSMaximum: 40, enumeratedRoleMaximum: roles.reduce((sum, row) => sum + row.count, 0), unusedRoleSlots: 4, roles, peak: 4, workerLiveMaximum: 1 }, budget: { milliseconds: 1200000, publicationMilliseconds: 180000, captureBytes: 67108864, innerCaptureBytes: 58720256, outerAdministrativeCaptureReserve: 8388608, workingBytes: 268435456, logicalBytes, components, qualification: 'ROOT-approved sampled/quiescent dev-npm work, non-atomic, not peak/prewrite work guarantee or OS quota; observed excess STOP; capture prewrite caps unchanged' }, outerAuthorityRequired: ['prewrite-bounded trusted capture before coordinator import/startup, with actual coordinator handle retained', 'one monotonic start before bootstrap/admission/install and fresh grant window', 'publication verifier and six Git commands included, captures each bounded within outer 8 MiB; no implicit process launches', 'different pilot SOURCE/PURE and PREEXEC approval before root grant'], runtimeCalls: 0, fullPrivateAndCOREGates: 'OPEN' };
fs.writeFileSync(path.join(owned, 'PROFILE.json'), JSON.stringify(profile, null, 2) + '\n', { flag: 'wx' });
const grant = { schema: 1, authorized: false, profileSha256: hash(read(path.join(owned, 'PROFILE.json'))), sourceReview: profile.sourceReview, producerReview: profile.producerReview, pilotReview: null, issuedAt: null, latestStart: null, expiresAt: null, outerStarted: null, sampledNpmWork: true, knownOS: 40, peak: 4, workers: 24, milliseconds: 1200000, publicationMilliseconds: 180000, captureBytes: 67108864, workingBytes: 268435456 };
fs.writeFileSync(path.join(owned, 'GRANT-TEMPLATE.json'), JSON.stringify(grant, null, 2) + '\n', { flag: 'wx' });
const receipt = { at: new Date().toISOString(), profileSha256: grant.profileSha256, assets, tools: tools.length, currentNodeRehashed: true, packageFiles: layouts.map(row => ({ name: row.name, files: row.shipping.length })), cells: 24, unchangedOracles: true, logicalBytes, components, enumeratedRoles: profile.counters.enumeratedRoleMaximum, rolesCeiling: 40, futureRootAbsent: !fs.existsSync(root), archiveInflations: 0, actualChildren: 0, actualWorkers: 0, productImports: 0 };
fs.writeFileSync(path.join(owned, 'PREPARATION-RECEIPT.json'), JSON.stringify(receipt, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify(receipt, null, 2));
