import {unpackCodepage} from "./codepage-table.js";
import { normalizeEncoding, pythonCodecAliases } from "./python-codec-aliases.js";

// dbfread 2.0.7 single-byte drivers, captured from frozen CPython 3.14.2.
// Every byte is qualified in docs/csvkit/dbf-codepage-reference.json.
export const dbfCodepages: Readonly<Record<string, readonly number[]>> = Object.freeze({
  "cp1250": unpackCodepage("rCD//xog//8eICYgICAhIP//MCBgATkgWgFkAX0BeQH//xggGSAcIB0gIiATIBQg//8iIWEBOiBbAWUBfgF6AaAAxwLYAkEBpAAEAaYApwCoAKkAXgGrAKwArQCuAHsBsACxANsCQgG0ALUAtgC3ALgABQFfAbsAPQHdAj4BfAFUAcEAwgACAcQAOQEGAccADAHJABgBywAaAc0AzgAOARABQwFHAdMA1ABQAdYA1wBYAW4B2gBwAdwA3QBiAd8AVQHhAOIAAwHkADoBBwHnAA0B6QAZAesAGwHtAO4ADwERAUQBSAHzAPQAUQH2APcAWQFvAfoAcQH8AP0AYwHZAg=="),
  "cp1251": unpackCodepage("AgQDBBogUwQeICYgICAhIKwgMCAJBDkgCgQMBAsEDwRSBBggGSAcIB0gIiATIBQg//8iIVkEOiBaBFwEWwRfBKAADgReBAgEpACQBKYApwABBKkABASrAKwArQCuAAcEsACxAAYEVgSRBLUAtgC3AFEEFiFUBLsAWAQFBFUEVwQQBBEEEgQTBBQEFQQWBBcEGAQZBBoEGwQcBB0EHgQfBCAEIQQiBCMEJAQlBCYEJwQoBCkEKgQrBCwELQQuBC8EMAQxBDIEMwQ0BDUENgQ3BDgEOQQ6BDsEPAQ9BD4EPwRABEEEQgRDBEQERQRGBEcESARJBEoESwRMBE0ETgRPBA=="),
  "cp1253": unpackCodepage("rCD//xogkgEeICYgICAhIP//MCD//zkg/////////////xggGSAcIB0gIiATIBQg//8iIf//OiD//////////6AAhQOGA6MApAClAKYApwCoAKkA//+rAKwArQCuABUgsACxALIAswCEA7UAtgC3AIgDiQOKA7sAjAO9AI4DjwOQA5EDkgOTA5QDlQOWA5cDmAOZA5oDmwOcA50DngOfA6ADoQP//6MDpAOlA6YDpwOoA6kDqgOrA6wDrQOuA68DsAOxA7IDswO0A7UDtgO3A7gDuQO6A7sDvAO9A74DvwPAA8EDwgPDA8QDxQPGA8cDyAPJA8oDywPMA80DzgP//w=="),
  "cp1254": unpackCodepage("rCD//xogkgEeICYgICAhIMYCMCBgATkgUgH//////////xggGSAcIB0gIiATIBQg3AIiIWEBOiBTAf////94AaAAoQCiAKMApAClAKYApwCoAKkAqgCrAKwArQCuAK8AsACxALIAswC0ALUAtgC3ALgAuQC6ALsAvAC9AL4AvwDAAMEAwgDDAMQAxQDGAMcAyADJAMoAywDMAM0AzgDPAB4B0QDSANMA1ADVANYA1wDYANkA2gDbANwAMAFeAd8A4ADhAOIA4wDkAOUA5gDnAOgA6QDqAOsA7ADtAO4A7wAfAfEA8gDzAPQA9QD2APcA+AD5APoA+wD8ADEBXwH/AA=="),
  "cp1255": unpackCodepage("rCD//xogkgEeICYgICAhIMYCMCD//zkg/////////////xggGSAcIB0gIiATIBQg3AIiIf//OiD//////////6AAoQCiAKMAqiClAKYApwCoAKkA1wCrAKwArQCuAK8AsACxALIAswC0ALUAtgC3ALgAuQD3ALsAvAC9AL4AvwCwBbEFsgWzBbQFtQW2BbcFuAW5Bf//uwW8Bb0FvgW/BcAFwQXCBcMF8AXxBfIF8wX0Bf//////////////////0AXRBdIF0wXUBdUF1gXXBdgF2QXaBdsF3AXdBd4F3wXgBeEF4gXjBeQF5QXmBecF6AXpBeoF/////w4gDyD//w=="),
  "cp1256": unpackCodepage("rCB+BhogkgEeICYgICAhIMYCMCB5BjkgUgGGBpgGiAavBhggGSAcIB0gIiATIBQgqQYiIZEGOiBTAQwgDSC6BqAADAaiAKMApAClAKYApwCoAKkAvgarAKwArQCuAK8AsACxALIAswC0ALUAtgC3ALgAuQAbBrsAvAC9AL4AHwbBBiEGIgYjBiQGJQYmBicGKAYpBioGKwYsBi0GLgYvBjAGMQYyBjMGNAY1BjYG1wA3BjgGOQY6BkAGQQZCBkMG4ABEBuIARQZGBkcGSAbnAOgA6QDqAOsASQZKBu4A7wBLBkwGTQZOBvQATwZQBvcAUQb5AFIG+wD8AA4gDyDSBg=="),
  "cp437": unpackCodepage("xwD8AOkA4gDkAOAA5QDnAOoA6wDoAO8A7gDsAMQAxQDJAOYAxgD0APYA8gD7APkA/wDWANwAogCjAKUApyCSAeEA7QDzAPoA8QDRAKoAugC/ABAjrAC9ALwAoQCrALsAkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlsQPfAJMDwAOjA8MDtQDEA6YDmAOpA7QDHiLGA7UDKSJhIrEAZSJkIiAjISP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp737": unpackCodepage("kQOSA5MDlAOVA5YDlwOYA5kDmgObA5wDnQOeA58DoAOhA6MDpAOlA6YDpwOoA6kDsQOyA7MDtAO1A7YDtwO4A7kDugO7A7wDvQO+A78DwAPBA8MDwgPEA8UDxgPHA8gDkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlyQOsA60DrgPKA68DzAPNA8sDzgOGA4gDiQOKA4wDjgOPA7EAZSJkIqoDqwP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp850": unpackCodepage("xwD8AOkA4gDkAOAA5QDnAOoA6wDoAO8A7gDsAMQAxQDJAOYAxgD0APYA8gD7APkA/wDWANwA+ACjANgA1wCSAeEA7QDzAPoA8QDRAKoAugC/AK4ArAC9ALwAoQCrALsAkSWSJZMlAiUkJcEAwgDAAKkAYyVRJVclXSWiAKUAECUUJTQlLCUcJQAlPCXjAMMAWiVUJWklZiVgJVAlbCWkAPAA0ADKAMsAyAAxAc0AzgDPABglDCWIJYQlpgDMAIAl0wDfANQA0gD1ANUAtQD+AN4A2gDbANkA/QDdAK8AtACtALEAFyC+ALYApwD3ALgAsACoALcAuQCzALIAoCWgAA=="),
  "cp852": unpackCodepage("xwD8AOkA4gDkAG8BBwHnAEIB6wBQAVEB7gB5AcQABgHJADkBOgH0APYAPQE+AVoBWwHWANwAZAFlAUEB1wANAeEA7QDzAPoABAEFAX0BfgEYARkBrAB6AQwBXwGrALsAkSWSJZMlAiUkJcEAwgAaAV4BYyVRJVclXSV7AXwBECUUJTQlLCUcJQAlPCUCAQMBWiVUJWklZiVgJVAlbCWkABEBEAEOAcsADwFHAc0AzgAbARglDCWIJYQlYgFuAYAl0wDfANQAQwFEAUgBYAFhAVQB2gBVAXAB/QDdAGMBtACtAN0C2wLHAtgCpwD3ALgAsACoANkCcQFYAVkBoCWgAA=="),
  "cp857": unpackCodepage("xwD8AOkA4gDkAOAA5QDnAOoA6wDoAO8A7gAxAcQAxQDJAOYAxgD0APYA8gD7APkAMAHWANwA+ACjANgAXgFfAeEA7QDzAPoA8QDRAB4BHwG/AK4ArAC9ALwAoQCrALsAkSWSJZMlAiUkJcEAwgDAAKkAYyVRJVclXSWiAKUAECUUJTQlLCUcJQAlPCXjAMMAWiVUJWklZiVgJVAlbCWkALoAqgDKAMsAyAD//80AzgDPABglDCWIJYQlpgDMAIAl0wDfANQA0gD1ANUAtQD//9cA2gDbANkA7AD/AK8AtACtALEA//++ALYApwD3ALgAsACoALcAuQCzALIAoCWgAA=="),
  "cp860": unpackCodepage("xwD8AOkA4gDjAOAAwQDnAOoAygDoAM0A1ADsAMMAwgDJAMAAyAD0APUA8gDaAPkAzADVANwAogCjANkApyDTAOEA7QDzAPoA8QDRAKoAugC/ANIArAC9ALwAoQCrALsAkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlsQPfAJMDwAOjA8MDtQDEA6YDmAOpA7QDHiLGA7UDKSJhIrEAZSJkIiAjISP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp861": unpackCodepage("xwD8AOkA4gDkAOAA5QDnAOoA6wDoANAA8ADeAMQAxQDJAOYAxgD0APYA/gD7AN0A/QDWANwA+ACjANgApyCSAeEA7QDzAPoAwQDNANMA2gC/ABAjrAC9ALwAoQCrALsAkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlsQPfAJMDwAOjA8MDtQDEA6YDmAOpA7QDHiLGA7UDKSJhIrEAZSJkIiAjISP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp863": unpackCodepage("xwD8AOkA4gDCAOAAtgDnAOoA6wDoAO8A7gAXIMAApwDJAMgAygD0AMsAzwD7APkApADUANwAogCjANkA2wCSAaYAtADzAPoAqAC4ALMArwDOABAjrAC9ALwAvgCrALsAkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlsQPfAJMDwAOjA8MDtQDEA6YDmAOpA7QDHiLGA7UDKSJhIrEAZSJkIiAjISP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp865": unpackCodepage("xwD8AOkA4gDkAOAA5QDnAOoA6wDoAO8A7gDsAMQAxQDJAOYAxgD0APYA8gD7APkA/wDWANwA+ACjANgApyCSAeEA7QDzAPoA8QDRAKoAugC/ABAjrAC9ALwAoQCrAKQAkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlsQPfAJMDwAOjA8MDtQDEA6YDmAOpA7QDHiLGA7UDKSJhIrEAZSJkIiAjISP3AEgisAAZIrcAGiJ/ILIAoCWgAA=="),
  "cp866": unpackCodepage("EAQRBBIEEwQUBBUEFgQXBBgEGQQaBBsEHAQdBB4EHwQgBCEEIgQjBCQEJQQmBCcEKAQpBCoEKwQsBC0ELgQvBDAEMQQyBDMENAQ1BDYENwQ4BDkEOgQ7BDwEPQQ+BD8EkSWSJZMlAiUkJWElYiVWJVUlYyVRJVclXSVcJVslECUUJTQlLCUcJQAlPCVeJV8lWiVUJWklZiVgJVAlbCVnJWglZCVlJVklWCVSJVMlayVqJRglDCWIJYQljCWQJYAlQARBBEIEQwREBEUERgRHBEgESQRKBEsETARNBE4ETwQBBFEEBARUBAcEVwQOBF4EsAAZIrcAGiIWIaQAoCWgAA=="),
  "cp874": unpackCodepage("rCD//////////yYg/////////////////////////////xggGSAcIB0gIiATIBQg/////////////////////6AAAQ4CDgMOBA4FDgYOBw4IDgkOCg4LDgwODQ4ODg8OEA4RDhIOEw4UDhUOFg4XDhgOGQ4aDhsOHA4dDh4OHw4gDiEOIg4jDiQOJQ4mDicOKA4pDioOKw4sDi0OLg4vDjAOMQ4yDjMONA41DjYONw44DjkOOg7//////////z8OQA5BDkIOQw5EDkUORg5HDkgOSQ5KDksOTA5NDk4OTw5QDlEOUg5TDlQOVQ5WDlcOWA5ZDloOWw7//////////w=="),
  "mac_cyrillic": unpackCodepage("EAQRBBIEEwQUBBUEFgQXBBgEGQQaBBsEHAQdBB4EHwQgBCEEIgQjBCQEJQQmBCcEKAQpBCoEKwQsBC0ELgQvBCAgsACQBKMApwAiILYABgSuAKkAIiECBFIEYCIDBFMEHiKxAGQiZSJWBLUAkQQIBAQEVAQHBFcECQRZBAoEWgRYBAUErAAaIpIBSCIGIqsAuwAmIKAACwRbBAwEXARVBBMgFCAcIB0gGCAZIPcAHiAOBF4EDwRfBBYhAQRRBE8EMAQxBDIEMwQ0BDUENgQ3BDgEOQQ6BDsEPAQ9BD4EPwRABEEEQgRDBEQERQRGBEcESARJBEoESwRMBE0ETgSsIA=="),
  "mac_greek": unpackCodepage("xAC5ALIAyQCzANYA3ACFA+AA4gDkAIQDqADnAOkA6ADqAOsAowAiIe4A7wAiIL0AMCD0APYApgCsIPkA+wD8ACAgkwOUA5gDmwOeA6AD3wCuAKkAowOqA6cAYCKwALcAkQOxAGQiZSKlAJIDlQOWA5cDmQOaA5wDpgOrA6gDqQOsA50DrACfA6EDSCKkA6sAuwAmIKAApQOnA4YDiANTARMgFSAcIB0gGCAZIPcAiQOKA4wDjgOtA64DrwPMA48DzQOxA7IDyAO0A7UDxgOzA7cDuQO+A7oDuwO8A70DvwPAA84DwQPDA8QDuAPJA8IDxwPFA7YDygPLA5ADsAOtAA=="),
  "mac_latin2": unpackCodepage("xAAAAQEByQAEAdYA3ADhAAUBDAHkAA0BBgEHAekAeQF6AQ4B7QAPARIBEwEWAfMAFwH0APYA9QD6ABoBGwH8ACAgsAAYAaMApwAiILYA3wCuAKkAIiEZAagAYCIjAS4BLwEqAWQiZSIrATYBAiIRIkIBOwE8AT0BPgE5AToBRQFGAUMBrAAaIkQBRwEGIqsAuwAmIKAASAFQAdUAUQFMARMgFCAcIB0gGCAZIPcAyiVNAVQBVQFYATkgOiBZAVYBVwFgARogHiBhAVoBWwHBAGQBZQHNAH0BfgFqAdMA1ABrAW4B2gBvAXABcQFyAXMB3QD9ADcBewFBAXwBIgHHAg=="),
  "mac_roman": unpackCodepage("xADFAMcAyQDRANYA3ADhAOAA4gDkAOMA5QDnAOkA6ADqAOsA7QDsAO4A7wDxAPMA8gD0APYA9QD6APkA+wD8ACAgsACiAKMApwAiILYA3wCuAKkAIiG0AKgAYCLGANgAHiKxAGQiZSKlALUAAiIRIg8iwAMrIqoAugCpA+YA+AC/AKEArAAaIpIBSCIGIqsAuwAmIKAAwADDANUAUgFTARMgFCAcIB0gGCAZIPcAyiX/AHgBRCCsIDkgOiAB+wL7ISC3ABogHiAwIMIAygDBAMsAyADNAM4AzwDMANMA1AD/+NIA2gDbANkAMQHGAtwCrwDYAtkC2gK4AN0C2wLHAg=="),
});

const cp1252High = [
  0x20ac, -1, 0x201a, 0x0192, 0x201e, 0x2026, 0x2020, 0x2021,
  0x02c6, 0x2030, 0x0160, 0x2039, 0x0152, -1, 0x017d, -1,
  -1, 0x2018, 0x2019, 0x201c, 0x201d, 0x2022, 0x2013, 0x2014,
  0x02dc, 0x2122, 0x0161, 0x203a, 0x0153, -1, 0x017e, 0x0178
];


export class PythonTextDecodeError extends Error {}

/** Existing strict single-byte decode loop; the caller bounds the input chunk. */
export function decodePythonSingleByte(bytes: Uint8Array, codepoints: readonly number[], encoding: string): string {
  let text = "";
  for (const byte of bytes) {
    const code = codepoints[byte]!;
    if (code < 0) throw new PythonTextDecodeError(`Invalid ${encoding} input`);
    text += String.fromCodePoint(code);
  }
  return text;
}

export const pythonSingleByteCodepages: Readonly<Record<string, readonly number[]>> = Object.freeze({
  ...Object.fromEntries(Object.entries(dbfCodepages).map(([name, codepoints]) => [pythonCodecAliases[normalizeEncoding(name)]!, codepoints])),
  ascii: Object.freeze(Array.from({ length: 256 }, (_, byte) => byte < 128 ? byte : -1)),
  "iso8859-1": Object.freeze(Array.from({ length: 256 }, (_, byte) => byte)),
  cp1252: Object.freeze(Array.from({ length: 256 }, (_, byte) => byte >= 128 && byte < 160 ? cp1252High[byte - 128]! : byte))
});
