import * as fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
const [repoArgument, ownArgument] = process.argv.slice(2);
assert(process.argv.length === 4);
const repo = fs.realpathSync(repoArgument), own = fs.realpathSync(ownArgument);
assert(own === path.join(repo, 'tests/shell/local-a-cleanup-v2-independent-20260829'));
assert(fs.fstatSync(1).isFile() && fs.fstatSync(2).isFile());
const sourceCommit = 'faff3d1b56b841594768e476700209e1d2bca734', evidenceCommit = '2e79988a91dcff82515771f5be4932b19429dad2';
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
function read(filename) { const before = fs.lstatSync(filename); assert(before.isFile() && before.size <= 16777216); const bytes = fs.readFileSync(filename), after = fs.lstatSync(filename); assert.equal(before.ino, after.ino); assert.equal(before.mtimeMs, after.mtimeMs); assert.equal(bytes.length, before.size); return bytes; }
function save(name, data) { const bytes = Buffer.from(JSON.stringify(data, null, 2) + '\n'); assert(bytes.length <= 16777216); fs.writeFileSync(path.join(own, name), bytes, { flag: 'wx', mode: 0o444 }); return { path: path.join(own, name), bytes: bytes.length, sha256: sha(bytes) }; }
const references = [sourceCommit + ':src/shell/runtime.ts', 'ec74e14df6bb7caf6b1be59fd44b027d7240101e:src/shell/runtime.ts', evidenceCommit + ':tests/shell/local-a-cleanup-v2/review.mjs', evidenceCommit + ':tests/shell/local-a-cleanup-v2/SOURCE-SEAL.json', evidenceCommit + ':tests/shell/local-a-cleanup-v2/RESULT.json', evidenceCommit + ':tests/shell/local-a-cleanup-v2/HANDOFF.md', sourceCommit + ':src/shell/arrays/ledger.ts'];
const stdout = fs.openSync(path.join(own, 'git-data.stdout'), 'wx'), stderr = fs.openSync(path.join(own, 'git-data.stderr'), 'wx');
const child = spawnSync('/usr/bin/git', ['cat-file','--batch'], { cwd: repo, input: references.join('\n') + '\n', env: { PATH: '/usr/bin:/bin', HOME: repo, GIT_CONFIG_NOSYSTEM: '1', GIT_CONFIG_GLOBAL: '/dev/null', GIT_OPTIONAL_LOCKS: '0' }, stdio: ['pipe', stdout, stderr], timeout: 60000 }); fs.closeSync(stdout); fs.closeSync(stderr); assert.equal(child.status, 0);
const capture = read(path.join(own, 'git-data.stdout')), objects = []; let offset = 0;
for (const reference of references) { const end = capture.indexOf(10, offset), [blob, kind, length] = capture.subarray(offset, end).toString().split(' '), size = Number(length); assert.equal(kind, 'blob'); assert(Number.isSafeInteger(size) && size <= 16777216); const bytes = capture.subarray(end + 1, end + 1 + size); assert.equal(crypto.createHash('sha1').update(Buffer.from('blob ' + size + '\0')).update(bytes).digest('hex'), blob); objects.push({ reference, blob, bytes: size, sha256: sha(bytes), body: bytes.toString() }); offset = end + size + 2; } assert.equal(offset, capture.length);
const source = objects[0].body, base = objects[1].body, author = objects[2].body, seal = JSON.parse(objects[3].body), historical = JSON.parse(objects[4].body), ledger = objects[6].body;
assert.equal(objects[0].sha256, 'bff86fcfc7f59b4f0a42a304edf72b9b69027b508c532b1401bea0628d201d2b'); assert.equal(objects[2].sha256, seal.helperSha256); assert.equal(objects[0].sha256, seal.sourceSha256); assert.equal(objects[1].sha256, seal.baseSha256);
const begin = '        if (command === "local" && indexedLocal) {', finish = '        if (command === "local" && !locals!.has(name)) {';
const start = source.indexOf(begin), end = source.indexOf(finish, start), baseStart = base.indexOf(begin), baseEnd = base.indexOf(finish, baseStart); assert(start > 0 && end > start); assert.equal(source.slice(0,start), base.slice(0,baseStart)); assert.equal(source.slice(end), base.slice(baseEnd));
const branch = source.slice(start,end); assert.equal(sha(Buffer.from(branch)), seal.branchSha256);
const fragment = branch.slice(branch.indexOf('          const existingLocal'), branch.lastIndexOf('          continue;')); assert.equal(fragment, seal.fragment);
let erased = fragment; for (const [before, after] of seal.replacements) { assert(erased.includes(before)); erased = erased.split(before).join(after); }
const execute = vm.runInNewContext('(async function(env){const {locals,assignments,saveVariable,typedSavedVariables,requireArrays,ArrayOwner,IndexedBinding,state,name,match,textToken,stateMonitor,context,invocationScope,ArrayFailure}=env;' + erased + '})', {}, { timeout: 1000 });
const probeStart = author.indexOf('  async function probe(options = {}) {'), probeEnd = author.indexOf('  const rows = [];', probeStart), checksStart = author.indexOf('  await check("C01-success"'), checksEnd = author.indexOf('  record("RESULT.json"', checksStart); assert(probeStart > 0 && probeEnd > probeStart && checksEnd > checksStart);
const probeSource = author.slice(probeStart, probeEnd), checks = author.slice(checksStart, checksEnd);
const replay = vm.runInNewContext('(async function(assert,execute,source,branch){' + probeSource + 'const rows=[]; async function check(id,body){try{await body();rows.push({id,pass:true});}catch(error){rows.push({id,pass:false,error:String(error)});}}' + checks + 'return {rows,probe};})', {}, { timeout: 1000 });
const replayed = await replay(assert, execute, source, branch); assert.equal(replayed.rows.length, 12);
const novel = [];
async function group(id, body) { try { const observations = await body(); novel.push({ id, pass: true, observations }); } catch (error) { novel.push({ id, pass: false, error: String(error), observations: error.observations ?? null }); } }
await group('N01-C05-named-publication-boundary', async () => { const observations = []; for (const stage of ['store','watch','reserve','name','shadow','text','insert','signal','publish']) { const result = await replayed.probe({ stage }); assert(result.present && result.actual === result.reason); const attached = stage === 'publish'; assert.equal(result.locals.get('ordinary') === result.saved, attached); assert.equal(result.typed.has(result.saved), attached); assert.equal(result.counts.discard, attached ? 0 : 1); assert(result.counts.operation <= 1 && result.counts.holding <= 1 && result.counts.shadow <= 1); observations.push({ stage, savedAttached: attached, typedSavedRetained: result.typed.has(result.saved), discard: result.counts.discard, variablePresent: Object.hasOwn(result.state.variables, 'ordinary') }); } return { conclusion: 'C05 blanket discarded=1 is a fixture expectation defect at publish; retaining attached typed restoration is correct for this boundary, not whole publication atomicity proof', cuts: observations }; });
await group('N02-borrowed-publication-failure', async () => { const observations = []; for (const existing of [false,true]) { const result = await replayed.probe({ existing, borrowed: !existing, typed: true, stage: 'publish', reason: null }); assert(result.present && result.actual === null); assert.equal(result.typed.get(result.saved), result.originalTyped); assert.equal(result.counts.prepare, 0); assert.equal(result.counts.discard, 0); assert.equal(result.locals.get('ordinary'), result.saved); observations.push({ existing, retainedOriginalTyped: true, discard: 0, prepare: 0 }); } return observations; });
await group('N03-raw-secondaries-order-and-bound', async () => { const observations = []; for (const primary of [undefined,null,false,0]) { const secondary = { discard: { stage: 'discard' }, shadow: { stage: 'shadow' }, operation: { stage: 'operation' }, holding: { stage: 'holding' } }; const result = await replayed.probe({ stage: 'signal', reason: primary, cleanup: Object.keys(secondary), cleanupReasons: secondary }); assert(result.present && result.actual === primary); assert.equal(result.failures.length, 4); for (const [index, stage] of Object.keys(secondary).entries()) { assert.equal(result.failures[index], secondary[stage]); assert.equal(result.counts[stage], 1); } observations.push({ primaryKind: primary === undefined ? 'undefined' : primary === null ? 'null' : String(primary), rawPrimaryPreserved: true, exactSecondaries: 4, allCleanupAttempts: true }); } return observations; });
const prepareStart = source.indexOf('  async prepareVariable('), prepareEnd = source.indexOf('\n  async prepareArrayObservers(', prepareStart), method = source.slice(prepareStart, prepareEnd), methodBody = method.slice(method.indexOf('{') + 1, method.lastIndexOf('}')).replace('let binding: IndexedBinding | undefined;', 'let binding;');
const discardStart = source.indexOf('  async discardVariable('), discardEnd = source.indexOf('\n  async indexedEnvironment(', discardStart), discard = source.slice(discardStart, discardEnd), discardBody = discard.slice(discard.indexOf('{') + 1, discard.lastIndexOf('}'));
assert(methodBody.includes('const holding = store.owner.hold();\n    let binding;\n    try {')); assert(ledger.includes('const header = ledger.reserve({ metadata: 64, work: 9 });')); assert(ledger.includes('const admission = this.reserve({ metadata: 64, work: 5 });'));
const prepareFactory = vm.runInNewContext('(function(env){const {requireArrays,ArrayOwner,textToken,typedSavedVariables}=env;return async function(state,name,saved,scalarLegacy=false){' + methodBody + '};})', {}, { timeout: 1000 });
const discardFactory = vm.runInNewContext('(function(typedSavedVariables){return async function(saved){' + discardBody + '};})', {}, { timeout: 1000 });
await group('N04-internal-prepare-owner-invisible-on-hold-refusal', async () => {
  const saved = { value: 'outer' }, typed = new WeakMap(), locals = new Map(), assignments = new Map(), failures = [], invocationScope = Symbol('scope'), primary = { budget: 'metadata remaining below hold admission' };
  let metadataRemaining = 64, createdOwners = 0, closedOwners = 0, discardCalls = 0, prepareCalls = 0;
  const reserve = charge => { if ((charge.metadata ?? 0) > metadataRemaining) throw primary; metadataRemaining -= charge.metadata ?? 0; return {}; };
  const parent = { ledger: { reserve }, hold() { reserve({ metadata: 64, work: 5 }); return { release() {} }; } };
  const store = { owner: parent }, state = { variables: { ordinary: 'inner' }, readonlyVariables: new Set() };
  const environment = { locals, assignments, saveVariable: () => saved, typedSavedVariables: typed, requireArrays: () => store, ArrayOwner: { create(ledger) { ledger.reserve({ metadata: 64, work: 9 }); createdOwners++; return { async close() { closedOwners++; } }; } }, IndexedBinding: {}, state, name: 'ordinary', match: ['ordinary','ordinary'], textToken() { throw new Error('unreached'); }, stateMonitor() { throw new Error('unreached'); }, context: { [invocationScope]: { failures } }, invocationScope, ArrayFailure: Error };
  const prepare = prepareFactory(environment), discardSaved = discardFactory(typed), receiver = { signal: { throwIfAborted() {} }, async prepareVariable(...args) { prepareCalls++; return prepare.apply(this, args); }, async discardVariable(value) { discardCalls++; return discardSaved.call(this, value); } };
  let caught = false, actual; try { await execute.call(receiver, environment); } catch (error) { caught = true; actual = error; }
  assert(caught && actual === primary); assert.equal(createdOwners, 1); assert.equal(closedOwners, 0); assert.equal(discardCalls, 1); assert.equal(typed.has(saved), false); assert.equal(locals.size, 0);
  const error = new Error('New local-a branch directly calls unchanged prepareVariable: owner header admission succeeds, internal hold refuses before helper try/typed registration; caller discard cannot reach that owner');
  error.observations = { metadataHeadroomAtEntry: 64, actualSourceCreateCharge: 64, actualSourceHoldCharge: 64, prepareCalls, createdOwners, closedOwners, discardCalls, savedRegistered: false, localsAttached: false, rawBudgetReasonPreserved: true, ownershipQualification: 'Exact new branch + exact unchanged prepare/discard fragments; finite reservation doubles, no real ArrayOwner instance or permanent leak claim', dependency: 'preexisting helper defect, newly required by generic local-a entry; not introduced by v2 cleanup diff' }; throw error;
});
const candidatePath = path.join(repo, 'tests/compatibility/final-composition-readiness-20260829/reconciliation-v2/CANDIDATE-INPUTS.json'), candidateRaw = read(candidatePath), candidate = JSON.parse(candidateRaw);
save('FRAGMENT-BINDINGS.json', { authorSourceFragment: seal, authorProbeSha256: sha(Buffer.from(probeSource)), authorChecksSha256: sha(Buffer.from(checks)), prepareMethod: method, discardMethod: discard, internalErasure: ['prepareVariable argument annotations replaced by explicit test signature','local binding type annotation'], baselinePrefixSuffixEqual: true, noProductClassesImportedOrExecuted: true });
const readiness = save('SOURCE-READINESS.json', { verdict: 'HOLD_TRANSITIVE_PREPARATION_ADMISSION', cleanupDeltaVerdict: 'SOURCE_PURE_ACCEPT_FOR_THREE_PRIOR_BRANCH_FINDINGS', fullLocalAFeatureAcceptance: false, c05: 'Fixture assertion defect independently isolated; original 11/12 remains', requiredSmallestFix: 'In prepareVariable, place fallible store.owner.hold acquisition under the existing owner cleanup try; make holding optional in finally so successfully created owner is closed when hold refuses. ROOT approval needed for this narrowly implicated helper scope.', sourceCommit, runtimeSha256: objects[0].sha256, candidate: { path: candidatePath, sha256: sha(candidateRaw), sourceCount: candidate.sourceCount }, compositionUpdated: false, all323FeaturesRemainSelected: true, noBuildGO: true });
const files = fs.readdirSync(own).filter(name => fs.lstatSync(path.join(own, name)).isFile()).map(name => { const bytes = read(path.join(own, name)); return { path: name, bytes: bytes.length, sha256: sha(bytes) }; });
const receipt = save('RESULT.json', { at: new Date().toISOString(), verdict: 'HOLD_TRANSITIVE_PREPARATION_ADMISSION', sourceCommit, evidenceCommit, authenticated: objects.map(({ body, ...item }) => item), authorReplay: { pass: replayed.rows.filter(row => row.pass).length, total: 12, rows: replayed.rows, originalReportedPass: historical.passed }, novel: { pass: novel.filter(row => row.pass).length, total: 4, rows: novel }, c05OriginalFailurePreserved: true, c05IndependentAttribution: 'Saved already attached to locals at injected publish failure; discard would invalidate restoration', priorThreeBranchFindingsResolved: true, remainingFindingPreexistedHelperButNewCallerDependsOnIt: true, sourceReadiness: readiness, controlsQualification: 'SOURCE plus exact isolated branch/prepare/discard fragments and doubles; no actual binding atomicity/restore/budget proof', counts: { pureHelperInvocations: 1, helperGitChildren: 1, knownRolesThroughHelper: 11, maximumKnownRoles: 24, conservativePeak: 3, maximumPeak: 3, gitExit: child.status, gitSignal: child.signal }, retainedLogicalBytes: files.reduce((sum, item) => sum + item.bytes, 0), captureBytes: files.filter(item => /\.(stdout|stderr|raw)$/.test(item.path)).reduce((sum, item) => sum + item.bytes, 0), publicationReserveBytes: 16777216, captureMaximum: 25165824, workMaximum: 134217728, deadline: '2026-08-29T17:23:21Z', product: 0, Workers: 0, compiler: 0, npm: 0, sourceEdits: 0, priorHOLD: '42530f2839dccd98a63e6d14d32354ad1022462f', retained: files });
console.log(JSON.stringify({ verdict: 'HOLD', branchDelta: 'prior three cleanup findings resolved', authorReplay: replayed.rows.filter(row => row.pass).length + '/12', authorFailures: replayed.rows.filter(row => !row.pass), novel: novel.filter(row => row.pass).length + '/4', findings: novel.filter(row => !row.pass), c05FixtureDefectConfirmed: true, receipt, compositionUpdated: false }));
