export const cases: readonly { id: string; setup: string; word: string; expected: readonly string[]; baselineFailure?: boolean }[] = [
  { id: "S06-two-empty", setup: "a=(); b=()", word: '"${a[@]}${b[@]}"', expected: [], baselineFailure: true },
  { id: "three-empty", setup: "a=(); b=(); c=()", word: '"${a[@]}${b[@]}${c[@]}"', expected: [], baselineFailure: true },
  { id: "repeated-empty", setup: "a=()", word: '"${a[@]}${a[@]}${a[@]}${a[@]}"', expected: [], baselineFailure: true },
  { id: "separate-quote-groups", setup: "a=(); b=()", word: '"${a[@]}""${b[@]}"', expected: [], baselineFailure: true },
  { id: "single-empty-at", setup: "a=()", word: '"${a[@]}"', expected: [], baselineFailure: true },
  { id: "S08-explicit-empty-before", setup: "a=()", word: '"""${a[@]}"', expected: [""] },
  { id: "explicit-empty-between", setup: "a=(); b=()", word: '"${a[@]}""""${b[@]}"', expected: [""] },
  { id: "explicit-empty-after", setup: "a=(); b=()", word: '"${a[@]}${b[@]}"""', expected: [""] },
  { id: "single-quoted-empty", setup: "a=(); b=()", word: "''\"${a[@]}${b[@]}\"", expected: [""] },
  { id: "ansi-empty", setup: "a=(); b=()", word: "$''\"${a[@]}${b[@]}\"", expected: [""] },
  { id: "empty-scalar-before", setup: 'a=(); b=(); empty=""', word: '"${empty}${a[@]}${b[@]}"', expected: [""] },
  { id: "empty-scalar-between", setup: 'a=(); b=(); empty=""', word: '"${a[@]}${empty}${b[@]}"', expected: [""] },
  { id: "empty-scalar-after", setup: 'a=(); b=(); empty=""', word: '"${a[@]}${b[@]}${empty}"', expected: [""] },
  { id: "unset-scalar-between", setup: "a=(); b=(); unset missing", word: '"${a[@]}${missing}${b[@]}"', expected: [""] },
  { id: "actual-empty-member-left", setup: 'a=(""); b=()', word: '"${a[@]}${b[@]}"', expected: [""] },
  { id: "actual-empty-member-right", setup: 'a=(); b=("")', word: '"${a[@]}${b[@]}"', expected: [""] },
  { id: "two-actual-empty-members", setup: 'a=("" ""); b=()', word: '"${a[@]}${b[@]}"', expected: ["", ""] },
  { id: "empty-prefix", setup: "a=(); b=()", word: 'pre"${a[@]}${b[@]}"', expected: ["pre"] },
  { id: "empty-suffix", setup: "a=(); b=()", word: '"${a[@]}${b[@]}"post', expected: ["post"] },
  { id: "empty-prefix-suffix", setup: "a=(); b=()", word: 'pre"${a[@]}${b[@]}"post', expected: ["prepost"] },
  { id: "literal-separator", setup: "a=(); b=()", word: '"${a[@]}:${b[@]}"', expected: [":"] },
  { id: "literal-double-quote", setup: "a=(); b=()", word: '"${a[@]}\\"${b[@]}"', expected: ['"'] },
  { id: "literal-single-quote", setup: "a=(); b=()", word: '"${a[@]}\'${b[@]}"', expected: ["'"] },
  { id: "escaped-quote-outside", setup: "a=(); b=()", word: '\\""${a[@]}${b[@]}"', expected: ['"'] },
  { id: "nonempty-at-splice", setup: "a=(A B); b=(C D)", word: '"${a[@]}${b[@]}"', expected: ["A", "BC", "D"] },
  { id: "nonempty-at-repeat", setup: "a=(A B); b=(C D)", word: 'pre"${a[@]}:${b[@]}:${a[@]}"post', expected: ["preA", "B:C", "D:A", "Bpost"] },
  { id: "empty-left-nonempty", setup: "a=(); b=(C D)", word: '"${a[@]}${b[@]}"', expected: ["C", "D"] },
  { id: "nonempty-left-empty", setup: "a=(A B); b=()", word: '"${a[@]}${b[@]}"', expected: ["A", "B"] },
  { id: "empty-between-nonempty", setup: "a=(A B); b=(); c=(C D)", word: '"${a[@]}${b[@]}${c[@]}${b[@]}${a[@]}"', expected: ["A", "BC", "DA", "B"] },
  { id: "quoted-empty-star", setup: "a=(); b=()", word: '"${a[*]}${b[*]}"', expected: [""] },
  { id: "quoted-star-before-at", setup: "a=(); b=()", word: '"${a[*]}${b[@]}"', expected: [""] },
  { id: "quoted-star-after-at", setup: "a=(); b=()", word: '"${a[@]}${b[*]}"', expected: [""] },
  { id: "nonempty-star-join", setup: "a=(A B); b=(C D)", word: '"${a[*]}${b[*]}"', expected: ["A BC D"] },
  { id: "nonempty-star-at", setup: "a=(A B); b=(C D); IFS=: ", word: '"${a[*]}${b[@]}"', expected: ["A:BC", "D"] },
  { id: "unquoted-empty-at", setup: "a=(); b=()", word: '${a[@]}${b[@]}', expected: [] },
  { id: "unquoted-empty-star", setup: "a=(); b=()", word: '${a[*]}${b[*]}', expected: [] },
  { id: "quoted-unquoted-empty", setup: "a=(); b=()", word: '"${a[@]}"${b[@]}', expected: [], baselineFailure: true },
  { id: "unquoted-quoted-empty", setup: "a=(); b=()", word: '${a[@]}"${b[@]}"', expected: [], baselineFailure: true },
  { id: "unquoted-scalar-between", setup: 'a=(); b=(); empty=""', word: '"${a[@]}"${empty}"${b[@]}"', expected: [], baselineFailure: true },
  { id: "unquoted-nonempty-splice", setup: "a=(A B); b=(C D)", word: '${a[@]}${b[@]}', expected: ["A", "BC", "D"] },
  { id: "mixed-split-preserved", setup: 'a=("A B" C); b=("D E" F)', word: '"${a[@]}"${b[@]}', expected: ["A B", "CD", "E", "F"] },
  { id: "scalar-empty-quoted", setup: 'empty=""', word: '"$empty"', expected: [""] },
  { id: "scalar-empty-unquoted", setup: 'empty=""', word: '$empty', expected: [] },
  { id: "positional-empty-at", setup: "set --", word: '"$@"', expected: [] },
  { id: "positional-empty-star", setup: "set --", word: '"$*"', expected: [""] },
  { id: "positional-members", setup: 'set -- "A B" "" C', word: '"$@"', expected: ["A B", "", "C"] },
  { id: "positional-prefix-suffix", setup: "set -- A B", word: 'pre"$@"post', expected: ["preA", "Bpost"] },
  { id: "positional-star", setup: "set -- A B; IFS=:", word: '"$*"', expected: ["A:B"] },
  { id: "lazy-alternate-empty-aggregate", setup: "a=(); b=(); unset missing", word: '"${a[@]}${missing-"${b[@]}"}"', expected: [], baselineFailure: true },
  { id: "lazy-alternate-explicit-empty", setup: "a=(); unset missing", word: '"${a[@]}${missing-""}"', expected: [""] },
];

export function script(entry: (typeof cases)[number]): string {
  return `${entry.setup}; __array_value ${entry.word}; __array_status "$?"`;
}
