import {strict as assert} from 'node:assert';
import {readFileSync} from 'node:fs';
import {fixture} from './fixture.mjs';
import {judge} from './snapshot/followup-preparation-r4/receipt-gate.mjs';
import {createRetirementLatch} from './snapshot/followup-preparation-r4/retirement-latch.mjs';
const rows=[];function check(id,body){try{const evidence=body();rows.push({id,pass:true,evidence});}catch(error){rows.push({id,pass:false,error:{name:error?.name,message:error?.message}});}}
check('N01-required-EOF-and-descriptors',()=>{let getterCalls=0;let refused=0;for(const keys of [['stdoutEnded'],['stderrEnded'],['stdoutEnded','stderrEnded']]){const row=fixture();for(const key of keys)row.processRow[key]=false;assert.throws(()=>judge(row.receipt,row.processRow,row.config));refused++;}for(const key of ['stdoutEnded','stderrEnded']){const row=fixture();Object.defineProperty(row.processRow,key,{get(){getterCalls++;return true;}});assert.throws(()=>judge(row.receipt,row.processRow,row.config));refused++;}const good=fixture();assert.equal(judge(good.receipt,good.processRow,good.config),'PASS');assert.equal(getterCalls,0);return {refused,getterCalls};});
check('N02-falsy-primary-after-semantic-UNKNOWN',()=>{const evidence=[];for(const reason of [undefined,null,false,0,new Error('owned-marker')]){const row=fixture('persistent');const latch=createRetirementLatch();latch.begin(1);latch.observe(row.receipt);row.receipt.caseSha256='f'.repeat(64);assert.throws(()=>judge(row.receipt,row.processRow,row.config));try{throw reason;}catch(caught){latch.recordPrimary(caught);}latch.recordPrimary(new Error('secondary'));assert.equal(latch.primary.present,true);assert.strictEqual(latch.primary.value,reason);assert.equal(latch.unconfirmed,true);latch.validated('PASS');assert.equal(latch.unconfirmed,true);assert.throws(()=>latch.begin(0));evidence.push({kind:reason===null?'null':typeof reason,identity:true,sticky:true});}return evidence;});
check('N03-pending-before-acquisition-and-conservative-failure',()=>{for(const reason of [undefined,false,0]){const latch=createRetirementLatch();latch.begin(1);try{throw reason;}catch(caught){latch.recordPrimary(caught);}assert.equal(latch.unconfirmed,true);assert.strictEqual(latch.primary.value,reason);}let getterCalls=0;const latch=createRetirementLatch();latch.begin(1);assert.throws(()=>latch.observe(Object.defineProperty({},'retirementState',{get(){getterCalls++;return 'RETIRED';}})));assert.equal(latch.unconfirmed,true);assert.equal(getterCalls,0);const normal=createRetirementLatch();normal.begin(1);normal.observe({retirementState:'RETIRED'});assert.equal(normal.unconfirmed,true);normal.validated('PASS');assert.equal(normal.unconfirmed,false);return {pendingPreserved:3,getterCalls,onlyValidatedPassClears:true};});
check('N04-post-judgment-census-and-source-order',()=>{const row=fixture('persistent');const latch=createRetirementLatch();latch.begin(1);latch.observe(row.receipt);const disposition=judge(row.receipt,row.processRow,row.config);assert.equal(disposition,'STOP_UNCONFIRMED');latch.validated(disposition);const marker={fault:'census'};try{throw marker;}catch(reason){latch.recordPrimary(reason);}assert.equal(latch.unconfirmed,true);assert.strictEqual(latch.primary.value,marker);const source=readFileSync(new URL('./snapshot/followup-preparation-r4/supervisor.mjs',import.meta.url),'utf8');const before=(left,right)=>{assert(source.indexOf(left)>=0);assert(source.indexOf(left)<source.indexOf(right));};before('lifetime.begin(cell.Workers)','await ownChild(');before("if(observed.state==='STOP_UNKNOWN')retained.push(acquired.ownership)",'captures+=observed.stdoutBytes');before('lifetime.observe(receipt)','disposition=judge(');before('lifetime.validated(disposition)','const after=census(');assert(source.includes("cell.purpose==='persistent'&&index!==12"));assert(source.includes('retainedUnknown:retained.length>0||lifetime.unconfirmed'));assert(source.includes("recovery:'NONE_AUTHORIZED',archive:false,cleanup:false"));return {disposition,stickyAfterCensus:true,sourceOnlyOrderChecks:7};});
console.log(JSON.stringify({schema:1,total:4,passed:rows.filter(row=>row.pass).length,rows,children:0,Workers:0,productImports:0}));if(rows.some(row=>!row.pass))process.exitCode=1;
