import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const home=path.dirname(fileURLToPath(import.meta.url)),fd=fs.openSync(path.join(home,'PUBLICATION.json'),'wx',0o600);
const insist=(value,code)=>{if(!value)throw Error(code);};
async function bind(filename,cap=262144){const info=fs.lstatSync(filename);insist(info.isFile()&&!info.isSymbolicLink()&&info.size<=cap,'FILE_ADMISSION');const digest=createHash('sha256');let bytes=0;for await(const chunk of fs.createReadStream(filename,{highWaterMark:65536})){bytes+=chunk.length;insist(bytes<=info.size,'GROWTH');digest.update(chunk);}insist(bytes===info.size,'SHORT');return{path:filename,bytes,mode:info.mode&511,sha256:digest.digest('hex')};}
function json(filename){const info=fs.lstatSync(filename);insist(info.isFile()&&!info.isSymbolicLink()&&info.size<=262144,'JSON_ADMISSION');return JSON.parse(fs.readFileSync(filename,'utf8'));}
let output;
try{const seal=json(path.join(home,'PRESEAL.json')),result=json(path.join(home,'RESULT.json')),capture=json(path.join(home,'raw/RECEIPT.json'));insist(result.author.passed===12&&result.independent.passed===12&&capture.errors.length===0&&capture.close.code===0&&capture.preflight&&capture.postflight,'CONTROL_CAPTURE');const guards=[];for(const row of[...seal.inputs,...seal.assets,...seal.own,seal.node]){const actual=await bind(row.path,120000000);insist(actual.sha256===row.sha256&&actual.bytes===row.bytes&&actual.mode===row.mode,'SOURCE_TOOL_DRIFT');guards.push(actual);}const files=[];let total=0;async function walk(directory){for(const name of fs.readdirSync(directory).sort()){const filename=path.join(directory,name),relative=path.relative(home,filename);if(['PUBLICATION.json','publish.stdout.raw','publish.stderr.raw'].includes(relative))continue;const info=fs.lstatSync(filename);insist(!info.isSymbolicLink(),'LINK');if(info.isDirectory())await walk(filename);else{const row=await bind(filename);total+=row.bytes;insist(files.length<80&&total<2097152,'EVIDENCE_BOUND');files.push({...row,path:relative});}}}await walk(home);output={schema:'PRIVATE_ERE_CORRECTIVE_REVIEW_PUBLICATION',verdict:'SOURCE_HOLD',review:await bind(path.join(home,'REVIEW.json')),guards,files,totalFileBytes:total,controlCapture:capture,authorPure:12,independentPure:12,loadedPureModules:5,Workers:0,ownerImports:0,matchingCalls:0,all60:'UNRUN',processes:{pureHelpersIncludingCaptureOwner:2,fixtureChildren:1,peak:2,allOwnedRoleUpperBoundIncludingFinalGit:44,cap:48,qualification:'Conservative tool-route bound including shell/Git/patch allowances, not44 individually measured PIDs or universal census. Final Git remains prospective here.'},captureUpperBoundIncludingArchiveDecodeAndPublicationReserve:8388608,workUpperBound:16777216,preparationAdmissionRefusal:'PRESEAL-v3 text exceeded65536-byte helper cap; no retry/read-cap increase',checkpoint:new Date().toISOString(),runtimeGO:false};}catch(error){output={verdict:'PUBLICATION_HOLD',message:error.message};process.exitCode=1;}
fs.writeSync(fd,JSON.stringify(output,null,2)+'\n');fs.fsyncSync(fd);fs.closeSync(fd);console.log(JSON.stringify({verdict:output.verdict,reviewSha256:output.review?.sha256,guards:output.guards?.length,files:output.files?.length,bytes:output.totalFileBytes,message:output.message??null}));
