import fs from 'node:fs';
import path from 'node:path';
import {gzipSync} from 'node:zlib';
import {hash,readPinned} from './auth.mjs';
export function write(filename,bytes,mode=0o600){fs.mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});const descriptor=fs.openSync(filename,'wx',mode);try{fs.writeFileSync(descriptor,bytes);fs.fsyncSync(descriptor);}finally{fs.closeSync(descriptor);}}
export function inventory(root,maximum=33554432){let total=0;const rows=[];function visit(relative){for(const name of fs.readdirSync(path.join(root,relative)).sort()){const next=relative?relative+'/'+name:name;const stat=fs.lstatSync(path.join(root,next));if(stat.isSymbolicLink())throw Error('MEMBER_SYMLINK');if(stat.isDirectory())visit(next);else if(stat.isFile()){if(rows.length>=2000||total+stat.size>maximum)throw Error('MEMBER_LIMIT');total+=stat.size;const bytes=fs.readFileSync(path.join(root,next));rows.push({path:next,bytes:bytes.length,sha256:hash(bytes),mode:stat.mode&0o777});}else throw Error('MEMBER_TYPE');}}visit('');return Object.freeze({root,bytes:total,rows});}
export function sample(root,maximum){let bytes=0,entries=0;function visit(filename){if(++entries>16000)throw Error('WORK_ENTRIES');const stat=fs.lstatSync(filename);if(stat.isSymbolicLink())throw Error('WORK_SYMLINK');if(stat.isDirectory())for(const name of fs.readdirSync(filename))visit(path.join(filename,name));else if(stat.isFile()){bytes+=stat.size;if(bytes>maximum)throw Error('WORK_BYTES');}else throw Error('WORK_TYPE');}visit(root);return Object.freeze({root,at:Date.now(),bytes,entries,qualification:'fresh sampled logical owned files, not RSS/continuous quota'});}
export function pack(root,members){const chunks=[];let total=1024;for(const row of members){const filename='package/'+row.path;const header=Buffer.alloc(512);let name=filename,prefix='';if(Buffer.byteLength(name)>100){const split=filename.lastIndexOf('/');prefix=filename.slice(0,split);name=filename.slice(split+1);}if(Buffer.byteLength(name)>100||Buffer.byteLength(prefix)>155)throw Error('TAR_PATH');header.write(name,0,100);header.write(prefix,345,155);const octal=(offset,length,value)=>header.write(value.toString(8).padStart(length-1,'0')+'\0',offset,length);octal(100,8,row.mode);octal(108,8,0);octal(116,8,0);octal(124,12,row.bytes);octal(136,12,0);header.fill(32,148,156);header[156]=48;header.write('ustar\0',257,6);header.write('00',263,2);const checksum=header.reduce((sum,value)=>sum+value,0);header.write(checksum.toString(8).padStart(6,'0')+'\0 ',148,8);const data=readPinned(path.join(root,row.path),row);chunks.push(header,data,Buffer.alloc((512-row.bytes%512)%512));total+=512+Math.ceil(row.bytes/512)*512;if(total>33554432)throw Error('TAR_BYTES');}chunks.push(Buffer.alloc(1024));const decoded=Buffer.concat(chunks,total);const compressed=gzipSync(decoded,{level:9});if(compressed.length>2097152)throw Error('PACK_COMPRESSED');return {compressed,decodedBytes:decoded.length};}
export function extract(buffer,destination){let offset=0;while(offset+512<=buffer.length){const header=buffer.subarray(offset,offset+512);if(header.every(value=>value===0))break;const field=(start,length)=>header.subarray(start,start+length).toString().split('\0')[0];const prefix=field(345,155),name=(prefix?prefix+'/':'')+field(0,100);const size=parseInt(field(124,12).trim(),8),mode=parseInt(field(100,8).trim(),8);write(path.join(destination,name.slice(8)),buffer.subarray(offset+512,offset+512+size),mode);offset+=512+Math.ceil(size/512)*512;}}
