import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const owned = dirname(fileURLToPath(import.meta.url));
const root = resolve(owned, '../../../..');
const capture = join(owned, 'candidate-01');
const load = name => JSON.parse(readFileSync(join(capture, name)));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const git = (...args) => execFileSync('git', args, { cwd: root, timeout: 120000, maxBuffer: 128 * 1024 * 1024 });
const manifest = load('CORRECTION-MANIFEST.json');
const current = load('shared11-process.json');
const previous = load('original-candidate-01-shared11-process.json');
const source = load('source-before.json');
const candidate = load('candidate.json');
const qualification = load('qualification.json');
const tests = text => text.split('ℹ tests ')[0].split('\n').filter(line => /^[✔✖] /u.test(line)).map(line => line.replace(/^[✔✖] /u, '').replace(/ \([\d.]+ms\)$/u, ''));
assert.deepEqual(current.args, previous.args);
assert.equal(current.executable, previous.executable);
assert.deepEqual(tests(current.stdout), tests(previous.stdout));
assert.equal(tests(current.stdout).length, 276);
assert.equal(current.status, 0);
assert.equal(current.signal, null);
assert.equal(current.error, null);
assert.equal(previous.status, 1);
assert.equal(current.stderr, '');
assert.equal(hash(readFileSync(join(owned, 'review.mjs'))), manifest.harnessSha256);
assert.equal(hash(readFileSync(join(capture, 'CORRECTION-MANIFEST.json'))), load('FREEZE.json').manifestSha256);
assert(manifest.frozenAt < load('build-process.json').started);
assert(manifest.frozenAt < current.started);
const inputs = Object.entries(source).filter(([, entry]) => entry.kind === 'file');
for (const [filename, entry] of inputs) assert.equal(hash(git('show', `${candidate.candidate}:${filename}`)), entry.sha256, filename);
assert.equal(inputs.length, 349);
assert.equal(hash(git('archive', '--format=tar', candidate.candidate, ...candidate.selected)), candidate.archiveSha256);
for (const [before, after] of [['source-before.json', 'source-after.json'], ['runtime-before.json', 'runtime-after.json'], ['build-before.json', 'build-after.json'], ['tooling-before.json', 'tooling-after.json'], ['original-review-before.json', 'original-review-after.json']]) assert.deepEqual(load(before), load(after));
const originalBuild = JSON.parse(git('show', `${manifest.originalCommit}:tests/commands/expr-stress/encounter-final-review-v2-20260827/candidate-01/compiled-before.json`));
assert.deepEqual(load('build-before.json'), originalBuild);
const tools = [qualification.node, qualification.compiler, qualification.git, qualification.tar, load('native-before.json')].map(entry => {
  const observedSha256 = hash(readFileSync(entry.realpath));
  assert.equal(observedSha256, entry.sha256);
  return { path: entry.path, realpath: entry.realpath, expectedSha256: entry.sha256, observedSha256 };
});
const originalAudit = load('original-SOURCE-AUDIT.json');
const glob = originalAudit.sharedHashes.find(entry => !entry.sameAsQualified);
assert.equal(glob.filename, 'tests/commands/regex-execution/continuation/glob.test.ts');
assert.equal(hash(git('show', `ec59c917ba137126a064960995b5fc6945ea8f6d:${glob.filename}`)), source[glob.filename].sha256);
assert.equal(hash(git('show', `cf5caabebff6eaec146700d4dd8c707ff8958e96:${glob.filename}`)), glob.qualifiedSha256);
assert.equal(git('diff', 'cf5caabebff6eaec146700d4dd8c707ff8958e96', candidate.candidate, '--', glob.filename).toString(), glob.diffFromQualified);
const cleanup = load('CLEANUP.json');
assert(cleanup.absent && !existsSync(cleanup.removedExactDirectory));
assert.deepEqual(cleanup.remainingOwnedProcesses, []);
const result = { auditedAt: new Date().toISOString(), candidate: candidate.candidate, exactArgvAndExecutable: true, sameOrderedTestNames: tests(current.stdout), testCount: 276, nativeDifferentialTestCount: tests(current.stdout).filter(name => name.startsWith('rg native differential:')).length, all349ArchivedInputsAuthenticatedAgain: true, correctionFrozenBeforeBuildAndTests: true, harnessMatchesPreExecutionHash: true, admittedEc59GlobDeltaAuthenticated: glob, originalCompiledEntrySetAndBytesIdentical: true, allBeforeAfterInventoriesAppendAwareAndEqual: true, toolHashPostcheck: tools, scratchStillAbsent: true, counts: load('SUMMARY.json') };
writeFileSync(join(owned, 'AUDIT.json'), `${JSON.stringify(result, null, 2)}\n`, { flag: 'wx' });
console.log(JSON.stringify({ candidate: candidate.candidate, tests: result.testCount, nativeDifferentials: result.nativeDifferentialTestCount, archivedFiles: inputs.length, buildMatchesOriginal: true }));
