export const diagnosticCases = [
  { name: "double-quote-eof", source: 'printf touched >marker; printf "unterminated' },
  { name: "double-quote-later-unit", source: ': >before;\nprintf "unterminated' },
  { name: "double-quote-multiline", source: 'printf "one\ntwo\n' },
  { name: "single-quote-eof", source: "printf touched >marker; printf 'unterminated" },
  { name: "single-quote-multiline", source: "printf 'one\ntwo\n" },
  { name: "ansi-quote-eof", source: "printf %s $'unterminated" },
  { name: "group-eof", source: "{ printf touched >marker;" },
  { name: "group-later-unit", source: ": >before;\n{ : >wrong;" },
  { name: "nested-group-eof", source: "{\n{ :;\n" },
  { name: "group-with-completed-if", source: "{ if true; then :; fi;" },
  { name: "if-with-incomplete-group", source: "if true; then { :;" },
  { name: "nul-one-warning-per-substitution", source: "value=$(printf 'a\\0b\\0\\n\\n'); printf '<%s>:%s' \"$value\" \"$?\"" },
  { name: "nul-two-substitutions", source: "value=$(printf 'a\\0b')$(printf 'c\\0d'); printf '<%s>' \"$value\"" },
  { name: "nul-multiline-assignment", source: "value=$(\nprintf 'a\\0b'\n); printf '<%s>' \"$value\"" },
  { name: "nul-multiline-backtick-assignment", source: "value=`\nprintf 'a\\0b'\n`; printf '<%s>' \"$value\"" },
  { name: "nul-multiline-argument", source: "printf '<%s>' \"\n$(printf 'a\\0b')\"" },
  { name: "nul-multiline-backtick-argument", source: "printf '<%s>' \"\n`printf 'a\\0b'`\"" },
  { name: "nul-function-definition-line", source: "call() {\nvalue=$(printf 'a\\0b')\n};\ncall" },
  { name: "nul-nested-substitution-line", source: "value=$(\nprintf '%s' \"$(printf 'a\\0b')\"\n); printf '<%s>' \"$value\"" },
  { name: "nul-redirected-parent-stderr", source: "{ value=$(\nprintf 'a\\0b'\n); printf '<%s>' \"$value\"; } 2>errors" },
  { name: "nul-heredoc-command-line", source: "cat <<EOF\n$(printf 'a\\0b')\nEOF\n" },
  { name: "nul-here-string-command-line", source: "cat <<<\"\n$(printf 'a\\0b')\"" },
  { name: "nul-short-circuit-not-expanded", source: "false && value=$(printf 'a\\0b'); :" },
  { name: "nul-binary-pipeline-control", source: "printf 'a\\0b' | cat" },
  { name: "nul-continued-command-line", source: "printf \\\n'<%s>' \"$(printf 'a\\0b')\"" },
  { name: "arithmetic-multiline-argument", source: ": >before;\nprintf '%s' \"\n$((1/0))\"; : >wrong" },
  { name: "parameter-multiline-argument", source: ": >before;\nprintf '%s' \"\n${missing:?stop}\"; : >wrong" },
  { name: "arithmetic-multiline-assignment", source: "value=\"\n$((1/0))\"; : >wrong" },
  { name: "parameter-multiline-assignment", source: "value=\"\n${missing:?stop}\"; : >wrong" },
  { name: "parameter-multiline-redirection", source: ": >before;\n: >\"\n${missing:?stop}\"; : >wrong" },
  { name: "parameter-multiline-redirect-only", source: ">\"\n${missing:?stop}\"; : >wrong" },
  { name: "nul-redirection-first-command-line", source: ">\"\nfile\" value=$(printf 'a\\0b'); printf '<%s>' \"$value\"" },
  { name: "cd-missing", source: "cd missing" },
  { name: "cd-nondirectory", source: ": >file; cd file" },
  { name: "cd-nondirectory-tail", source: ": >file; cd file/child" },
  { name: "cd-error-redirected", source: "cd missing 2>errors; printf '%s' \"$?\"; : >after" },
  { name: "redirect-missing-control", source: "cat <missing" },
  { name: "redirect-shortcut-missing-control", source: "value=$(<missing); printf '%s' \"$?\"" },
] as const;
