// Static vocabulary ported from toolcraft-design/terminal-markdown/parser/code-highlight.
// No build-time or runtime dependency on the reference package.
use super::{Family, Language, LexicalSpec};

pub fn language(alias: &str) -> Option<Language> {
    match alias {
        "javascript" | "js" | "mjs" | "cjs" | "es6" => Some(Language {
            family: Family::Lexical,
            spec: "javascript",
        }),
        "javascriptreact" | "jsx" => Some(Language {
            family: Family::Lexical,
            spec: "javascript",
        }),
        "typescript" | "ts" | "mts" | "cts" => Some(Language {
            family: Family::Lexical,
            spec: "typescript",
        }),
        "typescriptreact" | "tsx" => Some(Language {
            family: Family::Lexical,
            spec: "typescript",
        }),
        "json" => Some(Language {
            family: Family::Data,
            spec: "json",
        }),
        "jsonc" => Some(Language {
            family: Family::Data,
            spec: "jsonc",
        }),
        "jsonl" => Some(Language {
            family: Family::Data,
            spec: "json",
        }),
        "yaml" | "yml" => Some(Language {
            family: Family::Data,
            spec: "yaml",
        }),
        "css" => Some(Language {
            family: Family::Style,
            spec: "css",
        }),
        "scss" => Some(Language {
            family: Family::Style,
            spec: "css",
        }),
        "sass" => Some(Language {
            family: Family::Style,
            spec: "css",
        }),
        "less" => Some(Language {
            family: Family::Style,
            spec: "css",
        }),
        "postcss" => Some(Language {
            family: Family::Style,
            spec: "css",
        }),
        "shellscript" | "sh" | "bash" | "shell" | "zsh" | "fish" => Some(Language {
            family: Family::Lexical,
            spec: "shell",
        }),
        "python" | "py" => Some(Language {
            family: Family::Lexical,
            spec: "python",
        }),
        "sql" | "ddl" | "dml" => Some(Language {
            family: Family::Lexical,
            spec: "sql",
        }),
        "html" => Some(Language {
            family: Family::Markup,
            spec: "html",
        }),
        "xml" | "svg" => Some(Language {
            family: Family::Markup,
            spec: "xml",
        }),
        "markdown" | "md" => Some(Language {
            family: Family::Line,
            spec: "markdown",
        }),
        "diff" | "patch" => Some(Language {
            family: Family::Line,
            spec: "diff",
        }),
        "dockerfile" | "docker" => Some(Language {
            family: Family::Line,
            spec: "dockerfile",
        }),
        "ini" | "properties" => Some(Language {
            family: Family::Data,
            spec: "ini",
        }),
        "toml" => Some(Language {
            family: Family::Data,
            spec: "toml",
        }),
        "ruby" | "rb" => Some(Language {
            family: Family::Lexical,
            spec: "ruby",
        }),
        "go" | "golang" => Some(Language {
            family: Family::Lexical,
            spec: "go",
        }),
        "java" => Some(Language {
            family: Family::Lexical,
            spec: "java",
        }),
        "kotlin" | "kt" | "kts" => Some(Language {
            family: Family::Lexical,
            spec: "kotlin",
        }),
        "swift" => Some(Language {
            family: Family::Lexical,
            spec: "swift",
        }),
        "dart" => Some(Language {
            family: Family::Lexical,
            spec: "dart",
        }),
        "scala" | "sc" => Some(Language {
            family: Family::Lexical,
            spec: "scala",
        }),
        "groovy" | "gvy" | "gy" | "gsp" => Some(Language {
            family: Family::Lexical,
            spec: "groovy",
        }),
        "c" => Some(Language {
            family: Family::Lexical,
            spec: "c",
        }),
        "cpp" | "c++" | "cc" | "cxx" => Some(Language {
            family: Family::Lexical,
            spec: "cpp",
        }),
        "csharp" | "cs" | "c#" => Some(Language {
            family: Family::Lexical,
            spec: "csharp",
        }),
        "objective-c" | "objc" | "objectivec" | "m" | "mm" => Some(Language {
            family: Family::Lexical,
            spec: "objectivec",
        }),
        "rust" | "rs" => Some(Language {
            family: Family::Lexical,
            spec: "rust",
        }),
        "php" => Some(Language {
            family: Family::Lexical,
            spec: "php",
        }),
        "lua" => Some(Language {
            family: Family::Lexical,
            spec: "lua",
        }),
        "perl" | "pl" | "pm" => Some(Language {
            family: Family::Lexical,
            spec: "perl",
        }),
        "r" | "rscript" => Some(Language {
            family: Family::Lexical,
            spec: "r",
        }),
        "powershell" | "ps1" | "pwsh" => Some(Language {
            family: Family::Lexical,
            spec: "powershell",
        }),
        "elixir" | "ex" | "exs" => Some(Language {
            family: Family::Lexical,
            spec: "elixir",
        }),
        "erlang" | "erl" | "hrl" => Some(Language {
            family: Family::Lexical,
            spec: "erlang",
        }),
        "haskell" | "hs" => Some(Language {
            family: Family::Lexical,
            spec: "haskell",
        }),
        "clojure" | "clj" | "cljs" | "cljc" => Some(Language {
            family: Family::Lexical,
            spec: "clojure",
        }),
        "fsharp" | "fs" | "fsi" | "fsx" => Some(Language {
            family: Family::Lexical,
            spec: "fsharp",
        }),
        "vb" | "vbnet" => Some(Language {
            family: Family::Lexical,
            spec: "vb",
        }),
        "graphql" | "gql" => Some(Language {
            family: Family::Lexical,
            spec: "graphql",
        }),
        "protobuf" | "proto" => Some(Language {
            family: Family::Lexical,
            spec: "protobuf",
        }),
        "hcl" | "tf" | "terraform" => Some(Language {
            family: Family::Lexical,
            spec: "hcl",
        }),
        "nginx" | "nginxconf" => Some(Language {
            family: Family::Lexical,
            spec: "nginx",
        }),
        "makefile" | "mk" => Some(Language {
            family: Family::Lexical,
            spec: "makefile",
        }),
        "cmake" => Some(Language {
            family: Family::Lexical,
            spec: "cmake",
        }),
        "gradle" => Some(Language {
            family: Family::Lexical,
            spec: "groovy",
        }),
        "env" | "dotenv" => Some(Language {
            family: Family::Data,
            spec: "ini",
        }),
        "vue" => Some(Language {
            family: Family::Markup,
            spec: "html",
        }),
        "svelte" => Some(Language {
            family: Family::Markup,
            spec: "html",
        }),
        _ => None,
    }
}

pub fn lexical(name: &str) -> Option<&'static LexicalSpec> {
    match name {
        "javascript" => Some(&SPECS[0]),
        "typescript" => Some(&SPECS[1]),
        "shell" => Some(&SPECS[2]),
        "python" => Some(&SPECS[3]),
        "sql" => Some(&SPECS[4]),
        "ruby" => Some(&SPECS[5]),
        "go" => Some(&SPECS[6]),
        "java" => Some(&SPECS[7]),
        "kotlin" => Some(&SPECS[8]),
        "swift" => Some(&SPECS[9]),
        "dart" => Some(&SPECS[10]),
        "scala" => Some(&SPECS[11]),
        "groovy" => Some(&SPECS[12]),
        "c" => Some(&SPECS[13]),
        "cpp" => Some(&SPECS[14]),
        "csharp" => Some(&SPECS[15]),
        "objectivec" => Some(&SPECS[16]),
        "rust" => Some(&SPECS[17]),
        "php" => Some(&SPECS[18]),
        "lua" => Some(&SPECS[19]),
        "perl" => Some(&SPECS[20]),
        "r" => Some(&SPECS[21]),
        "powershell" => Some(&SPECS[22]),
        "elixir" => Some(&SPECS[23]),
        "erlang" => Some(&SPECS[24]),
        "haskell" => Some(&SPECS[25]),
        "clojure" => Some(&SPECS[26]),
        "fsharp" => Some(&SPECS[27]),
        "vb" => Some(&SPECS[28]),
        "graphql" => Some(&SPECS[29]),
        "protobuf" => Some(&SPECS[30]),
        "hcl" => Some(&SPECS[31]),
        "nginx" => Some(&SPECS[32]),
        "makefile" => Some(&SPECS[33]),
        "cmake" => Some(&SPECS[34]),
        _ => None,
    }
}

const SPECS: &[LexicalSpec] = &[
    // javascript
    LexicalSpec {
        keywords: &[
            "as",
            "async",
            "await",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "finally",
            "for",
            "from",
            "function",
            "get",
            "if",
            "import",
            "in",
            "instanceof",
            "let",
            "new",
            "of",
            "return",
            "set",
            "static",
            "super",
            "switch",
            "throw",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "yield",
        ],
        constants: &["true", "false", "null", "undefined", "NaN", "Infinity"],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        template_quotes: true,
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // typescript
    LexicalSpec {
        keywords: &[
            "as",
            "async",
            "await",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "finally",
            "for",
            "from",
            "function",
            "get",
            "if",
            "import",
            "in",
            "instanceof",
            "let",
            "new",
            "of",
            "return",
            "set",
            "static",
            "super",
            "switch",
            "throw",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "yield",
            "abstract",
            "declare",
            "enum",
            "implements",
            "interface",
            "keyof",
            "namespace",
            "private",
            "protected",
            "public",
            "readonly",
            "satisfies",
            "type",
        ],
        types: &[
            "any", "bigint", "boolean", "never", "number", "object", "string", "symbol", "unknown",
            "void",
        ],
        constants: &["true", "false", "null", "undefined", "NaN", "Infinity"],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        template_quotes: true,
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // shell
    LexicalSpec {
        keywords: &[
            "case", "do", "done", "elif", "else", "esac", "fi", "for", "function", "if", "in",
            "select", "then", "until", "while",
        ],
        commands: &[
            "awk", "cat", "cd", "chmod", "cp", "echo", "env", "export", "find", "grep", "mkdir",
            "mv", "printf", "pwd", "rm", "sed", "test",
        ],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        variable_prefix: true,
        flags: true,
        ..LexicalSpec::EMPTY
    },
    // python
    LexicalSpec {
        keywords: &[
            "and", "as", "assert", "async", "await", "break", "case", "class", "continue", "def",
            "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
            "in", "is", "lambda", "match", "nonlocal", "not", "or", "pass", "raise", "return",
            "try", "while", "with", "yield",
        ],
        types: &[
            "Any", "Callable", "Iterable", "None", "Protocol", "Self", "TypeVar", "bool", "bytes",
            "dict", "float", "int", "list", "object", "set", "str", "tuple",
        ],
        booleans: &["True", "False"],
        nulls: &["None", "NotImplemented", "Ellipsis"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        triple_string_quotes: true,
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // sql
    LexicalSpec {
        keywords: &[
            "add",
            "alter",
            "and",
            "as",
            "by",
            "case",
            "create",
            "delete",
            "desc",
            "distinct",
            "drop",
            "else",
            "end",
            "exists",
            "from",
            "group",
            "having",
            "in",
            "insert",
            "into",
            "is",
            "join",
            "left",
            "limit",
            "not",
            "null",
            "on",
            "or",
            "order",
            "outer",
            "primary",
            "references",
            "right",
            "select",
            "set",
            "table",
            "then",
            "union",
            "update",
            "values",
            "when",
            "where",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["--"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        case_insensitive: true,
        ..LexicalSpec::EMPTY
    },
    // ruby
    LexicalSpec {
        keywords: &[
            "alias", "and", "begin", "break", "case", "class", "def", "defined?", "do", "else",
            "elsif", "end", "ensure", "false", "for", "if", "in", "module", "next", "nil", "not",
            "or", "redo", "rescue", "retry", "return", "self", "super", "then", "true", "undef",
            "unless", "until", "when", "while", "yield",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // go
    LexicalSpec {
        keywords: &[
            "break",
            "case",
            "chan",
            "const",
            "continue",
            "default",
            "defer",
            "else",
            "fallthrough",
            "for",
            "func",
            "go",
            "goto",
            "if",
            "import",
            "interface",
            "map",
            "package",
            "range",
            "return",
            "select",
            "struct",
            "switch",
            "type",
            "var",
        ],
        types: &[
            "any",
            "bool",
            "byte",
            "complex128",
            "complex64",
            "error",
            "float32",
            "float64",
            "int",
            "int16",
            "int32",
            "int64",
            "int8",
            "rune",
            "string",
            "uint",
            "uint16",
            "uint32",
            "uint64",
            "uint8",
            "uintptr",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'", "`"],
        ..LexicalSpec::EMPTY
    },
    // java
    LexicalSpec {
        keywords: &[
            "abstract",
            "assert",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "default",
            "do",
            "else",
            "enum",
            "extends",
            "final",
            "finally",
            "for",
            "if",
            "implements",
            "import",
            "instanceof",
            "interface",
            "native",
            "new",
            "package",
            "private",
            "protected",
            "public",
            "return",
            "static",
            "strictfp",
            "super",
            "switch",
            "synchronized",
            "this",
            "throw",
            "throws",
            "transient",
            "try",
            "volatile",
            "while",
        ],
        types: &[
            "Boolean",
            "Byte",
            "Character",
            "Double",
            "Float",
            "Integer",
            "Long",
            "Object",
            "Optional",
            "Short",
            "String",
            "Void",
            "boolean",
            "byte",
            "char",
            "double",
            "float",
            "int",
            "long",
            "short",
            "void",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // kotlin
    LexicalSpec {
        keywords: &[
            "as",
            "break",
            "by",
            "catch",
            "class",
            "companion",
            "constructor",
            "continue",
            "data",
            "do",
            "else",
            "enum",
            "expect",
            "finally",
            "for",
            "fun",
            "if",
            "import",
            "in",
            "interface",
            "internal",
            "is",
            "object",
            "out",
            "override",
            "package",
            "private",
            "protected",
            "public",
            "return",
            "sealed",
            "suspend",
            "throw",
            "try",
            "typealias",
            "val",
            "var",
            "when",
            "where",
            "while",
        ],
        types: &[
            "Any", "Boolean", "Byte", "Char", "Double", "Float", "Int", "List", "Long", "Map",
            "Nothing", "Set", "Short", "String", "Unit",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        template_quotes: true,
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // swift
    LexicalSpec {
        keywords: &[
            "actor",
            "as",
            "associatedtype",
            "async",
            "await",
            "break",
            "case",
            "catch",
            "class",
            "continue",
            "defer",
            "deinit",
            "do",
            "else",
            "enum",
            "extension",
            "fallthrough",
            "for",
            "func",
            "guard",
            "if",
            "import",
            "in",
            "init",
            "inout",
            "let",
            "nil",
            "operator",
            "private",
            "protocol",
            "public",
            "repeat",
            "return",
            "self",
            "Self",
            "static",
            "struct",
            "subscript",
            "super",
            "switch",
            "throw",
            "throws",
            "try",
            "typealias",
            "var",
            "where",
            "while",
        ],
        types: &[
            "Any",
            "Array",
            "Bool",
            "Character",
            "Dictionary",
            "Double",
            "Float",
            "Int",
            "Optional",
            "Result",
            "Set",
            "String",
            "UInt",
            "Void",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // dart
    LexicalSpec {
        keywords: &[
            "abstract",
            "as",
            "assert",
            "async",
            "await",
            "base",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "covariant",
            "default",
            "deferred",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "extension",
            "external",
            "factory",
            "false",
            "final",
            "finally",
            "for",
            "function",
            "get",
            "hide",
            "if",
            "implements",
            "import",
            "in",
            "interface",
            "is",
            "late",
            "library",
            "mixin",
            "new",
            "null",
            "on",
            "operator",
            "part",
            "required",
            "return",
            "sealed",
            "set",
            "show",
            "static",
            "super",
            "switch",
            "sync",
            "this",
            "throw",
            "true",
            "try",
            "typedef",
            "var",
            "void",
            "when",
            "while",
            "with",
            "yield",
        ],
        types: &[
            "BigInt", "bool", "DateTime", "double", "Duration", "dynamic", "Future", "int",
            "Iterable", "List", "Map", "Never", "num", "Object", "Pattern", "Record", "Set",
            "Stream", "String", "Symbol", "Uri", "void",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // scala
    LexicalSpec {
        keywords: &[
            "abstract",
            "case",
            "catch",
            "class",
            "def",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "false",
            "final",
            "finally",
            "for",
            "forSome",
            "given",
            "if",
            "implicit",
            "import",
            "lazy",
            "macro",
            "match",
            "new",
            "null",
            "object",
            "override",
            "package",
            "private",
            "protected",
            "return",
            "sealed",
            "super",
            "then",
            "this",
            "throw",
            "trait",
            "true",
            "try",
            "type",
            "val",
            "var",
            "while",
            "with",
            "yield",
        ],
        types: &[
            "Any", "Boolean", "Byte", "Char", "Double", "Either", "Float", "Int", "List", "Long",
            "Map", "None", "Option", "Seq", "Set", "Short", "Some", "String", "Unit",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // groovy
    LexicalSpec {
        keywords: &[
            "abstract",
            "as",
            "assert",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "def",
            "default",
            "do",
            "else",
            "enum",
            "extends",
            "false",
            "final",
            "finally",
            "for",
            "goto",
            "if",
            "implements",
            "import",
            "in",
            "instanceof",
            "interface",
            "new",
            "null",
            "package",
            "private",
            "protected",
            "public",
            "return",
            "static",
            "super",
            "switch",
            "this",
            "throw",
            "throws",
            "trait",
            "true",
            "try",
            "var",
            "void",
            "while",
        ],
        types: &[
            "BigDecimal",
            "Boolean",
            "Closure",
            "Date",
            "Integer",
            "List",
            "Map",
            "Object",
            "String",
            "boolean",
            "def",
            "int",
            "long",
            "void",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // c
    LexicalSpec {
        keywords: &[
            "auto", "break", "case", "const", "continue", "default", "do", "else", "enum",
            "extern", "for", "goto", "if", "inline", "register", "restrict", "return", "sizeof",
            "static", "struct", "switch", "typedef", "union", "volatile", "while",
        ],
        types: &[
            "bool", "char", "double", "float", "int", "int16_t", "int32_t", "int64_t", "int8_t",
            "long", "short", "size_t", "uint16_t", "uint32_t", "uint64_t", "uint8_t", "void",
        ],
        booleans: &["true", "false"],
        nulls: &["nullptr", "NULL"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // cpp
    LexicalSpec {
        keywords: &[
            "auto",
            "break",
            "case",
            "const",
            "continue",
            "default",
            "do",
            "else",
            "enum",
            "extern",
            "for",
            "goto",
            "if",
            "inline",
            "register",
            "restrict",
            "return",
            "sizeof",
            "static",
            "struct",
            "switch",
            "typedef",
            "union",
            "volatile",
            "while",
            "alignas",
            "alignof",
            "and",
            "bitand",
            "bitor",
            "catch",
            "class",
            "concept",
            "constexpr",
            "consteval",
            "constinit",
            "decltype",
            "delete",
            "explicit",
            "export",
            "friend",
            "mutable",
            "namespace",
            "new",
            "noexcept",
            "not",
            "operator",
            "or",
            "private",
            "protected",
            "public",
            "requires",
            "template",
            "this",
            "throw",
            "try",
            "typename",
            "using",
            "virtual",
            "xor",
        ],
        types: &[
            "bool", "char", "double", "float", "int", "int16_t", "int32_t", "int64_t", "int8_t",
            "long", "short", "size_t", "uint16_t", "uint32_t", "uint64_t", "uint8_t", "void",
            "auto", "char16_t", "char32_t", "std", "string", "wstring",
        ],
        booleans: &["true", "false"],
        nulls: &["nullptr", "NULL"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // csharp
    LexicalSpec {
        keywords: &[
            "abstract",
            "as",
            "base",
            "break",
            "case",
            "catch",
            "checked",
            "class",
            "const",
            "continue",
            "default",
            "delegate",
            "do",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "finally",
            "fixed",
            "for",
            "foreach",
            "if",
            "implicit",
            "in",
            "interface",
            "internal",
            "is",
            "lock",
            "namespace",
            "new",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "record",
            "ref",
            "return",
            "sealed",
            "sizeof",
            "stackalloc",
            "static",
            "struct",
            "switch",
            "this",
            "throw",
            "try",
            "typeof",
            "unchecked",
            "unsafe",
            "using",
            "virtual",
            "void",
            "volatile",
            "while",
        ],
        types: &[
            "bool", "byte", "char", "decimal", "double", "dynamic", "float", "int", "long", "nint",
            "nuint", "object", "sbyte", "short", "string", "uint", "ulong", "ushort", "var",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // objectivec
    LexicalSpec {
        keywords: &[
            "auto",
            "break",
            "case",
            "const",
            "continue",
            "default",
            "do",
            "else",
            "enum",
            "extern",
            "for",
            "goto",
            "if",
            "inline",
            "register",
            "restrict",
            "return",
            "sizeof",
            "static",
            "struct",
            "switch",
            "typedef",
            "union",
            "volatile",
            "while",
            "@autoreleasepool",
            "@catch",
            "@class",
            "@dynamic",
            "@end",
            "@finally",
            "@implementation",
            "@import",
            "@interface",
            "@optional",
            "@package",
            "@private",
            "@property",
            "@protected",
            "@protocol",
            "@public",
            "@selector",
            "@synthesize",
            "@throw",
            "@try",
            "YES",
            "NO",
            "nil",
            "self",
            "super",
        ],
        types: &[
            "bool",
            "char",
            "double",
            "float",
            "int",
            "int16_t",
            "int32_t",
            "int64_t",
            "int8_t",
            "long",
            "short",
            "size_t",
            "uint16_t",
            "uint32_t",
            "uint64_t",
            "uint8_t",
            "void",
            "BOOL",
            "Class",
            "CGFloat",
            "NSInteger",
            "NSObject",
            "NSString",
            "NSUInteger",
            "SEL",
            "id",
        ],
        booleans: &["YES", "NO", "true", "false"],
        nulls: &["nil", "NULL", "nullptr"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // rust
    LexicalSpec {
        keywords: &[
            "as", "async", "await", "box", "break", "const", "continue", "crate", "dyn", "else",
            "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match",
            "mod", "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
            "super", "trait", "true", "type", "unsafe", "use", "where", "while",
        ],
        types: &[
            "Box", "Option", "Result", "Some", "String", "Vec", "bool", "char", "f32", "f64",
            "i128", "i16", "i32", "i64", "i8", "isize", "str", "u128", "u16", "u32", "u64", "u8",
            "usize",
        ],
        booleans: &["true", "false"],
        nulls: &["None"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        rust_attributes: true,
        ..LexicalSpec::EMPTY
    },
    // php
    LexicalSpec {
        keywords: &[
            "abstract",
            "and",
            "array",
            "as",
            "break",
            "callable",
            "case",
            "catch",
            "class",
            "clone",
            "const",
            "continue",
            "declare",
            "default",
            "do",
            "echo",
            "else",
            "elseif",
            "empty",
            "enddeclare",
            "endfor",
            "endforeach",
            "endif",
            "endswitch",
            "endwhile",
            "enum",
            "extends",
            "final",
            "finally",
            "fn",
            "for",
            "foreach",
            "function",
            "global",
            "if",
            "implements",
            "include",
            "instanceof",
            "interface",
            "isset",
            "match",
            "namespace",
            "new",
            "or",
            "private",
            "protected",
            "public",
            "readonly",
            "require",
            "return",
            "static",
            "switch",
            "throw",
            "trait",
            "try",
            "use",
            "var",
            "while",
            "xor",
            "yield",
        ],
        types: &[
            "array", "bool", "callable", "false", "float", "int", "iterable", "mixed", "never",
            "null", "object", "self", "static", "string", "true", "void",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//", "#"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        variable_prefix: true,
        ..LexicalSpec::EMPTY
    },
    // lua
    LexicalSpec {
        keywords: &[
            "and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto",
            "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until",
            "while",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &["--"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // perl
    LexicalSpec {
        keywords: &[
            "continue", "do", "else", "elsif", "for", "foreach", "given", "if", "last", "local",
            "my", "next", "our", "package", "redo", "require", "return", "state", "sub", "unless",
            "until", "use", "when", "while",
        ],
        booleans: &["true", "false"],
        nulls: &["undef"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        variable_prefix: true,
        ..LexicalSpec::EMPTY
    },
    // r
    LexicalSpec {
        keywords: &[
            "break", "else", "FALSE", "for", "function", "if", "Inf", "in", "NA", "NaN", "next",
            "NULL", "repeat", "return", "TRUE", "while",
        ],
        booleans: &["TRUE", "FALSE", "T", "F"],
        nulls: &["NULL", "NA", "NaN"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // powershell
    LexicalSpec {
        keywords: &[
            "begin",
            "break",
            "catch",
            "class",
            "continue",
            "data",
            "default",
            "do",
            "dynamicparam",
            "else",
            "elseif",
            "end",
            "enum",
            "exit",
            "filter",
            "finally",
            "for",
            "foreach",
            "from",
            "function",
            "if",
            "in",
            "param",
            "process",
            "return",
            "switch",
            "throw",
            "trap",
            "try",
            "until",
            "using",
            "var",
            "while",
        ],
        booleans: &["$true", "$false", "true", "false"],
        nulls: &["$null", "null"],
        commands: &[
            "Get-ChildItem",
            "Get-Content",
            "Invoke-Run",
            "Join-Path",
            "New-Item",
            "Remove-Item",
            "Set-Content",
            "Test-Path",
            "Write-Host",
            "Write-Output",
        ],
        line_comments: &["#"],
        block_comments: &[("<#", "#>")],
        string_quotes: &["\"", "'"],
        variable_prefix: true,
        flags: true,
        ..LexicalSpec::EMPTY
    },
    // elixir
    LexicalSpec {
        keywords: &[
            "after",
            "alias",
            "and",
            "case",
            "catch",
            "cond",
            "def",
            "defdelegate",
            "defexception",
            "defimpl",
            "defmacro",
            "defmodule",
            "defp",
            "defprotocol",
            "defstruct",
            "do",
            "else",
            "end",
            "false",
            "fn",
            "for",
            "if",
            "import",
            "in",
            "nil",
            "not",
            "or",
            "quote",
            "raise",
            "receive",
            "require",
            "rescue",
            "super",
            "throw",
            "true",
            "try",
            "unless",
            "unquote",
            "use",
            "when",
            "with",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // erlang
    LexicalSpec {
        keywords: &[
            "after", "and", "andalso", "band", "begin", "bnot", "bor", "bsl", "bsr", "bxor",
            "case", "catch", "cond", "div", "end", "fun", "if", "let", "not", "of", "or", "orelse",
            "receive", "rem", "try", "when", "xor",
        ],
        booleans: &["true", "false"],
        line_comments: &["%"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // haskell
    LexicalSpec {
        keywords: &[
            "as",
            "case",
            "class",
            "data",
            "default",
            "deriving",
            "do",
            "else",
            "family",
            "forall",
            "foreign",
            "hiding",
            "if",
            "import",
            "in",
            "infix",
            "infixl",
            "infixr",
            "instance",
            "let",
            "module",
            "newtype",
            "of",
            "qualified",
            "then",
            "type",
            "where",
        ],
        types: &[
            "Bool", "Char", "Double", "Either", "False", "Float", "IO", "Int", "Integer", "Maybe",
            "Nothing", "String", "True",
        ],
        booleans: &["True", "False"],
        nulls: &["Nothing"],
        line_comments: &["--"],
        block_comments: &[("{-", "-}")],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // clojure
    LexicalSpec {
        keywords: &[
            "def",
            "defmacro",
            "defmethod",
            "defmulti",
            "defn",
            "defonce",
            "do",
            "doseq",
            "false",
            "fn",
            "for",
            "if",
            "let",
            "loop",
            "nil",
            "ns",
            "quote",
            "recur",
            "require",
            "true",
            "try",
            "when",
        ],
        booleans: &["true", "false"],
        nulls: &["nil"],
        line_comments: &[";"],
        string_quotes: &["\""],
        ..LexicalSpec::EMPTY
    },
    // fsharp
    LexicalSpec {
        keywords: &[
            "abstract",
            "and",
            "as",
            "assert",
            "base",
            "begin",
            "class",
            "default",
            "delegate",
            "do",
            "done",
            "downcast",
            "downto",
            "elif",
            "else",
            "end",
            "exception",
            "extern",
            "false",
            "finally",
            "for",
            "fun",
            "function",
            "global",
            "if",
            "in",
            "inherit",
            "inline",
            "interface",
            "internal",
            "lazy",
            "let",
            "match",
            "member",
            "module",
            "mutable",
            "namespace",
            "new",
            "null",
            "of",
            "open",
            "or",
            "override",
            "private",
            "public",
            "rec",
            "return",
            "static",
            "struct",
            "then",
            "to",
            "true",
            "try",
            "type",
            "upcast",
            "use",
            "val",
            "void",
            "when",
            "while",
            "with",
            "yield",
        ],
        types: &[
            "Async", "bool", "decimal", "float", "int", "list", "Map", "option", "Result", "seq",
            "string", "unit",
        ],
        booleans: &["true", "false"],
        nulls: &["null", "None"],
        line_comments: &["//"],
        block_comments: &[("(*", "*)")],
        string_quotes: &["\"", "'"],
        decorators: true,
        ..LexicalSpec::EMPTY
    },
    // vb
    LexicalSpec {
        keywords: &[
            "AddHandler",
            "And",
            "As",
            "Boolean",
            "ByRef",
            "Byte",
            "ByVal",
            "Call",
            "Case",
            "Catch",
            "Class",
            "Const",
            "Continue",
            "Date",
            "Decimal",
            "Dim",
            "Do",
            "Double",
            "Each",
            "Else",
            "ElseIf",
            "End",
            "Enum",
            "Erase",
            "Error",
            "Event",
            "Exit",
            "False",
            "Finally",
            "For",
            "Friend",
            "Function",
            "Get",
            "Global",
            "GoTo",
            "Handles",
            "If",
            "Implements",
            "Imports",
            "In",
            "Inherits",
            "Integer",
            "Interface",
            "Is",
            "Let",
            "Lib",
            "Like",
            "Long",
            "Loop",
            "Me",
            "Mod",
            "Module",
            "MustInherit",
            "MustOverride",
            "MyBase",
            "Namespace",
            "New",
            "Next",
            "Not",
            "Nothing",
            "Object",
            "Of",
            "On",
            "Option",
            "Or",
            "Overloads",
            "Overrides",
            "ParamArray",
            "Partial",
            "Private",
            "Property",
            "Protected",
            "Public",
            "RaiseEvent",
            "ReadOnly",
            "ReDim",
            "REM",
            "RemoveHandler",
            "Resume",
            "Return",
            "Select",
            "Set",
            "Shadows",
            "Shared",
            "Short",
            "Single",
            "Static",
            "Step",
            "Stop",
            "String",
            "Structure",
            "Sub",
            "SyncLock",
            "Then",
            "Throw",
            "To",
            "True",
            "Try",
            "Using",
            "Variant",
            "Wend",
            "When",
            "While",
            "With",
            "WithEvents",
            "WriteOnly",
        ],
        types: &[
            "Boolean", "Byte", "Date", "Decimal", "Double", "Integer", "Long", "Object", "Short",
            "Single", "String",
        ],
        booleans: &["True", "False"],
        nulls: &["Nothing", "Null"],
        line_comments: &["'"],
        string_quotes: &["\""],
        case_insensitive: true,
        ..LexicalSpec::EMPTY
    },
    // graphql
    LexicalSpec {
        keywords: &[
            "directive",
            "enum",
            "extend",
            "false",
            "fragment",
            "implements",
            "input",
            "interface",
            "mutation",
            "null",
            "on",
            "query",
            "repeatable",
            "scalar",
            "schema",
            "subscription",
            "true",
            "type",
            "union",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["#"],
        string_quotes: &["\""],
        ..LexicalSpec::EMPTY
    },
    // protobuf
    LexicalSpec {
        keywords: &[
            "bool", "bytes", "double", "enum", "false", "fixed32", "fixed64", "float", "import",
            "int32", "int64", "map", "message", "oneof", "optional", "package", "proto2", "proto3",
            "public", "repeated", "reserved", "returns", "rpc", "service", "sfixed32", "sfixed64",
            "sint32", "sint64", "stream", "string", "syntax", "to", "true", "uint32", "uint64",
        ],
        types: &["Any", "Duration", "Timestamp"],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // hcl
    LexicalSpec {
        keywords: &[
            "and",
            "bool",
            "data",
            "dynamic",
            "false",
            "for",
            "if",
            "in",
            "locals",
            "module",
            "null",
            "number",
            "or",
            "output",
            "provider",
            "resource",
            "string",
            "terraform",
            "true",
            "variable",
        ],
        booleans: &["true", "false"],
        nulls: &["null"],
        line_comments: &["#", "//"],
        block_comments: &[("/*", "*/")],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // nginx
    LexicalSpec {
        keywords: &[
            "access_log",
            "add_header",
            "deny",
            "error_log",
            "events",
            "fastcgi_pass",
            "gzip",
            "http",
            "include",
            "index",
            "listen",
            "location",
            "log_format",
            "proxy_pass",
            "return",
            "rewrite",
            "root",
            "server",
            "server_name",
            "try_files",
            "upstream",
        ],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        ..LexicalSpec::EMPTY
    },
    // makefile
    LexicalSpec {
        keywords: &[
            "define", "else", "endef", "endif", "export", "ifneq", "ifeq", "ifdef", "ifndef",
            "include", "override", "private", "sinclude", "undefine", "unexport", "vpath",
        ],
        commands: &[
            "awk", "cat", "cd", "chmod", "cp", "echo", "env", "export", "find", "grep", "mkdir",
            "mv", "printf", "pwd", "rm", "sed", "test",
        ],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        variable_prefix: true,
        flags: true,
        ..LexicalSpec::EMPTY
    },
    // cmake
    LexicalSpec {
        keywords: &[
            "add_compile_definitions",
            "add_custom_command",
            "add_custom_target",
            "add_executable",
            "add_library",
            "cmake_minimum_required",
            "else",
            "elseif",
            "endforeach",
            "endif",
            "endfunction",
            "endmacro",
            "find_package",
            "foreach",
            "function",
            "if",
            "include",
            "macro",
            "message",
            "option",
            "project",
            "return",
            "set",
            "target_compile_features",
            "target_include_directories",
            "target_link_libraries",
        ],
        booleans: &["ON", "OFF", "TRUE", "FALSE"],
        nulls: &["NOTFOUND"],
        line_comments: &["#"],
        string_quotes: &["\"", "'"],
        case_insensitive: true,
        ..LexicalSpec::EMPTY
    },
];
