export const environment = { V: 'inherited space', EMPTY: '', KEEP: 'keep', FLAG: 'old', INSERT: 'a " b \\ c ${V}; `literal`' };
export const cases = [
  ['plain', ['-S', 'rec alpha beta']],
  ['whitespace', ['-S', 'rec\talpha\nbeta\rgamma\vdelta\fform']],
  ['quotes-empty', ['-S', `rec '' "" a' b'" c"`]],
  ['quote-literals', ['-S', `rec "'one'" '"two"'`]],
  ['escape-controls', ['-S', String.raw`rec a\nb a\tb a\rb a\vb a\fb`]],
  ['escape-punctuation', ['-S', String.raw`rec \# \$ \' \" \\`]],
  ['single-quote-escapes', ['-S', String.raw`rec '\n\_\c\$' '\'\\'`]],
  ['underscore', ['-S', String.raw`rec a\_b "a\_b" \_c`]],
  ['comment', ['-S', 'rec alpha # ignored', 'tail']],
  ['comment-active', ['-S', `rec ''#keep a#keep "#keep"`]],
  ['cancel-string', ['-S', String.raw`rec alpha\c ignored`, 'tail']],
  ['cancel-double-error', ['-S', String.raw`rec "a\cb"`]],
  ['escape-space-error', ['-S', String.raw`rec a\ b`]],
  ['escape-unknown-error', ['-S', String.raw`rec \q`]],
  ['escape-final-error', ['-S', 'rec trailing\\']],
  ['quote-final-error', ['-S', 'rec "unterminated']],
  ['expand-boundary', ['-S', 'rec pre${V}post ${INSERT}']],
  ['expand-empty-unset', ['-S', 'rec ${EMPTY} ${ABSENT} "${ABSENT}"']],
  ['expand-single-literal', ['-S', "rec '${V}' '\\${V}'"]],
  ['expand-before-i', ['-i', '-S', 'PATH=${PATH} KEEP=${V} rec ${V}']],
  ['expand-before-u', ['-u', 'V', '-S', 'rec ${V}']],
  ['expand-assignment-timing', ['-S', 'V=new rec ${V}']],
  ['dollar-bare-error', ['-S', 'rec $V tail']],
  ['dollar-name-error', ['-S', 'rec ${9BAD}']],
  ['dollar-default-error', ['-S', 'rec ${V:-fallback}']],
  ['dollar-substitution-error', ['-S', 'rec $(touch marker)']],
  ['literal-injection', ['-S', "rec ';touch marker' '$(touch marker)' `touch marker` > marker"]],
  ['attached-S', ['-Srec one', 'two']],
  ['combined-iS', ['-iSPATH=${PATH} KEEP=new rec one']],
  ['long-equals', ['--split-string=rec one', 'two']],
  ['long-separate', ['--split-string', 'rec one']],
  ['nested-S', ['-S', '-S "rec nested"', 'tail']],
  ['repeated-S-before-command', ['-S', '-u V', '-S', 'rec ${V}']],
  ['S-after-command-is-literal', ['-S', 'rec one', '-S', 'two three']],
  ['after-assignment-is-literal-command', ['A=new', '-S', 'rec one']],
  ['empty-S', ['-S', '', 'rec', 'tail']],
  ['empty-quoted-command', ['-S', "''"]],
  ['empty-print-environment', ['-i', '-S', '']],
  ['null-print', ['-i', '-S', '-0 A=1 B=2']],
  ['double-dash', ['-S', '-- rec -S literal']],
  ['bare-dash', ['-S', '- PATH=${PATH} rec']],
  ['bare-dash-stops-options', ['-S', '- -u V rec']],
  ['unset-long', ['-S', '--unset=V rec ${V}']],
  ['unicode', ['-S', 'rec é🙂 "λ x"']],
  ['no-S-single-target', ['rec alpha']],
];

export const protocols = [
  ['plain-e', '-S bash -e'],
  ['long-e', '--split-string=bash -e'],
  ['quote-argument', '-S bash -e "literal name"'],
  ['environment', '-S -i PATH=${PATH} KEEP=${V} bash -e'],
  ['relocated-file', '-S -C sub bash -e'],
  ['literal-no-S', 'bash -e'],
  ['long-space-not-equals', '--split-string bash -e'],
  ['explicit-c-capability-boundary', '-S bash -c "printf explicit"'],
];
