import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { cases, oldCap } from './cases.mjs';

const owned = dirname(fileURLToPath(import.meta.url));
const root = resolve(owned, '../../../..');
const commit = '21220b465537bf45ffcfb36740956a69f43bf75e';
const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');
if (process.argv[2] !== '--capture') throw new Error('Explicit --capture required; writes new freeze only.');
const destination = resolve(owned, 'freeze');
assert(!existsSync(destination), 'freeze is immutable; never overwrite');
assert.equal(spawnSync('git', ['rev-parse', '--show-toplevel'], { cwd: root, encoding: 'utf8' }).stdout.trim(), root);
mkdirSync(destination);
const archive = spawnSync('git', ['archive', '--format=tar.gz', commit, 'src', 'tests/commands/expr', 'package.json', 'package-lock.json', 'tsconfig.json', 'tsconfig.build.json'], { cwd: root, maxBuffer: 32 * 1024 * 1024 });
assert.equal(archive.status, 0, archive.stderr.toString());
writeFileSync(resolve(destination, 'accepted-source.tar.gz'), archive.stdout, { flag: 'wx' });
const inputs = `${JSON.stringify({ cases, oldCap }, null, 2)}\n`;
writeFileSync(resolve(destination, 'cases.json'), inputs, { flag: 'wx' });
const files = ['cases.mjs', 'freeze.mjs', 'capture.mjs', 'driver.mjs'];
const filesSha256 = Object.fromEntries(files.map(filename => [filename, sha256(readFileSync(resolve(owned, filename)))]));
const native = resolve(root, 'tests/commands/metadata-stress/.oracle/coreutils-9.7/src/expr');
const nativeSha256 = sha256(readFileSync(native));
assert.equal(nativeSha256, 'e8a4e2b58a33d2ad6bfa9eb8a4ed5f62775ab9ceac4b9421680c98973fd9109c');
writeFileSync(resolve(destination, 'receipt.json'), `${JSON.stringify({ frozenAt: new Date().toISOString(), commit, productSourceChangesAuthorized: false, sourceArchiveSha256: sha256(archive.stdout), casesSha256: sha256(inputs), filesSha256, native: { path: native, sha256: nativeSha256, expectedVersion: 'expr (GNU coreutils) 9.7', expectedPlatform: 'darwin', environment: { LC_ALL: 'C', LANG: 'C', PATH: '/usr/bin:/bin' } }, semanticCases: cases.filter(value => value.native !== false).length, productControls: cases.filter(value => value.native === false).length, oldCapSeparate: 1, sourceClassification: 'compressed immutable Git source/tests; never canonical TS discovery', controlsClassification: 'explicit version-specific opt-in .mjs drivers; no canonical test writes' }, null, 2)}\n`, { flag: 'wx' });
console.log(JSON.stringify({ destination, cases: cases.length, archiveSha256: sha256(archive.stdout) }));
