import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const here=import.meta.dirname,base=path.dirname(here),repo='/Users/kjopek/Workspace/safe-bash',sha=body=>crypto.createHash('sha256').update(body).digest('hex');
function read(filename,row){const stat=fs.lstatSync(filename);assert.ok(stat.isFile()&&!stat.isSymbolicLink());assert.equal(stat.size,row.bytes);assert.ok(stat.size<=4194304);const body=fs.readFileSync(filename);assert.equal(sha(body),row.sha256);return body;}
const tuple=JSON.parse(fs.readFileSync(path.join(here,'LOCATOR-IDENTITIES.json'))).tuples;for(const row of tuple)read(path.join(repo,row.path),row);
const fixture=JSON.parse(read(path.join(here,'workflowFixtureV4Preseal.json'),tuple[1]));JSON.parse(read(path.join(here,'stageAProducerPreseal.json'),tuple[0]));const retained=JSON.parse(fs.readFileSync(path.join(base,'stage-b/RETAINED-SOURCES.json')));
let patch='*** Begin Patch\n';for(const name of ['resources.mjs','loader.mjs']){const row=retained.find(item=>item.path.endsWith('/'+name));assert.ok(row);const body=Buffer.from(row.text??row.body);assert.equal(sha(body),row.sha256);assert.equal(body.at(-1),10);patch+='*** Add File: '+path.join(here,name)+'\n'+body.toString().slice(0,-1).split('\n').map(line=>'+'+line).join('\n')+'\n';}patch+='*** End Patch\n';fs.writeFileSync(path.join(here,'helpers.patch'),patch,{flag:'wx'});
const producerBindings=JSON.parse(fs.readFileSync(path.join(base,'stage-a-r2/BINDINGS.json')));assert.equal(sha(fs.readFileSync(path.join(base,'stage-a-r2/BINDINGS.json'))),'1b9f9f6a01f192cbd8a9f8b94716522ca7aff7ee2c7f679994f72e98256f0b7c');
const records=producerBindings.records;for(const name of ['PACKAGE-MEMBERS.json','EMITTED.json','TOOLS-BEFORE.json'])read(path.join(base,'stage-a-r2/evidence',name),records.find(row=>row.path===name));
const rows=[];for(const [target,source]of [['workflows.mjs','v4/workflows.mjs'],['fixture.json','v2/NEUTRAL-FIXTURE.json']]){const filename=path.join(base,source),row=fixture.fixtureFiles.find(item=>path.join(repo,item.path)===filename);assert.ok(row);read(filename,row);rows.push({source:path.relative(repo,filename),target,bytes:row.bytes,sha256:row.sha256});}
fs.writeFileSync(path.join(here,'PREP-DATA.json'),JSON.stringify({tuples:tuple,producerRecords:records,stageFiles:rows,sourceTree:'3adc676a0ab638c9788ef007e465931d65d2c6fe',ids:['C01','C02','C03','C04','C05','C06','C07','C08','C09','C12','C13','C14','C17'],retainedUnrun:true},null,2)+'\n',{flag:'wx'});console.log('Exact tuples and staging source DATA authenticated; helper patch emitted, zero product imports.');
