import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname,resolve,relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { authenticatePreparation } from '../public-candidate-execution-v1/common.mjs';
const here=dirname(fileURLToPath(import.meta.url)),prior=resolve(here,'../public-candidate-execution-v1'),repository=resolve(here,'../../../..'),sha=bytes=>createHash('sha256').update(bytes).digest('hex'),read=filename=>JSON.parse(fs.readFileSync(filename)),write=(name,value)=>fs.writeFileSync(resolve(here,name),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n',{flag:'wx'});
authenticatePreparation('74ee8bb5c667f7b143cdbf637627f67d83eaacaa5f7cea802ed5f2e072747826');
assert.equal(sha(fs.readFileSync(resolve(prior,'EVIDENCE-MANIFEST.json'))),'c9b9b61005eed611f959844f6e6fd1004a74f0a1936ec77cb5e8327041d3bdbc');
const oldManifest=read(resolve(prior,'MANIFEST.json')),oldEvidence=read(resolve(prior,'EVIDENCE-MANIFEST.json')),request=read(resolve(prior,'CANDIDATE.json')),priorResult=read(resolve(prior,'runs/actual-01/RESULT.json'));
const selected=['R01','R12','R21','R23','R24','R25','R28','R29'];
for(const profile of ['source','installed','moved']){const rows=priorResult.runtime.filter(row=>row.profile===profile);assert.equal(rows.length,30);assert.equal(rows.filter(row=>row.status==='PASS').length,22);assert.deepEqual(rows.filter(row=>row.status==='FAIL').map(row=>row.id),selected);}
assert.equal(priorResult.types.length,20);assert.ok(priorResult.types.every(row=>row.status==='PASS'));assert.equal(priorResult.negatives.length,7);assert.ok(priorResult.negatives.every(row=>row.status==='PASS'));assert.deepEqual(priorResult.mutants.filter(row=>row.status==='KILLED').map(row=>row.id),['M01','M02','M03','M04','M05','M06','M08']);
const protectedFiles=[];for(const name of ['MANIFEST.json','EVIDENCE-MANIFEST.json','CANDIDATE.json',...oldManifest.files.map(row=>row.path),...oldEvidence.files.map(row=>row.path)]){const filename=resolve(prior,name),bytes=fs.readFileSync(filename);protectedFiles.push({path:relative(repository,filename),bytes:bytes.length,sha256:sha(bytes)});}
for(const row of oldEvidence.files)assert.equal(sha(fs.readFileSync(resolve(prior,row.path))),row.sha256);
const continuation={schema:'timeout-public-readiness-stdin-continuation/1',candidate:request.candidate,packSha256:request.pack.sha256,priorRecipeCommit:'330ffcb9529e9cb62b6f075f90a4b66d19739209',priorEvidenceCommit:'2324e36d7f19c05a362d21460927c69098bbe17d',priorResultPath:relative(repository,resolve(prior,'runs/actual-01/RESULT.json')),priorResultSha256:sha(fs.readFileSync(resolve(prior,'runs/actual-01/RESULT.json'))),selected,protectedFiles,productMutant:request.mutants.find(row=>row.id==='M07'),boundaryControls:[{id:'B01',failure:'RAW_STDIN_ACQUIRE',role:'injected raw iterator acquisition'},{id:'B02',failure:'SHELL_STDIN_NEXT',role:'actual upstream next/content read'},{id:'B03',failure:'STDIN_RETURN_NOT_ENTERED',role:'upstream return omitted'},{id:'B04',failure:'SHELL_STDIN_RETURN_SETTLEMENT',role:'upstream return gate bypassed'}],focusedControls:18,expectedNodeChildren:32,setupExecutions:'Logged separately, never counted among the24 family attempts; no counter reset.',types:'Bound20; not rerun',native:0,safeJS:0};
write('CONTINUATION.json',continuation);
const names=['common.mjs','admission.mjs','preload.mjs','supervisor.mjs','archive.mjs','legacy-adapter.mjs','runtime.mjs','execute.mjs'],overlays=[];
for(const name of names){const original=fs.readFileSync(resolve(prior,name),'utf8');let text=original;const patches=[];
  const replace=(before,after,count=1)=>{assert.equal(text.split(before).length-1,count,`${name}:unique-overlay`);text=text.split(before).join(after);patches.push({before,after,count});};
  if(name==='common.mjs')replace("  const supplemental = read(resolve(recipe, 'AUTHOR-BINDINGS.json'));","  const supplemental = read(resolve(recipe, '../public-candidate-execution-v1/AUTHOR-BINDINGS.json'));\n  binding.protectedFiles.push(...read(resolve(recipe,'CONTINUATION.json')).protectedFiles);");
  if(name==='legacy-adapter.mjs'){
    replace("import assert from 'node:assert/strict';","import assert from 'node:assert/strict';\nimport { assertAdmission } from './boundaries.mjs';");
    replace("const encodeReason = value => ({ type: typeof value, text: String(value), name: value?.name, code: value?.code });","const encodeReason = value => ({ type: typeof value, text: String(value), name: value?.name, code: value?.code, message:value?.message, stack:value?.stack });");
    replace("const waitFor = (promise, outcome, label) => Promise.race([promise, outcome.settled.then(value => assert.fail(`${label}: handler settled before required admission (${value.status})`))]);","const waitFor = (promise, outcome, label) => {let admitted=false;return Promise.race([promise.then(value=>{admitted=true;return value;}),outcome.settled.then(value=>{if(!admitted)preserveDiagnostic('required-admission-settled',{label,outcome:diagnosticOutcome(value)});assert.fail(`${label}: handler settled before required admission (${value.status})`);})]);};");
    replace('function integrity() {',fs.readFileSync(resolve(here,'admission-probe.data'),'utf8')+'function integrity() {');
    replace("function returned(run, status) { assert.equal", "function returned(run, status) { preserveDiagnostic('handler-return-before-assertion',{expectedStatus:status,outcome:diagnosticOutcome(run.outcome)});assert.equal");
    replace("function rejected(run, reason) { assert.equal", "function rejected(run, reason) { preserveDiagnostic('handler-rejection-before-assertion',{outcome:diagnosticOutcome(run.outcome,reason)});assert.equal");
    replace("const instance = shell({}, timing), actual = instance.commands.get('timeout');","const instance = await admitPublicPlugin(shell({}, timing)), actual = instance.commands.get('timeout');");
    replace("const instance = shell({}, timing); const actual = instance.commands.get('timeout');","const instance = await admitPublicPlugin(shell({}, timing)); const actual = instance.commands.get('timeout');");
    replace("  rejected({ outcome: handler }, thrown); assert.equal(outcome.status, 'rejected');","  preserveDiagnostic('PC02-shell-before-assertion',{handler:diagnosticOutcome(handler,thrown),outer:diagnosticOutcome(outcome,thrown),retirementEntered,sameSentinel:Object.is(thrown,observed),childClosed,resources:timing.live});\n  rejected({ outcome: handler }, thrown); assert.equal(outcome.status, 'rejected');");
    replace('export { config, receipt,','export { admitPublicPlugin, admissionRecords, config, receipt,');
  }
  if(name==='runtime.mjs'){
    replace("import assert from 'node:assert/strict';","import assert from 'node:assert/strict';\nimport { rawInputProbe, shellInputProbe, assertRawInput, assertShellInput, assertPendingReturn } from './boundaries.mjs';");
    replace('import { config, receipt,','import { admitPublicPlugin, admissionRecords, diagnosticOutcome, config, receipt,');
    replace('function exact(run, record) { returned',"function exact(run, record) { preserveDiagnostic('exact-raw-before-assertion',{outcome:diagnosticOutcome(run.outcome),stdoutBase64:run.stdout().toString('base64'),stderrBase64:run.stderr().toString('base64')});returned");
    replace('function shellExact(result, record) { assert.equal',"function shellExact(result, record) { preserveDiagnostic('exact-shell-before-assertion',{exitCode:result?.exitCode,stdout:result?.stdout,stderr:result?.stderr,stdoutBase64:result?.stdoutBytes===undefined?null:Buffer.from(result.stdoutBytes).toString('base64'),stderrBase64:result?.stderrBytes===undefined?null:Buffer.from(result.stderrBytes).toString('base64')});assert.equal");
    replace("    assertInventory(makeShell().commands.list().map(row => row.name));","    assertInventory((await admitPublicPlugin(makeShell())).commands.list().map(row => row.name));");
    replace('handler=observeHandler(instance)','handler=observeHandler(await admitPublicPlugin(instance))',2);
    const start=text.indexOf('  async R12() {'),end=text.indexOf('  async R13() {');assert.ok(start>0&&end>start);replace(text.slice(start,end),fs.readFileSync(resolve(here,'r12.data'),'utf8'));
    replace('assert.ok(Object.hasOwn(cases,config.caseId));',`assert.ok(Object.hasOwn(cases,config.caseId));assert.ok(${JSON.stringify(selected)}.includes(config.caseId),'NARROW_CONTINUATION_ONLY');`);
    replace("await cases[config.caseId]();await tick();result.status='PASS';","await cases[config.caseId]();preserveDiagnostic('continuation-family-tail',{id:config.caseId,completed:true});await tick();result.status='PASS';");
    replace("  result.integrity='UNCHANGED';", "  result.pluginAdmissions=admissionRecords;preserveDiagnostic('plugin-admissions-final',{records:admissionRecords});result.integrity='UNCHANGED';");
  }
  if(name==='execute.mjs'){
    replace("import { qualifyType } from './type-trace.mjs';\n",'');replace("import { consumers, compilerOptions } from '../public-integration-freeze-v1/types.mjs';\n",'');replace("import { freshControls, packageNegatives } from './negative-protocol.mjs';\n",'');
    replace("const boundAuthor=read(resolve(recipe,'AUTHOR-BINDINGS.json'));", "const boundAuthor=read(resolve(recipe,'../public-candidate-execution-v1/AUTHOR-BINDINGS.json'));");
    replace("const guarded=new Map();",`const continuation=read(resolve(recipe,'CONTINUATION.json'));assert.deepEqual(continuation.selected,${JSON.stringify(selected)});assert.equal(continuation.candidate,request.candidate);const selectedCases=runtimeCases.filter(row=>continuation.selected.includes(row.id));assert.equal(selectedCases.length,8);const priorResult=read(resolve(repository,continuation.priorResultPath));assert.equal(fileHash(resolve(repository,continuation.priorResultPath)),continuation.priorResultSha256);\nconst guarded=new Map();`);
    replace("mutants:[],admission:[]", "mutants:[],boundaryControls:[],admission:[]");
    replace('async function runtime(profile,productRoot,consumer,caseId,mutation){','async function runtime(profile,productRoot,consumer,caseId,mutation,boundaryControl){');
    replace("profile==='source'||mutation", "profile==='source'||mutation||boundaryControl",2);
    replace("...(mutation?{intentionalMutation:mutation}:{})", "...(mutation?{intentionalMutation:mutation}:{}),...(boundaryControl?{boundaryControl}:{})");
    replace("if(mutation.id==='M06')", "if(mutation.id==='M07'){const observation=captured.observations.find(row=>row.kind==='PC01-boundaries');assert.ok(observation);assert.deepEqual(observation.dispatch,{timeout:1,child:1,outer:0});assert.equal(observation.sameCallerSentinel,true);assert.equal(observation.sameHandlerSignalReason,true);assert.equal(observation.beforeRelease.handler.status,'pending');assert.equal(observation.beforeRelease.outer.status,'pending');assert.equal(observation.handler.status,'fulfilled');assert.equal(observation.handler.exitCode,124);assert.equal(observation.outer.status,'rejected');assert.equal(observation.outer.sameSentinel,true);assert.equal(observation.childClosed,true);assert.equal(observation.resources,0);}if(mutation.id==='M06')");
    replace("  else{assert.equal(result.code,captured.status==='PASS'?0:1);state.runtime.push(captured);}", "  else if(boundaryControl){const record={id:boundaryControl.id,status:'KILLED',caseId,result:captured};try{assert.equal(result.code,1);assert.equal(captured.status,'FAIL');assert.ok(captured.failure.text.includes(boundaryControl.failure),'WRONG_BOUNDARY_MUTANT_FAILURE');const observation=captured.observations.find(row=>row.kind===(boundaryControl.id==='B01'?'R12-raw-before-assertion':boundaryControl.id==='B03'?'R12-return-admission-failure':'R12-shell-before-release'));assert.ok(observation,'ACTUAL_BOUNDARY_OBSERVATION');if(boundaryControl.id==='B01'){assert.equal(observation.counts.acquire,1);assert.equal(observation.counts.next,0);}if(boundaryControl.id==='B02'){assert.equal(observation.counts.next,1);assert.equal(observation.counts.contentBytes,1);}if(boundaryControl.id==='B03'){assert.equal(observation.counts.acquire,1);assert.equal(observation.counts.returned,0);}if(boundaryControl.id==='B04'){assert.equal(observation.counts.returned,1);assert.equal(observation.counts.settled,1);}}catch(error){record.status='FAIL';record.failure=reason(error);}state.boundaryControls.push(record);}\n  else{assert.equal(result.code,captured.status==='PASS'?0:1);state.runtime.push(captured);}");
    const start=text.indexOf('async function types(');assert.ok(start>0);replace(text.slice(start),fs.readFileSync(resolve(here,'execution-tail.data'),'utf8'));
  }
  write(name,text);overlays.push({name,originalSha256:sha(original),resultSha256:sha(text),byteIdentical:original===text,patches});
}
write('OVERLAY.json',{schema:'timeout-public-continuation-overlay/1',postCandidateInspection:true,priorRecipeSha256:'74ee8bb5c667f7b143cdbf637627f67d83eaacaa5f7cea802ed5f2e072747826',overlays});
const files=[...names,'boundaries.mjs','admission-probe.data','r12.data','execution-tail.data','controls.mjs','README.md','seal.mjs','CONTINUATION.json','OVERLAY.json'].map(path=>{const bytes=fs.readFileSync(resolve(here,path));return {path,bytes:bytes.length,sha256:sha(bytes)};});
write('MANIFEST.json',{schema:'timeout-public-continuation-recipe/1',sealedAt:new Date().toISOString(),candidate:request.candidate,files,references:oldManifest.references,selected,runtimeLayouts:3,publicTypeExecutions:0,productMutants:1,boundaryMutants:4,focusedControls:18});
const preparationSha256=sha(fs.readFileSync(resolve(here,'MANIFEST.json')));write('CANDIDATE.json',{...request,preparationSha256,runName:'continuation-01'});
console.log(JSON.stringify({preparationSha256,requestSha256:sha(fs.readFileSync(resolve(here,'CANDIDATE.json'))),selected,children:32}));
