import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { census, sha256 } from "./integrity-v1.mjs";
const root = dirname(fileURLToPath(import.meta.url));
const raw = resolve(root, "raw-v1"), work = resolve(root, "work-v1");
const files = readdirSync(raw).sort().map(path => { const bytes = readFileSync(resolve(raw, path)); const text = bytes.toString(); assert.deepEqual(Buffer.from(text), bytes); return { path, sha256: sha256(bytes), text }; });
assert.equal(files.length, 27);
const data = { version: 1, at: new Date().toISOString(), role: "complete27 new raw records/configs plus exact scratch inventory; no tool/product tree bytes", files, scratch: { "raw-v1": census(raw), "work-v1": census(work) } };
const encoded = gzipSync(JSON.stringify(data), { level: 9 }).toString("base64").match(/.{1,120}/g).join("\n") + "\n";
const summary = JSON.parse(readFileSync(resolve(raw, "RESULTS.json")));
const result = { version: 1, at: data.at, subcontrols: 2, layouts: 3, executions: 6, pass: summary.results.filter(row => row.kind === "pass").length, assertionFailures: summary.results.filter(row => row.kind === "assertion-failure").length, runtimeBlocked: 0, actualProductModules: summary.results.map(row => ({ id: row.id, layout: row.layout, modules: row.productModules })), sourceInputs: 265, packageMembers: 846, packageSha256: "15aa8d8dd6e78a9b7d12156ea2adaf93bd5f0037f13443e8928268c9d5215a18", rawRecords: 27, originalC06: "partial; root-versus-mapped-status contrast completed; genuine escaping-control/local selection remains source-only", oldCohortsReexecuted: 0, newBuilds: 0, newTypeCompiles: 0, native: 0, service: 0, guest: 0, provenanceRole: "actual root abort rejects; live outer ordinary false rethrow maps1+diagnostic; identity alone not proof", cleanupRole: "registered cooperative lookup and outer cleanup drained; natural direct children only, no independent descendant census", directoryModeRole: "full file and directory modes plus append-aware membership guarded before/after each new product execution" };
const manifest = { version: 1, path: "EVIDENCE-v1.json.gz.base64", bytes: Buffer.byteLength(encoded), sha256: sha256(encoded), rawRecords: files.length, scratch: ["raw-v1", "work-v1"] };
const additions = { "EVIDENCE-v1.json.gz.base64": encoded, "EVIDENCE-MANIFEST-v1.json": JSON.stringify(manifest, null, 2) + "\n", "RESULTS-v1.json": JSON.stringify(result, null, 2) + "\n" };
execFileSync("apply_patch", [], { maxBuffer: 32 * 1024 * 1024, input: "*** Begin Patch\n" + Object.entries(additions).map(([path, text]) => "*** Add File: " + resolve(root, path) + "\n" + text.trimEnd().split("\n").map(line => "+" + line).join("\n") + "\n").join("") + "*** End Patch\n" });
process.stdout.write(JSON.stringify({ manifest, pass: result.pass, failures: result.assertionFailures }) + "\n");
