import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { sha, regular, put, census, verify, copy, members, inventory } from './common.mjs';
import { controller } from '../../shell/indexed-arrays-independent-20260828/s06-successor-v1/preparation-v4/controller.mjs';
import { deadline } from '../../shell/indexed-arrays-independent-20260828/s06-successor-v1/preparation-v4/deadline.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../..'),clock=deadline(35*60*1000);
let budget,report;const immutable=[];
try{
  const[expected,label]=process.argv.slice(2);assert.equal(label,'COHERENT78-ARRAYS-20260828-01');const sealBytes=regular(path.join(here,'SEAL.json'));assert.equal(sha(sealBytes),expected);const seal=JSON.parse(sealBytes),auth=JSON.parse(regular(path.join(here,'AUTHENTICATION.json')));
  const integrity=()=>{clock.check('integrity');for(const row of seal.roles){const bytes=regular(path.join(repo,row.path));assert.equal(sha(bytes),row.sha256);assert.equal(bytes.length,row.bytes);assert.equal(fs.lstatSync(path.join(repo,row.path)).mode&0o777,row.mode);}for(const tree of immutable)verify(tree);};
  integrity();assert.equal(process.execPath,auth.node.origin);assert.equal(process.version,auth.node.version);assert.equal(sha(regular(auth.node.origin)),auth.node.sha256);verify({root:auth.sourceRoot,entries:auth.sourceCensus});for(const tool of Object.values(auth.tools))verify({root:tool.root,entries:tool.entries});
  const work=path.join(here,`RUN-${label}`);assert.ok(!fs.existsSync(work));fs.mkdirSync(work);report={candidate:auth.derived,base:auth.base,array:auth.array,packageSha256:auth.packageSha256,seal:expected,work,phases:[],complete:false,unsafeStop:false};
  budget=controller(work,seal.policy,{node:{path:auth.node.origin},git:{path:'/Library/Developer/CommandLineTools/usr/bin/git'}},integrity,clock);
  for(const directory of ['records','source','tools','apps','artifacts','home','tmp','cache']){fs.mkdirSync(path.join(work,directory));budget.registerStorage(directory,path.join(work,directory),directory==='records'?128*1024*1024:512*1024*1024);}
  const source=path.join(work,'source'),tools=path.join(work,'tools'),apps=path.join(work,'apps'),artifacts=path.join(work,'artifacts');
  for(const row of auth.selectedSource)put(path.join(source,row.path),regular(path.join(auth.sourceRoot,row.path)),parseInt(row.mode,8)&0o777);
  for(const[name,tool]of Object.entries(auth.tools))copy(tool.root,name==='npm'?path.join(tools,'npm'):path.join(source,'node_modules',name));
  immutable.push({root:tools,entries:census(tools)});
  const env={PATH:'',HOME:path.join(work,'home'),TMPDIR:path.join(work,'tmp'),LC_ALL:'C',TZ:'UTC',NO_COLOR:'1',npm_config_cache:path.join(work,'cache'),npm_config_offline:'true',npm_config_ignore_scripts:'true',npm_config_audit:'false',npm_config_fund:'false',npm_config_update_notifier:'false',npm_config_userconfig:path.join(work,'home/npmrc'),npm_config_globalconfig:path.join(work,'home/globalnpmrc')};put(env.npm_config_userconfig,'');put(env.npm_config_globalconfig,'');
  const node=auth.node.origin,compiler=path.join(source,'node_modules/typescript/bin/tsc'),npm=path.join(tools,'npm/bin/npm-cli.js');
  const tool=async(label,args,cwd)=>{const run=await budget.child('tool',node,['--permission',`--allow-fs-read=${work}`,`--allow-fs-read=${node}`,`--allow-fs-write=${work}`,...args],{cwd,env,timeoutMs:120000,maxBytes:4*1024*1024});report.phases.push({label,code:run.code});assert.equal(run.code,0,`${label}: ${run.stderr}`);return run;};
  await tool('one-source-build',[compiler,'-p','tsconfig.build.json'],source);
  const pack=await tool('one-offline-pack',[npm,'pack','--offline','--ignore-scripts','--json','--pack-destination',artifacts],source);const packRows=JSON.parse(pack.stdout);assert.equal(packRows.length,1);const tarPath=path.join(artifacts,packRows[0].filename),tar=regular(tarPath);assert.equal(sha(tar),auth.packageSha256);assert.deepEqual(inventory(tar),auth.packageEntries);report.freshPack={bytes:tar.length,sha256:sha(tar),members:Object.keys(auth.packageEntries).length};
  immutable.push({root:source,entries:census(source)});
  const packageEntries=auth.packageEntries,typeData=JSON.parse(regular(path.join(here,'TYPES.json'))),cases=JSON.parse(regular(path.join(here,'CASES.json')));
  function appFiles(app){
    for(const row of seal.appRoles)put(path.join(app,row.destination),regular(path.join(repo,row.path)));
    for(const group of typeData.groups)put(path.join(app,`type-${group.id}.mts`),typeData.prefix+group.body+'\n');
  }
  const sourceApp=path.join(apps,'source-build');fs.mkdirSync(sourceApp);put(path.join(sourceApp,'package.json'),'{"private":true,"type":"module"}\n');
  for(const[name,entry]of Object.entries(packageEntries)){const bytes=regular(path.join(source,name));assert.equal(sha(bytes),entry.sha256);put(path.join(sourceApp,'node_modules/virtual-bash',name),bytes,entry.mode);}appFiles(sourceApp);
  const installed=path.join(apps,'installed');fs.mkdirSync(installed);put(path.join(installed,'package.json'),'{"private":true,"type":"module"}\n');
  await tool('one-offline-install',[npm,'install',tarPath,'--offline','--ignore-scripts','--no-audit','--no-fund','--package-lock=false','--omit=dev'],installed);appFiles(installed);
  const outside=path.join(artifacts,'outside-canary.mjs');put(outside,'throw new Error("outside source executed");\n');
  let serial=0;
  const makeManifest=(app,variant)=>{const product=path.join(app,'node_modules/virtual-bash'),entries=census(app),files={};for(const[name,entry]of Object.entries(entries))if(!entry.directory)files[path.join(app,name)]=entry;const actual=Object.fromEntries(Object.entries(census(product)).filter(([,entry])=>!entry.directory));const expected={...packageEntries};if(variant)expected[variant.member]={...expected[variant.member],bytes:variant.bytes.length,sha256:sha(variant.bytes)};assert.deepEqual(actual,expected);return{node:{path:node,sha256:auth.node.sha256},candidate:auth.derived,product,files,trees:[{root:app,entries}],outside:pathToFileURL(outside).href,...(variant?{mutant:{id:variant.id,path:path.join(product,variant.member)}}:{})};};
  async function runtime(label,app,mode,ids,variant,negative){
    const manifest=makeManifest(app,variant);if(negative==='drift'){const target=path.join(manifest.product,'dist/shell/runtime.js');fs.appendFileSync(target,'\n');}if(negative==='missing')fs.unlinkSync(path.join(manifest.product,'dist/commands/timeout/index.js'));if(negative==='overlay')put(path.join(app,'unexpected.mjs'),'throw new Error("unexpected");\n');
    const stable=census(app),record=await budget.record(`manifest-${++serial}`,manifest);const result=await budget.child('product',node,['--permission',`--allow-fs-read=${app}`,`--allow-fs-read=${record.path}`,`--allow-fs-read=${node}`,path.join(app,'worker.mjs'),record.path,negative==='manifest'?'0'.repeat(64):record.sha256,mode,JSON.stringify(ids)],{cwd:app,env:{...env,PRODUCT_ROOT:manifest.product,RUN_ROOT:app,LAYOUT:label},timeoutMs:30000,maxBytes:2*1024*1024});assert.deepEqual(census(app),stable);
    let rows;try{rows=result.stdout.trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));}catch(reason){throw new Error(`incoherent JSON receipts ${label}: ${reason}`);}
    if(negative){assert.equal(result.code,78);assert.ok(rows.some(row=>typeof row.diagnostic==='string'&&row.diagnostic.includes(negative==='manifest'?'manifest binding mismatch':'tree census mismatch')));await budget.record(`body-${serial}`,{label,negative,refused:true,rows});report.phases.push({label,guard:true,accepted:true});return;}
    const summaries=rows.filter(row=>row.summary);assert.equal(summaries.length,1,'one mandatory summary');const summary=summaries[0].summary;const observations=rows.flatMap(row=>row.observation?[row.observation]:row.id?[row]:[]);const expectedCount=mode==='author-core'?19:mode==='author-array'?12:ids.length;assert.equal(summary.cases,expectedCount);assert.equal(observations.length,expectedCount);assert.equal(summary.disposed,summary.created??expectedCount);assert.ok(!rows.some(row=>row.diagnostic||row.unsafeCleanup));
    if(!mode.startsWith('author'))assert.deepEqual(observations.map(row=>row.id),ids);
    assert.equal(summary.pass,observations.filter(row=>row.pass===true).length,'summary must agree with actual observation rows');assert.equal(result.code,summary.pass===expectedCount?0:1,'all-PASS/nonzero cannot pass');assert.ok(rows.some(row=>row.load?.path===path.join(manifest.product,'dist/index.js')));
    let accepted=summary.pass===expectedCount;
    if(variant){const activation=rows.find(row=>row.activation)?.activation;assert.ok(activation&&activation.id===variant.id&&activation.hits>0,'actual mutation activation required');assert.ok(rows.some(row=>row.load?.path===activation.path&&row.load.sha256===activation.sha256));accepted=observations.find(row=>row.id===variant.fail)?.pass===false&&observations.find(row=>row.id===variant.pass)?.pass===true;}
    const receipt=await budget.record(`body-${serial}`,{label,mode,ids,summary,observations,loads:rows.filter(row=>row.load).map(row=>row.load),activation:rows.find(row=>row.activation)?.activation,accepted});report.phases.push({label,accepted,receipt});budget.ordinary(label,accepted);return{accepted,observations};
  }
  async function types(app,label){
    const product=path.join(app,'node_modules/virtual-bash'),tree={root:app,entries:census(app)};
    for(const group of typeData.groups){const file=path.join(app,`type-${group.id}.mts`);const result=await budget.child('type',node,['--permission',`--allow-fs-read=${app}`,`--allow-fs-read=${source}/node_modules`,`--allow-fs-read=${node}`,compiler,'--strict','--exactOptionalPropertyTypes','--noEmit','--skipLibCheck','false','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2022','--pretty','false','--listFiles','--typeRoots',path.join(source,'node_modules/@types'),file],{cwd:app,env,timeoutMs:30000,maxBytes:2*1024*1024});verify(tree);const text=result.stdout+result.stderr,errors=text.split(/\r?\n/u).filter(line=>/error TS\d+:/u.test(line));const diagnostics=errors.map(line=>line.match(/error (TS\d+):/u)[1]);let accepted=result.code===group.code&&JSON.stringify(diagnostics)===JSON.stringify(group.diagnostics)&&(!group.term||errors.every(line=>line.includes(group.term)));const declarations=text.split(/\r?\n/u).filter(line=>line.endsWith('.d.ts')&&line.includes('/dist/'));assert.ok(declarations.length>0,'actual public declaration binding required');for(const filename of declarations){const resolved=fs.realpathSync(filename);assert.ok(resolved.startsWith(product+'/dist/'),'type source fallback');const relative=path.relative(product,resolved);assert.equal(sha(regular(resolved)),packageEntries[relative]?.sha256);}await budget.record(`types-${label}-${group.id}`,{group:group.id,cases:group.cases,accepted,code:result.code,errors,declarations});report.phases.push({label:`${label}-types-${group.id}`,accepted,cases:group.cases});budget.ordinary(`${label}-types-${group.id}`,accepted);}
  }
  const positives=new Map();let moved;
  for(const label of ['source-build','installed','moved']){
    let app=label==='source-build'?sourceApp:installed;if(label==='moved'){moved=path.join(apps,'moved');const before=census(installed);fs.renameSync(installed,moved);assert.deepEqual(census(moved),before);assert.equal(fs.existsSync(installed),false);app=moved;}
    await runtime(label+'-author-core',app,'author-core',[]);await runtime(label+'-author-array',app,'author-array',[]);
    for(const[mode,ids]of [['literal',cases.literal.map(row=>row.id)],['dynamic',cases.dynamic]]){const outcome=await runtime(label+'-'+mode,app,mode,ids);if(label==='source-build')for(const row of outcome.observations)positives.set(row.id,row.pass);}
    await runtime(label+'-fallback',app,'guard',['G-fallback']);await types(app,label);
  }
  for(const negative of ['manifest','drift','missing','overlay']){const app=path.join(apps,'guard-'+negative);copy(moved,app);await runtime('guard-'+negative,app,'literal',['F01'],undefined,negative);}
  for(const specification of JSON.parse(regular(path.join(here,'MUTANTS.json')))){
    if(!positives.get(specification.fail)||!positives.get(specification.pass)){report.phases.push({label:specification.id,blocked:'failed positive prerequisite'});budget.ordinary(specification.id,false);continue;}
    const app=path.join(apps,specification.id);copy(moved,app);const filename=path.join(app,'node_modules/virtual-bash',specification.member),original=regular(filename),text=original.toString();assert.equal(text.split(specification.needle).length,2);const bytes=Buffer.from(text.replace(specification.needle,specification.replacement));fs.writeFileSync(filename,bytes);await runtime(specification.id,app,'literal',[specification.fail,specification.pass],{...specification,bytes});await runtime(specification.id+'-restored',moved,'literal',[specification.fail,specification.pass]);
  }
  report.complete=true;report.qualification='Fresh exact composition only. Independent24/layout plus unchanged author31/layout; R15 refusal separate. No old-array cohort replay or native/SafeJS/provider-service acceptance.';
}catch(reason){if(report){report.unsafeStop=true;report.error=String(reason?.stack??reason);}else{console.error(String(reason?.stack??reason));process.exitCode=78;}}
finally{if(report&&budget){try{const result=await budget.finalize(report,()=>({finalCensuses:['source','tools','apps','artifacts','home','tmp','cache'].map(name=>({root:path.join(report.work,name),entries:census(path.join(report.work,name))}))}),value=>new Promise((resolve,reject)=>process.stdout.write(JSON.stringify(value)+'\n',error=>error?reject(error):resolve())));clock.check('coordinator exit');process.exitCode=result.unsafeStop?78:result.accepted?0:1;}catch(reason){console.error(`unsafe finalization: ${reason}`);process.exitCode=78;}}}
