import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { chmodSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)), repository = resolve(here, '../../../..');
const revision = '6dc79cd58ba57dbbac9aff390af73d05368ccb56', candidate = '8670ebe8f0d39966c2de2638780437398e5f8490';
const prefix = 'tests/integration/full-gate-20260827', family = `${prefix}/runtime-profile-20260827`;
const output = resolve(process.argv[2] ?? ''); assert.ok(process.argv[2]); assert.equal(existsSync(output), false); mkdirSync(output, { recursive: true });
const temporary = realpathSync(mkdtempSync('/tmp/runtime-policy-independent-'));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const write = (path, bytes) => { mkdirSync(dirname(path), { recursive: true }); writeFileSync(path, bytes); };
const environment = { ...process.env, GIT_OPTIONAL_LOCKS: '0', GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_NOSYSTEM: '1', HOME: temporary, TSX_DISABLE_CACHE: '1' }; delete environment.NODE_OPTIONS; delete environment.NODE_TEST_CONTEXT;
const git = (args, cwd = repository, extra = {}) => execFileSync('git', ['--no-replace-objects', ...args], { cwd, env: environment, timeout: 60000, maxBuffer: 64 * 1024 * 1024, ...extra });
const blob = (path, commit = revision) => git(['show', `${commit}:${path}`]);
const report = { startedAt: new Date().toISOString(), revision, candidate, runnerSha256: hash(readFileSync(fileURLToPath(import.meta.url))), source: {}, tools: {}, checks: [], probes: {}, children: [], privateAccess: false, wholeGate: false, affectedBodiesReexecuted: false, separateBodyEvidence: '0579a239' };
const record = (name, action) => { try { const detail = action(); report.checks.push({ name, pass: true, detail }); } catch (error) { report.checks.push({ name, pass: false, message: error.message, stack: error.stack }); } console.log(JSON.stringify(report.checks.at(-1))); };
const staged = join(temporary, 'frozen-harness'); mkdirSync(staged);
const paths = ['runtime-profile-20260827/profile.mjs', 'runtime-profile-20260827/controls.mjs', 'combined-8670ebe8/run.mjs', 'combined-8670ebe8/committed-archive.mjs', 'combined-8670ebe8/prerequisites.mjs', 'combined-8670ebe8/import-guard.mjs', 'combined-8670ebe8/policy.json', 'combined-8670ebe8/CANDIDATE.json', 'combined-8670ebe8/cleanup-expected.json', 'preflight-repair/preflight.mjs', 'preflight-repair/policy.json', 'combined-b494675c/inspect.mjs', 'combined-b494675c/prerequisites.mjs', 'account.mjs', 'supervise.mjs', 'history.mjs'];
for (const path of paths) { const bytes = blob(`${prefix}/${path}`); write(join(staged, prefix, path), bytes); report.source[`${prefix}/${path}`] = hash(bytes); }
const oldBody = JSON.parse(blob(`${prefix}/loader-null-source-review-node24-bodies/attempt-1/RESULT.json`, '0579a239'));
const copyTools = destination => { for (const [path, pin] of Object.entries(oldBody.tools)) { const bytes = readFileSync(join(repository, 'node_modules', path)); assert.equal(hash(bytes), pin.sha256); write(join(destination, path), bytes); chmodSync(join(destination, path), pin.mode); assert.equal(lstatSync(join(destination, path)).nlink, 1); report.tools[path] = pin; } };
copyTools(join(staged, 'node_modules'));
const old = git(['rev-parse', '6699804a']).toString().trim(), objects = new Set([old]);
for (const path of ['', 'tests', 'tests/integration', prefix, `${prefix}/combined-8670ebe8`, `${prefix}/combined-8670ebe8/import-guard.mjs`]) objects.add(git(['rev-parse', path ? `${old}:${path}` : `${old}^{tree}`]).toString().trim());
const pack = git(['pack-objects', '--stdout'], repository, { input: [...objects].join('\n') + '\n' }); git(['init', '--quiet', '--template='], staged); git(['index-pack', '--stdin'], staged, { input: pack });
const profilePath = join(staged, family, 'profile.mjs');
const { gateProfile, inspectRuntime, probeGuardedRuntime } = await import(pathToFileURL(profilePath));
const legacy = '/Users/kjopek/.nvm/versions/node/v22.22.2/bin/node';
const child = (name, executable, args, options = {}) => { const result = spawnSync(executable, args, { cwd: staged, env: environment, encoding: 'utf8', timeout: 30000, maxBuffer: 8 * 1024 * 1024, ...options }); report.children.push({ name, executable, args, status: result.status, signal: result.signal, error: result.error?.message ?? null, stdout: result.stdout, stderr: result.stderr }); assert.equal(result.error, undefined); assert.equal(result.signal, null); return result; };
const root = join(temporary, 'owned'), source = join(root, 'source'); mkdirSync(source, { recursive: true });
const tar = join(temporary, 'candidate-source.tar'); git(['archive', '-o', tar, candidate, 'src', 'package.json', 'package-lock.json', 'tsconfig.json', 'tsconfig.build.json']); execFileSync('/usr/bin/tar', ['-xf', tar, '-C', source], { timeout: 60000 }); copyTools(join(source, 'node_modules'));
const originals = Object.fromEntries(['src/commands/execution.ts', 'src/commands/env-split.ts'].map(path => [path, readFileSync(join(source, path))]));
const expectedSource = Object.fromEntries(Object.entries(originals).map(([path, bytes]) => [path, hash(bytes)]));
const guardBytes = blob(`${prefix}/combined-8670ebe8/import-guard.mjs`);
const probe = (name, { executable = gateProfile.executable, guardContent = guardBytes, expected = expectedSource, env = {}, change = () => {} } = {}) => {
  const harness = join(root, `harness-${name}`); mkdirSync(harness); const guard = join(harness, 'import-guard.mjs'); write(guard, guardContent);
  const options = { executable, root, source, harness, guard, expectedSource: expected, environment: { PATH: `${dirname(legacy)}:/usr/bin:/bin`, LANG: 'C', LC_ALL: 'C', TZ: 'UTC', TSX_DISABLE_CACHE: '1', ...env } }; change(options);
  const result = probeGuardedRuntime(options); report.probes[name] = result; return result;
};
try {
  const authorOutput = join(output, 'UNCHANGED-AUTHOR.json');
  const authorRun = child('unchanged-author-controls', legacy, [join(staged, family, 'controls.mjs'), authorOutput], { timeout: 60000 });
  report.authorReplay = JSON.parse(readFileSync(authorOutput)); assert.equal(authorRun.status, 0); assert.equal(report.authorReplay.controls.length, 11); assert.equal(report.authorReplay.status, 'author-controls-pass-not-actual-body-acceptance');
  record('qualified actual Node24 identity', () => { const result = inspectRuntime(gateProfile.executable); assert.equal(result.supported, true); assert.equal(result.identity.sha256, gateProfile.sha256); assert.equal(result.identity.path, gateProfile.executable); report.runtime = result; });
  record('legacy Node22 identity refuses78', () => { const result = inspectRuntime(legacy); assert.equal(result.supported, false); assert.equal(result.refusalStatus, 78); report.legacyIdentity = result; });
  record('missing runtime refuses78', () => { const result = inspectRuntime(join(temporary, 'missing-node')); assert.equal(result.supported, false); assert.equal(result.refusalStatus, 78); assert.match(result.reason, /ENOENT/u); });
  record('nonexecutable known fixture refuses78', () => { const path = join(temporary, 'nonexec-node'); write(path, '#!/bin/sh\nexit 0\n'); chmodSync(path, 0o644); const result = inspectRuntime(path); assert.equal(result.supported, false); assert.equal(result.refusalStatus, 78); });
  record('changed executable bytes never qualify', () => {
    const path = join(temporary, 'changed-node'), marker = join(temporary, 'identity-probe-marker');
    write(path, `#!/bin/sh\nprintf invoked > '${marker}'\nprintf '%s\\n' '${JSON.stringify({ version: gateProfile.version, execPath: path, platform: gateProfile.platform, arch: gateProfile.arch })}'\n`); chmodSync(path, 0o755);
    const result = inspectRuntime(path); assert.equal(result.supported, false); assert.equal(result.refusalStatus, 78); assert.match(result.reason, /sha256/u);
    report.runtimeProbeTrustBoundary = { suppliedKnownFixtureExecutedForIdentityBeforeHashRefusal: existsSync(marker), noSuiteLaunched: true, qualification: 'inspectRuntime is a trusted host diagnostic, not safe execution of arbitrary untrusted executable paths; actual gate passes process.execPath' };
  });
  record('identical copied runtime fails selected-path policy', () => { const copy = join(temporary, 'copied-node'); write(copy, readFileSync(gateProfile.executable)); chmodSync(copy, 0o755); const result = inspectRuntime(copy); assert.equal(result.supported, false); assert.equal(result.identity.sha256, gateProfile.sha256); assert.match(result.reason, /explicitly selected installed runtime/u); });
  record('actual guarded8670 imports and direct/PATH children match Node24', () => { const result = probe('positive'); assert.equal(result.status, 0, result.reason); assert.deepEqual(result.childIdentities.self, result.childIdentities.direct); assert.deepEqual(result.childIdentities.self, result.childIdentities.byPath); assert.equal(result.childIdentities.self.execPath, gateProfile.executable); assert.equal(result.childIdentities.typescript, '5.9.3'); });
  record('legacy guarded feature refuses78 with original null-source failure', () => { const result = probe('legacy-feature', { executable: legacy }); assert.equal(result.status, 78); assert.equal(result.suiteLaunched, false); assert.match(result.probe.stderr, /ERR_INVALID_RETURN_PROPERTY_VALUE[\s\S]*got null/u); });
  record('actual legacy CLI refuses78 before output or native/archive work', () => { const target = `/tmp/full-gate-runtime-independent-${temporary.split('/').at(-1)}`; assert.equal(existsSync(target), false); const result = child('legacy-real-cli', legacy, [join(staged, prefix, 'combined-8670ebe8/run.mjs'), '--handoff', candidate, '--execute', target, '--committed-archive']); assert.equal(result.status, 78); assert.equal(existsSync(target), false); assert.equal(JSON.parse(result.stdout).runtime.supported, false); assert.doesNotMatch(result.stdout, /"preflight"/u); });
  record('correct launcher matches qualified receipt', () => { const result = child('matching-launcher', gateProfile.executable, ['--input-type=module', '-e', `const {inspectRuntime,requireMatchingLauncher,gateProfile}=await import(${JSON.stringify(pathToFileURL(profilePath).href)});requireMatchingLauncher(inspectRuntime(gateProfile.executable));console.log('launcher-bound');`]); assert.equal(result.status, 0); assert.match(result.stdout, /launcher-bound/u); });
  record('Node22 cannot use Node24 receipt to enter launcher', () => { const result = child('mismatched-launcher', legacy, ['--input-type=module', '-e', `const {inspectRuntime,requireMatchingLauncher,gateProfile}=await import(${JSON.stringify(pathToFileURL(profilePath).href)});requireMatchingLauncher(inspectRuntime(gateProfile.executable));console.log('MUST-NOT-ENTER');`]); assert.equal(result.status, 1); assert.match(result.stderr, /Gate launcher and selected child runtime must match/u); assert.doesNotMatch(result.stdout, /MUST-NOT-ENTER/u); });
  record('critical source tamper refuses78', () => { const path = 'src/commands/env-split.ts'; try { write(join(source, path), Buffer.concat([originals[path], Buffer.from('\nexport const altered = true;\n')])); const result = probe('tampered-source'); assert.equal(result.status, 78); assert.match(result.probe.stderr, /Frozen env source bytes/u); } finally { write(join(source, path), originals[path]); } });
  record('missing critical source refuses78', () => { const path = 'src/commands/env-split.ts'; try { rmSync(join(source, path)); const result = probe('missing-source'); assert.equal(result.status, 78); assert.match(result.probe.stderr, /ENOENT|ERR_MODULE_NOT_FOUND/u); } finally { write(join(source, path), originals[path]); } });
  record('disabled guard refuses before child', () => { const result = probe('disabled-guard', { guardContent: Buffer.from('export {};\n') }); assert.equal(result.status, 78); assert.equal(result.probe, undefined); assert.match(result.reason, /Authentication guard/u); });
  record('missing guard refuses before child', () => { const result = probe('missing-guard', { change: options => rmSync(options.guard) }); assert.equal(result.status, 78); assert.equal(result.probe, undefined); });
  record('guard symlink refuses even identical bytes', () => { const result = probe('guard-link', { change: options => { rmSync(options.guard); const outside = join(temporary, 'same-guard.mjs'); write(outside, guardBytes); symlinkSync(outside, options.guard); } }); assert.equal(result.status, 78); assert.equal(result.probe, undefined); });
  record('changed CJS tool refuses before child', () => { const path = join(source, 'node_modules/typescript/lib/typescript.js'), original = readFileSync(path); try { write(path, 'changed'); const result = probe('changed-typescript'); assert.equal(result.status, 78); assert.equal(result.probe, undefined); assert.match(result.reason, /Unqualified TypeScript/u); } finally { write(path, original); } });
  record('source-hash key inventory cannot omit critical parser', () => { const result = probe('missing-expected', { expected: { 'src/commands/execution.ts': expectedSource['src/commands/execution.ts'] } }); assert.equal(result.status, 78); assert.equal(result.probe, undefined); });
  record('caller NODE_OPTIONS cannot disable guard or inject preload', () => { const poison = join(temporary, 'poison.mjs'), marker = join(temporary, 'poison-marker'); write(poison, `import{writeFileSync}from'node:fs';writeFileSync(${JSON.stringify(marker)},'bad');throw new Error('POISON');\n`); const result = probe('poison-options', { env: { NODE_OPTIONS: '--import=' + pathToFileURL(poison).href } }); assert.equal(result.status, 0, result.reason); assert.equal(existsSync(marker), false); });
  record('PATH shadow node cannot replace selected child', () => { const directory = join(temporary, 'shadow-bin'), marker = join(temporary, 'shadow-marker'); write(join(directory, 'node'), `#!/bin/sh\nprintf bad > '${marker}'\nexit 42\n`); chmodSync(join(directory, 'node'), 0o755); const result = probe('shadow-path', { env: { PATH: `${directory}:${dirname(legacy)}:/usr/bin:/bin` } }); assert.equal(result.status, 0); assert.equal(result.childIdentities.byPath.execPath, gateProfile.executable); assert.equal(existsSync(marker), false); });
  record('authenticated importer still cannot import outside root', () => {
    const outside = join(temporary, 'outside.mjs'), path = 'src/commands/execution.ts'; write(outside, "throw new Error('OUTSIDE_BODY_RAN');\n"); const changed = Buffer.from(`import ${JSON.stringify(pathToFileURL(outside).href)};\n`);
    try { write(join(source, path), changed); const result = probe('outside', { expected: { ...expectedSource, [path]: hash(changed) } }); assert.equal(result.status, 78); assert.match(result.probe.stderr, /FROZEN_IMPORT_OUTSIDE/u); assert.doesNotMatch(result.probe.stderr, /Error: OUTSIDE_BODY_RAN/u); } finally { write(join(source, path), originals[path]); }
  });
  record('compiled source fallback still rejects', () => { const path = join(source, 'src/commands/execution.js'); write(path, 'export const compiled=true;\n'); try { const result = child('compiled-fallback', gateProfile.executable, ['--input-type=module', '-e', "await import('./src/commands/execution.js');"], { cwd: source, env: report.probes.positive.environment }); assert.equal(result.status, 1); assert.match(result.stderr, /Frozen env compiled-source fallback/u); } finally { rmSync(path); } });
  record('package engine policy and guard remain unchanged', () => { assert.equal(JSON.parse(blob('package.json', candidate)).engines.node, '>=22'); assert.deepEqual(blob('package.json'), blob('package.json', '6dc79cd5^')); assert.deepEqual(guardBytes, blob(`${prefix}/combined-8670ebe8/import-guard.mjs`, '6dc79cd5^')); });
  record('real phase npm selection uses selected process executable', () => { const text = blob(`${prefix}/combined-8670ebe8/run.mjs`).toString(); assert.ok(text.includes("const selectedExecutable = executable === 'npm' ? process.execPath : executable;")); assert.ok(text.includes("const selectedArgs = executable === 'npm' ? [npmPath, ...args] : args;")); assert.ok(text.indexOf('const runtimeReceipt = inspectRuntime();') < text.indexOf('mkdirSync(output)')); assert.ok(text.indexOf('report.runtimeProbe = probeGuardedRuntime') < text.indexOf("await phase(\"canonical-discovery\"")); assert.ok(text.includes('process.exitCode = error.exitCode === 78 ? 78 : 1')); });
  for (const path of paths) assert.equal(hash(readFileSync(join(staged, prefix, path))), report.source[`${prefix}/${path}`]);
  for (const [path, bytes] of Object.entries(originals)) assert.deepEqual(readFileSync(join(source, path)), bytes);
} catch (error) { report.error = { message: error.message, stack: error.stack }; process.exitCode = 1; }
finally { rmSync(temporary, { recursive: true, force: true }); report.cleaned = !existsSync(temporary); report.finishedAt = new Date().toISOString(); report.counts = { author: report.authorReplay?.controls.length ?? 0, independent: report.checks.length, pass: report.checks.filter(entry => entry.pass).length, fail: report.checks.filter(entry => !entry.pass).length }; write(join(output, 'RESULT.json'), JSON.stringify(report, null, 2) + '\n'); }
if (report.counts.fail || report.error) process.exitCode = 1;
console.log(JSON.stringify(report.counts));
