import { expect, it } from "vitest";
import { Volume } from "memfs";
import * as api from "./index.js";
import { Shell, MemoryFileSystem } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { w, textContext, textFixture } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";

for (const strict of [false, true]) for (const route of ["model", "sdk", "shell"] as const) for (const carrier of ["direct", "choice", "fallback", "process"] as const) for (const format of ["bullet", "decimal", "lowerLetter", "upperLetter", "lowerRoman", "upperRoman"] as const)
 it(`${route} sets all nine ${format} native levels with typed styles and lengths; carrier=${carrier}; strict=${strict}`, async () => {
  const wrap = (active: string) => carrier === "direct" ? active : carrier === "process" ? `<f:pass>${active}</f:pass><f:opaque f:scope="original"><w:lvl w:ilvl="8"><w:numFmt w:val="stored-inert"/></w:lvl></f:opaque>` : `<mc:AlternateContent><mc:Choice Requires="${carrier === "choice" ? "w" : "f"}">${carrier === "choice" ? active : '<f:opaque f:scope="original"/>'}</mc:Choice><mc:Fallback>${carrier === "fallback" ? active : '<f:opaque f:scope="original"/>'}</mc:Fallback></mc:AlternateContent>`;
  const numbering = `<w:numbering xmlns:w="${w}" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:list-level-variants" mc:Ignorable="f" mc:ProcessContent="f:pass">${wrap('<w:abstractNum w:abstractNumId="7"><w:nsid w:val="00000001"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1."/><w:rPr><w:i/></w:rPr></w:lvl></w:abstractNum>')}${wrap('<w:num w:numId="1"><w:abstractNumId w:val="7"/></w:num>')}<!--retained root--></w:numbering>`;
  const styles = `<w:styles xmlns:w="${w}"><w:style w:type="paragraph" w:styleId="ps"><w:name w:val="List paragraph"/></w:style><w:style w:type="numbering" w:styleId="ns"><w:name w:val="Numbering style"/></w:style></w:styles>`, body = '<w:p><w:pPr><w:keepNext/><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Selected 🌊</w:t></w:r></w:p><w:p><w:pPr><w:numPr><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>Unchanged</w:t></w:r></w:p>';
  const input = await textFixture(body, { numbering: { kind: "numbering", xml: numbering }, styles: { kind: "styles", xml: styles } }, strict), batch = { version: 1, operations: [{ operation: "paragraphs.get", arguments: { paragraph: 1 }, resultHandle: "owner" }, { operation: "lists.levels.set", receiver: { resultHandle: "owner" }, arguments: { levels: Array.from({ length: 9 }, (_, level) => ({ level, format, text: `${format} %${level + 1} 🌊`, start: level, restartAfter: level === 0 ? null : level - 1, paragraphStyle: "List paragraph", indent: { value: 1, unit: "pt" }, hanging: { value: 2, unit: "pt" } })), numberingStyle: "Numbering style" } }] }, memory = Volume.fromJSON({ "/out": "" }), sink = { async write(bytes: Uint8Array) { memory.appendFileSync("/out", bytes); } };
  if (route === "model") { const result = await api.applyStyleModelBatch(input, batch, textContext); await result.save(sink); }
  else if (route === "sdk") await api.executeDocumentBatch(input, batch, { output: "-" }, { ...textContext, encoding: { order: "input", compression: "store" }, stdout: sink });
  else { const fs = new MemoryFileSystem(); await fs.writeFile("/input", input); const shell = new Shell({ fs }).use(docxCommands({ engine: api.createDocxInspectionCommandEngine({ limits: textContext.limits }) })); try { const result = await shell.exec(`docx batch /input --ops-json '${JSON.stringify(batch)}' --output - > /out`); expect(result.exitCode, result.stdout + result.stderr).toBe(0); expect(await fs.readFile("/input")).toEqual(input); memory.writeFileSync("/out", await fs.readFile("/out")); } finally { await shell.dispose(); } }
  const output = new Uint8Array(memory.readFileSync("/out") as Buffer), before = readPackage(input), after = readPackage(output); assertPackageLinks(after); for (const [name, bytes] of before) if (!["word/document.xml", "word/numbering.xml"].includes(name)) expect(after.get(name), name).toEqual(bytes);
  const root = api.parseDocumentXml(after.get("word/numbering.xml")!).root, attr = (n: typeof root | undefined, name = "val") => n?.attributes.find(a => a.namespace === root.namespace && a.localName === name)?.value, child = (n: typeof root | undefined, name: string) => n?.children.find(c => c.namespace === root.namespace && c.localName === name);
  const main = api.parseDocumentXml(after.get("word/document.xml")!).root, numId = attr(child(child(child(main.children[0]!.children[0], "pPr"), "numPr"), "numId")), instance = root.children.find(n => n.localName === "num" && attr(n, "numId") === numId), abstractId = attr(child(instance, "abstractNumId")), definition = root.children.find(n => n.localName === "abstractNum" && attr(n, "abstractNumId") === abstractId);
  expect(attr(child(definition, "styleLink"))).toBe("ns"); expect(definition!.children.findIndex(n => n.localName === "styleLink")).toBeLessThan(definition!.children.findIndex(n => n.localName === "lvl")); expect(attr(child(definition, "nsid"))).toBe("00000001"); expect(definition!.children.filter(n => n.localName === "lvl")).toHaveLength(9);
  for (const level of Array.from({ length: 9 }, (_, i) => i)) { const n = definition!.children.find(n => n.localName === "lvl" && attr(n, "ilvl") === String(level)); expect(attr(child(n, "numFmt"))).toBe(format); expect(attr(child(n, "lvlText"))).toBe(`${format} %${level + 1} 🌊`); expect(attr(child(n, "start"))).toBe(String(level)); expect(attr(child(n, "lvlRestart"))).toBe(level === 0 ? undefined : String(level)); expect(attr(child(n, "pStyle"))).toBe("ps"); expect(attr(child(child(n, "pPr"), "ind"), strict ? "start" : "left")).toBe("20"); expect(attr(child(child(n, "pPr"), "ind"), "hanging")).toBe("40"); }
  expect((await api.Document(output, textContext)).paragraphs.map(p => p.text)).toEqual(["Selected 🌊", "Unchanged"]); expect(new TextDecoder().decode(after.get("word/numbering.xml")).split("<!--retained root-->")).toHaveLength(2);
 });
