import {DocumentBudget} from './budget.js';
import {MarkupCompatibility,documentCompatibilityProfile,type CompatibilityContent} from './compatibility.js';
import type {XmlElement} from './package-xml.js';
export interface ChartIssue {readonly code:string;readonly part:string;readonly path:readonly number[];readonly message:string}
export interface ChartPoint {readonly path:readonly number[];readonly index:string|null;readonly values:readonly (string|null)[];readonly issues:readonly ChartIssue[]}
export interface ChartCache {readonly kind:'string'|'numeric'|'multilevel-string';readonly path:readonly number[];readonly cached:boolean;readonly freshness:'unknown'|null;readonly counts:readonly (string|null)[];readonly formatCodes:readonly (string|null)[];readonly points:readonly ChartPoint[];readonly levels:readonly {readonly path:readonly number[];readonly points:readonly ChartPoint[]}[];readonly issues:readonly ChartIssue[]}
export interface ChartSource {readonly role:'label'|'category'|'value'|'x'|'y'|'bubble';readonly namespace:string;readonly localName:string;readonly path:readonly number[];readonly kind:'literal'|'reference'|'opaque';readonly literals:readonly (string|null)[];readonly formulas:readonly (string|null)[];readonly caches:readonly ChartCache[];readonly issues:readonly ChartIssue[]}
export interface ChartSeries {readonly group:number;readonly path:readonly number[];readonly indices:readonly (string|null)[];readonly orders:readonly (string|null)[];readonly name:string|null;readonly label:{readonly provenance:'literal'|'cached'|'missing'|'ambiguous'|'opaque'};readonly cachedValues:readonly (string|null)[];readonly sources:readonly ChartSource[];readonly issues:readonly ChartIssue[]}
export interface ChartExternalMetadata {readonly path:readonly number[];readonly relationshipId:string|null;readonly autoUpdate:readonly (string|null)[]}
export interface DecodedChartContent {readonly status:'decoded'|'opaque';readonly chartType:string|null;readonly chartTypes:readonly string[];readonly plotGroups:readonly {readonly type:string;readonly path:readonly number[]}[];readonly series:readonly ChartSeries[];readonly externalData:readonly ChartExternalMetadata[];readonly issues:readonly ChartIssue[]}
const namespaces=['http://schemas.openxmlformats.org/drawingml/2006/chart','http://purl.oclc.org/ooxml/drawingml/chart'];
const groups=['areaChart','area3DChart','lineChart','line3DChart','stockChart','radarChart','scatterChart','pieChart','pie3DChart','doughnutChart','barChart','bar3DChart','ofPieChart','surfaceChart','surface3DChart','bubbleChart'];
const plotMetadata=['layout','catAx','valAx','dateAx','serAx','dTable','spPr'];
const roleNames:Readonly<Record<string,ChartSource['role']>>={tx:'label',cat:'category',val:'value',xVal:'x',yVal:'y',bubbleSize:'bubble'};
/** Reads stored native chart data through existing MCE choices; never evaluates numeric or formula strings. */
export function decodeChartContent(root:XmlElement,part:string,budget:DocumentBudget):DecodedChartContent {
 const w=root.namespace,paths=new Map<XmlElement,readonly number[]>(),children=new Map<XmlElement,readonly XmlElement[]>();
 const raw=(node:XmlElement,path:readonly number[])=>{budget.charge('work',path.length+1);budget.charge('retainedBytes',64+path.length*8);paths.set(node,path);node.children.forEach((child,i)=>raw(child,[...path,i]));};raw(root,[]);
 const view=new MarkupCompatibility(root,documentCompatibilityProfile,budget);
 const effective=(content:readonly CompatibilityContent[]):XmlElement[]=>{const result:XmlElement[]=[];for(const item of content){budget.charge('work',1);if('source' in item){children.set(item.source,effective(item.content));result.push(item.source);}}return result;};effective(view.content);
 const kids=(node:XmlElement)=>children.get(node)??[];
 const named=(node:XmlElement,name:string)=>kids(node).filter(n=>n.namespace===w&&n.localName===name);
 const attr=(node:XmlElement,name:string,namespace='')=>node.attributes.find(a=>a.namespace===namespace&&a.localName===name)?.value??null;
 const reserve=(node:XmlElement,strings:readonly (string|null)[]=[])=>{budget.charge('work',1+strings.reduce((n,s)=>n+(s?.length??0),0));budget.charge('retainedBytes',128+(paths.get(node)?.length??0)*8+strings.reduce((n,s)=>n+(s?.length??0)*2,0));budget.charge('matches',1);};
 const issue=(code:string,node:XmlElement,message:string):ChartIssue=>{reserve(node,[code,part,message]);budget.charge('diagnosticBytes',code.length+message.length+part.length+32);return{code,part,path:paths.get(node)!,message};};
 const rootIssues:ChartIssue[]=[];
 const text=(node:XmlElement,issues:ChartIssue[]):string|null=>{if(node.namespace!==w||node.content.some(c=>c.kind!=='text'&&c.kind!=='cdata')){issues.push(issue('opaque-value',node,'A stored value has unsupported content.'));return null;}reserve(node,[node.text]);return node.text;};
 const values=(node:XmlElement,name:string,issues:ChartIssue[]):(string|null)[]=>{const result=kids(node).filter(n=>n.localName===name).map(n=>text(n,issues));if(result.length>1)issues.push(issue('duplicate-value',node,'A singleton value has repeated declarations.'));return result;};
 const unsigned=(value:string|null)=>{if(value===null||!value||[...value].some(c=>c<'0'||c>'9'))return false;let i=0;while(i<value.length-1&&value[i]==='0')i++;const token=value.slice(i);return token.length<10||token.length===10&&token<='4294967295';};
 const declarations=(node:XmlElement,name:string,issues:ChartIssue[]):(string|null)[]=>{const result=named(node,name).map(n=>{const value=attr(n,'val');reserve(n,[value]);if(!unsigned(value))issues.push(issue('invalid-index',n,'A stored index or count is missing or malformed.'));return value;});if(result.length>1)issues.push(issue('duplicate-declaration',node,'A singleton declaration is repeated.'));return result;};
 const points=(node:XmlElement,parentIssues:ChartIssue[]):ChartPoint[]=>{const seen=new Set<string>();return named(node,'pt').map(n=>{const issues:ChartIssue[]=[],index=attr(n,'idx');reserve(n,[index]);if(!unsigned(index))issues.push(issue('invalid-index',n,'A stored point index is missing or malformed.'));if(index!==null){let i=0;while(i<index.length-1&&index[i]==='0')i++;const key=index.slice(i);if(seen.has(key))parentIssues.push(issue('duplicate-point-index',n,'Stored point indices are repeated.'));seen.add(key);}const stored=values(n,'v',issues);if(stored.length!==1)issues.push(issue('point-value-cardinality',n,'A point does not contain exactly one admitted value.'));return{path:paths.get(n)!,index,values:stored,issues};});};
 const cache=(node:XmlElement,kind:ChartCache['kind'],cached:boolean):ChartCache=>{reserve(node);const issues:ChartIssue[]=[],counts=declarations(node,'ptCount',issues),formatCodes=values(node,'formatCode',issues);const ordinary=kind==='multilevel-string'?[]:points(node,issues);const levels=kind==='multilevel-string'?named(node,'lvl').map(n=>{reserve(n);return{path:paths.get(n)!,points:points(n,issues)};}):[];const allowed=['ptCount','formatCode',kind==='multilevel-string'?'lvl':'pt'];for(const child of kids(node))if(child.namespace!==w||!allowed.includes(child.localName))issues.push(issue('opaque-cache-child',child,'Unsupported cache content remains uninterpreted.'));return{kind,path:paths.get(node)!,cached,freshness:cached?'unknown':null,counts,formatCodes,points:ordinary,levels,issues};};
 const source=(node:XmlElement,role:ChartSource['role']):ChartSource=>{reserve(node);const issues:ChartIssue[]=[],name=node.localName;const allowed=role==='label'?['v','strRef']:role==='category'?['strLit','numLit','strRef','numRef','multiLvlStrRef']:['numLit','numRef'];const supported=node.namespace===w&&allowed.includes(name);let kind:ChartSource['kind']=!supported?'opaque':['strRef','numRef','multiLvlStrRef'].includes(name)?'reference':'literal';const literals=name==='v'?[text(node,issues)]:[],formulas=values(node,'f',issues),caches:ChartCache[]=[];
  if(!supported)issues.push(issue('opaque-source',node,'This stored series source is outside the bounded native profile.'));
  else if(name==='numLit'||name==='strLit')caches.push(cache(node,name==='numLit'?'numeric':'string',false));
  else if(kind==='reference'){const expected=name==='numRef'?'numCache':name==='strRef'?'strCache':'multiLvlStrCache';for(const child of kids(node)){if(child.namespace===w&&child.localName===expected)caches.push(cache(child,name==='numRef'?'numeric':name==='strRef'?'string':'multilevel-string',true));else if(!(child.namespace===w&&child.localName==='f'))issues.push(issue('opaque-source-child',child,'Unsupported reference-source content remains uninterpreted.'));}if(caches.length>1)issues.push(issue('ambiguous-cache',node,'A reference source has multiple cache declarations.'));}
  if(issues.some(i=>i.code==='opaque-value')&&name==='v')kind='opaque';return{role,namespace:node.namespace,localName:name,path:paths.get(node)!,kind,literals,formulas,caches,issues};};
 const seriesList:ChartSeries[]=[],plotGroups:DecodedChartContent['plotGroups'][number][]=[];
 if(!namespaces.includes(w)||root.localName!=='chartSpace')rootIssues.push(issue('opaque-chart-root',root,'The definition root is outside the bounded standard chart profile.'));
 const charts=named(root,'chart'),areas=charts.length===1?named(charts[0]!,'plotArea'):[];
 if(charts.length!==1||areas.length!==1)rootIssues.push(issue('chart-structure',root,'Exactly one native chart and plot area are required for decoding.'));
 if(namespaces.includes(w)&&root.localName==='chartSpace'&&areas.length===1){for(const group of kids(areas[0]!)){
  if(group.namespace!==w||!groups.includes(group.localName)){if(group.namespace!==w||!plotMetadata.includes(group.localName))rootIssues.push(issue('opaque-plot-child',group,'Unsupported plot content remains uninterpreted.'));continue;}
  reserve(group,[group.localName]);const groupIndex=plotGroups.length;plotGroups.push({type:group.localName,path:paths.get(group)!});
  for(const s of named(group,'ser')){reserve(s);const issues:ChartIssue[]=[],sources:ChartSource[]=[];for(const container of kids(s)){const role=Object.hasOwn(roleNames,container.localName)?roleNames[container.localName]:undefined;if(!role)continue;if(container.namespace!==w){sources.push(source(container,role));continue;}if(!kids(container).length){issues.push(issue('missing-source',container,'A series source declaration is empty.'));sources.push(source(container,role));}for(const child of kids(container))sources.push(source(child,role));}
   const labels=sources.filter(s=>s.role==='label');let name:string|null=null,provenance:ChartSeries['label']['provenance']='missing';
   if(labels.length===1){const label=labels[0]!;if(label.kind==='literal'&&label.localName==='v'&&label.literals.length===1&&label.literals[0]!==null){name=label.literals[0]!;provenance='literal';}else if(label.kind==='reference'&&label.localName==='strRef'&&label.caches.length===1&&label.caches[0]!.points.length===1&&label.caches[0]!.points[0]!.index==='0'&&label.caches[0]!.points[0]!.values.length===1&&label.caches[0]!.points[0]!.values[0]!==null){name=label.caches[0]!.points[0]!.values[0]!;provenance='cached';}else{provenance=label.kind==='opaque'?'opaque':'ambiguous';issues.push(issue('ambiguous-label',s,'The stored label does not admit the compact name projection.'));}}
   else if(labels.length>1){provenance='ambiguous';issues.push(issue('ambiguous-label',s,'Multiple label sources do not admit the compact name projection.'));}
   const primary=sources.filter(source=>source.role===(['scatterChart','bubbleChart'].includes(group.localName)?'y':'value'));let cachedValues:(string|null)[]=[];
   if(primary.length===1&&primary[0]!.kind==='reference'&&primary[0]!.caches.length===1&&primary[0]!.caches[0]!.kind==='numeric'){cachedValues=primary[0]!.caches[0]!.points.map(p=>{if(p.values.length===1)return p.values[0]!;issues.push(issue('point-value-cardinality',s,'A primary cache point has an absent or ambiguous value.'));return null;});}
   else{issues.push(issue(primary.length>1||primary.some(p=>p.caches.length>1)?'ambiguous-primary-cache':'missing-primary-cache',s,'The primary source does not admit a unique numeric reference cache projection.'));}
   seriesList.push({group:groupIndex,path:paths.get(s)!,indices:declarations(s,'idx',issues),orders:declarations(s,'order',issues),name,label:{provenance},cachedValues,sources,issues});
  }
 }}
 if(!plotGroups.length)rootIssues.push(issue('no-native-plot-group',root,'No admitted native plot group is available.'));
 const externalData=named(root,'externalData').map(n=>{reserve(n);const r=w===namespaces[1]?'http://purl.oclc.org/ooxml/officeDocument/relationships':'http://schemas.openxmlformats.org/officeDocument/2006/relationships';return{path:paths.get(n)!,relationshipId:attr(n,'id',r),autoUpdate:named(n,'autoUpdate').map(a=>{const value=attr(a,'val');reserve(a,[value]);if(value===null)rootIssues.push(issue('opaque-value',a,'A stored auto-update scalar is missing or unsupported.'));return value;})};});
 const chartTypes=plotGroups.map(g=>g.type);return{status:plotGroups.length?'decoded':'opaque',chartType:plotGroups.length===1?plotGroups[0]!.type:null,chartTypes,plotGroups,series:seriesList,externalData,issues:rootIssues};
}
