import {expect,it} from "vitest";
import {Volume} from "memfs";
import * as api from "./index.js";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import {textContext,textFixture,w} from "../tests/fixtures/text.js";
import {saveFixture} from "../tests/fixtures/save-output.js";
import {readPackage,assertPackageLinks,xmlStructure} from "../tests/assertions.js";
import {documentPartSourceCases} from "../tests/fixtures/document-part-exact-source.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
type Node=ReturnType<typeof xmlStructure>;
const nodes=(n:Node):Node[]=>[n,...n.children.flatMap(c=>typeof c==="string"?[]:nodes(c))];
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const c of documentPartSourceCases)for(const route of ["model","sdk","shell"] as const)
it(`${route} independently executes exact document-part witness R${c.row}; ${kind}; strict=${strict}`,async()=>{
 const r=strict?"http://purl.oclc.org/ooxml/officeDocument/relationships":"http://schemas.openxmlformats.org/officeDocument/2006/relationships",word=strict?"http://purl.oclc.org/ooxml/wordprocessingml/main":w,main="word/document.xml",rels="word/_rels/document.xml.rels",styles=`<w:styles xmlns:w="${w}"><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="BodyText"><w:name w:val="Body Text"/></w:style><w:style w:type="character" w:styleId="BodyCharacter"><w:name w:val="Body Character"/></w:style></w:styles>`,stories:Record<string,{kind:string;xml:string}>={comments:{kind:"comments",xml:`<w:comments xmlns:w="${w}"><w:comment w:id="2" w:author="Original"><w:p/></w:comment></w:comments>`},settings:{kind:"settings",xml:`<w:settings xmlns:w="${w}"><w:evenAndOddHeaders/></w:settings>`},styles:{kind:"styles",xml:styles},numbering:{kind:"numbering",xml:`<w:numbering xmlns:w="${w}"/>`},header:{kind:"header",xml:`<w:hdr xmlns:w="${w}"><w:p/></w:hdr>`},footer:{kind:"footer",xml:`<w:ftr xmlns:w="${w}"><w:p/></w:ftr>`}};
 if("missing"in c)delete stories[c.member==="numbering_part"?"numbering":c.member];const parts=readPackage(await textFixture('<w:p><w:r><w:t>Retain é 日本 עברית 🌊</w:t></w:r></w:p><w:sectPr/>',stories,strict));
 const id="id"in c?c.id:undefined,reserved=c.member==="add_footer_part"?11:c.member==="add_header_part"?6:0;
 let relationships=new TextDecoder().decode(parts.get(rels));if(c.member==="header_part"||c.member==="drop_header_part")relationships=relationships.replace('Id="header"',`Id="${id}"`);if(c.member==="footer_part")relationships=relationships.replace('Id="footer"',`Id="${id}"`);relationships=relationships.replace('</Relationships>',Array.from({length:reserved},(_,i)=>`<Relationship Id="rId${i+1}" Type="urn:original:reserved" Target="../audit/exact.bin"/>`).join("")+'<Relationship Id="audit" Type="urn:original:audit" Target="../audit/exact.bin"/></Relationships>');parts.set(rels,new TextEncoder().encode(relationships));parts.set("audit/exact.bin",new Uint8Array([0,255,10,7]));
 parts.set("metadata/core.xml",new TextEncoder().encode('<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>Native DocumentPart</dc:title></cp:coreProperties>'));parts.set("_rels/.rels",new TextEncoder().encode(new TextDecoder().decode(parts.get("_rels/.rels")).replace('</Relationships>','<Relationship Id="core" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="metadata/core.xml"/></Relationships>')));parts.set("[Content_Types].xml",new TextEncoder().encode(new TextDecoder().decode(parts.get("[Content_Types].xml")).replace('</Types>','<Default Extension="bin" ContentType="application/octet-stream"/><Override PartName="/metadata/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>').replace(kind==="dotx"?"wordprocessingml.document.main+xml":"__absent__","wordprocessingml.template.main+xml")));
 const memory=Volume.fromJSON({"/input":"","/out":""}),sink={async write(bytes:Uint8Array){memory.appendFileSync("/out",bytes);}},env=saveFixture(),context={...textContext,binaryResolver:{...env.vfs,capability:"command"}};await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date("2026-01-02T03:04:06Z")}))},{async write(bytes){memory.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer),operations:Record<string,unknown>[]=[{operation:"model.document.Document.part.get",receiver:ref("document"),arguments:{},resultHandle:"part"}];
 const args:Record<string,unknown>=c.member==="save"?{output:{path:"/work/foobar.docx",capability:"command"}}:"id"in c&&!c.member.startsWith("add_")?{rId:c.id}:c.member==="get_style"?{styleId:"BodyText",styleType:api.WD_STYLE_TYPE.PARAGRAPH}:c.member==="get_style_id"?{styleOrName:ref("character"),styleType:api.WD_STYLE_TYPE.CHARACTER}:{};
 if(c.member==="get_style_id")operations.push({operation:"model.parts.document.DocumentPart.styles.get",receiver:ref("part"),arguments:{},resultHandle:"styles"},{operation:"model.styles.styles.Styles.get_by_id.call",receiver:ref("styles"),arguments:{styleId:"BodyCharacter",styleType:api.WD_STYLE_TYPE.CHARACTER},resultHandle:"character"});const method=c.member.startsWith("add_")||["drop_header_part","header_part","footer_part","get_style","get_style_id","save"].includes(c.member);operations.push({operation:`model.parts.document.DocumentPart.${c.member}.${method?"call":"get"}`,receiver:ref("part"),arguments:args,...(c.member==="save"||c.member==="drop_header_part"?{}:{resultHandle:"observed"})});
 if("part"in c){if(c.member==="styles"||c.member==="settings")operations.push({operation:c.member==="styles"?"model.styles.styles.Styles.part.get":"model.settings.Settings.part.get",receiver:ref("observed"),arguments:{}});operations.push({operation:"model.parts.document.DocumentPart.part_related_by.call",receiver:ref("part"),arguments:{reltype:r+"/"+c.part},resultHandle:"definition"},{operation:"model.opc.part.Part.partname.get",receiver:ref("definition"),arguments:{}});}
 const mutation=operations.some(o=>api.docxOperationSchemas[o.operation as keyof typeof api.docxOperationSchemas]?.mutates),creating="missing"in c||c.member.startsWith("add_"),dropping=c.member==="drop_header_part";
 const observe=(values:unknown[])=>{if("part"in c)expect(values.at(-1)).toBe("/word/"+c.part+("missing"in c?"1":"")+".xml");else if(c.member.startsWith("add_")){const pair=values.at(-1) as {type:string}[];expect(pair[0]).toMatchObject({type:c.member==="add_header_part"?"HeaderPart":"FooterPart",owner:"document"});expect(pair[1]).toBe(id);}else if(c.member==="get_style_id")expect(values.at(-1)).toBe("BodyCharacter");else if(c.member!=="save"&&c.member!=="drop_header_part")expect(values.at(-1)).toMatchObject({type:({header_part:"HeaderPart",footer_part:"FooterPart",comments:"Comments",settings:"Settings",styles:"Styles",core_properties:"CoreProperties",inline_shapes:"InlineShapes",numbering_part:"NumberingPart",get_style:"ParagraphStyle"} as Record<string,string>)[c.member]});};
 if(route==="model"){const doc=await api.Document(input,context),part=doc.part;if(c.member==="save"){const pending=part.save({path:"/work/foobar.docx",capability:"command"});expect(pending).toBeInstanceOf(Promise);await pending;memory.writeFileSync("/out",env.bytes("/work/foobar.docx"));}else if(c.member.startsWith("add_")){const pair=c.member==="add_header_part"?part.add_header_part():part.add_footer_part();expect(pair[1]).toBe(id);expect(pair[0].package).toBe(part.package);expect(pair[0]).toBeInstanceOf(c.member==="add_header_part"?api.HeaderPart:api.FooterPart);expect(part.related_parts.get(id!)).toBe(pair[0]);}else if(c.member==="drop_header_part"){part.drop_header_part(c.id);expect(part.rels.has(c.id)).toBe(false);}else if(c.member==="header_part"||c.member==="footer_part"){const got=c.member==="header_part"?part.header_part(c.id):part.footer_part(c.id);expect(got).toBe(part.related_parts.get(c.id));expect(String(got.partname)).toBe(c.member==="header_part"?"/word/header.xml":"/word/footer.xml");}else if(c.member==="get_style"){expect(part.get_style("BodyText",api.WD_STYLE_TYPE.PARAGRAPH).equals(doc.styles.at("Body Text"))).toBe(true);}else if(c.member==="get_style_id")expect(part.get_style_id(doc.styles.at("Body Character"),api.WD_STYLE_TYPE.CHARACTER)).toBe("BodyCharacter");else if(c.member==="numbering_part"){expect(part.numbering_part).toBeInstanceOf(api.NumberingPart);expect(part.numbering_part).toBe(part.part_related_by(r+"/numbering"));}else if(c.member==="comments"){expect(part.comments.length).toBe(doc.comments.length);if(!("missing"in c)){expect(part.comments.get(2)!.part).toBe(doc.comments.get(2)!.part);expect(part.comments.get(2)!.element.serialize()).toEqual(doc.comments.get(2)!.element.serialize());}expect(part.comments.length).toBe("missing"in c?0:1);}else if(c.member==="settings"){expect(part.settings).toBe(doc.settings);if("part"in c)void part.settings.part;else expect(part.settings.odd_and_even_pages_header_footer).toBe(true);}else if(c.member==="styles"){if("part"in c)void part.styles.part;else expect(part.styles.at("Body Text").name).toBe("Body Text");}else if(c.member==="core_properties"){expect(part.core_properties).toBe(doc.core_properties);expect(part.core_properties.title).toBe("Native DocumentPart");}else expect(part.inline_shapes.length).toBe(0);if("part"in c)expect(String(part.part_related_by(r+"/"+c.part).partname)).toBe("/word/"+c.part+("missing"in c?"1":"")+".xml");if(c.member!=="save")await part.save(sink);}
 else if(route==="sdk"){const batch=await api.applyStyleModelBatch(input,{version:1,operations},context);observe(batch.results.map(v=>v.value));if(c.member==="save"){expect(env.volume.existsSync("/work/foobar.docx")).toBe(false);await batch.save({path:"/work/foobar.docx",capability:"command"});memory.writeFileSync("/out",env.bytes("/work/foobar.docx"));}else await batch.save(sink);}
 else{const fs=new MemoryFileSystem();await fs.mkdir("/work");await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' ${mutation?`--output ${c.member==="save"?"/work/foobar.docx":"/out"} ${c.member==="save"?"":"--force"}`:""} --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);observe(JSON.parse(result.stdout).data.results.map((v:{data:unknown})=>v.data));if(mutation)memory.writeFileSync("/out",await fs.readFile(c.member==="save"?"/work/foobar.docx":"/out"));else{expect(new TextDecoder().decode(await fs.readFile("/out"))).toBe("Original destination");await(await api.Document(input,context)).save(sink);}expect(await fs.readFile("/input")).toEqual(input);}finally{await shell.dispose();}}
 const saved=readPackage(new Uint8Array(memory.readFileSync("/out") as Buffer));assertPackageLinks(saved);expect(saved.get(main)).toEqual(parts.get(main));const dirty=new Set(creating||dropping?[rels,"[Content_Types].xml",...(dropping?["word/header.xml"]:[])]:[]);for(const[name,bytes]of parts)if(!dirty.has(name))expect(saved.get(name),name).toEqual(bytes);if(creating){const old=nodes(xmlStructure(parts.get(rels)!)).filter(n=>n.name.endsWith("}Relationship")),edges=nodes(xmlStructure(saved.get(rels)!)).filter(n=>n.name.endsWith("}Relationship"));expect(edges).toHaveLength(old.length+1);for(const edge of old)expect(edges).toContainEqual(edge);const created=edges.find(e=>!old.some(o=>o.attributes["{}Id"]===e.attributes["{}Id"]))!,resource=creating&&c.member.startsWith("add_")?c.member==="add_header_part"?"header":"footer":c.member==="numbering_part"?"numbering":c.member;expect(created.attributes["{}Type"]).toBe(r+"/"+resource);if(id)expect(created.attributes["{}Id"]).toBe(id);const target="word/"+created.attributes["{}Target"]!,rootNode=nodes(xmlStructure(saved.get(target)!)).find(n=>n.name!=="#document")!;expect(rootNode.name).toBe("{"+word+"}"+({header:"hdr",footer:"ftr",comments:"comments",settings:"settings",styles:"styles",numbering:"numbering"} as Record<string,string>)[resource]);if(resource==="header"||resource==="footer")expect(nodes(rootNode).filter(n=>n.name==="{"+word+"}p")).toHaveLength(1);}if(dropping){expect(saved.has("word/header.xml")).toBe(false);expect(new TextDecoder().decode(saved.get(rels))).not.toContain('Id="rId42"');}expect(memory.readFileSync("/input")).toEqual(Buffer.from(input));
});
