import {Volume} from "memfs";
import {expect,it} from "vitest";
import {MemoryFileSystem,Shell} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import * as api from "./index.js";
import {textContext,textFixture,paragraph,w as transitionalW,r as transitionalR} from "../tests/fixtures/text.js";
import {readPackage} from "../tests/assertions.js";
const enc=(s:string)=>new TextEncoder().encode(s),ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const route of ["model","sdk","cli","cli-dry"] as const)
it(`${route} rejects owned embedded font XML subset mutation strict=${strict}`,async()=>{
 const w=strict?"http://purl.oclc.org/ooxml/wordprocessingml/main":transitionalW,r=strict?"http://purl.oclc.org/ooxml/officeDocument/relationships":transitionalR;
 const parts=readPackage(await textFixture(paragraph("Retain 日本 עברית é 🌊"),{fontTable:{kind:"fontTable",xml:`<w:fonts xmlns:w="${w}" xmlns:r="${r}"><w:font w:name="Original Face"><w:embedRegular r:id="font" w:fontKey="{12345678-1234-1234-1234-123456789ABC}" w:subsetted="1"/></w:font><w:font w:name="Ordinary Face"/><!--retain--><?audit keep?></w:fonts>`}},strict));
 parts.set("[Content_Types].xml",enc(new TextDecoder().decode(parts.get("[Content_Types].xml")!).replace("</Types>",'<Override PartName="/word/fonts/payload.bin" ContentType="application/x-fontdata"/></Types>')));
 parts.set("word/fonts/payload.bin",Uint8Array.of(0,255,7,31));parts.set("word/_rels/fontTable.xml.rels",enc(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="font" Type="${r}/font" Target="fonts/payload.bin"/></Relationships>`));
 const memory=Volume.fromJSON({"/input":"","/output":"retained"});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date("2026-01-02T03:04:06Z")}))},{async write(b){memory.appendFileSync("/input",b);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer);
 const operations=[{operation:"model.document.Document.part.get",receiver:ref("document"),arguments:{},resultHandle:"documentPart"},{operation:"model.opc.part.Part.part_related_by.call",receiver:ref("documentPart"),arguments:{reltype:r+"/fontTable"},resultHandle:"fontsPart"},{operation:"model.opc.part.XmlPart.element.get",receiver:ref("fontsPart"),arguments:{},resultHandle:"fontsRoot"},{operation:"model.XmlElementView.children.get",receiver:ref("fontsRoot"),arguments:{},resultHandle:"fontRows"},{operation:"model.XmlElementView.children.get",receiver:ref("fontRows",0),arguments:{},resultHandle:"fontChildren"},{operation:"model.XmlElementView.set_attribute.call",receiver:ref("fontChildren",0),arguments:{name:{namespaceURI:w,localName:"subsetted"},value:"0"}}],batch={version:1,operations};
 if(route==="model"){const d=await api.Document(input,textContext),part=d.part.part_related_by(r+"/fontTable") as api.XmlPartView;expect(()=>part.element.children[0]!.children[0]!.set_attribute({namespaceURI:w,localName:"subsetted"},"0")).toThrow("Embedded font mutation is unsupported");memory.writeFileSync("/copy","");await d.save({async write(b){memory.appendFileSync("/copy",b);}});expect(readPackage(new Uint8Array(memory.readFileSync("/copy") as Buffer))).toEqual(parts);}
 else if(route==="sdk")await expect(api.applyStyleModelBatch(input,batch,textContext)).rejects.toMatchObject({code:"unsupported-edit",message:expect.stringContaining("Embedded font mutation is unsupported")});
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/output",enc("retained"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify(batch)}' --output /output --force --json${route==="cli-dry"?" --dry-run":""}`);expect(result.exitCode,result.stdout+result.stderr).toBe(1);expect(JSON.parse(result.stdout)).toMatchObject({ok:false,data:null,affected:0,errors:[{code:"unsupported-edit",message:expect.stringContaining("Embedded font mutation is unsupported")}]});expect(await fs.readFile("/input")).toEqual(input);expect(await fs.readFile("/output")).toEqual(enc("retained"));}finally{await shell.dispose();}}
 expect(memory.readFileSync("/output","utf8")).toBe("retained");expect(new Uint8Array(memory.readFileSync("/input") as Buffer)).toEqual(input);
});
for(const strict of [false,true])for(const route of ["model","sdk","cli"] as const)
it(`${route} permits owned font XML no-op and unembedded definition changes strict=${strict}`,async()=>{
 const w=strict?"http://purl.oclc.org/ooxml/wordprocessingml/main":transitionalW,r=strict?"http://purl.oclc.org/ooxml/officeDocument/relationships":transitionalR;
 const parts=readPackage(await textFixture(paragraph("Retain 日本 עברית é 🌊"),{fontTable:{kind:"fontTable",xml:`<w:fonts xmlns:w="${w}" xmlns:r="${r}"><w:font w:name="Original Face"><w:embedRegular r:id="font" w:fontKey="{12345678-1234-1234-1234-123456789ABC}" w:subsetted="1"/></w:font><w:font w:name="Ordinary Face"/><!--retain--><?audit keep?></w:fonts>`}},strict));
 parts.set("[Content_Types].xml",enc(new TextDecoder().decode(parts.get("[Content_Types].xml")!).replace("</Types>",'<Override PartName="/word/fonts/payload.bin" ContentType="application/x-fontdata"/></Types>')));parts.set("word/fonts/payload.bin",Uint8Array.of(0,255,7,31));parts.set("word/_rels/fontTable.xml.rels",enc(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="font" Type="${r}/font" Target="fonts/payload.bin"/></Relationships>`));const memory=Volume.fromJSON({"/input":"","/output":""});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date("2026-01-02T03:04:06Z")}))},{async write(b){memory.appendFileSync("/input",b);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer),sink={async write(b:Uint8Array){memory.appendFileSync("/output",b);}};
 const operations=[{operation:"model.document.Document.part.get",receiver:ref("document"),arguments:{},resultHandle:"documentPart"},{operation:"model.opc.part.Part.part_related_by.call",receiver:ref("documentPart"),arguments:{reltype:r+"/fontTable"},resultHandle:"fontsPart"},{operation:"model.opc.part.XmlPart.element.get",receiver:ref("fontsPart"),arguments:{},resultHandle:"fontsRoot"},{operation:"model.XmlElementView.children.get",receiver:ref("fontsRoot"),arguments:{},resultHandle:"fontRows"},{operation:"model.XmlElementView.children.get",receiver:ref("fontRows",0),arguments:{},resultHandle:"fontChildren"},{operation:"model.XmlElementView.set_attribute.call",receiver:ref("fontChildren",0),arguments:{name:{namespaceURI:w,localName:"subsetted"},value:"1"}},{operation:"model.XmlElementView.set_attribute.call",receiver:ref("fontRows",1),arguments:{name:{namespaceURI:w,localName:"name"},value:"Changed Ordinary Face"}}];
 if(route==="model"){const d=await api.Document(input,textContext),root=(d.part.part_related_by(r+"/fontTable") as api.XmlPartView).element;root.children[0]!.children[0]!.set_attribute({namespaceURI:w,localName:"subsetted"},"1");const copy=Volume.fromJSON({"/copy":""});await d.save({async write(b){copy.appendFileSync("/copy",b);}});expect(readPackage(new Uint8Array(copy.readFileSync("/copy") as Buffer))).toEqual(parts);root.children[1]!.set_attribute({namespaceURI:w,localName:"name"},"Changed Ordinary Face");await d.save(sink);}else if(route==="sdk"){const edited=await api.applyStyleModelBatch(input,{version:1,operations},textContext);expect(edited.affected).toBe(1);await edited.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /output --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(0);expect(JSON.parse(result.stdout).affected).toBe(1);memory.writeFileSync("/output",await fs.readFile("/output"));expect(await fs.readFile("/input")).toEqual(input);}finally{await shell.dispose();}}
 const saved=readPackage(new Uint8Array(memory.readFileSync("/output") as Buffer));for(const[name,bytes]of parts)if(name!=="word/fontTable.xml")expect(saved.get(name),name).toEqual(bytes);const xml=new api.DocumentXmlEditor(saved.get("word/fontTable.xml")!),before=new api.DocumentXmlEditor(parts.get("word/fontTable.xml")!);expect(xml.sourceXml(xml.root.children[0]!)).toBe(before.sourceXml(before.root.children[0]!));expect((await api.inspectDocument(new Uint8Array(memory.readFileSync("/output") as Buffer),textContext)).fontResources.fontTables[0]!.fonts[1]!.name).toBe("Changed Ordinary Face");expect(new Uint8Array(memory.readFileSync("/input") as Buffer)).toEqual(input);
});
