import {Volume} from "memfs";
import {expect,it} from "vitest";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import * as api from "./index.js";
import {textFixture,textContext} from "../tests/fixtures/text.js";
import {readPackage} from "../tests/assertions.js";
const enc=(s:string)=>new TextEncoder().encode(s),ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
const classes={Font:"text.run.Font",ColorFormat:"dml.color.ColorFormat",ParagraphFormat:"text.parfmt.ParagraphFormat",TabStops:"text.tabstops.TabStops"};
for(const strict of [false,true])for(const kind of Object.keys(classes) as Array<keyof typeof classes>)for(const method of ["__eq__","__ne__"])for(const route of ["model","sdk","cli"] as const)
it(`${route} rejects removed ${kind}.${method}(null) before type mismatch; strict=${strict}`,async()=>{
 const input=await textFixture(`<w:p><w:pPr><w:tabs><w:tab w:val="left" w:pos="720"/></w:tabs><w:keepNext/></w:pPr><w:r><w:rPr><w:b/><w:rtl/></w:rPr><w:t>Removed 日本 עברית é 🌊</w:t></w:r></w:p><w:p><w:r><w:t>Retained</w:t></w:r></w:p>`,{},strict),volume=Volume.fromJSON({"/out":""}),sink={async write(bytes:Uint8Array){volume.appendFileSync("/out",bytes);}};
 const ops:Array<{operation:string;receiver:ReturnType<typeof ref>;arguments:Record<string,unknown>;resultHandle?:string}>=[{operation:"model.document.Document.paragraphs.get",receiver:ref("document"),arguments:{},resultHandle:"paragraphs"}];
 if(kind==="Font"||kind==="ColorFormat"){ops.push({operation:"model.text.paragraph.Paragraph.runs.get",receiver:ref("paragraphs",0),arguments:{},resultHandle:"runs"},{operation:"model.text.run.Run.font.get",receiver:ref("runs",0),arguments:{},resultHandle:kind==="Font"?"selected":"font"});if(kind==="ColorFormat")ops.push({operation:"model.text.run.Font.color.get",receiver:ref("font"),arguments:{},resultHandle:"selected"});ops.push({operation:"model.text.paragraph.Paragraph.clear.call",receiver:ref("paragraphs",0),arguments:{}});}
 else{ops.push({operation:"model.text.paragraph.Paragraph.paragraph_format.get",receiver:ref("paragraphs",0),arguments:{},resultHandle:kind==="ParagraphFormat"?"selected":"format"});if(kind==="TabStops")ops.push({operation:"model.text.parfmt.ParagraphFormat.tab_stops.get",receiver:ref("format"),arguments:{},resultHandle:"selected"});ops.push({operation:"model.text.paragraph.Paragraph.element.get",receiver:ref("paragraphs",0),arguments:{},resultHandle:"element"},{operation:"model.XmlElementView.remove.call",receiver:ref("element"),arguments:{}});}
 ops.push({operation:`model.${classes[kind]}.${method}.call`,receiver:ref("selected"),arguments:{other:null}});
 if(route==="model"){const d=await api.Document(input,textContext),p=d.paragraphs[0]!,selected=kind==="Font"?p.runs[0]!.font:kind==="ColorFormat"?p.runs[0]!.font.color:kind==="ParagraphFormat"?p.paragraph_format:p.paragraph_format.tab_stops;if(kind==="Font"||kind==="ColorFormat")p.clear();else p.element.remove();expect(()=>method==="__eq__"?selected.equals(null):!selected.equals(null)).toThrowError(expect.objectContaining({code:"stale-selection"}));await d.save(sink);const saved=readPackage(new Uint8Array(volume.readFileSync("/out") as Buffer));for(const[n,b]of readPackage(input))if(n!=="word/document.xml")expect(saved.get(n),n).toEqual(b);expect(d.paragraphs.at(-1)!.text).toBe("Retained");}
 else if(route==="sdk")await expect(api.applyStyleModelBatch(input,{version:1,operations:ops},textContext)).rejects.toMatchObject({code:"stale-selection",operationIndex:ops.length-1});
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/destination",enc("Retained destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const r=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations:ops})}' --output /destination --force --json`);expect(r.exitCode,r.stdout+r.stderr).toBe(1);expect(JSON.parse(r.stdout)).toMatchObject({ok:false,data:null,affected:0,errors:[{code:"stale-selection",operationIndex:ops.length-1}]});expect(await fs.readFile("/input")).toEqual(input);expect(await fs.readFile("/destination")).toEqual(enc("Retained destination"));}finally{await shell.dispose();}}
});
