import { expect, it } from "vitest";
import { Volume } from "memfs";
import * as api from "./index.js";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const p=(text:string)=>`<w:p><w:r><w:t>${text}</w:t></w:r></w:p>`,table=(content:string)=>`<w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="3500"/></w:tblGrid><w:tr><w:tc>${content}</w:tc></w:tr></w:tbl>`,nested=table(p('Nested')),content=p('First')+table(p('Middle cell'))+p('Last');
const owners=['document-paragraphs','document-tables','paragraph-runs','paragraph-links','link-runs','cell-paragraphs','cell-tables','comment-paragraphs','comment-tables','header-paragraphs','header-tables','footer-paragraphs','footer-tables','table-row-cells','table-column-cells','row-cells','column-cells','row-slice','sections-slice','color-tuple','color-slice','xml-children','package-parts','relationship-pair'] as const;
function sequence(doc:api.DocumentView,owner:typeof owners[number]):readonly unknown[]{switch(owner){case'xml-children':return doc.paragraphs[0]!.element.children;case'package-parts':return doc.part.package.parts;case'relationship-pair':return doc.part.rels.items().next().value!;case'table-row-cells':return doc.tables[0]!.row_cells(0);case'table-column-cells':return doc.tables[0]!.column_cells(0);case'row-cells':return doc.tables[0]!.rows.at(0).cells;case'column-cells':return doc.tables[0]!.columns.at(0).cells;case'row-slice':return doc.tables[0]!.rows.slice(0,1);case'sections-slice':return doc.sections.slice(0,1);case'color-tuple':return new api.RGBColor(18,52,86).toArray();case'color-slice':return new api.RGBColor(18,52,86).slice(0,1);case'document-paragraphs':return doc.paragraphs;case'document-tables':return doc.tables;case'paragraph-runs':return doc.paragraphs[0]!.runs;case'paragraph-links':return doc.paragraphs[0]!.hyperlinks;case'link-runs':return doc.paragraphs[0]!.hyperlinks[0]!.runs;case'cell-paragraphs':return doc.tables[0]!.rows.at(0).cells[0]!.paragraphs;case'cell-tables':return doc.tables[0]!.rows.at(0).cells[0]!.tables;case'comment-paragraphs':return doc.comments.get(42)!.paragraphs;case'comment-tables':return doc.comments.get(42)!.tables;case'header-paragraphs':return doc.sections.at(0).header.paragraphs;case'header-tables':return doc.sections.at(0).header.tables;case'footer-paragraphs':return doc.sections.at(0).footer.paragraphs;case'footer-tables':return doc.sections.at(0).footer.tables;}}
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const owner of owners)for(const boundary of ['valid','index-end','at-end','at-before-start','fraction','nan','slice-end','slice-fraction'])
it(`model snapshot ${owner} obeys ${boundary} sequence contract; ${kind}; strict=${strict}`,async()=>{
 const parts=readPackage(await textFixture(`<w:p><w:r><w:t>First direct</w:t></w:r><w:hyperlink w:anchor="local">${p('Link A').slice(5,-6)}${p('Link B').slice(5,-6)}</w:hyperlink><w:r><w:t>Last direct</w:t></w:r></w:p>${p('Last paragraph')}${table(p('Cell A')+nested+p('Cell B'))}<w:sectPr><w:headerReference w:type="default" r:id="head"/><w:footerReference w:type="default" r:id="foot"/></w:sectPr>`,{head:{kind:'header',xml:`<w:hdr xmlns:w="${w}">${content}</w:hdr>`},foot:{kind:'footer',xml:`<w:ftr xmlns:w="${w}">${content}</w:ftr>`},comments:{kind:'comments',xml:`<w:comments xmlns:w="${w}"><w:comment w:id="42" w:author="Original">${content}</w:comment></w:comments>`}},strict));
 if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),doc=await api.Document(input,textContext),items=sequence(doc,owner);expect(items.length).toBe(owner==='package-parts'?4:owner==='xml-children'||owner==='color-tuple'?3:owner.endsWith('tables')||owner==='paragraph-links'||owner.includes('cells')||owner.endsWith('slice')?1:2);
 if(boundary==='valid'){expect(Array.isArray(items)).toBe(true);expect(items[0]).toBe(items.at(0));expect(items.at(-1)).toBe(items[items.length-1]);expect([...items]).toEqual(items);expect(items.slice(0,1)[0]).toBe(items[0]);}else if(boundary==='index-end')expect(()=>items[items.length]).toThrow(api.BoundsError);else if(boundary==='at-end')expect(()=>items.at(items.length)).toThrow(api.BoundsError);else if(boundary==='at-before-start')expect(()=>items.at(-items.length-1)).toThrow(api.BoundsError);else if(boundary==='fraction')expect(()=>items.at(0.5)).toThrow(api.InputTypeError);else if(boundary==='nan')expect(()=>items.at(NaN)).toThrow(api.InputTypeError);else if(boundary==='slice-fraction')expect(()=>items.slice(0.5,1)).toThrow(api.InputTypeError);else expect(()=>items.slice(0,1)[1]).toThrow(api.BoundsError);
 await doc.save({async write(bytes){volume.appendFileSync('/out',bytes);}});const after=readPackage(new Uint8Array(volume.readFileSync('/out') as Buffer));assertPackageLinks(after);expect(after.size).toBe(parts.size);for(const[name,bytes]of parts)expect(after.get(name),name).toEqual(bytes);expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));
});
