import { Volume } from "memfs";
import { expect, it } from "vitest";
import * as api from "./index.js";
import { MemoryFileSystem, Shell } from "@poe-platform/safe-bash";
import { docxCommands } from "@poe-platform/safe-bash/commands/docx";
import { textContext, textFixture, w } from "../tests/fixtures/text.js";
import { readPackage, assertPackageLinks } from "../tests/assertions.js";
const cases=[{row:561,count:0,companion:false},...[0,1,2,3].map((count,i)=>({row:562+i,count,companion:false})),...[1,2,3].map(count=>({row:562+count,count,companion:true}))];
expect(cases.filter(c=>!c.companion).map(c=>c.row)).toEqual([561,562,563,564,565]);
const ref=(resultHandle:string,key?:string)=>({resultHandle,...(key?{key}:{})});
for(const strict of [false,true])for(const kind of ['docx','dotx'] as const)for(const c of cases)for(const route of ['model','sdk','shell'])
it(`${route} independently executes exact numbering witness R${c.row}; ${kind}; strict=${strict}; fixture=${c.companion?'native-numbering-companion':'original'}`,async()=>{
 const raw=Array.from({length:c.count},()=>'<w:num/>').join(''),native='<w:abstractNum w:abstractNumId="7"><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="decimal"/><w:lvlText w:val="%1"/></w:lvl></w:abstractNum>'+Array.from({length:c.count},(_,i)=>`<w:num w:numId="${i+1}"><w:abstractNumId w:val="7"/></w:num>`).join(''),parts=readPackage(await textFixture('<w:p/>',{numbering:{kind:'numbering',xml:`<w:numbering xmlns:w="${w}">${c.companion?native:raw}<!--retain--><?audit keep?></w:numbering>`}},strict));
 if(kind==='dotx')parts.set('[Content_Types].xml',new TextEncoder().encode(new TextDecoder().decode(parts.get('[Content_Types].xml')).replace('wordprocessingml.document.main+xml','wordprocessingml.template.main+xml')));const volume=Volume.fromJSON({'/input':'','/out':''});await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date('2026-01-02T03:04:06Z')}))},{async write(bytes){volume.appendFileSync('/input',bytes);}},{order:'input',compression:'store'},textContext);const input=new Uint8Array(volume.readFileSync('/input') as Buffer),invalid=c.count>0&&!c.companion,sink={async write(bytes:Uint8Array){volume.appendFileSync('/out',bytes);}},operations=[{operation:'model.document.Document.part.get',receiver:ref('document'),arguments:{},resultHandle:'main'},{operation:'model.opc.part.Part.related_parts.get',receiver:ref('main'),arguments:{},resultHandle:'related'},{operation:'model.parts.numbering.NumberingPart.numbering_definitions.get',receiver:ref('related','numbering'),arguments:{},resultHandle:'definitions'},{operation:'model.NumberingDefinitionsView.length.get',receiver:ref('definitions'),arguments:{}}];
 if(route==='model'){const doc=await api.Document(input,textContext),part=doc.part.numbering_part,before=part.element.serialize(),definitions=part.numbering_definitions;expect(part).toBeInstanceOf(api.NumberingPart);expect(definitions).toBeInstanceOf(api._NumberingDefinitions);expect(definitions.length).toBe(c.count);expect(part.element.serialize()).toEqual(before);if(invalid)await expect(doc.save(sink)).rejects.toMatchObject({code:'invalid-package'});else await doc.save(sink);}else if(route==='sdk'){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);expect(batch.results.at(-1)!.value).toBe(c.count);expect(batch.affected).toBe(0);if(invalid)await expect(batch.save(sink)).rejects.toMatchObject({code:'invalid-package'});else await batch.save(sink);}else{const fs=new MemoryFileSystem();await fs.writeFile('/input',input);await fs.writeFile('/out',new TextEncoder().encode('Original destination'));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const read=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --json`);expect(read.exitCode,read.stdout+read.stderr).toBe(0);expect(JSON.parse(read.stdout).data.results.at(-1).data).toBe(c.count);expect(new TextDecoder().decode(await fs.readFile('/out'))).toBe('Original destination');if(invalid){const publish=[...operations,{operation:'model.document.Document.element.get',receiver:ref('document'),arguments:{},resultHandle:'root'},{operation:'model.XmlElementView.set_attribute.call',receiver:ref('root'),arguments:{name:{namespaceURI:strict?'http://purl.oclc.org/ooxml/wordprocessingml/main':w,localName:'rsidR'},value:null}}],reject=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations:publish})}' --output /out --force --json`);expect(reject.exitCode,reject.stdout+reject.stderr).toBe(1);expect(JSON.parse(reject.stdout).errors[0].code).toBe('invalid-package');expect(new TextDecoder().decode(await fs.readFile('/out'))).toBe('Original destination');}else await(await api.Document(input,textContext)).save(sink);expect(await fs.readFile('/input')).toEqual(input);}finally{await shell.dispose();}}
 expect(volume.readFileSync('/input')).toEqual(Buffer.from(input));if(invalid){expect((await api.validateDocument(input,textContext)).valid).toBe(false);expect(volume.readFileSync('/out')).toEqual(Buffer.from(''));return;}const after=readPackage(new Uint8Array(volume.readFileSync('/out') as Buffer));assertPackageLinks(after);expect(after.size).toBe(parts.size);for(const[name,bytes]of parts)expect(after.get(name),name).toEqual(bytes);
});
