import {expect,it} from "vitest";
import {Volume} from "memfs";
import * as api from "./index.js";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import {textContext,textFixture} from "../tests/fixtures/text.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const storyKind of ["header","footer"] as const)for(const variant of ["default","first","even"] as const)for(const action of ["part","relink"] as const)for(const duplicate of [false,true])for(const route of ["model","sdk","shell"] as const)
it(`${route} ${duplicate?"rejects duplicate":"admits unique"} ${storyKind}/${variant} binding before ${action}; ${kind}; strict=${strict}`,async()=>{
 const w=strict?"http://purl.oclc.org/ooxml/wordprocessingml/main":"http://schemas.openxmlformats.org/wordprocessingml/2006/main",root=storyKind==="header"?"hdr":"ftr",type=storyKind==="header"?"_Header":"_Footer",member=variant==="default"?storyKind:`${variant==="first"?"first":"even"}_page_${storyKind}`,binding=(id:string)=>`<w:${storyKind}Reference w:type="${variant}" r:id="${id}"/>`,source=await textFixture(`<w:p><w:r><w:t>Original é 日本 עברית 🌊</w:t></w:r></w:p><w:sectPr><!--retain--><?stored keep?>${binding("one")}${duplicate?binding("two"):""}</w:sectPr>`,{one:{kind:storyKind,xml:`<w:${root} xmlns:w="${w}"><w:p/></w:${root}>`},two:{kind:storyKind,xml:`<w:${root} xmlns:w="${w}"><w:p/></w:${root}>`}},strict),memory=Volume.fromJSON({"/input":"","/out":"Original destination"}),archive=await api.readArchive(source,textContext);
 const members=archive.members.map(m=>kind==="dotx"&&m.name==="[Content_Types].xml"?{...m,bytes:new TextEncoder().encode(new TextDecoder().decode(m.bytes).replace("wordprocessingml.document.main+xml","wordprocessingml.template.main+xml"))}:m);await api.writeArchive({...archive,members},{async write(bytes){memory.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer),operations=[{operation:"model.document.Document.sections.get",receiver:ref("document"),arguments:{},resultHandle:"sections"},{operation:`model.section.Section.${member}.get`,receiver:ref("sections",0),arguments:{},resultHandle:"story"},{operation:`model.section.${type}.${action==="part"?"part.get":"is_linked_to_previous.set"}`,receiver:ref("story"),arguments:action==="part"?{}:{value:true}}];
 if(route==="model"){const doc=await api.Document(input,textContext),story=Reflect.get(doc.sections[0]!,member) as api._Header|api._Footer,edit=()=>action==="part"?story.part:Reflect.set(story,"is_linked_to_previous",true);if(duplicate){expect(edit).toThrowError(expect.objectContaining({code:"unsupported-edit"}));expect(new TextDecoder().decode(doc.sections[0]!.element.serialize())).toContain(binding("one"));expect(new TextDecoder().decode(doc.sections[0]!.element.serialize())).toContain(binding("two"));}else expect(edit).not.toThrow();}
 else if(route==="sdk"){const edit=api.applyStyleModelBatch(input,{version:1,operations},textContext);if(duplicate)await expect(edit).rejects.toMatchObject({code:"unsupported-edit",operationIndex:2});else expect((await edit).results).toHaveLength(3);}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(duplicate?1:0);if(duplicate){const envelope=JSON.parse(result.stdout);expect(envelope.errors[0]).toMatchObject({code:"unsupported-edit",operationIndex:2});expect(envelope.affected).toBe(0);expect(new TextDecoder().decode(await fs.readFile("/out"))).toBe("Original destination");}expect(await fs.readFile("/input")).toEqual(input);}finally{await shell.dispose();}}
 expect(memory.readFileSync("/input")).toEqual(Buffer.from(input));expect(memory.readFileSync("/out","utf8")).toBe("Original destination");
});
