import {expect,it} from "vitest";
import {Volume} from "memfs";
import * as api from "./index.js";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import {textContext,textFixture} from "../tests/fixtures/text.js";
import {readPackage,assertPackageLinks} from "../tests/assertions.js";
const ref=(resultHandle:string,index?:number)=>({resultHandle,...(index===undefined?{}:{index})});
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const storyKind of ["header","footer"] as const)for(const action of ["part","relink"] as const)for(const mode of ["active-same","inactive-same","inactive-distinct"] as const)for(const carrier of ["direct","choice","fallback","process"] as const)for(const route of ["model","sdk","shell"] as const)
it(`${route} ${action} ${storyKind} binding ${mode}/${carrier}; ${kind}; strict=${strict}`,async()=>{
 const w=strict?"http://purl.oclc.org/ooxml/wordprocessingml/main":"http://schemas.openxmlformats.org/wordprocessingml/2006/main",root=storyKind==="header"?"hdr":"ftr",type=storyKind==="header"?"_Header":"_Footer",binding=(id:string)=>`<w:${storyKind}Reference w:type="default" r:id="${id}"/>`,inactive=`<!--inactive retained--><w:${storyKind}Reference w:type="default" r:id="${mode==="inactive-distinct"?"two":"one"}"/>`,active=binding("one")+(mode==="active-same"?binding("one"):""),stored=mode==="active-same"?"":inactive,inner=carrier==="choice"?`<mc:AlternateContent><mc:Choice Requires="w">${active}</mc:Choice><mc:Fallback>${stored}</mc:Fallback></mc:AlternateContent>`:carrier==="fallback"?`<mc:AlternateContent><mc:Choice Requires="f">${stored}</mc:Choice><mc:Fallback>${active}</mc:Fallback></mc:AlternateContent>`:carrier==="process"?`<f:pass>${active}</f:pass><f:opaque>${stored}</f:opaque>`:active+`<f:opaque>${stored}</f:opaque>`,source=await textFixture(`<w:p><w:r><w:t>Retain é 日本 עברית 🌊</w:t></w:r></w:p><w:sectPr>${inner}</w:sectPr>`,{one:{kind:storyKind,xml:`<w:${root} xmlns:w="${w}"><w:p/></w:${root}>`},two:{kind:storyKind,xml:`<w:${root} xmlns:w="${w}"><w:p/></w:${root}>`}},strict),archive=await api.readArchive(source,textContext),members=archive.members.map(m=>m.name==="word/document.xml"?{...m,bytes:new TextEncoder().encode(new TextDecoder().decode(m.bytes).replace('<w:document ', '<w:document xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:f="urn:original:binding" mc:Ignorable="f" mc:ProcessContent="f:pass" '))}:kind==="dotx"&&m.name==="[Content_Types].xml"?{...m,bytes:new TextEncoder().encode(new TextDecoder().decode(m.bytes).replace("wordprocessingml.document.main+xml","wordprocessingml.template.main+xml"))}:m),memory=Volume.fromJSON({"/input":"","/out":""}),sink={async write(bytes:Uint8Array){memory.appendFileSync("/out",bytes);}};
 await api.writeArchive({...archive,members},{async write(bytes){memory.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(memory.readFileSync("/input") as Buffer),parts=readPackage(input),reject=mode==="active-same",operations=[{operation:"model.document.Document.sections.get",receiver:ref("document"),arguments:{},resultHandle:"sections"},{operation:`model.section.Section.${storyKind}.get`,receiver:ref("sections",0),arguments:{},resultHandle:"story"},{operation:`model.section.${type}.${action==="part"?"part.get":"is_linked_to_previous.set"}`,receiver:ref("story"),arguments:action==="part"?{}:{value:true}}];
 if(route==="model"){const doc=await api.Document(input,textContext),story=Reflect.get(doc.sections[0]!,storyKind) as api._Header|api._Footer,run=()=>action==="part"?story.part:Reflect.set(story,"is_linked_to_previous",true);if(reject){expect(run).toThrowError(expect.objectContaining({code:"unsupported-edit"}));expect(doc.part.blob).toEqual(parts.get("word/document.xml"));}else{run();expect(story.is_linked_to_previous).toBe(action==="relink");await doc.save(sink);}}
 else if(route==="sdk"){const pending=api.applyStyleModelBatch(input,{version:1,operations},textContext);if(reject)await expect(pending).rejects.toMatchObject({code:"unsupported-edit",operationIndex:2});else{const batch=await pending;expect(batch.affected).toBe(action==="relink"?1:0);await batch.save(sink);}}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const result=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(result.exitCode,result.stdout+result.stderr).toBe(reject?1:0);const e=JSON.parse(result.stdout);if(reject){expect(e.errors[0]).toMatchObject({code:"unsupported-edit",operationIndex:2});expect(e.affected).toBe(0);expect(new TextDecoder().decode(await fs.readFile("/out"))).toBe("Original destination");}else memory.writeFileSync("/out",await fs.readFile("/out"));expect(await fs.readFile("/input")).toEqual(input);}finally{await shell.dispose();}}
 if(reject)expect(memory.readFileSync("/out").length).toBe(0);else{const saved=readPackage(new Uint8Array(memory.readFileSync("/out") as Buffer));assertPackageLinks(saved);const xml=new TextDecoder().decode(saved.get("word/document.xml"));expect(xml).toContain(stored);expect(xml).toContain("Retain é 日本 עברית 🌊");if(action==="part")for(const[name,bytes]of parts)expect(saved.get(name),name).toEqual(bytes);else{const dirty=new Set(["word/document.xml",...(mode==="inactive-distinct"?["word/_rels/document.xml.rels","[Content_Types].xml","word/one.xml"]:[])]);for(const[name,bytes]of parts)if(!dirty.has(name))expect(saved.get(name),name).toEqual(bytes);expect(saved.has("word/one.xml")).toBe(mode==="inactive-same");expect(saved.get("word/two.xml")).toEqual(parts.get("word/two.xml"));const rels=new TextDecoder().decode(saved.get("word/_rels/document.xml.rels"));expect(rels.includes('Id="one"')).toBe(mode==="inactive-same");expect(rels).toContain('Id="two"');}}
 expect(memory.readFileSync("/input")).toEqual(Buffer.from(input));
});
