import {expect,it} from "vitest";
import {Volume} from "memfs";
import * as api from "./index.js";
import {Shell,MemoryFileSystem} from "@poe-platform/safe-bash";
import {docxCommands} from "@poe-platform/safe-bash/commands/docx";
import {textContext,textFixture,w} from "../tests/fixtures/text.js";
import {settingsSourceCases} from "../tests/fixtures/settings-exact-source.js";
import {readPackage,assertPackageLinks,xmlStructure} from "../tests/assertions.js";
const ref=(resultHandle:string)=>({resultHandle});
type Node=ReturnType<typeof xmlStructure>;
const nodes=(n:Node):Node[]=>[n,...n.children.flatMap(c=>typeof c==="string"?[]:nodes(c))];
for(const strict of [false,true])for(const kind of ["docx","dotx"] as const)for(const c of settingsSourceCases)for(const route of ["model","sdk","shell"] as const)
it(`${route} independently executes exact settings witness R${c.row}; ${kind}; strict=${strict}`,async()=>{
 const parts=readPackage(await textFixture('<w:p><w:r><w:t>Retain é 日本 עברית 🌊</w:t></w:r></w:p><w:sectPr/>',{settings:{kind:"settings",xml:`<w:settings xmlns:w="${w}">${c.initial}</w:settings>`}},strict));if(kind==="dotx")parts.set("[Content_Types].xml",new TextEncoder().encode(new TextDecoder().decode(parts.get("[Content_Types].xml")).replace("wordprocessingml.document.main+xml","wordprocessingml.template.main+xml")));const volume=Volume.fromJSON({"/input":"","/out":""}),sink={async write(bytes:Uint8Array){volume.appendFileSync("/out",bytes);}};await api.writeArchive({comment:new Uint8Array(),members:[...parts].map(([name,bytes])=>({name,bytes,directory:false,modified:new Date("2026-01-02T03:04:06Z")}))},{async write(bytes){volume.appendFileSync("/input",bytes);}},{order:"input",compression:"store"},textContext);const input=new Uint8Array(volume.readFileSync("/input") as Buffer),operations=[{operation:"model.document.Document.settings.get",receiver:ref("document"),arguments:{},resultHandle:"settings"},...("value"in c?[{operation:"model.settings.Settings.odd_and_even_pages_header_footer.set",receiver:ref("settings"),arguments:{value:c.value}}]:[]),{operation:"model.settings.Settings.odd_and_even_pages_header_footer.get",receiver:ref("settings"),arguments:{}}];
 if(route==="model"){const doc=await api.Document(input,textContext),settings=doc.settings;expect(settings.equals(doc.settings)).toBe(true);expect(String(settings.part.partname)).toBe("/word/settings.xml");if("value"in c)settings.odd_and_even_pages_header_footer=c.value;expect(settings.odd_and_even_pages_header_footer).toBe(c.expected);await doc.save(sink);}
 else if(route==="sdk"){const batch=await api.applyStyleModelBatch(input,{version:1,operations},textContext);expect(batch.results.at(-1)!.value).toBe(c.expected);expect(batch.affected).toBe("value"in c?1:0);await batch.save(sink);}
 else{const fs=new MemoryFileSystem();await fs.writeFile("/input",input);await fs.writeFile("/out",new TextEncoder().encode("Original destination"));const shell=new Shell({fs}).use(docxCommands({engine:api.createDocxInspectionCommandEngine({limits:textContext.limits})}));try{const r=await shell.exec(`docx batch /input --ops-json '${JSON.stringify({version:1,operations})}' --output /out --force --json`);expect(r.exitCode,r.stdout+r.stderr).toBe(0);const e=JSON.parse(r.stdout);expect(e.data.results.at(-1).data).toBe(c.expected);expect(e.affected).toBe("value"in c?1:0);volume.writeFileSync("/out",await fs.readFile("/out"));expect(await fs.readFile("/input")).toEqual(input);}finally{await shell.dispose();}}
 const saved=readPackage(new Uint8Array(volume.readFileSync("/out") as Buffer));assertPackageLinks(saved);for(const[name,bytes]of parts)if(name!=="word/settings.xml"||!("value"in c))expect(saved.get(name),name).toEqual(bytes);if("value"in c){const flags=nodes(xmlStructure(saved.get("word/settings.xml")!)).filter(n=>n.name.endsWith("}evenAndOddHeaders"));expect(flags).toHaveLength(c.value?1:0);if(c.value)expect(flags[0]!.attributes).toEqual({});}expect(volume.readFileSync("/input")).toEqual(Buffer.from(input));
});
