export const readCases = [
  { name: "readonly first scalar stops with status two", before: "readonly first=old;", args: "first last", input: "one two\n", after: `printf '<%s><%s>' "$first" "$last"`, output: "2:<old><>", diagnostic: "first: readonly variable" },
  { name: "default REPLY retains whitespace", args: "", input: "  one two  \nnext\n", after: `printf '<%s>' "$REPLY"`, output: "0:<  one two  >" },
  { name: "scalar IFS trimming", args: "value", input: "  one two  \n", after: `printf '<%s>' "$value"`, output: "0:<one two>" },
  { name: "last scalar retains intervening separators", args: "first last", input: "one  two three \n", after: `printf '<%s><%s>' "$first" "$last"`, output: "0:<one><two three>" },
  { name: "missing fields assign empty", args: "first last", input: "one\n", after: `printf '<%s><%s>' "$first" "$last"`, output: "0:<one><>" },
  { name: "raw preserves backslashes", args: "-r value", input: "a\\ b\n", after: `printf '<%s>' "$value"`, output: "0:<a\\ b>" },
  { name: "escaped IFS is literal", args: "-a values", input: "a\\ b c\n", after: `printf '<%s>' "\${values[@]}"`, output: "0:<a b><c>" },
  { name: "backslash newline continues", args: "value", input: "a\\\nb\n", after: `printf '<%s>' "$value"`, output: "0:<ab>" },
  { name: "array clears old cells", before: "values=(old tail keep);", args: "-a values", input: "one two\n", after: `printf '<%s>' "\${values[@]}"`, output: "0:<one><two>" },
  { name: "empty EOF clears array", before: "values=(old tail);", args: "-a values", input: "", after: `printf 'count=%s' "\${#values[@]}"`, output: "1:count=0" },
  { name: "unterminated input still assigns", args: "-a values", input: "one two", after: `printf '<%s>' "\${values[@]}"`, output: "1:<one><two>" },
  { name: "empty delimiter ends on NUL", args: "-rd '' value", input: "a\0b\n", after: `printf '<%s>' "$value"`, output: "0:<a>" },
  { name: "ordinary NUL bytes are discarded", args: "-r value", input: "a\0b\n", after: `printf '<%s>' "$value"`, output: "0:<ab>" },
  { name: "delimiter first byte", args: "-d '::' value", input: "one:two\n", after: `printf '<%s>' "$value"`, output: "0:<one>" },
  { name: "count leaves unread tail", args: "-n2 value", input: "abcd\n", after: `read -r tail; printf '<%s><%s>' "$value" "$tail"`, output: "0:<ab><cd>" },
  { name: "signed whitespace count", args: "-n ' +2 ' value", input: "abcd\n", after: `printf '<%s>' "$value"`, output: "0:<ab>" },
  { name: "count zero assigns without consumption", before: "value=old;", args: "-n0 value", input: "abcd\n", after: `read -r tail; printf '<%s><%s>' "$value" "$tail"`, output: "0:<><abcd>" },
  { name: "exact count ignores newline and IFS", args: "-N4 value", input: " a\nbc\n", after: `printf '<%s>' "$value"`, output: "0:< a\nb>" },
  { name: "exact count remains sticky after n", args: "-N4 -n2 value", input: " a\nbc\n", after: `printf '<%s>' "$value"`, output: "0:< a>" },
  { name: "exact array is one unsplit field", args: "-N3 -a values", input: "a b\n", after: `printf '<%s>' "\${values[@]}"`, output: "0:<a b>" },
  { name: "IFS nonwhitespace empty fields", before: "IFS=:;", args: "-a values", input: ":one::two:\n", after: `printf '<%s>' "\${values[@]}"`, output: "0:<><one><><two>" },
  { name: "IFS empty array unsplit", before: "IFS=;", args: "-a values", input: "  a b  \n", after: `printf '<%s>' "\${values[@]}"`, output: "0:<  a b  >" },
  { name: "array option ignores subsequent valid names", before: "other=old;", args: "-a values other ignored", input: "a b\n", after: `printf '<%s><%s>' "\${values[*]}" "$other"`, output: "0:<a b><old>" },
  { name: "scalar assignment preserves indexed tail", before: "value=(old keep);", args: "value", input: "new\n", after: `printf '<%s>' "\${value[@]}"`, output: "0:<new><keep>" },
  { name: "readonly array consumes record and preserves cells", before: "values=(old tail); readonly values;", args: "-a values", input: "a b\nnext\n", after: `read -r tail; printf '<%s><%s>' "\${values[*]}" "$tail"`, output: "1:<old tail><next>", diagnostic: "values: readonly variable" },
  { name: "invalid array name diagnosed after read", args: "-a bad-name", input: "a b\nnext\n", after: `read -r tail; printf '<%s>' "$tail"`, output: "1:<next>", diagnostic: "read: `bad-name': not a valid identifier" },
  { name: "invalid first scalar rejected before read even with array", args: "-a values bad-name", input: "a b\nnext\n", after: `read -r tail; printf '<%s>' "$tail"`, output: "1:<a b>", diagnostic: "read: `bad-name': not a valid identifier" },
  { name: "invalid later scalar preserves prior assignment", args: "first bad-name last", input: "a b c\n", after: `printf '<%s>' "$first"`, output: "1:<a>", diagnostic: "read: `bad-name': not a valid identifier" },
] as const;

export const readUsage = "read: usage: read [-Eers] [-a array] [-d delim] [-i text] [-n nchars] [-N nchars] [-p prompt] [-t timeout] [-u fd] [name ...]\n";

export const readErrors = [
  { args: "-n $'\\u00a02'", status: 1, diagnostic: "read: \\u00A02: invalid number" },
  { args: "-u9 -u0 value", status: 1, diagnostic: "read: 9: invalid file descriptor: Bad file descriptor" },
  { args: "-Q", status: 2, diagnostic: "read: -Q: invalid option", usage: true },
  { args: "--bogus", status: 2, diagnostic: "read: --: invalid option", usage: true },
  { args: "-a", status: 2, diagnostic: "read: -a: option requires an argument", usage: true },
  { args: "-t", status: 2, diagnostic: "read: -t: option requires an argument", usage: true },
  { args: "-n -1", status: 1, diagnostic: "read: -1: invalid number" },
  { args: "-N 0x10", status: 1, diagnostic: "read: 0x10: invalid hex number" },
  { args: "-n 2147483648", status: 1, diagnostic: "read: 2147483648: invalid number" },
  { args: "-u -1", status: 1, diagnostic: "read: -1: invalid file descriptor specification" },
  { args: "-u 2147483648", status: 1, diagnostic: "read: 2147483648: invalid file descriptor specification" },
  { args: "-u9", status: 1, diagnostic: "read: 9: invalid file descriptor: Bad file descriptor" },
  { args: "-t -1", status: 1, diagnostic: "read: -1: invalid timeout specification" },
  { args: "-t 1e2", status: 1, diagnostic: "read: 1e2: invalid timeout specification" },
  { args: "-t ' 1 '", status: 1, diagnostic: "read:  1 : invalid timeout specification" },
] as const;
