export interface ErrexitCase {
  name: string;
  source?: string;
  args?: readonly string[];
  stdin?: string;
  files?: Record<string, { text: string; mode?: number }>;
}

const body = { body: { text: 'false; printf body\n' } };
export const errexitCases: readonly ErrexitCase[] = [
  { name: 'simple', source: 'set -e; false; printf BAD > marker' },
  { name: 'disable', source: 'set -e; set +e; false; printf after' },
  { name: 'flag-versus-context', source: 'f() { set -e; case $- in *e*) printf on;; esac; false; printf body; }; if f; then printf yes; fi; false; printf BAD' },
  { name: 'and-or', source: 'set -e; false && printf BAD; false || printf rescued; true && false; printf BAD' },
  { name: 'group-ignored-result', source: 'set -e; { false && true; }; printf after' },
  { name: 'function-ignored-result', source: 'set -e; f() { false && true; }; f; printf BAD' },
  { name: 'subshell-ignored-result', source: 'set -e; (false && true); printf BAD' },
  { name: 'if-body', source: 'set -e; if false; then printf BAD; elif true; then false; printf BAD; fi; printf BAD' },
  { name: 'while-until-negation', source: 'set -e; while false; do printf BAD; done; until true; do printf BAD; done; ! true; printf after' },
  { name: 'loop-body', source: 'set -e; for value in a b; do printf "$value"; false; printf BAD; done; printf BAD' },
  { name: 'loop-ignored-result', source: 'set -e; for value in a; do false && true; done; printf after' },
  { name: 'negated-function', source: 'set -e; f() { false; printf body; }; ! f; printf after' },
  { name: 'eval-tested', source: 'set -e; eval "false; printf body" || printf rescue; printf after' },
  { name: 'source-tested', source: 'set -e; . ./body || printf rescue; printf after', files: body },
  { name: 'source-normal', source: 'set -e; . ./body; printf BAD', files: body },
  { name: 'source-enables-option', source: '. ./body || true; case ${-} in *e*) printf on;; esac; false; printf BAD', files: { body: { text: 'set -e; false; printf body\n' } } },
  { name: 'source-disables-option', source: 'set -e; . ./body; false; printf after', files: { body: { text: 'set +e; false; printf body\n' } } },
  { name: 'eval-enables-option', source: 'eval "set -e; false; printf body" || true; false; printf BAD' },
  { name: 'subshell-normal', source: 'set -e; (false; printf BAD); printf BAD' },
  { name: 'subshell-tested', source: 'set -e; (false; printf body) || printf rescue; printf after' },
  { name: 'subshell-option-isolation', source: '(set -e; false; printf BAD); false; printf after' },
  { name: 'substitution-default', source: 'set -e; value=$(false; printf body); printf "value=%s" "$value"' },
  { name: 'substitution-tested', source: 'set -e; value=$(false; printf body) || printf rescue; printf "value=%s" "$value"' },
  { name: 'substitution-enable', source: 'value=$(set -e; false; printf BAD); printf "status=%s value=%s" "$?" "$value"' },
  { name: 'substitution-tested-enable', source: 'value=$(set -e; false; printf body) || printf rescue; printf "value=%s" "$value"' },
  { name: 'substitution-command-status', source: 'set -e; printf "value=%s" "$(false)"; printf after' },
  { name: 'backtick-inheritance', source: 'set -e; value=`false; printf body`; printf "value=%s" "$value"' },
  { name: 'pipeline-stage', source: 'set -e; { false; printf BAD > marker; } | cat; printf after' },
  { name: 'pipeline-pipefail', source: 'set -e; set -o pipefail; { false; printf BAD > marker; } | cat; printf BAD' },
  { name: 'pipeline-tested', source: 'set -e; { false; printf body; } | cat || printf rescue; printf after' },
  { name: 'pipeline-last', source: 'set -e; printf data | { cat; false; printf BAD; }; printf BAD' },
  { name: 'pipeline-disable', source: 'set -e; set -o pipefail; set +o pipefail; false | cat; printf after' },
  { name: 'exit-tested', source: 'set -e; f() { exit 7; }; if f; then printf BAD; fi; printf BAD' },
  { name: 'return-tested', source: 'set -e; f() { return 7; }; if f; then printf BAD; fi; printf after' },
  { name: 'return-untested', source: 'set -e; f() { return 7; }; f; printf BAD' },
  { name: 'source-return', source: 'set -e; . ./body; printf BAD', files: { body: { text: 'return 7; printf BAD\n' } } },
  { name: 'new-bash-reset', source: 'set -e; bash -c "false; printf child"; printf after' },
  { name: 'new-bash-tested', source: 'set -e; bash -ec "false; printf BAD" || printf rescue; printf after' },
  { name: 'new-sh-tested', source: 'set -e; sh -ec "false; printf BAD" || printf rescue; printf after' },
  { name: 'headerless-reset', source: 'set -e; ./script; printf after', files: { script: { text: 'false; printf child\n', mode: 0o755 } } },
  { name: 'parent-options', source: 'set -- parent; set -e; bash -c "set +e; false" || true; printf "%s:" "$1"; case $- in *e*) printf on;; esac; false; printf BAD' },
  { name: 'arithmetic-status', source: 'set -e; ((0)); printf BAD' },
  { name: 'set-ordered', source: 'set -- old; set -ee +e -e -- "" -arg; printf "[%s][%s]" "$1" "$2"; false; printf BAD' },
  { name: 'set-alias', source: 'set -o errexit; set +o errexit; false; printf after' },
  { name: 'option-ec', args: ['-ec', 'printf "%s:%s:" "$0" "$1"; false; printf BAD', 'named', ''] },
  { name: 'option-ce', args: ['-ce', 'false; printf BAD', 'shell'] },
  { name: 'option-after-c', args: ['-c', '-e', 'false; printf BAD', 'shell'] },
  { name: 'option-ordered', args: ['-e', '+ee', '-c', 'false; printf after', 'shell'] },
  { name: 'stdin-es', args: ['-es', '--', '-arg'], stdin: 'printf "arg=%s:" "$1"\nfalse\nprintf BAD\n' },
  { name: 'stdin-default-e', args: ['-e'], stdin: 'printf before\nfalse\nprintf BAD\n' },
  { name: 'stdin-cursor', args: ['-es'], stdin: 'read -r value\npayload\nprintf "%s" "$value"\nfalse\nprintf BAD\n' },
  { name: 'file-e', args: ['-e', './body', '', '-arg'], files: { body: { text: 'printf "[%s][%s]" "$1" "$2"; false; printf BAD\n' } } },
  { name: 'file-plus-e', args: ['-e', '+e', '--', './body'], files: body },
  { name: 'file-terminator', args: ['-e', '-', './body'], files: body },
];
