import type { ClosureCase } from "./invocation-closure-cases.js";

export const shCases: readonly ClosureCase[] = [
  { name: "special colon persists", source: 'VALUE=old; VALUE=new :; printf "%s\\n" "$VALUE"' },
  { name: "regular true temporary", source: 'VALUE=old; VALUE=new true; printf "%s\\n" "$VALUE"' },
  { name: "special export prefix", source: 'VALUE=old; VALUE=new export OTHER=ok; printf "%s:%s\\n" "$VALUE" "$OTHER"' },
  { name: "command export prefix temporary", source: 'VALUE=old; VALUE=new command export OTHER=ok; printf "%s:%s\\n" "$VALUE" "$OTHER"' },
  { name: "export explicit prefix", source: 'VALUE=old; VALUE=new command export VALUE; printf "%s\\n" "$VALUE"' },
  { name: "special unset prefix", source: 'VALUE=old; VALUE=new unset VALUE; printf "%s\\n" "${VALUE-unset}"' },
  { name: "command unset explicit prefix", source: 'VALUE=old; VALUE=new command unset VALUE; printf "%s\\n" "${VALUE-unset}"' },
  { name: "special shift prefix", source: 'VALUE=old; set -- arg; VALUE=new shift 0; printf "%s:%s\\n" "$VALUE" "$1"' },
  { name: "command colon temporary", source: 'VALUE=old; VALUE=new command :; printf "%s\\n" "$VALUE"' },
  { name: "function temporary prefix", source: 'VALUE=old; fun() { printf "in:%s\\n" "$VALUE"; VALUE=inside; }; VALUE=new fun; printf "out:%s\\n" "$VALUE"' },
  { name: "function inherited profile", source: 'VALUE=old; fun() { VALUE=new :; }; fun; printf "%s\\n" "$VALUE"' },
  { name: "local inherited profile", source: 'VALUE=old; fun() { local VALUE=local; VALUE=new :; printf "in:%s\\n" "$VALUE"; }; fun; printf "out:%s\\n" "$VALUE"' },
  { name: "subshell profile isolated", source: 'VALUE=old; ( VALUE=new :; printf "in:%s\\n" "$VALUE" ); printf "out:%s\\n" "$VALUE"' },
  { name: "substitution profile isolated", source: 'VALUE=old; RESULT=$(VALUE=new :; printf "%s" "$VALUE"); printf "%s:%s\\n" "$RESULT" "$VALUE"' },
  { name: "ordinary read prefix temporary", stdin: "xy", source: 'VALUE=old; VALUE=new read -n1 other; printf "%s:%s\\n" "$VALUE" "$other"' },
  { name: "special exit status", source: "VALUE=new exit 23" },
  { name: "readonly discovery", source: "readonly VALUE=old; command -v readonly; type -t readonly" },
  { name: "readonly special assignment", source: 'readonly VALUE=old; VALUE=new :; printf "after:%s:%s\\n" "$?" "$VALUE"' },
  { name: "readonly ordinary assignment", source: 'readonly VALUE=old; VALUE=new true; printf "after:%s:%s\\n" "$?" "$VALUE"' },
  { name: "readonly alone assignment", source: 'readonly VALUE=old; VALUE=new; printf "after\\n"' },
  { name: "readonly unset", source: 'readonly VALUE=old; unset VALUE; printf "after:%s:%s\\n" "$?" "$VALUE"' },
  { name: "command readonly unset", source: 'readonly VALUE=old; command unset VALUE; printf "after:%s:%s\\n" "$?" "$VALUE"' },
  { name: "readonly read cursor", stdin: "ab", source: 'readonly VALUE=old; read -n1 VALUE; printf "after:%s:%s\\n" "$?" "$VALUE"; read -n1 tail; printf "tail:%s\\n" "$tail"' },
  { name: "readonly local expires", source: 'VALUE=old; fun() { local VALUE=local; readonly VALUE; }; fun; VALUE=new; printf "%s\\n" "$VALUE"' },
  { name: "invalid export fatal", source: 'export bad-name; printf "after:%s\\n" "$?"' },
  { name: "command invalid export not fatal", source: 'command export bad-name; printf "after:%s\\n" "$?"' },
  { name: "special function definition", source: 'export() { printf "function\\n"; }; export; printf "after\\n"' },
  { name: "readonly multi read", stdin: "abcZ", source: 'first=old; second=old; third=old; readonly second; read -N3 first second third; printf "<%s>|<%s>|<%s>:%s\\n" "$first" "$second" "$third" "$?"; IFS= read -r tail; printf "tail:%s\\n" "$tail"' },
  { name: "special redirection fatal", source: 'VALUE=new : <missing; printf "after\\n"' },
  { name: "command redirection not fatal", source: 'VALUE=new command : <missing; printf "after\\n"' },
  { name: "readonly redirection effects", source: 'readonly VALUE=old; VALUE=new : >marker; printf "after:%s\\n" "$?"' },
  { name: "special redirected assignment", source: 'VALUE=old; VALUE=new : >marker; printf "%s\\n" "$VALUE"' },
  { name: "redirect expansion before prefix", source: 'FILE=old; FILE=new : >"$FILE"; printf "%s\\n" "$FILE"' },
  { name: "ordinary readonly redirection", source: 'readonly VALUE=old; VALUE=new true >marker; printf "after:%s\\n" "$?"' },
  { name: "assignment-only readonly redirection", source: 'readonly VALUE=old; VALUE=new >marker; printf "after:%s\\n" "$?"' },
];
