export interface SubstringCase { name: string; source: string; files?: Record<string, string>; byteFragment?: boolean }
const slice = (expression: string): string => `VALUE=abcdef; printf '<%s>' "${expression}"`;
export const substringCases: SubstringCase[] = [
  { name: "handoff-scalar", source: 'VALUE=abcabc; printf "%s:%s:%s:%s" "${#VALUE}" "${VALUE:1:3}" "${MISSING:-default}" "${VALUE:+set}"' },
  ...[
    ["offset-length", "${VALUE:1:3}"], ["tail", "${VALUE:2}"], ["empty-offset", "${VALUE::2}"],
    ["empty-length", "${VALUE:2:}"], ["both-empty", "${VALUE::}"], ["offset-empty-tail", "${VALUE:}"],
    ["negative-offset", "${VALUE: -2}"], ["negative-length", "${VALUE:1:-1}"],
    ["both-negative", "${VALUE: -4:-1}"], ["past-end", "${VALUE:99:3}"],
    ["before-start", "${VALUE: -99:3}"], ["at-end", "${VALUE:6:2}"],
    ["zero-length", "${VALUE:1:0}"], ["large-offset", "${VALUE:9007199254740993:2}"],
    ["large-length", "${VALUE:1:9007199254740993}"], ["overflow-arithmetic", "${VALUE:18446744073709551617:2}"],
    ["default-not-negative-offset", "${VALUE:-2}"], ["ternary-offset", "${VALUE:1?2:3:2}"],
    ["ternary-parentheses", "${VALUE:(1 ? 2 : 3):(0 ? 1 : 2)}"],
    ["nested-ternary", "${VALUE:0?1:1?2:3:2}"], ["arithmetic-expansion", "${VALUE:$((1+1)):2}"],
  ].map(([name, expression]) => ({ name: name!, source: slice(expression!) })),
  { name: "arithmetic-variables", source: 'VALUE=abcdef; OFFSET=1; LENGTH=2; printf "%s" "${VALUE:OFFSET+1:LENGTH*2}"' },
  { name: "arithmetic-side-effects", source: 'VALUE=abcdef; INDEX=1; printf "%s:%s" "${VALUE:INDEX++:++INDEX}" "$INDEX"' },
  { name: "value-snapshot", source: 'VALUE=abcdef; printf "%s:%s" "${VALUE:(VALUE=123,1):2}" "$VALUE"' },
  { name: "nested-parameter", source: 'VALUE=abcdef; printf "%s" "${VALUE:${OFFSET:-1}:${LENGTH:-2}}"' },
  { name: "nested-default", source: 'VALUE=abcdef; printf "%s" "${MISSING:-${VALUE:1:3}}"' },
  { name: "command-expansion-order", source: 'VALUE=abcdef; printf "%s" "${VALUE:$(printf offset >marker; printf 1):$(printf length >>marker; printf 2)}"' },
  { name: "out-of-range-skips-length", source: 'VALUE=abc; INDEX=0; printf "<%s>:%s" "${VALUE:99:INDEX++}" "$INDEX"' },
  { name: "negative-range-skips-length", source: 'VALUE=abc; INDEX=0; printf "<%s>:%s" "${VALUE: -99:INDEX++}" "$INDEX"' },
  { name: "end-evaluates-length", source: 'VALUE=abc; INDEX=0; printf "<%s>:%s" "${VALUE:3:INDEX++}" "$INDEX"' },
  { name: "unset-skips-arithmetic", source: 'unset VALUE; INDEX=0; printf "<%s>:%s" "${VALUE:INDEX++:++INDEX}" "$INDEX"' },
  { name: "empty-evaluates-arithmetic", source: 'VALUE=; INDEX=0; printf "<%s>:%s" "${VALUE:INDEX++:++INDEX}" "$INDEX"' },
  { name: "quoted-fields", source: 'VALUE="a b c"; printf "<%s>" "${VALUE:1:3}" ${VALUE:1:3}' },
  { name: "unquoted-glob", source: 'VALUE="a*"; printf "<%s>" ${VALUE:1} "${VALUE:1}"', files: { first: "keep", second: "keep" } },
  { name: "positional-one", source: 'set -- abcdef; printf "%s" "${1:1:3}"' },
  { name: "positional-ten", source: 'set -- a b c d e f g h i abcdef; printf "%s" "${10:1:3}"' },
  { name: "positional-zero", source: 'printf "%s" "${0:1:2}"' },
  { name: "function-state", source: 'slice() { local INDEX=1; printf "%s:%s" "${1:INDEX++:2}" "$INDEX"; }; INDEX=9; slice abcdef; printf ":%s" "$INDEX"' },
  { name: "substitution-state", source: 'VALUE=abcdef; INDEX=1; result=$(printf "%s" "${VALUE:INDEX++:2}"); printf "%s:%s" "$result" "$INDEX"' },
  { name: "offset-division-fatal", source: 'VALUE=abc; printf before >before; printf "%s" "${VALUE:1/0:$(printf forbidden >after)}"; printf wrong' },
  { name: "length-division-fatal", source: 'VALUE=abc; printf before >before; printf "%s" "${VALUE:1:1/0}"; printf wrong' },
  { name: "negative-end-fatal", source: 'VALUE=abc; printf before >before; printf "%s" "${VALUE:2:-10}"; printf wrong' },
  { name: "arithmetic-syntax-fatal", source: 'VALUE=abc; printf before >before; printf "%s" "${VALUE:1+:2}"; printf wrong' },
  { name: "substitution-fatal-scope", source: 'VALUE=abc; result=$(printf "%s" "${VALUE:1:1/0}"; printf wrong); printf "<%s>:%s" "$result" "$?"' },
  { name: "utf8-full-first", source: 'VALUE="é🙂Z"; printf "%s" "${VALUE:0:2}"' },
  { name: "utf8-full-middle", source: 'VALUE="é🙂Z"; printf "%s" "${VALUE:2:4}"' },
  { name: "utf8-last", source: 'VALUE="é🙂Z"; printf "%s" "${VALUE: -1}"' },
  { name: "utf8-fragment", source: 'VALUE="é🙂Z"; printf "%s" "${VALUE:1:1}"', byteFragment: true },
  { name: "utf8-negative-fragment", source: 'VALUE="é🙂Z"; printf "%s" "${VALUE: -2:1}"', byteFragment: true },
];
