import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const base=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash';
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
function read(file,max=8388608){const before=fs.lstatSync(file);assert(before.isFile()&&!before.isSymbolicLink()&&before.size<=max);const bytes=fs.readFileSync(file);assert.equal(bytes.length,before.size);const after=fs.lstatSync(file);for(const key of ['ino','dev','mtimeMs','size'])assert.equal(before[key],after[key]);return bytes;}
const rows=JSON.parse(read(base+'/ALL-INPUTS.json')),normative=JSON.parse(read(base+'/NORMATIVE-INPUTS.json'));
function body(row){assert(row);const bytes=Buffer.from(row.body,'base64');assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),row.oid);return bytes;}
for(const row of [...rows,...normative])body(row);
const actualPrefix='6b4ca17046a6f86b1947df28cd5bbdb876c9031f:tests/compatibility/bash-ere-native-reference-20260829/preflight-v2/actual-v1/';
const actual=rows.filter(row=>row.spec.startsWith(actualPrefix));const raw=name=>body(actual.find(row=>row.spec===actualPrefix+name));const json=name=>JSON.parse(raw(name));
assert.equal(sha(raw('FINAL-SEAL.json')),'1bb8ab78a65d8e85b7624b2dafb00fdc74ce19a7ed70a4cbe16ad72c96a604fc');assert.equal(sha(raw('OBSERVATIONS.json')),'d77e2767f6b36a9ec710224ef31faa53ec388304b5616a4818e18657bf1cb274');
const seal=json('FINAL-SEAL.json'),observations=json('OBSERVATIONS.json'),preflight=json('PREFLIGHT.json'),tool=json('TOOL-RETURN.json'),results=json('runtime/RESULTS.json');
const memberNames=new Set();for(const item of seal.files){assert(!memberNames.has(item.path));memberNames.add(item.path);const bytes=raw(item.path);assert.equal(bytes.length,item.bytes);assert.equal(sha(bytes),item.sha256);}
const exclusions=actual.map(row=>row.spec.slice(actualPrefix.length)).filter(name=>!memberNames.has(name)).sort();assert.deepEqual(exclusions,['FINAL-SEAL.json','raw/seal.stderr','raw/seal.stdout']);assert.equal(raw('raw/seal.stderr').length,0);const sealCapture=JSON.parse(raw('raw/seal.stdout').toString().trim());assert.equal(sealCapture.finalSealSha256,sha(raw('FINAL-SEAL.json')));assert.equal(sealCapture.observationsSha256,sha(raw('OBSERVATIONS.json')));
const inherited=JSON.parse(body(rows.find(row=>row.spec.endsWith('/resolved-slot-v1/AUTHORITY-INPUTS.json'))));for(const row of inherited)body(row);
const sourceBytes=name=>body(inherited.find(row=>row.spec.endsWith('/materialized/'+name)));const source=name=>JSON.parse(sourceBytes(name));
const sourceSeal=source('PRESEAL.json'),requests=source('REQUESTS.json'),cohort=source('COHORT.json'),protocol=source('PROTOCOL.json'),tools=source('TOOLS.json'),grant=source('GO.json'),receipt=source('REVIEW-ACCEPTANCE.json');
assert.equal(sha(sourceBytes('PRESEAL.json')),seal.presealSha256);assert.equal(sha(sourceBytes('GO.json')),preflight.grantSha256);assert.equal(preflight.grantSha256,'9eec9e95250998fc3bf78ee8727bbfbbba6d32c7aab42155291a5cea34a753ec');assert.equal(sha(sourceBytes('REVIEW-ACCEPTANCE.json')),'644630c96f3cdc647aabd9f21cf6c660d2c982fd75b0d8b33c61b241168e2476');assert.equal(receipt.reviewCommit,'f5d9e55ec3f3643904f1ec51d1cfa110b6a6dea8');
const slot=JSON.parse(body(rows.find(row=>row.spec.endsWith('/resolved-slot-v1/RESULT.json'))));assert.equal(slot.decision,'ACCEPT');assert.equal(slot.grantSha256,preflight.grantSha256);assert.equal(slot.commandUtf8Sha256,tool.commandStringSha256);assert.equal(tool.commandStringSha256,'9423c7e1d4bbbc6c77bef3962bfe97b93fe333f65263cb2f4df12f555a239e25');assert.equal(preflight.commandStringSha256,tool.commandStringSha256);assert.equal(preflight.reviewCommit,'a1d03bcb9be30b60b784b25abe510a7e2a23c9eb');assert.equal(tool.reportedExitCode,0);assert.equal(tool.sandboxPermissions,'require_escalated');assert.equal(tool.login,false);assert.equal(tool.prefixRule,'ABSENT');assert.equal(tool.attempts,1);assert.equal(tool.retry,false);
assert.equal(preflight.deadline,preflight.started+600000);assert.equal(grant.deadlineEpochMs,Date.parse('2026-08-29T10:46:09.884Z'));assert(preflight.started+600000<=grant.deadlineEpochMs);assert.equal(seal.actualDeadline,preflight.deadline);assert.equal(observations.actualDeadline,preflight.deadline);assert(Date.parse(seal.at)<=preflight.deadline);assert(Date.parse(observations.at)<=preflight.deadline);
const expectedTools=[...tools.toolPins,tools.environmentLauncher,tools.wrapperTool];for(const collection of [preflight.tools,seal.toolAfter]){assert.equal(collection.length,4);for(const pin of expectedTools){const observed=collection.find(item=>item.path===pin.path);assert(observed);for(const key of ['bytes','mode','sha256'])assert.equal(observed[key],pin[key]);assert(Date.parse(observed.at)<=preflight.deadline);}}
const journalBytes=raw('runtime/JOURNAL.jsonl');assert(journalBytes.at(-1)===10);const journal=journalBytes.toString('utf8').slice(0,-1).split('\n').map(line=>JSON.parse(line));assert.equal(journal.length,37);const start=journal[0];assert.equal(start.event,'AUTHENTICATED_START');assert.equal(results.deadline,Math.min(grant.deadlineEpochMs,start.started+600000));assert(start.started>=preflight.started&&start.started+600000<=grant.deadlineEpochMs);
assert.equal(results.completed,12);assert.equal(results.halted,false);assert.deepEqual(results.notStarted,[]);assert.equal(results.ledger.starts,13);assert.equal(results.ledger.confirmedStarts,13);assert.equal(results.ledger.active,1);assert.equal(results.ledger.activeConfirmed,1);assert.equal(results.ledger.peakCharged,2);assert.equal(results.ledger.sourceForkReservations,0);assert.equal(results.osContainment,false);
assert.equal(cohort.cases.length,12);assert.equal(cohort.fixtures.length,0);assert.equal(requests.length,12);assert.equal(observations.observations.length,12);assert.deepEqual(observations.qualificationErrors,[]);
const rawManifest=observations.files;assert.equal(rawManifest.length,40);assert.equal(new Set(rawManifest.map(item=>item.path)).size,40);let runtimeBytes=0;for(const item of rawManifest){const bytes=raw('runtime/'+item.path);assert.equal(bytes.length,item.bytes);assert.equal(sha(bytes),item.sha256);runtimeBytes+=bytes.length;}assert.equal(runtimeBytes,52128);assert.equal(runtimeBytes,observations.runtimeBytes);assert.deepEqual(actual.filter(row=>row.spec.startsWith(actualPrefix+'runtime/')).map(row=>row.spec.slice((actualPrefix+'runtime/').length)).sort(),rawManifest.map(item=>item.path).sort());
function framed(bytes,id,status){const fields=[];let previous=0;for(let offset=0;offset<bytes.length;offset++){if(bytes[offset]===0){fields.push(bytes.subarray(previous,offset));previous=offset+1;}}assert.equal(previous,bytes.length,'NO_UNFRAMED_TAIL');assert.equal(fields.length,16,'EXACT16_NO_EXTRA_OR_DROPPED_FIELDS');const ascii=index=>{assert(fields[index].every(byte=>byte<128));return fields[index].toString('ascii');};assert.equal(ascii(0),'EREOBS1');assert.equal(ascii(1),id);assert.equal(ascii(2),String(status));assert(/^[0-4]$/.test(ascii(3)));const cardinality=Number(ascii(3)),slots=[];for(let index=0;index<4;index++){const offset=4+index*3;assert.equal(ascii(offset),String(index));assert(['0','1'].includes(ascii(offset+1)));const present=ascii(offset+1)==='1',value=fields[offset+2];if(!present)assert.equal(value.length,0);slots.push({index,shellSlotPresent:present,bytes:value.length,base64:value.toString('base64')});}assert.equal(slots.filter(item=>item.shellSlotPresent).length,cardinality);return{regexStatus:status,cardinality,slots,stdoutSha256:sha(bytes),hiddenNativeSpans:'UNOBSERVABLE',nativeParticipationFromEmptyString:'NOT_INFERRED'};}
function capture(item,bytes){assert.deepEqual([item.flush,item.size,item.hash,item.close],[true,true,true,true]);assert.equal(item.bytes,bytes.length);assert.equal(item.sha256,sha(bytes));assert.equal(item.base64,bytes.toString('base64'));assert(bytes.length<=65536);}
const decoded=[],pids=new Set();let previousFinished=start.started;
for(let index=0;index<12;index++){const id='N'+String(index+1).padStart(2,'0'),row=json('runtime/'+id+'.json'),reported=observations.observations[index],request=requests[index],literal=cohort.cases[index],expectedStatus=index<10?0:index===10?1:2;assert.equal(row.id,id);assert.equal(row.status,expectedStatus);assert.equal(row.signal,null);assert.equal(row.stop,null);assert.deepEqual(row.errors,[]);assert.deepEqual(row.signals,[]);assert.equal(row.exit,true);assert.equal(row.close,true);assert.equal(row.retired,true);assert.equal(row.spawnObserved,true);assert.equal(row.stdinFinished,true);assert.equal(row.streamEOF,null);assert.equal(row.filesVerified,true);assert.equal(row.receiptPublished,false);assert.equal(row.regularCaptureCompletion,true);assert(!pids.has(row.pid));pids.add(row.pid);assert(row.started>=previousFinished&&row.finished>=row.started&&row.finished<=preflight.deadline);assert(row.finished-row.started<3000);previousFinished=row.finished;assert.equal(row.group.state,'absent');assert.equal(row.group.error.fields.code.presence,'value');assert.equal(row.group.error.fields.code.value,'ESRCH');assert(row.groupObservations.length>=1);for(const group of row.groupObservations){assert.equal(group.state,'absent');assert.equal(group.afterKill,false);assert(group.at>=row.started&&group.at<=row.finished);}assert.deepEqual(row.filesBefore,row.filesAfter);assert.deepEqual(row.filesBefore.map(item=>item.path),['empty-path','home','tmp','work']);
 const enrolled=journal[1+index*3],terminal=journal[2+index*3],credit=journal[3+index*3];assert.equal(enrolled.event,'CHILD_ENROLLED');assert.equal(enrolled.id,id);assert.equal(enrolled.executable,'/bin/bash');assert.deepEqual(enrolled.args,request.argv);assert.equal(terminal.event,'CHILD_TERMINAL');assert.equal(terminal.row.id,id);assert.equal(terminal.row.receiptPublished,false);assert.equal(terminal.row.filesVerified,false);assert.equal(credit.event,'OBSERVATION_READY_FOR_CREDIT');assert.equal(credit.id,id);
 assert.equal(literal.expectedNative,null);assert.equal(literal.stdinBase64,'');assert.equal(request.stdinBase64,'');assert.equal(literal.id,id);assert.equal(request.id,id);assert.equal(sha(Buffer.from(literal.program)),literal.programSha256);assert(sourceBytes('programs/'+id+'.bash.data').equals(Buffer.from(literal.program)));assert.deepEqual(request.argv,['--noprofile','--norc','-c',literal.program,'ere-capture-case']);const caseRoot=protocol.runRoot+'/cases/'+id;assert.equal(request.cwd,caseRoot+'/work');assert.deepEqual(request.environment,{LC_ALL:'C',LANG:'C',TZ:'UTC',HOME:caseRoot+'/home',TMPDIR:caseRoot+'/tmp',PATH:caseRoot+'/empty-path'});
 const stdout=raw('runtime/captures/'+id+'/stdout'),stderr=raw('runtime/captures/'+id+'/stderr');assert.equal(stderr.length,0);assert.equal(row.capture.length,2);capture(row.capture[0],stdout);capture(row.capture[1],stderr);assert.equal(row.capture[0].name,'stdout');assert.equal(row.capture[1].name,'stderr');const observed=framed(stdout,id,row.status);assert.deepEqual(observed,row.observation);assert.deepEqual(observed,reported.observation);assert.equal(reported.sourceReceiptPublishedField,false);assert.equal(reported.receiptFileSha256,sha(raw('runtime/'+id+'.json')));assert.deepEqual(reported.errors,[]);const values=observed.slots.filter(item=>item.shellSlotPresent).map(item=>{const bytes=Buffer.from(item.base64,'base64');assert(bytes.every(byte=>byte<128));return bytes.toString('ascii');});decoded.push({id,pattern:literal.pattern,subject:literal.subject,status:row.status,cardinality:observed.cardinality,values,slots:observed.slots,stdoutBytes:stdout.length,stdoutSha256:sha(stdout),stderrBytes:stderr.length,stderrSha256:sha(stderr),started:row.started,finished:row.finished,receiptPublishedStored:false,creditCorroborated:true});}
assert.deepEqual(observations.credits,decoded.map(item=>item.id));for(const item of results.outer)capture(item,raw('runtime/outer/bootstrap.'+item.name));assert.equal(seal.semanticPassCount,null);assert.equal(seal.knownDirectStartsIncludingCommit,35);assert.equal(seal.conservativeExecutableRoleCharge,36);assert.equal(seal.knownPeak,3);assert.equal(seal.attempt,'CONSUMED_NO_RETRY');assert.equal(seal.combinedObservedCaptureBytes,seal.adminCaptureBytes+runtimeBytes);
const liveRoot='/private/tmp/safe-bash-ere-native-observations-20260829-v1';const liveFiles=[],liveDirectories=[];function visit(directory,prefix=''){for(const name of fs.readdirSync(directory)){const filename=directory+'/'+name,relative=prefix+name,stat=fs.lstatSync(filename);assert(!stat.isSymbolicLink());assert(liveFiles.length+liveDirectories.length<512);if(stat.isDirectory()){liveDirectories.push({path:relative,mode:stat.mode&511});visit(filename,relative+'/');}else{assert(stat.isFile()&&stat.nlink===1&&stat.size<65536);const pin=rawManifest.find(item=>item.path===relative);assert(pin,'UNEXPECTED_LIVE_RUNTIME_FILE');const bytes=read(filename,65536);assert.equal(stat.mode&511,pin.mode);assert(bytes.equals(raw('runtime/'+relative)));liveFiles.push(relative);}}}visit(liveRoot);assert.deepEqual(liveFiles.sort(),rawManifest.map(item=>item.path).sort());assert.equal(liveDirectories.length,75);assert.deepEqual(liveDirectories.sort((left,right)=>left.path<right.path?-1:left.path>right.path?1:0),[...observations.directories].sort((left,right)=>left.path<right.path?-1:left.path>right.path?1:0));
for(const item of sourceSeal.files){const bytes=sourceBytes(item.path);assert.equal(sha(bytes),item.sha256);assert.equal(bytes.length,item.bytes);const live=repo+'/tests/compatibility/bash-ere-native-reference-20260829/preflight-v2/materialized/'+item.path;assert(read(live,1048576).equals(bytes));}
const model=JSON.parse(body(normative.find(row=>row.relative==='SUMMARY.json'))),sourceModel=JSON.parse(body(rows.find(row=>row.spec.endsWith('/authority-v1/SOURCE-DATA.json'))));assert.equal(sha(body(normative.find(row=>row.relative==='SUMMARY.json'))),sourceModel.inputs.find(item=>item.path==='SUMMARY.json').sha256);
const comparisons=[];for(let index=0;index<6;index++){const current=decoded[index],earlier=model.layouts[0].observations.find(item=>item.pattern===current.pattern&&item.subject===current.subject);assert(earlier);const projected=earlier.expected.map(span=>span===null?'':current.subject.slice(span[0],span[1]));assert.deepEqual(current.values,projected);assert.notDeepEqual(current.values,earlier.observed.values);for(const layout of model.layouts){const same=layout.observations.find(item=>item.pattern===current.pattern&&item.subject===current.subject);assert.deepEqual(same.expected,earlier.expected);assert.deepEqual(same.observed.values,earlier.observed.values);}comparisons.push({id:current.id,originalFailureId:sourceModel.failures[0].ids[index],nativeVisibleValues:current.values,documentedModelVisibleProjection:projected,priorEngineValues:earlier.observed.values,visibleResetWitness:true,nativeSpans:'UNKNOWN_NOT_DERIVED',originalFailuresUnrescored:true});}
assert.deepEqual(decoded[6].values,['ba','a','a','']);assert.deepEqual(sourceModel.authorE12.values,['aba','a','b']);assert.notDeepEqual(decoded[0].values,sourceModel.authorE12.values);assert.deepEqual(decoded[8].values,decoded[9].values);assert.equal(decoded[10].cardinality,0);assert.equal(decoded[11].cardinality,0);
const commitStdout=fs.openSync(base+'/commit.stdout','wx',0o600),commitStderr=fs.openSync(base+'/commit.stderr','wx',0o600);const result=spawnSync('/usr/bin/git',['cat-file','commit','6b4ca17046a6f86b1947df28cd5bbdb876c9031f'],{cwd:repo,env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_OPTIONAL_LOCKS:'0'},stdio:['ignore',commitStdout,commitStderr],timeout:30000});for(const fd of [commitStdout,commitStderr]){fs.fsyncSync(fd);assert(fs.fstatSync(fd).size<65536);fs.closeSync(fd);}fs.writeFileSync(base+'/COMMIT-PROCESS.json',JSON.stringify({pid:result.pid,status:result.status,signal:result.signal,closed:result.status!==null},null,2)+'\n',{flag:'wx'});assert(result.status===0&&result.signal===null&&!result.error);const commit=read(base+'/commit.stdout',65536);assert.equal(createHash('sha1').update(`commit ${commit.length}\0`).update(commit).digest('hex'),'6b4ca17046a6f86b1947df28cd5bbdb876c9031f');const match=/^committer .+ (\d+) [+-]\d{4}$/m.exec(commit.toString());assert(match);const commitTime=Number(match[1])*1000;assert(commitTime<=preflight.deadline);
const manifest={schema:'ere12-independent-actual-audit-bindings-v1',actualCommit:'6b4ca17046a6f86b1947df28cd5bbdb876c9031f',observationManifestSha256:sha(raw('OBSERVATIONS.json')),finalSealSha256:sha(raw('FINAL-SEAL.json')),sourceSealSha256:sha(sourceBytes('PRESEAL.json')),grantSha256:preflight.grantSha256,commandSha256:tool.commandStringSha256,allActualInputs:actual.map(({spec,oid,bytes,sha256})=>({path:spec.slice(actualPrefix.length),oid,bytes,sha256})),sealExclusions:exclusions.map(name=>({path:name,sha256:sha(raw(name)),binding:'actual Git commit; FINAL-SEAL self and active publisher captures excluded from recursive seal'})),normativeInputs:normative.map(({relative,oid,bytes,sha256})=>({path:relative,oid,bytes,sha256})),decoded,comparisons,reference:{path:'/bin/bash',sha256:tools.toolPins[1].sha256,version:'3.2.57 from inherited metadata; no fresh probe',gnu53:false},timing:{actualPreflightStart:new Date(preflight.started).toISOString(),outerActualDeadline:new Date(preflight.deadline).toISOString(),ownerStarted:new Date(start.started).toISOString(),ownerRuntimeDeadline:new Date(results.deadline).toISOString(),readbackAt:observations.at,sealAt:seal.at,commitTimestamp:new Date(commitTime).toISOString(),grantExpiry:new Date(grant.deadlineEpochMs).toISOString(),dualClockDifferenceMs:results.deadline-preflight.deadline},accounting:{runtimeFiles:40,runtimeDirectories:75,runtimeBytes,rawStdoutBytes:decoded.reduce((sum,item)=>sum+item.stdoutBytes,0),rawStderrBytes:0,managedStarts:13,managedPeak:2,knownDirectStartsReported:35,conservativeExecutableRolesReported:36,universalOsCensus:false,ownerFinalActiveAtPreExitReceipt:1,ownerExitEvidence:'agent-recorded tool exit0 plus ROOT attestation, not direct OS exit observation by auditor'},preserved:{originalR01Failures:7,I23OriginalChecks:62,I23OriginalContradictions:52,E12OriginalValues:sourceModel.authorE12.values,N11PriorNonemptyStateTested:false,N12PriorNonemptyStateTested:false,toolApprovalUnobservedByAuditor:true,attemptConsumed:true}};
fs.writeFileSync(base+'/AUDIT-BINDINGS.json',JSON.stringify(manifest,null,2)+'\n',{flag:'wx'});assert(Date.now()<Date.parse('2026-08-29T10:44:40.736Z'));const outcome={schema:'ere12-independent-native-observation-audit-v1',decision:'QUALIFIED_OBSERVATION_ORACLE_ACCEPT',at:new Date().toISOString(),observations:12,semanticPasses:null,sourceOnlyModelComparisons:6,designatedI23Witness:'N07 ba only; larger62-input property unqualified',observationManifestSha256:manifest.observationManifestSha256,finalSealSha256:manifest.finalSealSha256,auditBindingsSha256:sha(read(base+'/AUDIT-BINDINGS.json')),nativeExecutionsByAuditor:0,productImports:0,rawCapturesUnchanged:true,liveRuntimeExact:true,originalFailuresUnrescored:true,toolControlPlane:'ROOT attestation and agent-recorded metadata; independent artifacts cannot prove unobserved tool state',modelRecommendation:'ratify shell-visible reset reporting for these finite local Bash3.2.57 witnesses; retain hidden-span/internal-state and broader-family obligations'};fs.writeFileSync(base+'/RESULT.json',JSON.stringify(outcome,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({...outcome,resultSha256:sha(read(base+'/RESULT.json')),timing:manifest.timing,accounting:manifest.accounting}));
