import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const base=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash';
const inventory=JSON.parse(fs.readFileSync(base+'/INVENTORY.json'));
assert(inventory.every(item=>item.bytes<2097152)&&inventory.reduce((sum,item)=>sum+item.bytes,0)<8388608);
const normative='08e40d411dc47bd725cb138e7d419ef2079a2879:tests/compatibility/bash-ere-engine-independent-20260829/authority-v1/';
const specs=[...inventory.map(item=>'6b4ca17046a6f86b1947df28cd5bbdb876c9031f:'+item.path),...['ROUTING.md','SOURCE-DATA.json','RECEIPT.json','capture.data','check.mjs'].map(name=>normative+name),'a1d03bcb9be30b60b784b25abe510a7e2a23c9eb:tests/compatibility/bash-ere-native-preflight-review-20260829/resolved-slot-v1/AUTHORITY-INPUTS.json','a1d03bcb9be30b60b784b25abe510a7e2a23c9eb:tests/compatibility/bash-ere-native-preflight-review-20260829/resolved-slot-v1/RESULT.json'];
assert(specs.length<=200);fs.writeFileSync(base+'/ALL-SPECS.json',JSON.stringify(specs,null,2)+'\n',{flag:'wx'});
const records=[];function git(args,input){const index=records.length,stdout=fs.openSync(base+`/fetch-${index}.stdout`,'wx',0o600),stderr=fs.openSync(base+`/fetch-${index}.stderr`,'wx',0o600);let result;const record={args,startedAt:new Date().toISOString()};try{result=spawnSync('/usr/bin/git',args,{cwd:repo,env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_OPTIONAL_LOCKS:'0'},input,stdio:['pipe',stdout,stderr],timeout:30000});Object.assign(record,{pid:result.pid,status:result.status,signal:result.signal,error:result.error?String(result.error):null,closed:result.status!==null});}finally{for(const fd of [stdout,stderr]){fs.fsyncSync(fd);assert(fs.fstatSync(fd).size<8388608);fs.closeSync(fd);}record.finishedAt=new Date().toISOString();records.push(record);fs.writeFileSync(base+'/FETCH-PROCESS.json',JSON.stringify(records,null,2)+'\n');}assert(result.status===0&&result.signal===null&&!result.error);return fs.readFileSync(base+`/fetch-${index}.stdout`);}
const headers=git(['cat-file','--batch-check'],specs.join('\n')+'\n').toString().trimEnd().split('\n');assert.equal(headers.length,specs.length);const types=headers.map(header=>{const match=/^([a-f0-9]{40}) blob (\d+)$/.exec(header);assert(match);assert(Number(match[2])<2097152);return{oid:match[1],bytes:Number(match[2])};});assert(types.reduce((sum,item)=>sum+item.bytes,0)<8388608);
const raw=git(['cat-file','--batch'],specs.join('\n')+'\n');let position=0;const rows=[];for(let index=0;index<specs.length;index++){const item=types[index],end=raw.indexOf(10,position);assert(end>=0);assert.equal(raw.subarray(position,end).toString(),headers[index]);position=end+1;const bytes=raw.subarray(position,position+item.bytes);position+=item.bytes;assert.equal(raw[position++],10);assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),item.oid);rows.push({spec:specs[index],...item,sha256:createHash('sha256').update(bytes).digest('hex'),body:bytes.toString('base64')});}assert.equal(position,raw.length);fs.writeFileSync(base+'/ALL-INPUTS.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({files:rows.length,rawBytes:raw.length,normative:rows.filter(item=>item.spec.startsWith('08e40')).map(({spec,bytes,sha256})=>({spec,bytes,sha256})),native:0}));
