import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdir, readFile, writeFile, symlink, realpath } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { owned, repo, historical, packageRoot, jobs, hash, git, json, identity, verifyPackage } from './binding.mjs';

const evidence = resolve(owned, 'evidence');
await mkdir(evidence, { recursive: true });
const markerPath = '/tmp/regex-runtime-oracle-migration-ready.txt';
const marker = await readFile(markerPath, 'utf8');
const fixtureCommit = '8d0909ff3cf29290051e3d91dc3205e629ef6bda';
assert.ok(marker.includes(`fixture_commit ${fixtureCommit}`));
const fixturePath = 'tests/stress/regex-execution/cleanup-boundary-review/runtime.mjs';
const original = git('show', `c3a3647:${fixturePath}`);
const corrected = git('show', `${fixtureCommit}:${fixturePath}`);
assert.equal(hash(original), '34c3d137b96c4e963573977c92d478f3bd0d670fd2b7bf32bace1fdf852dd007');
assert.equal(hash(corrected), 'f0bfe258a8851d5709c10b5fc581a9c32d0daa2cbdd1f5dc828716102ff7cf22');
const importLine = "const api = await import(pathToFileURL(resolve(process.argv[2], 'dist/index.js')));";
assert.equal(corrected.toString().split(importLine).length, 2);
const transformed = corrected.toString().replace(importLine, "const api = await import('virtual-bash');");
await writeFile(resolve(evidence, 'original-runtime.mjs.txt'), original, { flag: 'wx' });
await writeFile(resolve(evidence, 'corrected-runtime.mjs.txt'), corrected, { flag: 'wx' });
await writeFile(resolve(evidence, 'fixture.diff'), git('diff', 'c3a3647', fixtureCommit, '--', fixturePath), { flag: 'wx' });
await writeFile(resolve(evidence, 'migration-marker.txt'), marker, { flag: 'wx' });
const temporarySource = resolve(owned, '.temporary/source');
await mkdir(resolve(temporarySource, 'fixture'), { recursive: true });
for (const name of ['child.mjs', 'observe.mjs', 'benign-entry.mjs']) await writeFile(resolve(temporarySource, name), await readFile(resolve(owned, name)));
await writeFile(resolve(temporarySource, 'fixture/runtime.mjs'), transformed);
const config = await json(resolve(owned, 'tsconfig.json'));
config.compilerOptions.rootDir = temporarySource;
config.compilerOptions.outDir = resolve(owned, '.temporary/compiled');
config.files = [...config.files, 'fixture/runtime.mjs'].map(path => resolve(temporarySource, path));
await writeFile(resolve(owned, '.temporary/tsconfig.json'), JSON.stringify(config, null, 2));
const compiler = resolve(repo, 'node_modules/.bin/tsc');
const build = spawnSync(compiler, ['-p', resolve(owned, '.temporary/tsconfig.json')], { cwd: owned, encoding: 'utf8', timeout: 30000, maxBuffer: 65536 });
await writeFile(resolve(evidence, 'compile.json'), JSON.stringify({ status: build.status, signal: build.signal, stdout: build.stdout, stderr: build.stderr, scope: 'only owned JS harness plus exact transformed fixture; allowJs emit, not JS typecheck or global product qualification' }, null, 2) + '\n', { flag: 'wx' });
assert.equal(build.status, 0, build.stdout + build.stderr);
await mkdir(resolve(owned, 'node_modules'), { recursive: true });
await symlink(packageRoot, resolve(owned, 'node_modules/virtual-bash'));
assert.equal(await realpath(resolve(owned, 'node_modules/virtual-bash')), packageRoot);
const packageIdentity = await verifyPackage();
const { defaults } = await import(pathToFileURL(resolve(packageRoot, 'dist/commands/regex-execution/protocol.js')));
assert.equal(defaults.requestTimeoutMs, 1000);
assert.equal(defaults.startupTimeoutMs, 3000);
assert.equal(defaults.maxWorkers, 2);
const authorResultPath = resolve(historical, 'oracle-migration/corrected-compiled-r1-result.json');
assert.equal(hash(await readFile(authorResultPath)), '7009c39ab51a2cff3dce60b7dde3167accee306dd644de0204dd8b0fe027d479');
const files = [];
for (const path of ['EXPECTATIONS.md', 'package.json', 'binding.mjs', 'observe.mjs', 'child.mjs', 'benign-entry.mjs', 'supervise.mjs', 'guard.mjs', 'prepare.mjs', 'tsconfig.json', 'evidence/original-runtime.mjs.txt', 'evidence/corrected-runtime.mjs.txt', 'evidence/fixture.diff', 'evidence/migration-marker.txt', '.temporary/compiled/child.mjs', '.temporary/compiled/observe.mjs', '.temporary/compiled/benign-entry.mjs', '.temporary/compiled/fixture/runtime.mjs']) files.push({ path, sha256: hash(await readFile(resolve(owned, path))) });
const historicalPaths = ['runtime-acceptance-workloads/guard.mjs', 'runtime-acceptance-workloads/observe.mjs', 'runtime-acceptance-workloads/child.mjs', 'runtime-acceptance-workloads/evidence/controls.json', 'runtime-acceptance-workloads/evidence/prepared.json'];
const priorControls = [];
for (const path of historicalPaths) {
  const originalBytes = git('show', `d9e277b:tests/stress/regex-execution/${path}`);
  priorControls.push({ path, sha256: hash(originalBytes), sameAsCurrent: hash(await readFile(resolve(owned, '..', path))) === hash(originalBytes) });
}
const matrix = jobs.map((job, index) => ({ slot: index + 1, job, state: 'UNUSED', pathologicalRequests: job.includes('queued') ? 0 : 1, watchdogMs: job.includes('queued') ? 8000 : 6000 }));
const prepared = { time: new Date().toISOString(), node: process.version, platform: process.platform, arch: process.arch, head: git('rev-parse', 'HEAD').toString().trim(), expectationsCommit: 'a3d3f773bac699bd11ac37f53694004cc4842797', chronology: 'expectations frozen before reading migration marker/diff, but author first correction commit 5a93969 precedes expectations commit by 10 seconds; do not claim pre-author-commit preregistration', package: packageIdentity, policy: defaults, fixture: { commit: fixtureCommit, originalSha256: hash(original), correctedSha256: hash(corrected), transformedSha256: hash(transformed), transformation: 'exact one import-line replacement to bare public virtual-bash; assertions unchanged', authorCompiledResult: await identity(authorResultPath), authorCompiledCounts: '9/9 groups; independent packed not yet run' }, matrix, totalTargetBudget: 6, pathologicalRequestBudget: 4, targetSlotsConsumed: 0, privatePackageBoundary: 'independent-runtime-containment-final-review', priorControls, controlsPlan: 'd9e277b concepts reused with modified guard: run four new benign supervisor controls, not claim exact-code reuse', files, defaultAcceptance: false };
await writeFile(resolve(evidence, 'prepared.json'), JSON.stringify(prepared, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify({ preparedSha256: hash(await readFile(resolve(evidence, 'prepared.json'))), sources: 216, emitted: 704, fixtureCommit, targetSlotsConsumed: 0, jobs }));
