import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {supervisor,durableJSON} from './frozen/new/owner.mjs';
import {caps,grant,admit,sha} from './frozen/new/support.mjs';
import {classifyTypes,classifyMutant,classifyRestore,classifyCases,classifyBinding} from './frozen/new/classify.mjs';
const own=fileURLToPath(new URL('.',import.meta.url));const seal=JSON.parse(fs.readFileSync(own+'PRESEAL.json'));const root=seal.work;const controls=[];
async function check(id,run){await run();controls.push({id,pass:true});}
const natural=code=>({exitCode:code,exitSignal:null,exited:true,closed:true,signalCount:0});
const filename=root+'/consumer-negative.mts';const expected=[{line:1,column:2,code:2345,message:'intended independent diagnostic'}];const diagnostic=filename+'(1,2): error TS2345: intended independent diagnostic\n';
await check('N01-diagnostic-code',()=>{assert.throws(()=>classifyTypes(natural(2),diagnostic.replace('TS2345','TS9999'),filename,expected,true,root));classifyTypes(natural(2),diagnostic,filename,expected,true,root);});
await check('N02-diagnostic-path-and-exit',()=>{assert.throws(()=>classifyTypes(natural(2),diagnostic.replace(filename,root+'/wrong.mts'),filename,expected,true,root));assert.throws(()=>classifyTypes({...natural(2),signalCount:1},diagnostic,filename,expected,true,root));assert.throws(()=>classifyTypes(natural(1),diagnostic,filename,expected,true,root));});
const mutation={id:'fixed',case:'K',file:'test.js',prospectiveMutantSha256:'1'.repeat(64),restoreExpectedSha256:'2'.repeat(64)};const kill=[{id:'K',pass:false,error:'expected assertion'}, {summary:{cases:1,fail:1}}];const loaded=[{kind:'authenticated-source-supplied',member:'dist/test.js',sha256:mutation.prospectiveMutantSha256}];
await check('N03-mutant-missing-load',()=>{assert.throws(()=>classifyMutant(natural(1),kill,[],mutation,'expected assertion'));classifyMutant(natural(1),kill,loaded,mutation,'expected assertion');});
await check('N04-mutant-wrong-hash',()=>{assert.throws(()=>classifyMutant(natural(1),kill,[{...loaded[0],sha256:'0'.repeat(64)}],mutation,'expected assertion'));assert.throws(()=>classifyMutant(natural(1),kill,loaded,mutation,'wrong primary'));});
const restored=[{id:'K',pass:true},{summary:{cases:1,pass:1}}],restoreTrace=[{...loaded[0],sha256:mutation.restoreExpectedSha256}];
await check('N05-restore-status',()=>{assert.throws(()=>classifyRestore(natural(1),restored,restoreTrace,mutation));classifyRestore(natural(0),restored,restoreTrace,mutation);});
await check('N06-falsy-cleanup-presence',()=>{for(const reason of [undefined,null,false,0])assert.throws(()=>classifyCases(natural(0),[{...restored[0],cleanupError:reason},restored[1]],['K']));classifyCases(natural(0),[{...restored[0],cleanupFailure:false},restored[1]],['K']);assert.throws(()=>classifyCases(natural(0),[{...restored[0],cleanupFailure:0},restored[1]],['K']));});
await check('N07-grant-time-and-caps',()=>{const start=Date.parse('2026-08-29T00:00:00.000Z');const value={schema:'B2_RUNTIME_GO_R6',authority:'ROOT_B2_672_EXPLICIT_FRESH_GO',reviewAuthority:'INDEPENDENT_PREEXEC_REVIEW_ACCEPTED',reviewCommit:'a'.repeat(40),packetSha256:seal.packetSha256,caps:{...caps},workRoot:'/private/tmp/safe-bash-b2-runtime-r6',issuedAt:new Date(start).toISOString(),notBefore:new Date(start).toISOString(),activeDeadline:new Date(start+1620000).toISOString(),deadline:new Date(start+1800000).toISOString()};grant(value,start);assert.throws(()=>grant({...value,deadline:Infinity},start));assert.throws(()=>grant({...value,caps:{...caps,knownOsStarts:65}},start));assert.throws(()=>grant(value,start+1620000));});
await check('N08-raw-falsy-publication',()=>{for(const reason of [undefined,null,false,0]){const seen=[];let closed=0,caught=false,selected;const io={openSync(){return 0;},writeSync(){throw reason;},fsyncSync(){throw Error('unexpected flush');},closeSync(){closed++;throw 'secondary';}};try{durableJSON(io,'/DATA',{x:1},error=>seen.push(error));}catch(error){caught=true;selected=error;}assert(caught&&Object.is(selected,reason));assert.equal(closed,1);assert(Object.is(seen[0],reason));assert.equal(seen[1],'secondary');}});
await check('N09-partial-open-primary',async()=>{let opens=0,spawns=0;const io={openSync(){opens++;if(opens===3)throw undefined;return opens;},writeSync(_fd,_body,_offset,length){return length;},fsyncSync(){},closeSync(fd){if(fd===2)throw false;}};const owner=supervisor('/DATA',30,100,{roles:['fixture'],io,spawn(){spawns++;throw Error('not reached');}});let caught=false,selected;try{await owner.run('fixture','unused',[],{cwd:'/DATA',env:{}});}catch(reason){caught=true;selected=reason;}assert(caught&&selected===undefined);assert.equal(spawns,0);assert(owner.records.some(row=>row.phase==='capture-close'&&row.reason===false));owner.abort(selected);});
await check('N10-auth-before-decode',()=>{const target=root+'/invalid-json.data',body=Buffer.from('{invalid');fs.writeFileSync(target,body,{flag:'wx'});assert.throws(()=>admit(target,{bytes:body.length,sha256:'0'.repeat(64)}));const admitted=admit(target,{bytes:body.length,sha256:sha(body)});assert.deepEqual(admitted,body);assert.throws(()=>JSON.parse(admitted));});
const roles=['H01','H02','H03','H04'];const manager=supervisor(root+'/children',60,1048576,{roles,allowedExitCodes:{H01:[0],H02:[1],H03:[1],H04:[2]}});const childResults=[];
for(const [index,role]of roles.entries()){
 const home=root+'/'+role;fs.mkdirSync(home);let packageRoot=home+'/package';fs.mkdirSync(packageRoot+'/dist',{recursive:true});const body=Buffer.from('export const harmless = 1;\n');const name=role==='H03'?'parser.js':'index.js';const relative=role==='H03'?'dist/shell/parser.js':'dist/index.js';fs.mkdirSync(path.dirname(packageRoot+'/'+relative),{recursive:true});fs.writeFileSync(packageRoot+'/'+relative,body,{flag:'wx'});
 if(role==='H01'){const before=fs.statSync(packageRoot);fs.renameSync(packageRoot,home+'/moved');packageRoot=home+'/moved';const after=fs.statSync(packageRoot);assert.equal(before.ino,after.ino);assert.equal(before.dev,after.dev);assert(!fs.existsSync(home+'/package'));}
 const target=packageRoot+'/'+relative,trace=home+'/trace.jsonl';const binding={packageRoot,trace,members:role==='H02'?[]:[{path:relative,absolute:target,bytes:body.length,sha256:role==='H03'?'0'.repeat(64):sha(body)}]};const bindingBytes=Buffer.from(JSON.stringify(binding)),bindingPath=home+'/binding.json';fs.writeFileSync(bindingPath,bindingBytes,{flag:'wx'});
 const environment={PATH:'',LANG:'C',LC_ALL:'C',PUBLIC_BINDING:bindingPath,PUBLIC_BINDING_BYTES:String(bindingBytes.length),PUBLIC_BINDING_SHA256:sha(bindingBytes),FIXTURE_TARGET:target,DIAGNOSTIC_FILE:filename};
 const result=await manager.run(role,seal.node.filename,[root+'/fixture/fixture.mjs',['positive','missing','changed','type'][index]],{cwd:home,env:environment,seconds:10});const stdout=fs.readFileSync(result.stdout,'utf8'),stderr=fs.readFileSync(result.stderr,'utf8'),traceRows=role==='H04'?[]:fs.readFileSync(trace,'utf8').trim().split('\n').map(line=>JSON.parse(line));
 if(role==='H01'){assert.equal(stdout,'LOADER_BODY_OK_NO_EVALUATION\n');assert.equal(traceRows.length,1);assert.equal(traceRows[0].sha256,sha(body));}else if(role==='H04')classifyTypes(result,stdout+stderr,filename,expected,true,root);else classifyBinding(result,stdout,stderr,traceRows,role==='H02'?'missing':'changed',packageRoot);
 childResults.push({id:role,result,stdoutBytes:Buffer.byteLength(stdout),stderrBytes:Buffer.byteLength(stderr),traceRows,qualified:true});
}
const retirement=manager.finish();const result={controls,harmless:childResults,retirement,pureGroups:10,harmlessGroups:4,actualProduct:0,actualCompiler:0,asyncLoaderStarts:0,workerStarts:0,loaderEvidence:'direct exported functions in harmless Node process; not async-loader integration',pid:process.pid};fs.writeFileSync(own+'RESULT.json',JSON.stringify(result,null,2)+'\n',{flag:'wx',mode:384});console.log(JSON.stringify({pure:controls.length,harmless:childResults.length,children:retirement.children,attempted:retirement.attemptedBytes,stored:retirement.storedBytes,actual:0}));
