import {fs,path,assert,scope,sha,read,streamed,json,inventory} from './common.mjs';
const work='/tmp/safe-bash-coherent-stage-a-20260829-r1';
const sealBytes=read(path.join(scope,'PRESEAL.json'),1048576,{bytes:46824,sha256:'313ba365cb23d67187362a949087f0d264c63e5d3f776f0fc64e47f220825a2a'});
const seal=JSON.parse(sealBytes),source=JSON.parse(read(seal.source.path,1048576,seal.source)),tools=JSON.parse(read(seal.tools.path,1048576,seal.tools));
for(const item of seal.inputs)read(path.join(scope,item.path),1048576,item);
for(const row of source.inputs)read(path.join(work,'source',row.path),16777216,row);
const links={};let toolFiles=0;
for(const [name,pack]of Object.entries(tools.packages))for(const row of pack.rows){const filename=path.join(work,'tools',name,row.path);if(row.type==='symlink'){assert.ok(fs.lstatSync(filename).isSymbolicLink());assert.equal(fs.readlinkSync(filename),row.target);assert.equal(fs.realpathSync(filename),path.join(fs.realpathSync(path.join(work,'tools',name)),row.resolvedRelative));links['tools/'+name+'/'+row.path]=row.target;}else{await streamed(filename,row);toolFiles++;}}
const sourceBefore=JSON.parse(read(path.join(work,'SOURCE-BEFORE.json'),1048576));const after=inventory(path.join(work,'source'));for(const row of sourceBefore)assert.deepEqual(after.find(item=>item.path===row.path),row);assert.ok(after.every(row=>sourceBefore.some(item=>item.path===row.path)||row.path.startsWith('node_modules/')));
assert.ok(!fs.existsSync(path.join(work,'source','dist')));assert.equal(fs.readdirSync(path.join(work,'pack')).length,0);
const eventsBytes=read(path.join(work,'capture','events.jsonl'),1048576),events=eventsBytes.toString().trim().split('\n').map(line=>JSON.parse(line));const spawned=events.filter(row=>row.spawned);
assert.equal(spawned.length,3);
const childResults=spawned.map(row=>{const exit=events.find(event=>event.pid===row.pid&&event.event==='exit'),closed=events.find(event=>event.pid===row.pid&&event.event==='close'),retired=events.find(event=>event.pid===row.pid&&event.groupAbsent===true);assert.ok(exit&&closed&&retired);return{role:row.role,pid:row.pid,exitStatus:exit.status,exitSignal:exit.signal,closeStatus:closed.status,closeSignal:closed.signal,stdoutBytes:closed.stdoutBytes,stderrBytes:closed.stderrBytes,ownedGroupAbsent:true};});
const stderr=read(path.join(work,'capture','02-strict-build.stderr'),4096);assert.ok(stderr.toString().includes("resource: '/tmp'"));assert.ok(stderr.toString().includes("code: 'ERR_ACCESS_DENIED'"));
const evidence=path.join(scope,'attempt-evidence');fs.mkdirSync(evidence);const records=[];
for(const filename of ['SOURCE-BEFORE.json','TOOLS-BEFORE.json',...fs.readdirSync(path.join(work,'capture')).map(name=>'capture/'+name)]){const original=path.join(work,filename),identity=await streamed(original),body=read(original,16777216,identity);const destination=path.join(evidence,filename);fs.mkdirSync(path.dirname(destination),{recursive:true});fs.writeFileSync(destination,body,{flag:'wx'});records.push({path:filename,...identity});}
const working=inventory(work,links);const workBytes=working.reduce((sum,row)=>sum+row.bytes,0);assert.ok(workBytes<seal.bounds.workingBytes);
const stop=JSON.parse(read(path.join(scope,'STOP.json'),65536));
const result={role:'STAGE_A_PERMISSION_STOP_NO_RETRY',sourceTree:seal.sourceTree,presealSha256:sha(sealBytes),started:stop.started,finished:stop.finished,published:new Date().toISOString(),retainedRoot:work,childResults,supervisedChildren:3,signalsSent:events.filter(row=>row.signal).length,source309Postguard:true,toolRegularFilesPostguard:toolFiles,toolLinksPostguard:12,sealedHarnessPostguard:true,sourceExtraEntries:'only declared compiler dependency copies',workingBytes:workBytes,workingInventoryEntries:working.length,rawChildCaptureBytes:childResults.reduce((sum,row)=>sum+row.stdoutBytes+row.stderrBytes,0),compilerDispatches:1,compilerBodyReached:false,productionBuildsCompleted:0,packDispatches:0,actualPackage:null,predictedMembers:1014,productImports:0,semanticCalls:0,workers:0,stageB:'UNRUN_NO_AUTHORITY',denial:{code:'ERR_ACCESS_DENIED',permission:'FileSystemRead',resource:'/tmp',boundary:'Node22 realpathSync during CJS compiler entry loader'},qualification:'Exit/close and known PGID absence are observed; no full descendant/kernel-drain proof. No permission expansion, rerun, extraction, install or engine work.',records};
result.collectorQualification={priorFailure:'publish-stop.stderr: lexical /tmp compared with canonical /private/tmp; historical failure retained',correction:'Compare resolved target to canonical admitted tool root plus the unchanged exact relative target; no producer/fence changes',canonicalWorkRoot:fs.realpathSync(work)};
json(path.join(scope,'FINAL-STOP.json'),result);console.log(JSON.stringify(result));
