import { expect, it } from "vitest";
import type { CommandDefinition, VirtualShellPlugin } from "safe-bash-contracts";
import * as csvkit from "safe-bash-command-csvkit";
import * as ssconvert from "safe-bash-command-ssconvert";
import * as csvcut from "safe-bash-command-csvcut";
import * as csvgrep from "safe-bash-command-csvgrep";
import * as diff3 from "safe-bash-command-diff3";
import * as htmlq from "safe-bash-command-htmlq";
import * as mmdc from "safe-bash-command-mmdc";
import * as pdftk from "safe-bash-command-pdftk";
import * as pdftoppm from "safe-bash-command-pdftoppm";
import * as pdftotext from "safe-bash-command-pdftotext";
import * as qpdf from "safe-bash-command-qpdf";
import * as soffice from "safe-bash-command-soffice";
import * as wkhtmltopdf from "safe-bash-command-wkhtmltopdf";

it("csvkit exposes zero-argument command factories and preserves plugin registration", () => {
  const options: csvkit.CsvkitCommandsOptions = {};
  const commands = csvkit.createCsvkitCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['csvclean', 'csvcut', 'csvgrep', 'csvstat']));
  expect(csvkit.createCsvkitCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = csvkit.csvkitCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("ssconvert exposes zero-argument command factories and preserves plugin registration", () => {
  const options: ssconvert.SsconvertCommandsOptions = {};
  const commands = ssconvert.createSsconvertCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['ssconvert']));
  expect(ssconvert.createSsconvertCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = ssconvert.ssconvertCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("csvcut exposes zero-argument command factories and preserves plugin registration", () => {
  const options: csvcut.CsvcutCommandsOptions = {};
  const commands = csvcut.createCsvcutCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['csvcut']));
  expect(csvcut.createCsvcutCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = csvcut.csvcutCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("csvgrep exposes zero-argument command factories and preserves plugin registration", () => {
  const options: csvgrep.CsvgrepCommandsOptions = {};
  const commands = csvgrep.createCsvgrepCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['csvgrep']));
  expect(csvgrep.createCsvgrepCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = csvgrep.csvgrepCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("diff3 exposes zero-argument command factories and preserves plugin registration", () => {
  const options: diff3.Diff3CommandsOptions = {};
  const commands = diff3.createDiff3Commands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['diff3']));
  expect(diff3.createDiff3Command().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = diff3.diff3Commands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("htmlq exposes zero-argument command factories and preserves plugin registration", () => {
  const options: htmlq.HtmlqCommandsOptions = {};
  const commands = htmlq.createHtmlqCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['htmlq']));
  expect(htmlq.createHtmlqCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = htmlq.htmlqCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("mmdc exposes zero-argument command factories and preserves plugin registration", () => {
  const options: mmdc.MmdcCommandsOptions = {};
  const commands = mmdc.createMmdcCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['mmdc']));
  expect(mmdc.createMmdcCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = mmdc.mmdcCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("pdftk exposes zero-argument command factories and preserves plugin registration", () => {
  const options: pdftk.PdftkCommandsOptions = {};
  const commands = pdftk.createPdftkCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['pdftk']));
  expect(pdftk.createPdftkCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = pdftk.pdftkCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("pdftoppm exposes zero-argument command factories and preserves plugin registration", () => {
  const options: pdftoppm.PdftoppmCommandsOptions = {};
  const commands = pdftoppm.createPdftoppmCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['pdftoppm', 'pdftocairo']));
  expect(pdftoppm.createPdftoppmCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = pdftoppm.pdftoppmCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("pdftotext exposes zero-argument command factories and preserves plugin registration", () => {
  const options: pdftotext.PdftotextCommandsOptions = {};
  const commands = pdftotext.createPdftotextCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['pdftotext', 'pdftohtml']));
  expect(pdftotext.createPdftotextCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = pdftotext.pdftotextCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("qpdf exposes zero-argument command factories and preserves plugin registration", () => {
  const options: qpdf.QpdfCommandsOptions = {};
  const commands = qpdf.createQpdfCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['qpdf']));
  expect(qpdf.createQpdfCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = qpdf.qpdfCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("soffice exposes zero-argument command factories and preserves plugin registration", () => {
  const options: soffice.SofficeCommandsOptions = {};
  const commands = soffice.createSofficeCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['soffice', 'libreoffice']));
  expect(soffice.createSofficeCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = soffice.sofficeCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
it("wkhtmltopdf exposes zero-argument command factories and preserves plugin registration", () => {
  const options: wkhtmltopdf.WkhtmltopdfCommandsOptions = {};
  const commands = wkhtmltopdf.createWkhtmltopdfCommands(options);
  expect(commands.map(command => command.name)).toEqual(expect.arrayContaining(['wkhtmltopdf']));
  expect(wkhtmltopdf.createWkhtmltopdfCommand().execute).toBeTypeOf("function");
  const plugin: VirtualShellPlugin = wkhtmltopdf.wkhtmltopdfCommands();
  const registered: CommandDefinition[] = [];
  const host = { commands: { register: (command: CommandDefinition) => registered.push(command), has: () => false } };
  plugin.setup(host as Parameters<VirtualShellPlugin["setup"]>[0]);
  expect(registered.map(command => command.name)).toEqual(commands.map(command => command.name));
});
