import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {selectChild,ownerOutcome,loadedHelper,m01Detected,inheritWindow,admitCase} from './snapshot/qualification.mjs';
import {Primary,errorRecord} from './snapshot/auth.mjs';
import {validateActivation} from './snapshot/activation.mjs';
import {assertOwned} from './snapshot/inherited/canonical.mjs';

function json(name){const filename=new URL(name,import.meta.url),stat=fs.lstatSync(filename);assert(stat.isFile()&&stat.size<=262144);return JSON.parse(fs.readFileSync(filename));}
const seal=json('./snapshot/SEAL.json'),data=json('./snapshot/CASES.json'),exact=json('./snapshot/M01-DISCRIMINATOR.json');
const groups=[];
function group(id,run){try{run();groups.push({id,pass:true});}catch(error){groups.push({id,pass:false,error:{name:error?.name,message:error?.message}});}}
const expected={started:100000,finalDeadline:1600000,observations:['source-built','installed','physically-moved'].flatMap(layout=>data.rows.map(row=>'case-'+layout+'-'+row.id)),helpers:['source-built','installed','physically-moved'].map(layout=>'helpers-'+layout)};
function report(){const result={started:100000,finished:100100,primaryPresent:false,secondary:[],status:'COMPLETED',semanticFailures:0,controlFailures:0,observations:expected.observations.map(id=>({id,receipt:{pass:true}})),helpers:expected.helpers.map(id=>({id,receipt:{pass:true}})),mutants:['M01','M02','M03'].map(id=>({mutation:{id},detected:true})),refusals:['N01','N02'].map(id=>({id,observed:true})),ledger:{starts:78,active:0,rows:[]}};result.ledger.rows=[...expected.observations,...expected.helpers,'M01','M02','M03','N01','N02'].map(id=>({id,qualified:true,knownOutstanding:0,exit:true,close:true}));return result;}
const summary={publicationSucceeded:true,primaryPresent:false,resultStatus:'COMPLETED'};
group('N01-composed-falsy-selection',()=>{for(const reason of [undefined,null,false,0]){const selected=selectChild({primary:{present:true,reason},row:{qualified:false}},()=>{});const primary=new Primary();if(selected.present)primary.fail(selected.reason);primary.fail('later');assert(primary.present);assert(Object.is(primary.reason,reason));assert.deepEqual(primary.secondary,[{kind:'string',value:'later'}]);assert.deepEqual(errorRecord(primary.reason),errorRecord(reason));}});
group('N02-semantic-failure-not-protocol-pass',()=>{const result=report();result.observations[68].receipt.pass=false;result.semanticFailures=1;result.status='COMPLETED_WITH_ASSERTION_FAILURES';const actual=ownerOutcome(result,{...summary,resultStatus:result.status},expected);assert.deepEqual(actual,{status:result.status,failures:1,accepted:false,knownOwnedRetired:true});result.semanticFailures=0;assert.throws(()=>ownerOutcome(result,{...summary,resultStatus:result.status},expected),/OWNER_RESULT_STATUS/);});
group('N03-primary-and-retirement-cannot-be-erased',()=>{for(const mutate of [row=>{row.primaryPresent=true;row.primary={kind:'undefined'};},row=>row.secondary.push({present:true,reason:{kind:'null'}}),row=>{row.ledger.rows[76].knownOutstanding=1;},row=>{row.ledger.rows[76].exit=false;},row=>{row.ledger.rows[76].id=row.ledger.rows[0].id;}]){const result=report();mutate(result);assert.throws(()=>ownerOutcome(result,summary,expected));}});
function mutant(){return {helperLoad:{sha256:exact.mutantSha256},receipt:{pass:false,failures:['status','stdout','stderr'],publicSettlement:{execObserved:true,disposeSettled:true},observation:{kind:'resolved',status:1,stdout:{base64:''},stderr:{base64:exact.stderrBase64},hasPrimary:false,hasCleanupError:false,filesBefore:[],filesAfter:[]}}};}
group('N04-m01-exact-diagnostic-and-baseline',()=>{const baseline={receipt:{pass:true},helperLoad:{sha256:exact.baselineSha256}};assert(m01Detected(baseline,mutant(),exact));for(const change of [row=>{row.receipt.observation.stderr.base64=Buffer.from(Buffer.from(exact.stderrBase64,'base64').toString().replace('$1','$2')).toString('base64');},row=>{row.receipt.publicSettlement.disposeSettled=false;},row=>{row.receipt.observation.kind='rejected';}]){const changed=mutant();change(changed);assert.equal(m01Detected(baseline,changed,exact),false);}assert.equal(m01Detected({...baseline,receipt:{pass:false}},mutant(),exact),false);assert.notEqual(exact.mutantSha256,exact.baselineSha256);});
group('N05-helper-load-not-adjacent-module-or-stale-bytes',()=>{const role={id:'M01',helperEntry:'/owned/arithmetic-parameters.js',files:{'/owned/arithmetic-parameters.js':{bytes:123,sha256:exact.mutantSha256}}},row={event:'module-loaded',url:'file:///owned/arithmetic-parameters.js',role:'M01',bytes:123,sha256:exact.mutantSha256};assert.equal(loadedHelper([row],role).sha256,exact.mutantSha256);for(const changed of [{...row,bytes:122},{...row,url:'file:///owned/arithmetic.js'},{...row,sha256:exact.baselineSha256},{...row,event:'resolved-only'}])assert.throws(()=>loadedHelper([changed],role),/HELPER_LOADED_BINDING/);});
group('N06-canonical-final-literals-and-rejected-sibling',()=>{for(const suffix of ['source-app','target-installed','target-moved','target-mutant-M01'])assert.equal(assertOwned(seal.work,seal.work+'/'+suffix),seal.work+'/'+suffix);assert.equal(assertOwned(seal.work,seal.sourceApp),seal.sourceApp);assert.throws(()=>assertOwned(seal.work,seal.work+'-sibling/source-app'));assert.throws(()=>assertOwned(seal.work,seal.work+'/source-app/../elsewhere'));for(const name of ['collector.mjs','launch.sh']){const filename=new URL('./snapshot/'+name,import.meta.url);const stat=fs.lstatSync(filename);assert(stat.isFile()&&stat.size<8192);const bytes=fs.readFileSync(filename);assert.equal(createHash('sha256').update(bytes).digest('hex'),seal.files[name].sha256);const source=bytes.toString();assert(source.includes(seal.work));assert(!source.includes('safe-bash-k08-preexec-v2-'));}});
group('N07-one-clock-cleanup-and-publication-tail',()=>{const window=inheritWindow(100000,1600000,{expiresEpochMs:2000000},seal.limits,800000);assert.deepEqual(window,{started:100000,finalDeadline:1600000,bodyDeadline:1540000,ownerPublicationDeadline:1585000,collectorRetirementDeadline:1594000});assert.equal(admitCase(window,1506999).bodyDeadline,1536999);assert.throws(()=>admitCase(window,1507000),/CHILD_CLEANUP_RESERVATION/);assert.throws(()=>inheritWindow(800000,1600000,{expiresEpochMs:2000000},seal.limits,800000),/OUTER_TIME_BINDING/);assert.equal(window.collectorRetirementDeadline+4000+1000,1599000);});
group('N08-inactive-and-typed-authority',()=>{const template=json('./snapshot/GO.template.json'),review=json('./snapshot/REVIEW.template.json');const input={preseal:template.preseal,work:seal.work,limits:seal.limits,roles:seal.roles,started:100000,now:100000};assert.throws(()=>validateActivation(template,review,input));const grant={...template,decision:'GO',issuedAtEpochMs:100000,latestStartEpochMs:100000,expiresEpochMs:1600000};const accepted={...review,decision:'ACCEPT',independentCommit:'a'.repeat(40)};assert.equal(validateActivation(grant,accepted,input).finalDeadline,1600000);for(const value of [null,false,undefined,'100000',NaN,Infinity])assert.throws(()=>validateActivation({...grant,issuedAtEpochMs:value},accepted,input));assert.throws(()=>validateActivation(grant,accepted,{...input,now:100001}),/AUTH_TIME_ORDER/);});
process.stdout.write(JSON.stringify({schema:'k08-independent-v2',groups,productCalls:0,workers:0,harmlessLifecycleFixtures:0})+'\n');
if(groups.some(row=>!row.pass))process.exitCode=1;
