import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { regular, put, sha, census, verify } from '../common.mjs';
const here = path.dirname(fileURLToPath(import.meta.url)), repo = path.resolve(here, '../../../../..');
const seal = JSON.parse(regular(path.join(here, 'SEAL.json')));
assert.equal(sha(regular(path.join(here, 'SEAL.json'))), '19cacaa0b7de259bc13c4a1106f1d6f5498c0ea8658ee57add9e32c78871ae0c');
const work = path.join(here, 'RUN-' + seal.label), records = path.join(work, 'records'), entries = census(records);
const finalBytes = regular(path.join(records, 'FINAL.json')); assert.equal(sha(finalBytes), '2453f8a7b6e0099da41dd5e87af648b203e6aed79f1845a1134eec863031e06b');
const final = JSON.parse(finalBytes); assert.equal(final.complete, true); assert.equal(final.unsafeStop, false); assert.equal(final.eligibleAcceptance, true);
assert.equal(final.accounting.children.length, 3); assert.ok(final.accounting.children.every(row => row.retired && row.code === 0 && row.signal === null && row.groupAbsent));
for (const row of [...seal.roles, ...seal.bindings]) { const filename = path.join(repo, row.path); assert.equal(sha(regular(filename)), row.sha256); assert.equal(fs.statSync(filename).mode & 0o777, row.mode); }
for (const tree of seal.protectedTrees) verify(tree);
const prior = census(seal.priorIndependent.root); for (const key of Object.keys(prior)) if (key.startsWith(seal.priorIndependent.excludedNewOwnedDirectory)) delete prior[key]; assert.deepEqual(prior, seal.priorIndependent.entries);
const archive = { schema: 'lossless-regular-records-no-compression-no-deletion', entries: Object.entries(entries).map(([filename, row]) => {
  assert.ok(!row.directory); const bytes = regular(path.join(records, filename)); assert.equal(sha(bytes), row.sha256); return { path: filename, ...row, base64: bytes.toString('base64') };
}) };
const archiveBytes = Buffer.from(JSON.stringify(archive) + '\n');
for (const row of JSON.parse(archiveBytes).entries) { const bytes = Buffer.from(row.base64, 'base64'); assert.equal(bytes.length, row.bytes); assert.equal(sha(bytes), row.sha256); assert.deepEqual(bytes, regular(path.join(records, row.path))); }
put(path.join(here, 'evidence/RECORDS.json'), archiveBytes);
const pilot = JSON.parse(regular(path.join(records, 'observations-pilot-v10.json')));
const capacity = JSON.parse(regular(path.join(repo, 'tests/commands/git-independent-20260828/adapter-pilot-v10/CAPACITY.json')));
const special = { A52: 'ten direct Session counter scopes, no command invocation/inflater', H08: 'registry factories only, no execute/inflater', A55: 'three preabort identities plus one midread abort; original zero inflaters', A56: 'slow sink, rejected sink identity, preclosed consumer141', A57: 'direct noHook/internal finally', A60: 'actual Shell plugin pipeline + cat + scope cleanup', H09: 'oversized declared header, no huge body', H10: 'ONE direct helper call, oversized config lstat before inflate', H11: 'ONE direct helper call through separately owned Real filesystem' };
const routeMap = capacity.allMembership.map(id => ({ id, route: special[id] ?? 'ordinary direct helper with registered callback; original case bytes authoritative', historicalDataOnly: capacity.historicalDataOnly.find(row => row.id === id) ?? null, independentInstrumentedPilot: ['A57','A60','H09'].includes(id), unchangedNewSemanticRun: false, full71WorkerCapacityProof: 'NOT_SEALED' }));
put(path.join(here, 'evidence/ROUTES.json'), Buffer.from(JSON.stringify({ sourceCasesSha256: capacity.frozenCasesSha256, rows: routeMap, historicalHelperObservationRows: capacity.historicalDataOnly.reduce((sum, row) => sum + row.invocationsObserved, 0), historicalIncludesOneShellObservation: true, authorH10TwoCallsCorrectedAsSourceDataOnly: true }, null, 2) + '\n'));
const facts = pilot.cases.map(row => ({ id: row.id, status: row.observations[0].exitCode, passed: row.passed, resources: row.afterNotification.resources.length, events: row.afterNotification.events.length, identities: row.afterNotification.identityCount, contexts: row.afterNotification.contexts.length, beforePendingNotifications: row.beforeNotification.resources.filter(resource => !resource.closeDelivered).length, afterPendingNotifications: row.afterNotification.resources.filter(resource => !resource.closeDelivered).length, counts: Object.fromEntries([...new Set(row.afterNotification.events.map(event => event.event))].map(name => [name, row.afterNotification.events.filter(event => event.event === name).length])), restoration: row.restoration }));
const workEntries = census(work), workBytes = Object.values(workEntries).reduce((total, row) => total + (row.bytes ?? 0), 0);
const audit = { sealSha256: sha(regular(path.join(here, 'SEAL.json'))), presealCommit: 'e91253e8f452c4412567535fd3f47ddbbbd35aa1', finalSha256: sha(finalBytes), terminalObservedFromExecTranscript: { coordinatorExit: 0, accepted: true, unsafeStop: false, childrenRetired: true, elapsedBeforeAnnouncementMs: 1822.773666 }, phaseResults: final.phases, pilotFacts: facts, loader: { originalProductLoads: 215, instrumentedProductLoads: 5, unchangedHarnessLoads: 4, totalPilotModuleLoads: pilot.loads.length, builtinLoads: pilot.builtins.length, bootstrapQualification: 'independent synchronous exact-byte hook; original author asynchronous bootstrap/loader not re-executed' }, resources: { directChildren: 3, coordinator: 1, peakProcesses: 2, compilerChildren: 0, nativeGitChildren: 0, captureBytes: final.accounting.captured, rawRecords: archive.entries.length, rawRecordBytes: archive.entries.reduce((sum, row) => sum + row.bytes, 0), archiveBytes: archiveBytes.length, archiveSha256: sha(archiveBytes), retainedWorkBytes: workBytes, metadataPreparationGitChildren: seal.metadata.length, preparationCandidateExecutions: 0 }, preserved: { protectedTrees: seal.protectedTrees.map(tree => ({ root: tree.root, entries: Object.keys(tree.entries).length })), priorIndependentCensus: true, newEntryDetection: true, rawDeletion: false, old69And215Unchanged: true, original289288NotRescored: true }, qualification: { sourceTransformReversals: 6, packageMembersAuthenticated: 898, packageSha256: seal.package.sha256, compilerReproduction: false, unmodifiedSemanticCredit: 0, full284Go: false, M1BRebinding: 'REQUIRED;090/fca6 not authenticated by M1A988' } };
put(path.join(here, 'evidence/AUDIT.json'), Buffer.from(JSON.stringify(audit, null, 2) + '\n'));
console.log(JSON.stringify({ records: archive.entries.length, rawBytes: audit.resources.rawRecordBytes, archiveBytes: archiveBytes.length, retainedWorkBytes: workBytes, candidateExecutionsNow: 0 }));
