import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';

const own=new URL('.',import.meta.url);
function raw(name){const file=new URL(name,own),stat=fs.lstatSync(file);assert(stat.isFile()&&stat.size<=1048576);return fs.readFileSync(file);}
const preseal=JSON.parse(raw('PRESEAL.json'));for(const row of preseal.files)assert.equal(crypto.createHash('sha256').update(raw(row.path)).digest('hex'),row.sha256);
const {ownerLedger,admitPrior,completePreimport,admitPublisher,countPublication}=await import('./snapshot/admin-owner-r2/ledger.mjs');
const {errors,openPair}=await import('./snapshot/admin-owner-r1/tracked-owner.mjs');
const {Ledger}=await import('./snapshot/stage-b1-r4/policy.mjs');
const packet=JSON.parse(raw('snapshot/final-admin-r5/FINAL.json')),publication=JSON.parse(raw('snapshot/final-admin-r5/PUBLICATION-BINDING.json')),command=JSON.parse(raw('snapshot/final-admin-r5/COMMAND.json'));
const groups=[];let accounting;
function group(id,body){try{body();groups.push({id,pass:true});}catch(reason){groups.push({id,pass:false,message:reason?.message});}}
const time='2026-08-29T15:45:00.000Z',self={id:'owner-500',role:'administrative-owner',pid:500,startUTC:time,startObserved:true,exitObserved:false,closeObserved:false};
function base(){return ownerLedger({self,starts:[]},'PURE-NOT-AUTHORITY',{path:'/owned/entry.mjs',sha256:'a'.repeat(64)});}
const observed={parentPid:500,selfPid:501,startedUTC:time};
function completed(){const admission=admitPrior(base(),observed);return completePreimport(admission,{pid:501,role:'publication-preimport',startObserved:true,exitObserved:true,closeObserved:true});}
group('F01-output-only-runtime',()=>{const before=JSON.parse(raw('snapshot/stage-b1-r4/PRESEAL.json')),after=JSON.parse(raw('snapshot/final-admin-r5/RUNTIME-PRESEAL.json'));assert.deepEqual({...after,workRoot:before.workRoot},before);});
group('F02-single-direct-command',()=>{assert.equal(command.executable,'/bin/zsh');assert.equal(command.argv.length,5);assert.equal(packet.runtimeCommand.executable,preseal.node);assert.equal(packet.publicationCommand.executable,preseal.node);});
group('F03-flat-bound-closure',()=>{for(const row of [...packet.adminFiles,...packet.preimportFiles,...packet.publisherFiles]){assert(!Array.isArray(row));assert(row.path.startsWith('/'));assert(Number.isSafeInteger(row.bytes));assert.match(row.sha256,/^[a-f0-9]{64}$/);const relative='snapshot/'+row.path.split('/agent-bash-coherent-author-20260829/')[1];const bytes=raw(relative);assert.equal(bytes.length,row.bytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),row.sha256);}});
group('F04-unobserved-streams-null',()=>{const source=raw('snapshot/final-admin-r5/entry.mjs').toString();assert(source.includes('stdoutEnd: null, stderrEnd: null'));assert(source.includes('EXIT_PENDING_EXTERNAL_OBSERVATION'));});
group('N01-exact-parent-and-extra-open-role',()=>{assert.equal(admitPrior(base(),observed).prior[0].state,'LIVE_ADMIN_OWNER');for(const change of [row=>row.starts.push({...row.starts[0],id:'second',pid:502}),row=>row.owner.pid=502,row=>row.starts.push({...row.starts[0],id:'open',pid:502,role:'unrelated'})]){const row=base();change(row);assert.throws(()=>admitPrior(row,observed));}});
group('N02-start-count-missing-or-phantom',()=>{const row=completed();for(const count of [undefined,null,0,3])assert.throws(()=>admitPublisher({...row,knownStartsBeforePublication:count},{...observed,selfPid:502}));const publisher=admitPublisher(row,{...observed,selfPid:502});assert.equal(countPublication(row,publisher,[]).knownStarts,3);});
group('N03-closed-not-falsy-or-missing',()=>{for(const value of [undefined,null,false,0]){const row=base();row.starts.push({id:'prior',role:'runtime',pid:503,startedUTC:time,state:'CLOSED',startObserved:true,exitObserved:value,closeObserved:true});assert.throws(()=>admitPrior(row,observed));}});
group('N04-reservations-exact-boundary',()=>{const row=base();while(row.starts.length<31)row.starts.push({id:'prior-'+row.starts.length,role:'runtime',pid:600+row.starts.length,startedUTC:time,state:'CLOSED',startObserved:true,exitObserved:true,closeObserved:true});assert.equal(admitPrior(row,observed).prior.length,31);row.starts.push({id:'over',role:'runtime',pid:900,startedUTC:time,state:'CLOSED',startObserved:true,exitObserved:true,closeObserved:true});assert.throws(()=>admitPrior(row,observed),/RESERVATION_OVER_CAP/);});
group('N05-closed-preimport-before-publisher',()=>{const row=admitPrior(base(),observed);assert.throws(()=>completePreimport(row,{pid:501,role:'publication-preimport',startObserved:true,exitObserved:true,closeObserved:false}));const done=completed();assert.throws(()=>admitPublisher(done,{...observed,selfPid:501}));assert.throws(()=>admitPublisher(done,{...observed,parentPid:499,selfPid:502}));});
group('N06-falsy-primary-partial-open-secondary',()=>{for(const primary of [undefined,null,false,0]){const state=errors();state.add(primary);state.add('later');assert(state.snapshot().primaryPresent);assert.equal(state.snapshot().primary.type,primary===null?'null':typeof primary);let calls=0;const secondary=[];let caught=false,reason;try{openPair({openSync(){if(++calls===1)return 8;throw primary;},closeSync(){throw 'close';}},['out','err'],value=>secondary.push(value));}catch(error){caught=true;reason=error;}assert(caught&&Object.is(reason,primary));assert.deepEqual(secondary,['close']);}});
group('N07-git-pid-not-reservation-or-duplicate',()=>{const done=completed(),publisher=admitPublisher(done,{...observed,selfPid:502});const row={role:'git-add',pid:503,exitObserved:true,closeObserved:true};assert.equal(countPublication(done,publisher,[row]).knownStarts,4);assert.throws(()=>countPublication(done,publisher,[row,{...row,role:'git-commit'}]));assert.equal(countPublication(done,publisher,[{role:'git-add',pid:null}]).childRetirement,'UNKNOWN');});
group('N08-startup-stream-reservation-covers-all-declared-files',()=>{const source=raw('snapshot/admin-owner-r2/publish.mjs').toString();assert(source.includes('ledger.charge(8192 - startupBytes)'));assert(source.includes('stat.size > 4096'));assert.equal(publication.outputs.startupCaptures.length,4);const ledger=new Ledger({capture:0,work:0});ledger.charge(8192);accounting={files:publication.outputs.startupCaptures,perFileAcceptedCeiling:4096,requiredAggregateCeiling:16384,chargedAggregateCeiling:ledger.snapshot().used.capture,shortfall:16384-ledger.snapshot().used.capture,qualification:'SOURCE arithmetic plus pure Ledger call; no publisher or byte streams executed'};assert(ledger.snapshot().used.capture>=16384,'four 4096-byte startup files exceed the retained 8192-byte reservation');});
for(const row of preseal.files)assert.equal(crypto.createHash('sha256').update(raw(row.path)).digest('hex'),row.sha256);
fs.writeFileSync(new URL('INDEPENDENT-RESULT.json',own),JSON.stringify({groups,accounting,postguards:preseal.files.length,productCalls:0,realPublisherCalls:0},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({groups,accounting}));if(groups.some(row=>!row.pass))process.exitCode=1;
