import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
let policy;
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
function trace(value){const bytes=Buffer.from(JSON.stringify(value)+'\n');if(fs.statSync(policy.loaderTrace).size+bytes.length>524288)throw Error('LOADER_TRACE_LIMIT');fs.appendFileSync(policy.loaderTrace,bytes);}
export function initialize(data){policy=data;trace({event:'loader-initialized',role:policy.id,regexWorkerPermission:0});}
export async function resolve(specifier,context,nextResolve){if(context.parentURL?.startsWith('file:')&&policy.edges){const parent=fileURLToPath(context.parentURL);if(!policy.edges[parent]?.includes(specifier))throw Error('SOURCE_EDGE_REFUSED:'+specifier);}if(specifier.startsWith('node:')){if(!policy.builtins.includes(specifier))throw Error('BUILTIN_REFUSED:'+specifier);return nextResolve(specifier,context);}const resolved=await nextResolve(specifier,context);if(!resolved.url.startsWith('file:')||!Object.hasOwn(policy.files,fileURLToPath(resolved.url)))throw Error('LOAD_BINDING_REFUSED:'+resolved.url);return resolved;}
export async function load(url,context,nextLoad){if(url.startsWith('node:'))return nextLoad(url,context);const filename=fileURLToPath(url),pin=policy.files[filename];if(!pin)throw Error('LOAD_BINDING_REFUSED');const stat=fs.lstatSync(filename);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==pin.bytes||stat.size>16777216)throw Error('LOAD_TYPE_SIZE');const fd=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let bytes;try{bytes=Buffer.alloc(pin.bytes);let offset=0;while(offset<bytes.length){const count=fs.readSync(fd,bytes,offset,Math.min(65536,bytes.length-offset),offset);if(!count)throw Error('LOAD_SHORT');offset+=count;}if(fs.readSync(fd,Buffer.alloc(1),0,1,offset))throw Error('LOAD_LONG');if(bytes.length!==pin.bytes||hash(bytes)!==pin.sha256)throw Error('LOAD_HASH_REFUSED');}finally{fs.closeSync(fd);}trace({event:'module-loaded',role:policy.id,url,bytes:bytes.length,sha256:pin.sha256});return {format:'module',source:bytes,shortCircuit:true};}
