import assert from 'node:assert/strict';
import fs from 'node:fs';
import { resolve,relative } from 'node:path';
import { pathToFileURL } from 'node:url';
import { recipe,repository,owned,read,fileHash,sha,save,write,safe,inventory,sameInventory,authenticatePreparation,reason } from './common.mjs';
import { requireAuthorization,materializeInputs } from './admission.mjs';
import { supervisor,absent } from './supervisor.mjs';
import { archiveEvidence } from './archive.mjs';
import { assertCaptureReceipt } from './capture.mjs';
const requestFile=process.env.TIMEOUT_PUBLIC_BINDING;assert.ok(requestFile,'EXPLICIT_B01_BINDING_REQUIRED');assert.ok(resolve(requestFile).startsWith(`${recipe}/`));safe(relative(recipe,resolve(requestFile)));assert.ok(fs.lstatSync(requestFile).isFile()&&!fs.lstatSync(requestFile).isSymbolicLink());assert.equal(fs.realpathSync(requestFile),resolve(requestFile));
const requestBytes=fs.readFileSync(requestFile),requestHash=sha(requestBytes),request=JSON.parse(requestBytes);requireAuthorization(process.argv.slice(2),request,requestHash);
const {binding,manifest}=authenticatePreparation(request.preparationSha256),continuation=read(resolve(recipe,'CONTINUATION.json')),author=read(resolve(recipe,'../public-candidate-execution-v1/AUTHOR-BINDINGS.json'));
for(const key of ['candidate','baseline','module','public','packageFiles','mutants'])assert.deepEqual(request[key],author[key],'SEALED_CANDIDATE_FIELD:'+key);
assert.equal(continuation.candidate,request.candidate);assert.equal(continuation.boundaryControl.id,'B01');assert.equal(continuation.actualProductFamilies,0);assert.equal(continuation.actualNodeChildren,1);
const run=resolve(recipe,'runs',safe(request.runName)),work=resolve(recipe,'node_modules',request.runName),raw=resolve(run,'raw');assert.equal(fs.existsSync(run),false,'NO_RETRY_EXISTING_RUN');assert.equal(fs.existsSync(work),false,'NO_RETRY_EXISTING_WORK');fs.mkdirSync(raw,{recursive:true});fs.mkdirSync(work,{recursive:true});write(resolve(run,'CANDIDATE.json'),requestBytes);
const state={schema:'timeout-public-b01-capture-execution/1',candidate:request.candidate,baseline:request.baseline,module:request.module,requestHash,preparationSha256:request.preparationSha256,startedAt:new Date().toISOString(),status:'RUNNING',attempts:1,retries:0,children:[],git:[],guards:[],runtime:[],mutants:[],boundaryControls:[],native:0,safeJS:0,positiveFamiliesExecuted:0,typeConsumersExecuted:0,buildsExecuted:0,packsExecuted:0,productMutantsExecuted:0};
const guarded=new Map();function guard(label){authenticatePreparation(request.preparationSha256);assert.equal(fileHash(resolve(run,'CANDIDATE.json')),requestHash);for(const [root,expected] of guarded)sameInventory(inventory(root),expected);state.guards.push({label,at:new Date().toISOString(),unchanged:true});}
const child=supervisor({raw,work,guard,children:state.children});
function helperLoads(){const loads={};for(const row of [...manifest.files,...manifest.references])if(row.path.endsWith('.mjs')){const filename=row.repositoryRelative?resolve(repository,row.path):resolve(recipe,row.path);loads[filename]=row.sha256;}return loads;}
async function runtime(profile,productRoot,consumer,caseId,mutation,boundaryControl){
  const label=`${profile}-${caseId}`,output=resolve(raw,label);fs.mkdirSync(output);
  const entry=resolve(consumer,`${label}.mjs`);write(entry,`await import(${JSON.stringify(pathToFileURL(resolve(recipe,'runtime.mjs')).href)});\n`);
  const loads=helperLoads();loads[entry]=fileHash(entry);
  for(const row of inventory(productRoot))if(row.path.endsWith(profile==='source'||mutation||boundaryControl?'.ts':'.js'))loads[resolve(productRoot,row.path)]=row.sha256;
  const config={profile:profile==='source'||mutation||boundaryControl?'source':profile,candidate:request.candidate,executionAuthorized:true,caseId,productRoot,consumerEntry:entry,loads,sourceEntries:{'virtual-bash':resolve(productRoot,'src/index.ts'),'virtual-bash/commands/timeout':resolve(productRoot,'src/commands/timeout/index.ts')},trace:resolve(output,'loads.jsonl'),output,guardRoots:[{root:productRoot,entries:inventory(productRoot)}],diagnostics:read(resolve(owned,'repaired-f22-v1/recipe/BINDINGS.json')).diagnostics,...(mutation?{intentionalMutation:mutation}:{}),...(boundaryControl?{boundaryControl}:{})};
  const configuration=resolve(work,`${label}-config.json`);save(configuration,config);
  const result=await child(label,['--permission',`--allow-fs-read=${owned}`,`--allow-fs-write=${output}`,'--import',resolve(recipe,'preload.mjs'),entry],consumer,{TIMEOUT_CONFIG:configuration,TIMEOUT_CONFIG_SHA256:fileHash(configuration)});
  const captured=read(resolve(output,'RESULT.json')),observations=fs.readFileSync(config.trace,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
  const required=['virtual-bash','virtual-bash/commands/timeout'];
  for(const specifier of required){const row=observations.find(item=>item.kind==='entrypoint-resolution'&&item.specifier===specifier);assert.ok(row,'ACTUAL_ENTRYPOINT_RESOLUTION');assert.equal(row.throughActualPackageExports,config.profile!=='source');const target=specifier==='virtual-bash'?'index':'commands/timeout/index';const path=resolve(productRoot,config.profile==='source'?`src/${target}.ts`:`dist/${target}.js`);assert.ok(observations.some(item=>item.kind==='actual-module-load'&&item.path===path&&item.sha256===loads[path]),'ACTUAL_ENTRYPOINT_LOAD');}
  assert.equal(captured.cleanup.pending,0);assert.equal(captured.cleanup.timers,0);assert.deepEqual(captured.cleanup.unhandled,[]);assert.equal(captured.integrity,'UNCHANGED');assert.notEqual(captured.status,'STOP_NO_RETRY');assert.equal(result.signal,null);
  captured.loadProof={actualModuleLoads:observations.filter(row=>row.kind==='actual-module-load').length,publicPackageExports:config.profile!=='source'};
  if(mutation){assert.ok(observations.some(row=>row.kind==='actual-module-load'&&row.path===resolve(productRoot,mutation.path)&&row.sha256===mutation.afterSha256),'ACTUAL_MUTATED_LOAD');const record={id:mutation.id,status:'KILLED',caseId,result:captured};try{assert.equal(result.code,1,'MUTANT_SURVIVED');assert.equal(captured.status,'FAIL');assert.ok(captured.failure.text.includes(mutation.failure),'WRONG_MUTANT_FAILURE');if(mutation.id==='M07'){const observation=captured.observations.find(row=>row.kind==='PC01-boundaries');assert.ok(observation);assert.deepEqual(observation.dispatch,{timeout:1,child:1,outer:0});assert.equal(observation.sameCallerSentinel,true);assert.equal(observation.sameHandlerSignalReason,true);assert.equal(observation.beforeRelease.handler.status,'pending');assert.equal(observation.beforeRelease.outer.status,'pending');assert.equal(observation.handler.status,'fulfilled');assert.equal(observation.handler.exitCode,124);assert.equal(observation.outer.status,'rejected');assert.equal(observation.outer.sameSentinel,true);assert.equal(observation.childClosed,true);assert.equal(observation.resources,0);}if(mutation.id==='M06'){const observation=captured.observations.find(row=>row.kind==='public-default-clock-result');assert.equal(observation?.status,125);assert.equal(observation.stdoutBase64,'');assert.equal(Buffer.from(observation.stderrBase64,'base64').toString(),'timeout: timer setup failed\n');}if(mutation.id==='M08')assert.ok(captured.observations.some(row=>row.kind==='PC02-direct-retirement'&&row.entered&&row.threw&&row.sameSentinel),'RETIREMENT_NOT_ACTIVATED');}catch(error){record.status='FAIL';record.failure=reason(error);}state.mutants.push(record);}
  else if(boundaryControl){const record={id:boundaryControl.id,status:'KILLED',caseId,result:captured};try{assert.equal(result.code,1);assert.equal(captured.status,'FAIL');assert.ok(captured.failure.text.includes(boundaryControl.failure),'WRONG_BOUNDARY_MUTANT_FAILURE');const observation=captured.observations.find(row=>row.kind===(boundaryControl.id==='B01'?'R12-raw-before-assertion':boundaryControl.id==='B03'?'R12-return-admission-failure':'R12-shell-before-release'));assert.ok(observation,'ACTUAL_BOUNDARY_OBSERVATION');if(boundaryControl.id==='B01'){assert.equal(observation.counts.acquire,1);assert.equal(observation.counts.next,0);}if(boundaryControl.id==='B02'){assert.equal(observation.counts.next,1);assert.equal(observation.counts.contentBytes,1);}if(boundaryControl.id==='B03'){assert.equal(observation.counts.acquire,1);assert.equal(observation.counts.returned,0);}if(boundaryControl.id==='B04'){assert.equal(observation.counts.returned,1);assert.equal(observation.counts.settled,1);}}catch(error){record.status='FAIL';record.failure=reason(error);}state.boundaryControls.push(record);}
  else{assert.equal(result.code,captured.status==='PASS'?0:1);state.runtime.push(captured);}
  return captured;
}
try{
  guard('BEFORE_B01');const focused=read(resolve(recipe,'FOCUSED-CONTROLS.json'));assert.equal(focused.manifestSha256,request.preparationSha256);assert.equal(focused.requestSha256,requestHash);assert.equal(focused.passed,7);assert.equal(focused.failed,0);
  const source=resolve(work,'source'),materialized=materializeInputs(binding,request,source,state.git);guarded.set(source,inventory(source));state.materialization=materialized.proof;
  save(resolve(raw,'PRE-RUN-BINDINGS.json'),{requestHash,preparationSha256:request.preparationSha256,inputs:materialized.inputs,tools:binding.tools,priorComposition:continuation.composition,pristineAndPatchedHashesAuthenticated:true,noBuildPackTypeReplay:true});
  const consumer=resolve(work,'B01-consumer');fs.mkdirSync(consumer);save(resolve(consumer,'package.json'),{private:true,type:'module'});
  const captured=await runtime('B01',source,consumer,'R12',undefined,continuation.boundaryControl);assert.equal(state.boundaryControls.length,1);assert.equal(state.boundaryControls[0].status,'KILLED','UNCHANGED_B01_QUALIFIER_REQUIRED');
  const before=captured.observations.find(row=>row.kind==='R12-raw-before-assertion'),after=captured.observations.find(row=>row.kind==='B01-rethrow-identity');assertCaptureReceipt(before,after);
  assert.equal(captured.cleanup.pending,0);assert.equal(captured.cleanup.timers,0);assert.deepEqual(captured.cleanup.unhandled,[]);assert.deepEqual(captured.cleanup.disposalRejections,[]);
  const loads=fs.readFileSync(resolve(raw,'B01-R12/loads.jsonl'),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse),helperProof=[];
  for(const name of ['capture.mjs','boundaries.mjs','runtime.mjs']){const filename=resolve(recipe,name),expected=fileHash(filename),row=loads.find(value=>value.kind==='actual-module-load'&&value.path===filename);assert.ok(row,'ACTUAL_CAPTURE_HELPER_LOAD');assert.equal(row.sha256,expected);helperProof.push({path:name,sha256:expected});}
  state.captureQualification={status:'PASS',unchangedBoundaryQualifierPassed:true,before,after,helperProof,cleanup:captured.cleanup};state.boundComposition=continuation.composition;
  assert.equal(state.children.length,1);assert.equal(state.runtime.length,0);assert.equal(state.mutants.length,0);state.status='COMPOSED_SCOPED_PUBLIC_TIMEOUT78_REVIEW_PASSED';
}catch(error){state.status='B01_CAPTURE_REVIEW_FINDINGS';state.failure=reason(error);process.exitCode=1;}
finally{
  try{guard('FINAL');for(const row of state.children)if(row.pid)absent(row.pid);state.allChildrenReaped=true;}catch(error){state.status='STOP_NO_RETRY';state.finalFailure=reason(error);process.exitCode=1;}
  state.finishedAt=new Date().toISOString();state.unexecutedBoundaryControls=state.boundaryControls.length?[]:['B01'];
  if(state.allChildrenReaped)try{state.archive=archiveEvidence({run,raw,work,children:state.children,remove:state.status!=='STOP_NO_RETRY'});}catch(error){state.status='STOP_NO_RETRY';state.archiveFailure=reason(error);process.exitCode=1;}
  save(resolve(run,'RESULT.json'),state);console.log(JSON.stringify({status:state.status,boundaryControls:state.boundaryControls.length,children:state.children.length,reaped:state.allChildrenReaped,positiveFamilies:0,types:0,builds:0,packs:0,productMutants:0,rootRatificationPending:true}));
}
