import assert from 'node:assert/strict';
import fs from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { resolve } from 'node:path';
import { recipe,read,save,fileHash,sha,authenticatePreparation } from './common.mjs';
const result=read(resolve(recipe,'runs/b01-01/RESULT.json'));authenticatePreparation(result.preparationSha256);
assert.equal(result.status,'COMPOSED_SCOPED_PUBLIC_TIMEOUT78_REVIEW_PASSED');assert.equal(result.captureQualification.status,'PASS');assert.equal(result.boundaryControls[0].status,'KILLED');
const archivePath=resolve(recipe,'runs/b01-01/RECEIPTS.json.gz');assert.equal(fileHash(archivePath),result.archive.archiveSha256);const archive=JSON.parse(gunzipSync(fs.readFileSync(archivePath),{maxOutputLength:128*1024**2}));for(const row of archive.rows){const bytes=Buffer.from(row.base64,'base64');assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);}
const captured=result.boundaryControls[0].result;
const review={schema:'timeout-public78-final-composed-independent-review/1',postProcessingOnly:true,at:new Date().toISOString(),verdict:'PASS_SCOPED_COMPOSED_PUBLIC_TIMEOUT78',rootRatificationPending:true,remainingInScopeBlocker:null,candidate:result.candidate,baseline:result.baseline,module:result.module,recipeCommit:'ef511785',recipeManifestSha256:result.preparationSha256,requestSha256:result.requestHash,resultSha256:fileHash(resolve(recipe,'runs/b01-01/RESULT.json')),actualB01:{startedAt:result.startedAt,finishedAt:result.finishedAt,attempts:result.attempts,retries:result.retries,status:result.boundaryControls[0].status,actualExpectedFailure:captured.failure,qualification:result.captureQualification,moduleLoads:captured.loadProof.actualModuleLoads,sourceAdapter:true,pluginAdmissions:captured.pluginAdmissions,cleanup:captured.cleanup},focusedControls:read(resolve(recipe,'FOCUSED-CONTROLS.json')),children:result.children.map(row=>({label:row.label,pid:row.pid,exit:row.exit,close:row.close,reaped:row.reaped,forced:row.forced})),synchronousGitChildren:result.git.length,integrityGuards:result.guards.length,composition:{...result.boundComposition,boundaryControls:{priorQualified:['B02','B03','B04'],newQualified:['B01'],composed:4,oldThreeOfFourUnchanged:true}},currentReplayCounts:{positiveFamilies:result.positiveFamiliesExecuted,types:result.typeConsumersExecuted,builds:result.buildsExecuted,packs:result.packsExecuted,productMutants:result.productMutantsExecuted},unexecuted:result.unexecutedBoundaryControls,archive:{...result.archive,bytes:fs.statSync(archivePath).size},historicalFailuresUnchanged:true,missingOldNumbersNotReconstructed:true,wholeHistoryProof:false,fullGate:false,native:0,safeJS:0};
save(resolve(recipe,'REVIEW.json'),review);console.log(JSON.stringify({verdict:review.verdict,blocker:review.remainingInScopeBlocker,composedRuntime:review.composition.runtime,retainedTypes:review.composition.boundTypes,productMutants:review.composition.boundProductMutants,boundaryControls:review.composition.boundaryControls,currentReplayCounts:review.currentReplayCounts,B01Counts:review.actualB01.qualification.before.counts,sameReason:review.actualB01.qualification.after.sameReason,children:review.children.length,loads:review.actualB01.moduleLoads,guards:review.integrityGuards,archive:review.archive,reviewSha256:fileHash(resolve(recipe,'REVIEW.json'))},null,2));
