import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Mustache from "mustache";
import type { McpSpawnConfig, SpawnResult } from "@poe-code/agent-spawn";
import { runCommand, spawn } from "@poe-code/agent-spawn";
import { S } from "@poe-code/cmdkit-schema";
import { UserError, defineCommand, defineGroup } from "@poe-code/cmdkit";
import type { Group } from "@poe-code/cmdkit";
import { discoverAutomations, loadAutomation } from "./discover.js";
import { checkUserAllow } from "./exec/check-user-allow.js";
import { requireCommentPrefix } from "./exec/require-comment-prefix.js";
import type { AutomationDefinition } from "./types.js";

const builtInPromptsDir = fileURLToPath(new URL("./prompts", import.meta.url));
const originalMustacheEscape = Mustache.escape;

interface RunItemResult {
  prompt: string;
  result: SpawnResult;
}

interface RunAutomationResult {
  agent: string;
  automation: string;
  items: RunItemResult[];
}

interface InstallTemplate {
  caller: string;
  ejected: string;
}

const installTemplates: Record<string, InstallTemplate> = {
  "github-issue-opened": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install github-issue-opened",
      "name: 'GitHub: Issue Opened'",
      "on:",
      "  issues:",
      "    types: [opened]",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-github-issue-opened.yml@main",
      "    secrets: inherit",
      "    with:",
      "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install github-issue-opened",
      "# Edit .poe-code/github-workflows/github-issue-opened.md to customize the prompt.",
      "name: 'GitHub: Issue Opened'",
      "on:",
      "  issues:",
      "    types: [opened]",
      "",
      "concurrency:",
      "  group: agent-issue-${{ github.event.issue.number }}",
      "  cancel-in-progress: true",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: write",
      "      issues: write",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows github-issue-opened --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          ISSUE_NUMBER: ${{ github.event.issue.number }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "github-issue-comment-created": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install github-issue-comment-created",
      "name: 'GitHub: Issue Comment Created'",
      "on:",
      "  issue_comment:",
      "    types: [created]",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-github-issue-comment-created.yml@main",
      "    secrets: inherit",
      "    with:",
      "      ISSUE_NUMBER: ${{ github.event.issue.number }}",
      "      ISSUE_STATE: ${{ github.event.issue.state }}",
      "      COMMENT_BODY: ${{ github.event.comment.body }}",
      "      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}",
      "      COMMENT_AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}",
      "      COMMENT_USER_TYPE: ${{ github.event.comment.user.type }}",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install github-issue-comment-created",
      "# Edit .poe-code/github-workflows/github-issue-comment-created.md to customize the prompt.",
      "name: 'GitHub: Issue Comment Created'",
      "on:",
      "  issue_comment:",
      "    types: [created]",
      "",
      "concurrency:",
      "  group: agent-issue-${{ github.event.issue.number }}",
      "  cancel-in-progress: true",
      "",
      "jobs:",
      "  run:",
      "    if: github.event.issue.state == 'open' && github.event.comment.user.type != 'Bot'",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: write",
      "      issues: write",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows exec check-user-allow github-issue-comment-created",
      "        env:",
      "          COMMENT_AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}",
      "      - run: npx poe-code github-workflows exec require-comment-prefix github-issue-comment-created",
      "        env:",
      "          COMMENT_BODY: ${{ github.event.comment.body }}",
      "      - run: npx poe-code github-workflows github-issue-comment-created --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          ISSUE_NUMBER: ${{ github.event.issue.number }}",
      "          COMMENT_BODY: ${{ github.event.comment.body }}",
      "          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "github-pull-request-opened": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install github-pull-request-opened",
      "name: 'GitHub: Pull Request Opened'",
      "on:",
      "  pull_request:",
      "    types: [opened, ready_for_review]",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-github-pull-request-opened.yml@main",
      "    secrets: inherit",
      "    with:",
      "      PR_NUMBER: ${{ github.event.pull_request.number }}",
      "      PR_TITLE: ${{ github.event.pull_request.title }}",
      "      PR_AUTHOR: ${{ github.event.pull_request.user.login }}",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install github-pull-request-opened",
      "# Edit .poe-code/github-workflows/github-pull-request-opened.md to customize the prompt.",
      "name: 'GitHub: Pull Request Opened'",
      "on:",
      "  pull_request:",
      "    types: [opened, ready_for_review]",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: read",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows github-pull-request-opened --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          PR_NUMBER: ${{ github.event.pull_request.number }}",
      "          PR_TITLE: ${{ github.event.pull_request.title }}",
      "          PR_AUTHOR: ${{ github.event.pull_request.user.login }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "github-pull-request-synchronized": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install github-pull-request-synchronized",
      "name: 'GitHub: Pull Request Synchronized'",
      "on:",
      "  pull_request:",
      "    types: [synchronize]",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-github-pull-request-synchronized.yml@main",
      "    secrets: inherit",
      "    with:",
      "      PR_NUMBER: ${{ github.event.pull_request.number }}",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install github-pull-request-synchronized",
      "# Edit .poe-code/github-workflows/github-pull-request-synchronized.md to customize the prompt.",
      "name: 'GitHub: Pull Request Synchronized'",
      "on:",
      "  pull_request:",
      "    types: [synchronize]",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: read",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows github-pull-request-synchronized --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          PR_NUMBER: ${{ github.event.pull_request.number }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "fix-vulnerabilities": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install fix-vulnerabilities",
      "name: 'Fix Vulnerabilities'",
      "on:",
      "  schedule:",
      "    - cron: '0 6 * * 1'",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-fix-vulnerabilities.yml@main",
      "    secrets: inherit",
      "    with:",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install fix-vulnerabilities",
      "# Edit .poe-code/github-workflows/fix-vulnerabilities.md to customize the prompt.",
      "name: 'Fix Vulnerabilities'",
      "on:",
      "  schedule:",
      "    - cron: '0 6 * * 1'",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: write",
      "      pull-requests: write",
      "      security-events: read",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows fix-vulnerabilities --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "update-dependencies": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install update-dependencies",
      "name: 'Update Dependencies'",
      "on:",
      "  schedule:",
      "    - cron: '0 6 * * 1'",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-update-dependencies.yml@main",
      "    secrets: inherit",
      "    with:",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install update-dependencies",
      "# Edit .poe-code/github-workflows/update-dependencies.md to customize the prompt.",
      "name: 'Update Dependencies'",
      "on:",
      "  schedule:",
      "    - cron: '0 6 * * 1'",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: write",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - run: npx poe-code github-workflows update-dependencies --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  },
  "update-documentation": {
    caller: [
      "# Auto-generated by: poe-code github-workflows install update-documentation",
      "name: 'Update Documentation'",
      "on:",
      "  push:",
      "    branches: [main]",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    uses: poe-code/poe-setup-scripts/.github/workflows/gh-update-documentation.yml@main",
      "    secrets: inherit",
      "    with:",
      "      GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n"),
    ejected: [
      "# Auto-generated by: poe-code github-workflows install update-documentation",
      "# Edit .poe-code/github-workflows/update-documentation.md to customize the prompt.",
      "name: 'Update Documentation'",
      "on:",
      "  push:",
      "    branches: [main]",
      "  workflow_dispatch:",
      "",
      "jobs:",
      "  run:",
      "    runs-on: ubuntu-latest",
      "    permissions:",
      "      contents: write",
      "      pull-requests: write",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "        with:",
      "          fetch-depth: 20",
      "      - run: npx poe-code github-workflows update-documentation --yes",
      "        env:",
      "          POE_API_KEY: ${{ secrets.POE_API_KEY }}",
      "          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
      "          GITHUB_REPOSITORY: ${{ github.repository }}"
    ].join("\n")
  }
};

const runCommandDef = defineCommand({
  name: "run",
  description: "Run a GitHub automation.",
  positional: ["name"],
  params: S.Object({
    name: S.String(),
    agent: S.Optional(S.String()),
    model: S.Optional(S.String()),
    mode: S.Optional(S.Enum(["yolo", "edit", "read"] as const)),
    cwd: S.Optional(S.String())
  }),
  secrets: {
    poeApiKey: { env: "POE_API_KEY" },
    githubToken: { env: "GITHUB_TOKEN", optional: true }
  },
  scope: ["cli", "sdk"],
  handler: async ({ params, env, secrets }) => {
    const cwd = resolveCwd(params.cwd);
    const automation = await loadNamedAutomation(params.name, cwd);
    const agent = automation.agent ?? params.agent ?? "codex";
    const sharedTemplateContext = buildTemplateContext(env);

    if (automation.source === undefined) {
      const prompt = renderPrompt(automation.prompt, sharedTemplateContext);
      return {
        automation: automation.name,
        agent,
        items: [
          {
            prompt,
            result: await spawn(agent, {
              prompt,
              cwd,
              ...(params.model === undefined ? {} : { model: params.model }),
              ...(params.mode === undefined ? {} : { mode: params.mode }),
              ...(automation.mcp === undefined
                ? {}
                : { mcpServers: resolveMcpConfig(automation.mcp, env) })
            })
          }
        ]
      } satisfies RunAutomationResult;
    }

    const sourceResult = await runCommand("sh", ["-c", resolveSourceCommand(automation.source, env)], {
      cwd,
      env: buildCommandEnv(env, secrets)
    });

    if (sourceResult.exitCode !== 0) {
      throw new UserError(
        `Automation "${automation.name}" source command failed with exit code ${sourceResult.exitCode}.`
      );
    }

    const items = parseSourceItems(automation.name, sourceResult.stdout);
    const results: RunItemResult[] = [];

    for (const item of items) {
      const prompt = renderPrompt(automation.prompt, buildPerItemTemplateContext(item, sharedTemplateContext));
      results.push({
        prompt,
        result: await spawn(agent, {
          prompt,
          cwd,
          ...(params.model === undefined ? {} : { model: params.model }),
          ...(params.mode === undefined ? {} : { mode: params.mode }),
          ...(automation.mcp === undefined
            ? {}
            : { mcpServers: resolveMcpConfig(automation.mcp, env) })
        })
      });
    }

    return {
      automation: automation.name,
      agent,
      items: results
    } satisfies RunAutomationResult;
  },
  render: {
    rich: (result: RunAutomationResult, { logger }) => {
      const total = result.items.length;
      const succeeded = result.items.filter((item) => item.result.exitCode === 0).length;
      logger.success(
        `Ran automation "${result.automation}" with agent "${result.agent}" for ${total} item${total === 1 ? "" : "s"}.`
      );
      logger.message(`${succeeded}/${total} run${total === 1 ? "" : "s"} exited successfully.`);
    },
    json: (result: RunAutomationResult) => result
  }
});

const listCommand = defineCommand({
  name: "list",
  description: "List available automations.",
  params: S.Object({}),
  scope: ["cli", "sdk"],
  handler: async () => discoverAutomations(builtInPromptsDir, projectPromptsDir(resolveCwd())),
  render: {
    rich: (automations: AutomationDefinition[], { logger, renderTable, getTheme }) => {
      logger.message(
        renderTable({
          theme: getTheme(),
          columns: [
            { name: "name", title: "Name", alignment: "left", maxLen: 40 },
            { name: "agent", title: "Agent", alignment: "left", maxLen: 24 },
            { name: "source", title: "Source", alignment: "left", maxLen: 12 }
          ],
          rows: automations.map((automation) => ({
            name: automation.name,
            agent: automation.agent ?? "",
            source: automation.source === undefined ? "direct" : "source"
          }))
        })
      );
    },
    json: (automations: AutomationDefinition[]) => automations
  }
});

const installCommand = defineCommand({
  name: "install",
  description: "Install an automation workflow into the current repo.",
  positional: ["name"],
  params: S.Object({
    name: S.String(),
    eject: S.Optional(S.Boolean())
  }),
  scope: ["cli"],
  handler: async ({ params }) => {
    const template = installTemplates[params.name];
    if (template === undefined) {
      throw new UserError(`Automation "${params.name}" cannot be installed.`);
    }

    const rawPrompt = await readBuiltInPromptFile(params.name);
    const cwd = resolveCwd();
    const promptPath = path.join(projectPromptsDir(cwd), `${params.name}.md`);
    const workflowPath = path.join(cwd, ".github", "workflows", `gh-${params.name}.yml`);

    await mkdir(path.dirname(promptPath), { recursive: true });
    await mkdir(path.dirname(workflowPath), { recursive: true });
    await writeFile(promptPath, rawPrompt, "utf8");
    await writeFile(workflowPath, params.eject === true ? template.ejected : template.caller, "utf8");

    return {
      workflowPath,
      promptPath,
      ejected: params.eject === true
    };
  },
  render: {
    rich: (result: { workflowPath: string; promptPath: string; ejected: boolean }, { logger }) => {
      logger.success(`Installed workflow at ${result.workflowPath}`);
      logger.message(`Prompt copied to ${result.promptPath}`);
    },
    json: (result: { workflowPath: string; promptPath: string; ejected: boolean }) => result
  }
});

const uninstallCommand = defineCommand({
  name: "uninstall",
  description: "Remove an installed automation workflow from the current repo.",
  positional: ["name"],
  params: S.Object({
    name: S.String()
  }),
  scope: ["cli"],
  handler: async ({ params }) => {
    const workflowPath = path.join(resolveCwd(), ".github", "workflows", `gh-${params.name}.yml`);

    try {
      await unlink(workflowPath);
    } catch (error) {
      if (!isMissingPathError(error)) {
        throw error;
      }
    }

    return {
      workflowPath
    };
  },
  render: {
    rich: (result: { workflowPath: string }, { logger }) => {
      logger.success(`Removed workflow ${result.workflowPath}`);
    },
    json: (result: { workflowPath: string }) => result
  }
});

const checkUserAllowCommand = defineCommand({
  name: "check-user-allow",
  description: "Fail when COMMENT_AUTHOR_ASSOCIATION is not allowed by the automation frontmatter.",
  positional: ["name"],
  params: S.Object({
    name: S.String()
  }),
  scope: ["cli"],
  handler: async ({ params, env }) => {
    const automation = await loadNamedAutomation(params.name, resolveCwd());
    checkUserAllow(automation, env.get("COMMENT_AUTHOR_ASSOCIATION"));
    return null;
  }
});

const requireCommentPrefixCommand = defineCommand({
  name: "require-comment-prefix",
  description: "Fail when COMMENT_BODY does not start with the automation prefix frontmatter.",
  positional: ["name"],
  params: S.Object({
    name: S.String()
  }),
  scope: ["cli"],
  handler: async ({ params, env }) => {
    const automation = await loadNamedAutomation(params.name, resolveCwd());
    requireCommentPrefix(automation, env.get("COMMENT_BODY"));
    return null;
  }
});

const execGroup = defineGroup({
  name: "exec",
  description: "Workflow step helpers.",
  scope: ["cli"],
  children: [checkUserAllowCommand, requireCommentPrefixCommand]
});

export const ghGroup: Group = defineGroup({
  name: "github-workflows",
  aliases: ["gh"],
  description: "GitHub workflow automations.",
  children: [runCommandDef, listCommand, installCommand, uninstallCommand, execGroup],
  default: runCommandDef
});

async function loadNamedAutomation(name: string, cwd: string): Promise<AutomationDefinition> {
  const automation = await loadAutomation(name, [projectPromptsDir(cwd), builtInPromptsDir]);
  if (automation === undefined) {
    throw new UserError(`Automation "${name}" was not found.`);
  }
  return automation;
}

async function readBuiltInPromptFile(name: string): Promise<string> {
  try {
    return await readFile(path.join(builtInPromptsDir, `${name}.md`), "utf8");
  } catch (error) {
    if (isMissingPathError(error)) {
      throw new UserError(`Automation "${name}" was not found.`);
    }
    throw error;
  }
}

function projectPromptsDir(cwd: string): string {
  return path.join(cwd, ".poe-code", "github-workflows");
}

function resolveCwd(cwd?: string): string {
  return cwd ?? process.cwd();
}

function buildCommandEnv(
  env: { get(key: string): string | undefined },
  secrets: Record<string, string | undefined>
): Record<string, string | undefined> {
  const values: Record<string, string | undefined> = {
    POE_API_KEY: secrets.poeApiKey,
    GITHUB_TOKEN: secrets.githubToken
  };

  for (const key of [
    "GITHUB_REPOSITORY",
    "ISSUE_NUMBER",
    "ISSUE_TITLE",
    "COMMENT_AUTHOR",
    "COMMENT_BODY",
    "PR_NUMBER",
    "PR_TITLE",
    "PR_AUTHOR"
  ]) {
    const value = env.get(key);
    if (value !== undefined) {
      values[key] = value;
    }
  }

  return values;
}

function buildTemplateContext(env: { get(key: string): string | undefined }): Record<string, unknown> {
  const repo = env.get("GITHUB_REPOSITORY");
  const issueNumber = env.get("ISSUE_NUMBER");
  const prNumber = env.get("PR_NUMBER");

  return {
    ...(repo === undefined ? {} : { repo }),
    ...(buildUrl(repo, issueNumber, prNumber) === undefined
      ? {}
      : { url: buildUrl(repo, issueNumber, prNumber) }),
    issue: pruneUndefined({
      number: issueNumber,
      title: env.get("ISSUE_TITLE")
    }),
    comment: pruneUndefined({
      author: env.get("COMMENT_AUTHOR"),
      body: env.get("COMMENT_BODY")
    }),
    pr: pruneUndefined({
      number: prNumber,
      title: env.get("PR_TITLE"),
      author: env.get("PR_AUTHOR")
    })
  };
}

function buildUrl(
  repo: string | undefined,
  issueNumber: string | undefined,
  prNumber: string | undefined
): string | undefined {
  if (repo === undefined) {
    return undefined;
  }

  if (issueNumber !== undefined) {
    return `https://github.com/${repo}/issues/${issueNumber}`;
  }

  if (prNumber !== undefined) {
    return `https://github.com/${repo}/pull/${prNumber}`;
  }

  return undefined;
}

function pruneUndefined(record: Record<string, string | undefined>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(record).filter((entry): entry is [string, string] => entry[1] !== undefined)
  );
}

function parseSourceItems(name: string, stdout: string): unknown[] {
  let parsed: unknown;

  try {
    parsed = JSON.parse(stdout);
  } catch {
    throw new UserError(`Automation "${name}" source command did not return valid JSON.`);
  }

  if (!Array.isArray(parsed)) {
    throw new UserError(`Automation "${name}" source command must return a JSON array.`);
  }

  return parsed;
}

function buildPerItemTemplateContext(
  item: unknown,
  sharedContext: Record<string, unknown>
): Record<string, unknown> {
  if (isRecord(item)) {
    return {
      ...sharedContext,
      ...item
    };
  }

  return {
    ...sharedContext,
    item
  };
}

function renderPrompt(template: string, view: Record<string, unknown>): string {
  Mustache.escape = (value: string) => value;
  try {
    return Mustache.render(template, view);
  } finally {
    Mustache.escape = originalMustacheEscape;
  }
}

function resolveSourceCommand(
  source: string,
  env: { get(key: string): string | undefined }
): string {
  const repo = env.get("GITHUB_REPOSITORY");
  if (repo === undefined) {
    return source;
  }

  const slashIndex = repo.indexOf("/");
  if (slashIndex < 0) {
    return source.split("{repo}").join(repo);
  }

  const owner = repo.slice(0, slashIndex);
  const repoName = repo.slice(slashIndex + 1);

  return source.split("{owner}").join(owner).split("{repo}").join(repoName);
}

function resolveMcpConfig(
  mcp: McpSpawnConfig,
  env: { get(key: string): string | undefined }
): McpSpawnConfig {
  return Object.fromEntries(
    Object.entries(mcp).map(([serverName, server]) => [
      serverName,
      {
        command: server.command,
        ...(server.args === undefined ? {} : { args: [...server.args] }),
        ...(server.env === undefined
          ? {}
          : {
              env: Object.fromEntries(
                Object.entries(server.env).map(([key, value]) => [key, resolveEnvInterpolation(value, env)])
              )
            })
      }
    ])
  );
}

function resolveEnvInterpolation(
  value: string,
  env: { get(key: string): string | undefined }
): string {
  if (!value.startsWith("${{") || !value.endsWith("}}")) {
    return value;
  }

  const key = value.slice(3, -2).trim();
  return env.get(key) ?? "";
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isMissingPathError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error && error.code === "ENOENT";
}
