import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import {createHash} from 'node:crypto';
import {dirname,join,resolve,relative} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {registerHooks,syncBuiltinESMExports} from 'node:module';
import childProcess from 'node:child_process';
const directory=dirname(fileURLToPath(import.meta.url)),repository=resolve(directory,'../../../../..'),binding=JSON.parse(fs.readFileSync(join(directory,'PLAN.json'))).bindings;
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const data=join(directory,'data-completion');assert.ok(!fs.existsSync(data));fs.mkdirSync(data);process.chdir(data);
const report={schema:'unified76-independent-final-component-completion/v4.2',started:new Date().toISOString(),bindings:binding,groups:[],sources:[],commands:[],trace:[],children:[],wholeGateLaunched:false,rootRelease:'HOLD'};
const preserved=Object.fromEntries(fs.readdirSync(directory).filter(name=>fs.lstatSync(join(directory,name)).isFile()&&name!=='COMPLETION-EXECUTION.txt').map(name=>[name,sha(fs.readFileSync(join(directory,name)))]));
const clean=()=>Object.fromEntries(Object.entries(process.env).filter(([key])=>!(/^(GIT_|DYLD_|LD_)/u.test(key)||['NODE_OPTIONS','NODE_PATH'].includes(key))));
const command=(executable,args,options={})=>{const answer=childProcess.spawnSync(executable,args,{cwd:data,env:{...clean(),HOME:data,TMPDIR:data},timeout:240000,maxBuffer:8388608,...options});const stdout=Buffer.from(answer.stdout??''),stderr=Buffer.from(answer.stderr??'');report.commands.push({executable,args,cwd:options.cwd??data,status:answer.status,signal:answer.signal,error:answer.error?.message,stdoutBytes:stdout.length,stdoutSha256:sha(stdout),stderrBytes:stderr.length,stderrSha256:sha(stderr),stdout:stdout.length<=16384?stdout.toString():undefined,stderr:stderr.toString()});return{...answer,stdout,stderr};};
const git=(args,cwd=repository,options={})=>{const answer=command(binding.git,['--no-replace-objects',...args],{cwd,...options});assert.equal(answer.status,0,answer.stderr.toString());assert.equal(answer.signal,null);return answer.stdout;};
const blob=path=>{const size=Number(git(['cat-file','-s',binding.driver+':'+binding.prefix+path]));assert.ok(size<=8388608);const bytes=git(['show',binding.driver+':'+binding.prefix+path]);assert.equal(bytes.length,size);return bytes;};
const seal=JSON.parse(blob('DRIVER.json')),staged=[];
for(const name of [...Object.keys(seal.files),'DRIVER.json']){const bytes=blob(name),path=join(directory,name);assert.ok(!fs.existsSync(path));assert.equal(sha(bytes),name==='DRIVER.json'?binding.driverFileSha256:seal.files[name]);fs.writeFileSync(path,bytes,{flag:'wx'});staged.push(path);report.sources.push({path,name,sha256:sha(bytes),revision:binding.driver});}
const allowed=new Map(report.sources.map(source=>[source.path,source.sha256]));
const originalSpawn=childProcess.spawn;
childProcess.spawn=function(executable,args,options){assert.equal(executable,binding.git);assert.ok(!args.some(argument=>/\b(worker|execute)\.mjs\b/u.test(String(argument))));const child=originalSpawn(executable,args,options),record={executable,args,pid:child.pid,started:Date.now(),closed:false};report.children.push(record);const timeout=setTimeout(()=>{record.independentTimeout=true;try{process.kill(-child.pid,'SIGKILL');}catch{}},240000);child.once('close',(status,signal)=>{clearTimeout(timeout);Object.assign(record,{closed:true,status,signal,elapsedMs:Date.now()-record.started});});return child;};syncBuiltinESMExports();
const hooks=registerHooks({resolve(specifier,context,next){const resolved=next(specifier,context);if(!resolved.url.startsWith('node:')){const path=fs.realpathSync(fileURLToPath(resolved.url));assert.ok(allowed.has(path));assert.ok(!['execute.mjs','public.mjs','controls.mjs'].includes(relative(directory,path)));assert.equal(sha(fs.readFileSync(path)),allowed.get(path));report.trace.push({specifier,parent:context.parentURL,path,sha256:allowed.get(path)});}return resolved;},load(url,context,next){if(!url.startsWith('node:')){const path=fileURLToPath(url);assert.ok(allowed.has(path));assert.ok(!['execute.mjs','public.mjs','controls.mjs'].includes(relative(directory,path)));assert.equal(sha(fs.readFileSync(path)),allowed.get(path));}return next(url,context);}});
const module=name=>import(pathToFileURL(join(directory,name)));
const fresh=name=>{const path=join(data,name);fs.mkdirSync(path);return path;};
const entry=(path,text,mode='100644')=>({path,mode,bytes:Buffer.byteLength(text),blob:createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0`).update(text).digest('hex')});
let group,inventory;
const check=async(name,operation)=>{try{group.controls.push({name,status:'PASS',detail:await operation()});}catch(error){group.controls.push({name,status:'FAIL',error:String(error).slice(0,4000),stack:error.stack?.slice(0,8000)});}};
const reject=(name,operation)=>check(name,async()=>{try{await operation();}catch(error){return{rejected:true,error:String(error).slice(0,2000)};}assert.fail('Unexpected acceptance');});
const run=async(id,operation)=>{group={id,controls:[]};report.groups.push(group);console.log(id+' COMPLETION START');try{await operation();}catch(error){group.controls.push({name:'infrastructure',status:'FAIL',error:String(error),stack:error.stack});}group.status=group.controls.some(control=>control.status==='FAIL')?'FAIL':'PASS';console.log(id+' COMPLETION '+group.status);};
try{
  inventory=await module('inventory.mjs');const transport=await module('transport.mjs'),policy=await module('policy.mjs');
  await run('A06',async()=>{
    const root=fresh('archive'),expected=[entry('input.mjs','fixed'),entry('link','input.mjs','120000')];fs.writeFileSync(join(root,'input.mjs'),'fixed');report.reviewOnlySetupTool={origin:'/bin/ln',physical:fs.realpathSync('/bin/ln'),sha256:sha(fs.readFileSync('/bin/ln')),qualification:'Review-owned fixture setup only; not an oracle or gate dependency substitute'};
    const link=(target,name)=>{const path=join(root,name);assert.ok(path.startsWith(root+'/'));assert.ok(['input.mjs','link','../archive/input.mjs'].includes(target));const answer=command('/bin/ln',['-s',target,path]);assert.equal(answer.status,0,answer.stderr.toString());};
    link('input.mjs','link');await check('actual archive accepts regular origin and declared contained fixture link',()=>inventory.verifyArchive(root,expected));
    fs.unlinkSync(join(root,'input.mjs'));link('link','input.mjs');await reject('actual source-origin link substitution',()=>inventory.verifyArchive(root,expected));fs.unlinkSync(join(root,'input.mjs'));fs.writeFileSync(join(root,'input.mjs'),'fixed');fs.unlinkSync(join(root,'link'));link('../archive/input.mjs','link');await reject('actual archive rejects lexical escaping fixture link',()=>inventory.verifyArchive(root,[expected[0],entry('link','../archive/input.mjs','120000')]));fs.unlinkSync(join(root,'link'));link('input.mjs','link');fs.writeFileSync(join(root,'new.json'),'{}');await reject('actual archive rejects new input',()=>inventory.verifyArchive(root,expected));
  });
  let tiny,commit,entries;
  await run('A12',async()=>{
    tiny=fresh('tiny-git');git(['init','--quiet',tiny]);fs.writeFileSync(join(tiny,'helper.mjs'),'export const marker=76;\n');fs.writeFileSync(join(tiny,'golden'),'golden\n');git(['add','--','helper.mjs','golden'],tiny);git(['-c','user.name=Independent bounded fixture','-c','user.email=bounded@example.invalid','-c','core.hooksPath=/dev/null','commit','--quiet','-m','Tiny regular transport'],tiny);commit=git(['rev-parse','HEAD'],tiny).toString().trim();entries=git(['ls-tree','-rlz','HEAD'],tiny).toString().split('\0').filter(Boolean).map(line=>{const match=/^(\d+) blob ([a-f0-9]{40})\s+(\d+)\t(.+)$/u.exec(line);return{path:match[4],mode:match[1],blob:match[2],bytes:Number(match[3])};});const bounds={...policy.BOUNDS,archiveEntries:entries.length,archiveBytes:entries.reduce((sum,item)=>sum+item.bytes,0)};
    await check('actual small streamed extraction and independently compared bytes',async()=>{const destination=fresh('extracted'),receipt=await transport.extractCommitted({git:binding.git,repository:tiny,candidate:commit,entries,destination,environment:clean(),bounds});assert.ok(receipt.transferBytes<1048576);return{receipt,verified:await inventory.verifyArchive(destination,entries)};});
    await check('actual reachable-object stream into owned Git database',async()=>{const destination=fresh('history');git(['init','--quiet',destination]);const receipt=await transport.transferHistory({git:binding.git,repository:tiny,candidate:commit,destination,environment:clean()});assert.ok(receipt.bytes<=8388608);assert.equal(git(['cat-file','-t',commit],destination).toString().trim(),'commit');return receipt;});
    for(const mutation of ['wrong-size','missing-object'])await reject('actual transport '+mutation,()=>{const changed=structuredClone(entries);if(mutation==='wrong-size')changed[0].bytes++;else changed[0].blob='0'.repeat(40);return transport.extractCommitted({git:binding.git,repository:tiny,candidate:commit,entries:changed,destination:fresh(mutation),environment:clean(),bounds:{...bounds,archiveBytes:changed.reduce((sum,item)=>sum+item.bytes,0)}});});await reject('charge beyond reviewed small limit',()=>policy.enforceCharge(64,1,64));
  });
  await run('A13',async()=>{
    for(const path of ['../escape','/absolute','.git/config','a/../b','a\\b'])await reject('actual path refusal '+path,()=>transport.validateEntries([entry(path,'x')],{archiveEntries:1,archiveBytes:1}));await reject('duplicate path',()=>transport.validateEntries([entry('a','x'),entry('a','x')],{archiveEntries:2,archiveBytes:2}));await reject('declared link ancestor',()=>transport.validateEntries([entry('a','x','120000'),entry('a/b','x')],{archiveEntries:2,archiveBytes:2}));
    const object=git(['hash-object','-w','--stdin'],tiny,{input:Buffer.from('../outside')}).toString().trim(),item={...entry('escape','../outside','120000'),blob:object};await reject('actual streamed escape target rejected before link creation',()=>transport.extractCommitted({git:binding.git,repository:tiny,candidate:commit,entries:[item],destination:fresh('escape-target'),environment:clean(),bounds:{archiveEntries:1,archiveBytes:item.bytes}}));await check('no outside-owned destination effect',()=>assert.equal(fs.existsSync(join(data,'outside')),false));
  });
  await run('A20',async()=>{
    const before=await inventory.capture(data),argv=process.argv;process.argv=[binding.node,join(directory,'run.mjs'),'--candidate',binding.candidate,'--run'];const launcher=await module('run.mjs');await module('worker.mjs');process.argv=argv;await check('actual run and worker imports remain inert',async()=>assert.deepEqual(inventory.compare(before,await inventory.capture(data)),[]));
    await check('actual clean-environment unreleased --run refuses before product',async()=>{const removed={};for(const[key,value]of Object.entries(process.env))if(/^(GIT_|DYLD_|LD_)/u.test(key)||['NODE_OPTIONS','NODE_PATH'].includes(key)){removed[key]=value;delete process.env[key];}let error;try{await launcher.main(['--candidate',binding.candidate,'--run','/tmp/full-gate-unified76-independent-never-created','--release',join(data,'NO-RELEASE.json'),'--committed-archive']);}catch(observed){error=observed;}finally{for(const key of Object.keys(process.env))if(/^(GIT_|DYLD_|LD_)/u.test(key)||['NODE_OPTIONS','NODE_PATH'].includes(key))delete process.env[key];Object.assign(process.env,removed);}assert.ok(error);assert.equal(error.code,'ENOENT',String(error));assert.match(error.message,/NO-RELEASE/u);assert.equal(fs.existsSync('/tmp/full-gate-unified76-independent-never-created'),false);assert.ok(!report.trace.some(item=>item.path===join(directory,'execute.mjs')));return{error:String(error),removedAmbientKeys:Object.keys(removed),noReleaseConstructed:true,noGateWorker:true};});
  });
}catch(error){report.infrastructureError={error:String(error),stack:error.stack};}
finally{
  hooks.deregister();childProcess.spawn=originalSpawn;syncBuiltinESMExports();for(const file of staged){assert.equal(sha(fs.readFileSync(file)),allowed.get(file));fs.unlinkSync(file);}for(const[name,hash]of Object.entries(preserved))assert.equal(sha(fs.readFileSync(join(directory,name))),hash);report.dataBeforeCleanup=await inventory.capture(data);assert.ok(report.dataBeforeCleanup.entries.reduce((sum,item)=>sum+(item.bytes??0),0)<=67108864);process.chdir(repository);fs.rmSync(data,{recursive:true});report.ownedTemporaryTreeRemoved=!fs.existsSync(data);report.preserved=preserved;report.finished=new Date().toISOString();report.summary=Object.fromEntries(['PASS','FAIL'].map(status=>[status,report.groups.filter(item=>item.status===status).length]));fs.writeFileSync(join(directory,'COMPLETION-RESULTS.json'),JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(report.summary));
}
