import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const base=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash',source='db6306798211811ffba11e8abaf6d977fcf89768',prefix='tests/integration/agent-bash-coherent-author-20260829/stage-b0-r2';
const records=[];function git(args,input){const index=records.length,stdout=fs.openSync(base+`/git-${index}.stdout`,'wx',0o600),stderr=fs.openSync(base+`/git-${index}.stderr`,'wx',0o600);let result;const record={args,startedAt:new Date().toISOString()};try{result=spawnSync('/usr/bin/git',args,{cwd:repo,env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_OPTIONAL_LOCKS:'0'},input,stdio:['pipe',stdout,stderr],timeout:30000});Object.assign(record,{pid:result.pid,status:result.status,signal:result.signal,error:result.error?String(result.error):null,closed:result.status!==null});}finally{for(const fd of [stdout,stderr]){fs.fsyncSync(fd);assert(fs.fstatSync(fd).size<8388608);fs.closeSync(fd);}record.finishedAt=new Date().toISOString();records.push(record);fs.writeFileSync(base+'/METADATA-PROCESS.json',JSON.stringify(records,null,2)+'\n');}assert(result.status===0&&!result.signal&&!result.error);return fs.readFileSync(base+`/git-${index}.stdout`);}
const inventory=git(['ls-tree','-rlz','--full-tree',source,'--',prefix]).toString().split('\0').filter(Boolean).map(line=>{const match=/^(\d+) blob ([a-f0-9]{40})\s+(\d+)\t(.+)$/.exec(line);assert(match);return{mode:match[1],oid:match[2],bytes:Number(match[3]),path:match[4]};});assert(inventory.length>0&&inventory.length<100&&inventory.every(item=>item.bytes<2097152)&&inventory.reduce((sum,item)=>sum+item.bytes,0)<8388608);fs.writeFileSync(base+'/INVENTORY.json',JSON.stringify(inventory,null,2)+'\n',{flag:'wx'});
const batch=git(['cat-file','--batch'],inventory.map(item=>item.oid).join('\n')+'\n');let position=0;const rows=[];for(const item of inventory){const end=batch.indexOf(10,position);assert(end>=0);assert.equal(batch.subarray(position,end).toString(),`${item.oid} blob ${item.bytes}`);position=end+1;const bytes=batch.subarray(position,position+item.bytes);position+=item.bytes;assert.equal(batch[position++],10);assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),item.oid);rows.push({...item,sha256:createHash('sha256').update(bytes).digest('hex'),body:bytes.toString('base64')});}assert.equal(position,batch.length);fs.writeFileSync(base+'/INPUTS.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({source,files:rows.map(({path,bytes,sha256})=>({path,bytes,sha256})),native:0,product:0}));
