import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { read, hash, bind } from '../data.mjs';
const root = path.resolve('tests/compatibility/bash-ere-core-public-pilot-preparation-20260829/runtime-author-v1/r2');
const prior = path.dirname(root);
const bytes = read(path.join(prior, 'PROFILE.json'));
assert.equal(hash(bytes), '446f44cea9091ce59a12c5591bc1d6e91049003848bef33bd75f520c98728aa6');
const profile = JSON.parse(bytes);
for (const row of profile.assets) bind(row);
const reviewFile = path.resolve('tests/compatibility/bash-ere-core-public-pilot-independent-20260829/runtime-review-v2/RESULT.json');
const reviewBytes = read(reviewFile);
assert.equal(hash(reviewBytes), '45dce84c4f0115c8abca42d4c8691f5fb9a9fd2f4791e7ec2b190c4656cca2f3');
let core = read(path.join(prior, 'core.mjs')).toString('utf8');
let coordinator = read(path.join(prior, 'coordinator.mjs')).toString('utf8');
const replace = (source, before, after) => { assert.equal(source.split(before).length, 2, `unique exact source: ${before}`); return source.replace(before, after); };
core = replace(core, 'const failures = ledger();\n  try {\n    await host.prepare(timer);', 'const failures = host.failures ?? ledger();\n  try {\n    await host.prepare(timer);');
core = replace(core, 'result.complete = false; await host.emergency(result);', "result.complete = false; try { await host.emergency(result); } catch (secondary) { failures.add(secondary, 'emergency-publication'); result.failure = describeLedger(failures.state); }");
coordinator = replace(coordinator, "import { ownChild } from './process-owner.mjs';", "import { ownChild } from '../process-owner.mjs';\nimport { finalizeInvocation } from './finalization.mjs';");
coordinator = replace(coordinator, "from './data.mjs';", "from '../data.mjs';");
coordinator = replace(coordinator, '  const aggregate = captureBudget(56 * 1024 * 1024);', "  let emergencyJournal;\n  return await finalizeInvocation({\n    descriptors, ownership, retained: retainedInvocations, ownerRoot, close: fs.closeSync,\n    emergency: row => { assert(emergencyJournal, 'journal unavailable'); return emergencyJournal(row); },\n    report: row => startup.bytes(Buffer.from(JSON.stringify(row) + '\\n')),\n    run: async failures => {\n  const aggregate = captureBudget(56 * 1024 * 1024);");
coordinator = replace(coordinator, '  const emergencyJournal = row => emergency.bytes', '  emergencyJournal = row => emergency.bytes');
coordinator = replace(coordinator, '  let result;\n  try {\n    result = await schedule(profile, {\n      started, now, sample,', '  const result = await schedule(profile, {\n      failures, started, now, sample,');
coordinator = replace(coordinator, "  } catch (reason) { emergencyJournal({ event: 'coordinator-stop', reason: describe(reason), unknownChildren: ownership.filter(row => !row.receipt.retired).length }); throw reason; }\n  finally { for (const descriptor of descriptors) fs.closeSync(descriptor); if (ownership.every(row => row.receipt.retired)) retainedInvocations.delete(ownerRoot); }\n", '');
coordinator = replace(coordinator, '  return { result, ownership };\n}', '  return { result, ownership };\n    },\n  });\n}');
coordinator = replace(coordinator, "captureBudget, writer, schedule, judgeCell, validateGrant, describe }", "captureBudget, writer, schedule, judgeCell, validateGrant, describe, ledger }");
coordinator = replace(coordinator, "fs.writeSync(2, bytes); });", "const failures = ledger(); failures.add(reason, 'bootstrap'); try { fs.writeSync(2, bytes); } catch (secondary) { failures.add(secondary, 'bootstrap-failure-publication'); } });");
const relative = path.relative(process.cwd(), root);
const patch = '*** Begin Patch\n' + [['core.mjs', core], ['coordinator.mjs', coordinator]].map(([name, source]) => `*** Add File: ${relative}/${name}\n` + source.replace(/\n$/, '').split('\n').map(line => '+' + line).join('\n') + '\n').join('') + '*** End Patch\n';
fs.writeFileSync(path.join(root, 'delta.patch'), patch, { flag: 'wx' });
fs.writeFileSync(path.join(root, 'SOURCE-ADMISSION.json'), JSON.stringify({ at: new Date().toISOString(), priorProfileSha256: hash(bytes), priorCoordinator: profile.assets.find(row => row.path.endsWith('/coordinator.mjs')), reviewCommit: '026d2e9fbd9bca460bb6267d7fc3e131540d754b', reviewReceiptSha256: hash(reviewBytes), sourceDerivedOnly: true, generated: { core: hash(Buffer.from(core)), coordinator: hash(Buffer.from(coordinator)) }, actualWorkers: 0, productImports: 0 }, null, 2) + '\n', { flag: 'wx' });
console.log('Exact N05 source and review receipt admitted; minimal patch generated, no runtime module evaluated.');
