import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { gzipSync, gunzipSync } from 'node:zlib';
import { regular, put, sha, census, verify, inventory } from '../coherent78-arrays-independent-20260828/common.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../..'),work=path.join(here,'RUN-APPLY-PUBLIC-INDEPENDENT-01'),records=path.join(work,'records');
const seal=JSON.parse(regular(path.join(here,'SEAL.json'))),auth=JSON.parse(regular(path.join(here,'AUTHENTICATION.json'))),finalBytes=regular(path.join(records,'FINAL.json')),final=JSON.parse(finalBytes),terminal=JSON.parse(regular(path.join(here,'OUTER.stdout')));
assert.equal(sha(finalBytes),terminal.receipt.sha256);assert.equal(final.complete,true);assert.equal(final.unsafeStop,false);assert.equal(terminal.childrenRetired,true);assert.equal(final.accounting.children.length,40);assert.ok(final.accounting.children.every(row=>row.retired&&row.closeObserved&&row.groupAbsent&&row.supervisorSettled));assert.equal(final.accounting.active,0);
assert.deepEqual(final.accounting.failures,['canonical-four-bodies']);assert.equal(terminal.accepted,false);assert.equal(regular(path.join(here,'OUTER.stderr')).length,0);
for(const row of seal.roles){const bytes=regular(path.join(repo,row.path));assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);}
verify({root:path.join(here,'PREPARED'),entries:auth.preparedCensus});verify({root:path.join(repo,'tests/integration/apply-patch-public-20260829'),entries:auth.authorCensus});
const filenames=fs.readdirSync(records).sort(),outcomes=filenames.filter(name=>name.startsWith('outcome-')).map(name=>JSON.parse(regular(path.join(records,name)))),children=filenames.filter(name=>name.startsWith('child-')).map(name=>JSON.parse(regular(path.join(records,name)))),types=filenames.filter(name=>name.startsWith('types-')).map(name=>({name,...JSON.parse(regular(path.join(records,name)))}));
const cohort=ending=>outcomes.filter(row=>row.label.endsWith(ending)).map(row=>({layout:row.label,code:row.code,passed:row.cases.filter(item=>item.pass).length,total:row.cases.length,created:row.cases.reduce((total,item)=>total+(item.created??item.shells??0),0),disposed:row.cases.reduce((total,item)=>total+(item.disposed??item.closed??0),0),productLoads:row.loads.filter(item=>item.role==='product').length,uniqueProductLoads:new Set(row.loads.filter(item=>item.role==='product').map(item=>item.path)).size}));
const canonical=outcomes.find(row=>row.label==='canonical-four-bodies'),canonicalChild=children.find(row=>/^# tests 83$/m.test(row.stdout));assert.ok(canonicalChild);
const failedBlocks=canonicalChild.stdout.split(/(?=^# Subtest:)/m).filter(block=>/^not ok /m.test(block));assert.equal(failedBlocks.length,4);
const failures=failedBlocks.map(block=>({test:Number(block.match(/^not ok ([0-9]+)/m)[1]),title:block.match(/^# Subtest: (.*)$/m)[1],raw:block}));
const fixture=regular(path.join(here,'PREPARED/fixtures/tests/plugins/agent-commands.test.ts')).toString().split('\n');
const relevantLines=fixture.map((line,index)=>({line:index+1,text:line})).filter(row=>/definitions fallback|nested argv across|forwards search limits|defaultInput|xargs rg|rg',|"rg"/.test(row.text));
const packName=fs.readdirSync(path.join(work,'artifacts')).find(name=>name.endsWith('.tgz')),tar=regular(path.join(work,'artifacts',packName));assert.equal(sha(tar),auth.packageSha256);assert.deepEqual(inventory(tar),auth.packageEntries);
const entries=[];for(const name of ['PREPARE.stdout','PREPARE.stderr','SEAL.stdout','SEAL.stderr','OUTER.stdout','OUTER.stderr','PREPARED/GIT-RAW.json']){const filename=path.join(here,name),bytes=regular(filename);entries.push({path:name,mode:fs.lstatSync(filename).mode&0o777,bytes:bytes.length,sha256:sha(bytes),base64:bytes.toString('base64')});}
for(const directory of ['records','artifacts'])for(const[name,row]of Object.entries(census(path.join(work,directory)))){if(row.directory)continue;const filename=path.join(work,directory,name),relative=path.relative(here,filename),bytes=regular(filename);entries.push({path:relative,mode:row.mode,bytes:bytes.length,sha256:sha(bytes),base64:bytes.toString('base64')});}
assert.ok(entries.length<250);assert.ok(entries.every(row=>!row.path.split('/').includes('AGENTS.md')));const payload=Buffer.from(JSON.stringify({schema:1,qualification:'exact one-attempt exit1; no rescore or deletion',entries})+'\n');assert.ok(payload.length<128*1024*1024);const compressed=gzipSync(payload,{level:9}),roundtrip=gunzipSync(compressed,{maxOutputLength:128*1024*1024});assert.deepEqual(roundtrip,payload);for(const row of JSON.parse(roundtrip).entries){const bytes=Buffer.from(row.base64,'base64');assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);assert.equal(fs.lstatSync(path.join(here,row.path)).mode&0o777,row.mode);assert.deepEqual(regular(path.join(here,row.path)),bytes);}
const encoded=Buffer.from(compressed.toString('base64')+'\n');put(path.join(here,'RAW.json.gz.base64'),encoded);
const workCensus=census(work),workBytes=Object.values(workCensus).reduce((sum,row)=>sum+(row.bytes??0),0),preparedBytes=Object.values(auth.preparedCensus).reduce((sum,row)=>sum+(row.bytes??0),0);assert.ok(workBytes+preparedBytes+encoded.length<768*1024*1024);
const mutants=outcomes.filter(row=>row.mutant).map(row=>({label:row.label,accepted:row.accepted,sha256:row.mutant.sha256,fail:row.mutant.fail,pass:row.mutant.pass,observations:row.cases,loads:row.loads.filter(load=>load.path.endsWith('/'+row.mutant.member))}));assert.equal(mutants.length,4);assert.ok(mutants.every(row=>row.accepted&&row.loads.length===1));
const result={date:new Date().toISOString(),candidate:auth.candidate,base:auth.base,module:auth.module,integration:auth.integration,package:{sha256:sha(tar),bytes:tar.length,members:Object.keys(auth.packageEntries).length},source:{inputs:auth.selected.length,storedComparisons:auth.authenticated.length,added:auth.added,changed:auth.changed,packageAdded:auth.packageAdded,packageChanged:auth.packageChanged,unchangedCommonMembers:864},terminal,overallStatus:'COMPLETE_WITH_FOUR_REVIEWER_WORKER_PROFILE_FAILURES_EXIT1',public:cohort('-public-v2'),arrays:cohort('-arrays'),coherence:cohort('-coherence'),novel:cohort('-novel'),canonical:{...canonical.summaries[0],failures,relevantLines,childCode:canonicalChild.code,fixtureSha256:sha(regular(path.join(here,'PREPARED/fixtures/tests/plugins/agent-commands.test.ts')))},stream:outcomes.find(row=>row.label==='stream-consumer').summaries,types:types.map(row=>({name:row.name,accepted:row.accepted,code:row.code,diagnostics:row.errors,declarationCount:row.declarations.length,uniqueDeclarations:new Set(row.declarations).size})),mutants,restores:outcomes.filter(row=>row.label.endsWith('-restored')).map(row=>({label:row.label,accepted:row.accepted,cases:row.cases})),guards:outcomes.filter(row=>row.guard||row.label==='old-origin-absent').map(row=>({label:row.label,accepted:row.accepted,code:row.code,kind:row.guard??'origin-absent'})),resources:{controlledChildren:40,retired:40,signals:children.filter(row=>row.signal).map(row=>row.signal),capturedBytes:final.accounting.captured,terminalElapsedMs:terminal.elapsedBeforeAnnouncementMs,maximumChildElapsedMs:Math.max(...children.map(row=>row.finishedElapsedMs-row.startedElapsedMs)),maximumRuntimeChildElapsedMs:Math.max(...children.filter(row=>row.role==='product').map(row=>row.finishedElapsedMs-row.startedElapsedMs)),workingBytes:workBytes,preparedBytes,archiveBytes:encoded.length,knownCombinedBytes:workBytes+preparedBytes+encoded.length,preparationGitChildren:1,workerStarts:0,descendantQualification:'Node child/Worker grants absent, four regex worker attempts refused; natural direct closes/group absence observed. No continuous OS-global/transient process census or RSS guarantee.'},archive:{path:'RAW.json.gz.base64',sha256:sha(encoded),compressedSha256:sha(compressed),decodedSha256:sha(payload),decodedBytes:payload.length,entries:entries.length,rawBytes:entries.reduce((sum,row)=>sum+row.bytes,0),rawDeleted:0},immutablePreparedAndAuthorCensuses:true,remaining:'Four maintained regex cases require separately authorized worker-aware harness qualification; no retry or permission change here. Public integration evidence is qualified, not an all-green maintained suite or whole gate.'};
put(path.join(here,'RESULTS.json'),JSON.stringify(result,null,2)+'\n');put(path.join(here,'ARCHIVE-MANIFEST.json'),JSON.stringify(entries.map(({base64,...row})=>row),null,2)+'\n');console.log(JSON.stringify({package:result.package,public:result.public,canonical:canonical.summaries,types:types.length,mutants:mutants.length,guards:result.guards.length,resources:result.resources,archive:result.archive},null,2));
