import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { regular, put, sha, census, verify, copy, inventory } from '../coherent78-arrays-independent-20260828/common.mjs';
import { controller } from '../../shell/indexed-arrays-independent-20260828/s06-successor-v1/preparation-v4/controller.mjs';
import { deadline } from '../../shell/indexed-arrays-independent-20260828/s06-successor-v1/preparation-v4/deadline.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../../..'),clock=deadline(40*60*1000);
let budget,report;const immutable=[];
function hashBinary(filename){const stat=fs.lstatSync(filename);assert.ok(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<256*1024*1024);const hash=createHash('sha256'),fd=fs.openSync(filename,'r'),chunk=Buffer.alloc(1024*1024);try{for(;;){const size=fs.readSync(fd,chunk,0,chunk.length,null);if(!size)break;hash.update(chunk.subarray(0,size));}}finally{fs.closeSync(fd);}return hash.digest('hex');}
try{
  const[expected,label]=process.argv.slice(2);assert.equal(label,'APPLY-PUBLIC-INDEPENDENT-01');const sealBytes=regular(path.join(here,'SEAL.json'));assert.equal(sha(sealBytes),expected);const seal=JSON.parse(sealBytes),auth=JSON.parse(regular(path.join(here,'AUTHENTICATION.json')));
  const integrity=()=>{clock.check('integrity');for(const row of seal.roles){const filename=path.join(repo,row.path),bytes=regular(filename);assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);assert.equal(fs.lstatSync(filename).mode&0o777,row.mode);}for(const tree of immutable)verify(tree);};
  integrity();assert.equal(process.execPath,auth.node.path);assert.equal(process.version,'v22.22.2');assert.equal(hashBinary(auth.node.path),auth.node.sha256);verify({root:path.join(here,'PREPARED'),entries:auth.preparedCensus});verify({root:path.join(repo,'tests/integration/apply-patch-public-20260829'),entries:auth.authorCensus});
  for(const tool of Object.values(auth.tools))verify({root:tool.root,entries:tool.entries});
  const work=path.join(here,'RUN-'+label);assert.ok(!fs.existsSync(work));fs.mkdirSync(work);report={candidate:auth.candidate,base:auth.base,module:auth.module,packageSha256:auth.packageSha256,seal:expected,work,phases:[],complete:false,unsafeStop:false};
  budget=controller(work,seal.policy,{node:{path:auth.node.path},git:{path:auth.git.path}},integrity,clock);
  for(const name of ['records','source','tools','apps','artifacts','home','tmp','cache']){fs.mkdirSync(path.join(work,name));budget.registerStorage(name,path.join(work,name),name==='records'?128*1024*1024:768*1024*1024);}
  const source=path.join(work,'source'),tools=path.join(work,'tools'),apps=path.join(work,'apps'),artifacts=path.join(work,'artifacts');
  for(const row of auth.selected)put(path.join(source,row.path),regular(path.join(auth.sourceRoot,row.path)),parseInt(row.mode,8)&0o777);
  for(const[name,tool]of Object.entries(auth.tools))copy(tool.root,name==='npm'?path.join(tools,'npm'):path.join(source,'node_modules',name));
  immutable.push({root:tools,entries:census(tools)});
  const env={PATH:'',HOME:path.join(work,'home'),TMPDIR:path.join(work,'tmp'),LC_ALL:'C',TZ:'UTC',NO_COLOR:'1',npm_config_cache:path.join(work,'cache'),npm_config_offline:'true',npm_config_ignore_scripts:'true',npm_config_audit:'false',npm_config_fund:'false',npm_config_update_notifier:'false',npm_config_userconfig:path.join(work,'home/npmrc'),npm_config_globalconfig:path.join(work,'home/globalnpmrc')};put(env.npm_config_userconfig,'');put(env.npm_config_globalconfig,'');
  const node=auth.node.path,compiler=path.join(source,'node_modules/typescript/bin/tsc'),npm=path.join(tools,'npm/bin/npm-cli.js');
  const command=async(role,args,cwd,extra={},write=false,timeout=30000)=>budget.child(role,node,['--permission','--allow-fs-read='+work,'--allow-fs-read='+node,...(write?['--allow-fs-write='+work]:[]),...args],{cwd,env:{...env,...extra},timeoutMs:timeout,maxBytes:role==='tool'?8*1024*1024:4*1024*1024});
  const tool=async(label,args,cwd)=>{const result=await command('tool',args,cwd,{},true,120000);await budget.record(label,{code:result.code});assert.equal(result.code,0,label+': '+result.stderr+result.stdout);return result;};
  await tool('strict-build',[compiler,'-p','tsconfig.build.json'],source);
  const packed=await tool('offline-pack',[npm,'pack','--offline','--ignore-scripts','--json','--pack-destination',artifacts],source),packRows=JSON.parse(packed.stdout);assert.equal(packRows.length,1);const tarPath=path.join(artifacts,packRows[0].filename),tar=regular(tarPath);assert.equal(sha(tar),auth.packageSha256);assert.deepEqual(inventory(tar),auth.packageEntries);
  for(const[name,row]of Object.entries(auth.packageEntries))assert.equal(sha(regular(path.join(source,name))),row.sha256);
  immutable.push({root:source,entries:census(source)});report.freshPack={sha256:sha(tar),bytes:tar.length,members:Object.keys(auth.packageEntries).length};
  const sourceApp=path.join(apps,'source-built');fs.mkdirSync(sourceApp);put(path.join(sourceApp,'package.json'),'{"private":true,"type":"module"}\n');for(const[name,row]of Object.entries(auth.packageEntries))put(path.join(sourceApp,'node_modules/virtual-bash',name),regular(path.join(source,name)),row.mode);
  const installed=path.join(apps,'installed');fs.mkdirSync(installed);put(path.join(installed,'package.json'),'{"private":true,"type":"module"}\n');await tool('offline-install',[npm,'install','--offline','--ignore-scripts','--no-audit','--no-fund','--package-lock=false','--omit=dev',tarPath],installed);
  const productFiles=root=>Object.fromEntries(Object.entries(census(root)).filter(([,row])=>!row.directory));assert.deepEqual(productFiles(path.join(installed,'node_modules/virtual-bash')),auth.packageEntries);
  function installHarness(app){for(const row of seal.appRoles)put(path.join(app,row.destination),regular(path.join(repo,row.path)));const positive=regular(path.join(here,'consumer.mts.fixture')).toString();put(path.join(app,'consumer-positive.mts'),positive);put(path.join(app,'consumer-negative.mts'),positive.replaceAll('// @ts-expect-error','// removed expected diagnostic'));}
  installHarness(sourceApp);installHarness(installed);
  let serial=0;
  const rowsFrom=output=>output.split('\n').filter(line=>line.startsWith('{')).map(line=>JSON.parse(line));
  async function runtime(label,app,entry,{extras={},count,ids,guard,mutant}={}){
    const product=path.join(app,'node_modules/virtual-bash'),before={root:app,entries:census(app)},modules={};
    const required=structuredClone(auth.packageEntries);if(mutant)required[mutant.member]={...required[mutant.member],bytes:mutant.bytes,sha256:mutant.sha256};
    if(guard==='export'){const metadata=JSON.parse(regular(path.join(source,'package.json')));delete metadata.exports['./commands/apply-patch'];const bytes=Buffer.from(JSON.stringify(metadata));required['package.json']={...required['package.json'],bytes:bytes.length,sha256:sha(bytes)};}
    assert.deepEqual(productFiles(product),required,'complete applicable package binding');
    for(const[name,row]of Object.entries(before.entries))if(!row.directory&&/\.(?:mjs|js)$/.test(name)){const filename=path.join(app,name);modules[filename]={bytes:row.bytes,sha256:row.sha256,role:name.startsWith('node_modules/virtual-bash/dist/')?'product':'harness'};}
    const binding={entry:path.join(app,entry),product,modules};if(guard==='missing')delete modules[path.join(product,'dist/index.js')];if(guard==='changed')modules[path.join(product,'dist/commands/apply-patch/index.js')].sha256='0'.repeat(64);if(guard==='outside')for(const name of Object.keys(modules))if(modules[name].role==='product')delete modules[name];if(guard==='fallback')binding.fallback=path.join(source,'src/index.ts');
    const manifest=await budget.record('binding-'+(++serial),binding),resultFile=path.join(artifacts,'result-'+serial+'.json');
    const result=await command('product',['--test-reporter=tap','--test-timeout=30000',path.join(app,'bootstrap.mjs'),manifest.path,manifest.sha256],app,{PRODUCT_ROOT:product,PUBLIC_RESULT:resultFile,LAYOUT:label,...extras},true,120000);verify(before);
    const observations=rowsFrom(result.stdout),loads=observations.filter(row=>row.load).map(row=>row.load);for(const load of loads){assert.ok(modules[load.path]);assert.equal(load.sha256,modules[load.path].sha256);}
    const summaries=observations.filter(row=>row.summary).map(row=>row.summary),cases=observations.filter(row=>typeof row.id==='string'&&typeof row.pass==='boolean');
    let accepted;
    if(guard){if(guard==='fallback')accepted=result.code===0&&observations.some(row=>row.refusal==='source-fallback');else accepted=result.code===1&&/REVIEW_UNBOUND_MODULE|REVIEW_HASH|ERR_PACKAGE_PATH_NOT_EXPORTED/.test(result.stderr);}
    else if(mutant){assert.ok(loads.some(row=>row.path===path.join(product,mutant.member)&&row.sha256===mutant.sha256),'ACTUAL_MUTANT_LOAD_REQUIRED');accepted=result.code===1&&cases.length===2&&cases.find(row=>row.id===mutant.fail)?.pass===false&&cases.find(row=>row.id===mutant.pass)?.pass===true;}
    else if(entry==='canonical-driver.mjs'||entry==='stream-consumer.mjs'){const value=name=>Number(result.stdout.match(new RegExp('^# '+name+' ([0-9]+)$','m'))?.[1]);accepted=result.code===0&&value('tests')===count&&value('pass')===count&&value('fail')===0&&value('skipped')===0&&value('cancelled')===0;summaries.push({tap:{tests:value('tests'),pass:value('pass'),fail:value('fail'),skip:value('skipped'),cancel:value('cancelled')}});}
    else if(entry==='origin-check.mjs')accepted=result.code===0&&observations.some(row=>row.originAbsent===true);
    else{assert.equal(summaries.length,1,'counted cohort summary required');assert.equal(summaries[0].cases,count);assert.equal(cases.length,count);if(ids)assert.deepEqual(cases.map(row=>row.id),ids);accepted=result.code===0&&cases.every(row=>row.pass);if(cases.some(row=>row.cleanupFailure||row.cleanupError))throw Error('UNSAFE_CASE_CLEANUP');}
    const receipt=await budget.record('outcome-'+serial,{label,accepted,code:result.code,summaries,cases,loads,guard,mutant});report.phases.push({label,accepted,receipt});budget.ordinary(label,accepted);return{accepted,cases};
  }
  async function types(app,label){const before={root:app,entries:census(app)};for(const variant of ['positive','negative']){const result=await command('type',[compiler,'--strict','--noUncheckedIndexedAccess','--exactOptionalPropertyTypes','--noEmit','--skipLibCheck','false','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2023','--pretty','false','--listFiles','--typeRoots',path.join(source,'node_modules/@types'),path.join(app,'consumer-'+variant+'.mts')],app);verify(before);const text=result.stdout+result.stderr,errors=text.split(/\r?\n/).filter(line=>/error TS\d+:/.test(line)),codes=errors.map(line=>line.match(/error (TS\d+):/)[1]),expected=variant==='positive'?[]:['TS2353','TS2353','TS2322','TS2353','TS2353','TS2540','TS2353','TS2322'];const declarations=text.split(/\r?\n/).filter(line=>line.endsWith('.d.ts')&&line.includes('/dist/'));assert.ok(declarations.length);for(const filename of declarations){assert.ok(filename.startsWith(path.join(app,'node_modules/virtual-bash/dist/')));const relative=path.relative(path.join(app,'node_modules/virtual-bash'),filename);assert.equal(sha(regular(filename)),auth.packageEntries[relative]?.sha256);}const accepted=result.code===(variant==='positive'?0:2)&&JSON.stringify(codes)===JSON.stringify(expected);await budget.record('types-'+label+'-'+variant,{accepted,code:result.code,errors,declarations});report.phases.push({label:'types-'+label+'-'+variant,accepted,diagnostics:codes});budget.ordinary('types-'+label+'-'+variant,accepted);}}
  const coherenceIds=Array.from({length:17},(_,index)=>'C'+String(index+2).padStart(2,'0')).concat('R15').join(',');let moved;
  for(const label of ['source-built','installed','moved']){let app=label==='source-built'?sourceApp:installed;if(label==='moved'){moved=path.join(apps,'physically moved');const before=census(installed);fs.renameSync(installed,moved);assert.deepEqual(census(moved),before);assert.equal(fs.existsSync(installed),false);app=moved;report.moved={old:installed,current:moved,oldAbsent:true};}await runtime(label+'-public-v2',app,'public-v2.mjs',{count:28});await runtime(label+'-arrays',app,'arrays.mjs',{count:12});await runtime(label+'-coherence',app,'coherence/probe.mjs',{count:18,extras:{CASE_IDS:coherenceIds}});await runtime(label+'-novel',app,'novel.mjs',{count:17});await types(app,label);await runtime(label+'-fallback-refusal',app,'novel.mjs',{guard:'fallback'});}
  const canonicalRoot=path.join(moved,'canonical'),canonicalBuild=path.join(moved,'canonical-built'),manifest=JSON.parse(regular(path.join(here,'PREPARED/harness/SOURCE-v2.json'))),fixtureRows=[...manifest.fixtures.filter(row=>row.path.endsWith('.ts')),...['tests/commands/stream-format/helpers.ts','tests/commands/split/helpers.ts'].map(name=>({path:name,helper:true}))],routing=[];
  for(const row of fixtureRows){const original=regular(path.join(here,'PREPARED',row.helper?'harness':'fixtures',row.path)).toString(),imports=[];const text=original.replace(/(["'])(?:\.\.\/)+src\/[^"']+\.js\1/g,specifier=>{imports.push(specifier);return '"virtual-bash"';});assert.ok(imports.length);put(path.join(canonicalRoot,row.path),text);routing.push({path:row.path,original:sha(original),routed:sha(text),imports});}
  await budget.record('canonical-import-routing',routing);await tool('canonical-compile',[compiler,'--strict','--noUncheckedIndexedAccess','--exactOptionalPropertyTypes','--target','ES2023','--module','NodeNext','--moduleResolution','NodeNext','--skipLibCheck','--pretty','false','--rootDir',canonicalRoot,'--outDir',canonicalBuild,'--typeRoots',path.join(source,'node_modules/@types'),...fixtureRows.map(row=>path.join(canonicalRoot,row.path))],moved);
  put(path.join(moved,'canonical-driver.mjs'),manifest.fixtures.filter(row=>row.path.endsWith('.ts')).map(row=>'await import('+JSON.stringify('./canonical-built/'+row.path.replace(/\.ts$/,'.js'))+');').join('\n')+'\n');await runtime('canonical-four-bodies',moved,'canonical-driver.mjs',{count:83});await runtime('stream-consumer',moved,'stream-consumer.mjs',{count:21});
  for(const spec of seal.mutants){const app=path.join(apps,spec.id);copy(sourceApp,app);const filename=path.join(app,'node_modules/virtual-bash',spec.member),original=regular(filename),text=original.toString();assert.equal(text.split(spec.needle).length,2);const bytes=Buffer.from(text.replace(spec.needle,spec.replacement));assert.equal(sha(bytes),spec.sha256);fs.writeFileSync(filename,bytes);await runtime(spec.id,app,'novel.mjs',{extras:{REVIEW_CASES:[spec.fail,spec.pass].join(',')},mutant:spec});fs.writeFileSync(filename,original);assert.equal(sha(regular(filename)),auth.packageEntries[spec.member].sha256);await runtime(spec.id+'-restored',app,'novel.mjs',{extras:{REVIEW_CASES:[spec.fail,spec.pass].join(',')},count:2});}
  for(const guard of ['missing','changed','outside'])await runtime('binding-'+guard,moved,'public-v2.mjs',{guard});
  const exportApp=path.join(apps,'removed-subpath');copy(sourceApp,exportApp);const filename=path.join(exportApp,'node_modules/virtual-bash/package.json'),original=regular(filename),metadata=JSON.parse(original);delete metadata.exports['./commands/apply-patch'];fs.writeFileSync(filename,JSON.stringify(metadata));await runtime('removed-subpath',exportApp,'public-v2.mjs',{guard:'export'});fs.writeFileSync(filename,original);
  put(path.join(moved,'origin-check.mjs'),'import assert from "node:assert/strict"; import fs from "node:fs"; assert.equal(fs.existsSync('+JSON.stringify(installed)+'),false); console.log(JSON.stringify({originAbsent:true}));\n');await runtime('old-origin-absent',moved,'origin-check.mjs');
  assert.deepEqual(productFiles(path.join(moved,'node_modules/virtual-bash')),auth.packageEntries);verify({root:path.join(here,'PREPARED'),entries:auth.preparedCensus});verify({root:path.join(repo,'tests/integration/apply-patch-public-20260829'),entries:auth.authorCensus});report.complete=true;
}catch(reason){if(report){report.unsafeStop=true;report.error=String(reason?.stack??reason);}else{console.error(String(reason?.stack??reason));process.exitCode=78;}}
finally{if(report&&budget)try{const terminal=await budget.finalize(report,()=>({finalCensuses:['source','tools','apps','artifacts','home','tmp','cache'].map(name=>({root:path.join(report.work,name),entries:census(path.join(report.work,name))}))}),value=>new Promise((resolve,reject)=>process.stdout.write(JSON.stringify(value)+'\n',error=>error?reject(error):resolve())));clock.check('terminal-exit');process.exitCode=terminal.unsafeStop?78:terminal.accepted?0:1;}catch(reason){console.error(String(reason?.stack??reason));process.exitCode=78;}}
