import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, mkdirSync, copyFileSync, renameSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const owned = dirname(fileURLToPath(import.meta.url));
const root = resolve(owned, '../../../../..');
const [phase, candidate] = process.argv.slice(2);
assert.match(phase ?? '', /^[a-z0-9-]+$/);
assert.match(candidate ?? '', /^[a-f0-9]{40}$/);
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const digest = path => hash(readFileSync(path));
const walk = directory => readdirSync(directory, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? walk(join(directory, entry.name)) : [join(directory, entry.name)]);
const snapshot = directory => Object.fromEntries(walk(directory).sort().map(path => [relative(directory, path), digest(path)]));
const run = (binary, args, options = {}) => {
  const result = spawnSync(binary, args, { cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024, timeout: 180000, killSignal: 'SIGKILL', ...options });
  return { command: [binary, ...args], status: result.status, signal: result.signal, stdout: result.stdout, stderr: result.stderr, error: result.error?.message };
};
const add = (path, content) => {
  assert.ok(!existsSync(path));
  const text = typeof content === 'string' ? content : JSON.stringify(content, null, 2);
  const result = run('apply_patch', [], { input: `*** Begin Patch\n*** Add File: ${relative(root, path)}\n${text.trimEnd().split('\n').map(line => '+' + line).join('\n')}\n*** End Patch\n` });
  assert.equal(result.status, 0, result.stderr);
};
const scratch = join(owned, '.work', phase);
assert.ok(!existsSync(scratch), 'append-only run');
mkdirSync(scratch, { recursive: true });
const fixtures = ['vectors.mjs', 'matrix.mjs', 'loader.mjs', 'run.mjs', 'README.md'];
const fixtureBefore = Object.fromEntries(fixtures.map(name => [name, digest(join(owned, name))]));
const liveBefore = snapshot(join(root, 'src'));
const source = join(scratch, 'source');
mkdirSync(source);
const archive = run('git', ['archive', candidate, 'src', 'package.json', 'tsconfig.json', 'tsconfig.build.json'], { encoding: null });
assert.equal(archive.status, 0);
assert.equal(run('tar', ['-xf', '-', '-C', source], { input: archive.stdout }).status, 0);
const sourceBefore = snapshot(source);
const freeze = JSON.parse(readFileSync(join(owned, 'freeze.json')));
if (candidate === freeze.candidate) assert.deepEqual(sourceBefore, freeze.source);
const stage = join(scratch, 'stage');
mkdirSync(stage);
const build = run(process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', join(source, 'tsconfig.build.json'), '--outDir', join(stage, 'dist')]);
add(join(owned, 'evidence', `${phase}-build.json`), build);
assert.equal(build.status, 0, 'isolated build failed');
copyFileSync(join(source, 'package.json'), join(stage, 'package.json'));
const buildBefore = snapshot(stage);
const packed = join(scratch, 'packed');
mkdirSync(packed);
const pack = run('npm', ['pack', '--ignore-scripts', '--offline', '--json', '--pack-destination', packed], { cwd: stage, env: { ...process.env, npm_config_cache: join(scratch, 'npm-cache') } });
add(join(owned, 'evidence', `${phase}-pack.json`), pack);
assert.equal(pack.status, 0, pack.stderr);
const packInfo = JSON.parse(pack.stdout)[0];
const tarball = join(packed, packInfo.filename);
const tarHash = digest(tarball);
const consumer = join(scratch, 'moved-consumer');
mkdirSync(consumer);
writeFileSync(join(consumer, 'package.json'), JSON.stringify({ name: 'independent-retained-byte-consumer', private: true, type: 'module' }));
const moved = join(consumer, packInfo.filename);
renameSync(tarball, moved);
assert.ok(!existsSync(tarball));
assert.equal(digest(moved), tarHash);
const installed = join(consumer, 'node_modules/virtual-bash');
mkdirSync(installed, { recursive: true });
assert.equal(run('tar', ['-xzf', moved, '--strip-components=1', '-C', installed]).status, 0);
const packageBefore = snapshot(installed);
assert.deepEqual(packageBefore, buildBefore);
for (const name of ['matrix.mjs', 'vectors.mjs']) copyFileSync(join(owned, name), join(consumer, name));
const hashes = Object.fromEntries(Object.entries(packageBefore).map(([name, sha256]) => [join(installed, name), sha256]));
const hashPath = join(scratch, 'hashes.json');
writeFileSync(hashPath, JSON.stringify(hashes));
const loadedPath = join(scratch, 'loaded.jsonl');
const resultsPath = join(scratch, 'results.json');
const execution = run(process.execPath, ['--unhandled-rejections=strict', '--experimental-loader', join(owned, 'loader.mjs'), join(consumer, 'matrix.mjs')], { cwd: consumer, env: { ...process.env, REVIEW_HASHES: hashPath, REVIEW_LOADED: loadedPath, REVIEW_RESULTS: resultsPath, REVIEW_PUBLIC: join(installed, 'dist/index.js'), REVIEW_NETWORK: join(installed, 'dist/commands/network/index.js') } });
add(join(owned, 'evidence', `${phase}-execution.json`), execution);
const results = JSON.parse(readFileSync(resultsPath));
add(join(owned, 'evidence', `${phase}-results.json`), results);
const loaded = readFileSync(loadedPath, 'utf8').trim().split('\n').map(line => JSON.parse(line));
for (const name of ['dist/index.js', 'dist/commands/network/body.js', 'dist/commands/structured/jq.js']) assert.ok(loaded.some(entry => entry.path === join(installed, name)), name);
const fixtureAfter = Object.fromEntries(fixtures.map(name => [name, digest(join(owned, name))]));
const sourceAfter = snapshot(source);
const buildAfter = snapshot(stage);
const packageAfter = snapshot(installed);
add(join(owned, 'evidence', `${phase}-authentication.json`), { phase, candidate, freezeCandidate: freeze.candidate, fixtureBefore, fixtureAfter, sourceBefore, sourceAfter, buildBefore, buildAfter, packageBefore, packageAfter, tarHash, moved, sourceArchiveHash: hash(archive.stdout), loaded, liveBefore, liveAfter: snapshot(join(root, 'src')), node: process.version, platform: process.platform, arch: process.arch, npm: run('npm', ['--version']).stdout.trim() });
assert.deepEqual(fixtureBefore, fixtureAfter);
assert.deepEqual(sourceBefore, sourceAfter);
assert.deepEqual(buildBefore, buildAfter);
assert.deepEqual(packageBefore, packageAfter);
assert.equal(results.count, 34);
assert.equal(execution.signal, null);
assert.ok(execution.status === 0 || execution.status === 1);
console.log(JSON.stringify({ phase, candidate, count: results.count, passed: results.passed, failed: results.failed, tarHash }));
process.exitCode = execution.status;
