import {readFile, writeFile} from 'node:fs/promises';
import {gzipSync} from 'node:zlib';
const source=JSON.parse(await readFile(new URL('../src/help-text.json',import.meta.url),'utf8'));
const packed=gzipSync(JSON.stringify(source),{level:9}).toString('base64');
const output='// Generated by npm run generate:help; edit help-text.json.\n'+
 `export type LlmHelpName = ${Object.keys(source).map(key=>JSON.stringify(key)).join(' | ')};\n`+
 `export const packedHelp = ${JSON.stringify(packed)};\n`;
const path=new URL('../src/help-data.ts',import.meta.url);
if(process.argv.includes('--check')) {
 if(await readFile(path,'utf8')!==output)throw new Error('Run npm run generate:help --workspace=safe-bash-command-llm');
}else await writeFile(path,output);
