import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { owned, root, work, git, hash, inventory, save, command } from './prepare.mjs';
const { candidate } = JSON.parse(readFileSync(join(owned, 'provenance.json')));
const source = join(work, 'shared-qualified'); mkdirSync(source);
const paths = ['src', 'package.json', 'tsconfig.json', 'tsconfig.build.json'];
const legacy = JSON.parse(git('show', `${candidate}:tests/commands/expr-stress/diagnostics-candidate-review/replay/legacy-plan.json`));
paths.push(...legacy.args.filter(arg => arg.endsWith('.ts')), 'tests/commands/search/helpers.ts', 'tests/commands/grep-aliases/helpers.ts', 'tests/commands/regex-execution/continuation/public-child.mjs');
const archive = git('archive', candidate, ...paths);
writeFileSync(join(work, 'shared-qualified.tar'), archive, { flag: 'wx' });
assert.equal(command('shared-qualified-extract', '/usr/bin/tar', ['-xf', join(work, 'shared-qualified.tar'), '-C', source]).status, 0);
const before = inventory(source); save('shared-qualified-before.json', before);
for (const entry of before.filter(entry => entry.type === 'file')) assert.equal(entry.sha256, hash(git('show', `${candidate}:${entry.path}`)));
assert.equal(command('shared-qualified-build', process.execPath, [join(root, 'node_modules/typescript/bin/tsc'), '-p', join(source, 'tsconfig.build.json'), '--skipLibCheck', 'false'], { cwd: source }).status, 0);
const built = inventory(source);
const output = command('shared-legacy276-qualified-rerun', process.execPath, legacy.args, { cwd: source, env: { ...process.env, TMPDIR: work } });
assert.deepEqual(inventory(source), built, 'including added entries');
save('shared-qualified-after.json', inventory(source));
save('shared-qualified-summary.json', { candidate, paths, archiveSha256: hash(archive), actualCounts: Object.fromEntries([...output.stdout.matchAll(/^ℹ (tests|pass|fail|cancelled|skipped|todo) (\d+)$/gm)].map(match => [match[1], Number(match[2])])), status: output.status, authenticatedArchiveFiles: before.filter(entry => entry.type === 'file').length, newBuildEntries: built.filter(entry => !before.some(previous => entry.path === previous.path)), postcheckIncludesNewEntries: true, classification: 'Separate exact candidate archive with three authenticated missing prerequisites. First incomplete 105/110 infrastructure result retained. Same unchanged eleven-file shared cohort; no input/assertion changes.' });
console.log(output.stdout.slice(-700));
