import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const repo='/Users/kjopek/Workspace/safe-bash',root=path.join(repo,'tests/compatibility/final-coherent-producer-20260829'),own=path.dirname(fileURLToPath(import.meta.url));
const archiveHash='de8741c1be9c870650e92944020fa2785114b7046ef1774af2c27ea79238e17a',archiveSize=974493;
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const blob=bytes=>crypto.createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');
const bound=[],checks=[];let decoders=0,parsers=0;const started=Date.now();
function write(name,value){const bytes=Buffer.isBuffer(value)?value:Buffer.from(typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');assert(bytes.length<8388608);fs.writeFileSync(path.join(own,name),bytes,{flag:'wx'});}
function read(filename,expected={}){const stat=fs.lstatSync(filename);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=16777216);if(expected.bytes!==undefined)assert.equal(stat.size,expected.bytes);if(expected.size!==undefined)assert.equal(stat.size,expected.size);const bytes=fs.readFileSync(filename);assert.equal(bytes.length,stat.size);if(expected.sha256)assert.equal(sha(bytes),expected.sha256);if(expected.blob)assert.equal(blob(bytes),expected.blob);if(expected.mode!==undefined)assert.equal(stat.mode&511,typeof expected.mode==='string'?parseInt(expected.mode,8)&511:expected.mode);bound.push({path:filename,bytes:bytes.length,sha256:sha(bytes),mode:stat.mode&511});return bytes;}
function parseInventory(bytes){const map=new Map();for(const entry of bytes.toString().split('\0').filter(Boolean)){const match=/^(\d+) blob ([0-9a-f]{40})\t(.+)$/.exec(entry);assert(match);map.set(path.join(repo,match[3]),match[2]);}return map;}
function admit(bytes,size,hash){assert(Buffer.isBuffer(bytes)&&Number.isSafeInteger(size)&&size>0&&size<=archiveSize);assert.equal(bytes.length,size);assert.equal(sha(bytes),hash);return bytes;}
const decoder=new TextDecoder('utf-8',{fatal:true});
function field(bytes){const end=bytes.indexOf(0);return decoder.decode(end<0?bytes:bytes.subarray(0,end));}
function octal(bytes){const text=field(bytes).trim();assert(/^[0-7]*$/.test(text));return text?parseInt(text,8):0;}
function tar(bytes){parsers++;assert(bytes.length<=33554432&&bytes.length%512===0);const members=new Map();let offset=0;while(offset+512<=bytes.length){const header=bytes.subarray(offset,offset+512);if(header.every(value=>value===0)){assert(offset+1024<=bytes.length);assert(bytes.subarray(offset).every(value=>value===0));break;}let checksum=0;for(let index=0;index<512;index++)checksum+=index>=148&&index<156?32:header[index];assert.equal(checksum,octal(header.subarray(148,156)));const size=octal(header.subarray(124,136)),mode=octal(header.subarray(100,108));assert(Number.isSafeInteger(size)&&size>=0&&size<=16777216);const prefix=field(header.subarray(345,500)),name=field(header.subarray(0,100));const full=prefix?prefix+'/'+name:name;assert(full.startsWith('package/'));const relative=full.slice(8);assert(relative&&!relative.startsWith('/')&&!relative.split('/').some(part=>part==='..'||part==='.'||part===''));assert(!relative.includes('\\')&&!relative.endsWith('AGENTS.md'));assert(!members.has(relative));assert(header[156]===0||header[156]===48,'only actual regular npm members admitted');assert(offset+512+size<=bytes.length);members.set(relative,{path:relative,size,mode,body:bytes.subarray(offset+512,offset+512+size)});assert(members.size<=2048);offset+=512+Math.ceil(size/512)*512;}return members;}
function test(id,action){try{action();checks.push({id,pass:true});}catch(reason){checks.push({id,pass:false,detail:String(reason)});}}
try{
 const finalObjects=parseInventory(read(path.join(own,'inventory.stdout')));
 const selected=['DATA-RECEIPT.json','PRODUCER-RECEIPT.json','PRESEAL.json','SOURCE-INPUTS.json','EMITS.json','SHIPPING.json','CLOSURE.json','TOOLS.json','USABILITY.json','SOURCE-REVIEW.json'];const records={};
 for(const name of selected){const filename=path.join(root,name);assert(finalObjects.has(filename));records[name]=read(filename,{blob:finalObjects.get(filename)});}
 assert.equal(sha(records['DATA-RECEIPT.json']),'d8451028627a01651e4fadf648147c15a39ef04e643dfa2e48a0259be385a50e');
 const data=JSON.parse(records['DATA-RECEIPT.json']),producer=JSON.parse(records['PRODUCER-RECEIPT.json']),preseal=JSON.parse(records['PRESEAL.json']),sources=JSON.parse(records['SOURCE-INPUTS.json']),shipping=JSON.parse(records['SHIPPING.json']),emits=JSON.parse(records['EMITS.json']),closure=JSON.parse(records['CLOSURE.json']),tools=JSON.parse(records['TOOLS.json']);
 assert.equal(sha(records['PRODUCER-RECEIPT.json']),data.producerReceiptSha256);assert.equal(sha(records['SOURCE-INPUTS.json']),producer.sourceSeal.sha256);assert.equal(sha(records['TOOLS.json']),producer.toolsSeal.sha256);assert.equal(sha(records['PRESEAL.json']),producer.preseal.sha256);assert.equal(sha(records['SHIPPING.json']),data.shipManifest.sha256);assert.equal(sha(records['CLOSURE.json']),data.closure.sha256);
 const archivePath=path.join(root,'virtual-bash-0.0.0.tgz');const freeze=spawnSync('/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false','ls-tree','-rz','ab46a006a0f324a42c563542e4545ce80de49731','--',path.relative(repo,archivePath),path.relative(repo,path.join(root,'PRODUCER-RECEIPT.json'))],{cwd:repo,maxBuffer:1048576,timeout:10000});write('freeze.stdout',freeze.stdout);write('freeze.stderr',freeze.stderr);assert.equal(freeze.status,0);assert.equal(freeze.signal,null);const frozen=parseInventory(freeze.stdout);assert.equal(blob(records['PRODUCER-RECEIPT.json']),frozen.get(path.join(root,'PRODUCER-RECEIPT.json')));
 const compressed=read(archivePath,{bytes:archiveSize,sha256:archiveHash,blob:frozen.get(archivePath)});admit(compressed,archiveSize,archiveHash);
 write('PRESEAL-v2.json',{selected,authorCommit:'937f1d9317256c18066d9f74c0ae0bb21842bfaa',freezeCommit:'ab46a006a0f324a42c563542e4545ce80de49731',archive:{path:archivePath,bytes:archiveSize,sha256:archiveHash},bound,helperSha256:sha(read(fileURLToPath(import.meta.url))),limits:{compressed:archiveSize,decoded:33554432,aggregateBuffers:100663296,members:2048},membership:['changed-compressed','short-compressed','oversize-compressed','tar-checksum','tar-traversal','duplicate-member'],scopeCorrection:'Original inspect.mjs included mutable administrative top-level captures and stopped on a committed-blob mismatch. Preserved exit1, no decode. This version admits only named frozen manifests/artifact; no expectation relaxation on them.'});
 test('changed-compressed',()=>{const bytes=Buffer.from(compressed);bytes[0]^=1;assert.throws(()=>admit(bytes,archiveSize,archiveHash));assert.equal(decoders,0);});
 test('short-compressed',()=>{assert.throws(()=>admit(compressed.subarray(1),archiveSize,archiveHash));assert.equal(decoders,0);});
 test('oversize-compressed',()=>{assert.throws(()=>admit(Buffer.concat([compressed,Buffer.from([0])]),archiveSize,archiveHash));assert.equal(decoders,0);});
 assert(checks.every(row=>row.pass));decoders++;const decoded=zlib.gunzipSync(compressed,{maxOutputLength:33554432});const members=tar(decoded);assert.equal(members.size,1070);assert.equal(decoded.length,data.tarBytes);
 test('tar-checksum',()=>{const changed=Buffer.from(decoded);changed[0]^=1;assert.throws(()=>tar(changed));});
 test('tar-traversal',()=>{const changed=Buffer.from(decoded);changed.fill(0,0,100);Buffer.from('package/../outside').copy(changed);changed.fill(32,148,156);let sum=0;for(let index=0;index<512;index++)sum+=changed[index];Buffer.from(sum.toString(8).padStart(6,'0')+'\0 ').copy(changed,148);assert.throws(()=>tar(changed));});
 test('duplicate-member',()=>{const size=octal(decoded.subarray(124,136));const first=decoded.subarray(0,512+Math.ceil(size/512)*512);assert.throws(()=>tar(Buffer.concat([first,decoded])));});
 const actual=[...members.values()].map(row=>({path:row.path,size:row.size,mode:row.mode,sha256:sha(row.body)})).sort((left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path)));
 assert.deepEqual(actual,shipping.members);assert.equal(actual.reduce((sum,row)=>sum+row.size,0),5382293);assert.equal(sha(Buffer.from(actual.map(row=>JSON.stringify([row.path,row.size,row.mode,row.sha256])+'\n').join(''))),shipping.canonicalSha256);
 assert.equal(emits.rows.length,1068);for(const row of emits.rows){const actualRow=members.get('dist/'+row.path);assert(actualRow);assert.equal(actualRow.size,row.size);assert.equal(actualRow.mode,row.mode);assert.equal(sha(actualRow.body),row.sha256);}
 assert.equal(sources.inputs.length,323);assert.equal(sources.excludedCount,40);assert.equal(tools.typedFiles,115);
 const sourceRoot=preseal.procedure.sourceRoot;assert.equal(sourceRoot,'/private/tmp/safe-bash-final-composition-20260829/source');const sourceMap=new Map();for(const row of sources.inputs){assert(!row.path.includes('xan')&&!row.path.includes('yq')&&!row.path.includes('query-core'));assert(!row.path.endsWith('AGENTS.md'));const bytes=read(path.join(sourceRoot,row.path),row);assert.equal(blob(bytes),row.blob);sourceMap.set(row.path,bytes);}
 const canonical=sources.inputs.slice().sort((left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path))).map(row=>JSON.stringify([row.path,row.mode,row.blob,row.bytes,row.sha256])+'\n').join('');assert.equal(sha(Buffer.from(canonical)),sources.canonicalRowsSha256);
 for(const row of emits.rows)read(path.join(sourceRoot,'dist',row.path),row);
 for(const name of ['README.md','package.json'])assert.deepEqual(members.get(name).body,sourceMap.get(name));
 const pkg=JSON.parse(members.get('package.json').body);assert.equal(Object.keys(pkg.dependencies??{}).length,0);const exports=[];function leaves(value){if(typeof value==='string')exports.push(value);else if(value&&typeof value==='object')for(const child of Object.values(value))leaves(child);}leaves(pkg.exports);for(const target of exports){assert(target.startsWith('./'));assert(members.has(target.slice(2)));assert(!target.includes('/ere/')&&!target.includes('worker-entry'));}assert(!Object.keys(pkg.exports).some(key=>key.includes('*')));
 assert.equal(closure.privateAssetCount,48);for(const row of closure.privateAssets){const item=members.get(row.path);assert(item);assert.equal(sha(item.body),row.sha256);}
 let literal=0;for(const edge of closure.edges){assert(members.has(edge.from));if(edge.target.startsWith('.')){assert.equal(path.posix.normalize(path.posix.join(path.posix.dirname(edge.from),edge.target)),edge.resolved);assert(members.has(edge.resolved));assert(members.get(edge.from).body.toString().includes(edge.target));}literal++;}assert.equal(literal,1259);assert.equal(closure.unresolved.length,0);assert.equal(closure.privatePublicExports.length,0);
 let mapCount=0;for(const [name,row]of members){if(!name.endsWith('.map'))continue;const map=JSON.parse(row.body);for(let index=0;index<map.sources.length;index++){const selected=path.posix.normalize(path.posix.join(path.posix.dirname(name),map.sourceRoot??'',map.sources[index]));assert(sourceMap.has(selected));if(map.sourcesContent?.[index]!==undefined&&map.sourcesContent[index]!==null)assert.equal(map.sourcesContent[index],sourceMap.get(selected).toString());}mapCount++;}
 assert.equal(data.compilerExit,0);assert.equal(data.packExit,0);assert.equal(producer.launches.filter(row=>row.role==='compiler').length<=1,true);
 read(archivePath,{bytes:archiveSize,sha256:archiveHash});
 const result={verdict:checks.every(row=>row.pass)?'QUALIFIED_FROZEN_PRODUCER_DATA_ACCEPT':'HOLD',archive:{path:archivePath,bytes:archiveSize,sha256:archiveHash},dataReceiptSha256:sha(records['DATA-RECEIPT.json']),freezeCommit:'ab46a006a0f324a42c563542e4545ce80de49731',finalCommit:'937f1d9317256c18066d9f74c0ae0bb21842bfaa',counts:{sources:323,typedManifest:115,emits:1068,shipping:1070,privateAssets:48,literalEdges:literal,sourceMaps:mapCount},checks,decoders,parsers,decodedBytes:decoded.length,shippingCanonicalSha256:shipping.canonicalSha256,closureSha256:sha(records['CLOSURE.json']),nonliteralSites:closure.nonliteralSites,producerLaunches:producer.launches,qualification:'Actual same-buffer hash-before-inflate DATA audit, no extraction/import/evaluation. Compiler/pack outcomes are authenticated historical receipts, not rerun. Tool manifest/type115 identity bound as DATA; no fresh npm/module runtime load census. Static/provider edges qualified. Original overbroad inspection failure retained.',elapsedMs:Date.now()-started};write('RESULT.json',result);
 write('REPORT.md',`# Frozen final producer DATA audit\n\n${result.verdict}. Archive974493B/${archiveHash} and producer receipt frozen at ab46a006 before decode; manifests authenticated to937f1d93. Exact same admitted Buffer decoded once, bounded32MiB; no extracted files/imports/Workers/build/npm/install. Full1070 unique regular tar members/checksums/modes/hashes and canonical manifest checked;1068 dist outputs also match frozen materialization.323 source hashes/Git-blob identities and canonical build projection checked at declared frozen sourceRoot, not liveHEAD. No excluded XAN/yq/query-core source opened.48 private assets/1259 declared literal edges and source maps verified; computed/provider sites retain author's static qualification. Public exports equal packaged frozen source package, no private wildcard, runtime deps empty.\n\nSix tamper controls; compressed refusals had zero decoder calls.115 types/tool manifest authenticated as frozen metadata, not fresh transitive npm load proof. Strict compiler/offline pack statuses retained from bound receipts, not default npm build or installation/smoke evidence.40 excluded extras are names/classification only. Later ROOT-authorized default-config work not incorporated.\n\nInitial inspect.mjs failed before decode by asserting all top-level administrative captures equal committed blobs. That overbroad-scope failure and raw exit1 remain. This version selects explicit final manifest/artifact authorities without weakening their hash checks. No source/artifact mismatch waived. Quiescent183161294/55of56/peak3 are producer observations, not independently repeated quota/native peak/RSS/census. Final smoke still requires actual producer/layout/tool/permission/work-fit binding; all runtime assertions remain UNRUN.\n`);
 console.log(JSON.stringify({verdict:result.verdict,counts:result.counts,controls:checks,receiptSha256:sha(fs.readFileSync(path.join(own,'RESULT.json')))}));process.exitCode=result.verdict==='HOLD'?1:0;
}catch(reason){console.error(reason);write('AUDIT-FAILURE.json',{primaryPresent:true,detail:String(reason),stack:reason?.stack,checks,decoders,parsers,bound,elapsedMs:Date.now()-started});process.exitCode=1;}
