import fs from 'node:fs';
import path from 'node:path';
import {hash as digest} from './auth.mjs';
export {digest};
export function retainPrimary(primary,secondary){return primary.present?primary:secondary;}
export class Storage{
 constructor(root,limits,clock=Date.now,operations=fs){this.root=root;this.limits=limits;this.clock=clock;this.fs=operations;this.bytes=0;this.completed=0;}
 check(final=false){if(this.clock()>=(final?this.limits.finalDeadline:this.limits.bodyDeadline))throw Error(final?'FINAL_DEADLINE':'BODY_DEADLINE');}
 file(name,bytes,{terminal=false}={}){this.check(terminal);if(!/^[a-zA-Z0-9_.-]+$/.test(name)||this.bytes+bytes.length>this.limits.maximum)throw Error('STORAGE_LIMIT_OR_NAME');let fd;let primary={present:false};let closed=false;this.bytes+=bytes.length;try{fd=this.fs.openSync(path.join(this.root,name),'wx',0o600);this.fs.writeFileSync(fd,bytes);this.fs.fsyncSync(fd);if(this.fs.fstatSync(fd).size!==bytes.length)throw Error('PUBLICATION_SIZE');this.check(terminal);}catch(reason){primary={present:true,reason};}finally{if(fd!==undefined){try{this.fs.closeSync(fd);closed=true;}catch(reason){primary=retainPrimary(primary,{present:true,reason});}}}if(primary.present)throw primary.reason;this.check(terminal);if(!closed)throw Error('PUBLICATION_CLOSE');this.completed++;return {bytes:bytes.length,sha256:digest(bytes),closed};}
 terminal(name,value){return this.file(name,Buffer.from(JSON.stringify(value,null,2)+'\n'),{terminal:true});}
}
export function authenticated(filename,pin,max=16777216){const before=fs.lstatSync(filename);if(!before.isFile()||before.isSymbolicLink()||before.size!==pin.bytes||before.size>max)throw Error('AUTH_TYPE_SIZE');const fd=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let bytes;try{const opened=fs.fstatSync(fd);if(opened.ino!==before.ino||opened.dev!==before.dev)throw Error('AUTH_IDENTITY');bytes=Buffer.alloc(before.size);let count=0;while(count<bytes.length){const size=fs.readSync(fd,bytes,count,Math.min(65536,bytes.length-count),count);if(!size)throw Error('AUTH_SHORT');count+=size;}const probe=Buffer.alloc(1);if(fs.readSync(fd,probe,0,1,count))throw Error('AUTH_LONG');const after=fs.fstatSync(fd),current=fs.lstatSync(filename);if(after.size!==before.size||after.mtimeMs!==before.mtimeMs||after.ctimeMs!==before.ctimeMs||current.ino!==before.ino||current.dev!==before.dev)throw Error('AUTH_MUTATION');if(digest(bytes)!==pin.sha256)throw Error('AUTH_HASH');}finally{fs.closeSync(fd);}return bytes;}
