import { expect, it } from "vitest";
import { functionDescriptors } from "./function-descriptors.js";
import { recalculateWorkbook } from "./evaluator.js";
import type { CapabilityContext } from "../contracts.js";

// Independently transcribed from the authenticated 1.12.61 manifests and C descriptor tables.
const released: readonly (readonly [string, string | null, string, string])[] = [
  [
    "DAVERAGE",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DCOUNT",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DCOUNTA",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DGET",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DMAX",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DMIN",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DPRODUCT",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DSTDEV",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DSTDEVP",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DSUM",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DVAR",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "DVARP",
    "rSr",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "GETPIVOTDATA",
    "rs",
    "GNM_FUNC_SIMPLE",
    "fn-database"
  ],
  [
    "CELL",
    "sr",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "COUNTBLANK",
    "r",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ERROR",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ERROR.TYPE",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "EXPRESSION",
    "r",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "GET.FORMULA",
    "r",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "GET.LINK",
    "r",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "INFO",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISBLANK",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISERR",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISERROR",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISEVEN",
    "f",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISFORMULA",
    "r",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISLOGICAL",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISNA",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISNONTEXT",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISNUMBER",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISODD",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISREF",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "ISTEXT",
    "E",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "N",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "NA",
    "",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "TYPE",
    "?",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "GETENV",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-info"
  ],
  [
    "AND",
    null,
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "OR",
    null,
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "XOR",
    null,
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "NOT",
    "b",
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "IFERROR",
    "EE",
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_SECOND",
    "fn-logical"
  ],
  [
    "IFNA",
    "EE",
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_SECOND",
    "fn-logical"
  ],
  [
    "IFS",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-logical"
  ],
  [
    "SWITCH",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-logical"
  ],
  [
    "TRUE",
    "",
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "FALSE",
    "",
    "GNM_FUNC_SIMPLE + GNM_FUNC_AUTO_UNITLESS",
    "fn-logical"
  ],
  [
    "ADDRESS",
    "ff|fbs",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "AREAS",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "ARRAY",
    null,
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "CHOOSE",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "COLUMN",
    "|A",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "COLUMNNUMBER",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "COLUMNS",
    "A",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "FLIP",
    "A|b",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "HLOOKUP",
    "EAf|bb",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "HYPERLINK",
    "S|S",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "INDIRECT",
    "s|b",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "INDEX",
    "A|fff",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "LOOKUP",
    "EA|r",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "MATCH",
    "EA|f",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "OFFSET",
    "rff|ff",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "ROW",
    "|A",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "ROWS",
    "A",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "SHEET",
    "|?",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "SHEETS",
    "|A",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "SORT",
    "r|f",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "TRANSPOSE",
    "A",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "UNIQUE",
    "A|bb",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "VLOOKUP",
    "EAf|bb",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "XLOOKUP",
    "EAA|?ff",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-lookup"
  ],
  [
    "XMATCH",
    "EA|ff",
    "GNM_FUNC_SIMPLE",
    "fn-lookup"
  ],
  [
    "ASC",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "CHAR",
    "f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "CLEAN",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "CODE",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "CONCAT",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "CONCATENATE",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "DOLLAR",
    "f|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "ENCODEURL",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "EXACT",
    "SS",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "FIND",
    "SS|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "FINDB",
    "SS|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "FIXED",
    "f|fb",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "JIS",
    "s",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "LEFT",
    "S|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "LEFTB",
    "S|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "LEN",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "LENB",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "LOWER",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "MID",
    "Sff",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "MIDB",
    "Sff",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "NUMBERVALUE",
    "SS",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "PROPER",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "REPLACE",
    "SffS",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "REPLACEB",
    "SffS",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "REPT",
    "Sf",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "RIGHT",
    "S|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "RIGHTB",
    "S|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "SEARCH",
    "SS|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "SEARCHB",
    "SS|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "SUBSTITUTE",
    "SSS|f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "T",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "TEXT",
    "Ss",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "TEXTAFTER",
    "SA|ffff",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "TEXTBEFORE",
    "SA|ffff",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "TEXTJOIN",
    null,
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "TEXTSPLIT",
    "SA|A?f?",
    "GNM_FUNC_RETURNS_NON_SCALAR",
    "fn-string"
  ],
  [
    "TRIM",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "UNICHAR",
    "f",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "UNICODE",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "UPPER",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ],
  [
    "VALUE",
    "S",
    "GNM_FUNC_SIMPLE",
    "fn-string"
  ]
];
const context: CapabilityContext = { signal: new AbortController().signal,
  environment: { env: {}, locale: "C", timezone: "UTC" },
  limits: { inputBytes: 10000, outputBytes: 10000, cells: 100, sheets: 2, operations: 100, workbookWork: 10000 }, own() {} };
it("covers exactly the five stable released plugin inventories and descriptor contracts", () => {
  const groups = new Set(["fn-database", "fn-info", "fn-logical", "fn-lookup", "fn-string"]);
  expect(Object.keys(functionDescriptors).filter(name => groups.has(functionDescriptors[name]!.group)).sort()).toEqual(released.map(([name]) => name).sort());
  for (const [name, signature, flags, group] of released) expect(functionDescriptors[name]).toEqual({ signature, flags, group });
});
it.each(released.filter((row): row is readonly [string, string, string, string] => row[1] !== null))(
  "rejects wrong fixed arity for %s before evaluating arguments", (name, signature) => {
    const types = signature.split("|").join(""), pipe = signature.indexOf("|"), minimum = pipe < 0 ? types.length : pipe;
    let draws = 0;
    const supplied = { ...context, random: { next() { draws++; return .5; } } };
    for (const args of [Array(types.length + 1).fill("RAND()"), ...(minimum ? [Array(minimum - 1).fill("RAND()")] : [])]) {
      const book = { sheets: [{ id: "s", name: "Sheet", cells: [{ row: 0, column: 0, formula: `=${name}(${args.join(",")})`, formulaDirty: true,
        value: { kind: "number" as const, value: 0 } }] }] };
      // INDEX has a signature for help but uses the node callback's own #VALUE! contract.
      expect(recalculateWorkbook(book, supplied).sheets[0]!.cells[0]!.value).toEqual({ kind: "error", value: name === "INDEX" ? "#VALUE!" : "#N/A" });
    }
    expect(draws).toBe(0);
  });
