// Frozen SQLAlchemy 2.0.54 identifier/DDL profile; not a DBAPI driver.
import type { DatabaseDialectDescriptor } from "./descriptor.js";
export const oracle: DatabaseDialectDescriptor = {
  "name": "oracle",
  defaultDriver: 'cx_oracle',
  drivers: { cx_oracle: { module: 'cx_Oracle' }, oracledb: { module: 'oracledb' } },
  "quoteStart": "\"",
  "quoteEnd": "\"",
  "reserved": [
    "all",
    "alter",
    "and",
    "any",
    "as",
    "asc",
    "between",
    "by",
    "char",
    "check",
    "cluster",
    "comment",
    "compress",
    "connect",
    "create",
    "current",
    "date",
    "decimal",
    "default",
    "delete",
    "desc",
    "distinct",
    "drop",
    "else",
    "exclusive",
    "exists",
    "float",
    "for",
    "from",
    "grant",
    "group",
    "having",
    "identified",
    "in",
    "index",
    "insert",
    "integer",
    "intersect",
    "into",
    "is",
    "level",
    "like",
    "lock",
    "long",
    "minus",
    "mode",
    "nocompress",
    "not",
    "nowait",
    "null",
    "number",
    "of",
    "on",
    "option",
    "or",
    "order",
    "pctfree",
    "prior",
    "public",
    "raw",
    "rename",
    "resource",
    "revoke",
    "select",
    "set",
    "share",
    "size",
    "smallint",
    "start",
    "synonym",
    "table",
    "then",
    "to",
    "trigger",
    "uid",
    "union",
    "unique",
    "update",
    "user",
    "values",
    "varchar",
    "varchar2",
    "view",
    "where",
    "with"
  ],
  "illegalInitial": [
    "$",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "_"
  ],
  "typedTypes": {"TimeDelta": "INTERVAL DAY TO SECOND"},
  "numericPrecision": 38
};
