import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync,readdirSync,lstatSync,readlinkSync,existsSync,createReadStream,createWriteStream,rmSync,unlinkSync} from 'node:fs';
import {join,dirname,relative,basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createGzip} from 'node:zlib';
import {once} from 'node:events';
import {finished} from 'node:stream/promises';
const owned=dirname(fileURLToPath(import.meta.url)),repository='/Users/kjopek/Workspace/safe-bash';
const read=name=>JSON.parse(readFileSync(join(owned,name))),sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const save=(name,value)=>writeFileSync(join(owned,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
async function hashFile(path){const hash=createHash('sha256');for await(const chunk of createReadStream(path,{highWaterMark:65536}))hash.update(chunk);return hash.digest('hex');}
const binding=read('BINDINGS.json'),setup=read('FULL-SETUP.json'),safety=read('SAFETY-RESULTS.json'),routes=read('ROUTE-RESULTS.json'),a10=read('A10-RESULTS.json');
assert.equal(safety.status,'SCOPED_RESOLVED_WRITE_SAFETY_PASS');assert.equal(routes.status,'ROUTE_PREREQUISITES_PASS');assert.equal(a10.status,'SHARED_A10_AND_REAL_DUPLICATE_SCOPED_PASS');
const inner=JSON.parse(readFileSync(a10.positive.reportPath)),typing=JSON.parse(readFileSync(a10.positive.typingPath));
assert.equal(typing.phases.length,32);assert.equal(typing.builds,1);assert.equal(typing.consumers.groups.length,23);assert.equal(typing.consumers.passed,true);assert.equal(typing.sourceConsumers.groups.length,3);assert.equal(typing.sourceConsumers.passed,true);assert.equal(typing.consumers.negativeTypes.length,3);assert.deepEqual(typing.consumers.negativeTypes.map(row=>[row.status,row.diagnostics]),[['pass',1],['pass',2],['pass',5]]);assert.equal(typing.candidateBinding.declarations.length,208);assert.equal(typing.runtimeExecutions,0);assert.equal(typing.cleaned,true);assert.equal(inner.buildReceipt.files.length,832);assert.equal(inner.actualProductionBuilds.length,1);
assert.equal(inner.archive.logical.count,37397);assert.equal(inner.archive.count,37392);assert.equal(inner.archive.metadataOnly.length,5);
for(const[index,entry]of setup.dependencies.entries()){assert.deepEqual(entry.projection.physical,inner.dependencyProjection[index].logical);assert.deepEqual(inner.dependencyProjection[index].logical,inner.dependencyProjection[index].physical);}
assert.equal(setup.dependencies[1].projection.metadataOnly.length,1);assert.equal(a10.duplicate.events.length,2);assert.equal(a10.duplicate.emittedUnchanged,true);
for(const[name,identity]of Object.entries(binding.files))assert.equal(await hashFile(join(binding.driver,name)),identity.sha256);
for(const[path,hash]of Object.entries(binding.prior))assert.equal(await hashFile(join(repository,path)),hash,'prior artifact changed: '+path);
const cohorts=[safety],runs=[a10.launch,a10.outerReport.fence.result,a10.duplicate.result,...a10.outerReport.fence.phaseReceipt.events.map(row=>row.result),...cohorts.flatMap(cohort=>[cohort.shipping.result,...cohort.shipping.phaseReceipt.events.map(row=>row.result)])];
const identities=[...new Map(runs.flatMap(row=>row.observed??[]).map(row=>[row.pid+':'+row.born,row])).values()];
const processes=['UTC','America/Chicago'].flatMap(TZ=>execFileSync('/bin/ps',['-axo','pid=,ppid=,pgid=,lstart=,command='],{env:{PATH:'/usr/bin:/bin',TZ},encoding:'utf8',timeout:5000,maxBuffer:8*1024*1024}).trim().split('\n').map(line=>{const parts=line.trim().split(/\s+/u);return{pid:Number(parts[0]),born:parts.slice(3,8).join(' '),command:parts.slice(8).join(' '),TZ};}));
const survivors=identities.filter(row=>processes.some(current=>row.pid===current.pid&&row.born===current.born));assert.deepEqual(survivors,[]);
const toolPaths=[...binding.externalTools.map(row=>row.physical),binding.toolRoutes.inspector.physical,'/usr/bin/sandbox-exec'];
const observedAbsolute=[...new Set(identities.map(row=>row.command.split(/\s+/u)[0]).filter(path=>path.startsWith('/')))];
const knownAliasBindings=[safety.worker.toolPath,inner.toolRoutes],selectedTools=[],unboundTools=[];
for(const path of observedAbsolute){let expected=binding.preImportToolFiles.find(row=>row.physical===path);let alias;for(const route of knownAliasBindings){const entry=route.aliases.find(row=>join(route.path,row.name)===path);if(entry){expected=entry;alias={path,target:readlinkSync(path)};assert.equal(alias.target,entry.physical);}}
if(path==='/usr/bin/sandbox-exec')expected={physical:path,sha256:binding.tools[path].sha256};
if(expected){assert.equal(await hashFile(expected.physical),expected.sha256);selectedTools.push({observed:path,physical:expected.physical,sha256:expected.sha256,alias:alias??null});}else unboundTools.push({path,qualification:'Not added to an OS exception or silently accepted'});}
assert.equal(unboundTools.length,0,'unbound actual tool route observed');
for(const denied of binding.toolRoutes.deniedSelectorExecutables)assert.equal(observedAbsolute.includes(denied),false,'selector executable actually observed');
save('TOOL-CLOSURE.json',{source:binding.source,externalReceipt:binding.externalReceipt,toolRoutesSha256:binding.toolRoutesSha256,inspector:binding.toolRoutes.inspector,preImportToolRecords:binding.preImportToolFiles.length,selectedTools,unboundTools,gitCore:routes.gitCore,aliases:inner.toolRoutes.aliases,processBasenames:[...new Set(identities.map(row=>row.command.split(/\s+/u)[0]).filter(path=>/^\(/u.test(path)))],inspection:routes.controls.find(row=>row.id==='P02-four-real-direct-inspections').actual,qualification:'Actual inspector PID/argv/environment/output receipts and pre-execution identities, finite alias/core binding; observed commands are polling evidence, not a complete dynamic process-image inventory. Only original11+sandbox2+approved inspector2 OS metadata reference pairs. No unbound xcodebuild allowance.'});
const roots=[binding.temporary,...safety.shipping.envelope.roots.map(row=>row.path),...a10.outerReport.fence.envelope.roots.map(row=>row.path),a10.outer];assert.equal(new Set(roots).size,roots.length);
for(const envelope of [safety.shipping.envelope,a10.outerReport.fence.envelope])for(const identity of envelope.roots){const stat=lstatSync(identity.path);assert.deepEqual([stat.dev,stat.ino,stat.mode&0o777,stat.uid],[identity.device,identity.inode,identity.mode,identity.uid]);}
const rawRoots=[join(binding.temporary,'raw'),join(binding.temporary,'a10-raw'),safety.shipping.envelope.roots[1].path,a10.outerReport.fence.envelope.roots[1].path,a10.outer];
const rawFiles=[],instructionNames=[];let regularBytes=0,regularFiles=0;
const manifestHash=createHash('sha256'),manifestZip=createGzip({level:9}),manifestOut=createWriteStream(join(owned,'FILESYSTEM.ndjson.gz'),{flags:'wx'});manifestZip.pipe(manifestOut);
async function emitManifest(row){const line=JSON.stringify(row)+'\n';manifestHash.update(line);if(!manifestZip.write(line))await once(manifestZip,'drain');}
async function walk(root,directory=root){for(const name of readdirSync(directory).sort()){
  const path=join(directory,name),stat=lstatSync(path),entry={root,path:relative(root,path),device:stat.dev,inode:stat.ino,mode:stat.mode&0o777,links:stat.nlink};
  if(/^agents\.md$/iu.test(name)){instructionNames.push(path);await emitManifest({...entry,kind:'instruction-name-metadata-only'});continue;}
  if(stat.isSymbolicLink())await emitManifest({...entry,kind:'symlink',target:readlinkSync(path)});
  else if(stat.isDirectory()){await emitManifest({...entry,kind:'directory'});await walk(root,path);}
  else{assert.ok(stat.isFile());regularBytes+=stat.size;regularFiles++;assert.ok(regularBytes<=8589934592);const row={...entry,kind:'file',bytes:stat.size,sha256:await hashFile(path)};await emitManifest(row);if(rawRoots.some(prefix=>path.startsWith(prefix+'/')))rawFiles.push({...row,absolute:path});}
}}
for(const root of roots){assert.match(root,/^\/private\/tmp\/(?:unified76-independent-tool-v10-|unified76-os-write-|unified76-build-types-review-tool-routes-v10-|unified76-build-types-outer-)/u);assert.ok(lstatSync(root).isDirectory());await walk(root);}
assert.deepEqual(instructionNames,[]);manifestZip.end();await finished(manifestOut);
for(const name of ['A10-POSITIVE.json','A10-RESULTS.json']){const path=join(owned,name),stat=lstatSync(path);rawFiles.push({root:owned,path:name,absolute:path,kind:'generated-raw-report',bytes:stat.size,sha256:await hashFile(path)});}
const rawHash=createHash('sha256'),rawZip=createGzip({level:9}),rawOut=createWriteStream(join(owned,'RAW.ndjson.gz'),{flags:'wx'});rawZip.pipe(rawOut);let captureBytes=0;
async function emitRaw(row){const line=JSON.stringify(row)+'\n';rawHash.update(line);if(!rawZip.write(line))await once(rawZip,'drain');}
for(const[index,file]of rawFiles.entries()){
  captureBytes+=file.bytes;assert.ok(captureBytes<=268435456);await emitRaw({...file,kind:'start',id:index});let bytes=0;const hash=createHash('sha256');
  for await(const chunk of createReadStream(file.absolute,{highWaterMark:65536})){bytes+=chunk.length;hash.update(chunk);await emitRaw({kind:'chunk',id:index,base64:chunk.toString('base64')});}
  assert.equal(bytes,file.bytes);assert.equal(hash.digest('hex'),file.sha256);await emitRaw({kind:'end',id:index,bytes,sha256:file.sha256});
}
rawZip.end();await finished(rawOut);
save('RAW-INDEX.json',{schema:1,format:'gzip streamed NDJSON start/chunk/end; each data chunk <=64KiB; no source/compiler/instruction payload capture',files:rawFiles.map(({absolute,...entry})=>entry),bytes:captureBytes,ndjsonSha256:rawHash.digest('hex'),gzipSha256:await hashFile(join(owned,'RAW.ndjson.gz')),filesystem:{file:'FILESYSTEM.ndjson.gz',ndjsonSha256:manifestHash.digest('hex'),gzipSha256:await hashFile(join(owned,'FILESYSTEM.ndjson.gz')),regularFiles,regularBytes,instructionNames}});
const safetyRecords=safety.controls.map(row=>JSON.parse(row.stdout)),instructionOperations=safetyRecords.reduce((sum,row)=>sum+row.events.filter(event=>event.instruction).length+row.events.reduce((count,event)=>count+(event.instructionAttempts??0),0),0);assert.equal(instructionOperations,11);
save('RESULTS.json',{
  schema:1,status:'QUALIFIED_SCOPED_RESOLVED_WRITES_ARCHIVE_AND_A10_PROVEN; COMPLETE_BINDING_HOLD',source:binding.source,additionalControls:binding.additionalControls,evidence:binding.evidence,candidate:binding.candidate,driverSha256:binding.normalizedDriverSha256,profileSha256:binding.profileSha256,projectionSha256:binding.projectionSha256,policySha256:sha(readFileSync(join(owned,'POLICY.json'))),packet:binding.packet,
  matrix:[{id:'R01',status:'PASS',scope:'inert file/directory links positive; resolved outside write/append/truncate/new-child deny, bytes/inodes/entries unchanged'},{id:'R02',status:'PASS',scope:'relative/renamed/chained/tmp aliases deny outside effects; contained link/output/literal POSIX backslash positives'},{id:'R03',status:'PASS',scope:'fresh instruction targets and ASCII case variants through alias/chain/rename create/append deny; direct instruction-name link deny; no existing protected file setup'},{id:'R04',status:'PASS',scope:'outside regular inode hardlink/direct+directory-alias and physical directory rename/tmp-alias deny; unfenced ordinary capability positives'},{id:'R05',status:'PASS_SCOPED',scope:'cleared-env Node/native descendants enforce writes, shipping foreign-canary FD absent, three separately grouped sentinels survive then controller termination'},{id:'R06',status:'PASS_CORRECTED_COHORT',scope:'real historical native Git/tar denial; original target succeeded but worker receipt-name collision exit1 preserved'},{id:'R07',status:'PASS_SCOPED',scope:'actual frozen full projected A10 and actual second compiler duplicate audit refusal; not fullgate or runtime consumer acceptance'}],
  cohorts:{safety:{phasePass:5,phaseFail:0},historicalInitial:{target:0,tar:1,worker:1,reason:'APFS case-insensitive report filename collision after target; retained'},historicalFollowup:{target:0,tar:1,worker:0},a10:{cold:78,typecheckAll:0,positiveBuilds:1,expectedCompilerInvocations:32,maintainedGroups:23,sourceGroups:3,negativeGroups:typing.consumers.negativeTypes,runtimeExecutions:0,emitted:832,declarations:208,candidateBinding:typing.candidateBinding.metadataSha256,emitManifestSha256:sha(JSON.stringify(inner.buildReceipt.files))},duplicate:{compiler:a10.duplicate.result.status,refusal:a10.duplicate.refusal,realCompilerPids:a10.duplicate.events.map(row=>row.pid),emittedUnchanged:true,qualification:'One extra real compiler is the explicit negative only; not permission for two positive driver builds'}},
  attempts:{independentInstructionOperations:instructionOperations,denied:instructionOperations,nativeArchiveMemberAttempts:2,nativeArchiveMembersDenied:2,unexpectedPhysicalInstructionFiles:0,qualification:'Operation/member counts, not an invented syscall count; both historical archive cohorts retained. A10 projection metadata omissions are not write attempts.'},
  fullCandidate:{logical:inner.archive.logical,physical:inner.archive.count,candidateMetadataOnly:inner.archive.metadataOnly,originalDependencyProjection:setup.dependencies.map(row=>row.projection),secondHopProjection:inner.dependencyProjection,compositePhysicalHashesMatch:true,opaqueHistory:setup.opaqueHistory,assembly:setup.assembly,qualification:'Original object stream480921521 bytes, no checkout/alternates. Full candidate reconstructed with frozen cat-file transport, not typing-only selection; no fresh whole-candidate tar claim. Exact5 candidate plus1 benchmark omissions composed across two authenticated dependency hops.'},
  historical:{revision:native.revision,instruction:native.instruction,archive:native.archive,ordinaryPublished:native.physical.filter(row=>row.present).length,tarExit:native.logs.at(-1).status,instructionTargetAbsent:true},
  tools:{external:setup.external,extraObservedPrerequisiteBindingsNeeded:extraTools,qualification:'Read-only original dependency/tool closure admitted by frozen verifier. Extra Xcode shim process observed without explicit pre-run EXTERNAL tool binding; complete tool-chain closure remains HOLD, no new OS metadata exception.'},
  provenance:{sourceFileHashes:binding.files,osProfiles:[...cohorts.map(cohort=>cohort.shipping.envelope.profileSha256),a10.outerReport.fence.envelope.profileSha256],priorArtifactsUnchanged:Object.keys(binding.prior).length,qualification:'Actual frozen shipping phaseRunner/outer OS launch used; no independent write interceptor. Parent source imports authenticated by full source guards; phase hook traces retained, not exhaustive process-image tracing.'},
  sevenNew76Proofs:[{id:'binding-complete',status:'HOLD_AUTHOR_REBOUND_TOOL_CHAIN_BINDING_NEW_ROOT_RELEASE_AND_FULLGATE_UNEXECUTED'},...['binding-pending-template','binding-mutable-head','binding-missing-asset','binding-missing-classification','binding-missing-cleanup-manifest','binding-skipped-case'].map(id=>({id,status:'PRIOR_BOUNDED_REFUSAL_HISTORY_NOT_RERUN'}))],
  history:'Old v8 2PASS/1FAIL plus safe2/9denials, missing-compiler and seal-alias failures, e5848/A10/13observer,21+1 original22 history, stopped0/14 and forbidden-copy incident unchanged. No old rescore or author outcomes counted.',
  package:{sha256:'c109372f90b1bd19bcf756cf993bb2976fb52b75fe0c92a1cf96dab4c229b5cd',freshPack:false,qualification:'Carried identical candidate/source/emit lineage; no new tarball reproduction'},publicPrerequisites:'Root HTML/DU/Expr accepted',rootRelease:'ABSENT',fullGateLaunched:false,privateAccess:false,
  limitations:['Existing protected-file precondition not introduced; all instruction targets fresh and absent','Known hostile external writable-FD provider limitation carried, not retested as extra score; shipping r+ foreign canary closure reconfirmed','No new network firewall/secrecy or malicious-host-JS certificate; no private engine/native semantic cohort','Foreign sentinel/natural phase closure exercised, no new forced-leak corpus','Frozen phaseRunner1800000ms/256MiB caps remain; parent40minute watchdog and source transport bounds; cooperative disk sample not kernel disk/RSS cap','No new author packet/root release accepted; observed Xcode helper binding gap requires explicit rebound prerequisite, not blanket trusted-OS expansion']
});
for(const name of ['A10-POSITIVE.json','A10-RESULTS.json'])unlinkSync(join(owned,name));
for(const root of roots)rmSync(root,{recursive:true,force:false});assert.ok(roots.every(root=>!existsSync(root)));
for(const[path,hash]of Object.entries(binding.prior))assert.equal(await hashFile(join(repository,path)),hash);
save('CLEANUP.json',{at:new Date().toISOString(),roots,allAbsent:true,regularFiles,regularBytes,rawBytes:captureBytes,priorArtifactsUnchanged:Object.keys(binding.prior).length,observedIdentities:identities,survivors,sentinels:cohorts.map(cohort=>cohort.sentinel),rawGeneratedReports:'A10-POSITIVE/A10-RESULTS exact bytes preserved in RAW.ndjson.gz before removing generated uncommitted plain captures',qualification:'Only owned roots removed; no foreign cleanup/signals. Watched targets naturally settled; controller-owned sentinels explicitly SIGTERM. PID/birth checks use both recorded timezone profiles. No fullgate/private execution.'});
console.log(JSON.stringify({status:'SEALED_SCOPED_PROOF_WITH_COMPLETE_BINDING_HOLD',rawFiles:rawFiles.length,captureBytes,regularFiles,regularBytes,removedRoots:roots.length,priorArtifacts:Object.keys(binding.prior).length,extraObservedTools:extraTools.map(row=>row.path)}));save('RESULTS.json',{schema:1,status:'SCOPED_FINAL_ROUTE_AND_A10_ACCEPTED_ROOT_RELEASE_ABSENT',source:binding.source,evidence:binding.evidence,candidate:binding.candidate,driverSha256:binding.normalizedDriverSha256,profileSha256:binding.profileSha256,projectionSha256:binding.projectionSha256,toolRoutesSha256:binding.toolRoutesSha256,externalReceipt:binding.externalReceipt,packet:binding.packet,controlFreezeSha256:await hashFile(join(owned,'CONTROL-FREEZE.json')),
controls:{routePrerequisites:{pass:routes.controls.filter(row=>row.status==='PASS').length,fail:routes.controls.filter(row=>row.status==='FAIL').length,cases:routes.controls.map(({id,status})=>({id,status}))},shippingPhases:{pass:safety.controls.filter(row=>row.status===0).length,fail:safety.controls.filter(row=>row.status!==0).length,cases:safety.controls.map(({id,status})=>({id,status}))},shadowMutations:safety.worker.shadows,shippingDescriptors:safety.worker.descriptors,sentinel:safety.sentinel,qualification:'Eight route groups,three shipping phases and three worker-side shadow mutations have distinct denominators; no author12 or old22 outcomes counted.'},
a10:{cold:inner.phases[0].status,typecheckAll:inner.phases[1].status,driverProductionBuilds:inner.actualProductionBuilds,compilerInvocations:typing.phases.length,maintained:typing.consumers.groups.map(row=>({name:row.name,status:row.status})),maintainedCount:typing.consumers.groups.length,source:typing.sourceConsumers.groups.map(row=>({name:row.name,status:row.status})),sourceCount:typing.sourceConsumers.groups.length,expectedNegative:typing.consumers.negativeTypes,emitted:inner.buildReceipt.files.length,declarations:typing.candidateBinding.declarations.length,emitManifestSha256:sha(JSON.stringify(inner.buildReceipt.files)),candidateBinding:typing.candidateBinding.metadataSha256,cleaned:typing.cleaned,runtimeExecutions:typing.runtimeExecutions,toolPath:inner.toolRoutes,duplicate:{compiler:a10.duplicate.result.status,refusal:a10.duplicate.refusal,events:a10.duplicate.events,emittedUnchanged:a10.duplicate.emittedUnchanged}},
fullProjection:{logical:inner.archive.logical,physical:inner.archive.count,candidateMetadataOnly:inner.archive.metadataOnly,dependencies:setup.dependencies.map(row=>row.projection),secondHop:inner.dependencyProjection,compositePhysicalHashesMatch:true,opaqueHistory:setup.opaqueHistory,assembly:setup.assembly,qualification:'Complete candidate,not typing-only subset. Exact5 candidate+1 benchmark omission; second-hop copies already projected dependencies; no instruction text snapshot or checkout.'},
provenance:{sourceFileHashes:binding.files,osProfiles:[safety.shipping.envelope.profileSha256,a10.outerReport.fence.envelope.profileSha256],priorArtifactsUnchanged:Object.keys(binding.prior).length},
protectedAttempts:{operations:2,denied:2,unexpectedPhysicalInstructionFiles:instructionNames.length,qualification:'Fresh benign Node/native protected-target operations only; not syscall counts. Inert links intentionally created. Historical tar attempts inherited,not rerun or added to fresh denominator.'},
transport:{unboundInitialSymlink:a10.transportRefusal,qualification:'Actual frozen extraction-path admission refusal,not broadened runtime symlink policy'},
sevenNew76Proofs:[{id:'binding-complete',status:'SCOPED_EVIDENCE_READY_FRESH_ROOT_RELEASE_BINDING_ABSENT_FULLGATE_UNEXECUTED'},...['binding-pending-template','binding-mutable-head','binding-missing-asset','binding-missing-classification','binding-missing-cleanup-manifest','binding-skipped-case'].map(id=>({id,status:'PRIOR_BOUNDED_REFUSAL_HISTORY_NOT_RERUN'}))],
package:{sha256:'c109372f90b1bd19bcf756cf993bb2976fb52b75fe0c92a1cf96dab4c229b5cd',freshPack:false,qualification:'Identical candidate/source with prior v9 package lineage carried; no author or independent fresh pack in this cohort'},
limits:{rawBytes:captureBytes,regularBytes,regularFiles,qualification:'Finite shipping/parent watchdog,stream and capture bounds; cooperative disk accounting,not a kernel disk/RSS or malicious-host security boundary'},
remaining:['Root fresh release absent; full14phase finite PATH compatibility unexecuted','Known externally supplied writable FD limitation; shipping closure checked,not hostile-provider security','Poll-based process metadata and exact inspection receipts are not every dynamic library/process-image attestation','No full native semantics/private engine/network corpus; historical stopped0/14 and forbidden-copy incident unchanged'],history:'All366 earlier independent artifacts including38a4e7b,f1f1daaa,e584,old unbound-tool and failures unchanged. Original22 and author cohorts not rescored.',publicPrerequisites:'Root HTML/DU/Expr accepted',fullGateLaunched:false,privateAccess:false,rootRelease:'ABSENT'});
for(const name of ['A10-POSITIVE.json','A10-RESULTS.json'])unlinkSync(join(owned,name));
for(const root of roots)rmSync(root,{recursive:true,force:false});assert.ok(roots.every(root=>!existsSync(root)));
for(const[path,hash]of Object.entries(binding.prior))assert.equal(await hashFile(join(repository,path)),hash);
save('CLEANUP.json',{at:new Date().toISOString(),roots,allAbsent:true,regularFiles,regularBytes,rawBytes:captureBytes,priorArtifactsUnchanged:Object.keys(binding.prior).length,observedIdentities:identities,survivors,sentinel:safety.sentinel,qualification:'Only exact owned roots removed after metadata/hash receipt; targets naturally settled,foreign-review sentinel survived and was owner-terminated. No unrelated signals or root/private writes. A10 generated plain reports preserved losslessly before removal.'});
console.log(JSON.stringify({status:'SEALED',rawFiles:rawFiles.length,captureBytes,regularFiles,regularBytes,removedRoots:roots.length,priorArtifacts:Object.keys(binding.prior).length,unboundTools:unboundTools.length}));
