import {strict as assert} from 'node:assert';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {validateStartupReceipt} from './startup-receipt.mjs';
import {derived} from './budget.mjs';
const rows=[];function fixture(phase='runtime'){const stdout={path:'/owned/outer.stdout',bytes:0,sha256:'0'.repeat(64)},stderr={path:'/owned/outer.stderr',bytes:1,sha256:'1'.repeat(64)};return {value:{schema:3,producer:'ROOT_TRUSTED_TOOL_POSTCHECK',phase,pid:123,toolReturned:true,toolExitCode:0,startupCapture:'RESERVED_POSTCHECK_NOT_PREWRITE_ENFORCED',streamCensus:'NOT_OBSERVED',workerRetirement:'NOT_INFERRED',activationSha256:'2'.repeat(64),stdout,stderr},expected:{phase,pid:123,activationSha256:'2'.repeat(64),stdout:stdout.path,stderr:stderr.path},actual:{stdout:{...stdout},stderr:{...stderr}}};}function run(id,body){try{body();rows.push({id,pass:true});}catch(error){rows.push({id,pass:false,message:error instanceof Error?error.message:'nonError'});}}
run('R3-01-runtime-trusted-postcheck',()=>{const row=fixture();assert.equal(validateStartupReceipt(row.value,row.expected,row.actual),row.value);assert.equal(row.value.streamCensus,'NOT_OBSERVED');});
run('R3-02-publication-trusted-postcheck',()=>{const row=fixture('publication');assert.equal(validateStartupReceipt(row.value,row.expected,row.actual),row.value);});
run('R3-03-old-enforcement-and-EOF-claims-refused',()=>{for(const change of ['old','enforced','EOF']){const row=fixture();if(change==='old')row.value.schema=1;if(change==='enforced')row.value.captureEnforced=true;if(change==='EOF')row.value.streamCensus='COMPLETE';assert.throws(()=>validateStartupReceipt(row.value,row.expected,row.actual));}});
run('R3-04-overflow-and-byte-binding',()=>{for(const bytes of [-1,65537,Infinity,NaN,'0']){const row=fixture();row.value.stdout={...row.value.stdout,bytes};assert.throws(()=>validateStartupReceipt(row.value,row.expected,row.actual));}const row=fixture();row.actual.stderr.bytes=2;assert.throws(()=>validateStartupReceipt(row.value,row.expected,row.actual));});
run('R3-05-own-data-no-getters-extras',()=>{let calls=0;for(const mode of ['accessor','nested','hidden','symbol']){const row=fixture();if(mode==='accessor')Object.defineProperty(row.value,'toolReturned',{get(){calls++;return true;}});if(mode==='nested')Object.defineProperty(row.value.stdout,'bytes',{get(){calls++;return 0;}});if(mode==='hidden')Object.defineProperty(row.value,'extra',{value:false});if(mode==='symbol')row.value[Symbol('extra')]=false;assert.throws(()=>validateStartupReceipt(row.value,row.expected,row.actual));}assert.equal(calls,0);});
run('R3-06-reserve-and-identity',()=>{assert.equal(derived.totalCapture,6078464);assert.equal(derived.workCeiling,21594112);for(const key of ['pid','phase','activationSha256','toolReturned']){const row=fixture();row.value[key]=key==='pid'?124:key==='phase'?'publication':key==='toolReturned'?false:'3'.repeat(64);assert.throws(()=>validateStartupReceipt(row.value,row.expected,row.actual));}});
const result={schema:3,groups:6,passed:rows.filter(row=>row.pass).length,rows,Workers:0,children:0,productImports:0,actualPostcheckFiles:0};writeFileSync(fileURLToPath(new URL('./CONTROL-RESULT.json',import.meta.url)),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));if(result.passed!==6)process.exitCode=1;
