import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import {isDeepStrictEqual} from 'node:util';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const input=JSON.parse(fs.readFileSync(path.join(root,'INPUTS.json'))),author=input.author,parent=path.dirname(author);
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const sha1=bytes=>crypto.createHash('sha1').update(bytes).digest('hex');
function pinned(file,pin,max=2097152){const stat=fs.lstatSync(file),size=pin.bytes??pin.size;if(!stat.isFile()||stat.size!==size||size>max||(pin.mode!==undefined&&(stat.mode&4095)!==pin.mode))throw Error('type/size/mode '+file);const buffer=fs.readFileSync(file);if(buffer.length!==size||hash(buffer)!==pin.sha256)throw Error('identity '+file);return buffer;}
const checks=[];const check=(name,value)=>checks.push({name,pass:value===true});
for(const pin of input.pins)pinned(pin.path,pin);
const sealBytes=pinned(path.join(author,'SEAL.json'),{bytes:7074,sha256:input.sealSha256});const seal=JSON.parse(sealBytes);
const sourceBytes=pinned(path.join(parent,'SOURCE.json'),input.source),source=JSON.parse(sourceBytes);
const compiled=JSON.parse(pinned(seal.compiled.path,seal.compiled));
const packagePin=input.pins.find(pin=>pin.path.endsWith('/PACKAGE-MANIFEST.json')),manifestBytes=pinned(packagePin.path,packagePin),manifest=JSON.parse(manifestBytes);
const receiptPin=input.pins.find(pin=>pin.path.endsWith('/PRE-INFLATE-RECEIPT.json')),receipt=JSON.parse(pinned(receiptPin.path,receiptPin));
const sourceReportPin=input.pins.find(pin=>pin.path.endsWith('/SOURCE-REPORT.json')),sourceReport=JSON.parse(pinned(sourceReportPin.path,sourceReportPin));
pinned(seal.oldSeal.path,seal.oldSeal);
const tools=JSON.parse(pinned(seal.tools.path,seal.tools));
const toolPins=[];function collectToolPins(value){if(!value||typeof value!=='object')return;if(typeof value.path==='string'&&typeof value.sha256==='string'&&Number.isSafeInteger(value.size))toolPins.push(value);for(const item of Object.values(value))if(item&&typeof item==='object')collectToolPins(item);}collectToolPins(tools);
let streamedTools=0;const unverifiedToolPaths=[];
for(const pin of toolPins){if(!path.isAbsolute(pin.path)){unverifiedToolPaths.push(pin.path);continue;}const stat=fs.lstatSync(pin.path);if(!stat.isFile()||stat.size!==pin.size||(stat.mode&4095)!==pin.mode)throw Error('tool type/size/mode');const digest=crypto.createHash('sha256');for await(const bytes of fs.createReadStream(pin.path,{highWaterMark:65536}))digest.update(bytes);if(digest.digest('hex')!==pin.sha256)throw Error('tool hash');streamedTools++;}
const producer=JSON.parse(pinned(receipt.producer.path,receipt.producer))[0];
check('producer archive SHA1/integrity',producer.shasum===receipt.sha1&&producer.integrity===receipt.integrity);
const candidate=seal.cwd;
check('candidate explicit source tree',source.selectedTree==='da4e1cc187022255521879b00db2ac77674f79d9'&&source.sources.length===305&&seal.sourceInputs===305);
const tree={};for(const row of source.sources){const bytes=pinned(path.join(candidate,row.path),{...row,mode:parseInt(row.mode,8)&4095});check('source blob '+row.path,sha1(Buffer.concat([Buffer.from('blob '+bytes.length+'\0'),bytes]))===row.blob);const parts=row.path.split('/');let current=tree;for(const part of parts.slice(0,-1)){current[part]??={};current=current[part];}current[parts.at(-1)]={blob:row.blob,mode:row.mode};}
function treeHash(directory){const entries=Object.entries(directory).map(([name,value])=>({name,value,directory:!Object.hasOwn(value,'blob')}));entries.sort((left,right)=>Buffer.compare(Buffer.from(left.name+(left.directory?'/':'')),Buffer.from(right.name+(right.directory?'/':''))));const content=Buffer.concat(entries.map(entry=>Buffer.concat([Buffer.from((entry.directory?'40000':entry.value.mode)+' '+entry.name+'\0'),Buffer.from(entry.directory?treeHash(entry.value):entry.value.blob,'hex')])));return sha1(Buffer.concat([Buffer.from('tree '+content.length+'\0'),content]));}
const derived=treeHash(tree);check('canonical full305 tree',derived===source.selectedTree);
const compiledMap=new Map();for(const row of compiled.rows){pinned(path.join(candidate,row.path),row);if(compiledMap.has(row.path))throw Error('duplicate compiled');compiledMap.set(row.path,row);}check('1305 source/compiled',compiledMap.size===1305);
const configStats=seal.configs.map(pin=>{pinned(pin.path,pin);return fs.lstatSync(pin.path);});check('two distinct empty configs',seal.configs.length===2&&seal.configs.every(pin=>pin.size===0)&&seal.configs[0].path!==seal.configs[1].path&&(configStats[0].dev!==configStats[1].dev||configStats[0].ino!==configStats[1].ino));check('offline scripts disabled role',seal.argv.includes('--offline')&&seal.argv.includes('--ignore-scripts')&&seal.env.npm_config_userconfig!==seal.env.npm_config_globalconfig);
let decoderCalls=0;
function admitted(bytes,stat,pin){if(!stat.regular||stat.size!==pin.bytes||bytes.length!==pin.bytes||bytes.length>908381||hash(bytes)!==pin.sha256)throw Error('pre-decode refusal');decoderCalls++;return zlib.gunzipSync(bytes,{maxOutputLength:67108864});}
const descriptor=fs.openSync(receipt.path,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);let compressed;
try{const stat=fs.fstatSync(descriptor);if(!stat.isFile()||stat.size!==908381||(stat.mode&4095)!==420)throw Error('archive descriptor admission');compressed=Buffer.alloc(908381);let offset=0;while(offset<compressed.length){const count=fs.readSync(descriptor,compressed,offset,compressed.length-offset,null);if(!count)throw Error('short read');offset+=count;}if(fs.readSync(descriptor,Buffer.alloc(1),0,1,null)!==0)throw Error('archive grew');}finally{fs.closeSync(descriptor);}
if(hash(compressed)!==input.archive.sha256)throw Error('archive pre-inflate hash');
const controls=[];for(const [name,bytes,stat,pin]of [['nonregular',compressed,{regular:false,size:908381},input.archive],['short',compressed.subarray(0,-1),{regular:true,size:908380},input.archive],['extra',Buffer.concat([compressed,Buffer.from([0])]),{regular:true,size:908382},input.archive],['wronghash',compressed,{regular:true,size:908381},{...input.archive,sha256:'0'.repeat(64)}],['size',compressed,{regular:true,size:1},input.archive],['tampered',Buffer.concat([Buffer.from([compressed[0]^1]),compressed.subarray(1)]),{regular:true,size:908381},input.archive]]){const before=decoderCalls;let refused=false;try{admitted(bytes,stat,pin);}catch{refused=true;}controls.push({name,pass:refused&&decoderCalls===before});}
const decoded=admitted(compressed,{regular:true,size:908381},input.archive);check('decoded exact bytes',decoded.length===5784064);
function parse(tar){const members=[];let position=0;const seen=new Set();while(position+512<=tar.length){const header=tar.subarray(position,position+512);if(header.every(value=>value===0)){if(!tar.subarray(position).every(value=>value===0))throw Error('tar tail');break;}const text=(start,length)=>header.subarray(start,start+length).toString('utf8').split('\0')[0];const octal=(start,length)=>{const raw=text(start,length).trim();if(!/^[0-7]+$/.test(raw))throw Error('octal');return parseInt(raw,8);};const stored=octal(148,8);let sum=0;for(let index=0;index<512;index++)sum+=index>=148&&index<156?32:header[index];if(sum!==stored)throw Error('checksum');const type=header[156];if(type!==0&&type!==48)throw Error('nonregular tar');const prefix=text(345,155),full=(prefix?prefix+'/':'')+text(0,100);if(!full.startsWith('package/'))throw Error('package prefix');const name=full.slice(8);if(!name||name.startsWith('/')||name.split('/').some(part=>part==='..'||part==='.'||part==='')||seen.has(name))throw Error('unsafe or duplicate tar path');seen.add(name);const size=octal(124,12),mode=octal(100,8),end=position+512+size;if(end>tar.length)throw Error('truncated tar');const body=tar.subarray(position+512,end);members.push({path:name,size,mode,sha256:hash(body)});position+=512+Math.ceil(size/512)*512;}return members;}
const byteOrder=(left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path));
const members=parse(decoded);check('full1002 tar inventory',isDeepStrictEqual([...members].sort(byteOrder),[...manifest.members].sort(byteOrder)));check('summed file bytes',members.reduce((sum,row)=>sum+row.size,0)===5021166);
for(const row of members){const expected=compiledMap.get(row.path);check('compiled package '+row.path,Boolean(expected)&&row.size===expected.size&&row.mode===expected.mode&&row.sha256===expected.sha256);}
const checksumBad=Buffer.from(decoded);checksumBad[0]^=1;let refused=false;try{parse(checksumBad);}catch{refused=true;}controls.push({name:'tar checksum',pass:refused});
const pathBad=Buffer.from(decoded);pathBad.fill(0,0,100);pathBad.write('package/../escape',0);pathBad.fill(32,148,156);let checksum=0;for(const value of pathBad.subarray(0,512))checksum+=value;pathBad.write(checksum.toString(8).padStart(6,'0')+'\0 ',148);refused=false;try{parse(pathBad);}catch{refused=true;}controls.push({name:'tar traversal',pass:refused});
const pkgSource=pinned(path.join(candidate,'package.json'),compiledMap.get('package.json'));const pkg=JSON.parse(pkgSource);check('unchanged exports/deps',isDeepStrictEqual(pkg.exports,manifest.exports)&&Object.keys(pkg.dependencies??{}).length===0);check('no private export wildcard',!Object.entries(pkg.exports).some(([key,value])=>JSON.stringify([key,value]).includes('regex-execution')));
const privateAssets=manifest.privateAssets;for(const row of privateAssets){const member=members.find(value=>value.path===row.path);check('private shipped '+row.path,Boolean(member)&&member.sha256===row.sha256);}
const staticEdges=[];for(const row of privateAssets.filter(row=>row.path.endsWith('.js'))){const text=pinned(path.join(candidate,row.path),row).toString('utf8');for(const match of text.matchAll(/(?:from\s*|import\s*\(|new URL\s*\()\s*["'](\.[^"']+)["']/g)){const target=path.posix.normalize(path.posix.join(path.posix.dirname(row.path),match[1]));check('static private target '+row.path+' -> '+target,compiledMap.has(target));staticEdges.push({from:row.path,to:target});}}
const logs=input.pins.filter(pin=>/A(?:09|12|15)\.(?:stdout|stderr)$/.test(pin.path)).map(pin=>({path:pin.path,sha256:pin.sha256,text:pinned(pin.path,pin).toString()}));
const privateHash=hash(Buffer.from(JSON.stringify(privateAssets))),edgeHash=hash(Buffer.from(JSON.stringify(staticEdges)));
const result={at:new Date().toISOString(),candidate:derived,sourceManifestSha256:hash(sourceBytes),compiledManifestSha256:seal.compiled.sha256,packageManifestSha256:hash(manifestBytes),packageSha256:hash(compressed),privateAssetsSha256:privateHash,staticEdgesSha256:edgeHash,counts:{sources:source.sources.length,compiled:compiledMap.size,members:members.length,privateAssets:privateAssets.length,staticEdges:staticEdges.length,streamedTools},unverifiedToolPaths,checks:checks.length,passed:checks.filter(row=>row.pass).length,failed:checks.filter(row=>!row.pass),controls,decoderCalls,strictConsumerRaw:logs,sourceReportFields:Object.keys(sourceReport),sourceReportCompiler:Object.fromEntries(Object.entries(sourceReport).filter(([key])=>/child|compiler|positive|negative|consumer|phase/i.test(key))),sourceOverrideRows:source.sources.filter(row=>row.group!=='core'),staticEdges,qualification:'SOURCE/PRODUCER DATA only. Recorded strict compilation is not rerun. Static literal layout is not Worker execution/authorization. All70 runtime and private60 remain unexecuted here.'};
fs.writeFileSync(path.join(root,'RESULT.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result,null,2));if(result.failed.length||controls.some(row=>!row.pass))process.exitCode=1;
