/** CPython 3.14.7 library definitions, executed by the guest interpreter.
 * Copyright CNRI / Python Software Foundation; see the package CPYTHON-LICENSE.txt.
 * Stream method bodies and concrete adapters retain upstream source verbatim.
 * Module assembly and package discovery are owned by runtime-codec-library.ts.
 * codecs.py SHA-256 718f39b3ea68fe934214d789c5bce3005fa828040b03a72d2f715fc5e2647b7e
 * encodings/__init__.py SHA-256 2b708410495acf12a6fad9d2de928dd89e567537c253eaa2b51aaae578e96c59
 * encodings/aliases.py SHA-256 1ee993f8eb4986999b6501381e53947be9a04443626cb48b4190bcff2e87d3b4
 * encodings/ascii.py SHA-256 578aa1173f7cc60dad2895071287fe6182bd14787b3fbf47a6c7983dfe3675e3
 * encodings/latin_1.py SHA-256 b75503e532a27c636477396c855209ff5f3036536d2a4bede0a576c89382b60c
 * encodings/utf_8.py SHA-256 ba0cac060269583523ca9506473a755203037c57d466a11aa89a30a5f6756f3d
 */
export const codecLibrarySources: ReadonlyMap<string,string> = new Map([
  ["codecs", [
    "\"\"\" codecs -- Python Codec Registry, API and helpers.",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "from _codecs import *",
    "",
    "",
    "",
    "",
    "__all__ = [\"register\",\"lookup\",\"open\",\"EncodedFile\",\"BOM\",\"BOM_BE\",\"BOM_LE\",\"BOM32_BE\",\"BOM32_LE\",\"BOM64_BE\",\"BOM64_LE\",\"BOM_UTF8\",\"BOM_UTF16\",\"BOM_UTF16_LE\",\"BOM_UTF16_BE\",\"BOM_UTF32\",\"BOM_UTF32_LE\",\"BOM_UTF32_BE\",\"CodecInfo\",\"Codec\",\"IncrementalEncoder\",\"IncrementalDecoder\",\"StreamReader\",\"StreamWriter\",\"StreamReaderWriter\",\"StreamRecoder\",\"getencoder\",\"getdecoder\",\"getincrementalencoder\",\"getincrementaldecoder\",\"getreader\",\"getwriter\",\"encode\",\"decode\",\"iterencode\",\"iterdecode\",\"strict_errors\",\"ignore_errors\",\"replace_errors\",\"xmlcharrefreplace_errors\",\"backslashreplace_errors\",\"namereplace_errors\",\"register_error\",\"lookup_error\"]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "class CodecInfo(tuple):",
    "    \"\"\"Codec details when looking up the codec registry\"\"\"",
    "",
    "    # Private API to allow Python 3.4 to denylist the known non-Unicode",
    "    # codecs in the standard library. A more general mechanism to",
    "    # reliably distinguish test encodings from other codecs will hopefully",
    "    # be defined for Python 3.5",
    "    #",
    "    # See http://bugs.python.org/issue19619",
    "    _is_text_encoding = True # Assume codecs are text encodings by default",
    "",
    "    def __new__(cls, encode, decode, streamreader=None, streamwriter=None,",
    "        incrementalencoder=None, incrementaldecoder=None, name=None,",
    "        *, _is_text_encoding=None):",
    "        self = tuple.__new__(cls, (encode, decode, streamreader, streamwriter))",
    "        self.name = name",
    "        self.encode = encode",
    "        self.decode = decode",
    "        self.incrementalencoder = incrementalencoder",
    "        self.incrementaldecoder = incrementaldecoder",
    "        self.streamwriter = streamwriter",
    "        self.streamreader = streamreader",
    "        if _is_text_encoding is not None:",
    "            self._is_text_encoding = _is_text_encoding",
    "        return self",
    "",
    "    def __repr__(self):",
    "        return \"<%s.%s object for encoding %s at %#x>\" % \\",
    "                (self.__class__.__module__, self.__class__.__qualname__,",
    "                 self.name, id(self))",
    "",
    "    def __getnewargs__(self):",
    "        return tuple(self)",
    "",
    "class Codec:",
    "",
    "    \"\"\" Defines the interface for stateless encoders/decoders.",
    "",
    "        The .encode()/.decode() methods may use different error",
    "        handling schemes by providing the errors argument. These",
    "        string values are predefined:",
    "",
    "         'strict' - raise a ValueError error (or a subclass)",
    "         'ignore' - ignore the character and continue with the next",
    "         'replace' - replace with a suitable replacement character;",
    "                    Python will use the official U+FFFD REPLACEMENT",
    "                    CHARACTER for the builtin Unicode codecs on",
    "                    decoding and '?' on encoding.",
    "         'surrogateescape' - replace with private code points U+DCnn.",
    "         'xmlcharrefreplace' - Replace with the appropriate XML",
    "                               character reference (only for encoding).",
    "         'backslashreplace'  - Replace with backslashed escape sequences.",
    "         'namereplace'       - Replace with \\\\N{...} escape sequences",
    "                               (only for encoding).",
    "",
    "        The set of allowed values can be extended via register_error.",
    "",
    "    \"\"\"",
    "    def encode(self, input, errors='strict'):",
    "",
    "        \"\"\" Encodes the object input and returns a tuple (output",
    "            object, length consumed).",
    "",
    "            errors defines the error handling to apply. It defaults to",
    "            'strict' handling.",
    "",
    "            The method may not store state in the Codec instance. Use",
    "            StreamWriter for codecs which have to keep state in order to",
    "            make encoding efficient.",
    "",
    "            The encoder must be able to handle zero length input and",
    "            return an empty object of the output object type in this",
    "            situation.",
    "",
    "        \"\"\"",
    "        raise NotImplementedError",
    "",
    "    def decode(self, input, errors='strict'):",
    "",
    "        \"\"\" Decodes the object input and returns a tuple (output",
    "            object, length consumed).",
    "",
    "            input must be an object which provides the bf_getreadbuf",
    "            buffer slot. Python strings, buffer objects and memory",
    "            mapped files are examples of objects providing this slot.",
    "",
    "            errors defines the error handling to apply. It defaults to",
    "            'strict' handling.",
    "",
    "            The method may not store state in the Codec instance. Use",
    "            StreamReader for codecs which have to keep state in order to",
    "            make decoding efficient.",
    "",
    "            The decoder must be able to handle zero length input and",
    "            return an empty object of the output object type in this",
    "            situation.",
    "",
    "        \"\"\"",
    "        raise NotImplementedError",
    "",
    "class IncrementalEncoder(object):",
    "    \"\"\"",
    "    An IncrementalEncoder encodes an input in multiple steps. The input can",
    "    be passed piece by piece to the encode() method. The IncrementalEncoder",
    "    remembers the state of the encoding process between calls to encode().",
    "    \"\"\"",
    "    def __init__(self, errors='strict'):",
    "        \"\"\"",
    "        Creates an IncrementalEncoder instance.",
    "",
    "        The IncrementalEncoder may use different error handling schemes by",
    "        providing the errors keyword argument. See the module docstring",
    "        for a list of possible values.",
    "        \"\"\"",
    "        self.errors = errors",
    "        self.buffer = \"\"",
    "",
    "    def encode(self, input, final=False):",
    "        \"\"\"",
    "        Encodes input and returns the resulting object.",
    "        \"\"\"",
    "        raise NotImplementedError",
    "",
    "    def reset(self):",
    "        \"\"\"",
    "        Resets the encoder to the initial state.",
    "        \"\"\"",
    "",
    "    def getstate(self):",
    "        \"\"\"",
    "        Return the current state of the encoder.",
    "        \"\"\"",
    "        return 0",
    "",
    "    def setstate(self, state):",
    "        \"\"\"",
    "        Set the current state of the encoder. state must have been",
    "        returned by getstate().",
    "        \"\"\"",
    "",
    "class BufferedIncrementalEncoder(IncrementalEncoder):",
    "    \"\"\"",
    "    This subclass of IncrementalEncoder can be used as the baseclass for an",
    "    incremental encoder if the encoder must keep some of the output in a",
    "    buffer between calls to encode().",
    "    \"\"\"",
    "    def __init__(self, errors='strict'):",
    "        IncrementalEncoder.__init__(self, errors)",
    "        # unencoded input that is kept between calls to encode()",
    "        self.buffer = \"\"",
    "",
    "    def _buffer_encode(self, input, errors, final):",
    "        # Overwrite this method in subclasses: It must encode input",
    "        # and return an (output, length consumed) tuple",
    "        raise NotImplementedError",
    "",
    "    def encode(self, input, final=False):",
    "        # encode input (taking the buffer into account)",
    "        data = self.buffer + input",
    "        (result, consumed) = self._buffer_encode(data, self.errors, final)",
    "        # keep unencoded input until the next call",
    "        self.buffer = data[consumed:]",
    "        return result",
    "",
    "    def reset(self):",
    "        IncrementalEncoder.reset(self)",
    "        self.buffer = \"\"",
    "",
    "    def getstate(self):",
    "        return self.buffer or 0",
    "",
    "    def setstate(self, state):",
    "        self.buffer = state or \"\"",
    "",
    "class IncrementalDecoder(object):",
    "    \"\"\"",
    "    An IncrementalDecoder decodes an input in multiple steps. The input can",
    "    be passed piece by piece to the decode() method. The IncrementalDecoder",
    "    remembers the state of the decoding process between calls to decode().",
    "    \"\"\"",
    "    def __init__(self, errors='strict'):",
    "        \"\"\"",
    "        Create an IncrementalDecoder instance.",
    "",
    "        The IncrementalDecoder may use different error handling schemes by",
    "        providing the errors keyword argument. See the module docstring",
    "        for a list of possible values.",
    "        \"\"\"",
    "        self.errors = errors",
    "",
    "    def decode(self, input, final=False):",
    "        \"\"\"",
    "        Decode input and returns the resulting object.",
    "        \"\"\"",
    "        raise NotImplementedError",
    "",
    "    def reset(self):",
    "        \"\"\"",
    "        Reset the decoder to the initial state.",
    "        \"\"\"",
    "",
    "    def getstate(self):",
    "        \"\"\"",
    "        Return the current state of the decoder.",
    "",
    "        This must be a (buffered_input, additional_state_info) tuple.",
    "        buffered_input must be a bytes object containing bytes that",
    "        were passed to decode() that have not yet been converted.",
    "        additional_state_info must be a non-negative integer",
    "        representing the state of the decoder WITHOUT yet having",
    "        processed the contents of buffered_input.  In the initial state",
    "        and after reset(), getstate() must return (b\"\", 0).",
    "        \"\"\"",
    "        return (b\"\", 0)",
    "",
    "    def setstate(self, state):",
    "        \"\"\"",
    "        Set the current state of the decoder.",
    "",
    "        state must have been returned by getstate().  The effect of",
    "        setstate((b\"\", 0)) must be equivalent to reset().",
    "        \"\"\"",
    "",
    "class BufferedIncrementalDecoder(IncrementalDecoder):",
    "    \"\"\"",
    "    This subclass of IncrementalDecoder can be used as the baseclass for an",
    "    incremental decoder if the decoder must be able to handle incomplete",
    "    byte sequences.",
    "    \"\"\"",
    "    def __init__(self, errors='strict'):",
    "        IncrementalDecoder.__init__(self, errors)",
    "        # undecoded input that is kept between calls to decode()",
    "        self.buffer = b\"\"",
    "",
    "    def _buffer_decode(self, input, errors, final):",
    "        # Overwrite this method in subclasses: It must decode input",
    "        # and return an (output, length consumed) tuple",
    "        raise NotImplementedError",
    "",
    "    def decode(self, input, final=False):",
    "        # decode input (taking the buffer into account)",
    "        data = self.buffer + input",
    "        (result, consumed) = self._buffer_decode(data, self.errors, final)",
    "        # keep undecoded input until the next call",
    "        self.buffer = data[consumed:]",
    "        return result",
    "",
    "    def reset(self):",
    "        IncrementalDecoder.reset(self)",
    "        self.buffer = b\"\"",
    "",
    "    def getstate(self):",
    "        # additional state info is always 0",
    "        return (self.buffer, 0)",
    "",
    "    def setstate(self, state):",
    "        # ignore additional state info",
    "        self.buffer = state[0]",
    "",
    "#",
    "# The StreamWriter and StreamReader class provide generic working",
    "# interfaces which can be used to implement new encoding submodules",
    "# very easily. See encodings/utf_8.py for an example on how this is",
    "# done.",
    "#",
    "",
    "class StreamWriter(Codec):",
    "",
    "    def __init__(self, stream, errors='strict'):",
    "",
    "        \"\"\" Creates a StreamWriter instance.",
    "",
    "            stream must be a file-like object open for writing.",
    "",
    "            The StreamWriter may use different error handling",
    "            schemes by providing the errors keyword argument. These",
    "            parameters are predefined:",
    "",
    "             'strict' - raise a ValueError (or a subclass)",
    "             'ignore' - ignore the character and continue with the next",
    "             'replace'- replace with a suitable replacement character",
    "             'xmlcharrefreplace' - Replace with the appropriate XML",
    "                                   character reference.",
    "             'backslashreplace'  - Replace with backslashed escape",
    "                                   sequences.",
    "             'namereplace'       - Replace with \\\\N{...} escape sequences.",
    "",
    "            The set of allowed parameter values can be extended via",
    "            register_error.",
    "        \"\"\"",
    "        self.stream = stream",
    "        self.errors = errors",
    "",
    "    def write(self, object):",
    "",
    "        \"\"\" Writes the object's contents encoded to self.stream.",
    "        \"\"\"",
    "        data, consumed = self.encode(object, self.errors)",
    "        self.stream.write(data)",
    "",
    "    def writelines(self, list):",
    "",
    "        \"\"\" Writes the concatenated list of strings to the stream",
    "            using .write().",
    "        \"\"\"",
    "        self.write(''.join(list))",
    "",
    "    def reset(self):",
    "",
    "        \"\"\" Resets the codec buffers used for keeping internal state.",
    "",
    "            Calling this method should ensure that the data on the",
    "            output is put into a clean state, that allows appending",
    "            of new fresh data without having to rescan the whole",
    "            stream to recover state.",
    "",
    "        \"\"\"",
    "        pass",
    "",
    "    def seek(self, offset, whence=0):",
    "        self.stream.seek(offset, whence)",
    "        if whence == 0 and offset == 0:",
    "            self.reset()",
    "",
    "    def __getattr__(self, name,",
    "                    getattr=getattr):",
    "",
    "        \"\"\" Inherit all other methods from the underlying stream.",
    "        \"\"\"",
    "        return getattr(self.stream, name)",
    "",
    "    def __enter__(self):",
    "        return self",
    "",
    "    def __exit__(self, type, value, tb):",
    "        self.stream.close()",
    "",
    "    def __reduce_ex__(self, proto):",
    "        raise TypeError(\"can't serialize %s\" % self.__class__.__name__)",
    "",
    "###",
    "",
    "class StreamReader(Codec):",
    "",
    "    charbuffertype = str",
    "",
    "    def __init__(self, stream, errors='strict'):",
    "",
    "        \"\"\" Creates a StreamReader instance.",
    "",
    "            stream must be a file-like object open for reading.",
    "",
    "            The StreamReader may use different error handling",
    "            schemes by providing the errors keyword argument. These",
    "            parameters are predefined:",
    "",
    "             'strict' - raise a ValueError (or a subclass)",
    "             'ignore' - ignore the character and continue with the next",
    "             'replace'- replace with a suitable replacement character",
    "             'backslashreplace' - Replace with backslashed escape sequences;",
    "",
    "            The set of allowed parameter values can be extended via",
    "            register_error.",
    "        \"\"\"",
    "        self.stream = stream",
    "        self.errors = errors",
    "        self.bytebuffer = b\"\"",
    "        self._empty_charbuffer = self.charbuffertype()",
    "        self.charbuffer = self._empty_charbuffer",
    "        self.linebuffer = None",
    "",
    "    def decode(self, input, errors='strict'):",
    "        raise NotImplementedError",
    "",
    "    def read(self, size=-1, chars=-1, firstline=False):",
    "",
    "        \"\"\" Decodes data from the stream self.stream and returns the",
    "            resulting object.",
    "",
    "            chars indicates the number of decoded code points or bytes to",
    "            return. read() will never return more data than requested,",
    "            but it might return less, if there is not enough available.",
    "",
    "            size indicates the approximate maximum number of decoded",
    "            bytes or code points to read for decoding. The decoder",
    "            can modify this setting as appropriate. The default value",
    "            -1 indicates to read and decode as much as possible.  size",
    "            is intended to prevent having to decode huge files in one",
    "            step.",
    "",
    "            If firstline is true, and a UnicodeDecodeError happens",
    "            after the first line terminator in the input only the first line",
    "            will be returned, the rest of the input will be kept until the",
    "            next call to read().",
    "",
    "            The method should use a greedy read strategy, meaning that",
    "            it should read as much data as is allowed within the",
    "            definition of the encoding and the given size, e.g.  if",
    "            optional encoding endings or state markers are available",
    "            on the stream, these should be read too.",
    "        \"\"\"",
    "        # If we have lines cached, first merge them back into characters",
    "        if self.linebuffer:",
    "            self.charbuffer = self._empty_charbuffer.join(self.linebuffer)",
    "            self.linebuffer = None",
    "",
    "        if chars < 0:",
    "            # For compatibility with other read() methods that take a",
    "            # single argument",
    "            chars = size",
    "",
    "        # read until we get the required number of characters (if available)",
    "        while True:",
    "            # can the request be satisfied from the character buffer?",
    "            if chars >= 0:",
    "                if len(self.charbuffer) >= chars:",
    "                    break",
    "            # we need more data",
    "            if size < 0:",
    "                newdata = self.stream.read()",
    "            else:",
    "                newdata = self.stream.read(size)",
    "            # decode bytes (those remaining from the last call included)",
    "            data = self.bytebuffer + newdata",
    "            if not data:",
    "                break",
    "            try:",
    "                newchars, decodedbytes = self.decode(data, self.errors)",
    "            except UnicodeDecodeError as exc:",
    "                if firstline:",
    "                    newchars, decodedbytes = \\",
    "                        self.decode(data[:exc.start], self.errors)",
    "                    lines = newchars.splitlines(keepends=True)",
    "                    if len(lines)<=1:",
    "                        raise",
    "                else:",
    "                    raise",
    "            # keep undecoded bytes until the next call",
    "            self.bytebuffer = data[decodedbytes:]",
    "            # put new characters in the character buffer",
    "            self.charbuffer += newchars",
    "            # there was no data available",
    "            if not newdata:",
    "                break",
    "        if chars < 0:",
    "            # Return everything we've got",
    "            result = self.charbuffer",
    "            self.charbuffer = self._empty_charbuffer",
    "        else:",
    "            # Return the first chars characters",
    "            result = self.charbuffer[:chars]",
    "            self.charbuffer = self.charbuffer[chars:]",
    "        return result",
    "",
    "    def readline(self, size=None, keepends=True):",
    "",
    "        \"\"\" Read one line from the input stream and return the",
    "            decoded data.",
    "",
    "            size, if given, is passed as size argument to the",
    "            read() method.",
    "",
    "        \"\"\"",
    "        # If we have lines cached from an earlier read, return",
    "        # them unconditionally",
    "        if self.linebuffer:",
    "            line = self.linebuffer[0]",
    "            del self.linebuffer[0]",
    "            if len(self.linebuffer) == 1:",
    "                # revert to charbuffer mode; we might need more data",
    "                # next time",
    "                self.charbuffer = self.linebuffer[0]",
    "                self.linebuffer = None",
    "            if not keepends:",
    "                line = line.splitlines(keepends=False)[0]",
    "            return line",
    "",
    "        readsize = size or 72",
    "        line = self._empty_charbuffer",
    "        # If size is given, we call read() only once",
    "        while True:",
    "            data = self.read(readsize, firstline=True)",
    "            if data:",
    "                # If we're at a \"\\r\" read one extra character (which might",
    "                # be a \"\\n\") to get a proper line ending. If the stream is",
    "                # temporarily exhausted we return the wrong line ending.",
    "                if (isinstance(data, str) and data.endswith(\"\\r\")) or \\",
    "                   (isinstance(data, bytes) and data.endswith(b\"\\r\")):",
    "                    data += self.read(size=1, chars=1)",
    "",
    "            line += data",
    "            lines = line.splitlines(keepends=True)",
    "            if lines:",
    "                if len(lines) > 1:",
    "                    # More than one line result; the first line is a full line",
    "                    # to return",
    "                    line = lines[0]",
    "                    del lines[0]",
    "                    if len(lines) > 1:",
    "                        # cache the remaining lines",
    "                        lines[-1] += self.charbuffer",
    "                        self.linebuffer = lines",
    "                        self.charbuffer = None",
    "                    else:",
    "                        # only one remaining line, put it back into charbuffer",
    "                        self.charbuffer = lines[0] + self.charbuffer",
    "                    if not keepends:",
    "                        line = line.splitlines(keepends=False)[0]",
    "                    break",
    "                line0withend = lines[0]",
    "                line0withoutend = lines[0].splitlines(keepends=False)[0]",
    "                if line0withend != line0withoutend: # We really have a line end",
    "                    # Put the rest back together and keep it until the next call",
    "                    self.charbuffer = self._empty_charbuffer.join(lines[1:]) + \\",
    "                                      self.charbuffer",
    "                    if keepends:",
    "                        line = line0withend",
    "                    else:",
    "                        line = line0withoutend",
    "                    break",
    "            # we didn't get anything or this was our only try",
    "            if not data or size is not None:",
    "                if line and not keepends:",
    "                    line = line.splitlines(keepends=False)[0]",
    "                break",
    "            if readsize < 8000:",
    "                readsize *= 2",
    "        return line",
    "",
    "    def readlines(self, sizehint=None, keepends=True):",
    "",
    "        \"\"\" Read all lines available on the input stream",
    "            and return them as a list.",
    "",
    "            Line breaks are implemented using the codec's decoder",
    "            method and are included in the list entries.",
    "",
    "            sizehint, if given, is ignored since there is no efficient",
    "            way of finding the true end-of-line.",
    "",
    "        \"\"\"",
    "        data = self.read()",
    "        return data.splitlines(keepends)",
    "",
    "    def reset(self):",
    "",
    "        \"\"\" Resets the codec buffers used for keeping internal state.",
    "",
    "            Note that no stream repositioning should take place.",
    "            This method is primarily intended to be able to recover",
    "            from decoding errors.",
    "",
    "        \"\"\"",
    "        self.bytebuffer = b\"\"",
    "        self.charbuffer = self._empty_charbuffer",
    "        self.linebuffer = None",
    "",
    "    def seek(self, offset, whence=0):",
    "        \"\"\" Set the input stream's current position.",
    "",
    "            Resets the codec buffers used for keeping state.",
    "        \"\"\"",
    "        self.stream.seek(offset, whence)",
    "        self.reset()",
    "",
    "    def __next__(self):",
    "",
    "        \"\"\" Return the next decoded line from the input stream.\"\"\"",
    "        line = self.readline()",
    "        if line:",
    "            return line",
    "        raise StopIteration",
    "",
    "    def __iter__(self):",
    "        return self",
    "",
    "    def __getattr__(self, name,",
    "                    getattr=getattr):",
    "",
    "        \"\"\" Inherit all other methods from the underlying stream.",
    "        \"\"\"",
    "        return getattr(self.stream, name)",
    "",
    "    def __enter__(self):",
    "        return self",
    "",
    "    def __exit__(self, type, value, tb):",
    "        self.stream.close()",
    "",
    "    def __reduce_ex__(self, proto):",
    "        raise TypeError(\"can't serialize %s\" % self.__class__.__name__)",
    "",
    "###",
    "",
    "class StreamReaderWriter:",
    "",
    "    \"\"\" StreamReaderWriter instances allow wrapping streams which",
    "        work in both read and write modes.",
    "",
    "        The design is such that one can use the factory functions",
    "        returned by the codec.lookup() function to construct the",
    "        instance.",
    "",
    "    \"\"\"",
    "    # Optional attributes set by the file wrappers below",
    "    encoding = 'unknown'",
    "",
    "    def __init__(self, stream, Reader, Writer, errors='strict'):",
    "",
    "        \"\"\" Creates a StreamReaderWriter instance.",
    "",
    "            stream must be a Stream-like object.",
    "",
    "            Reader, Writer must be factory functions or classes",
    "            providing the StreamReader, StreamWriter interface resp.",
    "",
    "            Error handling is done in the same way as defined for the",
    "            StreamWriter/Readers.",
    "",
    "        \"\"\"",
    "        self.stream = stream",
    "        self.reader = Reader(stream, errors)",
    "        self.writer = Writer(stream, errors)",
    "        self.errors = errors",
    "",
    "    def read(self, size=-1):",
    "",
    "        return self.reader.read(size)",
    "",
    "    def readline(self, size=None, keepends=True):",
    "",
    "        return self.reader.readline(size, keepends)",
    "",
    "    def readlines(self, sizehint=None, keepends=True):",
    "",
    "        return self.reader.readlines(sizehint, keepends)",
    "",
    "    def __next__(self):",
    "",
    "        \"\"\" Return the next decoded line from the input stream.\"\"\"",
    "        return next(self.reader)",
    "",
    "    def __iter__(self):",
    "        return self",
    "",
    "    def write(self, data):",
    "",
    "        return self.writer.write(data)",
    "",
    "    def writelines(self, list):",
    "",
    "        return self.writer.writelines(list)",
    "",
    "    def reset(self):",
    "",
    "        self.reader.reset()",
    "        self.writer.reset()",
    "",
    "    def seek(self, offset, whence=0):",
    "        self.stream.seek(offset, whence)",
    "        self.reader.reset()",
    "        if whence == 0 and offset == 0:",
    "            self.writer.reset()",
    "",
    "    def __getattr__(self, name,",
    "                    getattr=getattr):",
    "",
    "        \"\"\" Inherit all other methods from the underlying stream.",
    "        \"\"\"",
    "        return getattr(self.stream, name)",
    "",
    "    # these are needed to make \"with StreamReaderWriter(...)\" work properly",
    "",
    "    def __enter__(self):",
    "        return self",
    "",
    "    def __exit__(self, type, value, tb):",
    "        self.stream.close()",
    "",
    "    def __reduce_ex__(self, proto):",
    "        raise TypeError(\"can't serialize %s\" % self.__class__.__name__)",
    "",
    "###",
    "",
    "class StreamRecoder:",
    "",
    "    \"\"\" StreamRecoder instances translate data from one encoding to another.",
    "",
    "        They use the complete set of APIs returned by the",
    "        codecs.lookup() function to implement their task.",
    "",
    "        Data written to the StreamRecoder is first decoded into an",
    "        intermediate format (depending on the \"decode\" codec) and then",
    "        written to the underlying stream using an instance of the provided",
    "        Writer class.",
    "",
    "        In the other direction, data is read from the underlying stream using",
    "        a Reader instance and then encoded and returned to the caller.",
    "",
    "    \"\"\"",
    "    # Optional attributes set by the file wrappers below",
    "    data_encoding = 'unknown'",
    "    file_encoding = 'unknown'",
    "",
    "    def __init__(self, stream, encode, decode, Reader, Writer,",
    "                 errors='strict'):",
    "",
    "        \"\"\" Creates a StreamRecoder instance which implements a two-way",
    "            conversion: encode and decode work on the frontend (the",
    "            data visible to .read() and .write()) while Reader and Writer",
    "            work on the backend (the data in stream).",
    "",
    "            You can use these objects to do transparent",
    "            transcodings from e.g. latin-1 to utf-8 and back.",
    "",
    "            stream must be a file-like object.",
    "",
    "            encode and decode must adhere to the Codec interface; Reader and",
    "            Writer must be factory functions or classes providing the",
    "            StreamReader and StreamWriter interfaces resp.",
    "",
    "            Error handling is done in the same way as defined for the",
    "            StreamWriter/Readers.",
    "",
    "        \"\"\"",
    "        self.stream = stream",
    "        self.encode = encode",
    "        self.decode = decode",
    "        self.reader = Reader(stream, errors)",
    "        self.writer = Writer(stream, errors)",
    "        self.errors = errors",
    "",
    "    def read(self, size=-1):",
    "",
    "        data = self.reader.read(size)",
    "        data, bytesencoded = self.encode(data, self.errors)",
    "        return data",
    "",
    "    def readline(self, size=None):",
    "",
    "        if size is None:",
    "            data = self.reader.readline()",
    "        else:",
    "            data = self.reader.readline(size)",
    "        data, bytesencoded = self.encode(data, self.errors)",
    "        return data",
    "",
    "    def readlines(self, sizehint=None):",
    "",
    "        data = self.reader.read()",
    "        data, bytesencoded = self.encode(data, self.errors)",
    "        return data.splitlines(keepends=True)",
    "",
    "    def __next__(self):",
    "",
    "        \"\"\" Return the next decoded line from the input stream.\"\"\"",
    "        data = next(self.reader)",
    "        data, bytesencoded = self.encode(data, self.errors)",
    "        return data",
    "",
    "    def __iter__(self):",
    "        return self",
    "",
    "    def write(self, data):",
    "",
    "        data, bytesdecoded = self.decode(data, self.errors)",
    "        return self.writer.write(data)",
    "",
    "    def writelines(self, list):",
    "",
    "        data = b''.join(list)",
    "        data, bytesdecoded = self.decode(data, self.errors)",
    "        return self.writer.write(data)",
    "",
    "    def reset(self):",
    "",
    "        self.reader.reset()",
    "        self.writer.reset()",
    "",
    "    def seek(self, offset, whence=0):",
    "        # Seeks must be propagated to both the readers and writers",
    "        # as they might need to reset their internal buffers.",
    "        self.reader.seek(offset, whence)",
    "        self.writer.seek(offset, whence)",
    "",
    "    def __getattr__(self, name,",
    "                    getattr=getattr):",
    "",
    "        \"\"\" Inherit all other methods from the underlying stream.",
    "        \"\"\"",
    "        return getattr(self.stream, name)",
    "",
    "    def __enter__(self):",
    "        return self",
    "",
    "    def __exit__(self, type, value, tb):",
    "        self.stream.close()",
    "",
    "    def __reduce_ex__(self, proto):",
    "        raise TypeError(\"can't serialize %s\" % self.__class__.__name__)",
    "",
    "",
    "",
    "def open(filename, mode='r', encoding=None, errors='strict', buffering=-1):",
    "",
    "    \"\"\"Open an encoded file using the given mode and return",
    "a wrapped version providing transparent encoding/decoding.",
    "",
    "Note: The wrapped version will only accept the object format",
    "defined by the codecs, i.e. Unicode objects for most builtin",
    "codecs. Output is also codec dependent and will usually be",
    "Unicode as well.",
    "",
    "If encoding is not None, then the",
    "underlying encoded files are always opened in binary mode.",
    "The default file mode is 'r', meaning to open the file in read mode.",
    "",
    "encoding specifies the encoding which is to be used for the",
    "file.",
    "",
    "errors may be given to define the error handling. It defaults",
    "to 'strict' which causes ValueErrors to be raised in case an",
    "encoding error occurs.",
    "",
    "buffering has the same meaning as for the builtin open() API.",
    "It defaults to -1 which means that the default buffer size will",
    "be used.",
    "",
    "The returned wrapped file object provides an extra attribute",
    ".encoding which allows querying the used encoding. This",
    "attribute is only available if an encoding was specified as",
    "parameter.",
    "\"\"\"",
    "    import warnings",
    "    warnings.warn(\"codecs.open() is deprecated. Use open() instead.\",",
    "                  DeprecationWarning, stacklevel=2)",
    "",
    "    if encoding is not None and \\",
    "       'b' not in mode:",
    "        # Force opening of the file in binary mode",
    "        mode = mode + 'b'",
    "    file = builtins.open(filename, mode, buffering)",
    "    if encoding is None:",
    "        return file",
    "",
    "    try:",
    "        info = lookup(encoding)",
    "        srw = StreamReaderWriter(file, info.streamreader, info.streamwriter, errors)",
    "        # Add attributes to simplify introspection",
    "        srw.encoding = encoding",
    "        return srw",
    "    except:",
    "        file.close()",
    "        raise",
    "def EncodedFile(file, data_encoding, file_encoding=None, errors='strict'):",
    "",
    "    \"\"\" Return a wrapped version of file which provides transparent",
    "        encoding translation.",
    "",
    "        Data written to the wrapped file is decoded according",
    "        to the given data_encoding and then encoded to the underlying",
    "        file using file_encoding. The intermediate data type",
    "        will usually be Unicode but depends on the specified codecs.",
    "",
    "        Bytes read from the file are decoded using file_encoding and then",
    "        passed back to the caller encoded using data_encoding.",
    "",
    "        If file_encoding is not given, it defaults to data_encoding.",
    "",
    "        errors may be given to define the error handling. It defaults",
    "        to 'strict' which causes ValueErrors to be raised in case an",
    "        encoding error occurs.",
    "",
    "        The returned wrapped file object provides two extra attributes",
    "        .data_encoding and .file_encoding which reflect the given",
    "        parameters of the same name. The attributes can be used for",
    "        introspection by Python programs.",
    "",
    "    \"\"\"",
    "    if file_encoding is None:",
    "        file_encoding = data_encoding",
    "    data_info = lookup(data_encoding)",
    "    file_info = lookup(file_encoding)",
    "    sr = StreamRecoder(file, data_info.encode, data_info.decode,",
    "                       file_info.streamreader, file_info.streamwriter, errors)",
    "    # Add attributes to simplify introspection",
    "    sr.data_encoding = data_encoding",
    "    sr.file_encoding = file_encoding",
    "    return sr",
    "",
    "",
    "",
    "def getencoder(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its encoder function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found.",
    "",
    "    \"\"\"",
    "    return lookup(encoding).encode",
    "",
    "def getdecoder(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its decoder function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found.",
    "",
    "    \"\"\"",
    "    return lookup(encoding).decode",
    "",
    "def getincrementalencoder(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its IncrementalEncoder class or factory function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found",
    "        or the codecs doesn't provide an incremental encoder.",
    "",
    "    \"\"\"",
    "    encoder = lookup(encoding).incrementalencoder",
    "    if encoder is None:",
    "        raise LookupError(encoding)",
    "    return encoder",
    "",
    "def getincrementaldecoder(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its IncrementalDecoder class or factory function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found",
    "        or the codecs doesn't provide an incremental decoder.",
    "",
    "    \"\"\"",
    "    decoder = lookup(encoding).incrementaldecoder",
    "    if decoder is None:",
    "        raise LookupError(encoding)",
    "    return decoder",
    "",
    "def getreader(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its StreamReader class or factory function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found.",
    "",
    "    \"\"\"",
    "    return lookup(encoding).streamreader",
    "",
    "def getwriter(encoding):",
    "",
    "    \"\"\" Lookup up the codec for the given encoding and return",
    "        its StreamWriter class or factory function.",
    "",
    "        Raises a LookupError in case the encoding cannot be found.",
    "",
    "    \"\"\"",
    "    return lookup(encoding).streamwriter",
    "",
    "def iterencode(iterator, encoding, errors='strict', **kwargs):",
    "    \"\"\"",
    "    Encoding iterator.",
    "",
    "    Encodes the input strings from the iterator using an IncrementalEncoder.",
    "",
    "    errors and kwargs are passed through to the IncrementalEncoder",
    "    constructor.",
    "    \"\"\"",
    "    encoder = getincrementalencoder(encoding)(errors, **kwargs)",
    "    for input in iterator:",
    "        output = encoder.encode(input)",
    "        if output:",
    "            yield output",
    "    output = encoder.encode(\"\", True)",
    "    if output:",
    "        yield output",
    "",
    "def iterdecode(iterator, encoding, errors='strict', **kwargs):",
    "    \"\"\"",
    "    Decoding iterator.",
    "",
    "    Decodes the input strings from the iterator using an IncrementalDecoder.",
    "",
    "    errors and kwargs are passed through to the IncrementalDecoder",
    "    constructor.",
    "    \"\"\"",
    "    decoder = getincrementaldecoder(encoding)(errors, **kwargs)",
    "    for input in iterator:",
    "        output = decoder.decode(input)",
    "        if output:",
    "            yield output",
    "    output = decoder.decode(b\"\", True)",
    "    if output:",
    "        yield output",
    "",
    "### Helpers for charmap-based codecs",
    "",
    "def make_identity_dict(rng):",
    "",
    "    \"\"\" make_identity_dict(rng) -> dict",
    "",
    "        Return a dictionary where elements of the rng sequence are",
    "        mapped to themselves.",
    "",
    "    \"\"\"",
    "    return {i:i for i in rng}",
    "",
    "def make_encoding_map(decoding_map):",
    "",
    "    \"\"\" Creates an encoding map from a decoding map.",
    "",
    "        If a target mapping in the decoding map occurs multiple",
    "        times, then that target is mapped to None (undefined mapping),",
    "        causing an exception when encountered by the charmap codec",
    "        during translation.",
    "",
    "        One example where this happens is cp875.py which decodes",
    "        multiple character to \\\\u001a.",
    "",
    "    \"\"\"",
    "    m = {}",
    "    for k,v in decoding_map.items():",
    "        if not v in m:",
    "            m[v] = k",
    "        else:",
    "            m[v] = None",
    "    return m",
    "",
    "",
    "",
    "strict_errors = lookup_error(\"strict\")",
    "ignore_errors = lookup_error(\"ignore\")",
    "replace_errors = lookup_error(\"replace\")",
    "xmlcharrefreplace_errors = lookup_error(\"xmlcharrefreplace\")",
    "backslashreplace_errors = lookup_error(\"backslashreplace\")",
    "namereplace_errors = lookup_error(\"namereplace\")",
    "",
  ].join("\n")],
  ["encodings", [
    "\"\"\" Standard \"encodings\" Package",
    "",
    "    Standard Python encoding modules are stored in this package",
    "    directory.",
    "",
    "    Codec modules must have names corresponding to normalized encoding",
    "    names as defined in the normalize_encoding() function below, e.g.",
    "    'utf-8' must be implemented by the module 'utf_8.py'.",
    "",
    "    Each codec module must export the following interface:",
    "",
    "    * getregentry() -> codecs.CodecInfo object",
    "    The getregentry() API must return a CodecInfo object with encoder, decoder,",
    "    incrementalencoder, incrementaldecoder, streamwriter and streamreader",
    "    attributes which adhere to the Python Codec Interface Standard.",
    "",
    "    In addition, a module may optionally also define the following",
    "    APIs which are then used by the package's codec search function:",
    "",
    "    * getaliases() -> sequence of encoding name strings to use as aliases",
    "",
    "    Alias names returned by getaliases() must be normalized encoding",
    "    names as defined by normalize_encoding().",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"#\"",
    "",
    "import codecs",
    "",
    "from . import aliases",
    "",
    "_cache = {}",
    "_MAXCACHE = 500",
    "_unknown = '--unknown--'",
    "_import_tail = ['*']",
    "_aliases = aliases.aliases",
    "",
    "class CodecRegistryError(LookupError, SystemError):",
    "    pass",
    "",
    "def normalize_encoding(encoding):",
    "",
    "    \"\"\" Normalize an encoding name.",
    "",
    "        Normalization works as follows: all non-alphanumeric",
    "        characters except the dot used for Python package names are",
    "        collapsed and replaced with a single underscore, e.g. '  -;#'",
    "        becomes '_'. Leading and trailing underscores are removed.",
    "",
    "        Note that encoding names should be ASCII only.",
    "",
    "    \"\"\"",
    "    if isinstance(encoding, bytes):",
    "        encoding = str(encoding, \"ascii\")",
    "",
    "    chars = []",
    "    punct = False",
    "    for c in encoding:",
    "        if c.isalnum() or c == '.':",
    "            if punct and chars:",
    "                chars.append('_')",
    "            if c.isascii():",
    "                chars.append(c)",
    "            punct = False",
    "        else:",
    "            punct = True",
    "    return ''.join(chars)",
    "",
    "def search_function(encoding):",
    "",
    "    # Cache lookup",
    "    entry = _cache.get(encoding, _unknown)",
    "    if entry is not _unknown:",
    "        return entry",
    "",
    "    # Import the module:",
    "    #",
    "    # First try to find an alias for the normalized encoding",
    "    # name and lookup the module using the aliased name, then try to",
    "    # lookup the module using the standard import scheme, i.e. first",
    "    # try in the encodings package, then at top-level.",
    "    #",
    "    norm_encoding = normalize_encoding(encoding)",
    "    aliased_encoding = _aliases.get(norm_encoding) or \\",
    "                       _aliases.get(norm_encoding.replace('.', '_'))",
    "    if aliased_encoding is not None:",
    "        modnames = [aliased_encoding,",
    "                    norm_encoding]",
    "    else:",
    "        modnames = [norm_encoding]",
    "    for modname in modnames:",
    "        if not modname or '.' in modname:",
    "            continue",
    "        try:",
    "            # Import is absolute to prevent the possibly malicious import of a",
    "            # module with side-effects that is not in the 'encodings' package.",
    "            mod = __import__('encodings.' + modname, fromlist=_import_tail,",
    "                             level=0)",
    "        except ImportError:",
    "            # ImportError may occur because 'encodings.(modname)' does not exist,",
    "            # or because it imports a name that does not exist (see mbcs and oem)",
    "            pass",
    "        else:",
    "            break",
    "    else:",
    "        mod = None",
    "",
    "    try:",
    "        getregentry = mod.getregentry",
    "    except AttributeError:",
    "        # Not a codec module",
    "        mod = None",
    "",
    "    if mod is None:",
    "        # Cache misses",
    "        if len(_cache) >= _MAXCACHE:",
    "            _cache.clear()",
    "        _cache[encoding] = None",
    "        return None",
    "",
    "    # Now ask the module for the registry entry",
    "    entry = getregentry()",
    "    if not isinstance(entry, codecs.CodecInfo):",
    "        if not 4 <= len(entry) <= 7:",
    "            raise CodecRegistryError('module \"%s\" (%s) failed to register'",
    "                                     % (mod.__name__, mod.__file__))",
    "        if not callable(entry[0]) or not callable(entry[1]) or \\",
    "           (entry[2] is not None and not callable(entry[2])) or \\",
    "           (entry[3] is not None and not callable(entry[3])) or \\",
    "           (len(entry) > 4 and entry[4] is not None and not callable(entry[4])) or \\",
    "           (len(entry) > 5 and entry[5] is not None and not callable(entry[5])):",
    "            raise CodecRegistryError('incompatible codecs in module \"%s\" (%s)'",
    "                                     % (mod.__name__, mod.__file__))",
    "        if len(entry)<7 or entry[6] is None:",
    "            entry += (None,)*(6-len(entry)) + (mod.__name__.split(\".\", 1)[1],)",
    "        entry = codecs.CodecInfo(*entry)",
    "",
    "    # Cache the codec registry entry",
    "    if len(_cache) >= _MAXCACHE:",
    "        _cache.clear()",
    "    _cache[encoding] = entry",
    "",
    "    # Register its aliases (without overwriting previously registered",
    "    # aliases)",
    "    try:",
    "        codecaliases = mod.getaliases()",
    "    except AttributeError:",
    "        pass",
    "    else:",
    "        for alias in codecaliases:",
    "            if alias not in _aliases:",
    "                _aliases[alias] = modname",
    "",
    "    # Return the registry entry",
    "    return entry",
    "",
    "# Register the search_function in the Python codec registry",
    "codecs.register(search_function)",
    "",
    ""
  ].join("\n")],
  ["encodings.aliases", [
    "\"\"\" Encoding Aliases Support",
    "",
    "    This module is used by the encodings package search function to",
    "    map encodings names to module names.",
    "",
    "    Note that the search function normalizes the encoding names before",
    "    doing the lookup, so the mapping will have to map normalized",
    "    encoding names to module names.",
    "",
    "    Contents:",
    "",
    "        The following aliases dictionary contains mappings of all IANA",
    "        character set names for which the Python core library provides",
    "        codecs. In addition to these, a few Python specific codec",
    "        aliases have also been added.",
    "",
    "\"\"\"",
    "aliases = {",
    "",
    "    # Please keep this list sorted alphabetically by value !",
    "",
    "    # ascii codec",
    "    '646'                : 'ascii',",
    "    'ansi_x3.4_1968'     : 'ascii',",
    "    'ansi_x3_4_1968'     : 'ascii', # some email headers use this non-standard name",
    "    'ansi_x3.4_1986'     : 'ascii',",
    "    'cp367'              : 'ascii',",
    "    'csascii'            : 'ascii',",
    "    'ibm367'             : 'ascii',",
    "    'iso646_us'          : 'ascii',",
    "    'iso_646.irv_1991'   : 'ascii',",
    "    'iso_ir_6'           : 'ascii',",
    "    'us'                 : 'ascii',",
    "    'us_ascii'           : 'ascii',",
    "",
    "    # base64_codec codec",
    "    'base64'             : 'base64_codec',",
    "    'base_64'            : 'base64_codec',",
    "",
    "    # big5 codec",
    "    'big5_tw'            : 'big5',",
    "    'csbig5'             : 'big5',",
    "",
    "    # big5hkscs codec",
    "    'big5_hkscs'         : 'big5hkscs',",
    "    'hkscs'              : 'big5hkscs',",
    "",
    "    # bz2_codec codec",
    "    'bz2'                : 'bz2_codec',",
    "",
    "    # cp037 codec",
    "    '037'                : 'cp037',",
    "    'csibm037'           : 'cp037',",
    "    'ebcdic_cp_ca'       : 'cp037',",
    "    'ebcdic_cp_nl'       : 'cp037',",
    "    'ebcdic_cp_us'       : 'cp037',",
    "    'ebcdic_cp_wt'       : 'cp037',",
    "    'ibm037'             : 'cp037',",
    "    'ibm039'             : 'cp037',",
    "",
    "    # cp1026 codec",
    "    '1026'               : 'cp1026',",
    "    'csibm1026'          : 'cp1026',",
    "    'ibm1026'            : 'cp1026',",
    "",
    "    # cp1125 codec",
    "    '1125'                : 'cp1125',",
    "    'ibm1125'             : 'cp1125',",
    "    'cp866u'              : 'cp1125',",
    "    'ruscii'              : 'cp1125',",
    "",
    "    # cp1140 codec",
    "    '1140'               : 'cp1140',",
    "    'cp01140'            : 'cp1140',",
    "    'csibm01140'         : 'cp1140',",
    "    'ebcdic_us_37_euro'  : 'cp1140',",
    "    'ibm01140'           : 'cp1140',",
    "    'ibm1140'            : 'cp1140',",
    "",
    "    # cp1250 codec",
    "    '1250'               : 'cp1250',",
    "    'windows_1250'       : 'cp1250',",
    "",
    "    # cp1251 codec",
    "    '1251'               : 'cp1251',",
    "    'windows_1251'       : 'cp1251',",
    "",
    "    # cp1252 codec",
    "    '1252'               : 'cp1252',",
    "    'windows_1252'       : 'cp1252',",
    "",
    "    # cp1253 codec",
    "    '1253'               : 'cp1253',",
    "    'windows_1253'       : 'cp1253',",
    "",
    "    # cp1254 codec",
    "    '1254'               : 'cp1254',",
    "    'windows_1254'       : 'cp1254',",
    "",
    "    # cp1255 codec",
    "    '1255'               : 'cp1255',",
    "    'windows_1255'       : 'cp1255',",
    "",
    "    # cp1256 codec",
    "    '1256'               : 'cp1256',",
    "    'windows_1256'       : 'cp1256',",
    "",
    "    # cp1257 codec",
    "    '1257'               : 'cp1257',",
    "    'windows_1257'       : 'cp1257',",
    "",
    "    # cp1258 codec",
    "    '1258'               : 'cp1258',",
    "    'windows_1258'       : 'cp1258',",
    "",
    "    # cp273 codec",
    "    '273'                : 'cp273',",
    "    'ibm273'             : 'cp273',",
    "    'csibm273'           : 'cp273',",
    "",
    "    # cp424 codec",
    "    '424'                : 'cp424',",
    "    'csibm424'           : 'cp424',",
    "    'ebcdic_cp_he'       : 'cp424',",
    "    'ibm424'             : 'cp424',",
    "",
    "    # cp437 codec",
    "    '437'                : 'cp437',",
    "    'cspc8codepage437'   : 'cp437',",
    "    'ibm437'             : 'cp437',",
    "",
    "    # cp500 codec",
    "    '500'                : 'cp500',",
    "    'csibm500'           : 'cp500',",
    "    'ebcdic_cp_be'       : 'cp500',",
    "    'ebcdic_cp_ch'       : 'cp500',",
    "    'ibm500'             : 'cp500',",
    "",
    "    # cp775 codec",
    "    '775'                : 'cp775',",
    "    'cspc775baltic'      : 'cp775',",
    "    'ibm775'             : 'cp775',",
    "",
    "    # cp850 codec",
    "    '850'                : 'cp850',",
    "    'cspc850multilingual' : 'cp850',",
    "    'ibm850'             : 'cp850',",
    "",
    "    # cp852 codec",
    "    '852'                : 'cp852',",
    "    'cspcp852'           : 'cp852',",
    "    'ibm852'             : 'cp852',",
    "",
    "    # cp855 codec",
    "    '855'                : 'cp855',",
    "    'csibm855'           : 'cp855',",
    "    'ibm855'             : 'cp855',",
    "",
    "    # cp857 codec",
    "    '857'                : 'cp857',",
    "    'csibm857'           : 'cp857',",
    "    'ibm857'             : 'cp857',",
    "",
    "    # cp858 codec",
    "    '858'                : 'cp858',",
    "    'cp00858'            : 'cp858',",
    "    'csibm00858'         : 'cp858',",
    "    'csibm858'           : 'cp858',",
    "    'ibm00858'           : 'cp858',",
    "    'ibm858'             : 'cp858',",
    "    'pc_multilingual_850_euro' : 'cp858',",
    "",
    "    # cp860 codec",
    "    '860'                : 'cp860',",
    "    'csibm860'           : 'cp860',",
    "    'ibm860'             : 'cp860',",
    "",
    "    # cp861 codec",
    "    '861'                : 'cp861',",
    "    'cp_is'              : 'cp861',",
    "    'csibm861'           : 'cp861',",
    "    'ibm861'             : 'cp861',",
    "",
    "    # cp862 codec",
    "    '862'                : 'cp862',",
    "    'cspc862latinhebrew' : 'cp862',",
    "    'ibm862'             : 'cp862',",
    "",
    "    # cp863 codec",
    "    '863'                : 'cp863',",
    "    'csibm863'           : 'cp863',",
    "    'ibm863'             : 'cp863',",
    "",
    "    # cp864 codec",
    "    '864'                : 'cp864',",
    "    'csibm864'           : 'cp864',",
    "    'ibm864'             : 'cp864',",
    "",
    "    # cp865 codec",
    "    '865'                : 'cp865',",
    "    'csibm865'           : 'cp865',",
    "    'ibm865'             : 'cp865',",
    "",
    "    # cp866 codec",
    "    '866'                : 'cp866',",
    "    'csibm866'           : 'cp866',",
    "    'ibm866'             : 'cp866',",
    "",
    "    # cp869 codec",
    "    '869'                : 'cp869',",
    "    'cp_gr'              : 'cp869',",
    "    'csibm869'           : 'cp869',",
    "    'ibm869'             : 'cp869',",
    "",
    "    # cp874 codec",
    "    '874'                : 'cp874',",
    "    'ms874'              : 'cp874',",
    "    'windows_874'        : 'cp874',",
    "",
    "    # cp932 codec",
    "    '932'                : 'cp932',",
    "    'ms932'              : 'cp932',",
    "    'mskanji'            : 'cp932',",
    "    'ms_kanji'           : 'cp932',",
    "    'windows_31j'        : 'cp932',",
    "",
    "    # cp949 codec",
    "    '949'                : 'cp949',",
    "    'ms949'              : 'cp949',",
    "    'uhc'                : 'cp949',",
    "",
    "    # cp950 codec",
    "    '950'                : 'cp950',",
    "    'ms950'              : 'cp950',",
    "",
    "    # euc_jis_2004 codec",
    "    'jisx0213'           : 'euc_jis_2004',",
    "    'eucjis2004'         : 'euc_jis_2004',",
    "    'euc_jis2004'        : 'euc_jis_2004',",
    "",
    "    # euc_jisx0213 codec",
    "    'eucjisx0213'        : 'euc_jisx0213',",
    "",
    "    # euc_jp codec",
    "    'eucjp'              : 'euc_jp',",
    "    'ujis'               : 'euc_jp',",
    "    'u_jis'              : 'euc_jp',",
    "",
    "    # euc_kr codec",
    "    'euckr'              : 'euc_kr',",
    "    'korean'             : 'euc_kr',",
    "    'ksc5601'            : 'euc_kr',",
    "    'ks_c_5601'          : 'euc_kr',",
    "    'ks_c_5601_1987'     : 'euc_kr',",
    "    'ksx1001'            : 'euc_kr',",
    "    'ks_x_1001'          : 'euc_kr',",
    "    'cseuckr'            : 'euc_kr',",
    "",
    "    # gb18030 codec",
    "    'gb18030_2000'       : 'gb18030',",
    "",
    "    # gb2312 codec",
    "    'chinese'            : 'gb2312',",
    "    'csiso58gb231280'    : 'gb2312',",
    "    'euc_cn'             : 'gb2312',",
    "    'euccn'              : 'gb2312',",
    "    'eucgb2312_cn'       : 'gb2312',",
    "    'gb2312_1980'        : 'gb2312',",
    "    'gb2312_80'          : 'gb2312',",
    "    'iso_ir_58'          : 'gb2312',",
    "",
    "    # gbk codec",
    "    '936'                : 'gbk',",
    "    'cp936'              : 'gbk',",
    "    'ms936'              : 'gbk',",
    "",
    "    # hex_codec codec",
    "    'hex'                : 'hex_codec',",
    "",
    "    # hp_roman8 codec",
    "    'roman8'             : 'hp_roman8',",
    "    'r8'                 : 'hp_roman8',",
    "    'csHPRoman8'         : 'hp_roman8',",
    "    'cp1051'             : 'hp_roman8',",
    "    'ibm1051'            : 'hp_roman8',",
    "",
    "    # hz codec",
    "    'hzgb'               : 'hz',",
    "    'hz_gb'              : 'hz',",
    "    'hz_gb_2312'         : 'hz',",
    "",
    "    # iso2022_jp codec",
    "    'csiso2022jp'        : 'iso2022_jp',",
    "    'iso2022jp'          : 'iso2022_jp',",
    "    'iso_2022_jp'        : 'iso2022_jp',",
    "",
    "    # iso2022_jp_1 codec",
    "    'iso2022jp_1'        : 'iso2022_jp_1',",
    "    'iso_2022_jp_1'      : 'iso2022_jp_1',",
    "",
    "    # iso2022_jp_2 codec",
    "    'iso2022jp_2'        : 'iso2022_jp_2',",
    "    'iso_2022_jp_2'      : 'iso2022_jp_2',",
    "",
    "    # iso2022_jp_2004 codec",
    "    'iso_2022_jp_2004'   : 'iso2022_jp_2004',",
    "    'iso2022jp_2004'     : 'iso2022_jp_2004',",
    "",
    "    # iso2022_jp_3 codec",
    "    'iso2022jp_3'        : 'iso2022_jp_3',",
    "    'iso_2022_jp_3'      : 'iso2022_jp_3',",
    "",
    "    # iso2022_jp_ext codec",
    "    'iso2022jp_ext'      : 'iso2022_jp_ext',",
    "    'iso_2022_jp_ext'    : 'iso2022_jp_ext',",
    "",
    "    # iso2022_kr codec",
    "    'csiso2022kr'        : 'iso2022_kr',",
    "    'iso2022kr'          : 'iso2022_kr',",
    "    'iso_2022_kr'        : 'iso2022_kr',",
    "",
    "    # iso8859_10 codec",
    "    'csisolatin6'        : 'iso8859_10',",
    "    'iso_8859_10'        : 'iso8859_10',",
    "    'iso_8859_10_1992'   : 'iso8859_10',",
    "    'iso_ir_157'         : 'iso8859_10',",
    "    'l6'                 : 'iso8859_10',",
    "    'latin6'             : 'iso8859_10',",
    "",
    "    # iso8859_11 codec",
    "    'thai'               : 'iso8859_11',",
    "    'iso_8859_11'        : 'iso8859_11',",
    "    'iso_8859_11_2001'   : 'iso8859_11',",
    "",
    "    # iso8859_13 codec",
    "    'iso_8859_13'        : 'iso8859_13',",
    "    'l7'                 : 'iso8859_13',",
    "    'latin7'             : 'iso8859_13',",
    "",
    "    # iso8859_14 codec",
    "    'iso_8859_14'        : 'iso8859_14',",
    "    'iso_8859_14_1998'   : 'iso8859_14',",
    "    'iso_celtic'         : 'iso8859_14',",
    "    'iso_ir_199'         : 'iso8859_14',",
    "    'l8'                 : 'iso8859_14',",
    "    'latin8'             : 'iso8859_14',",
    "",
    "    # iso8859_15 codec",
    "    'iso_8859_15'        : 'iso8859_15',",
    "    'l9'                 : 'iso8859_15',",
    "    'latin9'             : 'iso8859_15',",
    "",
    "    # iso8859_16 codec",
    "    'iso_8859_16'        : 'iso8859_16',",
    "    'iso_8859_16_2001'   : 'iso8859_16',",
    "    'iso_ir_226'         : 'iso8859_16',",
    "    'l10'                : 'iso8859_16',",
    "    'latin10'            : 'iso8859_16',",
    "",
    "    # iso8859_2 codec",
    "    'csisolatin2'        : 'iso8859_2',",
    "    'iso_8859_2'         : 'iso8859_2',",
    "    'iso_8859_2_1987'    : 'iso8859_2',",
    "    'iso_ir_101'         : 'iso8859_2',",
    "    'l2'                 : 'iso8859_2',",
    "    'latin2'             : 'iso8859_2',",
    "",
    "    # iso8859_3 codec",
    "    'csisolatin3'        : 'iso8859_3',",
    "    'iso_8859_3'         : 'iso8859_3',",
    "    'iso_8859_3_1988'    : 'iso8859_3',",
    "    'iso_ir_109'         : 'iso8859_3',",
    "    'l3'                 : 'iso8859_3',",
    "    'latin3'             : 'iso8859_3',",
    "",
    "    # iso8859_4 codec",
    "    'csisolatin4'        : 'iso8859_4',",
    "    'iso_8859_4'         : 'iso8859_4',",
    "    'iso_8859_4_1988'    : 'iso8859_4',",
    "    'iso_ir_110'         : 'iso8859_4',",
    "    'l4'                 : 'iso8859_4',",
    "    'latin4'             : 'iso8859_4',",
    "",
    "    # iso8859_5 codec",
    "    'csisolatincyrillic' : 'iso8859_5',",
    "    'cyrillic'           : 'iso8859_5',",
    "    'iso_8859_5'         : 'iso8859_5',",
    "    'iso_8859_5_1988'    : 'iso8859_5',",
    "    'iso_ir_144'         : 'iso8859_5',",
    "",
    "    # iso8859_6 codec",
    "    'arabic'             : 'iso8859_6',",
    "    'asmo_708'           : 'iso8859_6',",
    "    'csisolatinarabic'   : 'iso8859_6',",
    "    'ecma_114'           : 'iso8859_6',",
    "    'iso_8859_6'         : 'iso8859_6',",
    "    'iso_8859_6_1987'    : 'iso8859_6',",
    "    'iso_ir_127'         : 'iso8859_6',",
    "",
    "    # iso8859_7 codec",
    "    'csisolatingreek'    : 'iso8859_7',",
    "    'ecma_118'           : 'iso8859_7',",
    "    'elot_928'           : 'iso8859_7',",
    "    'greek'              : 'iso8859_7',",
    "    'greek8'             : 'iso8859_7',",
    "    'iso_8859_7'         : 'iso8859_7',",
    "    'iso_8859_7_1987'    : 'iso8859_7',",
    "    'iso_ir_126'         : 'iso8859_7',",
    "",
    "    # iso8859_8 codec",
    "    'csisolatinhebrew'   : 'iso8859_8',",
    "    'hebrew'             : 'iso8859_8',",
    "    'iso_8859_8'         : 'iso8859_8',",
    "    'iso_8859_8_1988'    : 'iso8859_8',",
    "    'iso_ir_138'         : 'iso8859_8',",
    "    'iso_8859_8_i'       : 'iso8859_8',",
    "    'iso_8859_8_e'       : 'iso8859_8',",
    "",
    "    # iso8859_9 codec",
    "    'csisolatin5'        : 'iso8859_9',",
    "    'iso_8859_9'         : 'iso8859_9',",
    "    'iso_8859_9_1989'    : 'iso8859_9',",
    "    'iso_ir_148'         : 'iso8859_9',",
    "    'l5'                 : 'iso8859_9',",
    "    'latin5'             : 'iso8859_9',",
    "",
    "    # johab codec",
    "    'cp1361'             : 'johab',",
    "    'ms1361'             : 'johab',",
    "",
    "    # koi8_r codec",
    "    'cskoi8r'            : 'koi8_r',",
    "",
    "    # kz1048 codec",
    "    'kz_1048'           : 'kz1048',",
    "    'rk1048'            : 'kz1048',",
    "    'strk1048_2002'     : 'kz1048',",
    "",
    "    # latin_1 codec",
    "    #",
    "    # Note that the latin_1 codec is implemented internally in C and a",
    "    # lot faster than the charmap codec iso8859_1 which uses the same",
    "    # encoding. This is why we discourage the use of the iso8859_1",
    "    # codec and alias it to latin_1 instead.",
    "    #",
    "    '8859'               : 'latin_1',",
    "    'cp819'              : 'latin_1',",
    "    'csisolatin1'        : 'latin_1',",
    "    'ibm819'             : 'latin_1',",
    "    'iso8859'            : 'latin_1',",
    "    'iso8859_1'          : 'latin_1',",
    "    'iso_8859_1'         : 'latin_1',",
    "    'iso_8859_1_1987'    : 'latin_1',",
    "    'iso_ir_100'         : 'latin_1',",
    "    'l1'                 : 'latin_1',",
    "    'latin'              : 'latin_1',",
    "    'latin1'             : 'latin_1',",
    "",
    "    # mac_cyrillic codec",
    "    'maccyrillic'        : 'mac_cyrillic',",
    "",
    "    # mac_greek codec",
    "    'macgreek'           : 'mac_greek',",
    "",
    "    # mac_iceland codec",
    "    'maciceland'         : 'mac_iceland',",
    "",
    "    # mac_latin2 codec",
    "    'maccentraleurope'   : 'mac_latin2',",
    "    'mac_centeuro'       : 'mac_latin2',",
    "    'maclatin2'          : 'mac_latin2',",
    "",
    "    # mac_roman codec",
    "    'macintosh'          : 'mac_roman',",
    "    'macroman'           : 'mac_roman',",
    "",
    "    # mac_turkish codec",
    "    'macturkish'         : 'mac_turkish',",
    "",
    "    # mbcs codec",
    "    'ansi'               : 'mbcs',",
    "    'dbcs'               : 'mbcs',",
    "",
    "    # ptcp154 codec",
    "    'csptcp154'          : 'ptcp154',",
    "    'pt154'              : 'ptcp154',",
    "    'cp154'              : 'ptcp154',",
    "    'cyrillic_asian'     : 'ptcp154',",
    "",
    "    # quopri_codec codec",
    "    'quopri'             : 'quopri_codec',",
    "    'quoted_printable'   : 'quopri_codec',",
    "    'quotedprintable'    : 'quopri_codec',",
    "",
    "    # rot_13 codec",
    "    'rot13'              : 'rot_13',",
    "",
    "    # shift_jis codec",
    "    'csshiftjis'         : 'shift_jis',",
    "    'shiftjis'           : 'shift_jis',",
    "    'sjis'               : 'shift_jis',",
    "    's_jis'              : 'shift_jis',",
    "",
    "    # shift_jis_2004 codec",
    "    'shiftjis2004'       : 'shift_jis_2004',",
    "    'sjis_2004'          : 'shift_jis_2004',",
    "    's_jis_2004'         : 'shift_jis_2004',",
    "",
    "    # shift_jisx0213 codec",
    "    'shiftjisx0213'      : 'shift_jisx0213',",
    "    'sjisx0213'          : 'shift_jisx0213',",
    "    's_jisx0213'         : 'shift_jisx0213',",
    "",
    "    # tis_620 codec",
    "    'tis620'             : 'tis_620',",
    "    'tis_620_0'          : 'tis_620',",
    "    'tis_620_2529_0'     : 'tis_620',",
    "    'tis_620_2529_1'     : 'tis_620',",
    "    'iso_ir_166'         : 'tis_620',",
    "",
    "    # utf_16 codec",
    "    'u16'                : 'utf_16',",
    "    'utf16'              : 'utf_16',",
    "",
    "    # utf_16_be codec",
    "    'unicodebigunmarked' : 'utf_16_be',",
    "    'utf_16be'           : 'utf_16_be',",
    "",
    "    # utf_16_le codec",
    "    'unicodelittleunmarked' : 'utf_16_le',",
    "    'utf_16le'           : 'utf_16_le',",
    "",
    "    # utf_32 codec",
    "    'u32'                : 'utf_32',",
    "    'utf32'              : 'utf_32',",
    "",
    "    # utf_32_be codec",
    "    'utf_32be'           : 'utf_32_be',",
    "",
    "    # utf_32_le codec",
    "    'utf_32le'           : 'utf_32_le',",
    "",
    "    # utf_7 codec",
    "    'u7'                 : 'utf_7',",
    "    'utf7'               : 'utf_7',",
    "    'unicode_1_1_utf_7'  : 'utf_7',",
    "",
    "    # utf_8 codec",
    "    'u8'                 : 'utf_8',",
    "    'utf'                : 'utf_8',",
    "    'utf8'               : 'utf_8',",
    "    'utf8_ucs2'          : 'utf_8',",
    "    'utf8_ucs4'          : 'utf_8',",
    "    'cp65001'            : 'utf_8',",
    "",
    "    # uu_codec codec",
    "    'uu'                 : 'uu_codec',",
    "",
    "    # zlib_codec codec",
    "    'zip'                : 'zlib_codec',",
    "    'zlib'               : 'zlib_codec',",
    "",
    "    # temporary mac CJK aliases, will be replaced by proper codecs in 3.1",
    "    'x_mac_japanese'      : 'shift_jis',",
    "    'x_mac_korean'        : 'euc_kr',",
    "    'x_mac_simp_chinese'  : 'gb2312',",
    "    'x_mac_trad_chinese'  : 'big5',",
    "}",
    ""
  ].join("\n")],
  ["encodings.ascii", [
    "\"\"\" Python 'ascii' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "class Codec(codecs.Codec):",
    "",
    "    # Note: Binding these as C functions will result in the class not",
    "    # converting them to methods. This is intended.",
    "    encode = codecs.ascii_encode",
    "    decode = codecs.ascii_decode",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.ascii_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.IncrementalDecoder):",
    "    def decode(self, input, final=False):",
    "        return codecs.ascii_decode(input, self.errors)[0]",
    "",
    "class StreamWriter(Codec,codecs.StreamWriter):",
    "    pass",
    "",
    "class StreamReader(Codec,codecs.StreamReader):",
    "    pass",
    "",
    "class StreamConverter(StreamWriter,StreamReader):",
    "",
    "    encode = codecs.ascii_decode",
    "    decode = codecs.ascii_encode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='ascii',",
    "        encode=Codec.encode,",
    "        decode=Codec.decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamwriter=StreamWriter,",
    "        streamreader=StreamReader,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.latin_1", [
    "\"\"\" Python 'latin-1' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "class Codec(codecs.Codec):",
    "",
    "    # Note: Binding these as C functions will result in the class not",
    "    # converting them to methods. This is intended.",
    "    encode = codecs.latin_1_encode",
    "    decode = codecs.latin_1_decode",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.latin_1_encode(input,self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.IncrementalDecoder):",
    "    def decode(self, input, final=False):",
    "        return codecs.latin_1_decode(input,self.errors)[0]",
    "",
    "class StreamWriter(Codec,codecs.StreamWriter):",
    "    pass",
    "",
    "class StreamReader(Codec,codecs.StreamReader):",
    "    pass",
    "",
    "class StreamConverter(StreamWriter,StreamReader):",
    "",
    "    encode = codecs.latin_1_decode",
    "    decode = codecs.latin_1_encode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='iso8859-1',",
    "        encode=Codec.encode,",
    "        decode=Codec.decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_8", [
    "\"\"\" Python 'utf-8' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_8_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_8_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_8_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_8_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_8_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_8_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-8',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
]);
