/** Verbatim CPython 3.14.7 platform codec sources.
 * Copyright Python Software Foundation; see CPYTHON-LICENSE.txt.
 * Source SHA-256:
 * mbcs.py f6ed445ed537c9f856d8defe8b56505727737d0dc9348d0a877abedab4bdd864
 * oem.py 481656d3a35f792d0e5109e3f821e6dbfcf097163a19b0cdfcbff3b3db99292f
 * _win_cp_codecs.py a10ef385d2096ff10a4ed00e7adfb7750fefcd10aa8eea1b573846145c9abad7
 */
export const platformCodecSources: ReadonlyMap<string, string> = new Map([
  ["encodings.mbcs", [
    "\"\"\" Python 'mbcs' Codec for Windows",
    "",
    "",
    "Cloned by Mark Hammond (mhammond@skippinet.com.au) from ascii.py,",
    "which was written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "# Import them explicitly to cause an ImportError",
    "# on non-Windows systems",
    "from codecs import mbcs_encode, mbcs_decode",
    "# for IncrementalDecoder, IncrementalEncoder, ...",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = mbcs_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return mbcs_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return mbcs_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = mbcs_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = mbcs_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = mbcs_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='mbcs',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    "",
  ].join("\n")],
  ["encodings.oem", [
    "\"\"\" Python 'oem' Codec for Windows",
    "",
    "\"\"\"",
    "# Import them explicitly to cause an ImportError",
    "# on non-Windows systems",
    "from codecs import oem_encode, oem_decode",
    "# for IncrementalDecoder, IncrementalEncoder, ...",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = oem_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return oem_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return oem_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = oem_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = oem_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = oem_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='oem',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    "",
  ].join("\n")],
  ["encodings._win_cp_codecs", [
    "import codecs",
    "",
    "def create_win32_code_page_codec(cp):",
    "    from codecs import code_page_encode, code_page_decode",
    "",
    "    def encode(input, errors='strict'):",
    "        return code_page_encode(cp, input, errors)",
    "",
    "    def decode(input, errors='strict'):",
    "        return code_page_decode(cp, input, errors, True)",
    "",
    "    class IncrementalEncoder(codecs.IncrementalEncoder):",
    "        def encode(self, input, final=False):",
    "            return code_page_encode(cp, input, self.errors)[0]",
    "",
    "    class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "        def _buffer_decode(self, input, errors, final):",
    "            return code_page_decode(cp, input, errors, final)",
    "",
    "    class StreamWriter(codecs.StreamWriter):",
    "        def encode(self, input, errors='strict'):",
    "            return code_page_encode(cp, input, errors)",
    "",
    "    class StreamReader(codecs.StreamReader):",
    "        def decode(self, input, errors, final):",
    "            return code_page_decode(cp, input, errors, final)",
    "",
    "    return codecs.CodecInfo(",
    "        name=f'cp{cp}',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    "",
  ].join("\n")],
]);
