/** Verbatim CPython 3.14.7 guest library sources.
 * Copyright Python Software Foundation; see CPYTHON-LICENSE.txt.
 * SHA-256 of each original UTF-8 source:
 * utf_32.py 6c235e377e1e277cde5f684cee6f6f8da4c73d153a21891df0cb834f17cd2b6f
 * utf_16.py 08437559c8d255a5ba1449c1c75beaa62b0834fe4259d161ecf8699381e4c8e1
 * utf_8_sig.py 1ef3da8d8aa08149e7f274dc64dbfce2155da812e5258ca8e8f832428d3b5c2d
 * utf_7.py 9ff32314f4f1fa074f206bbf7fdb851504e5313128636d73b4bf75b886e4a87d
 * utf_16_le.py 3aedaf3eb49769282daef1eaedfd4fa1c31fe5eebeff67fe2307c89dc2e2fd80
 * utf_16_be.py 3357196f3fa52433326a6626880e34964e00c5570aee50e9a0a0a7c6d86f6e4f
 * utf_32_le.py 9134b91047d85b442898d59effe23e7e0cf4167ca341ae31119a731dbf880a7b
 * utf_32_be.py cbba20e1f6d0879c7c4293446c371a9f79e7c90bf3c78a77a9b8fc72b18915dd
 * unicode_escape.py 507e7ca8f18df639fd823d7cc23ce4028a3550ceefdfa40b3c76f81d1a94531d
 * raw_unicode_escape.py fa6328486b8f5a5cbd10e377e80adb8cf94acbbe19c38b4e1bf708d831a80a3a
 * charmap.py 1b8b5fdb36ce3becc62a6115ed904a17083949ec8aaef5a80f7078cec232f43b
 */
export const codecFamilySources: ReadonlyMap<string, string> = new Map([
  ["encodings.utf_8_sig", [
    "\"\"\" Python 'utf-8-sig' Codec",
    "This work similar to UTF-8 with the following changes:",
    "",
    "* On encoding/writing a UTF-8 encoded BOM will be prepended/written as the",
    "  first three bytes.",
    "",
    "* On decoding/reading if the first three bytes are a UTF-8 encoded BOM, these",
    "  bytes will be skipped.",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "def encode(input, errors='strict'):",
    "    return (codecs.BOM_UTF8 + codecs.utf_8_encode(input, errors)[0],",
    "            len(input))",
    "",
    "def decode(input, errors='strict'):",
    "    prefix = 0",
    "    if input[:3] == codecs.BOM_UTF8:",
    "        input = input[3:]",
    "        prefix = 3",
    "    (output, consumed) = codecs.utf_8_decode(input, errors, True)",
    "    return (output, consumed+prefix)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.IncrementalEncoder.__init__(self, errors)",
    "        self.first = 1",
    "",
    "    def encode(self, input, final=False):",
    "        if self.first:",
    "            self.first = 0",
    "            return codecs.BOM_UTF8 + \\",
    "                   codecs.utf_8_encode(input, self.errors)[0]",
    "        else:",
    "            return codecs.utf_8_encode(input, self.errors)[0]",
    "",
    "    def reset(self):",
    "        codecs.IncrementalEncoder.reset(self)",
    "        self.first = 1",
    "",
    "    def getstate(self):",
    "        return self.first",
    "",
    "    def setstate(self, state):",
    "        self.first = state",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.BufferedIncrementalDecoder.__init__(self, errors)",
    "        self.first = 1",
    "",
    "    def _buffer_decode(self, input, errors, final):",
    "        if self.first:",
    "            if len(input) < 3:",
    "                if codecs.BOM_UTF8.startswith(input):",
    "                    # not enough data to decide if this really is a BOM",
    "                    # => try again on the next call",
    "                    return (\"\", 0)",
    "                else:",
    "                    self.first = 0",
    "            else:",
    "                self.first = 0",
    "                if input[:3] == codecs.BOM_UTF8:",
    "                    (output, consumed) = \\",
    "                       codecs.utf_8_decode(input[3:], errors, final)",
    "                    return (output, consumed+3)",
    "        return codecs.utf_8_decode(input, errors, final)",
    "",
    "    def reset(self):",
    "        codecs.BufferedIncrementalDecoder.reset(self)",
    "        self.first = 1",
    "",
    "    def getstate(self):",
    "        state = codecs.BufferedIncrementalDecoder.getstate(self)",
    "        # state[1] must be 0 here, as it isn't passed along to the caller",
    "        return (state[0], self.first)",
    "",
    "    def setstate(self, state):",
    "        # state[1] will be ignored by BufferedIncrementalDecoder.setstate()",
    "        codecs.BufferedIncrementalDecoder.setstate(self, state)",
    "        self.first = state[1]",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    def reset(self):",
    "        codecs.StreamWriter.reset(self)",
    "        try:",
    "            del self.encode",
    "        except AttributeError:",
    "            pass",
    "",
    "    def encode(self, input, errors='strict'):",
    "        self.encode = codecs.utf_8_encode",
    "        return encode(input, errors)",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    def reset(self):",
    "        codecs.StreamReader.reset(self)",
    "        try:",
    "            del self.decode",
    "        except AttributeError:",
    "            pass",
    "",
    "    def decode(self, input, errors='strict'):",
    "        if len(input) < 3:",
    "            if codecs.BOM_UTF8.startswith(input):",
    "                # not enough data to decide if this is a BOM",
    "                # => try again on the next call",
    "                return (\"\", 0)",
    "        elif input[:3] == codecs.BOM_UTF8:",
    "            self.decode = codecs.utf_8_decode",
    "            (output, consumed) = codecs.utf_8_decode(input[3:],errors)",
    "            return (output, consumed+3)",
    "        # (else) no BOM present",
    "        self.decode = codecs.utf_8_decode",
    "        return codecs.utf_8_decode(input, errors)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-8-sig',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
].join("\n")],
  ["encodings.utf_7", [
    "\"\"\" Python 'utf-7' Codec",
    "",
    "Written by Brian Quinlan (brian@sweetapp.com).",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_7_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_7_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_7_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_7_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_7_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_7_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-7',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_16_le", [
    "\"\"\" Python 'utf-16-le' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_16_le_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_16_le_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_16_le_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_16_le_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_16_le_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_16_le_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-16-le',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_16_be", [
    "\"\"\" Python 'utf-16-be' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_16_be_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_16_be_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_16_be_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_16_be_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_16_be_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_16_be_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-16-be',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_32_le", [
    "\"\"\"",
    "Python 'utf-32-le' Codec",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_32_le_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_32_le_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_32_le_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_32_le_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_32_le_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_32_le_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-32-le',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_32_be", [
    "\"\"\"",
    "Python 'utf-32-be' Codec",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_32_be_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_32_be_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.utf_32_be_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    _buffer_decode = codecs.utf_32_be_decode",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    encode = codecs.utf_32_be_encode",
    "",
    "class StreamReader(codecs.StreamReader):",
    "    decode = codecs.utf_32_be_decode",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-32-be',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.unicode_escape", [
    "\"\"\" Python 'unicode-escape' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "class Codec(codecs.Codec):",
    "",
    "    # Note: Binding these as C functions will result in the class not",
    "    # converting them to methods. This is intended.",
    "    encode = codecs.unicode_escape_encode",
    "    decode = codecs.unicode_escape_decode",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.unicode_escape_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    def _buffer_decode(self, input, errors, final):",
    "        return codecs.unicode_escape_decode(input, errors, final)",
    "",
    "class StreamWriter(Codec,codecs.StreamWriter):",
    "    pass",
    "",
    "class StreamReader(Codec,codecs.StreamReader):",
    "    def decode(self, input, errors='strict'):",
    "        return codecs.unicode_escape_decode(input, errors, False)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='unicode-escape',",
    "        encode=Codec.encode,",
    "        decode=Codec.decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamwriter=StreamWriter,",
    "        streamreader=StreamReader,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.raw_unicode_escape", [
    "\"\"\" Python 'raw-unicode-escape' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "class Codec(codecs.Codec):",
    "",
    "    # Note: Binding these as C functions will result in the class not",
    "    # converting them to methods. This is intended.",
    "    encode = codecs.raw_unicode_escape_encode",
    "    decode = codecs.raw_unicode_escape_decode",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def encode(self, input, final=False):",
    "        return codecs.raw_unicode_escape_encode(input, self.errors)[0]",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    def _buffer_decode(self, input, errors, final):",
    "        return codecs.raw_unicode_escape_decode(input, errors, final)",
    "",
    "class StreamWriter(Codec,codecs.StreamWriter):",
    "    pass",
    "",
    "class StreamReader(Codec,codecs.StreamReader):",
    "    def decode(self, input, errors='strict'):",
    "        return codecs.raw_unicode_escape_decode(input, errors, False)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='raw-unicode-escape',",
    "        encode=Codec.encode,",
    "        decode=Codec.decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamwriter=StreamWriter,",
    "        streamreader=StreamReader,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.charmap", [
    "\"\"\" Generic Python Character Mapping Codec.",
    "",
    "    Use this codec directly rather than through the automatic",
    "    conversion mechanisms supplied by unicode() and .encode().",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"#\"",
    "",
    "import codecs",
    "",
    "### Codec APIs",
    "",
    "class Codec(codecs.Codec):",
    "",
    "    # Note: Binding these as C functions will result in the class not",
    "    # converting them to methods. This is intended.",
    "    encode = codecs.charmap_encode",
    "    decode = codecs.charmap_decode",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def __init__(self, errors='strict', mapping=None):",
    "        codecs.IncrementalEncoder.__init__(self, errors)",
    "        self.mapping = mapping",
    "",
    "    def encode(self, input, final=False):",
    "        return codecs.charmap_encode(input, self.errors, self.mapping)[0]",
    "",
    "class IncrementalDecoder(codecs.IncrementalDecoder):",
    "    def __init__(self, errors='strict', mapping=None):",
    "        codecs.IncrementalDecoder.__init__(self, errors)",
    "        self.mapping = mapping",
    "",
    "    def decode(self, input, final=False):",
    "        return codecs.charmap_decode(input, self.errors, self.mapping)[0]",
    "",
    "class StreamWriter(Codec,codecs.StreamWriter):",
    "",
    "    def __init__(self,stream,errors='strict',mapping=None):",
    "        codecs.StreamWriter.__init__(self,stream,errors)",
    "        self.mapping = mapping",
    "",
    "    def encode(self,input,errors='strict'):",
    "        return Codec.encode(input,errors,self.mapping)",
    "",
    "class StreamReader(Codec,codecs.StreamReader):",
    "",
    "    def __init__(self,stream,errors='strict',mapping=None):",
    "        codecs.StreamReader.__init__(self,stream,errors)",
    "        self.mapping = mapping",
    "",
    "    def decode(self,input,errors='strict'):",
    "        return Codec.decode(input,errors,self.mapping)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='charmap',",
    "        encode=Codec.encode,",
    "        decode=Codec.decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamwriter=StreamWriter,",
    "        streamreader=StreamReader,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_16", [
    "\"\"\" Python 'utf-16' Codec",
    "",
    "",
    "Written by Marc-Andre Lemburg (mal@lemburg.com).",
    "",
    "(c) Copyright CNRI, All Rights Reserved. NO WARRANTY.",
    "",
    "\"\"\"",
    "import codecs, sys",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_16_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_16_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.IncrementalEncoder.__init__(self, errors)",
    "        self.encoder = None",
    "",
    "    def encode(self, input, final=False):",
    "        if self.encoder is None:",
    "            result = codecs.utf_16_encode(input, self.errors)[0]",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_16_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_16_be_encode",
    "            return result",
    "        return self.encoder(input, self.errors)[0]",
    "",
    "    def reset(self):",
    "        codecs.IncrementalEncoder.reset(self)",
    "        self.encoder = None",
    "",
    "    def getstate(self):",
    "        # state info we return to the caller:",
    "        # 0: stream is in natural order for this platform",
    "        # 2: endianness hasn't been determined yet",
    "        # (we're never writing in unnatural order)",
    "        return (2 if self.encoder is None else 0)",
    "",
    "    def setstate(self, state):",
    "        if state:",
    "            self.encoder = None",
    "        else:",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_16_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_16_be_encode",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.BufferedIncrementalDecoder.__init__(self, errors)",
    "        self.decoder = None",
    "",
    "    def _buffer_decode(self, input, errors, final):",
    "        if self.decoder is None:",
    "            (output, consumed, byteorder) = \\",
    "                codecs.utf_16_ex_decode(input, errors, 0, final)",
    "            if byteorder == -1:",
    "                self.decoder = codecs.utf_16_le_decode",
    "            elif byteorder == 1:",
    "                self.decoder = codecs.utf_16_be_decode",
    "            elif consumed >= 2:",
    "                raise UnicodeDecodeError(\"utf-16\", input, 0, 2, \"Stream does not start with BOM\")",
    "            return (output, consumed)",
    "        return self.decoder(input, self.errors, final)",
    "",
    "    def reset(self):",
    "        codecs.BufferedIncrementalDecoder.reset(self)",
    "        self.decoder = None",
    "",
    "    def getstate(self):",
    "        # additional state info from the base class must be None here,",
    "        # as it isn't passed along to the caller",
    "        state = codecs.BufferedIncrementalDecoder.getstate(self)[0]",
    "        # additional state info we pass to the caller:",
    "        # 0: stream is in natural order for this platform",
    "        # 1: stream is in unnatural order",
    "        # 2: endianness hasn't been determined yet",
    "        if self.decoder is None:",
    "            return (state, 2)",
    "        addstate = int((sys.byteorder == \"big\") !=",
    "                       (self.decoder is codecs.utf_16_be_decode))",
    "        return (state, addstate)",
    "",
    "    def setstate(self, state):",
    "        # state[1] will be ignored by BufferedIncrementalDecoder.setstate()",
    "        codecs.BufferedIncrementalDecoder.setstate(self, state)",
    "        state = state[1]",
    "        if state == 0:",
    "            self.decoder = (codecs.utf_16_be_decode",
    "                            if sys.byteorder == \"big\"",
    "                            else codecs.utf_16_le_decode)",
    "        elif state == 1:",
    "            self.decoder = (codecs.utf_16_le_decode",
    "                            if sys.byteorder == \"big\"",
    "                            else codecs.utf_16_be_decode)",
    "        else:",
    "            self.decoder = None",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    def __init__(self, stream, errors='strict'):",
    "        codecs.StreamWriter.__init__(self, stream, errors)",
    "        self.encoder = None",
    "",
    "    def reset(self):",
    "        codecs.StreamWriter.reset(self)",
    "        self.encoder = None",
    "",
    "    def encode(self, input, errors='strict'):",
    "        if self.encoder is None:",
    "            result = codecs.utf_16_encode(input, errors)",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_16_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_16_be_encode",
    "            return result",
    "        else:",
    "            return self.encoder(input, errors)",
    "",
    "class StreamReader(codecs.StreamReader):",
    "",
    "    def reset(self):",
    "        codecs.StreamReader.reset(self)",
    "        try:",
    "            del self.decode",
    "        except AttributeError:",
    "            pass",
    "",
    "    def decode(self, input, errors='strict'):",
    "        (object, consumed, byteorder) = \\",
    "            codecs.utf_16_ex_decode(input, errors, 0, False)",
    "        if byteorder == -1:",
    "            self.decode = codecs.utf_16_le_decode",
    "        elif byteorder == 1:",
    "            self.decode = codecs.utf_16_be_decode",
    "        elif consumed>=2:",
    "            raise UnicodeDecodeError(\"utf-16\", input, 0, 2, \"Stream does not start with BOM\")",
    "        return (object, consumed)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-16',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")],
  ["encodings.utf_32", [
    "\"\"\"",
    "Python 'utf-32' Codec",
    "\"\"\"",
    "import codecs, sys",
    "",
    "### Codec APIs",
    "",
    "encode = codecs.utf_32_encode",
    "",
    "def decode(input, errors='strict'):",
    "    return codecs.utf_32_decode(input, errors, True)",
    "",
    "class IncrementalEncoder(codecs.IncrementalEncoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.IncrementalEncoder.__init__(self, errors)",
    "        self.encoder = None",
    "",
    "    def encode(self, input, final=False):",
    "        if self.encoder is None:",
    "            result = codecs.utf_32_encode(input, self.errors)[0]",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_32_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_32_be_encode",
    "            return result",
    "        return self.encoder(input, self.errors)[0]",
    "",
    "    def reset(self):",
    "        codecs.IncrementalEncoder.reset(self)",
    "        self.encoder = None",
    "",
    "    def getstate(self):",
    "        # state info we return to the caller:",
    "        # 0: stream is in natural order for this platform",
    "        # 2: endianness hasn't been determined yet",
    "        # (we're never writing in unnatural order)",
    "        return (2 if self.encoder is None else 0)",
    "",
    "    def setstate(self, state):",
    "        if state:",
    "            self.encoder = None",
    "        else:",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_32_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_32_be_encode",
    "",
    "class IncrementalDecoder(codecs.BufferedIncrementalDecoder):",
    "    def __init__(self, errors='strict'):",
    "        codecs.BufferedIncrementalDecoder.__init__(self, errors)",
    "        self.decoder = None",
    "",
    "    def _buffer_decode(self, input, errors, final):",
    "        if self.decoder is None:",
    "            (output, consumed, byteorder) = \\",
    "                codecs.utf_32_ex_decode(input, errors, 0, final)",
    "            if byteorder == -1:",
    "                self.decoder = codecs.utf_32_le_decode",
    "            elif byteorder == 1:",
    "                self.decoder = codecs.utf_32_be_decode",
    "            elif consumed >= 4:",
    "                raise UnicodeDecodeError(\"utf-32\", input, 0, 4, \"Stream does not start with BOM\")",
    "            return (output, consumed)",
    "        return self.decoder(input, self.errors, final)",
    "",
    "    def reset(self):",
    "        codecs.BufferedIncrementalDecoder.reset(self)",
    "        self.decoder = None",
    "",
    "    def getstate(self):",
    "        # additional state info from the base class must be None here,",
    "        # as it isn't passed along to the caller",
    "        state = codecs.BufferedIncrementalDecoder.getstate(self)[0]",
    "        # additional state info we pass to the caller:",
    "        # 0: stream is in natural order for this platform",
    "        # 1: stream is in unnatural order",
    "        # 2: endianness hasn't been determined yet",
    "        if self.decoder is None:",
    "            return (state, 2)",
    "        addstate = int((sys.byteorder == \"big\") !=",
    "                       (self.decoder is codecs.utf_32_be_decode))",
    "        return (state, addstate)",
    "",
    "    def setstate(self, state):",
    "        # state[1] will be ignored by BufferedIncrementalDecoder.setstate()",
    "        codecs.BufferedIncrementalDecoder.setstate(self, state)",
    "        state = state[1]",
    "        if state == 0:",
    "            self.decoder = (codecs.utf_32_be_decode",
    "                            if sys.byteorder == \"big\"",
    "                            else codecs.utf_32_le_decode)",
    "        elif state == 1:",
    "            self.decoder = (codecs.utf_32_le_decode",
    "                            if sys.byteorder == \"big\"",
    "                            else codecs.utf_32_be_decode)",
    "        else:",
    "            self.decoder = None",
    "",
    "class StreamWriter(codecs.StreamWriter):",
    "    def __init__(self, stream, errors='strict'):",
    "        self.encoder = None",
    "        codecs.StreamWriter.__init__(self, stream, errors)",
    "",
    "    def reset(self):",
    "        codecs.StreamWriter.reset(self)",
    "        self.encoder = None",
    "",
    "    def encode(self, input, errors='strict'):",
    "        if self.encoder is None:",
    "            result = codecs.utf_32_encode(input, errors)",
    "            if sys.byteorder == 'little':",
    "                self.encoder = codecs.utf_32_le_encode",
    "            else:",
    "                self.encoder = codecs.utf_32_be_encode",
    "            return result",
    "        else:",
    "            return self.encoder(input, errors)",
    "",
    "class StreamReader(codecs.StreamReader):",
    "",
    "    def reset(self):",
    "        codecs.StreamReader.reset(self)",
    "        try:",
    "            del self.decode",
    "        except AttributeError:",
    "            pass",
    "",
    "    def decode(self, input, errors='strict'):",
    "        (object, consumed, byteorder) = \\",
    "            codecs.utf_32_ex_decode(input, errors, 0, False)",
    "        if byteorder == -1:",
    "            self.decode = codecs.utf_32_le_decode",
    "        elif byteorder == 1:",
    "            self.decode = codecs.utf_32_be_decode",
    "        elif consumed >= 4:",
    "            raise UnicodeDecodeError(\"utf-32\", input, 0, 4, \"Stream does not start with BOM\")",
    "        return (object, consumed)",
    "",
    "### encodings module API",
    "",
    "def getregentry():",
    "    return codecs.CodecInfo(",
    "        name='utf-32',",
    "        encode=encode,",
    "        decode=decode,",
    "        incrementalencoder=IncrementalEncoder,",
    "        incrementaldecoder=IncrementalDecoder,",
    "        streamreader=StreamReader,",
    "        streamwriter=StreamWriter,",
    "    )",
    ""
  ].join("\n")]
]);
