export const baseline = '5137a74ec855a32d8a8860eb66b62eb44d11e290';
export const acceptedModule = 'a23867d6a42e1cb2f2e7278cf22061737a4bea9d';
export const expected77 = [
  '[', 'awk', 'base32', 'base64', 'basename', 'cat', 'chmod', 'cksum', 'column',
  'comm', 'cp', 'cut', 'date', 'diff', 'dirname', 'du', 'echo', 'egrep', 'env',
  'expand', 'expr', 'false', 'fgrep', 'file', 'find', 'fold', 'grep', 'gunzip',
  'gzip', 'head', 'html-to-markdown', 'join', 'jq', 'ln', 'ls', 'md5sum', 'mkdir',
  'mktemp', 'mv', 'nl', 'od', 'paste', 'patch', 'printenv', 'printf', 'pwd',
  'readlink', 'realpath', 'rev', 'rg', 'rm', 'rmdir', 'sed', 'seq', 'sha1sum',
  'sha256sum', 'sleep', 'sort', 'split', 'stat', 'strings', 'tac', 'tail', 'tar',
  'tee', 'test', 'touch', 'tr', 'tree', 'true', 'unexpand', 'uniq', 'wc', 'which',
  'xargs', 'xxd', 'zcat',
];
export const expected78 = [...expected77, 'timeout'].sort();
export const factories = ['createTimeoutCommand', 'createTimeoutCommands', 'timeoutCommands'];
export const types = ['TimeoutScheduler', 'TimeoutCommandOptions', 'TimeoutCommandsOptions'];
export const publicPaths = ['package.json', 'src/index.ts', 'src/plugins/index.ts'];
export const records = {
  help: { status: 0, stdout: 'Usage: timeout [OPTION] DURATION COMMAND [ARG]...\nRun a virtual-bash command with a cooperative time limit.\n', stderr: '' },
  version: { status: 0, stdout: 'timeout (virtual-bash cooperative profile)\n', stderr: '' },
  missingDuration: { status: 125, stdout: '', stderr: 'timeout: missing duration\n' },
  missingCommand: { status: 125, stdout: '', stderr: 'timeout: missing command\n' },
  invalidDuration: { status: 125, stdout: '', stderr: 'timeout: invalid duration\n' },
  invalidOption: { status: 125, stdout: '', stderr: 'timeout: invalid option\n' },
  unsupportedSignal: { status: 125, stdout: '', stderr: 'timeout: option --signal is unsupported\n' },
  unavailable: { status: 125, stdout: '', stderr: 'timeout: command invocation is unavailable\n' },
  borrowedOuter: { status: 1, stdout: '', stderr: 'shell: line 1: [object Object]\n' },
  textLimit: { status: 2, stdout: '', stderr: 'sed: text buffer limit exceeded\n' },
};

export const runtime = [
  { id: 'R01', name: 'Exact default plugin membership',
    setup: 'Compare independently frozen expected78 against createAgentCommands(), agentCommands().setup(empty host), and new Shell({fs}).use(agentCommands()).commands. Do not treat bare Shell as automatically populated.',
    expect: 'Each exactly 78 unique names; exactly one timeout, which, expr, du and html-to-markdown; curl/safejs/getopts absent from plugin names. getopts remains a builtin, not the 79th plugin.' },
  { id: 'R02', name: 'Public root and explicit leaf identity',
    setup: 'Import root and virtual-bash/commands/timeout through package exports in installed and physically moved layouts; compare all three function identities. Source layout uses its separately authenticated source entrypoints.',
    expect: 'Exactly the declared three runtime factory exports in the leaf; all three match root by identity. Single definition name timeout; family one definition; plugin name timeout-commands. No internal import by public consumers.' },
  { id: 'R03', name: 'Atomic collision preflight',
    vectors: ['timeout', 'printf', 'which'],
    setup: 'Preinstall selected conflict returning 23 plus unrelated custom returning 19; setup agentCommands() and agentCommands({replace:false,timeout:{replace:true}}) through deliberately untyped JS.',
    expect: 'Throw exact Error message Command already registered: <conflict>; registry objects/names and both original handlers unchanged, no partial installation.' },
  { id: 'R04', name: 'Top-level replacement is authoritative',
    setup: 'Existing timeout/printf return23 and custom returns19; install agentCommands({replace:true,timeout:{replace:false}}) through JS. Separately use fresh host with timeout/custom only for replace:false and nested true.',
    expect: 'First installs expected78 plus custom (79), replaces both conflicts, preserves custom by identity; timeout --version exact version, printf x outputs x. Separate fresh host throws exact timeout collision without changing registry.' },
  { id: 'R05', name: 'Direct factory compatibility',
    setup: 'Root and leaf factories with controlled scheduler and invoke returning7; single factory ignore a throwing replace getter, family/plugin accept replace true/false and reject string x. Plugin collision/replacement against timeout-only host.',
    expect: 'Direct accepted APIs unchanged; single factory does not read replace, invalid family replace TypeError, family count1; plugin default collision exact, explicit true replaces and retains unrelated definition.' },
  { id: 'R06', name: 'Aggregate trusted dependency forwarding',
    setup: 'Both createAgentCommands and agentCommands use timeout:{invoke:fallback7,scheduler:clock,maxTimerMilliseconds:2}. Execute their timeout definition on a context without invoke: args [.003,child,a b]. Hold child; initial clock0; wake first at2 then second at3; child observes deadline, close child before return.',
    expect: 'Fallback exactly once, this undefined, literal argv, arms [2,1], at most one live handle for this operation, final124/empty outputs only after child closure; no aggregate fallback synthesized when timeout.invoke is absent.' },
  { id: 'R07', name: 'Family option isolation',
    setup: 'Untightened positives: sed -n p with stdin long\\n => long\\n,0; timeout .003 child => child7,empty, first arm3. Independently set text.maxBufferBytes=1 (sed fails exact textLimit; timeout remains7/arm3), then timeout.maxTimerMilliseconds=2 (timeout remains7/arm2; sed remains exact positive). Configure fake scheduler separately for each timeout invocation.',
    expect: 'No cross-family option leakage; combine both options and obtain both independently expected effects. Timer chunk cap is not a failure budget and must not be mislabeled as one.' },
  { id: 'R08', name: 'Aggregate eager invalid option rejection',
    vectors: [{ maxTimerMilliseconds: 0 }, { maxTimerMilliseconds: 1.5 }, { maxTimerMilliseconds: 2147483648 }, { invoke: 1 }, { scheduler: null }],
    setup: 'Both aggregate factory and plugin setup; host initially only custom. Spy configured provider methods and fallback.',
    expect: 'First three RangeError, last two TypeError as accepted factory; no provider invocation, no registered aggregate commands, custom unchanged.' },
  { id: 'R09', name: 'Context hook priority and presence',
    setup: 'Default aggregate timeout definition with configured fallback17. Own callable and inherited callable return7 and receive this===context; absent uses fallback17; own/inherited undefined, null, false, object refuse. Getter own callable read once. Args [0,literal-command,a b,$(not-shell)].',
    expect: 'Callable present always wins; only absent invokes fallback; refusal exact unavailable with zero fallback calls; no timers; argv literal. With no configured fallback and absent context hook, same unavailable refusal.' },
  { id: 'R10', name: 'Zero duration transparent public dispatch',
    setup: 'Actual aggregate Shell command timeout 0 public-child; child receives binary stdin [0,255,65], writes same bytes stdout and [69,10] stderr, returns7. Also direct aggregate definition with borrowed streams, args [0,child,a b,$(not-shell)].',
    expect: 'Exit7, exact bytes/argv, no scheduler reads/arms/clears or timeout cleanup registration; direct invocation forwards same stream references and no local signal property; parent signal untouched.' },
  { id: 'R11', name: 'Help and version are no-work controls',
    vectors: ['--help', '--version'],
    setup: 'Default aggregate public Shell and direct aggregate definition. Throw-on-read stdin/invoke/cleanup on direct context; blocking stdout sink until released; spy scheduler/fallback.',
    expect: 'Exact records help/version; status0 only after write settles; zero child dispatch/stdin iteration/timer activity. Direct sink rejection preserves exact identity; do not swallow required output failures.' },
  { id: 'R12', name: 'CLI refusal before child admission',
    vectors: [{ argv: [], record: 'missingDuration' }, { argv: ['1'], record: 'missingCommand' }, { argv: ['bad','child'], record: 'invalidDuration' }, { argv: ['--unknown','1','child'], record: 'invalidOption' }, { argv: ['--signal=TERM','1','child'], record: 'unsupportedSignal' }],
    setup: 'Direct aggregate definition and actual Shell parsed equivalent commands. Observe child/fallback/provider/stdin counters and required stderr.',
    expect: 'Exact per-vector125 records, zero child admission/timer/stdin. Direct stderr sentinel rejection remains exact. This is not a new numeric/native cohort.' },
  { id: 'R13', name: 'Repaired default clock through default plugin',
    setup: 'No timeout overrides. Actual Shell with agentCommands and public-child immediate7: timeout 60 public-child. Observe middleware dispatch and owned timer/resource closure before disposal. Also root/leaf single factories on raw context with invoke7.',
    expect: '7 and empty outputs, one timeout/one child dispatch for Shell; no ERR_INVALID_THIS or timer setup failed; owned timer retired before settlement, resource baseline restored. No real 60-second wait required; watchdog is not a product timeout pass.' },
  { id: 'R14', name: 'Shared dispatcher and resolver boundaries',
    setup: 'agentCommands({timeout:{invoke:throwIfUsed}}) in actual Shell with middleware, custom child7, VFS directory /unsupported-directory. Commands timeout 0 public-child; unknown-fixture-command and timeout 0 unknown-fixture-command; /unsupported-directory and timeout 0 /unsupported-directory.',
    expect: 'Configured fallback never used; middleware order timeout then selected child. Wrapped/bare missing127 stderr shell: line 1: unknown-fixture-command: command not found\\n; directory126 stderr shell: line 1: /unsupported-directory: Is a directory\\n; exact empty stdout.' },
  { id: 'R15', name: 'Command budget not reset',
    source: 'timeout 0 public-child',
    setup: 'public-child returns0. Untightened baseline and maxCommands2 succeed; maxCommands1 rejects.',
    expect: 'Exact ShellLimitError, limit maxCommands, message Shell limit exceeded: maxCommands; limited leaf not dispatched; no private fallback/new Shell to escape shared budget.' },
  { id: 'R16', name: 'Nested invocation depth not reset',
    source: 'timeout 0 public-child recursive',
    setup: 'public-child uses context.invoke(leaf,[]); leaf returns0. Untightened baseline0; maxSubstitutionDepth1 rejects.',
    expect: 'ShellLimitError limit maxSubstitutionDepth with exact standard message; raw rejection not125 or124, all dispatch/cleanup observed.' },
  { id: 'R17', name: 'Shared output budget',
    source: 'timeout 0 public-child output',
    setup: 'Child awaits writing UTF8 four, returns0. Baseline exact four/status0. maxOutputBytes3 rejects.',
    expect: 'ShellLimitError limit maxOutputBytes exact standard message, not timeout status; output counted through same sink, no hidden collector/reset.' },
  { id: 'R18', name: 'Outer source and expansion bounds preserved',
    vectors: [{ limit: 'maxSourceBytes', value: 128, source: 'timeout <129 zero characters> public-child' }, { limit: 'maxExpansionBytes', value: 64, source: 'timeout $LONG public-child', env: { LONG: 'repeat zero 65' } }, { limit: 'maxExpansionFields', value: 4, source: 'timeout 0 public-child $FIELDS', env: { FIELDS: 'a b c d e' } }],
    expect: 'Each unrestricted baseline0 then exact ShellLimitError with named limit on constrained run; child not dispatched on rejection. Expand placeholders literally per stated lengths, no new parser counter/budget.' },
  { id: 'R19', name: 'Streaming backpressure and chunk ownership',
    setup: 'Actual Shell timeout 0 cat with async stdin yielding reusable Buffer [0,255,65], mutate only when producer is advanced; next chunk [66]. Gate first stdout sink write. Compare untimed cat baseline.',
    expect: 'Timed producer advancement count matches untimed baseline while first sink write remains pending; timeout introduces no additional read-ahead. Both routes exact [0,255,65,66]/status0/empty stderr. All writes awaited, producer finally closes; direct forwarding also checked by R10. No concurrent mutation/opaque provider preemption claim.' },
  { id: 'R20', name: 'Provenance and parent state unchanged',
    setup: 'Actual Shell parent cwd /parent env MARK=parent. Spy child under timeout 0 and untimed baseline with omitted stdin versus explicit empty Uint8Array; child snapshots stdinIsDefault/cwd/env/fs, writes nothing, returns7.',
    expect: 'Timed matches untimed: omitted stdin default true, supplied empty false; same fs/cwd/env semantics, parent state unchanged, no timeout-specific env injection or state reset. Direct forwarding preserves optional provenance property presence.' },
  { id: 'R21', name: 'Deadline waits for cooperative cleanup',
    setup: 'Actual aggregate timeout .001 public-child; clock0, child synchronously registers cleanup before admission and waits on borrowed signal; cleanup waits explicit gate. Wake timer at1, capture raw handler and outer outcome while gate held, then release.',
    expect: 'Own reason observed; handler/outer pending until child and registered cleanup close. Then124/empty outputs, no outstanding owned timer/promises/unhandled rejections, original caller remains live.' },
  { id: 'R22', name: 'Early completion retires without stale callback effects',
    setup: 'timeout .010 public-child returns7 with clock0; opaque handle0. After settled closure deliver the once-offered stale callback at10; include raw context cleanup hook and actual Shell route.',
    expect: '7/empty outputs before and after stale callback; exactly one retirement, no rearm/extra dispatch or caller abort. Cleanup registered before first now/arm and observed complete.' },
  { id: 'R23', name: 'Root caller same-sentinel priority',
    setup: 'Adapt accepted repaired PC01 root-caller schedule, selecting timeout from agentCommands rather than manual module registration. Fire own deadline, abort outer caller with that identical observed sentinel while child cleanup gated, release.',
    expect: 'Raw timeout handler and outer Shell both reject exact same sentinel after cleanup; never accept raw124 even if outer later rejects. Child closed and owned resources0; preserve accepted assertCallerCollision predicate unchanged.' },
  { id: 'R24', name: 'Borrowed caller and live Shell error boundary',
    setup: 'Adapt accepted repaired PC01 borrowed outer-context schedule through aggregate timeout. Outer command context.invoke(timeout,[.001,child],{signal:borrowedCaller}); fire own timer then abort borrowed caller with same observed sentinel before cleanup release.',
    expect: 'Preserve assertBorrowedCollision byte-identically: raw handler/raw invoke reject identical sentinel; dispatch timeout1/child1/outer1, pending until closure; live outer fulfills exact borrowedOuter record, stdout/stderr bytes checked; never raw124.' },
  { id: 'R25', name: 'Activated retirement sentinel collision',
    setup: 'Adapt accepted repaired PC02 direct and actual Shell cleanup-barrier schedules through root/aggregate factories. Offered timer deadline observed; provider clearTimeout actually entered and throws identical own-deadline sentinel during retirement.',
    expect: 'Receipt proves actual entered/threw and same identity, child closed before final outcome; raw handler/outer reject, never124; accepted cleanup aggregation/closure qualifications preserved, not an assumed scheduler call.' },
  { id: 'R26', name: 'Foreign execution failure is not deadline success',
    setup: 'Raw aggregate timeout .001 invokes gated child; own deadline fires, child then throws distinct Error(foreign-timeout-fixture). Separately actual Shell selected child throws that error while parent remains live.',
    expect: 'Raw handler rejects identical foreign error rather than124. Actual live Shell command boundary yields1, empty stdout, exact shell: line 1: foreign-timeout-fixture\\n stderr; record raw mapped child result, do not invent an escaping error from mapped status.' },
  { id: 'R27', name: 'Nested default timeout shares command budget',
    source: 'timeout 0 timeout 0 public-child',
    setup: 'Child returns7; unrestricted and maxCommands3 positives, maxCommands2 negative. Middleware records both timeout dispatches and leaf.',
    expect: 'Positive7/empty outputs, two timeout and one leaf; negative exact maxCommands ShellLimitError with no leaf admission. Zero timers, no budget reset; no global one-handle limit across separate operations invented.' },
  { id: 'R28', name: 'Timer remains live through selected cleanup',
    setup: 'Actual Shell child handler returns7 but registered cleanup waits gate. timeout .001 public-child with controlled clock; fire deadline during cleanup, then release. Separate raw aggregate definition uses trusted invoke that explicitly returns7 after deadline and its own gated closure, as accepted F32.',
    expect: 'Both routes remain pending through closure. Actual Shell local-invocation cancellation escapes selected invoke with own reason and timeout maps124 (accepted F29 pattern); raw trusted invoke returning7 remains7 (F32). Record selected invoke outcome separately; never infer provenance from returned status. All timers retired.' },
  { id: 'R29', name: 'Dispose overlaps cancellation and cleanup',
    setup: 'Adapt accepted F28 root-caller/disposal schedule through aggregate timeout: hold child cleanup, caller aborts frozen reason, start Shell.dispose while cleanup held, release.',
    expect: 'Raw/outer reject identical caller reason, exec and dispose do not settle early; disposal fulfills after closure; no additional child/timer admission or unhandled rejection.' },
  { id: 'R30', name: 'Captured injected receiver survives public composition',
    setup: 'Construct aggregate definitions with timeout fallback7, method-bound controlled scheduler, maxTimerMilliseconds7. Then replace original options.invoke/maxTimerMilliseconds and scheduler method properties with throwing sentinels. Execute .020 child with context invoke absent; repeat plugin after setup.',
    expect: 'Captured invoke7 still called with undefined receiver; captured scheduler methods see original receiver, first arm7, final7/empty outputs with retirement. No requirement that plugin capture options before setup; direct factories remain accepted eager capture.' },
];

export const admission = [
  { id: 'A01', name: 'Exact declared composition', expect: 'Reconstruct selected committed build view from 268 hash/mode/blob-bound accepted inputs (264 baseline plus four module files), replacing only three publicPaths with predeclared candidate Git blobs; authenticate complete selected inventory, forbid unknown product paths including concurrent WebDAV/XAN. No live source fallback/full history claim.' },
  { id: 'A02', name: 'Frozen and fresh-tree integrity', expect: 'Authenticate pristine freeze and tool closure before first run; guard fresh input mode/hash/newentry after each child/case. Reject AGENTS before content, symlinks, wrong base/module/public blob, unlisted input and path escape; no broad live-tree census.' },
  { id: 'A03', name: 'Whole pack reproduction', expect: 'Build from authenticated view, bind compiler/dependencies/actual tool loads, reproduce entire candidate npm pack byte hash and all member paths/modes/hashes; no identity-only substitute for build. Pinned base scripts/dependencies/exports remain unchanged except explicit timeout export. No new runtime dependency.' },
  { id: 'A04', name: 'Offline installed and physically moved', expect: 'Actual isolated offline install and physical move to another owned prefix, with original install path and source/build trees inaccessible to consumers. Run R01-R30 and T01-T10 per layout (source runtime, installed public, moved public), actual module/declaration load receipts, no internal import escape.' },
  { id: 'A05', name: 'Entrypoint-specific declarations', expect: 'Root consumers load actual root declaration plus transitive closure; leaf-only consumers load exported timeout leaf plus required closure, not unrelated root. All loaded package declarations authenticated, required entrypoint must actually be read. Missing-export/fallback/unrelated compiler error negatives must fail designated checks.' },
  { id: 'A06', name: 'Export and production fallback negatives', expect: 'Missing timeout root export, missing subpath mapping, wrong subpath target, missing declaration/runtime, tampered loaded module and forced source fallback are distinct expected negative controls; no product loads when load guard denies source. Do not accept generic assertion errors.' },
  { id: 'A07', name: 'Scoped mutants', expect: 'Versioned mutants after exact-source binding: omit timeout registration killed R01; replace-policy inversion R03/R04; erase context.invoke to force fallback R09/R14; cross-family maxTimer from text.maxBufferBytes killed R07 using text2 vs timeout7; new invocation budget killed R15/R27; scheduler receiver reversion killed R13; accepted caller/retirement priority mutants killed R23/R25 only with activation and cleanup. Actual mutated loads required, no disk-only proof.' },
  { id: 'A08', name: 'Bounded settlement and honest counts', expect: 'Preseal executable adapter/order/toolhashes/watchdogs and per-case cleanup before candidate run. Continue ordinary assertion failures only if bindings intact and all children/promises/timers reaped; otherwise STOP. Separate intentional negatives, all unrun rows, historical failures, source vs installed vs moved. No native/SafeJS/public/full-gate acceptance from freeze.' },
];
