import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url)), repo = resolve(here, '../../../..');
const sha = bytes => createHash('sha256').update(bytes).digest('hex');
const read = path => fs.readFileSync(resolve(repo, path));
const local = name => fs.readFileSync(resolve(here, name));
const manifestBytes = local('MANIFEST.json'), manifest = JSON.parse(manifestBytes);
assert.equal(process.argv[2], sha(manifestBytes), 'EXPLICIT_MANIFEST_HASH');
assert.equal(fs.existsSync(resolve(here, 'VALIDATION.json')), false, 'NO_RETRY');
for (const row of manifest.files) assert.equal(sha(local(row.path)), row.sha256, `FROZEN_FILE:${row.path}`);
const bindings = JSON.parse(local('BINDINGS.json'));
for (const row of bindings.tools) assert.equal(sha(read(row.path)), row.sha256, 'PRE_RUN_TOOL');
assert.equal(process.execPath, bindings.tools[0].path);
assert.equal(process.version, 'v22.22.2');
for (const row of bindings.protectedFiles) assert.equal(sha(read(row.path)), row.sha256, 'PROTECTED_PRE');
fs.writeFileSync(resolve(here, 'validation.lock'), JSON.stringify({ startedAt: new Date().toISOString(), manifest: sha(manifestBytes), pid: process.pid }) + '\n', { flag: 'wx' });
const { expected77, expected78, factories, baseline, acceptedModule, publicPaths, runtime, admission, records } = await import('./cases.mjs');
const { consumers } = await import('./types.mjs');
const { assertInventory, assertComposition, assertSafeInput, assertExports, assertSurface, assertTypeOutcome } = await import('./predicates.mjs');
assert.equal(expected77.length, 77);
assert.equal(runtime.length, 30);
assert.equal(admission.length, 8);
assert.equal(consumers.length, 10);
assert.equal(Buffer.byteLength(records.borrowedOuter.stderr), 31);
for (const group of [runtime, admission, consumers]) assert.equal(new Set(group.map(row => row.id)).size, group.length);
const clone = value => structuredClone(value);
const candidate = '1111111111111111111111111111111111111111';
const declaration = { baseline, module: acceptedModule, candidate, public: bindings.selectedInputs.filter(row => publicPaths.includes(row.path)).map(row => ({ ...row, commit: candidate })) };
const syntheticPackage = clone(bindings.originalPackage);
syntheticPackage.exports['./commands/timeout'] = { types: './dist/commands/timeout/index.d.ts', import: './dist/commands/timeout/index.js' };
const root = Object.fromEntries(factories.map(name => [name, function syntheticFactory() {}]));
const leaf = { ...root };
const positiveLeaf = { exitCode: 0, authenticatedReads: ['dist/commands/timeout/index.d.ts'], sourceFallback: false, unboundReads: 0, diagnostics: [] };
const negative = { exitCode: 2, authenticatedReads: ['dist/index.d.ts'], sourceFallback: false, unboundReads: 0, diagnostics: [{ file: 'consumer.ts', code: 2353, line: 2, token: 'replace', message: 'Object literal may only specify known properties, and \'replace\' does not exist in type \'Omit<TimeoutCommandsOptions, "replace">\'.' }] };
const controls = [];
const positive = (id, name, execute) => controls.push({ id, name, expectation: 'accept', execute });
const negativeControl = (id, name, pattern, execute) => controls.push({ id, name, expectation: 'reject', execute: () => assert.throws(execute, error => error.code === 'ERR_ASSERTION' && error.message.includes(pattern)) });
positive('C01', 'exact78', () => assertInventory(expected78));
negativeControl('C02', 'old77', 'DEFAULT_COUNT', () => assertInventory(expected77));
negativeControl('C03', 'duplicate', 'DUPLICATE_DEFAULT', () => assertInventory([...expected78.slice(1), expected78[1]]));
negativeControl('C04', 'curl-substitution', 'DEFAULT_NAMES', () => assertInventory(expected78.map(name => name === 'timeout' ? 'curl' : name)));
negativeControl('C05', 'builtin-substitution', 'DEFAULT_NAMES', () => assertInventory(expected78.map(name => name === 'which' ? 'getopts' : name)));
positive('C06', 'synthetic-composition', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, declaration));
negativeControl('C07', 'wrong-base', 'WRONG_BASELINE', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, { ...declaration, baseline: candidate }));
negativeControl('C08', 'wrong-module', 'WRONG_MODULE', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, { ...declaration, module: candidate }));
negativeControl('C09', 'unknown-input', 'UNLISTED_OR_MISSING_INPUT', () => assertComposition([...bindings.selectedInputs, { ...bindings.selectedInputs[0], path: 'src/commands/xan/index.ts' }], bindings.selectedInputs, declaration));
negativeControl('C10', 'missing-input', 'UNLISTED_OR_MISSING_INPUT', () => assertComposition(bindings.selectedInputs.slice(1), bindings.selectedInputs, declaration));
negativeControl('C11', 'module-tamper', 'INPUT_SHA256', () => assertComposition(bindings.selectedInputs.map(row => row.path === 'src/commands/timeout/scheduler.ts' ? { ...row, sha256: '0'.repeat(64) } : row), bindings.selectedInputs, declaration));
negativeControl('C12', 'mode-tamper', 'INPUT_MODE:', () => assertComposition(bindings.selectedInputs.map(row => row.path === 'src/commands/timeout/scheduler.ts' ? { ...row, mode: '100755' } : row), bindings.selectedInputs, declaration));
negativeControl('C13', 'AGENTS-name-only', 'AGENTS_INPUT', () => assertSafeInput({ ...bindings.selectedInputs[0], path: 'src/AGENTS.md' }));
negativeControl('C14', 'symlink-mode', 'INPUT_MODE', () => assertSafeInput({ ...bindings.selectedInputs[0], mode: '120000' }));
negativeControl('C15', 'escape-path', 'INPUT_PATH', () => assertSafeInput({ ...bindings.selectedInputs[0], path: '../package.json' }));
negativeControl('C16', 'wrong-public-blob', 'INPUT_BLOB', () => assertComposition(bindings.selectedInputs.map(row => row.path === 'src/index.ts' ? { ...row, blob: '0'.repeat(40) } : row), bindings.selectedInputs, declaration));
negativeControl('C17', 'concurrent-WebDAV-change', 'INPUT_SHA256', () => {
  const path = bindings.selectedInputs.find(row => row.path.startsWith('src/fs/webdav/')).path;
  assertComposition(bindings.selectedInputs.map(row => row.path === path ? { ...row, sha256: '0'.repeat(64) } : row), bindings.selectedInputs, declaration);
});
positive('C18', 'explicit-export-delta', () => assertExports(syntheticPackage, bindings.originalPackage));
negativeControl('C19', 'missing-subpath', 'PACKAGE_EXPORT_DELTA', () => assertExports(bindings.originalPackage, bindings.originalPackage));
negativeControl('C20', 'wrong-export-target', 'PACKAGE_EXPORT_DELTA', () => { const value = clone(syntheticPackage); value.exports['./commands/timeout'].import = './src/commands/timeout/index.ts'; assertExports(value, bindings.originalPackage); });
negativeControl('C21', 'new-runtime-dependency', 'PACKAGE_EXPORT_DELTA', () => assertExports({ ...syntheticPackage, dependencies: { injected: '*' } }, bindings.originalPackage));
positive('C22', 'root-leaf-identity', () => assertSurface(root, leaf));
negativeControl('C23', 'missing-root-export', 'MISSING_ROOT_EXPORT', () => assertSurface({}, leaf));
negativeControl('C24', 'replacement-export-function', 'ROOT_LEAF_IDENTITY', () => assertSurface(root, { ...leaf, createTimeoutCommand() {} }));
positive('C25', 'leaf-read-without-root', () => assertTypeOutcome(positiveLeaf, consumers[1]));
negativeControl('C26', 'wrong-leaf-entrypoint', 'DECLARATION_ENTRYPOINT', () => assertTypeOutcome({ ...positiveLeaf, authenticatedReads: ['dist/index.d.ts'] }, consumers[1]));
negativeControl('C27', 'root-read-missing', 'DECLARATION_ENTRYPOINT', () => assertTypeOutcome(positiveLeaf, consumers[0]));
negativeControl('C28', 'type-source-fallback', 'TYPE_SOURCE_FALLBACK', () => assertTypeOutcome({ ...positiveLeaf, sourceFallback: true }, consumers[1]));
negativeControl('C29', 'unrelated-diagnostic', 'TYPE_DIAGNOSTIC_TOKEN', () => { const value = clone(negative); value.diagnostics[0].token = 'unrelated'; assertTypeOutcome(value, consumers[3]); });
positive('C30', 'intended-negative-type', () => assertTypeOutcome(negative, consumers[3]));
negativeControl('C31', 'extra-diagnostic', 'TYPE_DIAGNOSTIC_COUNT', () => assertTypeOutcome({ ...negative, diagnostics: [...negative.diagnostics, ...negative.diagnostics] }, consumers[3]));
negativeControl('C32', 'public-commit-mismatch', 'PUBLIC_COMMIT', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, { ...declaration, public: declaration.public.map(row => ({ ...row, commit: baseline })) }));
negativeControl('C33', 'undeclared-public-path', 'PUBLIC_PATHS', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, { ...declaration, public: [...declaration.public, bindings.selectedInputs[0]] }));
negativeControl('C34', 'unbound-declaration', 'UNBOUND_DECLARATION', () => assertTypeOutcome({ ...positiveLeaf, unboundReads: 1 }, consumers[1]));
negativeControl('C35', 'wrong-diagnostic-meaning', 'TYPE_DIAGNOSTIC_MEANING', () => { const value = clone(negative); value.diagnostics[0].message = 'Missing library file'; assertTypeOutcome(value, consumers[3]); });
negativeControl('C36', 'public-mode-change', 'PUBLIC_MODE', () => assertComposition(bindings.selectedInputs, bindings.selectedInputs, { ...declaration, public: declaration.public.map(row => ({ ...row, mode: '100755' })) }));
assert.equal(controls.length, manifest.syntheticControls);
const outcomes = [];
for (const row of controls) {
  try { row.execute(); outcomes.push({ id: row.id, name: row.name, expectation: row.expectation, status: 'PASS' }); }
  catch (error) { outcomes.push({ id: row.id, name: row.name, expectation: row.expectation, status: 'FAIL', error: { name: error.name, code: error.code, message: error.message, stack: error.stack } }); }
}
const guardFailures = [];
for (const row of [...bindings.protectedFiles, ...bindings.tools]) if (sha(read(row.path)) !== row.sha256) guardFailures.push(row.path);
for (const row of manifest.files) if (sha(local(row.path)) !== row.sha256) guardFailures.push(row.path);
const result = { schema: 'timeout-public-freeze-validation/1', completedAt: new Date().toISOString(), manifestSha256: sha(manifestBytes), node: process.version, outcomes, passed: outcomes.filter(row => row.status === 'PASS').length, failed: outcomes.filter(row => row.status === 'FAIL').length, guardFailures, protectedFiles: bindings.protectedFiles.length, children: 0, pendingResources: 0, publicCandidate: null, actualPublicCases: 0, actualPublicTypes: 0, productImports: 0, actualBuilds: 0, native: 0, safeJS: 0, retries: 0 };
fs.writeFileSync(resolve(here, 'VALIDATION.json'), JSON.stringify(result, null, 2) + '\n', { flag: 'wx' });
const files = ['validation.lock','VALIDATION.json'].map(path => ({ path, sha256: sha(local(path)), bytes: local(path).length }));
fs.writeFileSync(resolve(here, 'VALIDATION-SEAL.json'), JSON.stringify({ schema: 'timeout-public-freeze-validation-seal/1', manifestSha256: sha(manifestBytes), files }, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify(result));
if (result.failed || guardFailures.length) process.exitCode = 1;
