import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const scope='/Users/kjopek/Workspace/safe-bash/tests/integration/agent-bash-coherent-author-20260829/stage-a-r2',work='/private/tmp/safe-bash-coherent-stage-a-20260829-r2';
const sha=body=>crypto.createHash('sha256').update(body).digest('hex');
function read(filename,maximum,expected){const before=fs.lstatSync(filename);assert.ok(before.isFile()&&!before.isSymbolicLink()&&before.size<=maximum);if(expected)assert.equal(before.size,expected.bytes);const fd=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const initial=fs.fstatSync(fd);assert.equal(initial.dev,before.dev);assert.equal(initial.ino,before.ino);const body=Buffer.alloc(before.size);let offset=0;while(offset<body.length){const count=fs.readSync(fd,body,offset,body.length-offset,offset);assert.ok(count>0);offset+=count;}assert.equal(fs.fstatSync(fd).mtimeMs,before.mtimeMs);if(expected)assert.equal(sha(body),expected.sha256);return body;}finally{fs.closeSync(fd);}}
const sealBytes=read(path.join(scope,'PRESEAL.json'),65536,{bytes:47291,sha256:'8acc5e35686a4fa20bf1f8a871b2c23edff4cb29b09a9b9f1848ffc1332006db'}),seal=JSON.parse(sealBytes);
for(const row of seal.inputs)read(path.join(scope,row.path),65536,row);
const outputReceipt=JSON.parse(read(path.join(work,'PACKAGE-OUTPUT-RECEIPT.json'),65536));assert.equal(outputReceipt.bytes,930368);assert.equal(outputReceipt.sha256,'2fe071e2bfac5ef5c81dc7e475e059091f6add65cd7411dfcfbf0ce7f51f2eca');assert.equal(outputReceipt.presealSha256,sha(sealBytes));assert.equal(outputReceipt.producerClosed,true);
const rawPackage=read(outputReceipt.path,16777216,outputReceipt);
const result=JSON.parse(read(path.join(work,'RESULT.json'),65536));assert.equal(result.actualMembers,1014);assert.equal(result.productionBuilds,1);assert.equal(result.sourceAndToolPostguards,true);
const events=read(path.join(work,'capture/events.jsonl'),65536).toString().trim().split('\n').map(line=>JSON.parse(line));const children=events.filter(row=>row.spawned).map(row=>{const exit=events.find(item=>item.pid===row.pid&&item.event==='exit'),close=events.find(item=>item.pid===row.pid&&item.event==='close'),group=events.find(item=>item.pid===row.pid&&item.groupAbsent===true);assert.ok(exit&&close&&group);assert.equal(exit.status,0);assert.equal(close.status,0);assert.equal(exit.signal,null);assert.equal(close.signal,null);return{role:row.role,pid:row.pid,args:row.args,cwd:row.cwd,exitStatus:exit.status,closeStatus:close.status,groupAbsent:true,stdoutBytes:close.stdoutBytes,stderrBytes:close.stderrBytes};});assert.equal(children.length,4);assert.equal(events.filter(row=>row.signal).length,0);
const admitted=events.find(row=>row.packageAdmittedBeforeInflate===true);assert.ok(admitted);assert.equal(admitted.sha256,outputReceipt.sha256);
const destination=path.join(scope,'evidence');fs.mkdirSync(destination);fs.mkdirSync(path.join(destination,'package'));
fs.writeFileSync(path.join(destination,'package/virtual-bash-0.0.0.tgz'),rawPackage,{flag:'wx',mode:420});
const records=[{path:'package/virtual-bash-0.0.0.tgz',bytes:rawPackage.length,sha256:sha(rawPackage)}];
const names=['ROOT-IDENTITY.json','SOURCE-BEFORE.json','TOOLS-BEFORE.json','EMITTED.json','PACKAGE-OUTPUT-RECEIPT.json','PACKAGE-MEMBERS.json','RESULT.json',...fs.readdirSync(path.join(work,'capture')).map(name=>'capture/'+name)];
for(const name of names){assert.ok(!name.includes('..'));const body=read(path.join(work,name),16777216);const target=path.join(destination,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,body,{flag:'wx'});records.push({path:name,bytes:body.length,sha256:sha(body)});}
const sourceBytes=read(seal.source.path,1048576,seal.source);fs.writeFileSync(path.join(destination,'SELECTED-SOURCE.json'),sourceBytes,{flag:'wx'});records.push({path:'SELECTED-SOURCE.json',bytes:sourceBytes.length,sha256:sha(sourceBytes)});
const members=JSON.parse(read(path.join(work,'PACKAGE-MEMBERS.json'),1048576));assert.deepEqual(members.map(row=>row.path).sort(),seal.expectedMembers);assert.equal(new Set(members.map(row=>row.path)).size,1014);
const bindings={role:'PRODUCER_ONLY_ARTIFACT_BINDINGS_NOT_RUNTIME_LOAD_OBSERVATION',sourceTree:seal.sourceTree,sourceInputs:309,sourceManifestSha256:sha(sourceBytes),fixtureSealSha256:seal.fixtureSealSha256,presealSha256:sha(sealBytes),package:records[0],actualMembers:1014,emittedFiles:1012,producerReceiptCreated:outputReceipt.created,sourceAndToolPostguards:true,sealedHarnessPostguardAtPublication:true,children,signals:0,sourceInputsFromMutableHead:false,records,productImports:0,semanticCalls:0,stageB:'UNRUN_FRESH_REVIEW_AND_GO_REQUIRED',public95:'Not loaded/copied; later sidecar3681c910 remains separate',runtimeLoadTrace:'NONE: manifests are prospective StageB admission data, not observed product loads',published:new Date().toISOString()};
fs.writeFileSync(path.join(scope,'BINDINGS.json'),JSON.stringify(bindings,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({package:bindings.package,actualMembers:1014,emittedFiles:1012,children:children.map(row=>({role:row.role,pid:row.pid,exit:row.exitStatus,close:row.closeStatus,groupAbsent:row.groupAbsent})),bindingsSha256:sha(read(path.join(scope,'BINDINGS.json'),1048576)),evidenceFiles:records.length,stageB:bindings.stageB}));
