import {exact} from './data-support.mjs';
const keys=['schema','id','layout','pass','assertions','primary','cleanup','expectedCleanupFailure','testOwnerRetired','subjectClean','WorkerAttempts','WorkerStarts','WorkerOnline','WorkerRetired','stdoutDrained','stderrDrained','unknownAcquisitions','unknownRetirements','captureFault','WorkerExits','requests','testRescues','loads','nestedLoads','trace','diagnosticIdentityClaim'];
function integer(value,max){if(!Number.isSafeInteger(value)||value<0||value>max)throw Error('finite count');}
function vector(value,max){if(!Array.isArray(value)||value.length>max)throw Error('finite vector');const own=Reflect.ownKeys(value);if(own.length!==value.length+1)throw Error('vector extras/holes');for(let index=0;index<value.length;index++){const row=Object.getOwnPropertyDescriptor(value,String(index));if(!row||!Object.hasOwn(row,'value'))throw Error('vector data');}return value;}
function reason(value){if(value===null||typeof value!=='object'||Array.isArray(value))throw Error('reason record');const own=Reflect.ownKeys(value);if(own.length>7)throw Error('reason keys');for(const key of own){if(!['present','kind','value','name','message','code','resource'].includes(key))throw Error('reason key');const field=Object.getOwnPropertyDescriptor(value,key);if(!field||!Object.hasOwn(field,'value'))throw Error('reason getter');if(typeof field.value==='string'&&Buffer.byteLength(field.value)>1024)throw Error('reason text');if(field.value!==null&&!['boolean','number','string'].includes(typeof field.value))throw Error('reason data');}if(typeof value.present!=='boolean')throw Error('reason presence');if(!value.present&&own.length!==1)throw Error('absent reason');}
export function judge(receipt,observed,config){
 exact(receipt,keys);if(receipt.schema!==1||receipt.id!==config.id||receipt.layout!==config.layout)throw Error('receipt identity');
 for(const name of ['pass','assertions','expectedCleanupFailure','testOwnerRetired','subjectClean','captureFault','diagnosticIdentityClaim'])if(typeof receipt[name]!=='boolean')throw Error('receipt boolean');reason(receipt.primary);reason(receipt.cleanup);
 for(const name of ['WorkerAttempts','WorkerStarts','WorkerOnline','WorkerRetired','stdoutDrained','stderrDrained','unknownAcquisitions','unknownRetirements','WorkerExits','testRescues'])integer(receipt[name],1);integer(receipt.requests,config.requestCeiling);
 if(!observed.closed||observed.signal!==null||observed.primary.present||observed.secondary.length||!observed.stdoutClosed||!observed.stderrClosed)throw Error('outer ownership');if(receipt.captureFault||receipt.unknownAcquisitions||receipt.unknownRetirements||!receipt.testOwnerRetired)throw Error('unknown Worker retirement');
 if(receipt.WorkerStarts!==receipt.WorkerAttempts||receipt.WorkerStarts!==receipt.WorkerRetired||receipt.WorkerStarts!==receipt.WorkerExits||receipt.WorkerStarts!==receipt.stdoutDrained||receipt.WorkerStarts!==receipt.stderrDrained||receipt.WorkerOnline>receipt.WorkerStarts)throw Error('Worker contradiction');
 const trace=vector(receipt.trace,512);const counts={attempt:0,constructed:0,online:0,exit:0,retired:0};for(const row of trace){if(row===null||typeof row!=='object'||Array.isArray(row))throw Error('trace record');const own=Reflect.ownKeys(row);if(own.length>4)throw Error('trace keys');for(const key of own){const field=Object.getOwnPropertyDescriptor(row,key);if(!field||!Object.hasOwn(field,'value')||!['string','number','boolean'].includes(typeof field.value))throw Error('trace own data');}const fields={attempt:['kind'],constructed:['kind','threadId'],online:['kind'],exit:['kind','code'],retired:['kind'],post:['kind','number','id'],message:['kind','number'],error:['kind','present'],terminationRequested:['kind'],stdoutEnd:['kind'],stdoutClose:['kind'],stderrEnd:['kind'],stderrClose:['kind']}[row.kind];if(!fields)throw Error('trace kind');exact(row,fields);if(Object.hasOwn(counts,row.kind))counts[row.kind]++;}for(const [event,name]of [['attempt','WorkerAttempts'],['constructed','WorkerStarts'],['online','WorkerOnline'],['exit','WorkerExits'],['retired','WorkerRetired']])if(counts[event]!==receipt[name])throw Error('trace count');
 for(const rows of [vector(receipt.loads,32),vector(receipt.nestedLoads,16)])for(const row of rows){exact(row,['name','sha256']);if(typeof row.name!=='string'||row.name.length>240||typeof row.sha256!=='string'||!/^[a-f0-9]{64}$/.test(row.sha256))throw Error('load row');}
 const seen=new Set();for(const row of receipt.loads){const bound=config.modules.find(item=>item.path===row.name);if(!bound||bound.sha256!==row.sha256||seen.has(row.name))throw Error('loaded module binding');seen.add(row.name);}for(const name of ['root.js','accounting.js','validation.js'])if(!receipt.loads.some(row=>row.name===config.packageRelative+'/ere/transport/'+name))throw Error('required actual parent load');if(receipt.diagnosticIdentityClaim)throw Error('serialized identity claim');const expectedCleanup=config.id==='L08/termination-rejects-undefined';if(receipt.expectedCleanupFailure!==expectedCleanup||receipt.testRescues!==(expectedCleanup?1:0)||receipt.subjectClean===receipt.cleanup.present)throw Error('cleanup contradiction');
 if(receipt.pass){if(observed.code!==0||!receipt.assertions||receipt.primary.present||receipt.WorkerStarts!==config.Workers)throw Error('false PASS');if(expectedCleanup){if(!receipt.cleanup.present||receipt.cleanup.kind!=='undefined')throw Error('cleanup undefined');}else if(receipt.cleanup.present)throw Error('unexpected cleanup');}else if(observed.code!==1)throw Error('nonpass exit');
 return Object.freeze({pass:receipt.pass,ordinaryFailure:!receipt.pass,knownRetired:true});
}
