export const nativeCases = [
  { id: 'source-state', script: 'value=old; source ./unit.sh; show; printf "%s:%s\\n" "$value" "$PWD"; bash -c \'printf "%s:%s\\n" "$EXPORTED" "${value-unset}"\'; printf effect > effect.txt', files: { 'unit.sh': 'value=new; export EXPORTED=visible; cd work; show() { printf "function\\n"; }\n' } },
  { id: 'dot-state', script: 'value=old; . ./unit.sh; show; printf "%s:%s\\n" "$value" "$PWD"; bash -c \'printf "%s\\n" "$EXPORTED"\'', files: { 'unit.sh': 'value=dot; export EXPORTED=dot-export; cd work; show() { printf "dot-function\\n"; }\n' } },
  { id: 'eval-state', script: 'value=old; eval \'value=eval; export EXPORTED=eval-export; cd work; show() { printf "eval-function\\n"; }\'; show; printf "%s:%s\\n" "$value" "$PWD"; bash -c \'printf "%s\\n" "$EXPORTED"\'; printf effect > effect.txt' },
  { id: 'source-status-sequence', script: 'false; source ./empty.sh; printf "empty:%s\\n" "$?"; source ./unit.sh; printf "source:%s\\n" "$?"; printf after', files: { 'empty.sh': '', 'unit.sh': 'printf before; false\n' } },
  { id: 'eval-join-empty-status', script: 'false; eval; printf "empty:%s\\n" "$?"; eval "printf" "\'%s:%s\\n\'" "one" "two"; eval false; printf "false:%s\\n" "$?"; eval ""; printf "blank:%s\\n" "$?"' },
  { id: 'source-noargs-positionals', script: 'set -- outer first; source ./unit.sh; printf "after:%s:%s:%s\\n" "$#" "$1" "$2"', files: { 'unit.sh': 'printf "inside:%s:%s:%s\\n" "$#" "$1" "$2"; set -- changed second third\n' } },
  { id: 'source-args-restoration', script: 'set -- outer first; . ./unit.sh "inner one" inner2; printf "after:%s:%s:%s\\n" "$#" "$1" "$2"', files: { 'unit.sh': 'printf "inside:%s:%s:%s\\n" "$#" "$1" "$2"; shift; set -- changed; return 7\n' } },
  { id: 'source-function-positionals', script: 'set -- top; call() { source ./unit.sh inner two; printf "function:%s:%s\\n" "$#" "$1"; }; call function-arg; printf "top:%s:%s\\n" "$#" "$1"', files: { 'unit.sh': 'printf "source:%s:%s\\n" "$#" "$1"; shift; return 4\n' } },
  { id: 'zero-source-eval', script: String.raw`bash -c 'printf "entry:%s\n" "$0"; source ./unit.sh source-arg; eval '\''printf "eval:%s:%s\n" "$0" "$1"'\''; printf "end:%s:%s\n" "$0" "$1"' cohort-zero outer`, files: { 'unit.sh': 'printf "source:%s:%s\\n" "$0" "$1"\n' } },
  { id: 'source-return', script: 'source ./unit.sh; printf "after:%s\\n" "$?"', files: { 'unit.sh': 'printf before; return 13; printf forbidden\n' } },
  { id: 'eval-return-function', script: 'call() { eval \'printf before; return 14; printf forbidden\'; printf forbidden2; }; call; printf "after:%s\\n" "$?"' },
  { id: 'nested-source-return', script: 'source ./outer.sh; printf "top:%s\\n" "$?"', files: { 'outer.sh': 'source ./inner.sh; printf "outer:%s\\n" "$?"; return 9\n', 'inner.sh': 'printf inner; return 8; printf forbidden\n' } },
  { id: 'eval-return-source', script: '. ./unit.sh; printf "top:%s\\n" "$?"', files: { 'unit.sh': 'eval \'printf inside; return 15; printf forbidden\'; printf forbidden2\n' } },
  { id: 'function-return-source-continues', script: 'source ./unit.sh; printf "top:%s\\n" "$?"', files: { 'unit.sh': 'call() { return 6; }; call; printf "source:%s\\n" "$?"; printf continued\n' } },
  { id: 'source-exit-function', script: 'call() { . ./unit.sh; printf forbidden; }; call; printf forbidden2', files: { 'unit.sh': 'printf exiting; exit 23\n' } },
  { id: 'eval-exit-nested-source', script: 'source ./outer.sh; printf forbidden', files: { 'outer.sh': '. ./inner.sh; printf forbidden2\n', 'inner.sh': 'eval \'printf exiting; exit 24\'\n' } },
  { id: 'source-path-precedence', script: 'PATH="$PWD/search:$PATH"; source unit.sh; printf "%s\\n" "$chosen"', files: { 'unit.sh': 'chosen=cwd\n', 'search/unit.sh': 'chosen=path\n' } },
  { id: 'source-direct-and-cwd-fallback', script: 'source unit.sh; printf "%s\\n" "$chosen"; . ./search/unit.sh; printf "%s\\n" "$chosen"', files: { 'unit.sh': 'chosen=cwd\n', 'search/unit.sh': 'chosen=direct\n' } },
  { id: 'source-missing', script: 'source ./missing.sh; printf "after:%s\\n" "$?"' },
  { id: 'source-directory', script: '. ./work; printf "after:%s\\n" "$?"' },
  { id: 'source-syntax-error', script: 'source ./unit.sh; printf "after:%s\\n" "$?"', files: { 'unit.sh': 'printf before\nif\n' } },
  { id: 'eval-syntax-error', script: 'eval \'printf before\nif\'; printf "after:%s\\n" "$?"' },
  { id: 'source-eval-utf8', script: '. ./żółć.sh; eval \'printf "%s\\n" "$word"\'; printf "%s" "$word" > utf8.txt', files: { 'żółć.sh': 'word="żółć 雪 🐚"; printf "%s\\n" "$word"\n' } },
  { id: 'source-eval-descriptors', script: 'source ./unit.sh > captured.txt 2> errors.txt; eval \'printf eval-out; printf eval-err >&2\' >> captured.txt 2>> errors.txt; printf top; printf top-err >&2', files: { 'unit.sh': 'printf source-out; printf source-err >&2\n' } },
  { id: 'source-shared-input-eof', script: 'source ./unit.sh; cat; printf end', stdin: 'first\nsecond\n', files: { 'unit.sh': 'cat; printf source-end\n' } },
  { id: 'eval-shared-input-eof', script: 'eval \'cat; printf eval-end\'; cat; printf end', stdin: 'first\nsecond\n' },
  { id: 'bash-child-isolation', script: 'value=parent; bash -c \'source ./unit.sh; show; printf "%s\\n" "$PWD"\'; printf "%s:%s\\n" "$value" "$PWD"; show', files: { 'unit.sh': 'value=child; cd work; show() { printf child-function; }\n' } },
  { id: 'subshell-isolation', script: 'value=parent; ( . ./unit.sh; eval \'value=eval-child\'; printf "%s:%s\\n" "$value" "$PWD" ); printf "%s:%s\\n" "$value" "$PWD"', files: { 'unit.sh': 'value=source-child; cd work\n' } },
  { id: 'pipeline-isolation', script: 'value=parent; source ./unit.sh | cat; printf "%s:%s\\n" "$value" "$PWD"; eval \'value=pipe-eval; printf eval-pipe\' | cat; printf "%s\\n" "$value"', files: { 'unit.sh': 'value=pipe-source; cd work; printf source-pipe\n' } },
  { id: 'sh-profile-dot', script: String.raw`sh -c '. ./unit.sh; eval '\''printf "%s:%s\n" "$value" "$0"'\''' sh-zero`, files: { 'unit.sh': 'value=sh-dot\n' } },
  { id: 'sh-profile-missing-fatal', script: 'sh -c \'. ./missing.sh; printf forbidden\' sh-zero; printf "parent:%s\\n" "$?"' },
  { id: 'nested-eval-expansion', script: 'value=one; code=\'printf "%s\\n" "$value"\'; value=two; eval "$code"; eval \'eval "$code"; value=three\'; printf "%s\\n" "$value"' },
];

export const hostCases = [
  { id: 'source-provenance-cursor', kind: 'provenance', operation: 'source' },
  { id: 'eval-provenance-cursor', kind: 'provenance', operation: 'eval' },
  { id: 'source-acquisition-cancellation', kind: 'cancel-source' },
  { id: 'eval-command-cancellation', kind: 'cancel-eval' },
  { id: 'source-byte-budget', kind: 'limit', script: 'source ./budget.sh; source ./budget.sh', files: { 'budget.sh': ':\n'.repeat(32) }, limit: 'maxSourceBytes', value: 110 },
  { id: 'eval-byte-budget', kind: 'limit', script: "eval ':; :; :; :'; eval ':; :; :; :'", limit: 'maxSourceBytes', value: 47 },
  { id: 'mixed-command-budget', kind: 'limit', script: ':; source ./budget.sh; eval ":; :; :"', files: { 'budget.sh': ':; :; :\n' }, limit: 'maxCommands', value: 7 },
  { id: 'mixed-loop-budget', kind: 'limit', script: 'for item in a b; do :; done; source ./budget.sh; eval "for item in e f; do :; done"', files: { 'budget.sh': 'for item in c d; do :; done\n' }, limit: 'maxLoopIterations', value: 5 },
  { id: 'mixed-output-budget', kind: 'limit', script: 'printf 1234; source ./budget.sh; eval "printf 90AB"', files: { 'budget.sh': 'printf 5678\n' }, limit: 'maxOutputBytes', value: 10 },
  { id: 'source-depth-budget', kind: 'limit', script: 'source ./budget.sh', files: { 'budget.sh': 'source ./budget.sh\n' }, limit: 'maxSubstitutionDepth', value: 4 },
  { id: 'eval-depth-budget', kind: 'limit', script: 'code=\'eval "$code"\'; eval "$code"', limit: 'maxSubstitutionDepth', value: 4 },
];
