import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { gunzipSync } from 'node:zlib';

const scope = dirname(fileURLToPath(import.meta.url));
const root = resolve(scope, '../../../..');
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const git = args => execFileSync('git', args, { cwd: root, timeout: 10000, maxBuffer: 16 * 1024 * 1024 });
const show = (commit, path) => git(['show', `${commit}:${path}`]);
const historicalCommit = 'eb602376d11f9d19cd22864027fe51f564944381';
const migrationCommit = '4fa20ac6cadb9d37fa9da4d205dc37a5a1bcb9f9';
const parentCommit = 'a95a10c970fe18f2039cbd90ca189bb53c560e26';
const auditCommit = '8cafed9bff7a8df1cf49b4ff4ef3ee021229ae3c';
const inspectedCommit = git(['rev-parse', 'HEAD']).toString().trim();
const baselinePath = 'benchmarks/shell-stress/diagnostic-profiles/native-baseline.json';
const baselineBytes = show(historicalCommit, baselinePath);
assert.equal(hash(baselineBytes), '0cb9d0b498331434ec2a49dd4f75b30dcfb10db2ff8fd029613d948f119d4cf3');
assert.deepEqual(readFileSync(join(root, baselinePath)), baselineBytes);
const baseline = JSON.parse(baselineBytes);
const driverPaths = ['tests/shell-stress/differential.test.ts', 'tests/shell-stress/current-gaps/compatibility.test.ts'];
const expectedCurrent = ['59027400ad1ea3741e652c49a50b03e076bb2672bc2c24cbee5c994caef1ec32', 'ddf404839fae525ae5ebc6d4241c09be307b4ab9359c099d7f7dac67e2c975ca'];
const drivers = driverPaths.map((path, index) => {
  const historical = show(historicalCommit, path);
  const current = show(migrationCommit, path);
  assert.equal(hash(historical), baseline.sources[path]);
  assert.deepEqual(show(parentCommit, path), historical);
  assert.deepEqual(show(inspectedCommit, path), current);
  assert.deepEqual(readFileSync(join(root, path)), current);
  assert.equal(hash(current), expectedCurrent[index]);
  return { path, historicalCommit, historicalSha256: hash(historical), historicalBytes: historical.length, parentCommit, migrationCommit, currentSha256: hash(current), currentBytes: current.length, historicalBlob: git(['rev-parse', `${historicalCommit}:${path}`]).toString().trim(), currentBlob: git(['rev-parse', `${migrationCommit}:${path}`]).toString().trim() };
});
const delta = git(['diff', historicalCommit, migrationCommit, '--', ...driverPaths]);
const auditRoot = 'tests/integration/current-type-diagnostics-20260827/evidence/audit';
assert.deepEqual(delta, show(auditCommit, `${auditRoot}/diagnostic-pin-migration.diff`));
assert.equal(hash(delta), '10aa629424a59a4c308cef544de051099a5b2e448b89f600b140c51a95accaf1');
writeFileSync(join(scope, 'driver-delta.diff'), delta, { flag: 'wx' });
const testInputs = Object.entries(baseline.sources).filter(([path]) => path.startsWith('tests/')).map(([path, historicalSha256]) => ({ path, historicalSha256, currentSha256: hash(readFileSync(join(root, path))) }));
assert.equal(testInputs.length, 14);
assert.deepEqual(testInputs.filter(row => row.historicalSha256 !== row.currentSha256).map(row => row.path), driverPaths);

const referenceRoot = 'tests/shell-stress/canonical-profile-migration';
const referenceFiles = ['primary-reference.ts', 'primary-fixtures.json', 'native.json'].map(name => {
  const path = `${referenceRoot}/${name}`;
  const bytes = show(migrationCommit, path);
  assert.deepEqual(readFileSync(join(root, path)), bytes);
  return { path, sha256: hash(bytes), bytes: bytes.length };
});
assert.equal(referenceFiles[1].sha256, '76204fc288836d2cde65156ee2d2f610d9ac31466414cc4ef2ec520284d72ec8');
assert.equal(referenceFiles[2].sha256, 'de379916112faa3cec68f3180b5ba55758eda415f2016456d448f635c9871bf5');
const metadata = JSON.parse(readFileSync(join(root, referenceFiles[1].path)));
const capture = JSON.parse(readFileSync(join(root, referenceFiles[2].path)));
assert.equal(metadata.sourceCommit, '6e3e3165e3b88aa5518eac33afd0b2ecdfa5fd2a');
assert.equal(metadata.profile, 'GNU5.3-primary');
assert.equal(metadata.invocationName, 'shell');
assert.equal(metadata.nativeCaptureSha256, referenceFiles[2].sha256);
const historicalRows = baseline.captures.find(entry => entry.profile === 'primary-5.3' && entry.argv0 === 'shell' && entry.repetition === 1).rows;
assert.deepEqual(metadata.fixtures.map(row => row.fixture), historicalRows.map(row => row.fixture));
const referenceRows = capture.rows.filter(row => row.profile === metadata.profile && row.invocationName === metadata.invocationName);
assert.equal(referenceRows.length, 88);
for (const [index, row] of referenceRows.entries()) {
  const original = historicalRows[index];
  assert.equal(row.name, original.fixture.name);
  assert.equal(row.source, original.fixture.script);
  assert.equal(row.sourceSha256, hash(original.fixture.script));
  assert.equal(row.inputHex, Buffer.from(original.fixture.stdin ?? '').toString('hex'));
  assert.deepEqual(row.args, original.args);
  const files = Object.fromEntries(Object.entries(row.after).map(([path, entry]) => [path, entry.type === 'directory' ? { type: 'directory' } : { type: 'file', base64: Buffer.from(entry.hex, 'hex').toString('base64') }]));
  assert.deepEqual({ stdoutBase64: Buffer.from(row.stdoutHex, 'hex').toString('base64'), stderrBase64: Buffer.from(row.stderrHex, 'hex').toString('base64'), exitCode: row.status, files }, { stdoutBase64: original.observation.stdoutBase64, stderrBase64: original.observation.stderrBase64, exitCode: original.observation.exitCode, files: original.observation.files });
}

const auditBytes = show(auditCommit, `${auditRoot}/hash-guards.json`);
assert.equal(hash(auditBytes), '519920488ea089f411983da490d70ba5b65402c7d7cc5be95cce2fe9aaac8aa0');
const failedRows = JSON.parse(auditBytes).failedRows.filter(row => row.group === 'historical-diagnostic-pin');
assert.equal(failedRows.length, 89);
const reportCommit = '954406871fae381b1c69441b34946a224201d7ad';
const reportRoot = 'tests/integration/full-gate-20260827/combined-b494675c';
const manifestBytes = show(reportCommit, `${reportRoot}/EVIDENCE_MANIFEST.json`);
const entry = JSON.parse(manifestBytes).captures.find(entry => entry.key === 'canonical/test.stdout.log');
const stored = show(reportCommit, `${reportRoot}/${entry.path}`);
assert.equal(hash(stored), entry.storedSha256);
const original = gunzipSync(Buffer.from(stored.toString().trim(), 'base64'));
assert.equal(hash(original), entry.originalSha256);
assert.equal(original.length, entry.originalBytes);
const lineStarts = [0];
for (let offset = original.indexOf(10); offset !== -1; offset = original.indexOf(10, offset + 1)) lineStarts.push(offset + 1);
const excerptBlocks = [];
const excerpts = failedRows.map(row => {
  const line = Number(row.id.replace('tap-line-', ''));
  const start = lineStarts[line - 2];
  const stop = original.indexOf(Buffer.from('\n  ...\n'), start) + 7;
  assert.ok(stop > start);
  const bytes = original.subarray(start, stop);
  assert.ok(bytes.toString().startsWith(`# Subtest: ${row.name}\nnot ok `));
  assert.ok(bytes.includes(Buffer.from("failureType: 'hookFailed'")));
  excerptBlocks.push(bytes);
  return { ...row, start, stop, bytes: bytes.length, sha256: hash(bytes) };
});
const excerpt = Buffer.concat(excerptBlocks);
writeFileSync(join(scope, 'original-89.tap'), excerpt, { flag: 'wx' });
const result = { authenticatedAt: new Date().toISOString(), inspectedCommit, historicalCommit, migrationCommit, parentCommit, auditCommit, drivers, baseline: { path: baselinePath, sha256: hash(baselineBytes), profiles: baseline.profiles }, deltaSha256: hash(delta), testInputs, referenceFiles, profileFacts: { siblingOracleChanged: true, old: { executable: '/bin/bash', invocationName: 'shell-stress' }, current: { sourceCommit: metadata.sourceCommit, profile: metadata.profile, invocationName: metadata.invocationName, binarySha256: metadata.binarySha256, liveNativeExecution: false }, fixtureCrosswalk: 88, sealedTupleCrosswalk: 88, modesNotCompared: true, diagnosticNativeProfilesUnchanged: true }, originalFailureEvidence: { auditSha256: hash(auditBytes), reportCommit, manifestSha256: hash(manifestBytes), capture: entry, excerptSha256: hash(excerpt), excerpts } };
writeFileSync(join(scope, 'authentication.json'), `${JSON.stringify(result, null, 2)}\n`, { flag: 'wx' });
console.log(JSON.stringify({ drivers: drivers.length, unchangedPins: 12, sealedTupleCrosswalk: 88, originalHookFailures: excerpts.length }));
