import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.dirname(new URL(import.meta.url).pathname);
const capture=fs.openSync(root+'/REVIEW-r3.capture.data','wx',0o600);
const log=row=>fs.writeSync(capture,JSON.stringify(row)+'\n');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const assert=(value,message)=>{if(!value)throw Error(message);};
const results=[];const began=Date.now();
try{
 log({event:'START',at:began,children:0,role:'DATA_ONLY'});
 const manifest=JSON.parse(fs.readFileSync(root+'/evidence/MANIFEST.json'));
 const source=JSON.parse(fs.readFileSync(root+'/source/MANIFEST.json'));
 const oldManifest=JSON.parse(fs.readFileSync(root+'/../v2/evidence/MANIFEST.json'));
 const read=(name,old=false)=>{const inventory=old?oldManifest:manifest;const row=inventory.rows.find(row=>row.path.endsWith('/'+name));assert(row,'MISSING '+name);const bytes=fs.readFileSync((old?root+'/../v2':root)+'/evidence/'+row.capture);assert(hash(bytes)===row.sha256&&bytes.length===row.bytes,'INPUT_INTEGRITY '+name);return bytes;};
 const json=(name,old=false)=>JSON.parse(read(name,old));
 const sealBytes=read('PRESEAL.json');assert(sealBytes.length===5602&&hash(sealBytes)==='ffee6eafb226ead4f9a15351c2964693971dfff7004b0d96cd6f9d0ca6098533','ROOT_PRESEAL_BINDING');
 const seal=JSON.parse(sealBytes);for(const pin of seal.files){const bytes=read(pin.path);assert(['source-commit','author-evidence'].includes(pin.role),'ROLE');const authority=pin.role==='source-commit'?source:manifest;const stored=authority.rows.find(row=>row.path.endsWith('/'+pin.path));assert(bytes.length===pin.bytes&&hash(bytes)===pin.sha256&&stored?.sha256===pin.sha256&&stored.bytes===pin.bytes&&(parseInt(stored.mode,8)&511)===pin.mode,'SOURCE_SEAL '+pin.path);}
 fs.mkdirSync(root+'/modules-r3');const bindings=[];
 for(const name of ['storage.mjs','state.mjs','admission.mjs','data-controls.mjs']){const bytes=read(name);fs.writeFileSync(root+'/modules-r3/'+name,bytes,{flag:'wx'});bindings.push({path:'modules-r3/'+name,bytes:bytes.length,sha256:hash(bytes),role:'EXACT_DATA_HELPER'});}
 for(const name of ['review-r3.mjs','CONTROL-PRESEAL.md']){const bytes=fs.readFileSync(root+'/'+name);bindings.push({path:name,bytes:bytes.length,sha256:hash(bytes),role:'REVIEW_SOURCE'});}
 fs.writeFileSync(root+'/CONTROL-SEAL-r3.json',JSON.stringify({bindings,author:6,novelGroups:6,nestedChildren:0},null,2)+'\n',{flag:'wx'});
 const {runDataControls}=await import('./modules-r3/data-controls.mjs');
 const {Storage}=await import('./modules-r3/storage.mjs');
 const {creditObservation}=await import('./modules-r3/state.mjs');
 const {validateReview,validateStartupScope,startupScope,admit}=await import('./modules-r3/admission.mjs');
 const authorEnvelope=runDataControls();log({event:'AUTHOR_RETURNED',value:authorEnvelope});assert(JSON.stringify(Object.keys(authorEnvelope))===JSON.stringify(['schema','identities','matched','actualChildStarts','entryImported','qualification'])&&authorEnvelope.schema==='functional-reference-v3-data-results'&&authorEnvelope.matched===6&&authorEnvelope.actualChildStarts===0&&authorEnvelope.entryImported===false&&authorEnvelope.qualification==='SYNTHETIC_CLOCK_AND_IO_NOT_NATIVE_OR_LIFECYCLE_ACCEPTANCE','AUTHOR_ENVELOPE');const author=authorEnvelope.identities;assert(Array.isArray(author)&&author.length===6&&author.every(row=>row.matched),'AUTHOR_CONTROLS');results.push(...author.map(row=>({...row,role:'UNCHANGED_AUTHOR_DATA_REPLAY'})));log({event:'AUTHOR_DATA',count:author.length});
 const eligible=()=>({id:'NOVEL_DATA',exit:true,close:true,group:{state:'absent'},signal:null,stop:null,errors:[],capture:[{flush:true,size:true,hash:true,close:true},{flush:true,size:true,hash:true,close:true}],filesVerified:true,receiptPublished:true});
 const reason=body=>{try{body();return null;}catch(error){return error;}};
 function mock(now,options={}){const clock={now},calls=[],primary=Error('PRIMARY_IDENTITY'),secondary=Error('SECONDARY_IDENTITY');let closes=0;const operations={openSync(){calls.push('open');if(options.openLate)clock.now=101;return 13;},writeFileSync(){calls.push('write');if(options.writeLate)clock.now=101;if(options.writeError)throw primary;},fsyncSync(){calls.push('flush');},closeSync(){calls.push('close');closes++;if(options.closeAlwaysFails||options.firstCloseFails&&closes===1){if(options.closeLate)clock.now=101;throw secondary;}if(options.closeLate)clock.now=101;}};return {clock,calls,primary,secondary,storage:new Storage('/SYNTHETIC_NEVER_OPENED',{deadline:100},{now:()=>clock.now,terminalOperations:operations})};}
 function check(id,body){try{const detail=body();results.push({id,matched:true,detail});}catch(error){results.push({id,matched:false,error:error.message});}log(results.at(-1));}
 check('N01',()=>{assert(read('AUDIT.json').equals(read('AUDIT.json',true)),'AUDIT_UNCHANGED');const requests=json('REQUESTS.json'),old=json('REQUESTS.json',true);assert(requests.length===37,'37');for(const [index,row]of requests.entries()){assert(row.id===old[index].id&&JSON.stringify(row.argv)===JSON.stringify(old[index].argv)&&row.stdinBase64===old[index].stdinBase64,'EXACT_INPUT');assert(JSON.stringify(row)===JSON.stringify(old[index]).replaceAll('functional-v2-','functional-v3-'),'NAMESPACE_ONLY_REQUEST');}const reusable=['capture.mjs','lifecycle.mjs','group-observer.mjs','observer-state.mjs','TOOLS.json','WRAPPER-TOOL.json','VERSION-PROVENANCE.json'];for(const name of reusable)assert(read(name).equals(read(name,true)),'REUSE '+name);return {sealFiles:seal.files.length,requests:37,literals:40,fixtures:4,reusable:reusable.map(name=>({name,sha256:hash(read(name))})),runtimeReplay:0};});
 check('N02',()=>{const expected={presealSha256:hash(sealBytes),requestsSha256:hash(read('REQUESTS.json'))};const receipt={schema:'functional-reference-independent-acceptance-v3',decision:'ACCEPT',profile:'functional-reference-v3',...expected,reviewer:'SYNTHETIC-DATA-NOT-ROOT',reviewCommit:'a'.repeat(40)};assert(validateReview(receipt,expected),'SYNTHETIC_VALID');assert(validateStartupScope(startupScope),'SCOPE');const callbacks=[()=>validateReview(null,expected),()=>validateReview({...receipt,profile:'functional-reference-v2'},expected),()=>validateReview({...receipt,requestsSha256:'b'.repeat(64)},expected),()=>validateStartupScope(undefined),()=>validateStartupScope('CLEAN_INITIAL_TOOL_SHELL'),()=>admit('/SYNTHETIC', '/WRONG/GO.json','a'.repeat(64)),()=>admit('/SYNTHETIC','/SYNTHETIC/GO.json','ROOT_APPROVED_GRANT_SHA256')];assert(callbacks.every(callback=>reason(callback)!==null),'NEGATIVE_REFUSAL');const protocol=json('PROTOCOL.json'),grant=json('GO.template.json'),template=json('APPROVAL-REQUEST.template.json');assert(grant.startupScope===startupScope&&JSON.stringify(protocol).includes(startupScope)&&template.startupScope.scope===startupScope&&template.parameters.justification.includes('trusted host/outside child'),'POLICY_DISCLOSURE');return {negativeVariants:callbacks.length,scope:startupScope,realGO:false,actualChild:0};});
 check('N03',()=>{const live=mock(75),events=[];live.storage.record=row=>events.push(row);assert(live.storage.terminal({event:'AFTER_BODY_BEFORE_FINAL'})&&creditObservation(eligible(),live.storage,0)===1,'LIVE_FINAL');const serialization=mock(99);const error=reason(()=>serialization.storage.terminal({toJSON(){serialization.clock.now=101;return {event:'LATE_SERIALIZATION'};}}));assert(error?.message==='FINALIZATION_DEADLINE'&&serialization.calls.length===0&&!serialization.storage.terminalState.qualified,'SERIALIZATION_NO_OPEN');const write=mock(99,{writeLate:true});assert(reason(()=>write.storage.terminal({event:'WRITE_CROSSES_DEADLINE'}))?.message==='FINALIZATION_DEADLINE','WRITE_LATE');assert(JSON.stringify(write.calls)===JSON.stringify(['open','write','close'])&&write.storage.terminalState.closed&&!write.storage.terminalState.qualified,'NO_LATE_FLUSH');return {bodyCutoff:50,finalDeadline:100,liveNow:75,liveCalls:live.calls,serializationCalls:serialization.calls,writeCalls:write.calls,noDeadlineReset:true};});
 check('N04',()=>{const test=mock(99,{writeError:true,closeAlwaysFails:true,closeLate:true});assert(reason(()=>test.storage.terminal({event:'FAULT'}))===test.primary,'PRIMARY_IDENTITY');assert(test.storage.terminalState.secondary.filter(row=>row.error===test.secondary).length===2,'SECONDARY_IDENTITIES');assert(!test.storage.terminalState.closed&&!test.storage.terminalState.qualified&&test.storage.terminalState.late,'UNKNOWN_CLOSE_NOT_QUALIFIED');const recordError=Error('RECORD_IDENTITY'),counter={value:0};const storage={checkTime(){},record(){throw recordError;}};assert(reason(()=>{counter.value=creditObservation(eligible(),storage,counter.value);})===recordError&&counter.value===0,'CREDIT_PRIMARY');return {primaryIdentity:true,secondaryIdentities:true,closed:false,qualified:false,late:true,calls:test.calls,counter:counter.value,operationMocksOnly:true};});
 check('N05',()=>{const template=json('APPROVAL-REQUEST.template.json'),command=template.parameters.cmd,slot='ROOT_APPROVED_GRANT_SHA256';assert((command.match(/ROOT_APPROVED_GRANT_SHA256/g)??[]).length===1,'ONE_SLOT');const validator=(candidate,digest)=>/^[0-9a-f]{64}$/.test(digest)&&candidate===command.replace(slot,digest);const digest='c'.repeat(64),synthetic=command.replace(slot,digest);assert(validator(synthetic,digest)&&!validator(command,slot)&&!validator(synthetic+'; echo injected',digest)&&!validator(synthetic.replace('/bin/zsh','/bin/sh')+' ',digest)&&!validator(synthetic.replace('functional-reference-v3/entry','different/entry'),digest)&&!validator(command.replace(slot,'C'.repeat(64)),'C'.repeat(64)),'SLOT_ONLY');assert(template.parameters.login===false&&template.parameters.shell==='/bin/zsh'&&template.parameters.sandbox_permissions==='require_escalated'&&template.prefixRule==='NONE','TOOL_SHAPE');const forbidden=['GO.json','REVIEW-ACCEPTANCE.json','APPROVAL-REQUEST.json'];assert(seal.files.every(row=>!forbidden.includes(row.path)),'NO_ACTUAL_AUTHORITY_IN_SOURCE_SEAL');assert(seal.files.every(row=>!['GO.template.json','REVIEW-ACCEPTANCE.template.json'].includes(row.path)),'NO_BACK_REFERENCE_TEMPLATES');const receipt=json('REVIEW-ACCEPTANCE.template.json');assert(receipt.presealSha256===hash(sealBytes)&&receipt.requestsSha256===hash(read('REQUESTS.json')),'RECEIPT_BASE');const grant=json('GO.template.json');assert(grant.preseal.sha256===hash(sealBytes)&&grant.independentReviewReceipt.sha256===null,'GRANT_TEMPLATE_FORWARD_SLOT');return {templateSha256:hash(read('APPROVAL-REQUEST.template.json')),mutableSlot:slot,syntheticOnly:true,actualResolvedCommandWritten:false,acyclicOrder:['frozen source/preseal and review evidence commit','receipt references evidence commit, not itself','raw receipt hash enters fresh GO','raw GO hash enters command sole slot','resolved command external DATA check; never embedded back into GO']};});
 check('N06',()=>{const entry=read('entry.mjs').toString('utf8'),storage=read('storage.mjs').toString('utf8'),state=read('state.mjs').toString('utf8');assert(entry.includes('completed=creditObservation(row,storage,completed);')&&!entry.includes('fs.writeSync(2'),'NO_FALLBACK_AND_GUARDED_CREDIT');assert(entry.includes('publicationFailure={primary:error,secondary,terminal:storage.terminalState,late:Date.now()>storage.deadline}')&&entry.includes('if(!finalizedOuter&&outerHandles.length)'),'MEMORY_FAILURE_AND_CLEANUP');assert(storage.includes('terminal(value){\n  this.checkTime();')&&storage.includes('if(state.primary!==null)throw state.primary.error;')&&state.includes('storage.checkTime();'),'SOURCE_GUARDS');const current=json('APPROVAL-REQUEST.template.json').parameters,old=json('APPROVAL-REQUEST.template.json',true).parameters;assert(current.cmd===old.cmd.replaceAll('functional-reference-v2','functional-reference-v3').replaceAll('functional-v2-','functional-v3-'),'WRAPPER_STRUCTURE');return {guardedCredit:true,stderrFallbackRemoved:true,failureStateMemoryOnly:true,descriptorCleanupNotRuntimeAcceptance:true,wrapperDerivativeReused:'595a9bc3938fc5ff9b048f7f30fb87ec9e4ba7ca; namespace-only structural relation; no new wrapper execution',lateBlockingSyscallsNotPrevented:true};});
 for(const row of bindings){const bytes=fs.readFileSync(root+'/'+row.path);assert(hash(bytes)===row.sha256&&bytes.length===row.bytes,'POST_INTEGRITY');}
 const result={status:results.every(row=>row.matched)?'SCOPED_PREEXEC_ACCEPT_READY':'FINDINGS_OR_HELPER_ASSERTIONS',sourceCommit:'4eea354169492b4c47d373d504e5918e1c4f3830',evidenceCommit:'73065e68469e2e514c0ee87ff34ac1db04ba51cb',presealSha256:hash(sealBytes),requestsSha256:hash(read('REQUESTS.json')),templateSha256:hash(read('APPROVAL-REQUEST.template.json')),results,authorData:6,novelDataGroups:6,newTargetChildren:0,nestedChildren:0,bash:0,nativeEntry:0,wrapperExecutions:0,realGO:false,eligibleUnrun:37,withheldUnrun:3,elapsedMs:Date.now()-began};fs.writeFileSync(root+'/RESULT-r3.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});log({event:'COMPLETE',status:result.status,results:results.length,elapsedMs:result.elapsedMs});console.log(JSON.stringify({status:result.status,results:results.map(row=>({id:row.id,matched:row.matched,error:row.error})),elapsedMs:result.elapsedMs}));if(results.some(row=>!row.matched))process.exitCode=1;
}catch(error){log({event:'STOP',message:error.message});process.exitCode=1;}finally{fs.closeSync(capture);}
