import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const base=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash',prefix='tests/compatibility/bash-ere-engine-independent-20260829',source='08e40d411dc47bd725cb138e7d419ef2079a2879';
const records=[];function git(args,input){const index=records.length,stdout=fs.openSync(base+`/norm-${index}.stdout`,'wx',0o600),stderr=fs.openSync(base+`/norm-${index}.stderr`,'wx',0o600);const result=spawnSync('/usr/bin/git',args,{cwd:repo,env:{PATH:'/usr/bin:/bin',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_OPTIONAL_LOCKS:'0'},input,stdio:['pipe',stdout,stderr],timeout:30000});for(const fd of [stdout,stderr]){fs.fsyncSync(fd);assert(fs.fstatSync(fd).size<4194304);fs.closeSync(fd);}records.push({args,pid:result.pid,status:result.status,signal:result.signal,closed:result.status!==null,error:result.error?String(result.error):null});fs.writeFileSync(base+'/NORMATIVE-PROCESS.json',JSON.stringify(records,null,2)+'\n');assert(result.status===0&&result.signal===null&&!result.error);return fs.readFileSync(base+`/norm-${index}.stdout`);}
const inventory=git(['ls-tree','-rlz','--full-tree',source,'--',prefix]).toString().split('\0').filter(Boolean).map(line=>{const match=/^(\d+) blob ([a-f0-9]{40})\s+(\d+)\t(.+)$/.exec(line);assert(match);return{oid:match[2],bytes:Number(match[3]),path:match[4],relative:match[4].slice(prefix.length+1)};});
const selected=inventory.filter(item=>(!item.relative.includes('/')&&item.relative.endsWith('.mjs'))||['witnesses/cases.json.data','SUMMARY.json'].includes(item.relative));assert(selected.length<=20&&selected.every(item=>item.bytes<1048576)&&selected.reduce((sum,item)=>sum+item.bytes,0)<2097152);
fs.writeFileSync(base+'/NORMATIVE-SELECTED.json',JSON.stringify(selected,null,2)+'\n',{flag:'wx'});const batch=git(['cat-file','--batch'],selected.map(item=>item.oid).join('\n')+'\n');let position=0;const rows=[];for(const item of selected){const end=batch.indexOf(10,position);assert(end>=0);assert.equal(batch.subarray(position,end).toString(),`${item.oid} blob ${item.bytes}`);position=end+1;const bytes=batch.subarray(position,position+item.bytes);position+=item.bytes;assert.equal(batch[position++],10);assert.equal(createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex'),item.oid);rows.push({...item,sha256:createHash('sha256').update(bytes).digest('hex'),body:bytes.toString('base64')});}assert.equal(position,batch.length);fs.writeFileSync(base+'/NORMATIVE-INPUTS.json',JSON.stringify(rows,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({files:rows.map(({relative,bytes,sha256})=>({relative,bytes,sha256})),native:0,imports:0}));
