import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { combinedIdentities, readIdentity } from './identity.mjs';
const scope = import.meta.dirname;
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const previous = JSON.parse(readIdentity({ path: `${scope}/FINAL-PACKET.json`, bytes: 26233, sha256: 'f23bf9a3af6ed9278e63606cfde791b676bd1b3c643bfa307e9f2929fdfc545d' }));
const keys = ['schema', 'issuedUTC', 'latestStartUTC', 'expiresUTC', 'windowEnforcement', 'reviews', 'publisherSourceCommit', 'runtimeSourceCommit', 'runtimePreseal', 'publisherBinding', 'publisherPreseal', 'runtimeFiles', 'publisherFiles', 'preimportFiles', 'node', 'product', 'absentSlots', 'runtimeCommand', 'publicationCommand', 'slots', 'bounds', 'actualAuthority', 'qualifications', 'preimportCommand', 'controlSourcePreseal', 'inspection', 'historicalData', 'controls', 'activatedConsumers', 'retiredConsumers', 'identityPolicy', 'retiredV4', 'preimportOrigin'];
const packet = Object.fromEntries(keys.map(key => [key, previous[key]]));
packet.metadataCorrection = { previousPath: `${scope}/FINAL-PACKET.json`, previousSha256: 'f23bf9a3af6ed9278e63606cfde791b676bd1b3c643bfa307e9f2929fdfc545d', change: 'remove stale inherited v4 four-control narrative; explicit final field set, no helper or window change' };
packet.preimportCommand.argv[1] = `${scope}/FINAL-BINDING.json`;
packet.preimportCommand.argv[2] = { slot: 'finalPacketSha256', source: 'BINDING-RECEIPT.json.sha256' };
packet.preimportCommand.argv[3] = { slot: 'finalPacketBytes', source: 'BINDING-RECEIPT.json.bytes' };
for (const entry of combinedIdentities(packet.publisherFiles, packet.preimportFiles)) readIdentity(entry, 131072);
readIdentity(packet.runtimePreseal, 32768); readIdentity(packet.publisherBinding, 131072); readIdentity(packet.publisherPreseal, 131072);
const control = JSON.parse(readIdentity(packet.controlSourcePreseal, 32768));
for (const entry of control.files) readIdentity(entry, 32768);
for (const slot of packet.absentSlots) assert.equal(fs.existsSync(slot), false);
const controlsBytes = fs.readFileSync(`${scope}/CONTROLS.json`);
const results = JSON.parse(controlsBytes); assert.equal(results.passed, 8);
packet.controls.identity = { path: `${scope}/CONTROLS.json`, bytes: controlsBytes.length, sha256: hash(controlsBytes) };
packet.completedUTC = new Date().toISOString();
const inspection = JSON.parse(readIdentity(packet.inspection, 32768));
assert(Date.now() - Date.parse(inspection.startedUTC) < 660000, 'publication time reserve');
const body = Buffer.from(JSON.stringify(packet, null, 2) + '\n');
fs.writeFileSync(`${scope}/FINAL-BINDING.json`, body, { flag: 'wx' });
const receipt = { path: `${scope}/FINAL-BINDING.json`, bytes: body.length, sha256: hash(body), issuedUTC: packet.issuedUTC, latestStartUTC: packet.latestStartUTC, expiresUTC: packet.expiresUTC, pureGroups: 8, productRuntimeCalls: 0, helperFiles: packet.preimportFiles, actualAuthority: false };
fs.writeFileSync(`${scope}/BINDING-RECEIPT.json`, JSON.stringify(receipt, null, 2) + '\n', { flag: 'wx' });
let workBytes = 0, files = 0;
const walk = directory => { for (const name of fs.readdirSync(directory)) { const file = path.join(directory, name), stat = fs.lstatSync(file); if (stat.isDirectory()) walk(file); else { assert(stat.isFile()); workBytes += stat.size; files++; } } }; walk(scope);
const rawCaptures = [];
for (const role of ['inspect', 'preseal', 'validation', 'publication']) for (const channel of ['stdout', 'stderr']) {
  const file = `/private/tmp/coherent-b1-final-binding-v5-20260829-${role}.${channel}`;
  const stat = fs.lstatSync(file); assert(stat.isFile()); rawCaptures.push({ path: file, bytes: stat.size, live: role === 'publication' }); workBytes += stat.size;
}
assert(workBytes + 1048576 < 50331648);
const census = { atUTC: new Date().toISOString(), elapsedSecondsFromFirstCapturedInspector: (Date.now() - Date.parse(inspection.startedUTC)) / 1000, knownStartsCompletedAtMetadataSnapshot: 21, finalGitRolesReserved: 2, knownStartsAfterSuccessfulCommit: 23, limit: 32, sourceVisiblePeak: 3, allowedPeak: 3, pureHelpers: 1, pureGroups: 8, runtimeOrEngineCalls: 0, files, measuredWorkAndCaptureBytes: workBytes, publicationTailReservedBytes: 1048576, captureCap: 50331648, workCap: 201326592, rawCaptures, noFullCensus: true, noGroupAbsenceClaim: true, knownSynchronousCommandsReturned: true, finalGitReceipt: 'external publication stdout after commit; not circularly inside committed evidence' };
fs.writeFileSync(`${scope}/CENSUS.json`, JSON.stringify(census, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify({ receipt, census }));
