export interface NativeCase {
  readonly name: string;
  readonly locale: "C" | "C.UTF-8";
  readonly pattern: string;
  readonly subjectBase64: string;
  readonly inputBase64: string;
  readonly status: number;
  readonly stdout: string;
  readonly stderr: string;
  readonly files: Readonly<Record<string, string>>;
}

export const nativeCases: readonly NativeCase[] = [
  {"name":"late-literal","locale":"C","pattern":"xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"late-literal","locale":"C.UTF-8","pattern":"xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"absolute-start","locale":"C","pattern":"^xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":1,"stdout":"5\n","stderr":"csplit: '/^xy/': match not found\n","files":{"xx00":"YWF4eQo="}},
  {"name":"absolute-start","locale":"C.UTF-8","pattern":"^xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":1,"stdout":"5\n","stderr":"csplit: ‘/^xy/’: match not found\n","files":{"xx00":"YWF4eQo="}},
  {"name":"absolute-end","locale":"C","pattern":"xy$","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"absolute-end","locale":"C.UTF-8","pattern":"xy$","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"late-empty-end","locale":"C","pattern":"$","subjectBase64":"YWJj","inputBase64":"YWJjCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YWJjCg=="}},
  {"name":"late-empty-end","locale":"C.UTF-8","pattern":"$","subjectBase64":"YWJj","inputBase64":"YWJjCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YWJjCg=="}},
  {"name":"buffer-start","locale":"C","pattern":"\\`xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":1,"stdout":"5\n","stderr":"csplit: '/\\\\`xy/': match not found\n","files":{"xx00":"YWF4eQo="}},
  {"name":"buffer-start","locale":"C.UTF-8","pattern":"\\`xy","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":1,"stdout":"5\n","stderr":"csplit: ‘/\\\\`xy/’: match not found\n","files":{"xx00":"YWF4eQo="}},
  {"name":"buffer-end","locale":"C","pattern":"xy\\'","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"buffer-end","locale":"C.UTF-8","pattern":"xy\\'","subjectBase64":"YWF4eQ==","inputBase64":"YWF4eQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YWF4eQo="}},
  {"name":"word-start","locale":"C","pattern":"\\<xy","subjectBase64":"IXh5","inputBase64":"IXh5Cg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"IXh5Cg=="}},
  {"name":"word-start","locale":"C.UTF-8","pattern":"\\<xy","subjectBase64":"IXh5","inputBase64":"IXh5Cg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"IXh5Cg=="}},
  {"name":"word-not-start","locale":"C","pattern":"\\<xy","subjectBase64":"YXh5","inputBase64":"YXh5Cg==","status":1,"stdout":"4\n","stderr":"csplit: '/\\\\<xy/': match not found\n","files":{"xx00":"YXh5Cg=="}},
  {"name":"word-not-start","locale":"C.UTF-8","pattern":"\\<xy","subjectBase64":"YXh5","inputBase64":"YXh5Cg==","status":1,"stdout":"4\n","stderr":"csplit: ‘/\\\\<xy/’: match not found\n","files":{"xx00":"YXh5Cg=="}},
  {"name":"word-end","locale":"C","pattern":"xy\\>","subjectBase64":"YXh5IQ==","inputBase64":"YXh5IQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YXh5IQo="}},
  {"name":"word-end","locale":"C.UTF-8","pattern":"xy\\>","subjectBase64":"YXh5IQ==","inputBase64":"YXh5IQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"YXh5IQo="}},
  {"name":"not-word-boundary","locale":"C","pattern":"\\Bxy","subjectBase64":"YXh5","inputBase64":"YXh5Cg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YXh5Cg=="}},
  {"name":"not-word-boundary","locale":"C.UTF-8","pattern":"\\Bxy","subjectBase64":"YXh5","inputBase64":"YXh5Cg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YXh5Cg=="}},
  {"name":"nullable-backref","locale":"C","pattern":"\\(a*\\)*\\1b","subjectBase64":"eGFhYWFi","inputBase64":"eGFhYWFiCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"eGFhYWFiCg=="}},
  {"name":"nullable-backref","locale":"C.UTF-8","pattern":"\\(a*\\)*\\1b","subjectBase64":"eGFhYWFi","inputBase64":"eGFhYWFiCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"eGFhYWFiCg=="}},
  {"name":"empty-loop","locale":"C","pattern":"\\(a*\\)*b","subjectBase64":"eGI=","inputBase64":"eGIK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"eGIK"}},
  {"name":"empty-loop","locale":"C.UTF-8","pattern":"\\(a*\\)*b","subjectBase64":"eGI=","inputBase64":"eGIK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"eGIK"}},
  {"name":"nested-nullable","locale":"C","pattern":"\\(\\(a*\\)*\\)\\1b","subjectBase64":"eGFhYWI=","inputBase64":"eGFhYWIK","status":0,"stdout":"0\n6\n","stderr":"","files":{"xx00":"","xx01":"eGFhYWIK"}},
  {"name":"nested-nullable","locale":"C.UTF-8","pattern":"\\(\\(a*\\)*\\)\\1b","subjectBase64":"eGFhYWI=","inputBase64":"eGFhYWIK","status":0,"stdout":"0\n6\n","stderr":"","files":{"xx00":"","xx01":"eGFhYWIK"}},
  {"name":"retained-capture","locale":"C","pattern":"\\(\\(a\\)\\|b\\)*\\2c","subjectBase64":"eGFiYWM=","inputBase64":"eGFiYWMK","status":0,"stdout":"0\n6\n","stderr":"","files":{"xx00":"","xx01":"eGFiYWMK"}},
  {"name":"retained-capture","locale":"C.UTF-8","pattern":"\\(\\(a\\)\\|b\\)*\\2c","subjectBase64":"eGFiYWM=","inputBase64":"eGFiYWMK","status":0,"stdout":"0\n6\n","stderr":"","files":{"xx00":"","xx01":"eGFiYWMK"}},
  {"name":"nullable-alternative","locale":"C","pattern":"\\(a\\|\\)*\\1b","subjectBase64":"eGFhYg==","inputBase64":"eGFhYgo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"eGFhYgo="}},
  {"name":"nullable-alternative","locale":"C.UTF-8","pattern":"\\(a\\|\\)*\\1b","subjectBase64":"eGFhYg==","inputBase64":"eGFhYgo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"eGFhYgo="}},
  {"name":"multibyte-offset","locale":"C","pattern":"é\\+","subjectBase64":"enrDqcOp","inputBase64":"enrDqcOpCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"enrDqcOpCg=="}},
  {"name":"multibyte-offset","locale":"C.UTF-8","pattern":"é\\+","subjectBase64":"enrDqcOp","inputBase64":"enrDqcOpCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"enrDqcOpCg=="}},
  {"name":"utf8-dot","locale":"C","pattern":"^.$","subjectBase64":"w6k=","inputBase64":"w6kK","status":1,"stdout":"3\n","stderr":"csplit: '/^.$/': match not found\n","files":{"xx00":"w6kK"}},
  {"name":"utf8-dot","locale":"C.UTF-8","pattern":"^.$","subjectBase64":"w6k=","inputBase64":"w6kK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"w6kK"}},
  {"name":"utf8-word","locale":"C","pattern":"\\<é\\>","subjectBase64":"IcOpIQ==","inputBase64":"IcOpIQo=","status":1,"stdout":"5\n","stderr":"csplit: '/\\\\<\\303\\251\\\\>/': match not found\n","files":{"xx00":"IcOpIQo="}},
  {"name":"utf8-word","locale":"C.UTF-8","pattern":"\\<é\\>","subjectBase64":"IcOpIQ==","inputBase64":"IcOpIQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"IcOpIQo="}},
  {"name":"unicode-word-digit","locale":"C","pattern":"\\<١\\>","subjectBase64":"IdmhIQ==","inputBase64":"IdmhIQo=","status":1,"stdout":"5\n","stderr":"csplit: '/\\\\<\\331\\241\\\\>/': match not found\n","files":{"xx00":"IdmhIQo="}},
  {"name":"unicode-word-digit","locale":"C.UTF-8","pattern":"\\<١\\>","subjectBase64":"IdmhIQ==","inputBase64":"IdmhIQo=","status":0,"stdout":"0\n5\n","stderr":"","files":{"xx00":"","xx01":"IdmhIQo="}},
  {"name":"invalid-word-start","locale":"C","pattern":"\\<a","subjectBase64":"6WE=","inputBase64":"6WEK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"6WEK"}},
  {"name":"invalid-word-start","locale":"C.UTF-8","pattern":"\\<a","subjectBase64":"6WE=","inputBase64":"6WEK","status":1,"stdout":"3\n","stderr":"csplit: ‘/\\\\<a/’: match not found\n","files":{"xx00":"6WEK"}},
  {"name":"invalid-word-end","locale":"C","pattern":"a\\>","subjectBase64":"Yek=","inputBase64":"YekK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"YekK"}},
  {"name":"invalid-word-end","locale":"C.UTF-8","pattern":"a\\>","subjectBase64":"Yek=","inputBase64":"YekK","status":1,"stdout":"3\n","stderr":"csplit: ‘/a\\\\>/’: match not found\n","files":{"xx00":"YekK"}},
  {"name":"invalid-not-boundary","locale":"C","pattern":"\\Ba","subjectBase64":"6WE=","inputBase64":"6WEK","status":1,"stdout":"3\n","stderr":"csplit: '/\\\\Ba/': match not found\n","files":{"xx00":"6WEK"}},
  {"name":"invalid-not-boundary","locale":"C.UTF-8","pattern":"\\Ba","subjectBase64":"6WE=","inputBase64":"6WEK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"6WEK"}},
  {"name":"invalid-dot","locale":"C","pattern":"^.$","subjectBase64":"/w==","inputBase64":"/wo=","status":0,"stdout":"0\n2\n","stderr":"","files":{"xx00":"","xx01":"/wo="}},
  {"name":"invalid-dot","locale":"C.UTF-8","pattern":"^.$","subjectBase64":"/w==","inputBase64":"/wo=","status":1,"stdout":"2\n","stderr":"csplit: ‘/^.$/’: match not found\n","files":{"xx00":"/wo="}},
  {"name":"invalid-negated-set","locale":"C","pattern":"^[^a]$","subjectBase64":"/w==","inputBase64":"/wo=","status":0,"stdout":"0\n2\n","stderr":"","files":{"xx00":"","xx01":"/wo="}},
  {"name":"invalid-negated-set","locale":"C.UTF-8","pattern":"^[^a]$","subjectBase64":"/w==","inputBase64":"/wo=","status":1,"stdout":"2\n","stderr":"csplit: ‘/^[^a]$/’: match not found\n","files":{"xx00":"/wo="}},
  {"name":"invalid-before-valid","locale":"C","pattern":"a$","subjectBase64":"wK9h","inputBase64":"wK9hCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"wK9hCg=="}},
  {"name":"invalid-before-valid","locale":"C.UTF-8","pattern":"a$","subjectBase64":"wK9h","inputBase64":"wK9hCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"wK9hCg=="}},
  {"name":"nul-dot","locale":"C","pattern":"^.$","subjectBase64":"AA==","inputBase64":"AAo=","status":1,"stdout":"2\n","stderr":"csplit: '/^.$/': match not found\n","files":{"xx00":"AAo="}},
  {"name":"nul-dot","locale":"C.UTF-8","pattern":"^.$","subjectBase64":"AA==","inputBase64":"AAo=","status":1,"stdout":"2\n","stderr":"csplit: ‘/^.$/’: match not found\n","files":{"xx00":"AAo="}},
  {"name":"nul-negated-set","locale":"C","pattern":"^[^a]$","subjectBase64":"AA==","inputBase64":"AAo=","status":0,"stdout":"0\n2\n","stderr":"","files":{"xx00":"","xx01":"AAo="}},
  {"name":"nul-negated-set","locale":"C.UTF-8","pattern":"^[^a]$","subjectBase64":"AA==","inputBase64":"AAo=","status":0,"stdout":"0\n2\n","stderr":"","files":{"xx00":"","xx01":"AAo="}},
  {"name":"nul-later-literal","locale":"C","pattern":"a$","subjectBase64":"AGE=","inputBase64":"AGEK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"AGEK"}},
  {"name":"nul-later-literal","locale":"C.UTF-8","pattern":"a$","subjectBase64":"AGE=","inputBase64":"AGEK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"AGEK"}},
  {"name":"incomplete-prefix-word","locale":"C","pattern":"\\<a","subjectBase64":"w2E=","inputBase64":"w2EK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"w2EK"}},
  {"name":"incomplete-prefix-word","locale":"C.UTF-8","pattern":"\\<a","subjectBase64":"w2E=","inputBase64":"w2EK","status":1,"stdout":"3\n","stderr":"csplit: ‘/\\\\<a/’: match not found\n","files":{"xx00":"w2EK"}},
  {"name":"invalid-word-e9","locale":"C","pattern":"\\w","subjectBase64":"6Q==","inputBase64":"6Qo=","status":1,"stdout":"2\n","stderr":"csplit: '/\\\\w/': match not found\n","files":{"xx00":"6Qo="}},
  {"name":"invalid-word-e9","locale":"C.UTF-8","pattern":"\\w","subjectBase64":"6Q==","inputBase64":"6Qo=","status":1,"stdout":"2\n","stderr":"csplit: ‘/\\\\w/’: match not found\n","files":{"xx00":"6Qo="}},
  {"name":"backref-longest","locale":"C","pattern":"\\(a\\|aa\\)*\\1b","subjectBase64":"emFhYWFi","inputBase64":"emFhYWFiCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"emFhYWFiCg=="}},
  {"name":"backref-longest","locale":"C.UTF-8","pattern":"\\(a\\|aa\\)*\\1b","subjectBase64":"emFhYWFi","inputBase64":"emFhYWFiCg==","status":0,"stdout":"0\n7\n","stderr":"","files":{"xx00":"","xx01":"emFhYWFiCg=="}},
  {"name":"empty-backref","locale":"C","pattern":"\\(a*\\)\\1b","subjectBase64":"eGI=","inputBase64":"eGIK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"eGIK"}},
  {"name":"empty-backref","locale":"C.UTF-8","pattern":"\\(a*\\)\\1b","subjectBase64":"eGI=","inputBase64":"eGIK","status":0,"stdout":"0\n3\n","stderr":"","files":{"xx00":"","xx01":"eGIK"}},
  {"name":"retained-empty-last","locale":"C","pattern":"^\\(a*\\)*\\1$","subjectBase64":"YWFh","inputBase64":"YWFhCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YWFhCg=="}},
  {"name":"retained-empty-last","locale":"C.UTF-8","pattern":"^\\(a*\\)*\\1$","subjectBase64":"YWFh","inputBase64":"YWFhCg==","status":0,"stdout":"0\n4\n","stderr":"","files":{"xx00":"","xx01":"YWFhCg=="}},
];
