import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const repo='/Users/kjopek/Workspace/safe-bash';
const author=path.join(repo,'tests/compatibility/bash-ere-runtime-integration-author-20260829/rebind-v1');
const mode=process.argv[2];
const capture=mode==='publish'?fs.mkdtempSync('/tmp/ere-npm-closure-v2-publication-'):path.join(root,'capture');
fs.mkdirSync(capture,{recursive:true});
const events=fs.openSync(path.join(capture,mode+'.events.jsonl'),'wx');
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const event=value=>{fs.writeSync(events,JSON.stringify({at:new Date().toISOString(),...value})+'\n');fs.fsyncSync(events);};
function read(file,max=2097152){const stat=fs.lstatSync(file);if(!stat.isFile()||stat.size>max)throw Error('bounded regular input');const bytes=fs.readFileSync(file);if(bytes.length!==stat.size)throw Error('read drift');return bytes;}
function write(name,value){fs.writeFileSync(path.join(root,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});}
async function child(label,exe,args,input){const out=path.join(capture,label+'.stdout'),err=path.join(capture,label+'.stderr');const stdout=fs.openSync(out,'wx'),stderr=fs.openSync(err,'wx');event({event:'capture-open',label});let failurePresent=false,failure,exitSeen=false;try{const proc=spawn(exe,args,{cwd:repo,stdio:[input===undefined?'ignore':'pipe',stdout,stderr],env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}});const done=new Promise(resolve=>{proc.on('error',error=>{failurePresent=true;failure=error;});proc.on('exit',(code,signal)=>{exitSeen=true;event({event:'exit',label,pid:proc.pid,code,signal});});proc.on('close',(code,signal)=>resolve({code,signal}));});event({event:'enrolled',label,pid:proc.pid,exe,args});if(input!==undefined){proc.stdin.on('error',error=>{failurePresent=true;failure=error;});proc.stdin.end(input);}let timedOut=false;const timer=setTimeout(()=>{timedOut=true;proc.kill('SIGKILL');},60000);const result=await done;clearTimeout(timer);fs.fsyncSync(stdout);fs.fsyncSync(stderr);event({event:'close',label,pid:proc.pid,...result,exitSeen,timedOut,failurePresent});if(!exitSeen||timedOut||failurePresent||result.signal!==null)throw Error('known retirement STOP '+String(failure));return {...result,stdout:out,stderr:err};}finally{fs.closeSync(stdout);fs.closeSync(stderr);event({event:'capture-closed',label});}}
const node='/Users/kjopek/.nvm/versions/node/v22.22.2/bin/node';
const git='/usr/bin/git';
const options=['-c','gc.auto=0','-c','maintenance.auto=false','-c','core.hooksPath=/dev/null','-c','commit.gpgsign=false','-c','core.abbrev=40'];
async function main(){event({event:'owner-start',pid:process.pid,mode});if(mode==='inspect'){
  const file=path.join(author,'TOOLS.json'),bytes=read(file);if(bytes.length!==528093||hash(bytes)!=='eebea839e8a061259a257245540485f8e7df5b64aebc2f77d0803de0f4141aca')throw Error('TOOLS identity');const tools=JSON.parse(bytes);
  const summary={};for(const [key,value]of Object.entries(tools))summary[key]=Array.isArray(value)?{length:value.length,first:value[0]}:value;
  if(summary.npm&&typeof summary.npm==='object')summary.npm=Object.fromEntries(Object.entries(summary.npm).map(([key,value])=>[key,Array.isArray(value)?{length:value.length,first:value[0]}:value]));
  write('START.json',{at:new Date().toISOString(),grant:{minutes:10,knownOS:24,peak:2,capture:33554432,work:134217728},scope:'npm relative file/link DATA only; no execution/inflation'});
  write('TOOL-SHAPE.json',summary);
  const result=await child('committed-tools',git,[...options,'show','22260dd7:'+path.relative(repo,file)]);if(result.code!==0||!read(result.stdout).equals(bytes))throw Error('committed TOOLS mismatch');
  write('INPUTS.json',{tools:{path:file,bytes:bytes.length,sha256:hash(bytes),commit:'22260dd7'},producerSeal:{path:path.join(author,'producer-v2/SEAL.json'),bytes:7074,sha256:'f78151de4b59220dc906ee29600f19fb5ed90ee99d88985093d422ea8d54e934'},packageManifest:{path:path.join(author,'producer-v2/PACKAGE-MANIFEST.json'),bytes:205721,sha256:'09f5f0a974cb5c33a91dc947d7b94bfb2473706e479014b4ef750a1182678fbb'}});
}else if(mode==='bind'){const names=['RESULT.json','runner.mjs','produce.outer.jsonl'];const pins=names.map(name=>{const file=path.join(author,'producer-v2',name),bytes=read(file);return {path:file,bytes:bytes.length,sha256:hash(bytes)};});const result=await child('committed-producer-records',git,[...options,'cat-file','--batch'],pins.map(pin=>'439138a0e13595a41e84841f83e4f2f51b36ff68:'+path.relative(repo,pin.path)).join('\n')+'\n');if(result.code!==0)throw Error('producer binding');const batch=read(result.stdout);let offset=0;for(const pin of pins){const end=batch.indexOf(10,offset),header=batch.subarray(offset,end).toString().split(' ');offset=end+1;if(header[1]!=='blob'||Number(header[2])!==pin.bytes)throw Error('Git frame');const bytes=batch.subarray(offset,offset+pin.bytes);offset+=pin.bytes+1;if(hash(bytes)!==pin.sha256)throw Error('producer record identity');}if(offset!==batch.length)throw Error('extra frame');write('AUTHOR-INPUTS.json',{commit:'439138a0e13595a41e84841f83e4f2f51b36ff68',pins});}
else if(mode==='syntax'){for(const name of ['supervise.mjs','audit.mjs']){const result=await child('syntax-'+name,node,['--check',path.join(root,name)]);if(result.code!==0)throw Error('syntax '+name);}}
else if(mode==='seal'){const files={};for(const name of ['supervise.mjs','audit.mjs','INPUTS.json','AUTHOR-INPUTS.json','PRESEAL.md']){const bytes=read(path.join(root,name));files[name]={bytes:bytes.length,sha256:hash(bytes)};}write('SEAL.json',{at:new Date().toISOString(),files});let result=await child('stage-preseal',git,[...options,'add','--',path.relative(repo,root)]);if(result.code!==0)throw Error('stage');result=await child('commit-preseal',git,[...options,'commit','--only','-m','test: preseal npm relative-tool closure audit','--',path.relative(repo,root)]);if(result.code!==0)throw Error('commit');}
else if(mode==='audit'){const seal=JSON.parse(read(path.join(root,'SEAL.json')));for(const [name,pin]of Object.entries(seal.files)){const bytes=read(path.join(root,name));if(bytes.length!==pin.bytes||hash(bytes)!==pin.sha256)throw Error('seal drift');}const result=await child('audit',node,[path.join(root,'audit.mjs')]);write('EXECUTION.json',{...result,at:new Date().toISOString()});if(result.code!==0)process.exitCode=1;}
else if(mode==='publish'){write('PUBLICATION-LOCATION.json',{capture,at:new Date().toISOString()});let bytes=0,entries=0;const files=[];function visit(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name),stat=fs.lstatSync(file);entries++;if(stat.isDirectory())visit(file);else{if(!stat.isFile())throw Error('owned nonregular');bytes+=stat.size;files.push({path:path.relative(root,file),bytes:stat.size,sha256:hash(read(file,16777216))});}}}visit(root);const snapshot=Object.freeze({root,at:new Date().toISOString(),bytes,entries,files});if(bytes>134217728)throw Error('working cap');write('PUBLICATION-SNAPSHOT.json',snapshot);event({event:'immutable-local-snapshot',bytes,entries});let result=await child('stage-results',git,[...options,'add','--',path.relative(repo,root)]);if(result.code!==0)throw Error('stage');result=await child('commit-results',git,[...options,'commit','--only','-m','test: publish npm tool-closure DATA rebind','--',path.relative(repo,root)]);if(result.code!==0)throw Error('commit');const commitText=read(result.stdout).toString();result=await child('owned-status',git,[...options,'status','--porcelain=v1','--untracked-files=normal','--',path.relative(repo,root)]);if(result.code!==0)throw Error('status');console.log(JSON.stringify({capture,code:0,commitText,ownedStatus:read(result.stdout).toString(),snapshot:{bytes,entries}}));}
else throw Error('unsupported explicit mode');}
try{await main();event({event:'owner-complete',pid:process.pid,mode,code:process.exitCode??0});}catch(error){event({event:'primary',present:true,message:String(error),stack:error?.stack});console.error(error);process.exitCode=1;}finally{fs.closeSync(events);}
