import fs from 'node:fs';
import assert from 'node:assert/strict';
import {readPinned,pinExecutable,Primary,errorRecord,publish} from './auth.mjs';
import {openCapturePair} from './direct-child.mjs';
const packet=process.argv[2],seal=JSON.parse(readPinned(packet+'/CONTROL-SEAL.json',JSON.parse(process.argv[3])));
for(const [name,pin]of Object.entries(seal.files))readPinned(packet+'/'+name,pin);pinExecutable(seal.node);if(Date.now()>=seal.deadline)throw Error('CONTROL_DEADLINE');
const rows=[];const objectOpen=Object.freeze(Object.assign(new Error('fixed open failure'),{code:'EOPEN'}));const objectClose=Object.freeze(Object.assign(new Error('fixed close failure'),{code:'ECLOSE'}));
const cases=[{id:'S01-undefined-false',open:undefined,close:false,closeFails:true},{id:'S02-null-zero',open:null,close:0,closeFails:true},{id:'S03-false-undefined',open:false,close:undefined,closeFails:true},{id:'S04-zero-null',open:0,close:null,closeFails:true},{id:'S05-object-pair',open:objectOpen,close:objectClose,closeFails:true},{id:'S06-close-success',open:objectOpen,closeFails:false},{id:'S07-first-open',open:0,firstFails:true},{id:'S08-success',success:true}];
for(const item of cases){const ledger={starts:0,active:0,stopped:false,rows:[]},row={id:item.id},primary=new Primary(),calls=[];let opens=0,caught=false,observed,result;const operations={openSync(filename,flags,mode){calls.push({operation:'open',filename,flags,mode});opens++;if(item.firstFails||!item.success&&opens===2)throw item.open;return opens-1;},closeSync(descriptor){calls.push({operation:'close',descriptor});if(item.closeFails)throw item.close;}};try{result=openCapturePair({capture:'/DATA/'+item.id},ledger,row,primary,operations);}catch(reason){caught=true;observed=reason;}
 if(item.success){assert.equal(caught,false);assert.deepEqual(result,{stdoutFd:0,stderrFd:1});assert.equal(ledger.stopped,false);assert.equal(ledger.rows.length,0);assert.equal(primary.present,false);assert.equal(calls.filter(call=>call.operation==='close').length,0);}
 else{assert.equal(caught,true);assert.equal(Object.is(observed,item.open),true);assert.equal(primary.present,true);assert.equal(Object.is(primary.reason,item.open),true);assert.equal(ledger.stopped,true);assert.equal(ledger.rows.length,1);assert.equal(row.childStarted,false);assert.equal(row.qualified,false);assert.equal(row.primaryPresent,true);assert.deepEqual(row.primary,errorRecord(item.open));assert.equal(row.captureCleanup.acquired,!item.firstFails);assert.equal(row.captureCleanup.closeAttempted,!item.firstFails);assert.equal(row.captureCleanup.closed,!item.firstFails&&!item.closeFails);assert.equal(row.knownOutstanding,item.closeFails?1:0);assert.equal(primary.secondary.length,item.closeFails?1:0);if(item.closeFails){assert.equal(row.captureCleanup.failurePresent,true);assert.deepEqual(row.captureCleanup.failure,errorRecord(item.close));assert.deepEqual(row.secondary[0],errorRecord(item.close));assert.equal(row.secondaryPresent,true);}assert.equal(calls.filter(call=>call.operation==='close').length,item.firstFails?0:1);}
 assert.equal(ledger.starts,0);assert.equal(ledger.active,0);rows.push({id:item.id,pass:true,caught,selectedPrimary:primary.present?errorRecord(primary.reason):undefined,lifecycle:ledger.rows,calls});}
assert.equal(Object.isFrozen(objectOpen),true);assert.equal(Object.isFrozen(objectClose),true);
publish(seal.result,Buffer.from(JSON.stringify({kind:'SYNTHETIC_OPERATIONS_ONLY',rows,groups:8,actualNativeFaults:0,childStarts:0},null,2)+'\n'),seal.deadline);process.stdout.write(JSON.stringify({groups:rows.length,passed:rows.filter(row=>row.pass).length,actualNativeFaults:0,childStarts:0})+'\n');
