import assert from 'node:assert/strict';
import {lstatSync,readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root=process.argv[2];if(root!=='/Users/kjopek/Workspace/safe-bash/tests/compatibility/bash-ere-transport-author-20260829/runtime-preflight-v1/l02-diagnosis-v1')throw Error('owned root');
const sourceStat=lstatSync(root+'/TERMINATE-SOURCE.json');if(!sourceStat.isFile()||sourceStat.size!==1497)throw Error('source size');
const sourceBytes=readFileSync(root+'/TERMINATE-SOURCE.json');assert.equal(createHash('sha256').update(sourceBytes).digest('hex'),'485ef75ae79da94d8e730de32b9fbf94b0056e41486dfeaa4216d4d9c6525dc7');
const source=JSON.parse(sourceBytes);assert.equal(source.sha256,'a418b39c68a6c0b6c8c839c5bedfbe01dc01f04fb0b4e7f5072f3b560dbd9b89');assert(source.source.indexOf('this[kHandle].stopThread();')<source.source.lastIndexOf("this.once('exit', resolve)"));
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done;});return{promise,resolve};}
async function turns(){for(let index=0;index<16;index++)await Promise.resolve();}
class HostDouble{
 constructor(mode,setupReason,forced){this.mode=mode;this.setupReason=setupReason;this.forced=forced;this.failures=0;this.phase='setup';this.listeners=[];this.trace=[];this.externalExit=false;}
 once(event,listener){this.trace.push(this.phase+':once:'+event);if(event==='exit'&&(this.mode==='persistent'||(this.mode==='single'&&this.failures===0))){this.failures++;throw this.setupReason;}this.listeners.push(listener);return this;}
 terminate(){this.phase='termination';this.trace.push('terminate:ref');if(this.forced?.present){this.trace.push('terminate:forced-reject');return Promise.reject(this.forced.value);}this.trace.push('terminate:stopThread');return new Promise(resolve=>{this.once('exit',resolve);});}
 deliverExit(){this.externalExit=true;this.trace.push('double:exit');const listeners=this.listeners.splice(0);for(const listener of listeners)listener(0);}
}
function mirrorOwner(worker,constructorReason){const exited=deferred(),stdout=deferred(),stderr=deferred();let installed=false;const setup={present:false,value:undefined};let ready;try{if(!worker)throw constructorReason;worker.once('exit',()=>exited.resolve());installed=true;ready=Promise.resolve();}catch(reason){setup.present=true;setup.value=reason;ready=Promise.reject(reason);void ready.catch(()=>{});if(!worker)exited.resolve();}const state={setup,installed,settled:false,closeOutcome:null,termination:{present:false,value:undefined},fallbackExitResolved:false,stdout,stderr,exited,retired:false};
 const termination=Promise.resolve().then(async()=>{if(!worker)return;await worker.terminate();if(!installed){state.fallbackExitResolved=true;exited.resolve();}});void termination.then(()=>{},reason=>{state.termination={present:true,value:reason};});
 const closing=Promise.resolve().then(async()=>{const retired=await Promise.allSettled([termination,exited.promise,installed?stdout.promise:undefined,installed?stderr.promise:undefined]);await Promise.allSettled([ready,undefined]);for(const result of retired)if(result.status==='rejected')throw result.reason;state.retired=true;});
 void closing.then(()=>{state.settled=true;state.closeOutcome={ok:true};},reason=>{state.settled=true;state.closeOutcome={ok:false,reason};});return state;}
const results=[];async function group(id,run){try{const details=await run();results.push({id,pass:true,details});}catch(reason){results.push({id,pass:false,diagnostic:reason instanceof Error?reason.message:'non-Error',reasonPresent:true});}}
await group('D01_persistent_exit_hook_double_fault',async()=>{const worker=new HostDouble('persistent',false);const owner=mirrorOwner(worker);await turns();assert.equal(owner.setup.value,false);assert.equal(worker.failures,2);assert.equal(owner.termination.present,true);assert.equal(owner.termination.value,false);assert.equal(owner.fallbackExitResolved,false);worker.deliverExit();await turns();assert.equal(worker.externalExit,true);assert.equal(owner.settled,false);return{setupThrow:false,terminationPromiseRejects:false,failedInstallations:2,externalDoubleExit:true,ownerWait:'UNRESOLVED_DEPENDENCY',trace:worker.trace};});
await group('D02_single_setup_fault_keeps_termination_registration',async()=>{const worker=new HostDouble('single',false);const owner=mirrorOwner(worker);await turns();assert.equal(worker.failures,1);assert.equal(owner.settled,false);worker.deliverExit();await turns();assert.equal(owner.setup.value,false);assert.equal(owner.termination.present,false);assert.equal(owner.fallbackExitResolved,true);assert.equal(owner.settled,true);assert.equal(owner.closeOutcome.ok,true);return{firstSetupReason:false,cleanupSettled:true,failedInstallations:1,streamQualification:'Production setup stops before stream enrollment; this model does NOT prove its OS stream drain.',trace:worker.trace};});
await group('D03_setup_false_cleanup_undefined_distinct_presence',async()=>{const worker=new HostDouble('single',false,{present:true,value:undefined});const owner=mirrorOwner(worker);await turns();worker.deliverExit();await turns();assert.equal(owner.setup.value,false);assert.equal(owner.termination.present,true);assert.equal(owner.termination.value,undefined);assert.equal(owner.settled,false);return{setupPresent:true,setupValue:false,cleanupPresent:true,cleanupValueType:'undefined',ownerWait:'UNRESOLVED_DEPENDENCY',trace:worker.trace};});
await group('D04_installed_exit_and_failed_termination',async()=>{const worker=new HostDouble('none',false,{present:true,value:undefined});const owner=mirrorOwner(worker);await turns();worker.deliverExit();owner.stdout.resolve();owner.stderr.resolve();await turns();assert.equal(owner.installed,true);assert.equal(owner.settled,true);assert.equal(owner.closeOutcome.ok,false);assert.equal(owner.closeOutcome.reason,undefined);assert.equal(owner.retired,false);return{exitObservedByOwner:true,cleanupRejectPresent:true,cleanupReasonType:'undefined',clean:false,trace:worker.trace};});
await group('D05_constructor_false_no_acquisition',async()=>{const owner=mirrorOwner(null,false);await turns();assert.equal(owner.setup.present,true);assert.equal(owner.setup.value,false);assert.equal(owner.settled,true);assert.equal(owner.closeOutcome.ok,true);return{constructorReason:false,WorkerAcquired:false,exitedWaiterResolvedWithoutAcquisition:true};});
await group('D06_normal_exit_and_both_streams_gate_close',async()=>{const worker=new HostDouble('none',false);const owner=mirrorOwner(worker);await turns();worker.deliverExit();await turns();assert.equal(owner.settled,false);owner.stdout.resolve();await turns();assert.equal(owner.settled,false);owner.stderr.resolve();await turns();assert.equal(owner.settled,true);assert.equal(owner.closeOutcome.ok,true);return{exitOnlyInsufficient:true,oneStreamInsufficient:true,bothStreamsJoined:true,trace:worker.trace};});
const receipt={schema:1,role:'PURE_HOST_DOUBLE_SOURCE_CONFORMANT_SELECTED_CONTROL_FLOW_NOT_PRODUCT_EXECUTION',groups:results,passed:results.filter(row=>row.pass).length,total:6,actualWorkers:0,productImports:0,nativeTerminateInvocations:0,unresolvedPromises:'D01/D03 are intentionally inert unresolved model promises with no handles/listeners on real resources; never awaited indefinitely. Sixteen microtask turns are a finite observation, not all-jobs or time proof.',sourceProvenance:'Pinned Node method live-handle/no-callback path plus owner.js start/catch/close wait edges; independent external double exit is not Node/OS evidence.',original5001Unchanged:true};writeFileSync(root+'/DOUBLE-RESULT.json',JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({passed:receipt.passed,total:6,actualWorkers:0,productImports:0}));if(receipt.passed!==6)process.exitCode=1;
