import type { GlobalSettings, PageSettings } from "./settings.js";
import { integer, float32, length, choice } from "./values.js";
interface Switch {
    readonly name: string;
    readonly short: string;
    readonly scope: "global" | "page" | "toc";
    readonly arity: number;
    readonly qtPatched: boolean;
    readonly disposition: "static" | "resource" | "harness" | "excluded";
    readonly apply?: (global: GlobalSettings, page: PageSettings, operands: readonly string[]) => void;
}
// Source-derived inventory; parser admission does not qualify renderer support.
const declarations: Switch[] = [
    { name: "--help", short: "h", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "help"; } },
    { name: "--version", short: "V", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "version"; } },
    { name: "--license", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "license"; } },
    { name: "--extended-help", short: "H", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "extended-help"; } },
    { name: "--manpage", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "manpage"; } },
    { name: "--htmldoc", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "htmldoc"; } },
    { name: "--readme", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.action = "readme"; } },
    { name: "--quiet", short: "q", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.logLevel = "none"; } },
    { name: "--log-level", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.logLevel = choice(_a[0]!, ["none", "error", "warn", "info", "debug"]); } },
    { name: "--no-collate", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.collate = false; } },
    { name: "--collate", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.collate = true; } },
    { name: "--copies", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.copies = integer(_a[0]!, 1, 2147483647); } },
    { name: "--orientation", short: "O", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.orientation = choice(_a[0]!, ["Portrait", "Landscape"]); } },
    { name: "--page-size", short: "s", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.pageSize = choice(_a[0]!, ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "C5E", "Comm10E", "DLE", "Executive", "Folio", "Ledger", "Legal", "Letter", "Tabloid"]); } },
    { name: "--grayscale", short: "g", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.colorMode = "grayscale"; } },
    { name: "--lowquality", short: "l", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.resolution = "screen"; } },
    { name: "--title", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.documentTitle = _a[0]!; } },
    { name: "--read-args-from-stdin", short: "", scope: "global", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.readArgsFromStdin = true; } },
    { name: "--margin-bottom", short: "B", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.marginBottom = length(_a[0]!); } },
    { name: "--margin-left", short: "L", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.marginLeft = length(_a[0]!); } },
    { name: "--margin-right", short: "R", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.marginRight = length(_a[0]!); } },
    { name: "--margin-top", short: "T", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.marginTop = length(_a[0]!); } },
    { name: "--dpi", short: "d", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.dpi = integer(_a[0]!, 1, 2147483647); } },
    { name: "--page-height", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.pageHeight = length(_a[0]!); } },
    { name: "--page-width", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.pageWidth = length(_a[0]!); } },
    { name: "--cookie-jar", short: "", scope: "global", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--image-quality", short: "", scope: "global", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.imageQuality = integer(_a[0]!, 0, 100); } },
    { name: "--image-dpi", short: "", scope: "global", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.imageDPI = integer(_a[0]!, 1, 2147483647); } },
    { name: "--no-pdf-compression", short: "", scope: "global", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.useCompression = false; } },
    { name: "--use-xserver", short: "", scope: "global", arity: 0, qtPatched: true, disposition: "excluded" },
    { name: "--outline", short: "", scope: "global", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.outline = true; } },
    { name: "--no-outline", short: "", scope: "global", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.outline = false; } },
    { name: "--outline-depth", short: "", scope: "global", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.outlineDepth = integer(_a[0]!, 0, 2147483647); } },
    { name: "--dump-outline", short: "", scope: "global", arity: 1, qtPatched: true, disposition: "resource" },
    { name: "--dump-default-toc-xsl", short: "", scope: "global", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.action = "dump-default-toc-xsl"; } },
    { name: "--default-header", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p) => { _p.header.left = "[webpage]"; _p.header.right = "[page]/[topage]"; _p.header.line = true; _g.marginTop = { value: 20, unit: "mm" }; } },
    { name: "--viewport-size", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.viewportSize = _a[0]!; } },
    { name: "--enable-plugins", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "excluded" },
    { name: "--disable-plugins", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.enablePlugins = false; } },
    { name: "--minimum-font-size", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.minimumFontSize = integer(_a[0]!, 1, 2147483647); } },
    { name: "--user-style-sheet", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--no-images", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.loadImages = false; } },
    { name: "--images", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.loadImages = true; } },
    { name: "--disable-javascript", short: "n", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.enableJavascript = false; } },
    { name: "--enable-javascript", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "harness" },
    { name: "--encoding", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.defaultEncoding = _a[0]!; } },
    { name: "--no-background", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.background = false; } },
    { name: "--background", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.web.background = true; } },
    { name: "--include-in-outline", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.includeInOutline = true; } },
    { name: "--exclude-from-outline", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.includeInOutline = false; } },
    { name: "--disable-smart-shrinking", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.web.enableIntelligentShrinking = false; } },
    { name: "--enable-smart-shrinking", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.web.enableIntelligentShrinking = true; } },
    { name: "--print-media-type", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.load.printMediaType = true; } },
    { name: "--no-print-media-type", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.load.printMediaType = false; } },
    { name: "--enable-forms", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.produceForms = true; } },
    { name: "--disable-forms", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.produceForms = false; } },
    { name: "--disable-internal-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.useLocalLinks = false; } },
    { name: "--enable-internal-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.useLocalLinks = true; } },
    { name: "--disable-external-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.useExternalLinks = false; } },
    { name: "--enable-external-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.useExternalLinks = true; } },
    { name: "--resolve-relative-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.resolveRelativeLinks = true; } },
    { name: "--keep-relative-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _g.resolveRelativeLinks = false; } },
    { name: "--enable-toc-back-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.backLinks = true; } },
    { name: "--disable-toc-back-links", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.backLinks = false; } },
    { name: "--proxy", short: "p", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--proxy-hostname-lookup", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "resource" },
    { name: "--bypass-proxy-for", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--username", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--password", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--ssl-key-path", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--ssl-key-password", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--ssl-crt-path", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--load-error-handling", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.load.loadErrorHandling = choice(_a[0]!, ["abort", "skip", "ignore"]); } },
    { name: "--load-media-error-handling", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.load.mediaLoadErrorHandling = choice(_a[0]!, ["abort", "skip", "ignore"]); } },
    { name: "--custom-header", short: "", scope: "page", arity: 2, qtPatched: false, disposition: "resource" },
    { name: "--custom-header-propagation", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "resource" },
    { name: "--no-custom-header-propagation", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "resource" },
    { name: "--javascript-delay", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "harness" },
    { name: "--window-status", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "harness" },
    { name: "--zoom", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.load.zoomFactor = float32(_a[0]!, true); } },
    { name: "--cookie", short: "", scope: "page", arity: 2, qtPatched: false, disposition: "resource" },
    { name: "--post", short: "", scope: "page", arity: 2, qtPatched: false, disposition: "resource" },
    { name: "--post-file", short: "", scope: "page", arity: 2, qtPatched: false, disposition: "resource" },
    { name: "--disable-local-file-access", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _p.load.blockLocalFileAccess = true; } },
    { name: "--enable-local-file-access", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "resource" },
    { name: "--allow", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--cache-dir", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--debug-javascript", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "harness" },
    { name: "--no-debug-javascript", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "harness" },
    { name: "--stop-slow-scripts", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "harness" },
    { name: "--no-stop-slow-scripts", short: "", scope: "page", arity: 0, qtPatched: false, disposition: "harness" },
    { name: "--run-script", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "harness" },
    { name: "--checkbox-svg", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--checkbox-checked-svg", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--radiobutton-svg", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--radiobutton-checked-svg", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "resource" },
    { name: "--page-offset", short: "", scope: "page", arity: 1, qtPatched: false, disposition: "static", apply: (_g, _p, _a) => { _g.pageOffset = integer(_a[0]!, -2147483648, 2147483647); } },
    { name: "--footer-center", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.center = _a[0]!; } },
    { name: "--footer-font-name", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.fontName = _a[0]!; } },
    { name: "--footer-font-size", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.fontSize = integer(_a[0]!, 1, 2147483647); } },
    { name: "--footer-left", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.left = _a[0]!; } },
    { name: "--footer-line", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.line = true; } },
    { name: "--no-footer-line", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.line = false; } },
    { name: "--footer-right", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.right = _a[0]!; } },
    { name: "--footer-spacing", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.footer.spacing = float32(_a[0]!, false); } },
    { name: "--footer-html", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "resource" },
    { name: "--header-center", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.center = _a[0]!; } },
    { name: "--header-font-name", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.fontName = _a[0]!; } },
    { name: "--header-font-size", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.fontSize = integer(_a[0]!, 1, 2147483647); } },
    { name: "--header-left", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.left = _a[0]!; } },
    { name: "--header-line", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.line = true; } },
    { name: "--no-header-line", short: "", scope: "page", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.line = false; } },
    { name: "--header-right", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.right = _a[0]!; } },
    { name: "--header-spacing", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.header.spacing = float32(_a[0]!, false); } },
    { name: "--header-html", short: "", scope: "page", arity: 1, qtPatched: true, disposition: "resource" },
    { name: "--replace", short: "", scope: "page", arity: 2, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.replacements.push([_a[0]!, _a[1]!]); } },
    { name: "--xsl-style-sheet", short: "", scope: "toc", arity: 1, qtPatched: true, disposition: "resource" },
    { name: "--toc-header-text", short: "", scope: "toc", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.captionText = _a[0]!; } },
    { name: "--disable-toc-links", short: "", scope: "toc", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.forwardLinks = false; } },
    { name: "--disable-dotted-lines", short: "", scope: "toc", arity: 0, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.useDottedLines = false; } },
    { name: "--toc-text-size-shrink", short: "", scope: "toc", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.fontScale = float32(_a[0]!, true); } },
    { name: "--toc-level-indentation", short: "", scope: "toc", arity: 1, qtPatched: true, disposition: "static", apply: (_g, _p, _a) => { _p.toc.indentation = _a[0]!; } },
];
export const switches: readonly Switch[] = Object.freeze(declarations.map(entry => Object.freeze(entry)));
