import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { lstatSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url)), repository = resolve(here, '../../..');
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const json = path => JSON.parse(readFileSync(join(here, path)));
const entries = {};
function visit(directory) { for (const name of readdirSync(directory).sort()) { const path = join(directory, name), key = relative(here, path), stat = lstatSync(path); assert.equal(stat.isSymbolicLink(), false); if (stat.isDirectory()) { entries[key + '/'] = 'directory'; visit(path); } else { assert.ok(stat.isFile()); if (key !== 'MANIFEST.json') entries[key] = hash(readFileSync(path)); } } }
visit(here); assert.deepEqual(entries, json('MANIFEST.json').entries);
const report = json('attempt-2/RESULT.json');
assert.equal(report.revision, '774644f9ea39b41f824db4c829e7a97e6e1386be');
assert.equal(report.product, '8670ebe8f0d39966c2de2638780437398e5f8490');
assert.equal(report.runnerSha256, hash(readFileSync(join(here, 'run.mjs'))));
assert.equal(report.error, undefined); assert.equal(report.cleaned, true);
assert.deepEqual(report.counts, { independent: 30, pass: 29, fail: 1 });
assert.deepEqual(report.checks.filter(row => !row.pass).map(row => row.name), ['v24.11.1 plain node:test execution preserves TAP consumers']);
assert.equal(report.author.controls.length, 26); assert.deepEqual(report.author.failures, []);
assert.deepEqual(report.author, json('attempt-2/UNCHANGED-AUTHOR.json'));
for (const row of report.staged) assert.equal(hash(execFileSync('git', ['--no-replace-objects', 'show', `${row.commit}:${row.path}`], { cwd: repository })), row.sha256);
assert.equal(report.importMap.length, 5); assert.ok(report.importMap.every(entry => entry.commit === report.product));
assert.equal(hash(Buffer.from(JSON.stringify(json('attempt-2/FRESH-DIST.json')))), report.freshDistSha256);
const neighbors = json('REPORTER-NEIGHBOR.json'); assert.equal(neighbors.error, undefined); assert.equal(neighbors.cleaned, true); assert.equal(neighbors.cases.length, 2);
assert.equal(neighbors.runnerSha256, hash(readFileSync(join(here, 'reporter-neighbor.mjs'))));
assert.ok(neighbors.cases.every(row => row.status === 0 && row.counts.tests === 1 && row.counts.pass === 1));
const failedSetup = json('attempt-1/RESULT.json'); assert.ok(failedSetup.error); assert.equal(failedSetup.runnerSha256, hash(readFileSync(join(here, 'attempt-1/run.mjs.txt'))));
assert.equal(report.fullRuntimeGroupsExecuted, false); assert.equal(report.privateAccess, false);
console.log(JSON.stringify({ sealed: true, authorReplay: '26/26', independent: '29/30', actualReporterBlockerPreserved: true, reporterNeighbors: '2/2', fullGroupsExecuted: false }));
