import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
const home=path.dirname(fileURLToPath(import.meta.url));const capsule=path.join(home,'capsule-v2');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const inputs=[];
for(const [label,expected]of [['m02','bbbc93d67d5e8fa93420d69a1e7692222ce11998327f7492556e176d9438aae6'],['m03','1df3e4f8829f2281588b2c94df564af42d3485f8c15787ae127cefc53d644c52'],['m04','6b5a5b06b33cdec4f5e92c06e4a3444d334060d5e6b90cbfd2d5e5775fc3220d']]){const encoded=path.join(home,label+'-INPUTS.json.gz.base64');if(!fs.lstatSync(encoded).isFile()||fs.lstatSync(encoded).size>16777216)throw Error('archive kind');const archive=Buffer.from(fs.readFileSync(encoded,'utf8'),'base64');if(hash(archive)!==expected)throw Error('archive integrity');inputs.push(...JSON.parse(gunzipSync(archive,{maxOutputLength:33554432})));}
function get(name,version='/author-v5/'){const record=inputs.find(item=>item.spec.includes(version)&&item.spec.endsWith('/'+name));if(!record)throw Error('missing fixed input '+name);const body=Buffer.from(record.body,'base64');if(body.length!==record.bytes||hash(body)!==record.sha256)throw Error('body binding');return body;}
const module=JSON.parse(get('MODULE-v5.json'));for(const row of module.files){const input=inputs.find(item=>item.spec==='a2f3983da537b95bed65b8bc727ab93bc7e98ca3:'+row.path);if(!input||row.blob!==input.oid||row.sha256!==input.sha256||row.bytes!==input.bytes)throw Error('full module binding');}
const archive=JSON.parse(gunzipSync(Buffer.from(get('INPUTS-v1.json.gz.base64').toString().trim(),'base64'),{maxOutputLength:16777216}));
if(archive.baseline.length!==278||archive.engine.length!==96)throw Error('baseline/engine count');
for(const row of [...archive.baseline,...archive.engine])if(Buffer.from(row.body,'base64').length!==row.bytes||hash(Buffer.from(row.body,'base64'))!==row.sha256)throw Error('baseline/public engine body');
const packageBytes=Buffer.from(get('r1-PACKAGE.tgz.base64','/author-v5/validation-v2/evidence/').toString().trim(),'base64');if(hash(packageBytes)!=='f6b13bd116196cd5559a2d6b5d8578c5c7f614af095f7f00515bd341366c4092')throw Error('full author package');
if(fs.existsSync(capsule))throw Error('no capsule overwrite');fs.mkdirSync(capsule);
const deltas=[];
function write(name,bytes){if(name.includes('/')||!name.match(/^[A-Za-z0-9.-]+$/))throw Error('capsule name');fs.writeFileSync(path.join(capsule,name),bytes,{flag:'wx'});}
function edit(text,from,to,count=1){const found=text.split(from).length-1;if(found!==count)throw Error('recipe anchor '+from.slice(0,70)+' '+found);deltas.push({from,to,count});return text.split(from).join(to);}
const focusedIds=Array.from({length:34},(_,index)=>'F'+String(index+1).padStart(2,'0')).map(id=>['F16','F17'].includes(id)?id+'-v2':id);
const workerIds=Array.from({length:29},(_,index)=>'W'+String(index+1).padStart(2,'0')).map(id=>id==='W23'?'W23-v2':id);
const independentIds=['R01-invalid-flag','R02-escaping-parent-job','R03-profile-parent-job','R04-lookalike','R05-cause-stack-unread','R06-extra-field','R07-private-class-escaping','R08-profile-completion','R09-async-publisher','R10-publisher-undefined','R11-cleanup-undefined','R12-prepare-registration',...Array.from({length:10},(_,index)=>'E'+String(index+1).padStart(2,'0'))];
for(const name of ['INPUTS-v1.json.gz.base64','MODULE-v5.json','BASE-PACKAGE-v1.json','capture-v1.mjs','load-guard-v1.mjs','host-guard-v1.mjs','load-negative-v1.mjs.data','engine-adapter-v1.mjs','engine-adapter-noise-v1.mjs','types-v1.mts.data'])write(name,get(name));
const oldFocused=JSON.parse(get('CONTROL-v5.json')).focusedIds;
let focused=get('focused-v5.mjs').toString();focused=edit(focused,'Object.freeze('+JSON.stringify(oldFocused)+')','Object.freeze('+JSON.stringify(focusedIds)+')');write('focused-v5.mjs',focused);
let workers=get('workers-v5.mjs').toString();workers=edit(workers,'Object.freeze('+JSON.stringify(JSON.parse(get('CONTROL-v5.json')).workerIds)+')','Object.freeze('+JSON.stringify(workerIds)+')');write('workers-v5.mjs',workers);
let judge=get('judge-v5.mjs').toString();judge=edit(judge,'const focusedIds='+JSON.stringify(oldFocused)+';','const focusedIds='+JSON.stringify(focusedIds)+';');write('judge-v5.mjs',judge);
const expectations=JSON.parse(get('WORKER-CASES-v4.json','/author-v4/')).filter(row=>row.id!=='W23');for(const row of JSON.parse(get('WORKER-CASES-v5.json')))if(!expectations.some(item=>item.id===row.id))expectations.push(row);expectations.sort((left,right)=>workerIds.indexOf(left.id)-workerIds.indexOf(right.id));if(expectations.length!==29)throw Error('versionmapped expectations');write('WORKER-CASES-v5.json',JSON.stringify(expectations,null,2)+'\n');
const mutations=JSON.parse(get('MUTATIONS-v1.json',':tests/commands/node-author-20260829/'));const latest=JSON.parse(get('MUTATIONS-v5.json'));mutations[mutations.findIndex(item=>item.id==='M05')]=latest[0];write('MUTATIONS-v5.json',JSON.stringify(mutations,null,2)+'\n');
write('raw-controls.mjs',get('raw-controls.mjs.data',':tests/commands/node-independent-20260829/source-review-v2/'));
write('independent.mjs',fs.readFileSync(path.join(home,'independent.mjs.data')));
let runner=get('case-runner-v5.mjs').toString();runner=edit(runner,"import {runFocused} from './focused-v5.mjs';","import {runFocused} from './focused-v5.mjs';\nimport {runIndependent} from './independent.mjs';");runner=edit(runner,"else throw new Error('case role');","else if(input.role==='independent'){const rows=await runIndependent(input,publish);final={role:'independent-summary',pass:rows.every(row=>row.pass),clean:rows.every(row=>row.clean),count:rows.length};}\nelse throw new Error('case role');");write('case-runner-v5.mjs',runner);
let owner=get('owner-v5.mjs').toString();owner=edit(owner,"role:'node-author-validation-v2'","role:'node-independent-actual-review-v1'");owner=edit(owner,'state.mutations.length===1','state.mutations.length===6');owner=edit(owner,"const rows=judgeRows(receipts(record),record.code,role,id,readJSON(path.join(home,'WORKER-CASES-v5.json'),32768));",`if(role==='independent'){
 const rows=receipts(record);const last=rows.pop();const expected=configuration.independentIds;
 if(rows.length!==expected.length||last.role!=='independent-summary'||last.count!==expected.length||last.clean!==true||record.code!==(last.pass?0:1))throw Error('independent summary');
 let workers=0,entries=0;for(let index=0;index<rows.length;index++){const row=rows[index];if(row.id!==expected[index]||typeof row.pass!=='boolean'||row.clean!==true||!Number.isSafeInteger(row.workers)||row.workers<0||row.workers>20||!Number.isSafeInteger(row.guestEntries)||row.guestEntries<0||row.guestEntries>row.workers)throw Error('independent ownership/schema');workers+=row.workers;entries+=row.guestEntries;}
 if(workers>18||entries>18||last.pass!==rows.every(row=>row.pass))throw Error('independent counters');state.workerSlots+=18;state.workers+=workers;state.guestEntries+=entries;if(state.workerSlots>configuration.workers||state.workers>configuration.workers||state.guestEntries>configuration.guests)throw Error('independent cumulative caps');const loads=loadRows(record);if(!loads.some(row=>row.path===moduleRoot+'/commands/node/index.js'))throw Error('independent actual load');state.loads.push({name,rows:loads});state.cases.push(...rows.map(row=>({layout,...row})));return last;
 }
 const rows=judgeRows(receipts(record),record.code,role,id,readJSON(path.join(home,'WORKER-CASES-v5.json'),32768));`);
owner=edit(owner,"await types('source',sourceModule);","await types('source',sourceModule);await oneCase('source',sourceModule,'independent','independent');");owner=edit(owner,"await types(layout,moduleRoot);}","await types(layout,moduleRoot);await oneCase(layout,moduleRoot,'independent','independent');}");
owner=edit(owner,"if(entries.length!==958)throw Error('whole package entry count');","if(entries.length!==958||sha(tarBytes)!=='f6b13bd116196cd5559a2d6b5d8578c5c7f614af095f7f00515bd341366c4092')throw Error('whole package identity');");
write('owner-v5.mjs',owner);
const builtin=JSON.parse(get('BUILTINS-v5.json'));
for(const file of ['independent.mjs','raw-controls.mjs']){const text=fs.readFileSync(path.join(capsule,file),'utf8');const names=[...new Set([...text.matchAll(/(?:from\s*|import\s*)["'](node:[^"']+)["']/g)].map(match=>match[1]))].sort();builtin.rows.push({path:'fixtures/'+file,builtins:names});}
write('BUILTINS-v5.json',JSON.stringify(builtin,null,2)+'\n');
const configuration=JSON.parse(get('CONTROL-v5.json'));Object.assign(configuration,{schema:'node-independent-full-versionmapped-review',children:140,totalOwnedProcesses:142,peakOwnedProcesses:4,wallMs:3600000,outerWallMs:3720000,absoluteDeadline:Date.now()+4500000,captureBytes:201326592,outerCaptureBytes:2097152,workBytes:939524096,wholeWorkCeiling:1073741824,workers:192,guests:192,focusedIds,workerIds,independentIds,authorizedOutputRoot:capsule});configuration.readRoots=configuration.readRoots.filter(root=>!root.includes('/tests/commands/node-author-'));configuration.readRoots.push(capsule);configuration.environment.HOME=path.join(capsule,'validation-v2/work/home');configuration.environment.TMPDIR=path.join(capsule,'validation-v2/work/tmp');configuration.planned={authorMappedIdentities:61,newBOMIdentities:2,mainAuthorExecutions:189,mainIndependentRows:66,rawIndependentIdentities:12,engineIndependentIdentities:10,mainWorkerCeiling:141,mainGuestCeiling:141,mutantFamilies:6,mutationCaseProcesses:12,loadNegativeFamilies:6,typePositiveIdentities:12,typeNegativeIdentities:12,typeProcesses:6,strictBuild:1,pack:1,offlineInstall:1,expectedOwnerChildStarts:120};write('CONTROL-v5.json',JSON.stringify(configuration,null,2)+'\n');
const files=fs.readdirSync(capsule).sort().map(name=>{const body=fs.readFileSync(path.join(capsule,name));return{path:name,bytes:body.length,sha256:hash(body)};});
const seal={schema:'independent-node-actual-preseal-v1',nodeSha256:archive.tools.node.sha256,source:configuration.source,files,phase:'DISARMED_UNTIL_COMMITTED',noProductExecuted:true};write('PRESEAL-v5.json',JSON.stringify(seal,null,2)+'\n');
const matrix=JSON.parse(get('MATRIX.json',':tests/commands/node-independent-20260829/preparation-v2/'));
const coverage=['E01,W05,W24','W03,E09','W02,W17,E02','W04,W29','F11,F12,F27,R01-invalid-flag','F27 SOURCE cli binding','F25','E03','SOURCE admission; runtime untested computed-require branch','W22 SOURCE exclusion','SOURCE constructor refusal; no extra guest constructor attempt','W14','W07,E07','E01,E07 SOURCE VFS namespace policy','W11,E01','W10','W08,F04-F10,R04-R06','F02,F13,F14,F17-v2,F25,F26,W09,W16','W28,W29,E04','F26,W04; reusable-buffer variant remains unrun','W06,E06','E06; pathname race guarantee expressly absent','E05; parse-failure cache variant unrun','F16-v2,F17-v2,W23-v2; full max-adjacent matrix not run','E08','E08','F02 SOURCE preabort; full reason vector unrun','W20,E09','F01,F29,W21','W21,W22,F29; constructor-throw branch source-only','F01,F33,F34,W15,W26,E09','E10,W16; artificial held-sink variant unrun','R09,R10,F18-F24,W27','F02,F14,F17-v2,R07,R11','F03,W14,W26; full cutoff-frame schedule source-only','SOURCE channel/host; loaded mutants selective','all E/W actual closure + source ledger inventory','F11,F29,W22 SOURCE provider admission'];
const handoff={source:configuration.source,authorEvidence:'af66b7748af06319751b6cf87acacbe43acc48fd',moduleInputs:module.files.map(({body,...row})=>row),baselineDerived:'7fde32264d757ef856acf3ae92c8581b4a294341',baselineInputs:278,engineEmissions:archive.engine.filter(row=>row.target.endsWith('.js')).length,engineEntries:archive.engine.length,engineSHA256:hash(Buffer.from(JSON.stringify(archive.engine.map(({body,...row})=>row)))),fullPackageSha256:hash(packageBytes),files,recipeDeltas:deltas,coverage:matrix.cases.map((item,index)=>({id:item.id,original:item,plannedBindings:coverage[index],notFullFamilyProof:true})),types:matrix.typeFamilies,loads:matrix.loadFamilies,planned:configuration.planned};fs.writeFileSync(path.join(home,'BINDINGS.json'),JSON.stringify(handoff,null,2)+'\n',{flag:'wx'});
fs.writeFileSync(path.join(home,'PREP-RESULTS.json'),JSON.stringify({role:'SOURCE_DATA_ONLY',sourceMatches:16,baselineBodies:278,engineEntries:96,actualEngine:0,build:0,workers:0,caseIdentities:63,independentRows:22,recipeDeltas:deltas.length,sealSha256:hash(Buffer.from(JSON.stringify(seal,null,2)+'\n'))},null,2)+'\n',{flag:'wx'});
console.log(JSON.stringify({role:'PREP_ONLY',capsuleFiles:files.length+1,authorIdentities:63,independentRows:22,productExecutions:0,seal:hash(Buffer.from(JSON.stringify(seal,null,2)+'\n'))}));
