export { DisallowedSyntaxError, parse } from "./parse/parser.js";
export type {
  ArrayPattern,
  ArrayExpression,
  ArrowFunctionExpression,
  AssignmentPattern,
  AssignmentProperty,
  BinaryExpression,
  BlockStatement,
  BooleanLiteral,
  CallExpression,
  ConditionalExpression,
  Expression,
  ExpressionStatement,
  Identifier,
  LogicalExpression,
  MemberExpression,
  NullLiteral,
  NumericLiteral,
  ObjectExpression,
  ObjectPattern,
  Property,
  RestElement,
  ReturnStatement,
  SourceSpan,
  SpreadElement,
  Statement,
  StringLiteral,
  TemplateElement,
  TemplateLiteral,
  UnaryExpression,
  UndefinedLiteral
} from "./parse/parser.js";
