import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { runInNewContext } from 'node:vm';
import { canonicalData, dataHash, projectData, sha256 } from './own-data.mjs';
import { validateContribution, validateObservations } from './contributions.mjs';
import { ingestSourceArguments } from './source-arguments.mjs';
import { readSelectedSources } from './source-files.mjs';
import { runWorker } from './source-audit-worker.mjs';

const [root] = process.argv.slice(2);
assert(root && resolve(root) === root);
process.umask(0o022);
const fixture = JSON.parse(readFileSync(new URL('./synthetic-fixture.json', import.meta.url), 'utf8'));
const results = [];
const test = async (id, operation) => { await operation(); results.push({ id, status: 'PASS_SYNTHETIC_ONLY' }); };
const input = () => ({ candidate: fixture.candidate, manifest: structuredClone(fixture.manifest), origins: structuredClone(fixture.origins), plan: structuredClone(fixture.plan), bundle: structuredClone(fixture.bundle), allocation: structuredClone(fixture.allocation), readSource: async () => Buffer.from(fixture.sourceUtf8) });
await test('C01', async () => { const report = await ingestSourceArguments(input()); assert.equal(report.boundArguments, 1); assert.equal(report.boundSourceBindings, 1); assert.equal(report.missingArguments, 1); assert.equal(report.status, 'INCOMPLETE'); assert.equal(report.semanticPasses, 0); });
await test('C02', async () => { const request = input(); request.bundle.arguments = []; const report = await ingestSourceArguments(request); assert.equal(report.boundArguments, 0); assert.equal(report.missingArguments, 2); });
await test('C03', async () => { const request = input(); request.bundle.sourceManifestSha256 = '0'.repeat(64); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_MAP_BINDING' }); });
await test('C04', async () => { const request = input(); request.bundle.arguments[0].dependencies[0].revision = 'f'.repeat(40); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_DEPENDENCY_BINDING' }); });
await test('C05', async () => { const request = input(); request.readSource = async () => Buffer.from('changed\n'); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_DEPENDENCY_BYTES' }); });
await test('C06', async () => { const request = input(); request.bundle.arguments[0].dependencies[0].spans[0].sha256 = '0'.repeat(64); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_SPAN_BYTES' }); });
await test('C07', async () => { const request = input(); request.bundle.arguments.push(structuredClone(request.bundle.arguments[0])); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_DUPLICATE_ARGUMENT' }); });
await test('C08', async () => { const request = input(); request.bundle.arguments[0].authority.role = 'product-author-success'; await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_AUTHORITY_ENROLLMENT' }); });
await test('C09', async () => { const request = input(); const reason = Object.freeze({ reason: 'same-object' }); request.readSource = async () => { throw reason; }; let observed; try { await ingestSourceArguments(request); } catch (error) { observed = error; } assert.equal(observed, reason); });
await test('C10', async () => { const request = input(); const foreign = runInNewContext('JSON.parse(text)', { text: JSON.stringify({ candidate: request.candidate, manifest: request.manifest, origins: request.origins, plan: request.plan, bundle: request.bundle, allocation: request.allocation }) }); foreign.readSource = request.readSource; assert.equal((await ingestSourceArguments(foreign)).boundArguments, 1); });
await test('C11', async () => { let getterCalls = 0; const value = {}; Object.defineProperty(value, 'value', { enumerable: true, get() { getterCalls++; return 1; } }); assert.throws(() => projectData(value), { code: 'DATA_ACCESSOR' }); assert.equal(getterCalls, 0); const sparse = []; sparse.length = 1; assert.throws(() => projectData(sparse)); const request = input(); request.bundle.extra = undefined; await assert.rejects(() => ingestSourceArguments(request)); });
await test('C12', async () => { const hidden = {}; Object.defineProperty(hidden, 'kept', { value: 1 }); assert.equal(canonicalData(hidden), '{"kept":1}'); const symbol = { [Symbol('extra')]: 1 }; assert.throws(() => projectData(symbol), { code: 'DATA_SYMBOL' }); const request = input(); Object.defineProperty(request.bundle, 'extra', { value: 1 }); await assert.rejects(() => ingestSourceArguments(request), { code: 'SOURCE_BUNDLE_KEYS' }); });
const sourceRoot = join(root, 'source');
mkdirSync(sourceRoot, { mode: 0o755 });
writeFileSync(join(sourceRoot, 'SOURCE.txt'), fixture.sourceUtf8, { flag: 'wx', mode: 0o644 });
await test('C13', async () => { assert.equal(readSelectedSources(sourceRoot, fixture.manifest).totalBytes, Buffer.byteLength(fixture.sourceUtf8)); writeFileSync(join(sourceRoot, 'added.txt'), 'x', { flag: 'wx', mode: 0o644 }); assert.throws(() => readSelectedSources(sourceRoot, fixture.manifest), { code: 'SOURCE_TREE_INTEGRITY' }); rmSync(join(sourceRoot, 'added.txt')); });
const makeApi = (name, argumentBundle) => {
  const destination = join(root, name);
  mkdirSync(destination, { mode: 0o755 });
  const events = [];
  const bindings = { candidate: fixture.candidate, sourceRoot };
  const data = { sourceManifest: fixture.manifest, sourceOrigins: fixture.origins, sourceProofPlan: fixture.plan, coverageAllocation: fixture.allocation, sourceArguments: argumentBundle };
  return { bindings, events, destination, async phase(phase) { events.push(phase); }, async guard() { events.push('guard'); }, async readBoundJson(name) { return data[name]; }, async writeJson(name, value) { events.push(name); const bytes = Buffer.from(JSON.stringify(value) + '\n'); const filename = join(destination, name); writeFileSync(filename, bytes, { flag: 'wx', mode: 0o600 }); return { path: filename, sha256: sha256(bytes), bytes: bytes.length, mode: 384 }; } };
};
await test('C14', async () => { const api = makeApi('worker-success', fixture.bundle); const result = await runWorker(api); assert.equal(result.status, 'INCOMPLETE'); assert.equal(result.proofRole, 'source-static-counterproof'); assert.equal(result.details.boundArguments, 1); assert(api.events.indexOf('source-arguments-raw.json') < api.events.indexOf('source-audit.json')); assert.equal(JSON.parse(readFileSync(join(api.destination, 'source-audit.json'))).semanticPasses, 0); assert.equal(api.events.filter(event => event === 'guard').length, 2); });
await test('C15', async () => { const bad = structuredClone(fixture.bundle); bad.arguments[0].dependencies[0].spans[0].sha256 = '0'.repeat(64); const api = makeApi('worker-failure', bad); await assert.rejects(() => runWorker(api), { code: 'SOURCE_SPAN_BYTES' }); assert.equal(JSON.parse(readFileSync(join(api.destination, 'source-arguments-raw.json'))).bundle.arguments[0].dependencies[0].spans[0].sha256, '0'.repeat(64)); assert(api.events.indexOf('source-arguments-raw.json') < api.events.indexOf('source-argument-failure.json')); });
await test('C16', async () => { const contribution = structuredClone(fixture.contribution); assert.equal(validateContribution(contribution, fixture.allocation).owner, 'core'); contribution.extra = undefined; assert.throws(() => validateContribution(contribution, fixture.allocation)); });
await test('C17', async () => { const observations = [{ bindingId: 'WRK-06::missing/0', recordId: 'WRK-06', role: 'runtime', status: 'UNOBSERVED', facts: {}, evidenceRefs: [] }]; assert.equal(validateObservations(observations, ['WRK-06::missing/0']).length, 1); assert.throws(() => validateObservations([...observations, ...observations], ['WRK-06::missing/0']), { code: 'OBSERVATION_ENROLLMENT' }); });
await test('C18', async () => { const request = input(); request.plan.designated = [request.plan.designated[0]]; const report = await ingestSourceArguments(request); assert.equal(report.status, 'SOURCE_ARGUMENTS_BOUND_ONLY'); assert.equal(report.runtimeProofs, 0); assert.equal(report.argumentTruthClaim, false); assert.equal(report.rows[0].fullRecordPass, false); assert.equal(report.canonicalBundleSha256, dataHash(request.bundle)); });
process.stdout.write(JSON.stringify({ schema: 1, jobId: 'source-contract-stubs', status: 'PASS_SYNTHETIC_ONLY', results, targetImports: 0, semanticPasses: 0 }) + '\n');
