import {strict as assert} from 'node:assert';import {readFileSync,writeFileSync,lstatSync} from 'node:fs';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {journal,fullWrite,exact} from './journal.mjs';import {judge} from './receipt-gate.mjs';import {ownChild,captureScope} from '../preparation-r3/owned-process.mjs';
const own=fileURLToPath(new URL('.',import.meta.url));const inventory=JSON.parse(readFileSync(join(own,'CASE-INVENTORY.json'),'utf8'));const rows=[];const children=[];async function test(id,body){try{await body();rows.push({id,pass:true});}catch(error){rows.push({id,pass:false,message:error instanceof Error?error.message:'nonError'});}}
function fixture(purpose='normal'){const cell=inventory.cases.find(row=>row.purpose===purpose);const config={...JSON.parse(readFileSync(join(own,'CASES',cell.folder,'CASE.json'),'utf8')),caseSha256:cell.caseSha256};const names=['ere/errors.js','ere/limits.js','ere/transport/accounting.js','ere/transport/protocol.js','ere/transport/validation.js','ere/transport/owner.js','ere/transport/root.js'].map(suffix=>config.packageRelative+'/'+suffix).concat('worker-bridge.mjs');const kinds=purpose==='persistent'?['case-entry','attempt','constructed','setup-fault','termination-requested','setup-fault','termination-rejected','execute-settled','close-settled','close-settled','unconfirmed','retained-root-and-handles']:['case-entry','attempt','constructed','post','posted','execute-settled','termination-requested','worker-exit','stdout-end','stderr-end','close-settled','close-settled','owner-retired'];const trace=kinds.map((kind,index)=>({seq:index+1,at:index+1,kind,detail:''}));const receipt={schema:1,id:config.id,purpose,layout:config.layout,caseSha256:cell.caseSha256,packageSha256:config.packageSha256,assertions:true,passed:purpose==='normal',retirementState:purpose==='normal'?'RETIRED':'UNCONFIRMED',primary:purpose==='normal'?{present:false}:{present:true,kind:'boolean',value:false},cleanup:{present:false},termination:purpose==='normal'?{present:false}:{present:true,kind:'boolean',value:false,route:'promise-rejection'},attempts:1,Workers:1,exits:purpose==='normal'?1:0,stdout:purpose==='normal'?1:0,stderr:purpose==='normal'?1:0,rootRetained:true,handlesRetained:1,retainedCharges:purpose!=='normal',captureFault:false,loads:names.map(path=>({path,sha256:config.modules.find(row=>row.path===path).sha256})),trace,assertionFailure:{present:false},nestedObservation:'NOT_OBSERVED'};const processRow={pid:100,admitted:true,created:true,spawned:true,exited:true,closed:true,stdoutClosed:true,stderrClosed:true,captureComplete:true,captureTruncated:false,primary:{present:false},secondary:[],termRequested:false,killRequested:false,code:purpose==='normal'?0:2};return {receipt,processRow,config};}
await test('J01-own-data-accessor',()=>{let calls=0;const input={};Object.defineProperty(input,'value',{get(){calls++;throw false}});assert.throws(()=>exact(input,['value']));assert.equal(calls,0);});
await test('J02-journal-reserve-cap',()=>{const entry=journal('virtual',{open:()=>1,close:()=>{},write:(_fd,_bytes,_offset,length)=>length});for(let index=0;index<128;index++)assert(entry.emit('event'));assert.equal(entry.emit('extra'),false);assert(entry.fault.present);assert.equal(entry.records.length,128);entry.close();});
await test('J03-short-zero-undefined',()=>{let writes=0;fullWrite(1,Buffer.from('abc'),(_fd,_bytes,_offset,length)=>{writes++;return Math.min(length,1)});assert.equal(writes,3);assert.throws(()=>fullWrite(1,Buffer.from('a'),()=>0));const entry=journal('virtual',{open:()=>1,write:()=>{throw undefined},close:()=>{throw false}});assert.equal(entry.emit('fault'),false);entry.close();assert(entry.fault.present);assert.equal(entry.fault.value,undefined);});
await test('J04-normal-strict-receipt',()=>{const f=fixture();assert.equal(judge(f.receipt,f.processRow,f.config),'PASS');f.processRow.admitted='true';assert.throws(()=>judge(f.receipt,f.processRow,f.config));});
await test('J05-false-retirement-refused',()=>{const f=fixture('persistent');f.receipt.retirementState='RETIRED';f.receipt.passed=true;assert.throws(()=>judge(f.receipt,f.processRow,f.config));});
await test('J06-unknown-distinct-from-process-close',()=>{const f=fixture('persistent');assert(f.processRow.closed);assert.equal(judge(f.receipt,f.processRow,f.config),'STOP_UNCONFIRMED');f.receipt.termination.route='sync-throw';assert.throws(()=>judge(f.receipt,f.processRow,f.config));});
await test('J07-hash-request-binding',()=>{const f=fixture();f.receipt.loads[0].sha256='0'.repeat(64);assert.throws(()=>judge(f.receipt,f.processRow,f.config));const other=fixture();other.receipt.trace=other.receipt.trace.filter(row=>row.kind!=='posted').map((row,index)=>({...row,seq:index+1}));assert.throws(()=>judge(other.receipt,other.processRow,other.config));});
await test('J08-chronology',()=>{const f=fixture();const exit=f.receipt.trace.find(row=>row.kind==='worker-exit');exit.at=0;assert.throws(()=>judge(f.receipt,f.processRow,f.config));});
for(const [id,mode,code,out,err]of [['J09-natural-owned','normal',0,'owned\n',''],['J10-nonzero-owned','failure',7,'','owned-failure\n']])await test(id,async()=>{const child=await ownChild({node:process.execPath,args:[join(own,'stub.mjs'),mode],cwd:own,env:{PATH:process.execPath.slice(0,process.execPath.lastIndexOf('/')),LANG:'C',LC_ALL:'C',HOME:own,TMPDIR:own},role:id,stdout:join(own,'capture',id+'.stdout'),stderr:join(own,'capture',id+'.stderr'),deadline:performance.now()+20000,reserveMilliseconds:5000,timeoutMilliseconds:3000,channelBytes:65536});children.push(child.record);assert.equal(child.record.state,'RETIRED');assert.equal(child.record.code,code);assert(child.record.captureComplete);assert.equal(child.record.primary.present,false);assert.equal(child.record.secondary.length,0);assert.equal(readFileSync(join(own,'capture',id+'.stdout'),'utf8'),out);assert.equal(readFileSync(join(own,'capture',id+'.stderr'),'utf8'),err);if(code!==0){const f=fixture();assert.throws(()=>judge(f.receipt,child.record,f.config));}});
const result={schema:1,rows,passed:rows.filter(row=>row.pass).length,children,actualWorkers:0,productImports:0};writeFileSync(join(own,'CONTROL-RESULT.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({groups:10,passed:result.passed,children:children.length,closed:children.filter(row=>row.closed).length,Workers:0}));if(result.passed!==10)process.exitCode=1;
