import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {SourceTextModule} from 'node:vm';
const root=path.dirname(new URL(import.meta.url).pathname),repo='/Users/kjopek/Workspace/safe-bash';
const author=repo+'/tests/compatibility/bash-ere-runtime-integration-author-20260829/runtime-preflight-v1';
const mode=process.argv[2],scratch='/private/tmp/core70-independent-v6-20260829',control=scratch+'/controls';
const deadline=Math.floor(fs.statSync('/tmp/core70-preexec-review-bootstrap-20260829.stdout').birthtimeMs)+1200000;
const capture=fs.mkdtempSync('/tmp/core70-review-'+mode+'-'),journal=fs.openSync(capture+'/events.jsonl','wx',0o600);
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const events=row=>{fs.writeSync(journal,JSON.stringify({at:new Date().toISOString(),...row})+'\n');fs.fsyncSync(journal);};
const write=(name,value)=>fs.writeFileSync(root+'/'+name,typeof value==='string'?value:JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});
function read(file,pin){const stat=fs.lstatSync(file);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=4194304,file);if(pin){assert.equal(stat.size,pin.size??pin.bytes,file);assert.equal(stat.mode&511,pin.mode,file);}const descriptor=fs.openSync(file,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const before=fs.fstatSync(descriptor);assert.equal(before.ino,stat.ino);const bytes=fs.readFileSync(descriptor),after=fs.fstatSync(descriptor);assert.equal(bytes.length,stat.size);assert.equal(after.mtimeMs,before.mtimeMs);if(pin)assert.equal(hash(bytes),pin.sha256,file);return bytes;}finally{fs.closeSync(descriptor);}}
const pin=file=>{const bytes=read(file),stat=fs.lstatSync(file);return{path:file,size:bytes.length,mode:stat.mode&511,sha256:hash(bytes)};};
async function child(label,exe,args,{cwd=repo,env=process.env,collector}={}){assert(Date.now()<deadline);const output=collector??capture+'/'+label;const stdout=fs.openSync(output+'.stdout','wx',0o600),stderr=fs.openSync(output+'.stderr','wx',0o600);try{const proc=spawn(exe,args,{cwd,env,stdio:['ignore',stdout,stderr]});let exited=false;const done=new Promise(resolve=>{proc.on('error',reason=>events({label,error:String(reason)}));proc.on('exit',(code,signal)=>{exited=true;events({label,event:'exit',pid:proc.pid,code,signal});});proc.on('close',(code,signal)=>resolve({code,signal}));});events({label,event:'start',pid:proc.pid,exe,args});const timer=setTimeout(()=>proc.kill('SIGKILL'),Math.min(60000,deadline-Date.now()));const result=await done;clearTimeout(timer);events({label,event:'close',pid:proc.pid,...result,exited});assert(exited&&result.signal===null,'unknown retirement/deadline STOP');fs.fsyncSync(stdout);fs.fsyncSync(stderr);return{...result,stdout:output+'.stdout',stderr:output+'.stderr'};}finally{fs.closeSync(stdout);fs.closeSync(stderr);}}
async function git(label,args){const result=await child(label,'/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false','-c','core.hooksPath=/dev/null','-c','commit.gpgsign=false','-c','core.abbrev=40',...args]);assert.equal(result.code,0);return read(result.stdout);}
async function main(){assert(Date.now()<deadline);events({event:'owner-start',pid:process.pid,mode});
if(mode==='prepare'){
 const inventory=await git('inventory',['ls-tree','-rz','2fe9ed42910d719c40e2f441e71c4261cb961a41','--',path.relative(repo,author+'/v4'),path.relative(repo,author+'/v6')]);
 const authenticated=[];for(const record of inventory.toString().split('\0').filter(Boolean)){const match=/^[0-7]+ blob ([a-f0-9]{40})\t(.+)$/.exec(record);assert(match);const file=repo+'/'+match[2];const bytes=read(file);assert.equal(crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+bytes.length+String.fromCharCode(0)),bytes])).digest('hex'),match[1]);authenticated.push(pin(file));}assert(authenticated.length>20);
 const sealBytes=read(author+'/v4/EXECUTION-SEAL.json');assert.equal(sealBytes.length,351213);assert.equal(hash(sealBytes),'ea3c82e4192729f4cbd2172e9548d5e21da3d4e3d8ccbfbfa7ad591a47736301');const seal=JSON.parse(sealBytes);assert.equal(seal.sourceTree,'da4e1cc187022255521879b00db2ac77674f79d9');assert.equal(seal.archive.sha256,'4f90df04dba998f184473254bb450f9e085b9fc9d5994dc91a21a7ccf1d1d66e');read(seal.archive.path,seal.archive);
 const cases=JSON.parse(read(author+'/v4/CASES-v4.json')).rows;const ids=[...Array.from({length:32},(_,index)=>'R'+String(index+1).padStart(2,'0')),...Array.from({length:8},(_,index)=>'H'+String(index+1).padStart(2,'0')),...Array.from({length:25},(_,index)=>'EC'+String(index+1).padStart(2,'0')),...Array.from({length:5},(_,index)=>'EH'+String(index+1).padStart(2,'0'))];assert.deepEqual(cases.map(row=>row.id),ids);
 const layoutRows=[];for(const layout of seal.layouts){const manifest=JSON.parse(read(layout.manifest.path,layout.manifest));for(const row of manifest.rows)read(path.join(layout.app,row.path),row);assert.equal(layout.cells.length,70);assert.equal(layout.privateAssets,48);for(const cell of layout.cells){assert.equal(cell.executable,seal.node.path);assert.equal(cell.argv.includes('--allow-child-process'),false);assert.equal(cell.argv.some(value=>value.includes('--loader')),false);const definition=JSON.parse(read(layout.app+'/cells/'+cell.originalId+'.json'));assert.deepEqual(definition.definition,cases.find(row=>row.id===cell.originalId));assert.equal(definition.worker.closure.length,48);for(const row of definition.worker.closure)read(row.path,row);for(const role of definition.worker.roles)if(role.file)read(role.file.path,role.file);assert(!fs.existsSync(cell.capture),'already consumed cell');}layoutRows.push({name:layout.name,manifest:layout.manifest,entries:manifest.rows.length,cells:layout.cells.length,privateAssets:layout.privateAssets,wrapperRoles:layout.wrapperRoles.map(row=>row.name)});}
 assert.equal(seal.layouts.length,3);for(const row of seal.controller)read(row.path,row);const nodeStat=fs.lstatSync(seal.node.path);assert(nodeStat.isFile()&&!nodeStat.isSymbolicLink());assert.equal(nodeStat.size,seal.node.size);const nodeHash=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(seal.node.path,{highWaterMark:65536}))nodeHash.update(chunk);assert.equal(nodeHash.digest('hex'),seal.node.sha256);
 const old='/private/tmp/safe-bash-core70-v6-20260829/controls';const inventoryRows=read(author+'/v6/raw/SHA256SUMS').toString().trim().split('\n').map(line=>{const match=/^([a-f0-9]{64})  (.+)$/.exec(line);assert(match);return{name:match[2],sha256:match[1]};});
 fs.mkdirSync(scratch,{mode:0o700});fs.mkdirSync(control,{mode:0o700});
 const correspondence=[];for(const row of inventoryRows){const bytes=read(old+'/'+row.name);assert.equal(hash(bytes),row.sha256);const output=row.name==='START.json'?Buffer.from(JSON.stringify({deadlineMs:deadline})+'\n'):bytes;fs.writeFileSync(control+'/'+row.name,output,{flag:'wx',mode:0o600});correspondence.push({name:row.name,originalSha256:hash(bytes),freshSha256:hash(output),change:row.name==='START.json'?'fresh owned deadline only':'byte-identical'});}
 for(const name of ['pure-controls.mjs','root-binding.mjs','guards.mjs','array-observer.mjs']){const input=author+'/'+(['guards.mjs','array-observer.mjs'].includes(name)?'v4/':'v6/')+name;const bytes=read(input);const output=name==='root-binding.mjs'?Buffer.from(bytes.toString().replaceAll(old,control)):bytes;fs.writeFileSync(control+'/'+name,output,{flag:'wx',mode:0o600});correspondence.push({name,originalSha256:hash(bytes),freshSha256:hash(output),change:name==='root-binding.mjs'?'exact physical control root relocation':'byte-identical'});}
 fs.writeFileSync(control+'/SHA256SUMS',inventoryRows.map(row=>hash(read(control+'/'+row.name))+'  '+row.name).join('\n')+'\n',{flag:'wx'});
 const custom=read(author+'/v6/raw/CUSTOM-SHA256SUMS').toString().trim().split('\n').map(line=>{const match=/^([a-f0-9]{64})  (.+)$/.exec(line);assert(match);const name=match[2].startsWith(old+'/')?control+match[2].slice(old.length):match[2];const file=name.startsWith('/')?name:repo+'/'+name;return hash(read(file))+'  '+name;});fs.writeFileSync(control+'/CUSTOM-SHA256SUMS',custom.join('\n')+'\n',{flag:'wx'});
 for(const name of ['pure-controls.mjs','root-binding.mjs','guards.mjs','array-observer.mjs','owner.mjs','controls.mjs','harmless.mjs'])new SourceTextModule(read(control+'/'+name).toString(),{identifier:name});new SourceTextModule(read(root+'/novel.mjs').toString(),{identifier:'novel'});
 const files=fs.readdirSync(control).sort().map(name=>pin(control+'/'+name));write('ADMISSION.json',{source:seal.sourceTree,sourceInputs:seal.sourceInputs,archive:seal.archive,authenticated,layoutRows,futureCaps:seal.futureCaps,cases:cases.map(row=>({id:row.id,route:row.route,script:row.script,expected:row.expected,workerStartsMaximum:row.workerStartsMaximum})),correspondence,files,node:seal.node,deadline,imports:0,Workers:0});write('EXECUTION-PRESEAL.json',{mode:'SOURCE-DATA-HARMLESS-ONLY',deadline,control,node:seal.node,files,own:[pin(root+'/owner.mjs'),pin(root+'/novel.mjs')],expected:{pure:30,ownerRecords:18,harmless:2,novel:8},maximumKnownOS:48,peak:3,product:0,Workers:0});
}
if(mode==='seal'){const relative=path.relative(repo,root);await git('add',['add','--',relative]);const result=await git('commit',['commit','--only','-m','Seal CORE70 v6 independent preexecution controls','--',relative]);fs.writeSync(3,result);}
if(mode==='run'){
 const seal=JSON.parse(read(root+'/EXECUTION-PRESEAL.json'));for(const row of [...seal.files,...seal.own])read(row.path,row);
 const replay=await child('controller',seal.node.path,['--experimental-vm-modules',control+'/pure-controls.mjs'],{cwd:control,env:{PATH:path.dirname(seal.node.path),HOME:control,TMPDIR:control,LC_ALL:'C',TZ:'UTC',CORE70_COLLECTOR:control+'/controller'},collector:control+'/controller'});
 write('REPLAY.json',replay);const result=JSON.parse(read(control+'/RESULT.json')),pure=JSON.parse(read(control+'/ADDITIONAL-CONTROLS.json'));assert.equal(result.actual.length,2);assert(result.actual.every(row=>row.retired&&row.closeObserved));assert.equal(result.rows.length,18);assert.equal(pure.results.length,30);assert.equal(replay.code,0);
 const novel=await child('novel',seal.node.path,[root+'/novel.mjs',control,author+'/v4/cell-v4.mjs',root]);write('NOVEL-EXECUTION.json',novel);assert([0,1].includes(novel.code));
 for(const row of [...seal.files,...seal.own])read(row.path,row);write('RESULT.json',{authorPure:pure,owner:result,novel:JSON.parse(read(root+'/NOVEL.json')),replay,novelExecution:novel,at:new Date().toISOString(),actualProduct:0,Workers:0});
}
if(mode==='publish'){
 const raw=root+'/raw';fs.mkdirSync(raw);for(const name of fs.readdirSync('/tmp').sort()){if(name.startsWith('core70-preexec-review-')&&(name.endsWith('.stdout')||name.endsWith('.stderr'))&&!name.includes('publish')){const bytes=read('/tmp/'+name);fs.writeFileSync(raw+'/'+name,bytes,{flag:'wx'});}}
 for(const name of ['RESULT.json','ADDITIONAL-CONTROLS.json','children.jsonl','controller.stdout','controller.stderr','actual-zero.stdout','actual-zero.stderr','actual-nonzero.stdout','actual-nonzero.stderr'])if(fs.existsSync(control+'/'+name))fs.writeFileSync(raw+'/replay-'+name,read(control+'/'+name),{flag:'wx'});
 const rows=[];function walk(directory){for(const name of fs.readdirSync(directory).sort()){const file=directory+'/'+name,stat=fs.lstatSync(file);assert(!stat.isSymbolicLink());if(stat.isDirectory())walk(file);else rows.push(pin(file));}}walk(root);walk(scratch);const bytes=rows.reduce((sum,row)=>sum+row.size,0);assert(bytes<384*1048576);write('PUBLICATION-SNAPSHOT.json',{at:new Date().toISOString(),domain:'current owned review+scratch regular files, before this snapshot/publication tail; no Git storage or final/peak claim',rows,bytes});const relative=path.relative(repo,root);await git('add',['add','--',relative]);const result=await git('commit',['commit','--only','-m','Record CORE70 v6 preexecution findings and control replay','--',relative]);const status=await git('status',['status','--porcelain','--untracked-files=all','--',relative]);assert.equal(status.length,0);fs.writeSync(3,result);fs.writeSync(3,JSON.stringify({cleanOwned:true,at:new Date().toISOString(),capture,bytes})+'\n');
}
events({event:'owner-complete',pid:process.pid,mode});fs.writeSync(3,JSON.stringify({mode,capture,at:new Date().toISOString()})+'\n');}
try{await main();}catch(reason){events({event:'failure',present:true,reason:String(reason),stack:reason?.stack});console.error(reason);process.exitCode=1;}finally{fs.closeSync(journal);}
