import * as runtime from "../dist/runtime.js";
import * as originalRuntime from "toolcraft/runtime";
import * as errors from "../dist/user-error.js";
import * as originalErrors from "toolcraft/user-error";
import * as proxy from "../dist/mcp-proxy.js";
import * as originalProxy from "toolcraft/mcp-proxy";
import {UserError} from "../dist/index.js";
const runtimeForward:typeof originalRuntime=runtime;
const runtimeReverse:typeof runtime=originalRuntime;
const errorsForward:typeof originalErrors=errors;
const errorsReverse:typeof errors=originalErrors;
const proxyForward:typeof originalProxy=proxy;
const proxyReverse:typeof proxy=originalProxy;
const failure:errors.UserError=new UserError("failure",{cause:"context"});
const command=runtime.defineCommand({name:"hello",params:runtime.S.Object({name:runtime.S.String()}),handler:({params})=>params.name});
const group=runtime.defineGroup({name:"app",children:[command],default:command});
const cloned=runtime.cloneCommandNode(group);
const pending:Promise<void>=proxy.disposeMcpProxies(cloned);
void [runtimeForward,runtimeReverse,errorsForward,errorsReverse,proxyForward,proxyReverse,failure,pending];
