import assert from 'node:assert/strict';
import fs from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { resolve } from 'node:path';
import { recipe, read, fileHash, sha, save, authenticatePreparation } from './common.mjs';
const run=resolve(recipe,'runs/actual-01'),result=read(resolve(run,'RESULT.json')),request=read(resolve(recipe,'CANDIDATE.json'));
authenticatePreparation(request.preparationSha256);
const archivePath=resolve(run,'RECEIPTS.json.gz');assert.equal(fileHash(archivePath),result.archive.archiveSha256);
const archive=JSON.parse(gunzipSync(fs.readFileSync(archivePath),{maxOutputLength:128*1024**2}));
for(const row of archive.rows){const bytes=Buffer.from(row.base64,'base64');assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);}
const count=rows=>({executed:rows.length,passed:rows.filter(row=>row.status==='PASS').length,failed:rows.filter(row=>row.status!=='PASS').map(row=>({id:row.id,status:row.status,failure:row.failure?.text??row.failure?.message}))});
const runtime=Object.fromEntries(['source','installed','moved'].map(profile=>[profile,count(result.runtime.filter(row=>row.profile===profile))]));
const types=Object.fromEntries(['installed','moved'].map(profile=>[profile,{...count(result.types.filter(row=>row.profile===profile)),outcomes:result.types.filter(row=>row.profile===profile).map(row=>({id:row.id,status:row.status,exitCode:row.exitCode,declarations:row.trace?.authenticatedReads.length,diagnostics:row.trace?.diagnostics}))}]));
const loadProof={};
for(const row of archive.rows.filter(row=>row.path.endsWith('/loads.jsonl'))){const label=row.path.split('/').at(-2),events=Buffer.from(row.base64,'base64').toString().trim().split('\n').filter(Boolean).map(JSON.parse);loadProof[label]={actualModuleLoads:events.filter(event=>event.kind==='actual-module-load').length,sourceTransforms:events.filter(event=>event.kind==='actual-module-load'&&event.sourceAdapter).length,packageResolutions:events.filter(event=>event.kind==='entrypoint-resolution'&&event.throughActualPackageExports).length,allowlistDenials:events.filter(event=>event.kind==='strict-load-allowlist-denial').length};}
const summary={schema:'timeout-public-independent-post-execution-review/1',postProcessingOnly:true,at:new Date().toISOString(),recipeCommit:'330ffcb9',recipeSha256:request.preparationSha256,requestSha256:fileHash(resolve(recipe,'CANDIDATE.json')),candidate:result.candidate,baseline:result.baseline,module:result.module,verdict:result.status,attempts:result.attempts,retries:result.retries,startedAt:result.startedAt,finishedAt:result.finishedAt,runtime,types,admission:result.admission,negatives:result.negatives.map(row=>({id:row.id,status:row.status,failure:row.failure,caught:row.observation?.caught,compiler:row.result})),mutants:result.mutants.map(row=>({id:row.id,status:row.status,caseId:row.caseId,qualificationFailure:row.failure,actualFailure:row.result?.failure,activation:row.result?.activations,observations:row.result?.observations})),focusedControls:read(resolve(recipe,'FOCUSED-CONTROLS.json')),loadProof,children:{count:result.children.length,reaped:result.children.filter(row=>row.reaped).length,forced:result.children.filter(row=>row.forced).map(row=>({label:row.label,cause:row.forced})),allChildrenReaped:result.allChildrenReaped,gitSynchronousNatural:result.git.length},integrityGuards:result.guards.length,unexecuted:{runtime:result.unexecutedRuntime,types:result.unexecutedTypes,admission:result.unexecutedAdmission,negatives:result.unexecutedNegatives,mutants:result.unexecutedMutants},archive:result.archive,provenance:{profile:'scoped committed Git-blob composition',buildInputs:269,authorInputs:271,extraBaselineReadme:true,authorOnlyFixtureHelpersExcluded:2,maintainedInventoryFiles:5,staticMaintainedHunks:19,fullHistoryProof:false},boundaries:{native:0,safeJS:0,fullGate:false,publicAccepted:false,originalFreezeAndPreparationUnchanged:true,oldModuleQualificationUnchanged:true,T08Original2353NotRescored:true}};
save(resolve(recipe,'REVIEW.json'),summary);
console.log(JSON.stringify({status:summary.verdict,runtime,types:Object.fromEntries(Object.entries(types).map(([profile,row])=>[profile,{executed:row.executed,passed:row.passed,failed:row.failed}])),admission:result.admission.map(row=>({id:row.id,status:row.status})),negatives:summary.negatives.map(row=>({id:row.id,status:row.status,failure:row.failure?.message})),mutants:summary.mutants.map(row=>({id:row.id,status:row.status,failure:row.qualificationFailure?.message})),children:summary.children,integrityGuards:summary.integrityGuards,unexecuted:summary.unexecuted,archive:summary.archive,reviewSha256:fileHash(resolve(recipe,'REVIEW.json'))},null,2));
