import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const repo='/Users/kjopek/Workspace/safe-bash',relative='tests/compatibility/final-coherent-producer-20260829',root=path.join(repo,relative),own=path.dirname(fileURLToPath(import.meta.url));
const archiveHash='de8741c1be9c870650e92944020fa2785114b7046ef1774af2c27ea79238e17a',archiveSize=974493;
const finalCommit='937f1d9317256c18066d9f74c0ae0bb21842bfaa',freezeCommit='ab46a006a0f324a42c563542e4545ce80de49731';
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const blob=bytes=>crypto.createHash('sha1').update(`blob ${bytes.length}\0`).update(bytes).digest('hex');
const bound=[],checks=[];const started=Date.now();let decodes=0;
function write(name,value){const bytes=Buffer.isBuffer(value)?value:Buffer.from(typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');assert(bytes.length<8388608);fs.writeFileSync(path.join(own,name),bytes,{flag:'wx'});}
function read(filename,expected={}){const stat=fs.lstatSync(filename);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=16777216);if(expected.bytes!==undefined)assert.equal(stat.size,expected.bytes);if(expected.size!==undefined)assert.equal(stat.size,expected.size);if(expected.mode!==undefined)assert.equal(stat.mode&511,typeof expected.mode==='string'?parseInt(expected.mode,8)&511:expected.mode);const bytes=fs.readFileSync(filename);assert.equal(bytes.length,stat.size);if(expected.sha256)assert.equal(sha(bytes),expected.sha256);if(expected.blob)assert.equal(blob(bytes),expected.blob);bound.push({path:filename,bytes:bytes.length,sha256:sha(bytes),mode:stat.mode&511});return bytes;}
function inventory(commit,paths,name){const result=spawnSync('/usr/bin/git',['-c','gc.auto=0','-c','maintenance.auto=false','ls-tree','-rz',commit,'--',...paths],{cwd:repo,maxBuffer:2097152,timeout:10000});write(name+'.stdout',result.stdout);write(name+'.stderr',result.stderr);assert.equal(result.status,0);assert.equal(result.signal,null);assert(!result.error);const rows=new Map();for(const entry of result.stdout.toString().split('\0').filter(Boolean)){const match=/^(\d+) blob ([0-9a-f]{40})\t(.+)$/.exec(entry);assert(match);rows.set(path.join(repo,match[3]),match[2]);}return rows;}
function safeName(name){assert(typeof name==='string'&&name.length>0&&!name.startsWith('/')&&!name.includes('\\')&&!name.includes('\0'));assert(!name.split('/').some(part=>part==='..'||part==='.'||part===''));}
const utf8=new TextDecoder('utf-8',{fatal:true});
function field(bytes){const end=bytes.indexOf(0);return utf8.decode(end<0?bytes:bytes.subarray(0,end));}
function octal(bytes){const text=field(bytes).trim();assert(/^[0-7]*$/.test(text));return text?parseInt(text,8):0;}
function parseTar(bytes){assert(bytes.length<=33554432&&bytes.length%512===0);const members=new Map();let offset=0,terminated=false;while(offset+512<=bytes.length){const header=bytes.subarray(offset,offset+512);if(header.every(value=>value===0)){assert(offset+1024<=bytes.length&&bytes.subarray(offset).every(value=>value===0));terminated=true;break;}let sum=0;for(let index=0;index<512;index++)sum+=index>=148&&index<156?32:header[index];assert.equal(sum,octal(header.subarray(148,156)));const size=octal(header.subarray(124,136)),mode=octal(header.subarray(100,108));assert(Number.isSafeInteger(size)&&size>=0&&size<=16777216);const prefix=field(header.subarray(345,500)),name=field(header.subarray(0,100)),full=prefix?prefix+'/'+name:name;assert(full.startsWith('package/'));const selected=full.slice(8);safeName(selected);assert(!selected.endsWith('AGENTS.md')&&!selected.includes('/xan/')&&!selected.includes('/yq/')&&!selected.includes('/query-core/'));assert(!members.has(selected));assert(header[156]===0||header[156]===48);assert(offset+512+size<=bytes.length);members.set(selected,{path:selected,size,mode,body:bytes.subarray(offset+512,offset+512+size)});assert(members.size<=2048);offset+=512+Math.ceil(size/512)*512;}assert(terminated);return members;}
function expandedTarget(key,target,names){assert(typeof target==='string'&&target.startsWith('./'));safeName(target.slice(2));assert(!target.includes('/ere/')&&!target.includes('worker-entry'));if(target.includes('*')){assert.equal(key,'./contracts/*');assert(target==='./dist/contracts/*.js'||target==='./dist/contracts/*.d.ts');const [prefix,suffix]=target.slice(2).split('*');const matches=names.filter(name=>name.startsWith(prefix)&&name.endsWith(suffix)&&name.length>prefix.length+suffix.length);assert(matches.length>0);for(const name of matches){const replacement=name.slice(prefix.length,name.length-suffix.length);safeName(replacement);assert(!replacement.includes('/'));assert(name.startsWith('dist/contracts/'));}return matches;}assert(!key.includes('*'));assert(names.includes(target.slice(2)));return[target.slice(2)];}
function test(id,action){try{action();checks.push({id,pass:true});}catch(reason){checks.push({id,pass:false,detail:String(reason)});}}
try{
 const selected=['DATA-RECEIPT.json','PRODUCER-RECEIPT.json','PRESEAL.json','SOURCE-INPUTS.json','EMITS.json','SHIPPING.json','CLOSURE.json','TOOLS.json','USABILITY.json','SOURCE-REVIEW.json'];
 const finalObjects=inventory(finalCommit,selected.map(name=>relative+'/'+name),'final-git');const raw={};for(const name of selected){const filename=path.join(root,name);assert(finalObjects.has(filename));raw[name]=read(filename,{blob:finalObjects.get(filename)});}
 assert.equal(sha(raw['DATA-RECEIPT.json']),'d8451028627a01651e4fadf648147c15a39ef04e643dfa2e48a0259be385a50e');
 const data=JSON.parse(raw['DATA-RECEIPT.json']),producer=JSON.parse(raw['PRODUCER-RECEIPT.json']),preseal=JSON.parse(raw['PRESEAL.json']),sources=JSON.parse(raw['SOURCE-INPUTS.json']),shipping=JSON.parse(raw['SHIPPING.json']),emits=JSON.parse(raw['EMITS.json']),closure=JSON.parse(raw['CLOSURE.json']),tools=JSON.parse(raw['TOOLS.json']);
 for(const [name,hash]of [['PRODUCER-RECEIPT.json',data.producerReceiptSha256],['PRESEAL.json',producer.preseal.sha256],['SOURCE-INPUTS.json',producer.sourceSeal.sha256],['TOOLS.json',producer.toolsSeal.sha256],['SHIPPING.json',data.shipManifest.sha256],['CLOSURE.json',data.closure.sha256]])assert.equal(sha(raw[name]),hash);
 const frozen=inventory(freezeCommit,[relative+'/virtual-bash-0.0.0.tgz',relative+'/PRODUCER-RECEIPT.json'],'freeze-git');assert.equal(blob(raw['PRODUCER-RECEIPT.json']),frozen.get(path.join(root,'PRODUCER-RECEIPT.json')));
 const archivePath=path.join(root,'virtual-bash-0.0.0.tgz');assert(frozen.has(archivePath));const compressed=read(archivePath,{bytes:archiveSize,sha256:archiveHash,blob:frozen.get(archivePath)});
 write('PRESEAL.json',{finalCommit,freezeCommit,archive:{path:archivePath,bytes:archiveSize,sha256:archiveHash},helperSha256:sha(read(fileURLToPath(import.meta.url))),bound,controls:['P01-single-star-contracts','P02-escape-private-pattern','P03-malformed-empty-pattern'],scope:'Narrow pattern-aware exports plus remaining private/edge/map/postguards. Original six tamper controls retained without rerun. No product imports/evaluation/extraction.',limits:{compressedBytes:archiveSize,decodedBytes:33554432,concurrentBufferCeiling:100663296,knownOS:20,peak:3},roles:{dataHelper:1,metadataGit:2,syntaxOnly:1,workers:0,loaders:0}});
 decodes++;const decoded=zlib.gunzipSync(compressed,{maxOutputLength:33554432});assert.equal(decoded.length,6195200);const members=parseTar(decoded);assert.equal(members.size,1070);const names=[...members.keys()];
 const actual=[...members.values()].map(row=>({path:row.path,size:row.size,mode:row.mode,sha256:sha(row.body)})).sort((left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path)));assert.deepEqual(actual,shipping.members);assert.equal(sha(Buffer.from(actual.map(row=>JSON.stringify([row.path,row.size,row.mode,row.sha256])+'\n').join(''))),shipping.canonicalSha256);
 test('P01-single-star-contracts',()=>{for(const target of ['./dist/contracts/*.js','./dist/contracts/*.d.ts']){const expanded=expandedTarget('./contracts/*',target,names);assert(expanded.includes(target.endsWith('.d.ts')?'dist/contracts/index.d.ts':'dist/contracts/index.js'));assert(expanded.every(name=>!name.includes('*')));}});
 test('P02-escape-private-pattern',()=>{for(const [key,target]of [['./contracts/*','./dist/contracts/../*.js'],['./contracts/*','./dist/commands/regex-execution/ere/*.js'],['./contracts/../*','./dist/contracts/*.js'],['./contracts/*','./dist/contracts/\\*.js']])assert.throws(()=>expandedTarget(key,target,names));});
 test('P03-malformed-empty-pattern',()=>{for(const target of ['./dist/contracts/**.js','./dist/contracts/*.json','./dist/contracts/*.js\0'])assert.throws(()=>expandedTarget('./contracts/*',target,names));assert.throws(()=>expandedTarget('./contracts/*','./dist/contracts/*.js',[]));});
 assert(checks.every(row=>row.pass));const sourceRoot=preseal.procedure.sourceRoot;assert.equal(sourceRoot,'/private/tmp/safe-bash-final-composition-20260829/source');const sourceMap=new Map();assert.equal(sources.inputs.length,323);
 for(const row of sources.inputs){safeName(row.path);assert(!row.path.endsWith('AGENTS.md')&&!row.path.includes('/xan/')&&!row.path.includes('/yq/')&&!row.path.includes('/query-core/'));const bytes=read(path.join(sourceRoot,row.path),row);assert.equal(blob(bytes),row.blob);sourceMap.set(row.path,bytes);}
 const canonical=sources.inputs.slice().sort((left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path))).map(row=>JSON.stringify([row.path,row.mode,row.blob,row.bytes,row.sha256])+'\n').join('');assert.equal(sha(Buffer.from(canonical)),sources.canonicalRowsSha256);
 assert.equal(emits.rows.length,1068);for(const row of emits.rows){const member=members.get('dist/'+row.path);assert(member);assert.equal(member.size,row.size);assert.equal(member.mode,row.mode);assert.equal(sha(member.body),row.sha256);read(path.join(sourceRoot,'dist',row.path),row);}
 for(const name of ['package.json','README.md'])assert.deepEqual(sourceMap.get(name),members.get(name).body);
 const pkg=JSON.parse(members.get('package.json').body);assert.equal(Object.keys(pkg.dependencies??{}).length,0);const exportBindings=[];function visit(key,value){if(typeof value==='string'){exportBindings.push({key,target:value,matches:expandedTarget(key,value,names)});return;}assert(value&&typeof value==='object'&&!Array.isArray(value));for(const child of Object.values(value))visit(key,child);}for(const [key,value]of Object.entries(pkg.exports)){assert(key==='.'||key.startsWith('./'));if(key.includes('*'))assert.equal(key,'./contracts/*');visit(key,value);}
 assert.equal(closure.privateAssetCount,48);assert.equal(closure.privateAssets.length,48);for(const row of closure.privateAssets){const member=members.get(row.path);assert(member);assert.equal(member.size,row.size);assert.equal(member.mode,row.mode);assert.equal(sha(member.body),row.sha256);assert(!exportBindings.some(binding=>binding.matches.includes(row.path)));}
 const edgeKinds={};for(const edge of closure.edges){assert(members.has(edge.from));edgeKinds[edge.kind]=(edgeKinds[edge.kind]??0)+1;if(edge.target.startsWith('.')){const resolved=path.posix.normalize(path.posix.join(path.posix.dirname(edge.from),edge.target));assert.equal(resolved,edge.resolved);assert(members.has(resolved));assert(members.get(edge.from).body.toString().includes(edge.target));}else assert(edge.target.startsWith('node:'),'nonrelative nonbuiltin needs separate authority');}assert.equal(closure.edges.length,1259);assert.equal(closure.unresolved.length,0);assert.equal(closure.privatePublicExports.length,0);
 const maps=[];for(const [name,row]of members){if(!name.endsWith('.map'))continue;const map=JSON.parse(row.body);assert(Array.isArray(map.sources));const resolvedSources=[];for(let index=0;index<map.sources.length;index++){const selected=path.posix.normalize(path.posix.join(path.posix.dirname(name),map.sourceRoot??'',map.sources[index]));assert(sourceMap.has(selected),'source-map target outside frozen input set: '+selected);if(map.sourcesContent?.[index]!==undefined&&map.sourcesContent[index]!==null)assert.equal(map.sourcesContent[index],sourceMap.get(selected).toString());resolvedSources.push(selected);}maps.push({path:name,sources:resolvedSources});}
 assert.equal(data.compilerExit,0);assert.equal(data.packExit,0);assert.equal(tools.typedFiles,115);assert.equal(sources.excludedCount,40);
 for(const row of [...bound])read(row.path,row);
 const result={verdict:'QUALIFIED_COMPLETE_PRODUCER_DATA_ACCEPT',finalCommit,freezeCommit,archive:{path:archivePath,bytes:archiveSize,sha256:archiveHash},dataReceiptSha256:sha(raw['DATA-RECEIPT.json']),counts:{sources:323,emits:1068,shipping:1070,privateAssets:48,literalEdges:1259,maps:maps.length,typedManifest:115,excludedNames:40},checks,decodes,decodedBytes:decoded.length,exportBindings,edgeKinds,sourceMaps:maps,nonliteralSites:closure.nonliteralSites,shippingCanonicalSha256:shipping.canonicalSha256,sourceCanonicalSha256:sources.canonicalRowsSha256,closureSha256:sha(raw['CLOSURE.json']),postguards:bound.length/2,toolQualification:'Frozen115 type/tool manifest authenticated as metadata; no new compiler/npm execution or exhaustive live module-load census.',historical:'52891ffe partial/HOLD and original6 controls preserved; this separate continuation has3 pattern groups, no retrospective allgreen campaign.',actual:{helpers:1,metadataGit:2,product:0,workers:0,loaders:0,compiler:0,npmInstall:0},elapsedMs:Date.now()-started};
 write('RESULT.json',result);
 write('REPORT.md',`# Final producer DATA completion\n\nQUALIFIED COMPLETE PRODUCER DATA ACCEPT for frozen${finalCommit}, artifact${archiveHash}/974493B, freeze-before-decode${freezeCommit}. Single fresh decode of exact regular/type/size/hash-admitted Buffer, bounded32MiB, no extraction/import/evaluation. Full1070 shipping members/1068 emits/323 frozen source inputs, canonical hashes and postguards verified. All48 private assets,1259 declared literal edges including import.meta URL routes,${maps.length} source maps checked. Public package JSON byte-identical to frozen source; only existing contracts single-star mapping expanded against actual shipping members with literal prefix/suffix. No private asset matches public targets, no new export invented; runtime dependencies empty. Three new pattern/escape controls pass.\n\nOriginal52891ffe export-pattern failure and earlier inspection failure remain unchanged; original six tamper controls are prior evidence, not repeated. Fresh producer sourceRoot is the presealed materialization, not currentHEAD/default-config alignment. No held XAN/yq/query-core content opened.115 types/tool manifests are authenticated DATA; this is not new compiler/type execution, full runtime tool-load closure, or a normal default-build/install/smoke pass. Historical compiler/pack zero results stay bound to their producer receipts. Computed/provider edges remain explicitly qualified, not static completeness or Worker execution proof.\n\nFinal smoke still needs actual manifest/cardinality-aware layout materialization, loader/tool/entry/argv/permissions/capture/work-fit bindings and fresh ROOT activation. No build success or runtime equivalence inferred beyond authenticated historical producer result. Peak/RSS/Gitphysical/globalcensus claims remain excluded. One helper/two metadata children returned normally, no product/Workers/native/network/privateengine; raw capture established before Node. Frozen input postguards do not substitute for live-default config authority.\n`);
 console.log(JSON.stringify({verdict:result.verdict,counts:result.counts,checks,edgeKinds,receiptSha256:sha(fs.readFileSync(path.join(own,'RESULT.json')))}));
}catch(reason){console.error(reason);write('FAILURE.json',{primaryPresent:true,detail:String(reason),stack:reason?.stack,checks,decodes,bound,elapsedMs:Date.now()-started});process.exitCode=1;}
