import {lstatSync,readFileSync,writeFileSync,readdirSync,mkdirSync,chmodSync,createReadStream,realpathSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const own=fileURLToPath(new URL('.',import.meta.url));
const root=dirname(own.slice(0,-1));
const future=join(root,'FUTURE-ACTUAL-01');
const started=Date.now(),deadline=started+480000;
const runtimeHash='56f2df9e895c86d289682754dac22e83cc26d0a77d9e96631eb4fa0488f02811';
const stopHash='c104c1eb9bb08f258bb063f8a84c925137081439a7e2a81019f8a6f0c38738d7';
const inventoryHash='aa7ae40bdfe1821a2cd493cc5408be9662003eb02784d05171e6b89a3a0d3a15';
function clock(){if(Date.now()>deadline)throw Error('preservation deadline');}
function sha(bytes){return createHash('sha256').update(bytes).digest('hex');}
function read(path,max=1048576){clock();const stat=lstatSync(path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>max||realpathSync(path)!==path)throw Error('bounded regular file');const bytes=readFileSync(path);if(bytes.length!==stat.size)throw Error('size changed');return {bytes,mode:stat.mode&511,size:bytes.length,sha256:sha(bytes)};}
function directory(path){const stat=lstatSync(path);if(!stat.isDirectory()||stat.isSymbolicLink()||realpathSync(path)!==path)throw Error('directory identity');}
function requireHash(bytes,expected){if(sha(bytes)!==expected)throw Error('bound digest mismatch');}
function judge(runtime,stop){if(runtime.schema!==2||runtime.outcome.retainedUnknown!==true||runtime.outcome.exitCode!==2||stop.disposition!=='STOP_UNCONFIRMED'||stop.ownerRetired!==false||stop.WorkerExitEvents!==0||stop.processClosed!==true||stop.recovery!=='NONE_AUTHORIZED'||stop.archive!==false||stop.cleanup!==false)throw Error('unknown disposition');const rows=runtime.outcome.rows;if(!Array.isArray(rows)||rows.length!==13||!Array.isArray(stop.rows)||stop.rows.length!==13)throw Error('cell count');let exits=0;for(let index=0;index<13;index++){const row=rows[index],other=stop.rows[index];if(row.cell!==index+1||row.processClosed!==true||row.receiptSha256!==other.receiptSha256||row.disposition!==other.disposition||row.WorkerExitEvents!==other.WorkerExitEvents||row.rootRetirement!==other.rootRetirement)throw Error('row binding');if(index<12){if(row.disposition!=='PASS'||row.rootRetirement!=='RETIRED'||row.WorkerExitEvents!==(index<3?0:1))throw Error('author observation');}else if(row.disposition!=='STOP_UNCONFIRMED'||row.purpose!=='persistent'||row.layout!=='built'||row.rootRetirement!=='UNCONFIRMED'||row.WorkerExitEvents!==0)throw Error('final uncertainty');exits+=row.WorkerExitEvents;}if(exits!==9)throw Error('exit count');return rows;}
const nodeStat=lstatSync(process.execPath);if(!nodeStat.isFile()||nodeStat.isSymbolicLink()||nodeStat.size>160000000)throw Error('Node tool');const toolHash=createHash('sha256');let toolBytes=0;for await(const chunk of createReadStream(process.execPath,{highWaterMark:65536})){clock();toolBytes+=chunk.length;if(toolBytes>nodeStat.size)throw Error('tool changed');toolHash.update(chunk);}const nodeSha=toolHash.digest('hex');if(toolBytes!==nodeStat.size||nodeSha!=='5c899797c4eb8f1db5563eea56538342ddb3e9276ee1b04a5a1f0f1023d2b011')throw Error('Node hash');
directory(future);const inventoryInput=read(join(root,'CASE-INVENTORY.json'));requireHash(inventoryInput.bytes,inventoryHash);const inventory=JSON.parse(inventoryInput.bytes);if(inventory.cases.length!==13)throw Error('fixed cases');
const allowed=new Set(['ACTIVATION.json','RUNTIME-RESULT.json','STOP.json','EMERGENCY.json','RESULT.json','outer.stdout','outer.stderr','bootstrap.stdout','bootstrap.stderr','owner.stdout','owner.stderr']);for(const cell of inventory.cases){allowed.add(cell.folder+'.stdout');allowed.add(cell.folder+'.stderr');}
const selected=[];const futureNames=readdirSync(future).sort();for(const name of futureNames){if(!allowed.has(name))throw Error('unexpected future output');selected.push({source:join(future,name),relative:'FUTURE-ACTUAL-01/'+name});}
const missing=[];for(const cell of inventory.cases){if(typeof cell.folder!=='string'||!/^[A-Za-z0-9-]+$/.test(cell.folder))throw Error('case folder');const home=join(root,'CASES',cell.folder);directory(home);for(const name of ['RESULT.json','JOURNAL.jsonl','EMERGENCY.json']){const source=join(home,name);try{lstatSync(source);}catch(reason){if(reason.code==='ENOENT'){missing.push({case:cell.folder,name});continue;}throw reason;}selected.push({source,relative:'CASES/'+cell.folder+'/'+name});}}
if(selected.length>256)throw Error('file count');let total=0;const retained=[];for(const row of selected){const input=read(row.source);total+=input.size;if(total>16777216)throw Error('aggregate cap');retained.push({...row,...input});}
const byName=new Map(retained.map(row=>[row.relative,row]));for(const name of ['ACTIVATION.json','RUNTIME-RESULT.json','STOP.json','outer.stdout','outer.stderr'])if(!byName.has('FUTURE-ACTUAL-01/'+name))throw Error('missing terminal input');const runtimeInput=byName.get('FUTURE-ACTUAL-01/RUNTIME-RESULT.json'),stopInput=byName.get('FUTURE-ACTUAL-01/STOP.json');requireHash(runtimeInput.bytes,runtimeHash);requireHash(stopInput.bytes,stopHash);if(byName.get('FUTURE-ACTUAL-01/outer.stdout').size!==0||byName.get('FUTURE-ACTUAL-01/outer.stderr').size!==0)throw Error('outer capture changed');
const runtime=JSON.parse(runtimeInput.bytes),stop=JSON.parse(stopInput.bytes);const rows=judge(runtime,stop);const activation=JSON.parse(byName.get('FUTURE-ACTUAL-01/ACTIVATION.json').bytes);if(activation.pid!==84282||activation.profileSha256!=='dbb576cdb97945543ef15cb02548f3cbe12875cbeab4bb01af2d60addf5dbffa'||activation.grantSha256!=='b0cf01197a9ab3fdf5439540759541b04c923f10004b16e1620f17f9534ecc78')throw Error('activation binding');
const caseSummaries=[];for(let index=0;index<13;index++){const cell=inventory.cases[index];const retainedCase=byName.get('CASES/'+cell.folder+'/RESULT.json');if(!retainedCase)throw Error('missing case result');requireHash(retainedCase.bytes,rows[index].receiptSha256);const receipt=JSON.parse(retainedCase.bytes);if(receipt.id!=='L02-followup/'+cell.purpose+'-v1'||receipt.layout!==cell.layout||receipt.retirementState!==rows[index].rootRetirement||receipt.exits!==rows[index].WorkerExitEvents)throw Error('case row consistency');caseSummaries.push({cell:index+1,purpose:cell.purpose,layout:cell.layout,disposition:rows[index].disposition,WorkersReported:receipt.Workers,recordedExits:receipt.exits,retirementState:receipt.retirementState,rootRetained:receipt.rootRetained,handlesRetained:receipt.handlesRetained,retainedCharges:receipt.retainedCharges,primary:receipt.primary,cleanup:receipt.cleanup,termination:receipt.termination,receiptSha256:retainedCase.sha256});}
const controls=[];function rejects(id,body){let rejected=false;try{body();}catch{rejected=true;}controls.push({id,pass:rejected});if(!rejected)throw Error('tamper accepted '+id);}
rejects('T01-bound-runtime-byte',()=>{const changed=Buffer.from(runtimeInput.bytes);changed[0]^=1;requireHash(changed,runtimeHash);});
rejects('T02-sticky-false',()=>{const changed=JSON.parse(runtimeInput.bytes);changed.outcome.retainedUnknown=false;judge(changed,stop);});
rejects('T03-final-retirement-fabrication',()=>{const changed=JSON.parse(runtimeInput.bytes);changed.outcome.rows[12].WorkerExitEvents=1;changed.outcome.rows[12].rootRetirement='RETIRED';judge(changed,stop);});
rejects('T04-pass-count-contradiction',()=>{const changed=JSON.parse(runtimeInput.bytes);changed.outcome.rows[0].disposition='STOP_UNCONFIRMED';judge(changed,stop);});
const target=join(own,'DATA');mkdirSync(target);const manifest=[];for(const row of retained){clock();const output=join(target,row.relative);mkdirSync(dirname(output),{recursive:true});writeFileSync(output,row.bytes,{flag:'wx',mode:row.mode});chmodSync(output,row.mode);const copy=read(output);if(copy.sha256!==row.sha256||copy.mode!==row.mode||copy.size!==row.size)throw Error('copy authentication');manifest.push({source:row.source,path:row.relative,size:row.size,mode:row.mode,sha256:row.sha256});}
for(const row of retained){const current=read(row.source);if(current.sha256!==row.sha256||current.mode!==row.mode||current.size!==row.size)throw Error('source changed during preservation');}if(JSON.stringify(readdirSync(future).sort())!==JSON.stringify(futureNames))throw Error('future entries changed');
const manifestBytes=Buffer.from(JSON.stringify({schema:1,files:manifest,totalFiles:manifest.length,totalBytes:total,byteAndModeExact:true,sourceUnmodified:true},null,2)+'\n');if(manifestBytes.length>262144)throw Error('manifest capacity');writeFileSync(join(own,'MANIFEST.json'),manifestBytes,{flag:'wx'});
const result={schema:1,phase:'SEPARATE_ROOT_AUTHORIZED_DATA_RETENTION_NOT_CAMPAIGN_PUBLICATION',startedAt:new Date(started).toISOString(),completedAt:new Date().toISOString(),files:manifest.length,bytes:total,manifestSha256:sha(manifestBytes),controls,authorObservedPass:12,stopUnconfirmed:1,unrun:0,recordedWorkerExits:9,finalRecordedExits:0,finalRootRetirement:'UNCONFIRMED',retainedUnknown:true,ownerPID:84282,toolSession:98687,toolReturnCode:2,toolObservationSource:'ROOT-supplied and prior tool return; not an OS census',caseSummaries,missingOptionalOutputs:missing,startupOuterBytes:[0,0],startupQualification:'RESERVED_POSTCHECKED_NO_EOF_OR_PREWRITE_ENFORCEMENT_CLAIM',logicalHandleQualification:'receipt records retained root/handle/charges; no claim a live JavaScript reference survives known process close',sourceProfileReference:activation.profileSha256,activationSha256:byName.get('FUTURE-ACTUAL-01/ACTIVATION.json').sha256,runtimeSha256:runtimeHash,stopSha256:stopHash,NodeTool:{path:process.execPath,size:toolBytes,sha256:nodeSha},helperSha256:sha(read(fileURLToPath(import.meta.url),100000).bytes),actualWorkersStartedThisPhase:0,childProcessesThisHelper:0,recovery:false,signals:false,cleanup:false,originalBudgetNotRescored:true};const resultBytes=Buffer.from(JSON.stringify(result,null,2)+'\n');if(resultBytes.length>131072)throw Error('result capacity');writeFileSync(join(own,'RESULT.json'),resultBytes,{flag:'wx'});console.log(JSON.stringify({files:result.files,bytes:total,manifestSha256:result.manifestSha256,resultSha256:sha(resultBytes),tamperControls:4,passed:4,authorObservedPass:12,stopUnconfirmed:1,recordedWorkerExits:9,finalRecordedExits:0,retainedUnknown:true,WorkersStarted:0,dispatch:false}));
