import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const own=path.dirname(new URL(import.meta.url).pathname),repo=process.cwd(),author='tests/integration/agent-bash-coherent-b2-preflight-20260829/completion-r9/actual-v2',commit='1a4c02b9bb72625480b3eac3ed076ed65eee522e';
const hash=raw=>crypto.createHash('sha256').update(raw).digest('hex');
const read=filename=>{const stat=fs.lstatSync(filename);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=16777216,filename);const raw=fs.readFileSync(filename);assert.equal(raw.length,stat.size);return raw;};
const record=(name,value)=>fs.writeFileSync(path.join(own,name),JSON.stringify(value,null,2)+'\n',{flag:'wx'});
const refs=['RAW-MANIFEST.json','RECEIPT.json','HANDOFF.md'];
if(!fs.existsSync(path.join(own,'objects.stdout'))){const stdout=fs.openSync(path.join(own,'objects.stdout'),'wx'),stderr=fs.openSync(path.join(own,'objects.stderr'),'wx');let child;try{child=spawnSync('/usr/bin/git',['cat-file','--batch'],{cwd:repo,input:refs.map(name=>commit+':'+author+'/'+name).join('\n')+'\n',stdio:['pipe',stdout,stderr],timeout:20000});}finally{fs.closeSync(stdout);fs.closeSync(stderr);}assert.equal(child.status,0);}
const gitObjects=read(path.join(own,'objects.stdout'));let offset=0;for(const name of refs){const end=gitObjects.indexOf(10,offset),[oid,kind,sizeText]=gitObjects.subarray(offset,end).toString().split(' '),size=Number(sizeText),raw=gitObjects.subarray(end+1,end+1+size);assert.equal(kind,'blob');assert.equal(crypto.createHash('sha1').update(Buffer.from(`blob ${size}\0`)).update(raw).digest('hex'),oid);assert(raw.equals(read(path.join(repo,author,name))));offset=end+size+2;}assert.equal(offset,gitObjects.length);
const manifestRaw=read(path.join(repo,author,'RAW-MANIFEST.json'));assert.equal(hash(manifestRaw),'138b6b2f81551506220d82a46d82210ca09782499ba7faf876e8f2b9512538b3');const manifest=JSON.parse(manifestRaw),receipt=JSON.parse(read(path.join(repo,author,'RECEIPT.json')));assert.equal(hash(read(path.join(repo,author,'RECEIPT.json'))),'87845ae146e6c73ae43dcda4bf1b5443320b9387d60177565bfdd1be64df57f8');
const payloads=new Map();let total=0;for(const row of manifest.files){assert(row.path&&!path.isAbsolute(row.path)&&!row.path.split('/').includes('..'));assert(!payloads.has(row.path));const raw=read(path.join(repo,author,row.path));assert.equal(raw.length,row.bytes);assert.equal(hash(raw),row.sha256);total+=raw.length;payloads.set(row.path,{row,raw});}assert.equal(payloads.size,196);assert.equal(total,10155453);
if(!fs.existsSync(path.join(own,'AUTHENTICATION.json')))record('AUTHENTICATION.json',{authorCommit:commit,payloads:payloads.size,bytes:total,manifestSha256:hash(manifestRaw),allRegularFileHashesVerified:true,at:new Date().toISOString()});
const checks=[],controls=[],details={};
function check(id,body){try{const value=body();checks.push({id,pass:true});if(value!==undefined)details[id]=value;}catch(error){checks.push({id,pass:false,error:String(error)});}}
function same(left,right){if(left===null||right===null||typeof left!=='object'||typeof right!=='object'){assert(Object.is(left,right));return;}const leftKeys=Reflect.ownKeys(left).sort(),rightKeys=Reflect.ownKeys(right).sort();assert.equal(leftKeys.length,rightKeys.length);for(let index=0;index<leftKeys.length;index++){assert.equal(leftKeys[index],rightKeys[index]);const leftData=Object.getOwnPropertyDescriptor(left,leftKeys[index]),rightData=Object.getOwnPropertyDescriptor(right,rightKeys[index]);assert(Object.hasOwn(leftData,'value')&&Object.hasOwn(rightData,'value'));same(leftData.value,rightData.value);}}
function json(filename){const entry=payloads.get(filename);assert(entry,filename);return JSON.parse(entry.raw);}
function objects(value,result=[]){if(value&&typeof value==='object'){result.push(value);for(const item of Object.values(value))objects(item,result);}return result;}
function strings(value,result=[]){if(typeof value==='string')result.push(value);else if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){result.push(key);strings(item,result);}return result;}
const runtime=json('evidence/payload/runtime/RESULT.json'),classification=json('evidence/payload/administration/RAW-CLASSIFICATION-v2.json'),post=json('evidence/payload/administration/POSTGUARDS.json'),grantRaw=payloads.get('evidence/payload/runtime/ROOT-GO.json').raw,grant=JSON.parse(grantRaw);
check('root-grant-source-review-and-window',()=>{assert.equal(grantRaw.length,1081);assert.equal(hash(grantRaw),'26aa0d1c7c6a34d576fae7b326dc08c600fc5ae7bae4753609ea78b9224d3e30');assert.equal(grant.reviewCommit,'8c88c15553488aacee8eb469fbd012fd00f8fb27');assert.equal(grant.packetSha256,'5b4a12e14081d6c95f7805358737d32008b0b7f5844413b485e77a81fb1b807d');assert.equal(receipt.reviewReceiptSha256,'c65013b32f58e6335d1f4a232d97691c8e11dc5dddf08ca7a333ddc72e3db48c');assert(Date.parse(receipt.window.admission)>=Date.parse(grant.notBefore));assert(Date.parse(receipt.window.admission)<=Date.parse(receipt.window.externalLatest));assert(Date.parse(receipt.window.terminalObserved)<Date.parse(grant.activeDeadline));assert(Date.parse(post.checkedAt)<Date.parse(grant.deadline));assert.equal(grant.activeDeadline,'2026-08-29T17:57:00.000Z');assert.equal(grant.deadline,'2026-08-29T18:00:00.000Z');});
check('author-summary-and-retirement',()=>{assert.equal(runtime.status,'PASS');assert.equal(runtime.completed.length,41);assert.equal(new Set(runtime.completed).size,41);same(runtime.retirement.failures,[]);assert.equal(runtime.retirement.children,41);assert.equal(runtime.retirement.attemptedBytes,344330);assert.equal(runtime.retirement.storedBytes,344330);assert.equal(classification.rows.length,41);for(const row of classification.rows){assert.equal(row.exitCode,row.closeCode);assert.equal(row.signal,null);assert(Number.isInteger(row.pid)&&row.pid>0);}return{roles:classification.rows.map(row=>({role:row.role,pid:row.pid,exit:row.exitCode,close:row.closeCode})),qualification:'Cross-checked recorded exit/close rows; raw event audit separately required'};});
const childRaw=(role,stream)=>{const matches=[...payloads].filter(([filename])=>path.posix.dirname(filename)==='evidence/payload/runtime/children'&&path.posix.basename(filename).slice(3)===role+'.'+stream);assert.equal(matches.length,1,role+' '+stream);return matches[0][1].raw;};
let passCases=0,diagnostics=0,mutants=0,restores=0,bindings=0;const caseIdentities={},histogram={};
check('all-child-raw-bytes-and-finite-outcomes',()=>{let stdoutBytes=0,stderrBytes=0;for(const row of classification.rows){const stdout=childRaw(row.role,'stdout'),stderr=childRaw(row.role,'stderr');assert.equal(stdout.length,row.stdoutBytes);assert.equal(stderr.length,row.stderrBytes);stdoutBytes+=stdout.length;stderrBytes+=stderr.length;histogram[row.exitCode]=(histogram[row.exitCode]??0)+1;assert.equal(row.classification?.accepted??row.kind==='install',true,row.role);if(row.kind==='retained'||row.kind==='restore'||row.kind==='mutant'){const records=stdout.toString().trim().split('\n').filter(Boolean).map(line=>JSON.parse(line));const cases=records.filter(item=>typeof item.pass==='boolean'&&typeof item.id==='string');assert(cases.length>0,row.role);assert.equal(new Set(cases.map(item=>item.id)).size,cases.length);if(row.kind!=='mutant'){assert(cases.every(item=>item.pass));assert.equal(row.exitCode,0);for(const item of cases){if(Object.hasOwn(item,'cleanupFailure'))assert.equal(item.cleanupFailure,false);if(Object.hasOwn(item,'created')&&Object.hasOwn(item,'disposed'))assert.equal(item.created,item.disposed);}}if(row.kind==='retained'){assert.equal(cases.length,row.classification.cases);passCases+=cases.length;(caseIdentities[row.layout]??=[]).push({role:row.role,ids:cases.map(item=>item.id)});}else if(row.kind==='restore')restores++;else{mutants++;assert.equal(row.exitCode,1);assert(cases.some(item=>!item.pass));details[row.role]={classification:row.classification,failedCases:cases.filter(item=>!item.pass)};}}else if(row.kind==='type'){const found=[...stdout.toString().matchAll(/\((\d+),(\d+)\): error TS(\d+): ([^\r\n]+)/g)].map(match=>({line:Number(match[1]),column:Number(match[2]),code:Number(match[3]),message:match[4]}));same(found,row.classification.diagnostics);assert.equal(found.length,row.classification.negative?8:0);assert.equal(row.exitCode,row.classification.negative?2:0);diagnostics+=found.length;}else if(row.kind==='binding'){bindings++;assert.equal(row.exitCode,1);details[row.role]={classification:row.classification,stdout:stdout.toString(),stderr:stderr.toString()};}else assert.equal(row.role,'offline-install');}assert.equal(stdoutBytes,304439);assert.equal(stderrBytes,39891);assert.equal(passCases,672);assert.equal(diagnostics,24);assert.equal(mutants,7);assert.equal(restores,7);assert.equal(bindings,2);same(histogram,{'0':29,'1':9,'2':3});return{passCases,diagnostics,mutants,restores,bindings,stdoutBytes,stderrBytes,histogram,caseIdentities};});
check('three-layout-byte-mode-postguards',()=>{assert.equal(post.packetPins,32);assert.equal(post.sourceInputs,309);assert.equal(post.actualEmitted,1012);assert.equal(post.installedPathAbsentAfterPhysicalRename,true);assert.equal(post.layouts.length,3);const inventories=[];for(const layout of post.layouts){assert.equal(layout.inventory.length,1014);assert.equal(layout.modeMismatches,0);const expected=layout.expectedMode==='0600'?384:420;assert(['0644','0600'].includes(layout.expectedMode));assert.equal(expected,layout.expectedMode==='0600'?(420&~0o77):420);for(const row of layout.inventory)assert.equal(row.mode,expected);inventories.push(layout.inventory.map(row=>({path:row.path,bytes:row.bytes,sha256:row.sha256})));}same(inventories[0],inventories[1]);same(inventories[0],inventories[2]);same(runtime.installedIdentity.before,runtime.installedIdentity.after);return post.layouts.map(({inventory,...row})=>row);});
check('loader-traces-bindings-and-prepared-hashes',()=>{const traceFiles=[...payloads].filter(([filename])=>filename.endsWith('.jsonl'));assert.equal(traceFiles.length,34);const bindingFiles=[...payloads].filter(([filename])=>filename.includes('/bindings/')&&filename.endsWith('.json'));assert.equal(bindingFiles.length,34);let recordCount=0,traceBytes=0;const kinds={};for(const [filename,{raw}] of traceFiles){const stem=path.posix.basename(filename,'.jsonl');const matches=bindingFiles.filter(([bindingPath])=>path.posix.basename(bindingPath,'.json')===stem);assert.equal(matches.length,1,'exact binding basename '+stem);const binding=JSON.parse(matches[0][1].raw),allowed=new Set(strings(binding).filter(value=>/^[0-9a-f]{64}$/.test(value)));const records=raw.toString().trim().split('\n').map(line=>JSON.parse(line));for(const item of records){kinds[item.kind]=(kinds[item.kind]??0)+1;if(item.kind==='authenticated-source-prepared')assert(allowed.has(item.sha256),'prepared hash absent from role binding '+filename+' '+item.member);else assert.equal(item.kind,'binding-refusal');}recordCount+=records.length;traceBytes+=raw.length;}assert.equal(recordCount,8025);assert.equal(traceBytes,2254280);same(kinds,{'authenticated-source-prepared':8023,'binding-refusal':2});return{recordCount,traceBytes,kinds,qualification:'Individual loader exit remains UNOBSERVED; hash membership is not evaluation proof'};});
check('raw-lifecycle-events-present-and-closed',()=>{const candidates=[];for(const [filename,{raw}] of payloads){if(!filename.endsWith('.json')||!filename.includes('/children/'))continue;const value=JSON.parse(raw);candidates.push({filename,value});}details.lifecycleCandidates=candidates.map(({filename,value})=>({filename,keys:Object.keys(value)}));assert(candidates.length>0,'raw lifecycle file not located in exact children directory; no ancestor inference');const eventObjects=candidates.flatMap(({value})=>objects(value));for(const row of classification.rows){const related=eventObjects.filter(value=>value.pid===row.pid);assert(related.some(value=>Object.values(value).includes('exit')),'raw exit event not independently decoded '+row.role);assert(related.some(value=>Object.values(value).includes('close')),'raw close event not independently decoded '+row.role);}});
check('identity-receipts-disjoint-authenticated-payload-links',()=>{const root=path.join(repo,author,'evidence/identities'),identityRows=[];function visit(folder){for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const filename=path.join(folder,entry.name);if(entry.isDirectory())visit(filename);else{const raw=read(filename);identityRows.push({path:path.relative(root,filename),value:JSON.parse(raw),sha256:hash(raw)});}}}visit(root);assert.equal(identityRows.length,196);const identities=identityRows.map(row=>new Set(strings(row.value)));for(const [filename,{row}] of payloads){assert(identities.some(values=>values.has(row.sha256)&&(values.has(filename)||values.has(row.source))),filename+' identity linkage');}return{count:identityRows.length,sample:identityRows[0]};});
check('cache-and-preserved-reader-error',()=>{const failure=json('evidence/payload/administration/DATA-READER-FAILURE.json');assert(strings(failure).some(value=>value.includes('cases.map is not a function')));assert.equal(post.census.snapshotRaceCount,0);assert.equal(post.census.atomic,false);assert.equal(post.census.peakProof,false);assert.equal(post.census.observedCacheBytes,932606);assert.equal(runtime.accounting.totalSnapshotRaces,17);return failure;});
for(const [id,body] of [['byte-tamper',()=>{const first=[...payloads.values()].find(item=>item.raw.length>0),changed=Buffer.from(first.raw);changed[0]^=1;assert.equal(hash(changed),first.row.sha256);}],['pass-bit-tamper',()=>same({id:'R01',pass:true},{id:'R01',pass:false})],['diagnostic-message-tamper',()=>same({line:9,column:24,code:2353,message:'expected'},{line:9,column:24,code:2353,message:'different'})],['installed-mode-escalation',()=>assert.equal(420,420&~0o77)]]){let rejected=false;try{body();}catch{rejected=true;}controls.push({id,rejected});}
const gaps=[];
gaps.push('Exact mutant defect expectations and per-mutant changed/restored path-hash pairing require further independent binding interpretation; author accepted classifications alone do not discharge this.');
gaps.push('Packet 7320-byte content, pinned installer origin/umask derivation, and unused-binding refusal source expectations are bound by author receipts but not independently reinterpreted here.');
const verdict=checks.every(row=>row.pass)&&gaps.length===0?'FINITE DATA ACCEPT':'FINITE DATA HOLD';
const result={verdict,authorCommit:commit,authenticatedPayloads:196,payloadBytes:10155453,checks,controls,details,gaps,package:{members:1014,sha256:'2fe071e2bfac5ef5c81dc7e475e059091f6add65cd7411dfcfbf0ce7f51f2eca',source:'3adc676a0ab638c9788ef007e465931d65d2c6fe'},qualifications:['HOLD is incomplete independent audit, not an observed product regression','No product/compiler/Worker/loader/npm/install executed; no archive decoding','No transfer to final1070 package or new local-a/ERE/K08','Individual loader exits UNOBSERVED; author parent retirement known-role only, not full census','49 runtime known roles is author conservative accounting, not reviewer full-process census; mutable cache best-effort non-atomic not peak quota','Corrected author DATA reader error retained, no product retry'],reviewResources:{knownStartsThroughPublication:20,maximumKnownStarts:20,conservativePeak:3,dataHelperFiles:1,dataHelperInvocations:2,payloadBuffers:10155453,captureCap:33554432,logicalCap:167772160,publicationReserve:16777216,qualification:'No payload copies beyond bounded memory and owned textual evidence; OS/RSS/Git physical excluded'},at:new Date().toISOString()};record('REVIEW-RECEIPT.json',result);console.log(JSON.stringify({verdict,checks,controls,gaps,receiptSha256:hash(read(path.join(own,'REVIEW-RECEIPT.json'))),receiptBytes:read(path.join(own,'REVIEW-RECEIPT.json')).length},null,2));
