// Frozen SQLAlchemy 2.0.54 identifier/DDL profile; not a DBAPI driver.
import type { DatabaseDialectDescriptor } from "./descriptor.js";
export const postgresql: DatabaseDialectDescriptor = {
  "doublePercent": true,
  "name": "postgresql",
  defaultDriver: 'psycopg2',
  drivers: { psycopg2: { module: 'psycopg2' }, psycopg: { module: 'psycopg' }, pg8000: { module: 'pg8000' }, asyncpg: { module: 'asyncpg' }, psycopg2cffi: { module: 'psycopg2cffi' } },
  "quoteStart": "\"",
  "quoteEnd": "\"",
  "reserved": [
    "all",
    "analyse",
    "analyze",
    "and",
    "any",
    "array",
    "as",
    "asc",
    "asymmetric",
    "authorization",
    "between",
    "binary",
    "both",
    "case",
    "cast",
    "check",
    "collate",
    "column",
    "constraint",
    "create",
    "cross",
    "current_catalog",
    "current_date",
    "current_role",
    "current_schema",
    "current_time",
    "current_timestamp",
    "current_user",
    "default",
    "deferrable",
    "desc",
    "distinct",
    "do",
    "else",
    "end",
    "except",
    "false",
    "fetch",
    "for",
    "foreign",
    "freeze",
    "from",
    "full",
    "grant",
    "group",
    "having",
    "ilike",
    "in",
    "initially",
    "inner",
    "intersect",
    "into",
    "is",
    "isnull",
    "join",
    "leading",
    "left",
    "like",
    "limit",
    "localtime",
    "localtimestamp",
    "natural",
    "new",
    "not",
    "notnull",
    "null",
    "of",
    "off",
    "offset",
    "old",
    "on",
    "only",
    "or",
    "order",
    "outer",
    "over",
    "overlaps",
    "placing",
    "primary",
    "references",
    "returning",
    "right",
    "select",
    "session_user",
    "similar",
    "some",
    "symmetric",
    "table",
    "then",
    "to",
    "trailing",
    "true",
    "union",
    "unique",
    "user",
    "using",
    "variadic",
    "verbose",
    "when",
    "where",
    "window",
    "with"
  ],
  "illegalInitial": [
    "$",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
  ],
  "typedTypes": {"TimeDelta": "INTERVAL", "DateTime": "TIMESTAMP WITHOUT TIME ZONE"},
};
