import {strict as assert} from 'node:assert';import {readFileSync,writeFileSync} from 'node:fs';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import {judge} from './receipt-gate.mjs';import {createRetirementLatch} from './retirement-latch.mjs';
const own=fileURLToPath(new URL('.',import.meta.url));const inventory=JSON.parse(readFileSync(join(own,'CASE-INVENTORY.json'),'utf8'));const rows=[];function test(id,body){try{body();rows.push({id,pass:true});}catch(error){rows.push({id,pass:false,message:error instanceof Error?error.message:'nonError'});}}
function fixture(purpose='normal'){const cell=inventory.cases.find(row=>row.purpose===purpose);const config={...JSON.parse(readFileSync(join(own,'CASES',cell.folder,'CASE.json'),'utf8')),caseSha256:cell.caseSha256};const names=['ere/errors.js','ere/limits.js','ere/transport/accounting.js','ere/transport/protocol.js','ere/transport/validation.js','ere/transport/owner.js','ere/transport/root.js'].map(suffix=>config.packageRelative+'/'+suffix).concat('worker-bridge.mjs');const kinds=purpose==='persistent'?['case-entry','attempt','constructed','setup-fault','termination-requested','setup-fault','termination-rejected','execute-settled','close-settled','close-settled','unconfirmed','retained-root-and-handles']:['case-entry','attempt','constructed','post','posted','execute-settled','termination-requested','worker-exit','stdout-end','stdout-close','stderr-end','stderr-close','termination-fulfilled','close-settled','close-settled','owner-retired'];let closeIndex=0;const trace=kinds.map((kind,index)=>({seq:index+1,at:index+1,kind,detail:kind==='close-settled'?((++closeIndex===1?'session':'root')+':'+(purpose==='normal'?'fulfilled':'rejected')):kind==='execute-settled'?(purpose==='normal'?'fulfilled':'rejected'):'',attemptId:kind==='case-entry'?0:1}));const receipt={schema:1,id:config.id,purpose,layout:config.layout,caseSha256:cell.caseSha256,packageSha256:config.packageSha256,assertions:true,passed:purpose==='normal',retirementState:purpose==='normal'?'RETIRED':'UNCONFIRMED',primary:purpose==='normal'?{present:false}:{present:true,kind:'boolean',value:false},cleanup:{present:false},termination:purpose==='normal'?{present:false}:{present:true,kind:'boolean',value:false,route:'promise-rejection'},attempts:1,Workers:1,exits:purpose==='normal'?1:0,stdout:purpose==='normal'?1:0,stderr:purpose==='normal'?1:0,stdoutClosed:purpose==='normal'?1:0,stderrClosed:purpose==='normal'?1:0,rootRetained:true,handlesRetained:1,retainedCharges:purpose!=='normal',captureFault:false,loads:names.map(path=>({path,sha256:config.modules.find(row=>row.path===path).sha256})),trace,assertionFailure:{present:false},nestedObservation:'NOT_OBSERVED'};const processKinds=['admit','created','spawn','stdoutEnd','stderrEnd','stdoutClose','stderrClose','exit','close','retired'];const code=purpose==='normal'?0:2;const processRow={schema:3,role:'case',ownerPid:200,clockDomain:'owner:200',pid:100,admitted:true,created:true,spawned:true,exited:true,closed:true,code,signal:null,exitCode:code,exitSignal:null,stdoutBytes:0,stderrBytes:0,stdoutClosed:true,stderrClosed:true,stdoutEnded:true,stderrEnded:true,state:'RETIRED',captureComplete:true,captureTruncated:false,primary:{present:false},secondary:[],termRequested:false,killRequested:false,trace:processKinds.map((kind,index)=>({seq:index+1,at:index+1,kind,...(kind==='created'||kind==='spawn'?{pid:100}:kind==='exit'||kind==='close'?{code,signal:null}:{})}))};return {receipt,processRow,config};}

function failure(latch,body){try{body();assert.fail('expected failure');}catch(reason){latch.recordPrimary(reason);return reason;}}
test('F01-v2-normal',()=>{const row=fixture();assert.equal(judge(row.receipt,row.processRow,row.config),'PASS');});
for(const [id,keys]of [['F01-v2-stdout',['stdoutEnded']],['F01-v2-stderr',['stderrEnded']],['F01-v2-both',['stdoutEnded','stderrEnded']]])test(id,()=>{const row=fixture();for(const key of keys)row.processRow[key]=false;assert.throws(()=>judge(row.receipt,row.processRow,row.config));});
test('F02-v2-unknown-before-invalid-judgment',()=>{const row=fixture('persistent'),latch=createRetirementLatch();latch.begin(1);latch.observe(row.receipt);row.receipt.caseSha256='0'.repeat(64);failure(latch,()=>judge(row.receipt,row.processRow,row.config));assert(latch.unconfirmed);const source=readFileSync(join(own,'supervisor.mjs'),'utf8');assert(source.indexOf('lifetime.observe(receipt)')<source.indexOf('disposition=judge('));assert(source.indexOf('lifetime.validated(disposition)')<source.indexOf('const after=census('));});
test('F02-v2-census-undefined',()=>{const row=fixture('persistent'),latch=createRetirementLatch();latch.begin(1);latch.observe(row.receipt);latch.validated(judge(row.receipt,row.processRow,row.config));const reason=failure(latch,()=>{throw undefined;});assert.equal(reason,undefined);assert(latch.primary.present);assert.equal(latch.primary.value,undefined);assert(latch.unconfirmed);});
test('F02-v2-unread-receipt-false',()=>{const latch=createRetirementLatch();latch.begin(1);assert.equal(failure(latch,()=>{throw false;}),false);assert(latch.unconfirmed);assert.equal(latch.primary.value,false);});
test('F02-v2-primary-before-cleanup',()=>{for(const first of [false,undefined]){const latch=createRetirementLatch();latch.begin(1);failure(latch,()=>{throw first;});latch.recordPrimary({cleanup:true});assert(latch.primary.present);assert.equal(latch.primary.value,first);assert(latch.unconfirmed);}});
test('F02-v2-only-validated-retirement-clears-pending',()=>{const latch=createRetirementLatch();latch.begin(1);latch.observe({retirementState:'RETIRED'});assert(latch.unconfirmed);latch.validated('PASS');assert.equal(latch.unconfirmed,false);latch.begin(1);latch.observe({retirementState:'UNCONFIRMED'});latch.validated('PASS');assert(latch.unconfirmed);assert.throws(()=>latch.begin(1));});
test('F01-v2-strict-regressions',()=>{let getterCalls=0;for(const kind of ['presence','getter','duplicate','close']){const row=fixture();if(kind==='presence')row.processRow.primary.present=0;if(kind==='getter')Object.defineProperty(row.processRow,'stdoutEnded',{get(){getterCalls++;return true;}});if(kind==='duplicate')row.receipt.trace.splice(2,0,{...row.receipt.trace[1]});if(kind==='close')row.processRow.closed=false;assert.throws(()=>judge(row.receipt,row.processRow,row.config));}assert.equal(getterCalls,0);});
const result={schema:4,groups:10,passed:rows.filter(row=>row.pass).length,rows,Workers:0,children:0,productImports:0,lifecycleProof:'PURE latch plus source ordering; not Worker/OS'};writeFileSync(join(own,'CONTROL-RESULT.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(result));if(result.passed!==10)process.exitCode=1;
