import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
const root=path.dirname(new URL(import.meta.url).pathname),base=path.dirname(root),materialized=base+'/materialized',activation=base+'/activation-v1';
assert.equal(root,'/Users/kjopek/Workspace/safe-bash/tests/compatibility/bash-function-pipestatus-native-reference-20260829/v2/actual-run-v1');
const actual='/private/tmp/safe-bash-function-pipestatus-observations-20260829-v2';
let deadline=Math.min(1788011757530,fs.statSync(root+'/raw/startup.stdout').birthtimeMs+600000);
const time=()=>assert(Date.now()<=deadline,'OUTER_ATTEMPT_DEADLINE');time();
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const read=(filename,maximum=33554432)=>{time();const stat=fs.lstatSync(filename);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=maximum&&stat.uid===process.getuid()&&stat.nlink===1);const descriptor=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const first=fs.fstatSync(descriptor);assert.equal(first.ino,stat.ino);assert.equal(first.dev,stat.dev);const bytes=fs.readFileSync(descriptor),last=fs.fstatSync(descriptor);assert.equal(bytes.length,first.size);assert.equal(last.size,first.size);assert.equal(last.mtimeMs,first.mtimeMs);return bytes;}finally{fs.closeSync(descriptor);}};
const decode=bytes=>new TextDecoder('utf-8',{fatal:true}).decode(bytes);
const admit=(filename,sha,maximum)=>{const bytes=read(filename,maximum);assert.equal(hash(bytes),sha);return bytes;};
const write=(relative,bytes)=>{time();const filename=root+'/'+relative;fs.mkdirSync(path.dirname(filename),{recursive:true,mode:448});const descriptor=fs.openSync(filename,fs.constants.O_WRONLY|fs.constants.O_CREAT|fs.constants.O_EXCL|fs.constants.O_NOFOLLOW,384);try{fs.writeFileSync(descriptor,bytes);fs.fsyncSync(descriptor);}finally{fs.closeSync(descriptor);}time();};
const json=(relative,value)=>write(relative,JSON.stringify(value,null,2)+'\n');
const parse=filename=>JSON.parse(decode(read(filename)));
async function authenticate(){
 const executableRaw=admit(materialized+'/PRESEAL.json','b082c051f1e1599af1a5789786c20a6d89d882dda67b6d2430062c84779bf901',65536),readyRaw=admit(base+'/READY-SEAL.json','7cad2e981d9008e90f64bc04d528ecc9da02458bd46859382d1028020c925b47',1048576);
 const executable=JSON.parse(decode(executableRaw)),ready=JSON.parse(decode(readyRaw));const rows=[];
 for(const [directory,seal] of [[materialized,executable],[base,ready]])for(const row of seal.files){const bytes=admit(directory+'/'+row.path,row.sha256,4194304);assert.equal(bytes.length,row.bytes);assert.equal(fs.lstatSync(directory+'/'+row.path).mode&511,row.mode);rows.push({path:directory+'/'+row.path,bytes:bytes.length,sha256:row.sha256,mode:row.mode});}
 const tools=parse(materialized+'/TOOLS.json'),observedTools=[];
 for(const pin of [...tools.toolPins,tools.environmentLauncher,tools.wrapperTool]){const stat=fs.lstatSync(pin.path);assert(stat.isFile()&&stat.size===pin.bytes&&(stat.mode&511)===pin.mode);const digest=crypto.createHash('sha256');let bytes=0;for await(const chunk of fs.createReadStream(pin.path,{highWaterMark:65536})){time();bytes+=chunk.length;assert(bytes<=pin.bytes);digest.update(chunk);}assert.equal(bytes,pin.bytes);assert.equal(digest.digest('hex'),pin.sha256);const after=fs.lstatSync(pin.path);assert.equal(after.ino,stat.ino);assert.equal(after.mtimeMs,stat.mtimeMs);observedTools.push({path:pin.path,bytes,sha256:pin.sha256,mode:pin.mode});}
 const goRaw=admit(materialized+'/GO.json','d7fd91283815bf0cf6e153cd2d728afb76f43a04db2d3575cfcaf16d43e09bc7',1945);assert.equal(goRaw.length,1945);assert.equal(fs.lstatSync(materialized+'/GO.json').mode&511,384);
 const approvalRaw=admit(activation+'/RESOLVED-APPROVAL.json','b319f2f7904229328d7081be99de460bc9be951286662403503263816fb781a6',1392);assert.equal(approvalRaw.length,1392);
 const commandRaw=admit(activation+'/resolved-command.txt','4e7905d3ea72325eb8922f80735a98d29192fb309fffac871a5f2c9817a3e72f',871);assert.equal(commandRaw.length,871);
 const approval=JSON.parse(decode(approvalRaw));assert.equal(approval.cmd,decode(commandRaw));assert.equal(approval.login,false);assert.equal(approval.sandbox_permissions,'require_escalated');assert(!Object.hasOwn(approval,'prefix_rule'));
 return{rows,tools:observedTools,approval,go:JSON.parse(decode(goRaw)),executable};
}
if(process.argv[2]==='preflight'){
 const stdout=fs.openSync(root+'/raw/slot-receipt.json','wx',384),stderr=fs.openSync(root+'/raw/slot-receipt.stderr','wx',384);let result;
 try{result=spawnSync('/usr/bin/git',['cat-file','blob','8b76e28e28cc86950ff55b4da8e408c8f68fb725:tests/compatibility/bash-function-pipestatus-native-preflight-review-20260829/sole-slot-v1/RECEIPT.json'],{cwd:'/Users/kjopek/Workspace/safe-bash',stdio:['ignore',stdout,stderr],timeout:10000,killSignal:'SIGKILL'});}finally{fs.closeSync(stdout);fs.closeSync(stderr);}
 json('raw/slot-receipt-child.json',{status:result.status,signal:result.signal,error:result.error?.message??null});assert.equal(result.error,undefined);assert.equal(result.signal,null);assert.equal(result.status,0);
 const slotRaw=admit(root+'/raw/slot-receipt.json','8b90b85c6ebd2ec02f3b113bc8dad25d161f8877ad1f907a1facf506ceda04c5',1048576);const slot=JSON.parse(decode(slotRaw));
 const authenticated=await authenticate();assert(Date.now()<=1788011157530,'LATEST_FULL_WINDOW_START');
 const admission=await import(pathToFileURL(materialized+'/admission.mjs'));
 const accepted=admission.admit(materialized,materialized+'/GO.json','d7fd91283815bf0cf6e153cd2d728afb76f43a04db2d3575cfcaf16d43e09bc7');admission.validateProvision(accepted.provision,actual);admission.validateCohort(parse(materialized+'/COHORT.json'),accepted.requests,actual);
 const template=parse(base+'/APPROVAL-PROPOSAL.template.json');assert.equal(hash(Buffer.from(template.parameters.cmd)),'256789485b602f9f11f5414f45d33516ecc72d26abf08fe6e4a0dfbded7774e4');admission.resolveApproval(template,authenticated.approval,'d7fd91283815bf0cf6e153cd2d728afb76f43a04db2d3575cfcaf16d43e09bc7');
 const binding=parse(activation+'/RESULT.json');for(const parent of binding.createdParents){const stat=fs.lstatSync(parent.path);assert(stat.isDirectory()&&stat.uid===process.getuid()&&(stat.mode&511)===448&&String(stat.ino)===parent.inode&&String(stat.dev)===parent.device);}
 const journal=read(actual+'/JOURNAL.jsonl',0);assert.equal(journal.length,0);assert.equal(fs.lstatSync(actual+'/JOURNAL.jsonl').mode&511,384);
 for(const name of ['outer','cases','captures'])assert.deepEqual(fs.readdirSync(actual+'/'+name),[]);
 assert(!fs.existsSync(actual+'/outer/bootstrap.stdout')&&!fs.existsSync(actual+'/outer/bootstrap.stderr'));
 assert(Date.now()+600000<=authenticated.go.deadlineEpochMs);time();
 json('PREFLIGHT.json',{status:'PASS',at:new Date().toISOString(),outerDeadlineEpochMs:deadline,goDeadline:authenticated.go.deadlineEpochMs,sourceAndTools:authenticated,slotReceipt:slot,slotReceiptSha256:hash(slotRaw),runtimeReceiptsAndProvision:true,bootstrapCapturesAbsent:true,actualFdAdmission:'REQUIRED_AT_OWNER_START_NOT_ASSUMED',children:[{role:'Git receipt',status:result.status,signal:result.signal}],nativeStarts:0});
 console.log(JSON.stringify({preflight:'PASS',at:new Date().toISOString(),outerDeadlineEpochMs:deadline,parameters:authenticated.approval}));
}else if(process.argv[2]==='publish'){
 const authenticated=await authenticate();const inventory=[];let bytesTotal=0;
 const walk=(directory,prefix='')=>{for(const name of fs.readdirSync(directory).sort()){time();const filename=directory+'/'+name,relative=prefix+name,stat=fs.lstatSync(filename);assert(!stat.isSymbolicLink()&&stat.uid===process.getuid());if(stat.isDirectory())walk(filename,relative+'/');else{assert(stat.isFile()&&stat.nlink===1);const bytes=read(filename);bytesTotal+=bytes.length;assert(bytesTotal<=33554432&&inventory.length<4096);write('captured/'+relative+'.data',bytes);inventory.push({path:relative,bytes:bytes.length,sha256:hash(bytes),mode:stat.mode&511,device:String(stat.dev),inode:String(stat.ino)});}}};walk(actual);
 const results=parse(actual+'/RESULTS.json');assert(Number.isSafeInteger(results.deadline));deadline=Math.min(deadline,results.deadline,authenticated.go.deadlineEpochMs);time();
 const cohort=parse(materialized+'/COHORT.json'),observations=[];
 for(const literal of cohort.cases){const filename=actual+'/'+literal.id+'.json';if(!fs.existsSync(filename)){observations.push({id:literal.id,disposition:'UNRUN_NO_ROW'});continue;}const row=parse(filename);assert.equal(row.id,literal.id);const capture=[];for(const name of ['stdout','stderr']){const value=row.capture.find(item=>item.name===name);const bytes=read(actual+'/captures/'+literal.id+'/'+name,65536);assert.equal(hash(bytes),value.sha256);assert.equal(bytes.length,value.bytes);assert.equal(bytes.toString('base64'),value.base64);capture.push({name,bytes:bytes.length,sha256:value.sha256,base64:value.base64,text:bytes.every(byte=>byte<128)?bytes.toString('ascii'):null});}
  const frame=read(actual+'/'+literal.id+'.observation.nul',262144);assert.equal(hash(frame),row.observation.sha256);const fields=frame.toString('ascii').split('\0');assert.equal(fields.length,9);assert.equal(fields[0],'FNPIPEOBS1');assert.equal(fields[1],literal.id);assert.equal(Number(fields[2]),row.status);assert.equal(fields[4],capture[0].base64);assert.equal(fields[6],capture[1].base64);
  assert(row.exit&&row.close&&row.retired&&row.group.state==='absent'&&row.signal===null&&row.stop===null&&row.errors.length===0&&row.regularCaptureCompletion&&row.filesVerified);assert(row.capture.every(item=>item.flush&&item.size&&item.hash&&item.close));
  observations.push({id:literal.id,disposition:'OBSERVATION_NOT_PARITY_PASS',programSha256:literal.programSha256,status:row.status,capture,filesBefore:row.filesBefore,filesAfter:row.filesAfter,exit:row.exit,close:row.close,retired:row.retired,group:row.group,groupObservations:row.groupObservations,started:row.started,finished:row.finished,frameSha256:hash(frame)});
 }
 json('OBSERVATIONS.json',{profile:'local pinned Bash3.2.57; no GNU5.3 or universal libc claim',observations,managedLedger:results.ledger,completed:results.completed,halted:results.halted,notStarted:results.notStarted,deadline:results.deadline,publicationDeadline:deadline,sourceForkReservations:'UNOBSERVED_NOT_MEASURED_STARTS',initialToolStartup:'TRUSTED_HOST_OUTSIDE_COHORT',p02Prologue:'none added: exact first-command script, no shell assignments or instrumentation before its printf'});
 json('CAPTURE-MANIFEST.json',{root:actual,files:inventory,totalBytes:bytesTotal,unchangedCopy:true});
 const summary=observations.map(row=>({id:row.id,status:row.status,stdout:row.capture?.[0].text,stderr:row.capture?.[1].text,files:row.filesAfter?.filter(item=>item.type==='file')}));
 write('HANDOFF.md',`# Native26 actual observation handoff\n\nLocal pinned Bash3.2.57 only; no GNU5.3/libc-all-versions/full-Bash parity claim. Exact one approved entry, no native version probe or product/ERE execution.\n\n${results.completed} credited native observations; halted=${results.halted}; not-started=${JSON.stringify(results.notStarted)}. Captured files ${inventory.length}, bytes ${bytesTotal}. Complete raw byte/hash/status/frame/effects and lifecycle rows in OBSERVATIONS.json and captured/. These are observations, not parity passes.\n\nManaged ledger: ${JSON.stringify(results.ledger)}. Source-derived fork reservations are UNOBSERVED, not measured starts. All credited rows have exit/close/absent group and qualified capture/retirement; independent actual artifact audit remains required. Initial tool/zsh startup is trusted host outside fresh child environment/raw capture.\n\nP02 exact program's printf is the first shell command: no instrumentation/prologue command is inserted. This is local process startup, not GNU5.3 startup or a declaration/type probe. P18 outputs describe visible values, not a direct scalar/array type observation. No dedicated present-nonarray probe exists in these26; source-backed preservation remains subject to policy adjudication. F05 observes final file effects, not creation timing; ordinary dollar-parenthesis source qualification is unchanged.\n\nNumeric results and raw observations:\n\n\`\`\`json\n${JSON.stringify(summary,null,2)}\n\`\`\`\n\nEntry deadline ${results.deadline}; stricter publication deadline ${deadline}. Known native owner/case accounting is distinct from18 administrative slots and19 unobserved fork reservations. No universal process census or OS containment. No retry or policy/golden change.\n`);
 const files=[];const snapshot=(directory,prefix='')=>{for(const name of fs.readdirSync(directory).sort()){const relative=prefix+name,filename=directory+'/'+name,stat=fs.lstatSync(filename);assert(!stat.isSymbolicLink());if(stat.isDirectory())snapshot(filename,relative+'/');else if(!['raw/publish.stdout','raw/publish.stderr'].includes(relative)){const bytes=read(filename);files.push({path:relative,bytes:bytes.length,sha256:hash(bytes),mode:stat.mode&511});}}};snapshot(root);json('SEAL.json',{files,actualSourceFiles:authenticated.rows,managedLedger:results.ledger,observations:results.completed,excludes:['SEAL.json','raw/publish.stdout','raw/publish.stderr','later publication metadata'],deadline});console.log(JSON.stringify({completed:results.completed,halted:results.halted,summary,managed:results.ledger,artifactBytes:bytesTotal,deadline,sealSha256:hash(read(root+'/SEAL.json'))}));
}else throw Error('EXACT_MODE_REQUIRED');
