import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = dirname(fileURLToPath(import.meta.url));
const repository = resolve(directory, '../../../..');
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const git = args => execFileSync('git', ['--no-replace-objects', ...args], { cwd: repository, maxBuffer: 64 * 1024 * 1024, env: { ...process.env, GIT_OPTIONAL_LOCKS: '0' } });
const receipt = JSON.parse(readFileSync(resolve(directory, 'RECEIPT.json')));
for (const [path, expected] of Object.entries(receipt.files)) assert.equal(hash(readFileSync(resolve(directory, path))), expected, path);
const report = JSON.parse(readFileSync(resolve(directory, 'INVENTORY.json')));
assert.equal(report.snapshot, report.headAtEnd);
assert.equal(report.suiteLaunched, false);
assert.equal(report.productExecutions, 0);
assert.equal(git(['rev-parse', `${report.snapshot}^{tree}`]).toString().trim(), report.tree);
const paths = git(['ls-tree', '-r', '--name-only', '-z', report.snapshot]).toString().split('\0').filter(Boolean).sort();
assert.deepEqual(paths.filter(path => /^tests\/.*\.test\.ts$/.test(path) && !path.startsWith('tests/commands/regex-execution/continuation/artifacts/native/')), report.canonical.paths);
assert.equal(report.canonical.count, 600);
assert.equal(paths.filter(path => path.endsWith('.mts')).length, 190);
assert.equal(report.mts.unclassified.length, 11);
assert.equal(report.registry.unique, 73);
assert.equal(report.cleanup.currentCount, 244);
for (const [path, expected] of Object.entries(report.cleanup.envelope.files)) assert.equal(hash(git(['show', `${report.snapshot}:${path}`])), expected, path);
assert.equal(report.native.assets.length, 48);
assert.equal(report.native.issues.length, 1);
assert.equal(report.native.issues[0].name, 'rg');
assert.ok(report.writerSourceBindings.every(entry => entry.unchangedSinceAcceptedFix));
assert.ok(report.additionalNative.every(entry => entry.matched && !entry.executed));
console.log(JSON.stringify({ verified: true, snapshot: report.snapshot, canonicalPaths: report.canonical.count, cleanupInputs: report.cleanup.currentCount, productExecuted: false, hostAvailabilityRechecked: false }));
