import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';

const outerStarted = Number(process.hrtime.bigint() / 1000000n);
const startedUtc = new Date().toISOString();
const root = path.resolve('tests/compatibility/bash-ere-core-public-pilot-preparation-20260829/runtime-author-v1/r2/final-binding-v1');
const r2 = path.dirname(root);
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const read = (filename, maximum = 4 * 1024 * 1024) => { const stat = fs.lstatSync(filename); assert(stat.isFile() && !stat.isSymbolicLink() && stat.size <= maximum); const bytes = fs.readFileSync(filename); assert.equal(bytes.length, stat.size); return bytes; };
const checked = [];
const bind = row => {
  const stat = fs.lstatSync(row.path); assert(stat.isFile() && !stat.isSymbolicLink()); assert.equal(stat.size, row.size);
  if (row.mode !== undefined) assert.equal(stat.mode & 0o777, row.mode);
  const descriptor = fs.openSync(row.path, 'r'); const digest = crypto.createHash('sha256'); const buffer = Buffer.alloc(65536);
  try { const opened = fs.fstatSync(descriptor); assert.equal(opened.dev, stat.dev); assert.equal(opened.ino, stat.ino); let count; while ((count = fs.readSync(descriptor, buffer))) digest.update(buffer.subarray(0, count)); } finally { fs.closeSync(descriptor); }
  assert.equal(digest.digest('hex'), row.sha256, row.path); checked.push({ path: row.path, size: row.size, sha256: row.sha256 });
};
const profilePath = path.join(r2, 'PROFILE.json'); const profileBytes = read(profilePath);
const profileSha256 = hash(profileBytes); assert.equal(profileSha256, 'bacc21fb126bb6e0b5441bee560cb0bad1f7ffda01d129b996c1cdd3e6312e05');
const profile = JSON.parse(profileBytes);
const reviewPath = path.resolve('tests/compatibility/bash-ere-core-public-pilot-independent-20260829/runtime-review-r2/RESULT.json');
const reviewBytes = read(reviewPath); assert.equal(hash(reviewBytes), 'f5499bbffd18ef06483b26c256bd989d2124abe0fa8afb261d00aa7936becd7b');
const templatePath = path.join(r2, 'GRANT-TEMPLATE.json'); const templateBytes = read(templatePath, 16384); const template = JSON.parse(templateBytes);
assert.equal(Object.keys(template).length, 18);
const inertBytes = read(path.join(r2, 'INERT-COMMAND.txt'), 16384);
assert(inertBytes.toString('utf8').includes(profileSha256));
for (const row of profile.assets) bind(row);
for (const row of profile.tools) bind(row);
bind(profile.archive);
assert.equal(profile.archive.size, 909885);
const layoutRows = [];
for (const layout of profile.layouts) {
  const names = [];
  const walk = directory => { for (const name of fs.readdirSync(directory)) { const filename = path.join(directory, name); const stat = fs.lstatSync(filename); assert(!stat.isSymbolicLink()); if (stat.isDirectory()) walk(filename); else { assert(stat.isFile()); names.push(path.relative(layout.source, filename)); } } };
  walk(layout.source); assert.deepEqual(names.sort(), layout.shipping.map(row => row.path).sort());
  for (const row of layout.shipping) bind({ ...row, path: path.join(layout.source, row.path) });
  layoutRows.push({ name: layout.name, productFiles: names.length });
}
for (const cell of profile.cells) bind(cell.inheritedCell);
assert.equal(profile.cells.length, 24);
const futureGrantPath = path.join(root, 'ROOT-GRANT.json');
const futureStdout = path.join(root, 'actual-outer.stdout'); const futureStderr = path.join(root, 'actual-outer.stderr');
const unused = [profile.root, futureGrantPath, futureStdout, futureStderr, ...profile.cells.flatMap(cell => [cell.config, cell.stdout, cell.stderr])];
for (const filename of unused) assert(!fs.existsSync(filename), `occupied activation path: ${filename}`);
const grant = { ...template, authorized: true, pilotReview: 'fc188075658ef573da605bf11055460ca0b85112', issuedAt: '2026-08-29T17:10:00.000Z', latestStart: '2026-08-29T17:25:00.000Z', expiresAt: '2026-08-29T17:45:00.000Z', outerStarted };
assert.deepEqual(Object.keys(grant), Object.keys(template));
assert.equal(grant.sourceReview, 'f17d8dec11190ef40ecac6c175b208a2e29c7fbf');
assert.equal(grant.producerReview, '5c2ef0795ca402344b5b0d28869b64db46d73b86');
assert.equal(grant.profileSha256, profileSha256);
const source = read(path.join(r2, 'core.mjs')).toString('utf8');
const matched = /record\(grant, \[([^\]]+)\]\)/.exec(source); assert(matched);
const keys = [...matched[1].matchAll(/'([^']+)'/g)].map(match => match[1]); assert.deepEqual(keys, Object.keys(template));
const clause = 'assert(times[2] - times[0] <= 1200000 && wallNow < times[2]);'; assert(source.includes(clause));
const issued = Date.parse(grant.issuedAt), latest = Date.parse(grant.latestStart), expires = Date.parse(grant.expiresAt);
const assignedSpan = expires - issued;
assert.equal(assignedSpan, 2100000);
const grantBytes = Buffer.from(JSON.stringify(grant, null, 2) + '\n');
const grantSha256 = hash(grantBytes);
fs.writeFileSync(path.join(root, 'PENDING-GRANT.json'), grantBytes, { flag: 'wx' });
const executable = profile.node.path;
const argv = [path.join(r2, 'coordinator.mjs'), profilePath, profileSha256, futureGrantPath, grantSha256, String(outerStarted)];
const cwd = process.cwd();
const env = { PATH: path.dirname(executable), LANG: 'C', LC_ALL: 'C', TZ: 'UTC', HOME: path.dirname(r2), TMPDIR: path.dirname(r2) };
const quote = text => "'" + text.replaceAll("'", "'\\''") + "'";
const commandBytes = Buffer.from('exec /usr/bin/env -i ' + Object.entries(env).map(([key, value]) => `${key}=${quote(value)}`).join(' ') + ' ' + [executable, ...argv].map(quote).join(' ') + '\n');
fs.writeFileSync(path.join(root, 'RESOLVED-COMMAND.txt'), commandBytes, { flag: 'wx' });
const launch = { executable, argv, cwd, env, activationGrantPath: futureGrantPath, stdout: futureStdout, stderr: futureStderr, commandMeaning: 'inert candidate; qualified outer owner must establish bounded pipes before dispatch; DO NOT RUN' };
fs.writeFileSync(path.join(root, 'RESOLVED-LAUNCH.json'), JSON.stringify(launch, null, 2) + '\n', { flag: 'wx' });
const captured = [1, 2].map(descriptor => { const stat = fs.fstatSync(descriptor); return { descriptor, regular: stat.isFile(), device: stat.dev, inode: stat.ino, sizeAtSample: stat.size }; });
const sampledMonotonic = Number(process.hrtime.bigint() / 1000000n); const sampledUtc = new Date().toISOString();
const remainingMilliseconds = Math.max(0, outerStarted + 1200000 - sampledMonotonic);
const receipt = { schema: 1, status: 'BLOCKED_ASSIGNED_WINDOW_VIOLATES_REVIEWED_VALIDATOR', startedUtc, sampledUtc, profileSha256, sourceCommit: '0f8684d8eea2042cef6ab194ad2f9be165b31698', reviewCommit: grant.pilotReview, reviewReceiptSha256: hash(reviewBytes), exactGrantKeys: keys, grantFieldCount: keys.length, reviewNarrativeNineteenKeysNotAdopted: true, grant: { path: path.join(root, 'PENDING-GRANT.json'), bytes: grantBytes.length, sha256: grantSha256, candidateOnlyNotIssued: true, authorizedTrueOnlyIfFutureRootPromotesExactBytes: true }, command: { path: path.join(root, 'RESOLVED-COMMAND.txt'), bytes: commandBytes.length, sha256: hash(commandBytes) }, launch: { path: path.join(root, 'RESOLVED-LAUNCH.json'), sha256: hash(read(path.join(root, 'RESOLVED-LAUNCH.json'))) }, contractConflict: { sourcePath: path.join(r2, 'core.mjs'), clause, assignedSpanMilliseconds: assignedSpan, acceptedSpanMaximum: 1200000, timestampChangeMade: false, validatorChangeMade: false }, monotonic: { source: 'Number(process.hrtime.bigint() / 1000000n)', outerStarted, sampledMonotonic, elapsedBindingMilliseconds: sampledMonotonic - outerStarted, remainingMillisecondsAtSample: remainingMilliseconds, publicationReservationMilliseconds: 180000, caseAndSetupMillisecondsAfterPublicationReserve: Math.max(0, remainingMilliseconds - 180000), notPerformanceNow: true, notWallClock: true, immutableOriginIfPromoted: true, priorInspectionIsSeparatePrepNotClaimedRuntimeStart: true }, wallWindowAtSample: { issuedAt: grant.issuedAt, latestStart: grant.latestStart, expiresAt: grant.expiresAt, millisecondsUntilLatestStart: latest - Date.parse(sampledUtc), millisecondsUntilExpiry: expires - Date.parse(sampledUtc) }, currentCaptureOwnership: { helperPid: process.pid, parentPid: process.ppid, declaredCommandShellPid: Number(process.env.BINDING_COMMAND_SHELL_PID), captureDescriptors: captured, shellCaptureEstablishedBeforeHelperStartup: true, currentCaptureQualification: 'finite DATA helper output, direct shell files reserved/postchecked; NOT claimed prewrite OS enforcement or proof of future parent ownership' }, futureCapturePlan: { qualifiedOuterOwnerPid: null, coordinatorPid: null, reason: 'not launched; future PID identities cannot be supplied honestly', stdout: futureStdout, stderr: futureStderr, outerAdministrativeReservation: 8388608, innerPrewriteMaximum: 58720256, aggregateMaximum: 67108864, initialStdoutReserve: 524288, initialStderrReserve: 524288, requirements: ['retain actual future process handle before fallible observer enrollment', 'bound both stdout/stderr before writes; independently observe exit/close/both EOF', 'postcheck trusted initial startup captures; qualification is not OS filesystem quota', 'keep UNKNOWN ownership and reserved publication, no process-close-to-Worker-retirement inference', 'count publication-verifier and six Git roles; sampled work exceptions unchanged'] }, checkedFiles: checked.length, layoutRows, tools: profile.tools.length, assets: profile.assets.length, unusedPaths: unused, archiveInflations: 0, productImports: 0, workers: 0, runtimeChildren: 0, futurePathsCreated: false, boundBytes: profile.budget.logicalBytes, headroomBytes: profile.budget.workingBytes - profile.budget.logicalBytes };
fs.writeFileSync(path.join(root, 'BINDING-RECEIPT.json'), JSON.stringify(receipt, null, 2) + '\n', { flag: 'wx' });
console.log(JSON.stringify({ status: receipt.status, sampledUtc, grant: receipt.grant, command: receipt.command, monotonic: receipt.monotonic, currentCaptureOwnership: receipt.currentCaptureOwnership, checkedFiles: checked.length, tools: profile.tools.length, assets: profile.assets.length, layoutRows, unusedPathCount: unused.length, activationPathsCreated: false }, null, 2));
