// Released 1.12.61 C-locale captures; argv0 alone is mapped to the virtual name.
// Configuration roots are virtual identities, never ambient host directories.
export const referenceText: Readonly<Record<string, string>> = Object.freeze({
  "help": "Usage:\n  ssconvert [OPTION?] INFILE [OUTFILE]\n\nHelp Options:\n  -h, --help                         Show help options\n  --help-all                         Show all help options\n  --help-libspreadsheet              Show Gnumeric Options\n  --help-gtk                         Show GTK+ Options\n\nApplication Options:\n  --version                          Display program version\n  -v, --verbose                      Be somewhat more verbose during conversion\n  -E, --import-encoding=ENCODING     Optionally specify an encoding for imported content\n  -I, --import-type=ID               Optionally specify which importer to use\n  --list-importers                   List the available importers\n  -M, --merge-to=file                Merge listed files (all same format) to make this file\n  -T, --export-type=ID               Optionally specify which exporter to use\n  -O, --export-options=string        Detailed instructions for the chosen exporter\n  --list-exporters                   List the available exporters\n  -S, --export-file-per-sheet        Export a file for each sheet if the exporter only supports one sheet at a time\n  --export-graphs                    Export graphs\n  --list-image-formats               List the available image formats\n  --set                              Change the contents of a cell before writing --set A12=2\n  --recalc                           Recalculate all cells before writing the result\n  --display=DISPLAY                  X display to use\n\n",
  "help-all": "Usage:\n  ssconvert [OPTION?] INFILE [OUTFILE]\n\nHelp Options:\n  -h, --help                         Show help options\n  --help-all                         Show all help options\n  --help-libspreadsheet              Show Gnumeric Options\n  --help-gtk                         Show GTK+ Options\n\nGnumeric Options\n  --libspreadsheet-version           Display Gnumeric's version\n  -L, --lib-dir=DIR                  Set the root library directory\n  -D, --data-dir=DIR                 Adjust the root data directory\n\nGTK+ Options\n  --class=CLASS                      Program class as used by the window manager\n  --name=NAME                        Program name as used by the window manager\n  --gtk-module=MODULES               Load additional GTK+ modules\n  --g-fatal-warnings                 Make all warnings fatal\n\nApplication Options:\n  --version                          Display program version\n  -v, --verbose                      Be somewhat more verbose during conversion\n  -E, --import-encoding=ENCODING     Optionally specify an encoding for imported content\n  -I, --import-type=ID               Optionally specify which importer to use\n  --list-importers                   List the available importers\n  -M, --merge-to=file                Merge listed files (all same format) to make this file\n  -T, --export-type=ID               Optionally specify which exporter to use\n  -O, --export-options=string        Detailed instructions for the chosen exporter\n  --list-exporters                   List the available exporters\n  -S, --export-file-per-sheet        Export a file for each sheet if the exporter only supports one sheet at a time\n  --export-graphs                    Export graphs\n  --list-image-formats               List the available image formats\n  --set                              Change the contents of a cell before writing --set A12=2\n  --recalc                           Recalculate all cells before writing the result\n  --display=DISPLAY                  X display to use\n\n",
  "help-libspreadsheet": "Usage:\n  ssconvert [OPTION?] INFILE [OUTFILE]\n\nGnumeric Options\n  --libspreadsheet-version           Display Gnumeric's version\n  -L, --lib-dir=DIR                  Set the root library directory\n  -D, --data-dir=DIR                 Adjust the root data directory\n\n",
  "help-gtk": "Usage:\n  ssconvert [OPTION?] INFILE [OUTFILE]\n\nGTK+ Options\n  --class=CLASS                      Program class as used by the window manager\n  --name=NAME                        Program name as used by the window manager\n  --display=DISPLAY                  X display to use\n  --gtk-module=MODULES               Load additional GTK+ modules\n  --g-fatal-warnings                 Make all warnings fatal\n\n",
  "version": "ssconvert version '1.12.61'\ndatadir := '/opt/ssconvert-reference/share/gnumeric/1.12.61'\nlibdir := '/opt/ssconvert-reference/lib/gnumeric/1.12.61'\n",
  "libspreadsheet-version": "gnumeric version '1.12.61'\ndatadir := '/opt/ssconvert-reference/share/gnumeric/1.12.61'\nlibdir := '/opt/ssconvert-reference/lib/gnumeric/1.12.61'\n"
});
