const hex = text => Buffer.from(text).toString('hex');
const vector = (id, purpose, input, argv = ['-c', '.'], extra = {}) => ({ id, purpose, argv, inputHex: hex(input), ...extra });
const files = entries => Object.fromEntries(Object.entries(entries).map(([name, text]) => [name, hex(text)]));

export const cases = [
  vector('mixed-quoted-container', 'Numeric tokens must not rewrite keys, quoted lookalikes, escaped Unicode or embedded BOM strings.',
    '{"NaN":[NaN,"NaN",Infinity,"Infinity",-Infinity,"-Infinity",01,"01",1.,"1."],"\\u004e\\u0061\\u004e":"\\u0049nfinity","bom":"\uFEFFNaN","quote":"\\\"NaN\\\""}\n'),
  vector('case-sign-neighbors', 'Observe case and sign variants as a sequence, without assuming JSON grammar.', 'nan NAN +NaN -NaN inf INF +Infinity -inf\n'),
  vector('nan-payload-neighbor', 'NaN payload spelling is an oracle question, not a presumed rejection.', 'NaN17\n8\n'),
  vector('signaling-nan-neighbor', 'Signaling NaN spelling is an oracle question.', 'sNaN\n8\n'),
  vector('incomplete-infinity', 'Incomplete special token must not consume a later valid record.', 'Infinit\n8\n'),
  vector('nan-suffix-cuts', 'Bad special-number suffix, valid following scalar, every byte cut.', 'NaNx 8\n', ['-c', '.'], { allBoundaries: true }),
  vector('decimal-neighbors', 'Observe leading zero, signed zero, absent integer/fraction digits, plus and exponent neighbors.', '[00,-00,007,0.0,2.,.5,-.5,+2,2.e3,02e+1]\n'),
  vector('hex-prefix-rejection', 'Hex-looking prefix followed by a valid JSON record.', '0x10\n8\n'),
  vector('incomplete-exponent-prefix-effects', 'Retain completed output but stop after a malformed exponent.', '7\n2.e+\n8\n'),
  vector('double-sign-rejection', 'Do not globally remove or reinterpret repeated signs.', '--2 8\n'),
  vector('decimal-copy-versus-arithmetic', 'Retained decimal precision and overflow lexemes differ from binary arithmetic.',
    '[9007199254740993,1.2300,01.00,1e400,-1e400,1e-400,Infinity,-Infinity,NaN]\n',
    ['-c', 'map([., tostring, .+0, ., type, isnan, isinfinite])']),
  vector('nonfinite-type-copy-predicates', 'Distinguish parsed NaN, infinities, null and strings; copy through arrays and objects.',
    '[NaN,Infinity,-Infinity,null,"NaN","Infinity",0]\n',
    ['-c', 'map([type,isnan,isinfinite,isfinite,{copy:.},[.,.]])']),
  vector('nonfinite-arithmetic', 'Arithmetic must preserve nonfinite semantics rather than only its serialized null/max-double.',
    '[NaN,Infinity,-Infinity,1e400]\n', ['-c', 'map([.+0,.*0,.-.,./2,((.*0)|isnan),((.+0)|isinfinite)])']),
  vector('nonfinite-comparisons', 'Observe self equality and order, plus null/zero comparisons in this native profile.',
    '[NaN,Infinity,-Infinity,1e400,-1e400,0]\n', ['-c', 'map([.==.,.!=.,.<0,.>0,.==null,.<=.,.>=.])']),
  vector('nonfinite-sort-order', 'Keep native ordering including NaN and textual lookalikes; no hand-written numeric expectations.',
    '["NaN",NaN,Infinity,-Infinity,1e400,-1e400,0,null,false]\n', ['-c', 'sort']),
  vector('exit-status-nan', 'Rendered null does not itself determine -e truth status.', 'NaN\n', ['-ce', '.']),
  vector('exit-status-last-false', 'Last output status after special numeric input.', 'NaN\nfalse\n', ['-ce', '.']),
  vector('runtime-continue-false', 'UTF-8 runtime diagnostic, subsequent false output, final -e status.', '"λ"\n{"a":false}\n', ['-ce', '.a']),
  vector('runtime-continue-true', 'Runtime failure is not a parse-fatal stop; subsequent truthy output.', '"λ"\n{"a":true}\n', ['-ce', '.a']),
  vector('utf8-prefix-parse-fatal', 'Byte columns after UTF-8 and nested accepted numeric prefix; preserve only complete outputs.', '"é"\n[01,NaNx]\n42\n'),
  vector('adjacent-delimiters', 'Scalar boundaries adjoining containers and quoted lookalikes without whitespace.', '01[]1.{}NaN"NaN"'),
  vector('initial-bom-cuts', 'Split every byte of an initial UTF-8 BOM and following nonstandard number.', '\uFEFF01\n', ['-c', '.'], { allBoundaries: true }),
  vector('repeated-bom', 'A second leading BOM is not silently globally stripped.', '\uFEFF\uFEFF0\n'),
  vector('embedded-bom', 'BOM after a completed scalar is not initial BOM.', '0 \uFEFF1\n'),
  vector('whitespace-before-bom', 'Whitespace before BOM distinguishes initial prefix handling.', ' \uFEFF0\n'),
  { ...vector('partial-bom-cuts', 'Malformed BOM prefix with a mismatching third byte across every cut.', '', ['-c', '.'], { allBoundaries: true }), inputHex: 'efbb30' },
  vector('per-file-bom', 'Observe parser BOM state across separate file arguments, not assumed per-file reset.', '', ['-c', '.', 'alpha.txt', 'beta.txt'],
    { files: files({ 'alpha.txt': '\uFEFF01\n', 'beta.txt': '\uFEFF1.\n' }) }),
  vector('raw-bom-preserved', 'Raw input keeps initial and embedded BOM and all numeric lookalike bytes.', '\uFEFFNaN\n\uFEFF01 1. Infinity\n', ['-Rsc', '.']),
  vector('raw-files-bom-preserved', 'Raw slurp across files preserves each BOM and quoted lookalikes.', '', ['-Rsc', '.', 'alpha.txt', 'beta.txt'],
    { files: files({ 'alpha.txt': '\uFEFFNaN\n', 'beta.txt': '\uFEFF"01"\n' }) }),
  vector('file-utf8-parse-fatal', 'File-routed malformed token byte offsets and no later-file output after parse fatal.', '', ['-c', '.', 'alpha.txt', 'beta.txt'],
    { files: files({ 'alpha.txt': '"🙂"\n[01,NaNx]\n', 'beta.txt': '42\n' }) }),
  vector('file-runtime-continuation', 'Runtime error filename and line plus later-file successful output.', '', ['-ce', '.a', 'alpha.txt', 'beta.txt'],
    { files: files({ 'alpha.txt': '"é"\n', 'beta.txt': '{"a":7}\n' }) }),
  vector('number-token-length-boundaries', 'Decimal tokens around 256 and 4096 bytes, without exhaustive chunk Cartesian products.',
    [255, 256, 257, 4095, 4096, 4097].map(length => '9'.repeat(length)).join('\n') + '\n'),
  vector('pipeline-render-reparse', 'Actual public Shell pipe loses original nonfinite representation on serialization; assert direct stages too.',
    '[NaN,Infinity,-Infinity,01,1.,"NaN"]\n', undefined,
    { stages: [{ argv: ['-c', '.[]'] }, { argv: ['-c', '[type,isnan,isinfinite,.]'] }] }),
  vector('pipeline-parse-error-prefix', 'Upstream parse-fatal prefix still reaches downstream; last stage status and stderr both matter.',
    '01\nNaNx\n99\n', undefined, { stages: [{ argv: ['-c', '.'] }, { argv: ['-sc', '.'] }] }),
  vector('exit-status-no-output', 'Accepted NaN with no result must retain -e no-output semantics.', 'NaN\n', ['-ce', 'empty']),
];
