name: 'GitHub: Issue Comment Created'
on:
  issue_comment:
    types: [created]

jobs:
  run:
    uses: __UPSTREAM_REPO__/.github/workflows/gh-github-issue-comment-created.yml@main
    secrets: inherit
    with:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      ISSUE_STATE: ${{ github.event.issue.state }}
      COMMENT_BODY: ${{ github.event.comment.body }}
      COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
      COMMENT_AUTHOR_ASSOCIATION: ${{ github.event.comment.author_association }}
      COMMENT_USER_TYPE: ${{ github.event.comment.user.type }}
      GITHUB_REPOSITORY: ${{ github.repository }}
