import {strict as assert} from 'node:assert';import {writeFileSync,createReadStream,lstatSync} from 'node:fs';import {createHash} from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';import {join} from 'node:path';import {read,sha,fullWrite,withCapture} from './data-support.mjs';import {captureScope} from './owned-process.mjs';import {judge} from './receipt-gate.mjs';import {materialize} from './materializer.mjs';
const own=fileURLToPath(new URL('.',import.meta.url));const results=[];const sealBytes=read(join(own,'DATA-PRESEAL.json'),131072);if(sha(sealBytes)!==process.argv[2])throw Error('DATA seal');const seal=JSON.parse(sealBytes);for(const row of seal.inputs){const bytes=read(join(own,row.name),131072);if(bytes.length!==row.size||sha(bytes)!==row.sha256)throw Error('DATA input');}
const tool=seal.typescript;const stat=lstatSync(tool.path);if(!stat.isFile()||stat.isSymbolicLink()||stat.size!==tool.size)throw Error('syntax tool');const digest=createHash('sha256');let total=0;for await(const chunk of createReadStream(tool.path,{highWaterMark:65536})){total+=chunk.length;if(total>tool.size)throw Error('tool cap');digest.update(chunk);}if(total!==tool.size||digest.digest('hex')!==tool.sha256)throw Error('tool hash');const ts=await import(pathToFileURL(tool.path).href);const syntax=[];for(const row of seal.inputs.filter(row=>/\.mjs(?:\.data)?$/.test(row.name))){const parsed=ts.createSourceFile(row.name,read(join(own,row.name),131072).toString(),ts.ScriptTarget.ES2023,true,ts.ScriptKind.JS);syntax.push({name:row.name,diagnostics:parsed.parseDiagnostics.map(item=>({code:item.code,start:item.start??null,message:ts.flattenDiagnosticMessageText(item.messageText,' ')}))});}writeFileSync(join(own,'capture','H2-syntax.json'),JSON.stringify(syntax,null,2)+'\n',{flag:'wx'});if(syntax.some(row=>row.diagnostics.length))throw Error('repaired syntax diagnostics retained');
await import('./data-controls-r2.mjs');const old=JSON.parse(read(join(own,'DATA-RESULT.json'),65536));if(old.passed!==14||old.total!==14)throw Error('14 old controls');
async function test(id,body){try{await body();results.push({id,pass:true});}catch(reason){results.push({id,pass:false,message:reason instanceof Error?reason.message:'non-Error'});}}
await test('N01-async-capture-first-open',async()=>{const row=await captureScope(['a'],()=>assert.fail(),{open(){throw false},close(){assert.fail()}});assert.equal(row.primary.value,false)});
await test('N02-async-capture-second-open',async()=>{let opened=0;const closes=[];const row=await captureScope(['a','b'],()=>assert.fail(),{open(){if(++opened===2)throw undefined;return 1},close(fd){closes.push(fd)}});assert.equal(row.primary.present,true);assert.equal(row.primary.value,undefined);assert.deepEqual(closes,[1])});
await test('N03-async-both-closes-primary',async()=>{let opened=0;const closes=[];const row=await captureScope(['a','b'],async()=>{await Promise.resolve();throw false},{open(){return++opened},close(fd){closes.push(fd);throw undefined}});assert.equal(row.primary.value,false);assert.deepEqual(closes,[1,2]);assert.equal(row.secondary.length,2);assert.equal(row.secondary[0].value,undefined)});
await test('N04-partial-write',()=>assert.equal(fullWrite(1,Buffer.from('abcd'),()=>1),4));await test('N05-zero-write',()=>assert.throws(()=>fullWrite(1,Buffer.from('x'),()=>0)));
function receipt(){return{schema:1,id:'P01/matched-vector',layout:'built',pass:true,assertions:true,primary:{present:false},cleanup:{present:false},expectedCleanupFailure:false,testOwnerRetired:true,subjectClean:true,WorkerAttempts:1,WorkerStarts:1,WorkerOnline:1,WorkerRetired:1,stdoutDrained:1,stderrDrained:1,unknownAcquisitions:0,unknownRetirements:0,captureFault:false,WorkerExits:1,requests:1,testRescues:0,loads:['root.js','accounting.js','validation.js'].map(name=>({name:'package/ere/transport/'+name,sha256:'a'.repeat(64)})),nestedLoads:[],trace:[{kind:'attempt'},{kind:'constructed',threadId:1},{kind:'online'},{kind:'exit',code:1},{kind:'retired'}],diagnosticIdentityClaim:false};}
const observed={closed:true,signal:null,primary:{present:false},secondary:[],stdoutClosed:true,stderrClosed:true,code:0};const config={id:'P01/matched-vector',layout:'built',Workers:1,requestCeiling:1,packageRelative:'package',modules:['root.js','accounting.js','validation.js'].map(name=>({path:'package/ere/transport/'+name,sha256:'a'.repeat(64)}))};
await test('N06-composed-receipt',()=>assert.equal(judge(receipt(),observed,config).pass,true));
for(const [id,change]of [['N07-false-pass-exit',row=>{}],['N08-unknown-retirement',row=>{row.unknownRetirements=1}],['N09-spawn-counter',row=>{row.WorkerAttempts=0}],['N10-trace-contradiction',row=>{row.trace.pop()}],['N11-cleanup-contradiction',row=>{row.cleanup={present:true,kind:'undefined',value:null}}],['N12-capture-fault',row=>{row.captureFault=true}],['N13-extra-key',row=>{row.extra=1}],['N14-getter',row=>{Object.defineProperty(row,'pass',{get(){throw Error('must not call')}})}],['N15-hole',row=>{delete row.trace[0]}]])await test(id,()=>{const row=receipt();change(row);assert.throws(()=>judge(row,id==='N07-false-pass-exit'?{...observed,code:1}:observed,config));});
await test('N16-ordinary-failure',()=>{const row=receipt();row.pass=false;row.assertions=false;row.primary={present:true,kind:'boolean',value:false};assert.equal(judge(row,{...observed,code:1},config).ordinaryFailure,true)});
const result={schema:1,old14:old.passed,novel:results,passed:results.filter(row=>row.pass).length,total:results.length,syntax,Workers:0,productImports:0};writeFileSync(join(own,'CONTROL-RESULT.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});if(result.passed!==result.total)throw Error('pure controls failed');const materialized=materialize(own,join(own,'CASES'));writeFileSync(join(own,'CASE-INVENTORY.json'),JSON.stringify(materialized,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({old:14,new:results.length,syntax:syntax.length,cells:materialized.cases.length,bytes:materialized.bytes,Workers:0}));
