import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
const own = path.dirname(fileURLToPath(import.meta.url));
const root = '/Users/kjopek/Workspace/safe-bash';
const author = root + '/tests/integration/agent-bash-coherent-b2-preflight-20260829/completion-r7';
const binding = author + '/final-binding-v1';
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
function read(filename, limit = 2097152) { const stat = fs.lstatSync(filename); assert.ok(stat.isFile() && !stat.isSymbolicLink() && stat.size <= limit); const bytes = fs.readFileSync(filename); assert.equal(bytes.length, stat.size); return bytes; }
async function identity(row) { assert.equal(typeof row.path, 'string'); assert.ok(path.isAbsolute(row.path)); assert.ok(Number.isSafeInteger(row.bytes) && row.bytes >= 0); assert.match(row.sha256, /^[a-f0-9]{64}$/); const before = fs.lstatSync(row.path); assert.ok(before.isFile() && !before.isSymbolicLink()); assert.equal(before.size, row.bytes); if (row.mode !== undefined) assert.equal(before.mode & 511, row.mode); const digest = crypto.createHash('sha256'); for await (const chunk of fs.createReadStream(row.path, { highWaterMark: 65536 })) digest.update(chunk); assert.equal(digest.digest('hex'), row.sha256); const after = fs.lstatSync(row.path); assert.equal(after.ino, before.ino); assert.equal(after.dev, before.dev); assert.equal(after.size, before.size); assert.equal(after.mtimeMs, before.mtimeMs); return { path: row.path, bytes: row.bytes, sha256: row.sha256 }; }
const receiptBytes = read(binding + '/RECEIPT.json'); assert.equal(hash(receiptBytes), '6d247a13f14667af62629ac16ebc4eea65c61d3e024adbc229f3111726ef0f10');
const receipt = JSON.parse(receiptBytes); assert.equal(receipt.reviewCommit, '7ad82903e3269de5527c8308c755eb1b132bb58c'); assert.equal(receipt.sourceCandidate, '5d60457781b73783eecdd61e34d33ec7916d891b');
const packetBytes = read(author + '/staged/PACKET.json'); assert.equal(packetBytes.length, 6519); assert.equal(hash(packetBytes), 'f97901065a7803f72edb92c19f219e66f35dc2f050917d10dd25cb411ba5f65a'); const packet = JSON.parse(packetBytes);
const packetArrays = Object.values(packet).filter(value => Array.isArray(value) && value.length === 31 && value.every(row => typeof row.path === 'string' && typeof row.sha256 === 'string'));
assert.equal(packetArrays.length, 1); const checked = [];
for (const row of packetArrays[0]) { assert.ok(!path.isAbsolute(row.path) && !row.path.split('/').includes('..')); checked.push(await identity({ ...row, path: author + '/staged/' + row.path })); }
const identityArrays = Object.values(receipt).filter(value => Array.isArray(value) && value.length >= 31 && value.every(row => typeof row.path === 'string' && typeof row.sha256 === 'string'));
assert.equal(identityArrays.length, 1); for (const row of identityArrays[0]) checked.push(await identity(row));
const grantPath = '/private/tmp/B2-R7-ROOT-GO.json'; const grantBytes = read(grantPath); assert.equal(grantBytes.length, 859); assert.equal(hash(grantBytes), '720bee1710c078eb4c9ee606ae69cb101fe5fc688f5a420d715ddfe4d793f7d1'); assert.ok(grantBytes.equals(read(binding + '/GRANT.json'))); const stat = fs.lstatSync(grantPath); assert.equal(stat.mode & 511, 384); assert.equal(stat.uid, process.getuid()); const grant = JSON.parse(grantBytes);
const pending = JSON.parse(read(author + '/PENDING-AUTHORITY.json')); const expected = { ...pending, reviewCommit: receipt.reviewCommit, issuedAt: '2026-08-29T15:47:01.060Z', notBefore: '2026-08-29T15:52:01.060Z', activeDeadline: '2026-08-29T16:19:01.060Z', deadline: '2026-08-29T16:22:01.060Z' }; assert.deepEqual(grant, expected);
assert.equal(grant.caps.knownOsStarts, 64); assert.equal(grant.caps.peakOs, 3); assert.equal(grant.caps.loaderAdmissions, 34); assert.equal(grant.caps.rawBytes, 96 * 1024 * 1024); assert.equal(grant.caps.workBytes, 512 * 1024 * 1024); assert.equal(packet.roleCount, 41);
const command = `/bin/zsh ${author}/staged/new/launch.sh ${grantPath} 6519`; assert.equal(receipt.command, command);
assert.equal(receipt.externalLatestStart, '2026-08-29T15:57:01.060Z'); assert.equal(Date.parse(grant.deadline) - Date.parse(grant.notBefore), 1800000); assert.equal(Date.parse(grant.deadline) - Date.parse(grant.activeDeadline), 180000);
for (const filename of [grant.workRoot, grant.workRoot + '.outer.raw']) assert.equal(fs.existsSync(filename), false);
const now = new Date(); assert.ok(now.getTime() >= Date.parse(grant.issuedAt)); assert.ok(now.getTime() < Date.parse(receipt.externalLatestStart));
const result = { verdict: 'SCOPED_FINAL_SLOT_ACCEPT_NO_ACTIVATION', utc: now.toISOString(), receiptSha256: hash(receiptBytes), grant: { path: grantPath, bytes: grantBytes.length, sha256: hash(grantBytes), mode: '0600', uid: stat.uid }, packetSha256: hash(packetBytes), reviewCommit: receipt.reviewCommit, sourceCandidate: receipt.sourceCandidate, checkedIdentityRecords: checked.length, checked, command, cwd: root, login: false, issuedAt: grant.issuedAt, notBefore: grant.notBefore, externalLatestStart: receipt.externalLatestStart, activeDeadline: grant.activeDeadline, deadline: grant.deadline, currentBeforeNotBefore: now.getTime() < Date.parse(grant.notBefore), anchoredNoRenewal: true, publicationReserveSeconds: 180, unusedRuntimeRoots: true, noScheduler: true, noRuntime: true, fullSourceRecensus: false, knownOsPlannedInclusive: 10, maximum: 18, peak: 2, loaderAdmissions: 0 };
fs.writeFileSync(own + '/RESULT.json', JSON.stringify(result, null, 2) + '\n', { flag: 'wx' });
fs.writeFileSync(own + '/REPORT.md', `# B2-r7 final-slot review\n\nACCEPT DATA binding only at ${result.utc}. No activation authority.\n\nLive grant:859 bytes,0600,current uid${stat.uid},SHA256 ${result.grant.sha256}.\nPacket6519 bytes/f979 and accepted7ad82903 review unchanged. ${checked.length} identity records reauthenticated (packet31 plus sparse receipt records; not unique full source census). Package930368 bytes is hash-checked without inflation; Node and shell binaries stream-hashed.\n\nNot-before ${result.notBefore}; external latest-start ${result.externalLatestStart}; active-end ${result.activeDeadline}; expiry ${result.deadline}. Later launch consumes anchored remaining time, no reset;180 seconds publication reserved. Runtime and outer paths absent. Require fresh ROOT actual GO and launch-time freshness/absence recheck. External latest-start is orchestration policy, not a shipping validator field.\n\nExact command:\n\n\`${command}\`\n\nCwd ${root},login:false.64knownOS/peak3,41children,34loader admissions/one live,96MiB capture/512MiB logical work unchanged. No product/Worker/compiler/install/native/control reruns. Prior43a1c3dc0/672, prepared-source-not-evaluation, individual loader exits/native threads UNOBSERVED and trusted shell startup qualifiers preserved.\n`, { flag: 'wx' });
fs.mkdirSync(own + '/raw'); for (const name of ['startup.stdout', 'startup.stderr']) fs.copyFileSync('/tmp/b2-r7-slot-review-20260829/' + name, own + '/raw/' + name, fs.constants.COPYFILE_EXCL);
const relative = path.relative(root, own);
for (const args of [['add', '--', relative], ['commit', '--only', '-m', 'test: authenticate B2 r7 final grant slot', '--', relative], ['status', '--porcelain', '--', relative], ['rev-parse', 'HEAD']]) { const child = spawnSync('/usr/bin/git', ['-c', 'gc.auto=0', '-c', 'maintenance.auto=false', ...args], { cwd: root, stdio: ['ignore', 1, 2] }); assert.equal(child.status, 0); }
console.log(JSON.stringify({ utc: new Date().toISOString(), resultSha256: hash(read(own + '/RESULT.json')), verdict: result.verdict, checked: checked.length, command, activeChildren: 0 }));
