import fs from 'node:fs';
import {createHash} from 'node:crypto';
const own='/Users/kjopek/Workspace/safe-bash/tests/shell/pipestatus-author-20260829/preexec-v1/actual-v1';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const inputs=['/private/tmp/safe-bash-pipestatus-actual-grant-v1.stdout','/private/tmp/safe-bash-pipestatus-actual-grant-v1.stderr','/private/tmp/safe-bash-pipestatus-actual-preparation-v1.stdout','/private/tmp/safe-bash-pipestatus-actual-preparation-v1.stderr','/private/tmp/safe-bash-pipestatus-actual-authorization-commit.stdout','/private/tmp/safe-bash-pipestatus-actual-stop-inspection.stdout','/private/tmp/safe-bash-pipestatus-actual-stop-inspection.stderr'];
fs.mkdirSync(own+'/raw',{recursive:false});const raw=[];
for(let index=0;index<inputs.length;index++){const source=inputs[index],stat=fs.lstatSync(source);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>32768)throw Error('RAW_TYPE_SIZE');const bytes=fs.readFileSync(source);if(bytes.length!==stat.size)throw Error('RAW_SIZE');const filename=own+'/raw/'+String(index+1).padStart(2,'0')+'-'+source.split('/').pop();fs.writeFileSync(filename,bytes,{flag:'wx',mode:stat.mode&0o777});const check=fs.readFileSync(filename);if(!check.equals(bytes))throw Error('RAW_COPY');raw.push({source,path:filename,bytes:bytes.length,mode:stat.mode&0o777,sha256:hash(bytes)});}
const slots=['/private/tmp/safe-bash-pipestatus-actual-78-v1','/private/tmp/safe-bash-pipestatus-actual-78-v1-outer','/private/tmp/safe-bash-pipestatus-actual-78-v1.startup.stdout','/private/tmp/safe-bash-pipestatus-actual-78-v1.startup.stderr','/private/tmp/safe-bash-pipestatus-actual-78-v1.node.sha256',own+'/grant.json'];
for(const slot of slots){try{fs.lstatSync(slot);throw Error('UNEXPECTED_ACTIVATION '+slot);}catch(error){if(error.code!=='ENOENT')throw error;}}
const record={status:'HOLD_PREGRANT_HELPER_FAILURE_NO_RETRY',authorization:'ROOT_PIPESTATUS_20260829_ONE_ACTUAL_AFTER_18b0c0e6',rootReceipt:'200993b448ae5a788481784d16be1504b4a6b1ac',sealSha256:'f61b8fb41db61be3ed89fba296f5cbb9a6e8b4c80dd019202b065fe4f5a093d5',failure:{phase:'grant preparation before grant creation or terminal exec',status:1,stderr:'zsh:37: unknown function: int\n',expression:'started=$(( int(EPOCHREALTIME * 1000) ))',classification:'Reviewer preparation-shell error; not a product, archive, loader, permission or PIPESTATUS result',repairProposal:'Future separately authorized preparation must use an authenticated supported safe-integer conversion; no correction/retry applied here'},raw,absentSlotsAtPublication:slots,productCasesExecuted:0,publicExecCalls:0,contextInvokes:0,Workers:0,compilerBuildInstallCalls:0,ownerOrCollectorStarted:false,grantCreated:false,knownStartsThroughInspection:6,retirement:'Both preparation shells and apply_patch/Git children returned; no owner, collector or product child was launched. Publication roles are captured separately.',attempt:'No actual launch occurred. This authorization is left closed/HOLD pending ROOT disposition; no implicit retry or reused grant.',sourceAndHistory:'No production or sealed executable changes; original preexec/independent holds, H01/H07 source-only and manual artifact qualifiers remain unchanged.',recordedAt:new Date().toISOString()};
fs.writeFileSync(own+'/RESULT.json',JSON.stringify(record,null,2)+'\n');
console.log(JSON.stringify({status:record.status,rawFiles:raw.length,rawBytes:raw.reduce((total,row)=>total+row.bytes,0),receiptSha256:hash(fs.readFileSync(own+'/RESULT.json')),productCases:0,knownStartsThroughInspection:6,absentSlots:slots.length}));
