import type { OpObject } from "./types.js";

export const pluginRequiredFieldLabels: Readonly<Record<string, string>> = Object.freeze({
  "akamai": "Client Secret, Host, Access Token, Client Token",
  "claude": "API Key",
  "argocd": "Auth Token",
  "aws": "Access Key ID, Secret Access Key",
  "cdk": "Access Key ID, Secret Access Key",
  "sam": "Access Key ID, Secret Access Key",
  "eksctl": "Access Key ID, Secret Access Key",
  "awslogs": "Access Key ID, Secret Access Key",
  "axiom": "Token, Organization",
  "binance-cli": "API Key, API Secret",
  "cachix": "Token",
  "cargo": "Token",
  "circleci": "Token",
  "civo": "API Key",
  "cline": "API Key",
  "wrangler": "Token",
  "crash": "Host, Username, Password",
  "crowdin": "Token",
  "agent": "API Key",
  "databricks": "Host, Token",
  "dog": "API Key, App Key",
  "descope": "Project ID, Management Key",
  "doctl": "Token",
  "exercism": "URL, API Key, Directory",
  "expo": "Token",
  "eas": "Token",
  "fastly": "Token",
  "flyctl": "Token",
  "fly": "Token",
  "fossa": "API Key",
  "tea": "Token, Host Address, User",
  "gh": "Token",
  "copilot": "Token",
  "glab": "Token",
  "gemini": "API Key",
  "vault": "Token",
  "heroku": "API Key",
  "hcloud": "Token",
  "brew": "Token",
  "huggingface-cli": "User Access Token",
  "influx": "Host, Organization, Access Token",
  "junie": "API Key",
  "kaggle": "Token, Username",
  "kiro-cli": "API Key",
  "lacework": "Account, API Key ID, API Secret",
  "forge": "Token",
  "vapor": "Token",
  "linode-cli": "Token",
  "localstack": "API Key",
  "atlas": "Public Key, Private Key",
  "mysql": "Password",
  "ngrok": "Authtoken",
  "ohdear": "Token",
  "okta": "Token, Org URL",
  "openai": "API Key",
  "oaieval": "API Key",
  "oaievalset": "API Key",
  "codex": "API Key",
  "opencode": "API Key",
  "tofu": "Depends on configured credentials",
  "pd": "API Key",
  "psql": "Host, User, Password",
  "pg_dump": "Host, User, Password",
  "pg_restore": "Host, User, Password",
  "pgcli": "Host, User, Password",
  "pulumi": "Token",
  "twine": "Token",
  "flit": "Token",
  "hatch": "Token",
  "rdme": "API Key",
  "redis-cli": "Password",
  "rediscloud": "Account Key, User Key",
  "scw": "Access Key ID, Secret Access Key",
  "sentry-cli": "Token",
  "snowsql": "Account, Username, Password",
  "snyk": "Token",
  "src": "Token",
  "stripe": "Key",
  "todoist": "Token",
  "td": "API Key",
  "tugboat": "Token",
  "twilio": "Account SID, API Key, API Secret",
  "upctl": "Username, Password",
  "upstash": "API Key, Email",
  "vercel": "Token",
  "vsql": "Username, Password, Database",
  "vultr-cli": "API Key",
  "ysqlsh": "Host, Username, Password",
  "zapier": "Key",
  "zcli": "Subdomain, Email, Token",
});

export interface OpPluginAvailability {
  readonly source?: string;
  readonly name?: string;
  readonly executable?: string;
  readonly plugin_name?: string;
  readonly id?: string;
}

const nativePlugins: readonly OpPluginAvailability[] = Object.freeze([
  Object.freeze({"source":"1password-registry","name":"Akamai CLI","executable":"akamai","plugin_name":"Akamai"}),
  Object.freeze({"source":"1password-registry","name":"Claude Code","executable":"claude","plugin_name":"Anthropic"}),
  Object.freeze({"source":"1password-registry","name":"Argo CD CLI","executable":"argocd","plugin_name":"Argo CD"}),
  Object.freeze({"source":"1password-registry","name":"AWS CLI","executable":"aws","plugin_name":"AWS"}),
  Object.freeze({"source":"1password-registry","name":"AWS CDK Toolkit","executable":"cdk","plugin_name":"AWS"}),
  Object.freeze({"source":"1password-registry","name":"AWS SAM CLI","executable":"sam","plugin_name":"AWS"}),
  Object.freeze({"source":"1password-registry","name":"eksctl CLI","executable":"eksctl","plugin_name":"AWS"}),
  Object.freeze({"source":"1password-registry","name":"awslogs","executable":"awslogs","plugin_name":"AWS"}),
  Object.freeze({"source":"1password-registry","name":"Axiom CLI","executable":"axiom","plugin_name":"Axiom"}),
  Object.freeze({"source":"1password-registry","name":"Binance CLI","executable":"binance-cli","plugin_name":"Binance"}),
  Object.freeze({"source":"1password-registry","name":"Cachix CLI","executable":"cachix","plugin_name":"Cachix"}),
  Object.freeze({"source":"1password-registry","name":"Cargo CLI","executable":"cargo","plugin_name":"Cargo"}),
  Object.freeze({"source":"1password-registry","name":"CircleCI CLI","executable":"circleci","plugin_name":"CircleCI"}),
  Object.freeze({"source":"1password-registry","name":"Civo CLI","executable":"civo","plugin_name":"Civo"}),
  Object.freeze({"source":"1password-registry","name":"Cline CLI","executable":"cline","plugin_name":"Cline"}),
  Object.freeze({"source":"1password-registry","name":"Cloudflare Workers CLI","executable":"wrangler","plugin_name":"Cloudflare Workers"}),
  Object.freeze({"source":"1password-registry","name":"CrateDB Shell","executable":"crash","plugin_name":"CrateDB"}),
  Object.freeze({"source":"1password-registry","name":"Crowdin CLI","executable":"crowdin","plugin_name":"Crowdin"}),
  Object.freeze({"source":"1password-registry","name":"Cursor CLI","executable":"agent","plugin_name":"Cursor"}),
  Object.freeze({"source":"1password-registry","name":"Databricks CLI","executable":"databricks","plugin_name":"Databricks"}),
  Object.freeze({"source":"1password-registry","name":"Dogshell","executable":"dog","plugin_name":"Datadog"}),
  Object.freeze({"source":"1password-registry","name":"Descope CLI","executable":"descope","plugin_name":"Descope"}),
  Object.freeze({"source":"1password-registry","name":"DigitalOcean CLI","executable":"doctl","plugin_name":"DigitalOcean"}),
  Object.freeze({"source":"1password-registry","name":"Exercism CLI","executable":"exercism","plugin_name":"Exercism"}),
  Object.freeze({"source":"1password-registry","name":"Expo CLI","executable":"expo","plugin_name":"Expo"}),
  Object.freeze({"source":"1password-registry","name":"EAS CLI","executable":"eas","plugin_name":"Expo"}),
  Object.freeze({"source":"1password-registry","name":"Fastly CLI","executable":"fastly","plugin_name":"Fastly"}),
  Object.freeze({"source":"1password-registry","name":"Flyctl","executable":"flyctl","plugin_name":"Fly.io"}),
  Object.freeze({"source":"1password-registry","name":"Fly","executable":"fly","plugin_name":"Fly.io"}),
  Object.freeze({"source":"1password-registry","name":"FOSSA CLI","executable":"fossa","plugin_name":"FOSSA"}),
  Object.freeze({"source":"1password-registry","name":"Gitea CLI","executable":"tea","plugin_name":"Gitea"}),
  Object.freeze({"source":"1password-registry","name":"GitHub CLI","executable":"gh","plugin_name":"GitHub"}),
  Object.freeze({"source":"1password-registry","name":"GitHub Copilot CLI","executable":"copilot","plugin_name":"GitHub Copilot"}),
  Object.freeze({"source":"1password-registry","name":"GitLab CLI","executable":"glab","plugin_name":"GitLab"}),
  Object.freeze({"source":"1password-registry","name":"Google Gemini CLI","executable":"gemini","plugin_name":"Google Gemini CLI"}),
  Object.freeze({"source":"1password-registry","name":"Vault CLI","executable":"vault","plugin_name":"HashiCorp Vault"}),
  Object.freeze({"source":"1password-registry","name":"Heroku CLI","executable":"heroku","plugin_name":"Heroku"}),
  Object.freeze({"source":"1password-registry","name":"Hetzner Cloud CLI","executable":"hcloud","plugin_name":"Hetzner Cloud"}),
  Object.freeze({"source":"1password-registry","name":"Homebrew CLI","executable":"brew","plugin_name":"Homebrew"}),
  Object.freeze({"source":"1password-registry","name":"HuggingFace CLI","executable":"huggingface-cli","plugin_name":"Hugging Face"}),
  Object.freeze({"source":"1password-registry","name":"InfluxDB CLI","executable":"influx","plugin_name":"InfluxDB"}),
  Object.freeze({"source":"1password-registry","name":"JetBrains Junie CLI","executable":"junie","plugin_name":"JetBrains Junie"}),
  Object.freeze({"source":"1password-registry","name":"Kaggle CLI","executable":"kaggle","plugin_name":"Kaggle"}),
  Object.freeze({"source":"1password-registry","name":"Kiro CLI","executable":"kiro-cli","plugin_name":"Kiro"}),
  Object.freeze({"source":"1password-registry","name":"Lacework CLI","executable":"lacework","plugin_name":"Lacework"}),
  Object.freeze({"source":"1password-registry","name":"Laravel Forge CLI","executable":"forge","plugin_name":"Laravel Forge"}),
  Object.freeze({"source":"1password-registry","name":"Laravel Vapor CLI","executable":"vapor","plugin_name":"Laravel Vapor"}),
  Object.freeze({"source":"1password-registry","name":"Linode CLI","executable":"linode-cli","plugin_name":"Linode"}),
  Object.freeze({"source":"1password-registry","name":"LocalStack CLI","executable":"localstack","plugin_name":"LocalStack"}),
  Object.freeze({"source":"1password-registry","name":"MongoDB Atlas CLI","executable":"atlas","plugin_name":"MongoDB Atlas"}),
  Object.freeze({"source":"1password-registry","name":"mysql","executable":"mysql","plugin_name":"MySQL"}),
  Object.freeze({"source":"1password-registry","name":"ngrok CLI","executable":"ngrok","plugin_name":"ngrok"}),
  Object.freeze({"source":"1password-registry","name":"Oh Dear CLI","executable":"ohdear","plugin_name":"Oh Dear"}),
  Object.freeze({"source":"1password-registry","name":"Okta CLI","executable":"okta","plugin_name":"Okta"}),
  Object.freeze({"source":"1password-registry","name":"OpenAI CLI","executable":"openai","plugin_name":"OpenAI"}),
  Object.freeze({"source":"1password-registry","name":"OpenAI Evals CLI","executable":"oaieval","plugin_name":"OpenAI"}),
  Object.freeze({"source":"1password-registry","name":"OpenAI Eval Set CLI","executable":"oaievalset","plugin_name":"OpenAI"}),
  Object.freeze({"source":"1password-registry","name":"OpenAI Codex","executable":"codex","plugin_name":"OpenAI"}),
  Object.freeze({"source":"1password-registry","name":"OpenCode CLI","executable":"opencode","plugin_name":"OpenCode"}),
  Object.freeze({"source":"1password-registry","name":"OpenTofu","executable":"tofu","plugin_name":"OpenTofu"}),
  Object.freeze({"source":"1password-registry","name":"Pipedream CLI","executable":"pd","plugin_name":"Pipedream"}),
  Object.freeze({"source":"1password-registry","name":"psql","executable":"psql","plugin_name":"PostgreSQL"}),
  Object.freeze({"source":"1password-registry","name":"pg_dump","executable":"pg_dump","plugin_name":"PostgreSQL"}),
  Object.freeze({"source":"1password-registry","name":"pg_restore","executable":"pg_restore","plugin_name":"PostgreSQL"}),
  Object.freeze({"source":"1password-registry","name":"pgcli","executable":"pgcli","plugin_name":"PostgreSQL"}),
  Object.freeze({"source":"1password-registry","name":"Pulumi CLI","executable":"pulumi","plugin_name":"Pulumi"}),
  Object.freeze({"source":"1password-registry","name":"Twine","executable":"twine","plugin_name":"PyPI"}),
  Object.freeze({"source":"1password-registry","name":"Flit","executable":"flit","plugin_name":"PyPI"}),
  Object.freeze({"source":"1password-registry","name":"Hatch","executable":"hatch","plugin_name":"PyPI"}),
  Object.freeze({"source":"1password-registry","name":"ReadMe CLI","executable":"rdme","plugin_name":"ReadMe"}),
  Object.freeze({"source":"1password-registry","name":"Redis CLI","executable":"redis-cli","plugin_name":"Redis"}),
  Object.freeze({"source":"1password-registry","plugin_name":"rediscloud"}),
  Object.freeze({"source":"1password-registry","name":"Scaleway CLI","executable":"scw","plugin_name":"Scaleway"}),
  Object.freeze({"source":"1password-registry","name":"Sentry CLI","executable":"sentry-cli","plugin_name":"Sentry"}),
  Object.freeze({"source":"1password-registry","name":"Snowflake CLI","executable":"snowsql","plugin_name":"Snowflake"}),
  Object.freeze({"source":"1password-registry","name":"Snyk CLI","executable":"snyk","plugin_name":"Snyk"}),
  Object.freeze({"source":"1password-registry","name":"Sourcegraph CLI","executable":"src","plugin_name":"Sourcegraph"}),
  Object.freeze({"source":"1password-registry","name":"Stripe CLI","executable":"stripe","plugin_name":"Stripe"}),
  Object.freeze({"source":"1password-registry","name":"Todoist CLI","executable":"todoist","plugin_name":"Todoist"}),
  Object.freeze({"source":"1password-registry","name":"Treasure Data Toolbelt","executable":"td","plugin_name":"Treasure Data"}),
  Object.freeze({"source":"1password-registry","name":"Tugboat CLI","executable":"tugboat","plugin_name":"Tugboat"}),
  Object.freeze({"source":"1password-registry","name":"Twilio CLI","executable":"twilio","plugin_name":"Twilio"}),
  Object.freeze({"source":"1password-registry","name":"UpCloud CLI","executable":"upctl","plugin_name":"UpCloud"}),
  Object.freeze({"source":"1password-registry","name":"Upstash CLI","executable":"upstash","plugin_name":"Upstash"}),
  Object.freeze({"source":"1password-registry","name":"Vercel CLI","executable":"vercel","plugin_name":"Vercel"}),
  Object.freeze({"source":"1password-registry","name":"Vertica CLI","executable":"vsql","plugin_name":"Vertica"}),
  Object.freeze({"source":"1password-registry","name":"Vultr CLI","executable":"vultr-cli","plugin_name":"Vultr"}),
  Object.freeze({"source":"1password-registry","name":"YugabyteDB SQL Shell","executable":"ysqlsh","plugin_name":"YugabyteDB"}),
  Object.freeze({"source":"1password-registry","name":"Zapier CLI","executable":"zapier","plugin_name":"Zapier"}),
  Object.freeze({"source":"1password-registry","name":"Zendesk CLI","executable":"zcli","plugin_name":"Zendesk"}),
]);

export function availablePlugins(configured: readonly OpObject[]): OpPluginAvailability[] {
  const entries = nativePlugins.map(plugin => ({ ...plugin }));
  const executables = new Set(nativePlugins.flatMap(plugin => plugin.executable ? [plugin.executable.toLowerCase()] : []));
  for (const plugin of configured) {
    if (executables.has(plugin.id.toLowerCase())) continue;
    executables.add(plugin.id.toLowerCase());
    entries.push({ id: plugin.id, name: typeof plugin.name === "string" ? plugin.name : plugin.id });
  }
  return entries;
}
