import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const own=path.dirname(new URL(import.meta.url).pathname),repo=process.cwd(),deadline=Date.parse('2026-08-29T17:47:02Z'),fileCap=16777216;
const hash=raw=>crypto.createHash('sha256').update(raw).digest('hex');
const read=filename=>{const stat=fs.lstatSync(filename);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<=fileCap,filename);const raw=fs.readFileSync(filename);assert.equal(raw.length,stat.size);return raw;};
const write=(name,value)=>{const raw=Buffer.from(JSON.stringify(value,null,2)+'\n');assert(raw.length<=fileCap);fs.writeFileSync(path.join(own,name),raw,{flag:'wx'});return{path:path.join(own,name),bytes:raw.length,sha256:hash(raw)};};
let children=0;const launches=[];
function run(label,args,input){assert(Date.now()+20000+180000<deadline);const stdout=fs.openSync(path.join(own,label+'.stdout'),'wx'),stderr=fs.openSync(path.join(own,label+'.stderr'),'wx');let child;try{children++;child=spawnSync('/usr/bin/git',args,{cwd:repo,env:{PATH:'/usr/bin:/bin',HOME:process.env.HOME,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_OPTIONAL_LOCKS:'0'},stdio:[input===undefined?'ignore':'pipe',stdout,stderr],input,timeout:20000});}finally{fs.closeSync(stdout);fs.closeSync(stderr);}launches.push({label,status:child.status,signal:child.signal,pid:child.pid});assert.equal(child.status,0);return read(path.join(own,label+'.stdout'));}
function walk(root){const rows=[];function visit(folder){for(const name of fs.readdirSync(folder).sort()){const full=path.join(folder,name),stat=fs.lstatSync(full);if(stat.isDirectory())visit(full);else{assert(stat.isFile()&&!stat.isSymbolicLink());assert(stat.size<=fileCap);rows.push({path:path.relative(root,full),full,size:stat.size,mode:stat.mode&0o777});}}}visit(root);return rows;}
try{
 const publication=JSON.parse(read(path.join(own,'PRODUCER-PUBLICATION.json'))),receiptRaw=read(publication.producerReceipt.path);assert.equal(hash(receiptRaw),publication.producerReceipt.sha256);const receipt=JSON.parse(receiptRaw);const archive=read(receipt.archive.path);assert.equal(archive.length,receipt.archive.bytes);assert.equal(hash(archive),receipt.archive.sha256);
 const refs=[publication.producerCommit+':'+path.relative(repo,receipt.archive.path),publication.producerCommit+':'+path.relative(repo,publication.producerReceipt.path)];const committed=run('committed-artifact-admission',['cat-file','--batch'],refs.join('\n')+'\n');let position=0;for(const expected of [archive,receiptRaw]){const end=committed.indexOf(10,position);const [oid,kind,sizeText]=committed.subarray(position,end).toString().split(' '),size=Number(sizeText);assert.equal(kind,'blob');assert.equal(size,expected.length);const raw=committed.subarray(end+1,end+1+size);assert(raw.equals(expected));assert.equal(crypto.createHash('sha1').update(Buffer.from(`blob ${size}\0`)).update(raw).digest('hex'),oid);position=end+size+2;}assert.equal(position,committed.length);
 const source=JSON.parse(read(receipt.sourceSeal.path)),preseal=JSON.parse(read(path.join(own,'PRESEAL.json'))),emits=JSON.parse(read(receipt.emitManifest.path)),tools=JSON.parse(read(receipt.toolsSeal.path));assert.equal(hash(read(receipt.sourceSeal.path)),receipt.sourceSeal.sha256);assert.equal(hash(read(receipt.toolsSeal.path)),receipt.toolsSeal.sha256);assert.equal(hash(read(receipt.emitManifest.path)),receipt.emitManifest.sha256);
 const sourceRoot=preseal.procedure.sourceRoot,work=preseal.procedure.outputRoot;const beforeRows=[...walk(own),...walk(work)],beforeBytes=beforeRows.reduce((sum,row)=>sum+row.size,0);const referencedTools=tools.node.size+tools.git.size+tools.typescript.reduce((sum,row)=>sum+row.size,0)+tools.typedRows.reduce((sum,row)=>sum+row.size,0)+tools.npm.rows.filter(row=>row.kind==='file').reduce((sum,row)=>sum+row.size,0);assert(beforeBytes+referencedTools+2*67108864+16*1024*1024<512*1024*1024);
 const tar=zlib.gunzipSync(archive,{maxOutputLength:67108864});
 const members=new Map(),directories=[],paxHeaders=[];let cursor=0,pax={};
 const text=buffer=>buffer.toString('utf8').replace(/\0.*$/s,'');const octal=buffer=>{const value=text(buffer).trim();assert(/^[0-7]*$/.test(value));return value?parseInt(value,8):0;};
 while(cursor+512<=tar.length){const header=tar.subarray(cursor,cursor+512);if(header.every(byte=>byte===0)){assert(tar.subarray(cursor).every(byte=>byte===0));break;}const expected=octal(header.subarray(148,156));let checksum=0;for(let index=0;index<512;index++)checksum+=index>=148&&index<156?32:header[index];assert.equal(checksum,expected);let name=text(header.subarray(0,100));const prefix=text(header.subarray(345,500));if(prefix)name=prefix+'/'+name;const size=octal(header.subarray(124,136)),mode=octal(header.subarray(100,108)),type=text(header.subarray(156,157));assert(size<=fileCap);const raw=tar.subarray(cursor+512,cursor+512+size);assert.equal(raw.length,size);cursor+=512+Math.ceil(size/512)*512;assert(cursor<=tar.length);
  if(type==='x'){pax={};let offset=0;while(offset<raw.length){const space=raw.indexOf(32,offset);const length=Number(raw.subarray(offset,space).toString());assert(Number.isInteger(length)&&length>0&&offset+length<=raw.length);const item=raw.subarray(space+1,offset+length-1).toString(),equals=item.indexOf('=');assert(equals>0);pax[item.slice(0,equals)]=item.slice(equals+1);offset+=length;}paxHeaders.push({name,fields:pax});continue;}
  if(pax.path)name=pax.path;if(pax.size!==undefined)assert.equal(Number(pax.size),size);pax={};assert(name.startsWith('package/'));const relative=name.slice(8);assert(relative&&!relative.startsWith('/')&&!relative.split('/').includes('..')&&!relative.includes('\\'));if(type==='5'){directories.push({path:relative,mode});continue;}assert(type===''||type==='0','nonregular tar member '+name);assert(!members.has(relative),name);members.set(relative,{path:relative,size,mode,sha256:hash(raw),raw});
 }
 assert.equal(Object.keys(pax).length,0);assert(cursor<=tar.length);
 const shipping=[...members.values()].map(({raw,...row})=>row).sort((left,right)=>Buffer.compare(Buffer.from(left.path),Buffer.from(right.path)));
 const packFiles=receipt.packMetadata.files;assert.equal(shipping.length,packFiles.length);for(const row of packFiles){const member=members.get(row.path);assert(member,row.path);assert.equal(member.size,row.size);assert.equal(member.mode,row.mode);}
 const shipManifest=write('SHIPPING.json',{count:shipping.length,logicalBytes:shipping.reduce((sum,row)=>sum+row.size,0),canonicalEncoding:'UTF8 JSON arrays [path,size,mode,sha256], pathname byte ascending, one LF per row',canonicalSha256:hash(Buffer.from(shipping.map(row=>JSON.stringify([row.path,row.size,row.mode,row.sha256])+'\n').join(''))),members:shipping,directories,paxHeaders});
 const sourceRows=new Map(source.inputs.map(row=>[row.path,row]));for(const row of source.inputs){const raw=read(path.join(sourceRoot,row.path));assert.equal(hash(raw),row.sha256);assert.equal(fs.lstatSync(path.join(sourceRoot,row.path)).mode&0o777,parseInt(row.mode,8)&0o777);}
 assert.deepEqual(walk(sourceRoot).filter(row=>!row.path.startsWith('dist/')).map(row=>row.path).sort(),source.inputs.map(row=>row.path).sort());
 const emitted=new Map(emits.rows.map(row=>['dist/'+row.path,row]));for(const [name,row] of emitted){const member=members.get(name);assert(member,'missing compiled shipping asset '+name);assert.equal(member.sha256,row.sha256);assert.equal(member.size,row.size);assert.equal(hash(read(path.join(sourceRoot,name))),row.sha256);}for(const row of shipping){if(row.path.startsWith('dist/'))assert(emitted.has(row.path),row.path);else{const input=sourceRows.get(row.path);assert(input,'unexpected nonemit shipping input '+row.path);assert.equal(row.sha256,input.sha256);}}
 const edges=[],unresolved=[],nonliteral=[],sourceMaps=[];
 function edge(from,target,kind){if(target.startsWith('.')){const resolved=path.posix.normalize(path.posix.join(path.posix.dirname(from),target));const exists=members.has(resolved);edges.push({from,target,resolved,kind,exists});if(!exists)unresolved.push({from,target,resolved,kind});}else edges.push({from,target,kind,builtin:target.startsWith('node:')});}
 for(const [filename,member] of members){if(filename.endsWith('.map')){const map=JSON.parse(member.raw);const sources=map.sources.map(target=>path.posix.normalize(path.posix.join(path.posix.dirname(filename),map.sourceRoot??'',target)));for(const target of sources)assert(sourceRows.has(target),'unselected sourcemap input '+target);sourceMaps.push({path:filename,sources});continue;}if(!/\.(js|mjs|d\.ts)$/.test(filename))continue;const code=member.raw.toString();
  const staticPattern=/^\s*(?:import|export)\s+(?:[^;\n]*?\s+from\s+)?["']([^"']+)["']/gm;for(const match of code.matchAll(staticPattern))edge(filename,match[1],'static module');
  const dynamicPattern=/\bimport\s*\(\s*["']([^"']+)["']\s*\)/g;for(const match of code.matchAll(dynamicPattern))edge(filename,match[1],'literal dynamic module');
  const urlPattern=/new\s+URL\s*\(\s*["']([^"']+)["']\s*,\s*import\.meta\.url\s*\)/g;for(const match of code.matchAll(urlPattern))edge(filename,match[1],'literal import-meta URL');
  for(const match of code.matchAll(/\bimport\s*\((?!\s*["'])/g))nonliteral.push({path:filename,offset:match.index,kind:'nonliteral dynamic import',context:code.slice(Math.max(0,match.index-100),match.index+160)});
  for(const match of code.matchAll(/new\s+Worker\s*\(/g))nonliteral.push({path:filename,offset:match.index,kind:'Worker construction source site (not executed)',context:code.slice(Math.max(0,match.index-100),match.index+240)});
 }
 const pkg=JSON.parse(members.get('package.json').raw);assert.equal(Object.keys(pkg.dependencies??{}).length,0);assert.equal(Object.keys(pkg.optionalDependencies??{}).length,0);
 const exportTargets=[];function exportsWalk(value,trail){if(typeof value==='string'){if(value.startsWith('./')){const target=value.slice(2);if(target.includes('*')){const [prefix,suffix]=target.split('*');const matches=shipping.filter(row=>row.path.startsWith(prefix)&&row.path.endsWith(suffix)).map(row=>row.path);assert(matches.length);exportTargets.push({export:trail,target,matches});}else{assert(members.has(target),target);exportTargets.push({export:trail,target});}}}else if(value&&typeof value==='object'){for(const [key,item] of Object.entries(value))exportsWalk(item,trail+'/'+key);}}exportsWalk(pkg.exports,'exports');for(const key of ['main','module','types'])if(pkg[key]){assert(members.has(pkg[key].replace(/^\.\//,'')));}
 const privateAssets=shipping.filter(row=>row.path.startsWith('dist/commands/regex-execution/ere/'));const privateEntries=privateAssets.filter(row=>/worker.*\.js$|\/transport\/(?:owner|root)\.js$/.test(row.path));const privatePublicExports=exportTargets.flatMap(row=>row.matches??[row.target]).filter(target=>target.startsWith('dist/commands/regex-execution/ere/'));assert.equal(privatePublicExports.length,0);assert.equal(unresolved.length,0,JSON.stringify(unresolved));
 const closure=write('CLOSURE.json',{literalEdges:edges.length,edges,unresolved,privateAssetCount:privateAssets.length,privateAssets,privateEntries,publicExports:exportTargets,privatePublicExports,sourceMaps,nonliteralSites:nonliteral,qualification:'DATA/source inventory of emitted line-form static module specifiers, literal dynamic imports and literal import.meta URLs; computed/provider-controlled sites explicitly listed, not runtime closure or Worker execution proof',noRuntimeDependencies:true});
 const extras=source.excludedTrackedPaths.map(row=>({...row,classification:row.path.startsWith('scripts/')?'development workflow script':row.path.startsWith('src/')?'unselected product source (not compiled in this projection)':row.path.startsWith('types/')?'ambient/development type input':row.path.startsWith('tsconfig')?'development TypeScript configuration':'other tracked development/build input'}));const groups={};for(const row of extras)(groups[row.classification]??=[]).push(row.path);
 const usability=write('USABILITY.json',{excludedCount:extras.length,groups,exactRows:extras,filesDeleted:0,normalWorkingTreeModified:false,defaultNpmRunBuildExecuted:false,actualProcedure:preseal.procedure.commands,reason:'Only exact accepted 323-source projection was built using explicit isolated Node typeRoots. Excluded tracked inputs remain in normal checkout; this does not certify default build, all-fixture typecheck, installation, command behavior, filesystem adapters, or smoke.',packageScripts:preseal.packageScripts});
 const postRows=[...walk(own),...walk(work)],logical=postRows.reduce((sum,row)=>sum+row.size,0)+referencedTools+archive.length+tar.length+committed.length;const captures=postRows.filter(row=>/\.(stdout|stderr|raw)$/.test(row.path)).reduce((sum,row)=>sum+row.size,0);assert(logical+16*1024*1024<512*1024*1024);assert(captures<80*1024*1024);
 const result=write('DATA-RECEIPT.json',{status:'PRODUCER_DATA_READY_FOR_INDEPENDENT_AUDIT',sourceReview:{commit:'42c5df0d2e6c8246d18ddd331ad3d3a0ecb65582',receiptSha256:'aaee5bc24adb0460e0858eae44e10804ea6168a4470f13bfb84139b00d871a52',authorControls:8,novelControls:3,allPassed:true},presealCommit:receipt.presealCommit,producerCommit:publication.producerCommit,producerReceiptSha256:publication.producerReceipt.sha256,archive:receipt.archive,archiveCommitAuthenticatedBeforeDecode:true,sameBufferDecoded:true,tarBytes:tar.length,sourceCount:source.inputs.length,sourceTree:source.buildInputProjectionTree,unchangedSourceInputs:322,typedFiles:115,compilerExit:0,packExit:0,emitCount:emits.count,shippingCount:shipping.length,shipManifest,closure,usability,sourcePostguard:'All 323 content hashes and modes unchanged; exact non-dist materialized path set unchanged; all compiled shipping bytes match complete emit inventory',resources:{knownOSStartsAtPublication:55,knownOSMaximum:56,conservativePeak:3,pureHelpers:1,dataHelpers:2,correctedDataHelperLaunches:2,logicalBytesAtQuiescentSamplePlusRetainedDecodeBuffers:logical,captureBytes:captures,publicationReserveBytes:16*1024*1024,deadline:new Date(deadline).toISOString(),qualification:'quiescent sampled logical work with explicit buffer/startup reserves, not native transient peak/OS disk/RSS quota; physical Git storage excluded'},qualifications:['Not an independent producer acceptance; author producer DATA ready for audit','No Shell, Worker, native Bash, product execution, install, network, or smoke','V2 C05 fixture defect and all prior failed cohorts remain immutable','Historical feature acceptance is not transferred to unified runtime proof','First inspection launch had parse-time missing brace; original helper and stderr retained, no body executed or archive decoded on that launch'],at:new Date().toISOString()});
 const before=run('final-index-before',['diff','--cached','--name-status','-z']);const files=fs.readdirSync(own).filter(name=>fs.lstatSync(path.join(own,name)).isFile()&&!name.startsWith('inspect.stdout')&&!name.startsWith('inspect.stderr')).map(name=>path.relative(repo,path.join(own,name)));run('final-add',['add','-f','--',...files]);const output=run('final-commit',['-c','core.abbrev=40','-c','core.hooksPath=/dev/null','-c','maintenance.auto=false','-c','gc.auto=0','-c','commit.gpgsign=false','commit','--only','-m','Bind final coherent package DATA and usability qualifications','--',...files]);const after=run('final-index-after',['diff','--cached','--name-status','-z']);assert(before.equals(after),'foreign staging changed');const finalCommit=output.toString().match(/\[.*? ([0-9a-f]{40})\]/)?.[1];write('FINAL-PUBLICATION.json',{finalCommit,result,foreignStagingUnchanged:true,childrenInDataHelper:children,launches});console.log(JSON.stringify({finalCommit,result,shippingCount:shipping.length,privateAssets:privateAssets.length,literalEdges:edges.length,unresolved:unresolved.length,nonliteralSites:nonliteral,excludedGroups:groups,logicalBytes:logical,captureBytes:captures,children},null,2));
}catch(error){write('DATA-STOP.json',{error:String(error.stack??error),children,launches,at:new Date().toISOString()});console.error(error);process.exitCode=1;}
