export interface JsonParseLocation {line:number;column:number;}
export declare function formatJsonParseUserErrorMessage(label:string,filePath:string,source:string,error:unknown,options:{quotePath:boolean}):string;
export declare function removeNativeJsonParseLocation(message:string,location:JsonParseLocation):string;
export declare function getJsonParseErrorLocation(error:unknown,source:string):JsonParseLocation|null;
export declare function getJsonParseCauseLocation(error:unknown):JsonParseLocation|null;
export declare function getNumericProperty(value:unknown,key:string):number|null;
export declare function getJsonParseMessagePosition(message:string):number|null;
export declare function getSourceOffsetLocation(source:string,offset:number):JsonParseLocation;
export declare function isAsciiDigit(value:string):boolean;
