import * as own from '../dist/index.js';
import * as reference from 'terminal-pilot';
const stripA:typeof reference.stripAnsi=own.stripAnsi;
const stripB:typeof own.stripAnsi=reference.stripAnsi;
const keyA:typeof reference.keyToSequence=own.keyToSequence;
const keyB:typeof own.keyToSequence=reference.keyToSequence;
const screenA:typeof reference.TerminalScreen=own.TerminalScreen;
const screenB:typeof own.TerminalScreen=reference.TerminalScreen;
type BufferContract=Pick<reference.TerminalBuffer,keyof reference.TerminalBuffer>;
const bufferA:BufferContract=new own.TerminalBuffer(8,3);
const bufferB:own.TerminalBuffer=null as unknown as BufferContract;
void [stripA,stripB,keyA,keyB,screenA,screenB,bufferA,bufferB];
type SessionContract=Pick<reference.TerminalSession,keyof reference.TerminalSession>;
const sessionA:SessionContract=null as unknown as own.TerminalSession;
const sessionB:own.TerminalSession=null as unknown as SessionContract;
type PilotContract=Pick<reference.TerminalPilot,keyof reference.TerminalPilot>;
type OwnPilotContract=Pick<own.TerminalPilot,keyof own.TerminalPilot>;
type PublicReturns<T>={[K in keyof T]:T[K] extends (...args:infer A)=>Promise<reference.TerminalSession>? (...args:A)=>Promise<SessionContract>:T[K] extends (...args:infer A)=>reference.TerminalSession? (...args:A)=>SessionContract:T[K] extends (...args:infer A)=>reference.TerminalSession[]? (...args:A)=>SessionContract[]:T[K]};
const pilotA:PublicReturns<PilotContract>=null as unknown as OwnPilotContract;
const pilotB:PublicReturns<OwnPilotContract>=null as unknown as PilotContract;
void [sessionA,sessionB,pilotA,pilotB];
import type * as ownCommands from '../dist/commands.js';
import type * as sdkCommands from 'terminal-pilot/commands';
const runtimeA:sdkCommands.TerminalPilotRuntime=null as unknown as ownCommands.TerminalPilotRuntime;
const runtimeB:ownCommands.TerminalPilotRuntime=null as unknown as sdkCommands.TerminalPilotRuntime;
void [runtimeA,runtimeB];
import type {Group} from 'toolcraft';
const groupA:Group<any>=null as unknown as ReturnType<typeof ownCommands.createTerminalPilotGroup>;
const createA:typeof sdkCommands.createSession=null as unknown as typeof ownCommands.createSession;
const createB:typeof ownCommands.createSession=null as unknown as typeof sdkCommands.createSession;
void [groupA,createA,createB];
type AutomationNames='createSession'|'fill'|'type'|'pressKey'|'sendSignal'|'waitFor'|'waitForExit'|'readScreen'|'readHistory'|'resize'|'closeSession'|'getSession'|'listSessions';
const commandsA:Pick<typeof sdkCommands,AutomationNames>=null as unknown as Pick<typeof ownCommands,AutomationNames>;
const commandsB:Pick<typeof ownCommands,AutomationNames>=null as unknown as Pick<typeof sdkCommands,AutomationNames>;
void [commandsA,commandsB];
