import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
const own = path.dirname(fileURLToPath(import.meta.url));
const overlay = JSON.parse(readFileSync(path.join(own, "OVERLAY.json"), "utf8"));
const hash = bytes => createHash("sha256").update(bytes).digest("hex");
const bytes = readFileSync(path.join(own, "../cohort-v1.mjs"));
assert.equal(hash(bytes), overlay.baseSha256);
const original = bytes.toString("utf8");
assert.equal(original.split(overlay.replacement.before).length, 2);
const effective = original.replace(overlay.replacement.before, overlay.replacement.after);
assert.equal(hash(effective), overlay.effectiveSha256);
assert.deepEqual(original.split("\n").flatMap((line, index) => line === effective.split("\n")[index] ? [] : [index + 1]), [180]);
assert.equal(overlay.replacement.before.split("function-only").length, 3);
assert.equal(overlay.replacement.before.replaceAll("function-only", "function_only"), overlay.replacement.after);
assert.equal(effective.split("\n").length, original.split("\n").length);
assert.equal(overlay.amendedExecutionsAtSeal, 0);
console.log(JSON.stringify({ check: "overlay hashes only; no product execution", changedTokens: 2, changedLines: [180], effectiveSha256: overlay.effectiveSha256 }));
