export const cases = [
  { id: 'grep-basic', command: 'grep', args: ['-n', 'a+b'], input: 'a+b\nabb\n', output: '1:a+b\n', code: 0 },
  { id: 'grep-extended', command: 'grep', args: ['-Eo', '(ab)+'], input: 'xxabab yyab\n', output: 'abab\nab\n', code: 0 },
  { id: 'grep-fixed', command: 'grep', args: ['-F', 'a.b'], input: 'a.b\naXb\n', output: 'a.b\n', code: 0 },
  { id: 'grep-word', command: 'grep', args: ['-wo', 'cat'], input: 'cat catfish cat!\n', output: 'cat\ncat\n', code: 0 },
  { id: 'grep-empty', command: 'grep', args: ['-n', ''], input: 'a\n\nb\n', output: '1:a\n2:\n3:b\n', code: 0 },
  { id: 'grep-invert', command: 'grep', args: ['-vc', 'a'], input: 'a\nb\nc\n', output: '2\n', code: 0 },
  { id: 'grep-case', command: 'grep', args: ['-ix', 'beta'], input: 'Beta\nbetas\nBETA\n', output: 'Beta\nBETA\n', code: 0 },
  { id: 'grep-patterns', command: 'grep', args: ['-o', '-e', 'ab', '-e', 'abc'], input: 'abc ab\n', output: 'abc\nab\n', code: 0 },
  { id: 'grep-invalid', command: 'grep', args: ['['], input: 'a\n', code: 2 },
  { id: 'grep-nomatch', command: 'grep', args: ['missing'], input: 'a\n', output: '', code: 1 },
  { id: 'rg-unicode', command: 'rg', args: ['-bon', 'cat', '-'], input: 'é cat cat\n😀cat\n', output: '1:3:cat\n1:7:cat\n2:15:cat\n', code: 0 },
  { id: 'rg-fixed', command: 'rg', args: ['-F', 'a.b', '-'], input: 'a.b\naXb\n', output: 'a.b\n', code: 0 },
  { id: 'rg-case', command: 'rg', args: ['-i', 'k', '-'], input: 'k\nK\nK\n', output: 'k\nK\nK\n', code: 0 },
  { id: 'rg-empty', command: 'rg', args: ['-n', '', '-'], input: 'a\n\nb\n', output: '1:a\n2:\n3:b\n', code: 0 },
  { id: 'rg-onlyempty', command: 'rg', args: ['-o', 'a*', '-'], input: 'baac\n', output: 'aa\n', code: 0 },
  { id: 'rg-word', command: 'rg', args: ['-w', 'cat', '-'], input: 'cat\nécat\ncat!\n', output: 'cat\ncat!\n', code: 0 },
  { id: 'rg-patterns', command: 'rg', args: ['-o', '-e', 'ab', '-e', 'abc', '-'], input: 'abc ab\n', output: 'ab\nab\n', code: 0 },
  { id: 'rg-crlf', command: 'rg', args: ['--crlf', '-x', 'a', '-'], input: 'a\r\nb\r\n', output: 'a\r\n', code: 0 },
  { id: 'rg-namedbackref', command: 'rg', args: ['(?<word>a)\\k<word>', '-'], input: 'aa\n', output: 'aa\n', code: 0, approvedChange: 'default-rg-named-backref-rejection' },
  { id: 'rg-lookahead', command: 'rg', args: ['a(?=b)', '-'], input: 'ab\nac\n', code: 2 },
  { id: 'rg-invalid', command: 'rg', args: ['[', '-'], input: 'a\n', code: 2 },
  { id: 'rg-nomatch', command: 'rg', args: ['missing', '-'], input: 'a\n', output: '', code: 1 },
  { id: 'pipe-regex', script: "printf 'ab\\ncd\\nab\\n' | grep -E '^a' | rg 'b$'", output: 'ab\nab\n', code: 0 },
  { id: 'pipe-early', script: "printf 'ab\\ncd\\nab\\n' | grep -E '^a' | head -n 1", output: 'ab\n', code: 0 },
];
