import assert from 'node:assert/strict';
import * as api from 'virtual-bash';
import * as leaf from 'virtual-bash/commands/apply-patch';
const names = '[ apply_patch awk base32 base64 basename cat chmod cksum column comm cp cut date diff dirname du echo egrep env expand expr false fgrep file find fold grep gunzip gzip head html-to-markdown join jq ln ls md5sum mkdir mktemp mv nl od paste patch printenv printf pwd readlink realpath rev rg rm rmdir sed seq sha1sum sha256sum sleep sort split stat strings tac tail tar tee test timeout touch tr tree true unexpand uniq wc which xargs xxd zcat'.split(' ');
const caps = { maxPatchBytes:4194304,maxFiles:256,maxHunks:4096,maxPathBytes:16384,maxPathComponents:256,maxFileBytes:8388608,maxReadBytes:67108864,maxStagedBytes:33554432,maxLines:262144,maxInputChunks:65536,maxFsCalls:65536,maxWork:134217728,maxOutputBytes:1048576,maxDiagnosticBytes:16384 };
const quote = value => "'" + value.replaceAll("'", "'\\''") + "'";
const patch = (name='item',value='hé😀') => `*** Begin Patch\n*** Add File: ${name}\n+${value}\n*** End Patch\n`;
const summary = name => `Success. Updated the following files:\nA ${name}\n`;
const host = commands => ({ commands, use(){throw Error('unexpected middleware');}, registerFileSystem(){throw Error('unexpected FS');} });
const rows=[], shells=new Set();
async function fixture(options={},fs=new api.MemoryFileSystem()) { await fs.mkdir('/w',{recursive:true}); const shell=new api.Shell({fs,cwd:'/w'}).use(api.agentCommands(options));shells.add(shell);return {fs,shell}; }
async function absent(fs,name){await assert.rejects(fs.lstat(name),reason=>reason.code==='ENOENT');}
async function record(id,body){if(process.env.REVIEW_CASES&&!process.env.REVIEW_CASES.split(',').includes(id))return;const row={id,pass:false};const timer=setTimeout(()=>{console.error('CASE_DEADLINE',id);process.exit(78);},30000);try{await body();row.pass=true;}catch(reason){row.error=String(reason?.stack??reason);}finally{row.created=shells.size;const results=await Promise.allSettled([...shells].map(shell=>shell.dispose()));row.disposed=results.filter(result=>result.status==='fulfilled').length;shells.clear();clearTimeout(timer);if(row.disposed!==row.created){row.cleanupFailure=true;row.pass=false;}}rows.push(row);console.log(JSON.stringify(row));if(row.cleanupFailure)process.exit(78);}
await record('N01-all-fixed-caps',()=>{assert.equal(Object.keys(caps).length,14);for(const[key,max]of Object.entries(caps)){const min=key==='maxDiagnosticBytes'?32:1;for(const factory of [leaf.createApplyPatchCommand,options=>api.createAgentCommands({applyPatch:options})]){factory({limits:{[key]:min}});factory({limits:{[key]:max}});for(const value of [0,-1,max+1,Infinity,NaN,1.5,Number.MAX_SAFE_INTEGER])assert.throws(()=>factory({limits:{[key]:value}}),RangeError);}}});
await record('N02-invalid-atomic-setup',()=>{for(const limits of [{unlimited:1},{maxFiles:'2'},null]){const commands=new api.CommandRegistry([{name:'sentinel',execute:()=>({exitCode:3})}]),prior=commands.get('sentinel');assert.throws(()=>api.agentCommands({replace:true,applyPatch:{limits}}).setup(host(commands)));assert.deepEqual(commands.list(),[prior]);}assert.throws(()=>leaf.createApplyPatchCommand({limits:{unlimited:1}}),TypeError);});
await record('N03-limit-snapshot',async()=>{const limits={maxFiles:1};const{fs,shell}=await fixture({applyPatch:{limits}});await shell.exec('true');limits.maxFiles=2;const input=patch('one').replace('*** End Patch\n','*** Add File: two\n+second\n*** End Patch\n');const result=await shell.exec('apply_patch',{stdin:input});assert.equal(result.exitCode,1);assert.match(result.stderr,/maxFiles/);await absent(fs,'/w/one');await absent(fs,'/w/two');});
await record('N04-custom-preservation',()=>{const custom={name:'custom',execute:()=>({exitCode:17})},commands=new api.CommandRegistry([custom]);const before=commands.get('custom');api.agentCommands({replace:true}).setup(host(commands));assert.equal(commands.get('custom'),before);assert.equal(commands.get('custom').execute,custom.execute);assert.equal(commands.list().length,80);});
await record('N05-replacement-authority',async()=>{const commands=new api.CommandRegistry([{name:'apply_patch',execute:()=>({exitCode:19})}]),before=commands.get('apply_patch');api.agentCommands({replace:true,applyPatch:{replace:false}}).setup(host(commands));assert.notEqual(commands.get('apply_patch'),before);assert.equal(commands.list().length,79);const other=new api.CommandRegistry([before]);assert.throws(()=>api.agentCommands({applyPatch:{replace:true}}).setup(host(other)),/already registered/);assert.equal(other.get('apply_patch').execute,before.execute);assert.equal(other.list().length,1);});
await record('N06-exact79',()=>{assert.equal(names.length,79);assert.deepEqual(api.createAgentCommands().map(command=>command.name).sort(),names);for(const key of ['createApplyPatchCommand','createApplyPatchCommands','applyPatchCommands'])assert.equal(api[key],leaf[key]);for(const name of ['git','node','npm','npx','safejs','curl','yq','xan'])assert.ok(!names.includes(name));});
await record('N07-post60-tail',()=>{assert.deepEqual(api.createAgentCommands().map(command=>command.name).slice(60),['seq','nl','rev','unexpand','split','date','sleep','printenv','tree','file','egrep','fgrep','column','html-to-markdown','du','expr','which','timeout','apply_patch']);});
await record('N08-readonly-mount',async()=>{const root=new api.MemoryFileSystem(),child=new api.MemoryFileSystem();await root.mkdir('/w');await child.writeFile('/existing',Buffer.from('unchanged\n'));const fs=api.createMountFileSystem({root,mounts:{'/w':api.createReadOnlyFileSystem(child)}});const shell=new api.Shell({fs,cwd:'/w'}).use(api.agentCommands());shells.add(shell);const result=await shell.exec('apply_patch',{stdin:patch('new')});assert.equal(result.exitCode,1);assert.match(result.stderr,/read-only/);assert.equal(result.stdout,'');await absent(child,'/new');assert.equal(Buffer.from(await child.readFile('/existing')).toString(),'unchanged\n');});
await record('N09-array-stdin-pipeline',async()=>{const{fs,shell}=await fixture();const result=await shell.exec('parts=('+quote(patch('space name'))+'); printf "%s" "${parts[0]}" | apply_patch; cat '+quote('space name')+'; printf "%s\\n" "${#parts[@]}"');assert.equal(result.exitCode,0);assert.equal(result.stderr,'');assert.equal(result.stdout,summary('space name')+'hé😀\n1\n');assert.equal(Buffer.from(await fs.readFile('/w/space name')).toString(),'hé😀\n');});
await record('N10-literal-context-invoke',async()=>{const{fs,shell}=await fixture();let invoked=0;shell.register({name:'relay',async execute(context){assert.ok(context.invoke);assert.equal(context.env.KEEP,'parent');assert.equal(context.env.localOnly,undefined);invoked++;return context.invoke('apply_patch',[],{stdin:context.stdin,stdinIsDefault:false});}});const result=await shell.exec('export KEEP=parent; localOnly=secret; relay; printf "%s:%s\\n" "$KEEP" "$localOnly"',{stdin:patch()});assert.equal(invoked,1);assert.equal(result.exitCode,0);assert.equal(result.stdout,summary('item')+'parent:secret\n');assert.equal(result.stderr,'');assert.equal(Buffer.from(await fs.readFile('/w/item')).toString(),'hé😀\n');});
await record('N11-lowered-files-no-publication',async()=>{const{fs,shell}=await fixture({applyPatch:{limits:{maxFiles:1}}});const input=patch('one').replace('*** End Patch\n','*** Add File: two\n+two\n*** End Patch\n');const result=await shell.exec('apply_patch',{stdin:input});assert.equal(result.exitCode,1);assert.match(result.stderr,/maxFiles/);assert.equal(result.stdout,'');await absent(fs,'/w/one');await absent(fs,'/w/two');});
await record('N12-exact-utf8-byte-cap',async()=>{const input=patch('雪','😀'),size=Buffer.byteLength(input);for(const[limit,expected]of [[size,0],[size-1,1]]){const{fs,shell}=await fixture({applyPatch:{limits:{maxPatchBytes:limit}}});const result=await shell.exec('apply_patch',{stdin:input});assert.equal(result.exitCode,expected);if(expected){assert.match(result.stderr,/maxPatchBytes/);await absent(fs,'/w/雪');}else{assert.equal(result.stdout,summary('雪'));assert.equal(Buffer.from(await fs.readFile('/w/雪')).toString(),'😀\n');}}});
await record('N13-reused-input-and-owned-cleanups',async()=>{const fs=new api.MemoryFileSystem(),callbacks=[],bytes=Buffer.from(patch());let finalized=0;const stdin=(async function*(){try{const chunk=Buffer.alloc(1);for(const byte of bytes){chunk[0]=byte;yield chunk;}chunk[0]=0;}finally{finalized++;}})();const chunks=[];const result=await leaf.createApplyPatchCommand().execute({command:'apply_patch',args:[],cwd:'/',env:{},fs,signal:new AbortController().signal,stdin,stdout:{async write(bytes){chunks.push(Buffer.from(bytes));}},stderr:{async write(){throw Error('unexpected diagnostic');}},registerCleanup(callback){callbacks.push(callback);}});assert.equal(result.exitCode,0);assert.equal(finalized,1);assert.equal(callbacks.length,2);await Promise.all(callbacks.map(callback=>callback()));await Promise.all(callbacks.map(callback=>callback()));assert.equal(Buffer.concat(chunks).toString(),summary('item'));assert.equal(Buffer.from(await fs.readFile('/item')).toString(),'hé😀\n');});
await record('N14-abort-output-gate',async()=>{const{fs,shell}=await fixture();const controller=new AbortController(),reason={caller:'independent'};let enter,release;const entered=new Promise(resolve=>{enter=resolve;}),gate=new Promise(resolve=>{release=resolve;});let settled=false;const pending=shell.exec('apply_patch',{stdin:patch(),signal:controller.signal,stdout:{async write(){enter();await gate;}}});pending.then(()=>{settled=true;},()=>{settled=true;});try{await entered;assert.equal(settled,false);assert.equal(Buffer.from(await fs.readFile('/w/item')).toString(),'hé😀\n');controller.abort(reason);}finally{release();}await assert.rejects(pending,error=>error===reason);});
await record('N15-falsy-preabort',async()=>{const{fs,shell}=await fixture();const controller=new AbortController();controller.abort(0);let caught=false;try{await shell.exec('apply_patch',{stdin:patch(),signal:controller.signal});}catch(reason){assert.equal(reason,0);caught=true;}assert.ok(caught);await absent(fs,'/w/item');});
await record('N16-array-local-subshell',async()=>{const{fs,shell}=await fixture();const result=await shell.exec('value=(outer); f(){ local value; value=('+quote(patch())+'); apply_patch "${value[0]}"; }; (f); let count=2; printf "%s:%s\\n" "${value[0]}" "$count"');assert.equal(result.exitCode,0);assert.equal(result.stderr,'');assert.equal(result.stdout,summary('item')+'outer:2\n');assert.equal(Buffer.from(await fs.readFile('/w/item')).toString(),'hé😀\n');});
await record('N17-parent-budget-retained',async()=>{const fs=new api.MemoryFileSystem();await fs.mkdir('/w');const shell=new api.Shell({fs,cwd:'/w',limits:{maxCommands:1}}).use(api.agentCommands());shells.add(shell);await assert.rejects(shell.exec('apply_patch '+quote(patch())+'; true'),reason=>reason instanceof api.ShellLimitError&&reason.limit==='maxCommands');assert.equal(Buffer.from(await fs.readFile('/w/item')).toString(),'hé😀\n');});
console.log(JSON.stringify({summary:{cases:rows.length,pass:rows.filter(row=>row.pass).length,created:rows.reduce((total,row)=>total+row.created,0),disposed:rows.reduce((total,row)=>total+row.disposed,0)}}));
process.exitCode=rows.every(row=>row.pass)?0:1;
