import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gunzipSync,gzipSync} from 'node:zlib';
import {spawn} from 'node:child_process';
import {types as nativeTypes} from 'node:util';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {acquireCapture} from './capture-v1.mjs';
import {judgeRows,judgeControls} from './judge-v4.mjs';
const home=path.dirname(fileURLToPath(import.meta.url));
const configuration=readJSON(path.join(home,'CONTROL-v4-r1.json'),65536);
const seal=readJSON(path.join(home,'PRESEAL-v4-r1.json'),2097152);
const capture=path.join(home,configuration.capture);const work=path.join(home,configuration.work);const evidence=path.join(home,configuration.evidence);
const deadline=performance.now()+Math.max(0,Math.min(configuration.wallMs,configuration.absoluteDeadline-Date.now()));
const state={role:'node-author-validation-v2',start:new Date().toISOString(),source:configuration.source,children:[],captureControls:[],cases:[],types:[],controls:[],mutations:[],loads:[],workers:0,workerSlots:0,guestEntries:0,captureBytes:0,writtenBytes:0,unsafe:false,stopped:null,cleanup:false};
let journal;let active;let childCount=0;let copiedNode;let fixtureGraph;const overrides=new Map();const temporaryFixtures=new Set();
function sha(bytes){return createHash('sha256').update(bytes).digest('hex');}
function readBound(file,maximum){const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>maximum)throw Error('read admission '+file);return fs.readFileSync(file);}
function readJSON(file,maximum){return JSON.parse(readBound(file,maximum).toString('utf8'));}
function hashFile(file,maximum){const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>maximum)throw Error('hash admission '+file);const descriptor=fs.openSync(file,'r');const hash=createHash('sha256');const buffer=Buffer.alloc(65536);let bytes=0;try{for(;;){const count=fs.readSync(descriptor,buffer,0,buffer.length,null);if(count===0)break;bytes+=count;if(bytes>stat.size)throw Error('growing input');hash.update(buffer.subarray(0,count));}}finally{fs.closeSync(descriptor);}if(bytes!==stat.size)throw Error('short input');return {bytes,sha256:hash.digest('hex'),mode:stat.mode&511};}
function relative(value){if(typeof value!=='string'||value.startsWith('/')||value.split('/').some(part=>!part||part==='.'||part==='..'||part==='AGENTS.md')||value.includes('\\')||value.includes('\0'))throw Error('relative input');return value;}
function write(file,bytes,mode=0o600){if(!file.startsWith(work+'/')&&!file.startsWith(evidence+'/')&&!file.startsWith(capture+'/'))throw Error('write ownership');const value=typeof bytes==='string'?Buffer.from(bytes):bytes;state.writtenBytes+=value.length;if(state.writtenBytes+state.captureBytes>configuration.workBytes)throw Error('cumulative work bound');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,value,{mode});}
function event(value){const bytes=Buffer.from(JSON.stringify(value)+'\n');state.captureBytes+=bytes.length;if(state.captureBytes>configuration.captureBytes||state.writtenBytes+state.captureBytes>configuration.workBytes)throw Error('journal resource ceiling');if(bytes.length>65536)throw Error('journal frame');let offset=0;while(offset<bytes.length){const count=fs.writeSync(journal,bytes,offset,bytes.length-offset);if(count<=0)throw Error('journal short write');offset+=count;}}
function observation(error){const result={present:true,isUndefined:error===undefined,name:null,message:null};if(error!==null&&typeof error==='object'&&!nativeTypes.isProxy(error))for(const key of ['name','message']){const item=Object.getOwnPropertyDescriptor(error,key);if(item&&Object.hasOwn(item,'value')&&typeof item.value==='string')result[key]=item.value.slice(0,2048);}return result;}
function checkTime(){if(performance.now()>=deadline)throw Error('owner wall admission');}
function environment(){return {PATH:path.join(work,'bin'),HOME:path.join(work,'home'),TMPDIR:path.join(work,'tmp'),NO_COLOR:'1',TZ:'UTC',LANG:'C.UTF-8',npm_config_offline:'true',npm_config_ignore_scripts:'true',npm_config_audit:'false',npm_config_fund:'false',npm_config_cache:path.join(work,'npm-cache'),npm_config_userconfig:path.join(work,'npmrc'),npm_config_globalconfig:path.join(work,'global-npmrc'),npm_config_update_notifier:'false'};}
async function run(id,args,options={}){
  checkTime();scratchUsage();if(active||++childCount>configuration.children-1)throw Error('process admission');
  const paths=[path.join(capture,'r1-'+id+'.stdout'),path.join(capture,'r1-'+id+'.stderr')];
  const opened=acquireCapture(paths);if(!opened.ok){state.unsafe=true;state.stopped={role:'capture acquisition',primary:observation(opened.primary.value),cleanup:opened.cleanup.map(item=>observation(item.value))};throw opened.primary.value;}
  let child;let timer;let kill;let fault;let timedOut=false;let total=0;
  const record={id,pid:null,args,code:null,signal:null,spawned:false,closed:false,bytes:0,cleanupFaults:[]};state.children.push(record);
  const result=await new Promise((resolve,reject)=>{
    try{checkTime();child=spawn(copiedNode,args,{cwd:options.cwd??work,env:{...environment(),...options.env},stdio:['ignore','pipe','pipe']});}
    catch(error){fault={present:true,value:error};const cleanup=opened.close();record.cleanupFaults=cleanup.map(item=>observation(item.value));reject(error);return;}
    active=child;
    child.once('error',error=>{fault??={present:true,value:error};});
    child.once('close',(code,signal)=>{clearTimeout(timer);clearTimeout(kill);record.closed=true;record.code=code;record.signal=signal;record.bytes=total;active=undefined;const cleanup=opened.close();record.cleanupFaults=cleanup.map(item=>observation(item.value));try{event({kind:'childClose',id,pid:record.pid,code,signal,bytes:total});}catch(error){fault??={present:true,value:error};}if(fault||timedOut||signal!==null||cleanup.length){state.unsafe=true;reject(fault?fault.value:Error('child/capture retirement '+id));}else resolve(record);});
    const terminate=()=>{if(record.closed)return;child.kill('SIGTERM');kill??=setTimeout(()=>{if(!record.closed)child.kill('SIGKILL');},2000);};
    try {
    for(const [index,stream] of [child.stdout,child.stderr].entries()){stream.on('error',error=>{fault??={present:true,value:error};terminate();});stream.on('data',bytes=>{try{total+=bytes.length;state.captureBytes+=bytes.length;if(total>configuration.childCaptureBytes||state.captureBytes>configuration.captureBytes||state.writtenBytes+state.captureBytes>configuration.workBytes)throw Error('capture byte ceiling');opened.write(index,bytes);}catch(error){fault??={present:true,value:error};terminate();}});}
    active=child;record.pid=child.pid??null;record.spawned=child.pid!==undefined;
    timer=setTimeout(()=>{timedOut=true;terminate();},Math.max(1,Math.min(options.timeout??configuration.caseMs,deadline-performance.now())));
    event({kind:'childSpawn',id,pid:record.pid,args});
    }catch(error){fault??={present:true,value:error};terminate();}
  });
  scratchUsage();
  result.stdout=readBound(paths[0],configuration.childCaptureBytes).toString('utf8');result.stderr=readBound(paths[1],configuration.childCaptureBytes).toString('utf8');
  return result;
}
function scratchUsage(){let bytes=0;let entries=0;const visit=directory=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){if(++entries>20000)throw Error('scratch entry ceiling');const file=path.join(directory,entry.name);const stat=fs.lstatSync(file);if(stat.isSymbolicLink()||!stat.isFile()&&!stat.isDirectory())throw Error('scratch nonregular kind');if(stat.isDirectory())visit(file);else{bytes+=stat.size;if(stat.size>120000000||bytes>configuration.workBytes)throw Error('scratch byte ceiling');}}};if(fs.existsSync(work))visit(work);state.scratchHighWater=Math.max(state.scratchHighWater??0,bytes);return {entries,bytes};}
function census(root,maximumFiles=4096,maximumBytes=67108864){const rows=[];let bytes=0;const visit=(directory,prefix='')=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true}).sort((left,right)=>Buffer.compare(Buffer.from(left.name),Buffer.from(right.name)))){const name=prefix+entry.name;relative(name);const absolute=path.join(root,name);if(entry.isSymbolicLink())throw Error('output link '+name);if(entry.isDirectory())visit(absolute,name+'/');else if(entry.isFile()){const row=hashFile(absolute,16777216);bytes+=row.bytes;if(rows.length>=maximumFiles||bytes>maximumBytes)throw Error('census bound');rows.push({path:name,...row});}else throw Error('output kind '+name);}};visit(root);return rows;}
function decodeRows(rows,destination){for(const row of rows){const name=relative(row.path??row.target);const body=Buffer.from(row.body,'base64');if(body.length!==row.bytes||sha(body)!==row.sha256)throw Error('archive input '+name);write(path.join(destination,name),body,Number.parseInt(row.mode??'100644',8)&511);}}
function verifyGraph(moduleRoot){
 const actual=census(moduleRoot,1200,33554432);const expected=state.emissions.map(row=>overrides.has(path.join(moduleRoot,row.path))?{...row,...overrides.get(path.join(moduleRoot,row.path))}:row);if(JSON.stringify(actual)!==JSON.stringify(expected))throw Error('emission integrity drift');
 const current=census(path.join(work,'fixtures'),256,4194304);const retained=current.filter(row=>!temporaryFixtures.has(row.path));if(JSON.stringify(retained)!==JSON.stringify(fixtureGraph))throw Error('fixture/engine integrity drift');
}
function importNames(source){const names=new Set();for(const match of source.matchAll(/(?:from\s*|import\s*)["'](node:[^"']+)["']/gu))names.add(match[1]);return [...names].sort();}
function runtimeManifest(moduleRoot,extra=[]){const files=[];for(const root of [moduleRoot,path.join(work,'fixtures')])for(const row of census(root,4096,33554432)){if(!row.path.endsWith('.js')&&!row.path.endsWith('.mjs'))continue;const absolute=path.join(root,row.path);const builtins=importNames(readBound(absolute,262144).toString('utf8'));const role=(root===moduleRoot?'module/':'fixtures/')+row.path;const admitted=readJSON(path.join(home,'BUILTINS-v4-r1.json'),262144).rows.find(item=>item.path===role);if(!admitted&&!temporaryFixtures.has(row.path)||builtins.some(name=>!admitted?.builtins.includes(name)))throw Error('unsealed importer builtin edge');files.push({...row,path:absolute,builtins});}for(const row of extra)files.push(row);const manifest=path.join(work,'load-manifest.json');write(manifest,JSON.stringify({files}));return manifest;}
function childArgs(entry,manifest){return ['--experimental-permission','--allow-fs-read='+work,'--allow-fs-write='+work,'--allow-worker','--import',path.join(work,'fixtures/host-guard-v1.mjs'),...(manifest?['--import',path.join(work,'fixtures/load-guard-v1.mjs')]:[]),entry];}
function loadRows(record){const rows=[];for(const line of record.stderr.split('\n'))if(line.startsWith('@@NODE_LOAD ')){if(rows.length>=2048)throw Error('load witness bound');const row=JSON.parse(line.slice(12));if(typeof row.path!=='string'||!Number.isSafeInteger(row.bytes)||typeof row.sha256!=='string')throw Error('load witness shape');rows.push(row);}return rows;}
function receipts(record){const rows=[];for(const line of record.stdout.trim().split('\n')){if(!line)continue;if(line.length>65536)throw Error('receipt frame');const row=JSON.parse(line);if(row.role!=='case-receipt-v1'&&row.role!=='focused-summary'&&row.role!=='worker-summary')throw Error('receipt role');rows.push(row);}return rows;}
async function oneCase(layout,moduleRoot,id,role='worker'){
  verifyGraph(moduleRoot);
  if(role==='worker'&&++state.workerSlots>configuration.workers)throw Error('Worker slot admission');const name=layout+'-'+id;const realRoot=path.join(work,'real',name);fs.mkdirSync(realRoot,{recursive:true});const input=path.join(work,'case-input.json');write(input,JSON.stringify({role,id,moduleRoot,adapter:path.join(work,'fixtures/engine-adapter-v1.mjs'),realRoot}));const manifest=runtimeManifest(moduleRoot);
  const record=await run(name,[...childArgs(path.join(work,'fixtures/case-runner-v4.mjs'),manifest),input],{env:{NODE_AUTHOR_LOAD_MANIFEST:manifest}});
  verifyGraph(moduleRoot);
  if(record.stdout.includes('AUTHOR_NATIVE_STDOUT_PROBE')||record.stderr.includes('AUTHOR_NATIVE_STDERR_PROBE'))throw Error('product Worker diagnostic escaped virtual stdio ownership');
  const rows=judgeRows(receipts(record),record.code,role,id,readJSON(path.join(home,'WORKER-CASES-v4.json'),32768));const last=rows.at(-1);if(!last||last.count!==(role==='worker'?1:34)||last.pass!==rows.slice(0,-1).every(row=>row.pass===true)||record.code!==(last.pass?0:1))throw Error('contradictory case completion '+name);
  const loads=loadRows(record);if(!loads.some(row=>row.path===moduleRoot+'/commands/node/index.js'))throw Error('missing actual module load '+name);state.loads.push({name,rows:loads});
  if(role==='worker'){const receipt=rows[0];if(rows.length!==2||receipt.id!==id||receipt.clean!==true||![0,1].includes(receipt.workers)||receipt.exits!==receipt.workers||receipt.workers===1&&receipt.retired!==1||receipt.workers===0&&receipt.noAcquisition!==true||last.clean!==true)throw Error('unclean Worker receipt '+name);state.workers+=receipt.workers;state.guestEntries+=receipt.guestEntries;if(state.workers>configuration.workers||state.guestEntries>configuration.guests)throw Error('actual Worker/guest ceiling');state.cases.push({layout,...receipt});return receipt;}
  if(rows.length!==35)throw Error('focused row cardinality');state.cases.push(...rows.slice(0,-1).map(row=>({layout,...row})));return last;
}
async function types(layout,moduleRoot){const original=readBound(path.join(home,'types-v1.mts.data'),32768).toString('utf8').replaceAll('__MODULE__',moduleRoot);const positive=path.join(work,'types',layout+'.mts');write(positive,original);const compiler=path.join(work,'tools/typescript/lib/tsc.js');const argumentsFor=file=>[...childArgs(compiler), '--noEmit','--strict','--exactOptionalPropertyTypes','--noUncheckedIndexedAccess','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2023','--skipLibCheck','--types','node','--typeRoots',path.join(work,'source/node_modules/@types'),'--listFiles',file];const accepted=await run('types-'+layout,argumentsFor(positive),{timeout:configuration.buildMs});const negative=path.join(work,'types',layout+'-negative.mts');const stripped=original.replace(/^\/\/ @ts-expect-error.*\n/gmu,'');if((original.match(/@ts-expect-error/gu)??[]).length!==12)throw Error('negative type cardinality');write(negative,stripped);const rejected=await run('types-negative-'+layout,argumentsFor(negative),{timeout:configuration.buildMs});const diagnostics=(rejected.stdout.match(/error TS\d+:/gu)??[]).length;state.types.push({layout,positiveIdentities:12,negativeIdentities:12,positiveExit:accepted.code,negativeExit:rejected.code,diagnostics,pass:accepted.code===0&&rejected.code!==0&&diagnostics===12});}
function tarRows(bytes){const data=gunzipSync(bytes,{maxOutputLength:33554432});const rows=[];for(let offset=0;offset+512<=data.length;){const header=data.subarray(offset,offset+512);if(header.every(value=>value===0))break;const name=header.subarray(0,100).toString('utf8').replace(/\0.*$/u,'');const size=Number.parseInt(header.subarray(124,136).toString('ascii').replace(/\0.*$/u,'').trim()||'0',8);const kind=header[156];if(!Number.isSafeInteger(size)||size<0||size>16777216||offset+512+size>data.length)throw Error('tar size');if(kind!==48&&kind!==0)throw Error('tar non-regular entry');relative(name);const body=data.subarray(offset+512,offset+512+size);rows.push({path:name,bytes:size,sha256:sha(body)});if(rows.length>1200)throw Error('tar count');offset+=512+Math.ceil(size/512)*512;}return rows;}
async function layouts(sourceRoot){
  const sourceModule=path.join(sourceRoot,'dist');await oneCase('source',sourceModule,'focused','focused');for(let index=1;index<=27;index++)await oneCase('source',sourceModule,'W'+String(index).padStart(2,'0'));await types('source',sourceModule);
  const packDir=path.join(work,'pack');fs.mkdirSync(packDir,{recursive:true});const npm=path.join(work,'tools/npm/bin/npm-cli.js');const packed=await run('pack',[...childArgs(npm),'pack','--json','--offline','--ignore-scripts','--pack-destination',packDir],{cwd:sourceRoot,timeout:configuration.buildMs});if(packed.code!==0)throw Error('pack nonzero');const packResult=JSON.parse(packed.stdout);if(!Array.isArray(packResult)||packResult.length!==1||typeof packResult[0].filename!=='string'||packResult[0].filename.includes('/'))throw Error('pack result');const tar=path.join(packDir,packResult[0].filename);const tarBytes=readBound(tar,4194304);const entries=tarRows(tarBytes);const baseline=readJSON(path.join(home,'BASE-PACKAGE-v1.json'),262144);if(entries.length!==958)throw Error('whole package entry count');const projection=entries.filter(row=>!row.path.startsWith('package/dist/commands/node/')).sort((a,b)=>Buffer.compare(Buffer.from(a.path),Buffer.from(b.path)));const expectedProjection=baseline.entries.slice().sort((a,b)=>Buffer.compare(Buffer.from(a.path),Buffer.from(b.path)));if(JSON.stringify(projection)!==JSON.stringify(expectedProjection))throw Error('accepted baseline package projection changed');state.package={bytes:tarBytes.length,sha256:sha(tarBytes),entries};write(path.join(evidence,'r1-PACKAGE.tgz.base64'),tarBytes.toString('base64')+'\n');
  const consumer=path.join(work,'consumer');write(path.join(consumer,'package.json'),'{"name":"node-module-author-consumer","version":"1.0.0","private":true,"type":"module"}\n');const installed=await run('install',[...childArgs(npm),'install',tar,'--offline','--ignore-scripts','--no-audit','--no-fund','--package-lock=false','--bin-links=false','--omit=dev'],{cwd:consumer,timeout:configuration.buildMs});if(installed.code!==0)throw Error('offline install nonzero');
  for(const layout of ['installed','moved']){let root=consumer;if(layout==='moved'){root=path.join(work,'physically-moved');fs.renameSync(consumer,root);state.originAbsent=!fs.existsSync(consumer);if(!state.originAbsent)throw Error('installation origin remains');}const moduleRoot=path.join(root,'node_modules/virtual-bash/dist');const actual=census(moduleRoot);if(JSON.stringify(actual.map(({mode,...row})=>row))!==JSON.stringify(state.emissions.map(({mode,...row})=>row)))throw Error('installed/moved emission mismatch');await oneCase(layout,moduleRoot,'focused','focused');for(let index=1;index<=27;index++)await oneCase(layout,moduleRoot,'W'+String(index).padStart(2,'0'));await types(layout,moduleRoot);}
  await controls(sourceModule);
}
async function controls(moduleRoot){
 const mutations=readJSON(path.join(home,'MUTATIONS-v1.json'),32768);
 for(const mutation of mutations){const file=path.join(moduleRoot,mutation.file);const original=readBound(file,262144).toString('utf8');let modified=original;for(const change of mutation.changes){const matches=modified.split(change.from).length-1;if(matches!==change.count){state.mutations.push({id:mutation.id,disposition:'UNRUN_EMISSION_ANCHOR',expected:change.count,actual:matches});modified=undefined;break;}modified=modified.split(change.from).join(change.to);}if(modified===undefined)continue;write(file,modified);overrides.set(file,hashFile(file,262144));const mutant=await oneCase(mutation.id+'-mutant',moduleRoot,mutation.case,mutation.case==='focused'?'focused':'worker');write(file,original);overrides.delete(file);const restored=await oneCase(mutation.id+'-restore',moduleRoot,mutation.case,mutation.case==='focused'?'focused':'worker');state.mutations.push({id:mutation.id,mutantDetected:mutant.pass===false,restorePass:restored.pass===true,pass:mutant.pass===false&&restored.pass===true});}
 const template=readBound(path.join(home,'load-negative-v1.mjs.data'),16384).toString('utf8');for(const id of ['source-fallback','builtin-edge','package-fallback','pass-nonzero','missing-receipt','tamper']){const file=path.join(work,'fixtures/negative-'+id+'.mjs');const forbidden=path.join(work,'source/src/commands/node/index.ts');const tampered=path.join(work,'fixtures/tamper-target.mjs');temporaryFixtures.add(path.basename(file));temporaryFixtures.add(path.basename(tampered));verifyGraph(moduleRoot);write(tampered,'export const marker=1;\n');write(file,template.replaceAll('__MODULE__',moduleRoot).replaceAll('__FORBIDDEN__',pathToFileURL(forbidden).href).replaceAll('__TAMPER__',pathToFileURL(tampered).href));const manifest=runtimeManifest(moduleRoot);if(id==='tamper')write(tampered,'export const marker=2;\n');const record=await run('load-negative-'+id,[...childArgs(file,manifest),id],{env:{NODE_AUTHOR_LOAD_MANIFEST:manifest}});const loaded=loadRows(record).some(row=>row.path===moduleRoot+'/commands/node/index.js');const pass=loaded&&(id==='pass-nonzero'?record.code===1&&record.stdout==='PASS\n':id==='missing-receipt'?record.code===0&&record.stdout==='PASS\n':record.code!==0&&record.stderr.includes('AUTHOR_LOAD_'));state.controls.push({id,loaded,code:record.code,pass});fs.unlinkSync(file);fs.unlinkSync(tampered);temporaryFixtures.delete(path.basename(file));temporaryFixtures.delete(path.basename(tampered));verifyGraph(moduleRoot);}
}
try{
 for(const value of [configuration.capture,configuration.work,configuration.evidence])relative(value);if(!configuration.capture.startsWith('validation-v2/')||!configuration.work.startsWith('validation-v2/')||!configuration.evidence.startsWith('validation-v2/'))throw Error('owned output roots');
 fs.mkdirSync(capture,{recursive:true});fs.mkdirSync(evidence,{recursive:true});journal=fs.openSync(path.join(capture,'journal-r1.jsonl'),'wx',0o600);event({kind:'ownerEntry',pid:process.pid,configuration:sha(readBound(path.join(home,'CONTROL-v4-r1.json'),65536))});
 if(fs.existsSync(work))throw Error('work root reuse');fs.mkdirSync(work,{recursive:true});
 for(const row of seal.files){const result=hashFile(path.join(home,relative(row.path)),4194304);if(result.bytes!==row.bytes||result.sha256!==row.sha256)throw Error('preseal '+row.path);}
 if(hashFile(process.execPath,120000000).sha256!==seal.nodeSha256)throw Error('Node identity');
 state.captureControlsInherited={commit:'1dfcd65fa24a710f27cea82022da8aafda2bf8be',count:7,rerun:false};
 state.judgeControls=judgeControls();
 const archive=JSON.parse(gunzipSync(Buffer.from(readBound(path.join(home,'INPUTS-v1.json.gz.base64'),4194304).toString('ascii').trim(),'base64'),{maxOutputLength:16777216}).toString('utf8'));
 const moduleRows=readJSON(path.join(home,'MODULE-v6-r1.json'),1048576).files;
 const sourceRoot=path.join(work,'source');decodeRows(archive.baseline,sourceRoot);decodeRows(moduleRows,sourceRoot);
 const fixtureRoot=path.join(work,'fixtures');for(const row of seal.files)if(row.path.endsWith('.mjs')&&!['owner-v4-r1.mjs','capture-v1.mjs','startup-capture-v3.mjs','startup-owner-v4-r1.mjs'].includes(row.path))write(path.join(fixtureRoot,row.path),readBound(path.join(home,row.path),262144));
 for(const row of archive.engine){const target=row.target.replace(/^compiled\//u,'');decodeRows([{...row,path:target}],fixtureRoot);}
 for(const [name,tool] of Object.entries(archive.tools)){if(name==='node'){const input=hashFile(tool.origin,120000000);if(input.sha256!==tool.sha256||input.bytes!==tool.bytes)throw Error('Node tool drift');copiedNode=path.join(work,'bin/node');fs.mkdirSync(path.dirname(copiedNode),{recursive:true});fs.copyFileSync(tool.origin,copiedNode);fs.chmodSync(copiedNode,0o755);if(hashFile(copiedNode,120000000).sha256!==tool.sha256)throw Error('copied Node identity');state.writtenBytes+=input.bytes;if(state.writtenBytes+state.captureBytes>configuration.workBytes)throw Error('tool copy work bound');continue;}for(const row of tool.rows){relative(row[0]);if(row.length===3){if(!fs.lstatSync(path.join(tool.origin,row[0])).isSymbolicLink()||fs.readlinkSync(path.join(tool.origin,row[0]))!==row[2])throw Error('tool alias');continue;}const input=hashFile(path.join(tool.origin,row[0]),10000000);if(input.bytes!==row[2]||input.sha256!==row[3]||input.mode!==row[1])throw Error('tool drift');const target=path.join(work,'tools',name,row[0]);fs.mkdirSync(path.dirname(target),{recursive:true});if(state.writtenBytes+state.captureBytes+input.bytes>configuration.workBytes)throw Error('tool copy admission');fs.copyFileSync(path.join(tool.origin,row[0]),target);fs.chmodSync(target,row[1]);const copied=hashFile(target,10000000);if(copied.bytes!==input.bytes||copied.sha256!==input.sha256||copied.mode!==input.mode)throw Error('tool destination drift');state.writtenBytes+=input.bytes;}}
 fs.mkdirSync(path.join(sourceRoot,'node_modules/@types'),{recursive:true});for(const [name,target] of [['@types/node','@types/node'],['undici-types','undici-types']]){const origin=path.join(work,'tools',name);const destination=path.join(sourceRoot,'node_modules',target);for(const row of census(origin,128,4194304))write(path.join(destination,row.path),readBound(path.join(origin,row.path),262144),row.mode);}
 for(const directory of ['home','tmp','npm-cache'])fs.mkdirSync(path.join(work,directory),{recursive:true});write(path.join(work,'npmrc'),'offline=true\nignore-scripts=true\naudit=false\nfund=false\n');write(path.join(work,'global-npmrc'),'');
 fixtureGraph=census(fixtureRoot,256,4194304);state.fixtureGraph=fixtureGraph;
 const built=await run('build',[...childArgs(path.join(work,'tools/typescript/lib/tsc.js')),'-p',path.join(sourceRoot,'tsconfig.build.json')],{cwd:sourceRoot,timeout:configuration.buildMs});
 state.build={code:built.code,diagnostics:(built.stdout+'\n'+built.stderr).split('\n').filter(line=>line.includes('error TS'))};
 state.emissions=fs.existsSync(path.join(sourceRoot,'dist'))?census(path.join(sourceRoot,'dist'),1200,33554432):[];
 if(built.code!==0)throw Error('strict source build failed; downstream slots unrun');
 if(state.emissions.length!==956)throw Error('full emission graph cardinality');
 await layouts(sourceRoot);
 state.pass=state.cases.filter(row=>['source','installed','moved'].includes(row.layout)).every(row=>row.pass)&&state.types.every(row=>row.pass)&&state.controls.length===6&&state.controls.every(row=>row.pass)&&state.mutations.length===6&&state.mutations.every(row=>row.pass);
}catch(error){state.stopped??=observation(error);state.pass=false;}
finally{
 if(active){state.unsafe=true;state.stopped={name:'UnknownRetirement',message:'active owned child at finalization'};}
 state.end=new Date().toISOString();state.allChildrenClosed=state.children.every(row=>row.closed);state.processCount=1+state.children.filter(row=>row.spawned).length;
 try{if(journal!==undefined){event({kind:'ownerRetiring',children:state.processCount,unsafe:state.unsafe});fs.closeSync(journal);journal=undefined;}
 const raw=JSON.stringify(state);write(path.join(evidence,'r1-RAW.json.gz.base64'),gzipSync(Buffer.from(raw),{level:9}).toString('base64')+'\n');const rawHash=hashFile(path.join(evidence,'r1-RAW.json.gz.base64'),16777216);write(path.join(evidence,'r1-ARCHIVE.json'),JSON.stringify(rawHash)+'\n');
 if(!state.unsafe&&state.allChildrenClosed&&fs.existsSync(work)){fs.rmSync(work,{recursive:true,force:false});state.cleanup=!fs.existsSync(work);}write(path.join(evidence,'r1-SUMMARY.json'),JSON.stringify({pass:state.pass,unsafe:state.unsafe,stopped:state.stopped,processCount:state.processCount,workers:state.workers,guestEntries:state.guestEntries,cleanup:state.cleanup,raw:rawHash})+'\n');
 }catch(error){state.unsafe=true;process.stderr.write('AUTHOR_FINALIZATION_FAILURE '+JSON.stringify(observation(error))+'\n');}
 process.stdout.write(JSON.stringify({role:'owner-final',pass:state.pass,unsafe:state.unsafe,children:state.processCount,workers:state.workers,guests:state.guestEntries,cleanup:state.cleanup})+'\n');process.exitCode=state.pass&&!state.unsafe&&state.cleanup?0:1;
}
