import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,lstatSync,realpathSync} from 'node:fs';
import {gunzipSync} from 'node:zlib';
import {basename} from 'node:path';
const packetCommit='d9dd698a33421b197ee15432a6606ad91dd06c63';
const source='fe15f1e406fa1039accddec25c696ae7187f6135';
const accepted='97c081ec7c7f180889d3640c29d1cd5fd1b10752';
const packetRoot='tests/integration/full-gate-20260827/unified76-driver/release-packet-v2-final-routes/';
const driverRoot='tests/integration/full-gate-20260827/unified76-driver/launcher-v3/';
const reviewRoot='tests/integration/full-gate-20260827/unified76-driver-independent/tool-routes-v10/';
const git=args=>execFileSync('/Applications/Xcode.app/Contents/Developer/usr/bin/git',['--no-replace-objects',...args],{env:{PATH:'/dev/null',GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_OPTIONAL_LOCKS:'0'},timeout:10000,maxBuffer:4194304});
const blob=(revision,path)=>git(['show',revision+':'+path]);
const json=(revision,path)=>JSON.parse(blob(revision,path));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const normalized=data=>sha(JSON.stringify(data));
const packet=json(packetCommit,packetRoot+'PACKET.json'),seal=json(packetCommit,packetRoot+'SEAL.json'),template=json(packetCommit,packetRoot+'ROOT-RECEIPT.template.json');
const bindings=json(accepted,reviewRoot+'BINDINGS.json');
assert.equal(normalized(packet),'7e40e84c099d8eaa2e9bc4c1cc73274b4a174d699737f34b7015eb4eb706ec70');
assert.equal(seal.normalizedPacketSha256,normalized(packet));
for(const row of seal.files){const bytes=blob(packetCommit,packetRoot+row.path);assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);}
assert.equal(packet.executionAuthorized,false);assert.equal(packet.fullGateLaunched,false);
assert.equal(packet.driver.source,source);assert.equal(packet.independent.acceptedCommit,accepted);
assert.equal(packet.driver.files.length,38);
assert.deepEqual(packet.driver.files.map(row=>basename(row.path)).sort(),Object.keys(bindings.files).sort());
const shipping=[];
for(const row of packet.driver.files){assert.ok(row.path.startsWith(driverRoot));assert.equal(row.revision,source);assert.equal(row.mode,'100644');const bytes=blob(source,row.path),expected=bindings.files[basename(row.path)];assert.equal(sha(bytes),row.sha256);assert.equal(row.sha256,expected.sha256);assert.equal(bytes.length,row.bytes);assert.equal(row.bytes,expected.bytes);assert.equal(row.blob,expected.gitBlob);assert.equal(git(['rev-parse',source+':'+row.path]).toString().trim(),row.blob);assert.equal(git(['ls-tree',source,'--',row.path]).toString().split(' ')[0],row.mode);assert.equal(sha(blob(packetCommit,row.path)),row.sha256);const stat=lstatSync(row.path);assert.ok(stat.isFile()&&!stat.isSymbolicLink());assert.equal(sha(readFileSync(row.path)),row.sha256);shipping.push({path:row.path,blob:row.blob,sha256:row.sha256,liveRegularBytesMatch:true});}
assert.equal(packet.independent.proofFiles.length,5);
for(const row of packet.independent.proofFiles){assert.equal(row.revision,accepted);const bytes=blob(accepted,row.path);assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256);assert.equal(git(['rev-parse',accepted+':'+row.path]).toString().trim(),row.blob);assert.equal(row.mode,'100644');assert.equal(sha(readFileSync(row.path)),row.sha256);}
const driver=json(source,driverRoot+'DRIVER.json');
assert.equal(Object.keys(driver.files).length,37);for(const[name,hash]of Object.entries(driver.files))assert.equal(bindings.files[name].sha256,hash);
assert.equal(normalized(driver),packet.driver.normalizedSha256);assert.equal(normalized(driver),bindings.normalizedDriverSha256);
const decode=name=>JSON.parse(gunzipSync(Buffer.from(blob(source,driverRoot+name).toString().trim(),'base64'),{maxOutputLength:33554432}));
const profile=decode('PROFILE.json.gz.base64'),external=decode('EXTERNAL.json.gz.base64'),projection=json(source,driverRoot+'INSTRUCTION-PROJECTION.json'),routes=json(source,driverRoot+'TOOL-ROUTES.json'),candidate=json(source,driverRoot+'CANDIDATE.json');
assert.equal(normalized(profile),packet.profile.normalizedSha256);assert.equal(normalized(profile),bindings.profileSha256);
assert.equal(normalized(projection),packet.projection.normalizedSha256);assert.equal(normalized(projection),bindings.projectionSha256);
assert.equal(normalized(routes),packet.tools.routesNormalizedSha256);assert.equal(normalized(routes),bindings.toolRoutesSha256);assert.deepEqual(packet.tools.routes,routes);
assert.deepEqual(packet.tools.externalReceipt,bindings.externalReceipt);assert.deepEqual(packet.tools.readableTools,external.tools);assert.deepEqual(packet.tools.nativeAssets,external.native.assets);
for(const[name,tree]of Object.entries(external.directories))assert.deepEqual(packet.tools.dependencyTrees[name],{origin:tree.origin,entries:tree.entries.length,bytes:tree.bytes,sha256:tree.sha256});
assert.deepEqual(packet.projection.candidateEntries,projection.candidateEntries);assert.deepEqual(packet.projection.dependencyEntries,projection.dependencyEntries);assert.equal(projection.candidateEntries.length,5);assert.equal(projection.dependencyEntries.length,1);
for(const name of ['logical','physical','opaqueGit'])assert.deepEqual(packet.projection[name],projection[name]);
for(const name of ['candidate','tree','sourceTree'])assert.equal(packet.product[name],profile[name]);
assert.equal(packet.product.candidate,'f5e9fc49b6abb38e180cc9de16c95fced102ff75');assert.equal(packet.product.base,'44f00bf84278e3361b52106478d59c707ab7b2bc');
assert.equal(git(['rev-parse',packet.product.candidate+'^{tree}']).toString().trim(),packet.product.tree);
assert.equal(packet.product.expectedPackageSha256,'c109372f90b1bd19bcf756cf993bb2976fb52b75fe0c92a1cf96dab4c229b5cd');assert.equal(packet.product.expectedPackageSha256,candidate.expectedPackageSha256);assert.equal(packet.product.packageManifestSha256,profile.packageManifestSha256);assert.equal(packet.product.packageRebuiltHere,false);
const fixturePaths=git(['diff','--name-only',packet.product.base,packet.product.candidate,'--']).toString().trim().split('\n');assert.equal(fixturePaths.length,4);
assert.equal(packet.profile.scopeEntries,profile.scopeInputs.length);assert.equal(packet.profile.canonicalPaths,profile.canonicalFiles.length);assert.equal(packet.profile.classifiedMts,profile.classifiedMts.length);assert.equal(packet.profile.cleanupInputs,Object.keys(profile.cleanup.files).length);assert.equal(packet.profile.cleanupNormalizedSha256,normalized(profile.cleanup));assert.deepEqual(packet.profile.support,profile.support);
for(const name of ['defaultCount','testConcurrency','reporter'])assert.equal(packet.profile[name],profile[name]);
assert.equal(template.action,'AWAITING_FRESH_ROOT_RELEASE');assert.equal(template.authorization,'');
for(const[name,expected]of Object.entries({candidate:packet.product.candidate,driverSha256:normalized(driver),profileSha256:normalized(profile),packageSha256:packet.product.expectedPackageSha256}))assert.equal(template[name],expected);
for(const name of ['public74','public75','public76','independentDriverAccepted'])assert.equal(template[name],true);
assert.equal(template.independentEvidence,accepted+':'+reviewRoot+'HANDOFF.md');
const policy=blob(source,driverRoot+'policy.mjs').toString(),run=blob(source,driverRoot+'run.mjs').toString(),execute=blob(source,driverRoot+'execute.mjs').toString(),phaseRunner=blob(source,driverRoot+'phase-runner.mjs').toString(),supervise=blob(source,driverRoot+'supervise.mjs').toString();
const phaseSection=policy.slice(policy.indexOf('export const PHASES'),policy.indexOf('export function parseArgs'));
const phases=[...phaseSection.matchAll(/\['([^']+)', (\d+)\]/gu)].map(match=>({name:match[1],expectedStatus:Number(match[2])}));assert.equal(phases.length,14);assert.deepEqual(packet.phases,phases);
const expectedBounds={archiveEntries:37397,archiveBytes:2382440321,archiveTransferBytes:3221225472,historyTransferBytes:8589934592,dependencyBytes:1073741824,setupStderrBytes:1048576,phaseOutputBytes:268435456,allPhaseOutputBytes:4294967296,setupTimeoutMs:600000,phaseTimeoutMs:1800000,cleanupTimeoutMs:5000,chunkBytes:65536,maximumLineBytes:1048576,totalSupervisorMs:25805000,observerRequests:4096,maintainedConsumerTimeoutMs:900000,secondaryDiagnosticBytes:8388608,maximumTapCases:100000};assert.deepEqual(packet.bounds,expectedBounds);
assert.equal(packet.bounds.totalSupervisorMs,packet.bounds.setupTimeoutMs+phases.length*packet.bounds.phaseTimeoutMs+packet.bounds.cleanupTimeoutMs);
assert.ok(run.includes('BOUNDS.setupTimeoutMs+PHASES.length*BOUNDS.phaseTimeoutMs+BOUNDS.cleanupTimeoutMs'));assert.ok(run.includes('PHASES.slice(0,-1)'));assert.ok(execute.includes("requireOrdered(completed,'final-sweep')"));assert.ok(phaseRunner.includes('Math.min(timeoutMs,BOUNDS.phaseTimeoutMs)'));assert.ok(phaseRunner.includes('BOUNDS.allPhaseOutputBytes-totalOutput'));assert.ok(supervise.includes('options.timeoutMs'));assert.ok(supervise.includes('options.setupTimeoutMs'));
assert.equal(packet.launch.cwd,'/Users/kjopek/Workspace/safe-bash');assert.equal(packet.launch.script,driverRoot+'run.mjs');assert.deepEqual(packet.launch.executable,external.tools.find(row=>row.origin==='/Users/kjopek/.nvm/versions/node/v24.11.1/bin/node'));
assert.deepEqual(packet.launch.args,['--candidate',packet.product.candidate,'--run',packet.launch.output,'--release',packet.launch.authorizationFile,'--committed-archive']);assert.equal(packet.launch.args.filter(arg=>arg==='--run').length,1);assert.match(packet.launch.output,/^\/tmp\/full-gate-unified76-[A-Za-z0-9_-]+$/u);assert.equal(packet.launch.physicalOutput,'/private'+packet.launch.output);assert.equal(realpathSync('/tmp'),'/private/tmp');
const absence=[];for(const path of [packet.launch.output,packet.launch.physicalOutput,packet.launch.authorizationFile]){let missing=false;try{lstatSync(path);}catch(error){assert.equal(error.code,'ENOENT');missing=true;}assert.equal(missing,true);absence.push({path,absent:true});}
const launch=blob(packetCommit,packetRoot+'LAUNCH.md').toString(),command=launch.match(/```sh\n([\s\S]*?)\n```/u)[1];assert.equal((command.match(/--run/g)||[]).length,1);assert.ok(command.includes(packet.launch.script));for(const arg of packet.launch.args)assert.ok(command.includes(arg));
const tokens=command.split(String.fromCharCode(10)).map(line=>line.trimEnd().endsWith(String.fromCharCode(92))?line.trimEnd().slice(0,-1):line).join(' ').trim().split(/\s+/u);
assert.equal(tokens[0],'GIT_PAGER=');
const nativeAssignments=tokens.slice(1,3).map(token=>{const [name,origin]=token.split('=');assert.ok(['RG_NATIVE_BIN','TREE_NATIVE_BIN'].includes(name));assert.ok(external.tools.some(tool=>tool.origin===origin));return{name,origin};});
assert.deepEqual(tokens.slice(3),[packet.launch.executable.origin,packet.launch.script,...packet.launch.args]);
assert.equal(sha(blob(packet.product.candidate,'package.json')),packet.product.packageManifestSha256);

console.log(JSON.stringify({status:'ACCEPT_READY_FOR_ROOT_AUTHORIZATION_METADATA_ONLY',packetCommit,normalizedPacketSha256:normalized(packet),rawPacketSha256:sha(blob(packetCommit,packetRoot+'PACKET.json')),source,acceptedReview:accepted,shippingFiles:shipping,independentProofFiles:packet.independent.proofFiles,driverSha256:normalized(driver),profileSha256:normalized(profile),projectionSha256:normalized(projection),toolRoutesSha256:normalized(routes),externalSha256:packet.tools.externalReceipt.sha256,readableToolRecords:external.tools.length,nativeAssetRecords:external.native.assets.length,dependencyManifests:Object.keys(external.directories).length,fixturePaths,projectionRecords:6,phaseCount:phases.length,supervisedPhaseCount:13,finalSweep:'in-worker verification/receipt,not a fourteenth child process',phases,bounds:packet.bounds,launch:packet.launch,command,nativeAssignments,pathAbsenceAtVerification:absence,template:'Deliberately invalid: pending action and blank authorization; no valid root receipt created',limitations:['One attempt/no retry is root policy; receipt is not a cryptographically consumed one-shot token','No wider permissions/overlay/old GO is root policy backed by unchanged code and source/hash guards,not an imported packet executor','25805s is configured post-preflight worker watchdog;5000ms is cleanup/IPC allowance,not kernel-hard all-drain deadline','Current live shipping files match as a separate point-in-time check; accepted identity derives from committed source/accepted seal; recheck before launch','No executable driver/product imports,tools rehash/native probes,build/pack/fullgate/private access or instruction payload materialization'],rootAuthorizationIssued:false,fullGateLaunched:false},null,2));
