import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const profile=path.resolve('tests/compatibility/bash-ere-native-reference-20260829/preflight-v2'),own=profile+'/actual-v1',directory=profile+'/materialized';
const started=Date.now(),deadline=started+600000;
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const ensure=(value,reason)=>{if(!value)throw Error(reason);};
function read(filename,pin){const descriptor=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const stat=fs.fstatSync(descriptor);ensure(stat.isFile()&&stat.nlink===1&&stat.size<=1048576,'FILE_TYPE_SIZE');if(pin?.bytes!==undefined)ensure(stat.size===pin.bytes,'SIZE');if(pin?.mode!==undefined)ensure((stat.mode&511)===pin.mode,'MODE');const bytes=fs.readFileSync(descriptor),after=fs.fstatSync(descriptor);ensure(bytes.length===stat.size&&stat.size===after.size&&stat.ino===after.ino&&stat.mtimeMs===after.mtimeMs,'FILE_RACE');if(pin?.sha256)ensure(hash(bytes)===pin.sha256,'HASH');return bytes;}finally{fs.closeSync(descriptor);}}
function write(filename,bytes){fs.writeFileSync(filename,bytes,{flag:'wx',mode:0o600});}
const gitRows=[];
function git(id,args,maximum){const output=fs.openSync(own+'/raw/'+id+'.stdout','wx+',0o600),error=fs.openSync(own+'/raw/'+id+'.stderr','wx+',0o600);let bytes,result;try{result=spawnSync('/usr/bin/git',['-c','core.fsmonitor=false','-c','core.hooksPath=/dev/null',...args],{cwd:process.cwd(),shell:false,stdio:['ignore',output,error],timeout:5000,killSignal:'SIGKILL'});fs.fsyncSync(output);fs.fsyncSync(error);const stat=fs.fstatSync(output),err=fs.fstatSync(error);ensure(stat.isFile()&&err.isFile()&&stat.size<=maximum&&err.size<=65536,'METADATA_CAPTURE');bytes=Buffer.alloc(stat.size);let offset=0;while(offset<bytes.length){const amount=fs.readSync(output,bytes,offset,bytes.length-offset,offset);ensure(amount>0,'SHORT_CAPTURE');offset+=amount;}ensure(!result.error&&result.signal===null&&result.status===0,'METADATA_STOP');}finally{fs.closeSync(output);fs.closeSync(error);}gitRows.push({id,args,pid:result.pid,status:result.status,signal:result.signal,bytes:bytes.length,sha256:hash(bytes),retired:true});return bytes;}
const reviewCommit='a1d03bcb9be30b60b784b25abe510a7e2a23c9eb',reviewPath='tests/compatibility/bash-ere-native-preflight-review-20260829/resolved-slot-v1/REPORT.md';
const sizeBytes=git('slot-size',['cat-file','-s',reviewCommit+':'+reviewPath],32),size=Number(sizeBytes.toString('ascii'));ensure(Number.isSafeInteger(size)&&size>0&&size<=65536,'SLOT_REPORT_SIZE');
const report=git('slot-report',['cat-file','blob',reviewCommit+':'+reviewPath],size);ensure(report.length===size,'SLOT_REPORT_BYTES');write(own+'/SLOT-REPORT.md.data',report);
const sealBytes=read(directory+'/PRESEAL.json',{sha256:'211483cbe1b12ad505345da5396a227c7da9931743d035ed365f7cc74bb4d457'}),seal=JSON.parse(sealBytes);for(const item of seal.files)read(directory+'/'+item.path,item);
const admission=await import('../materialized/admission.mjs');
const grantHash='9eec9e95250998fc3bf78ee8727bbfbbba6d32c7aab42155291a5cea34a753ec';
const grantBytes=read(directory+'/GO.json',{bytes:1796,mode:384,sha256:grantHash}),accepted=admission.admit(directory,directory+'/GO.json',grantHash);
ensure(accepted.grant.deadlineEpochMs===Date.parse('2026-08-29T10:46:09.884Z')&&accepted.grant.deadlineEpochMs-Date.now()>=600000,'FULL_WINDOW_OR_EXPIRY');
const tools=JSON.parse(read(directory+'/TOOLS.json',seal.files.find(item=>item.path==='TOOLS.json'))),observations=[];for(const pin of [...tools.toolPins,tools.environmentLauncher,tools.wrapperTool]){admission.pinned(pin.path,pin);observations.push({path:pin.path,bytes:pin.bytes,mode:pin.mode,sha256:pin.sha256,at:new Date().toISOString()});}
const root='/private/tmp/safe-bash-ere-native-observations-20260829-v1';admission.validateProvision(accepted.provision,root);
const cohort=JSON.parse(read(directory+'/COHORT.json',seal.files.find(item=>item.path==='COHORT.json')));admission.validateCohort(cohort,accepted.requests,root);for(const literal of cohort.cases)ensure(read(directory+'/programs/'+literal.id+'.bash.data',seal.files.find(item=>item.path==='programs/'+literal.id+'.bash.data')).equals(Buffer.from(literal.program)),'PROGRAM_BYTES');
ensure(JSON.stringify(fs.readdirSync(root).sort())===JSON.stringify(['JOURNAL.jsonl','captures','cases','outer']),'ROOT_MEMBERSHIP');for(const name of ['outer','cases','captures'])ensure(fs.readdirSync(root+'/'+name).length===0,'ALREADY_STARTED');ensure(read(root+'/JOURNAL.jsonl',{bytes:0,mode:384}).length===0,'JOURNAL_NOT_EMPTY');
const resolvedBytes=read(profile+'/activation-v1/RESOLVED-COMMAND.json',{bytes:1295,mode:384,sha256:'d2dca84a74ff36a2a7fae05986f237acd5cf3d8c35caa3e4d97ee96344d6460d'}),resolved=JSON.parse(resolvedBytes);
const templateBytes=read(profile+'/APPROVAL-PROPOSAL.template.json',{sha256:'6e092362c293a54bdd108b44a59ad245346890265f3d16d3ff18918239cf7881'}),template=JSON.parse(templateBytes);admission.resolveApproval(template,resolved,grantHash);ensure(hash(Buffer.from(resolved.cmd))==='9423c7e1d4bbbc6c77bef3962bfe97b93fe333f65263cb2f4df12f555a239e25','EXACT_COMMAND');
ensure(report.toString('utf8').includes('ACCEPT'),'SLOT_REPORT_DECISION');
for(const item of seal.files)read(directory+'/'+item.path,item);ensure(Date.now()<=deadline&&accepted.grant.deadlineEpochMs-Date.now()>=600000,'FINAL_PREFLIGHT_TIME');
const result={schema:'ere12-actual-preflight-v1',decision:'PASS',started,deadline,at:new Date().toISOString(),grantSha256:grantHash,commandStringSha256:hash(Buffer.from(resolved.cmd)),resolvedSha256:hash(resolvedBytes),presealSha256:hash(sealBytes),reviewCommit,reviewPath,reviewSha256:hash(report),gitRows,tools:observations,expiresAt:'2026-08-29T10:46:09.884Z',latestFullWindowStart:'2026-08-29T10:36:09.884Z',root,entryImported:false,nativeChildrenBeforeApproval:0,knownStartsBeforeApproval:11,plannedManagedStarts:13,plannedPublicationStarts:8,allKnownCeiling:40};
write(own+'/PREFLIGHT.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));console.log(report.toString('utf8'));
