import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const profile=path.resolve('tests/compatibility/bash-ere-native-reference-20260829/preflight-v2'),own=profile+'/actual-v1',directory=profile+'/materialized',root='/private/tmp/safe-bash-ere-native-observations-20260829-v1';
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const ensure=(value,reason)=>{if(!value)throw Error(reason);};
function read(filename,pin,maximum=1048576){const fd=fs.openSync(filename,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW);try{const stat=fs.fstatSync(fd);ensure(stat.isFile()&&stat.nlink===1&&stat.size<=maximum,'FILE_ADMISSION');if(pin?.mode!==undefined)ensure((stat.mode&511)===pin.mode,'MODE');if(pin?.bytes!==undefined)ensure(stat.size===pin.bytes,'SIZE');const bytes=fs.readFileSync(fd),after=fs.fstatSync(fd);ensure(bytes.length===stat.size&&stat.size===after.size&&stat.ino===after.ino&&stat.mtimeMs===after.mtimeMs,'READ_RACE');if(pin?.sha256)ensure(hash(bytes)===pin.sha256,'HASH');return bytes;}finally{fs.closeSync(fd);}}
const preflightBytes=read(own+'/PREFLIGHT.json'),preflight=JSON.parse(preflightBytes);const check=()=>ensure(Date.now()<=preflight.deadline,'INCLUSIVE_ACTUAL_DEADLINE');check();
const sealBytes=read(directory+'/PRESEAL.json',{sha256:'211483cbe1b12ad505345da5396a227c7da9931743d035ed365f7cc74bb4d457'}),seal=JSON.parse(sealBytes);for(const item of seal.files)read(directory+'/'+item.path,item);
read(directory+'/GO.json',{bytes:1796,mode:384,sha256:'9eec9e95250998fc3bf78ee8727bbfbbba6d32c7aab42155291a5cea34a753ec'});
const output=own+'/runtime';ensure(!fs.existsSync(output),'UNUSED_PUBLICATION');fs.mkdirSync(output,{mode:0o700});
const files=[],directories=[];let total=0;function copy(absolute,relative=''){for(const name of fs.readdirSync(absolute).sort()){check();const filename=absolute+'/'+name,rel=relative?relative+'/'+name:name,stat=fs.lstatSync(filename);ensure(!stat.isSymbolicLink()&&files.length+directories.length<4096,'RUNTIME_MEMBERSHIP');if(stat.isDirectory()){directories.push({path:rel,mode:stat.mode&511});fs.mkdirSync(output+'/'+rel,{mode:0o700});copy(filename,rel);}else{const bytes=read(filename);total+=bytes.length;ensure(total<=33554432,'COMBINED_CAPTURE_CAP');fs.writeFileSync(output+'/'+rel,bytes,{flag:'wx',mode:0o600});files.push({path:rel,bytes:bytes.length,mode:stat.mode&511,sha256:hash(bytes)});}}}copy(root);
const observations=[],qualificationErrors=[];let results=null;
if(fs.existsSync(root+'/RESULTS.json'))results=JSON.parse(read(root+'/RESULTS.json'));
if(!results)qualificationErrors.push('NO_RESULTS');
const {decodeObservation}=await import('../materialized/observation.mjs');
for(let index=1;index<=12;index++){
 const id='N'+String(index).padStart(2,'0'),filename=root+'/'+id+'.json';if(!fs.existsSync(filename)){observations.push({id,disposition:'UNRUN_OR_UNPUBLISHED'});continue;}
 const bytes=read(filename),row=JSON.parse(bytes),errors=[];
 if(row.id!==id||!row.exit||!row.close||!row.retired||row.group?.state!=='absent'||row.signal!==null||row.stop!==null||row.errors.length||!row.regularCaptureCompletion)errors.push('LIFECYCLE');
 for(const name of ['stdout','stderr']){const capture=row.capture.find(item=>item.name===name);if(!capture){errors.push('MISSING_CAPTURE_'+name);continue;}const actual=read(root+'/captures/'+id+'/'+name,undefined,65536);if(!capture.flush||!capture.size||!capture.hash||!capture.close||capture.bytes!==actual.length||capture.sha256!==hash(actual)||capture.base64!==actual.toString('base64'))errors.push('CAPTURE_'+name);}
 if(JSON.stringify(row.filesBefore)!==JSON.stringify(row.filesAfter)||!row.filesVerified)errors.push('EFFECTS');
 let decoded=null;try{decoded=decodeObservation(row);}catch(error){errors.push('OBSERVATION_PROTOCOL:'+String(error.message));}
 const summary={id,status:row.status,signal:row.signal,stop:row.stop,exit:row.exit,close:row.close,retired:row.retired,group:row.group,started:row.started,finished:row.finished,receiptFileSha256:hash(bytes),sourceReceiptPublishedField:row.receiptPublished,sourceReceiptOrder:'case JSON is written before receiptPublished=true and owner credit',stdout:row.capture.find(item=>item.name==='stdout'),stderr:row.capture.find(item=>item.name==='stderr'),observation:decoded,visibleAsciiValues:decoded?.slots.map(slot=>({index:slot.index,shellSlotPresent:slot.shellSlotPresent,value:Buffer.from(slot.base64,'base64').toString('ascii')})),qualification:errors.length?'UNQUALIFIED':'CAPTURE_AND_LIFECYCLE_VERIFIED',errors};
 observations.push(summary);if(errors.length)qualificationErrors.push({id,errors});
}
if(results){if(results.completed!==12||results.halted||results.rows.length!==12||results.ledger.active!==1||results.ledger.activeConfirmed!==1)qualificationErrors.push('OWNER_COMPLETION_OR_LEDGER');for(const capture of results.outer??[]){const actual=read(root+'/outer/bootstrap.'+capture.name,undefined,65536);if(!capture.flush||!capture.size||!capture.hash||!capture.close||hash(actual)!==capture.sha256||actual.toString('base64')!==capture.base64)qualificationErrors.push('OUTER_CAPTURE');}}
const journalBytes=read(root+'/JOURNAL.jsonl'),journalLines=journalBytes.toString('utf8').split('\n').filter(line=>line.length),journal=journalLines.map(line=>JSON.parse(line));const credits=journal.filter(item=>item.event==='OBSERVATION_READY_FOR_CREDIT').map(item=>item.id);if(JSON.stringify(credits)!==JSON.stringify(Array.from({length:12},(_,index)=>'N'+String(index+1).padStart(2,'0'))))qualificationErrors.push('OWNER_CREDIT_SEQUENCE');
for(const item of files)read(root+'/'+item.path,item);for(const item of seal.files)read(directory+'/'+item.path,item);check();
const report={schema:'ere12-native-observation-manifest-v1',at:new Date().toISOString(),preflightSha256:hash(preflightBytes),root,sourceCommit:'2d07f5921010fda988dcda36ac81a89831fbac55',activationCommit:'016aa3a940c19dc17fd94bce0ed7468676e1d5c5',slotReviewCommit:'a1d03bcb9be30b60b784b25abe510a7e2a23c9eb',presealSha256:hash(sealBytes),grantSha256:preflight.grantSha256,commandStringSha256:preflight.commandStringSha256,reference:'executed pinned /bin/bash corresponding to previously captured local 3.2.57 metadata; no new version probe',nativeSpans:'UNOBSERVABLE',normativePosixClaim:false,gnu53Claim:false,observationsNotPasses:true,observations,results,credits,files,directories,runtimeBytes:total,qualificationErrors,allObservationsQualified:qualificationErrors.length===0,sourceIntegrityAfter:true,actualDeadline:preflight.deadline};
fs.writeFileSync(own+'/OBSERVATIONS.json',JSON.stringify(report,null,2)+'\n',{flag:'wx',mode:0o600});
const table=observations.map(row=>`| ${row.id} | ${row.status??'UNRUN'} | ${row.observation?.cardinality??'unknown'} | ${row.visibleAsciiValues?JSON.stringify(row.visibleAsciiValues.filter(slot=>slot.shellSlotPresent).map(slot=>slot.value)):'unpublished'} | ${row.qualification??row.disposition} |`).join('\n');
const text=`# Actual ERE capture observations\n\nTwelve observations, not semantic passes. Independent artifact audit and R01 adjudication pending.\n\n| ID | Status | Cardinality | Present shell-slot values (JSON) | Artifact qualification |\n|---|---:|---:|---|---|\n${table}\n\nQualified manifest: ${qualificationErrors.length===0}. Original binary streams, NUL framing, stderr, per-case rows and journal are copied byte-exact under runtime/. No native spans or hidden nonparticipation inferred. The saved case JSON precedes receiptPublished=true; final owner RESULTS and the exact twelve journal credit events establish subsequent owner credit.\n\nReference is this pinned local Bash/platform corresponding to prior 3.2.57 version metadata, not GNU5.3 or all libc implementations. No product/engine/comparator/Worker execution or native version probe. Raw nonzero regex statuses are observations. Historical R01 conflicts are not rescored here.\n\nAll copied files and selected source members were checked after publication reads. Runtime bytes: ${total}. Overall actual preflight-to-artifact deadline: ${new Date(preflight.deadline).toISOString()}; published ${new Date().toISOString()}. See OBSERVATIONS.json for exact status, bytes, hashes, lifecycle and remaining qualifications.\n`;
fs.writeFileSync(own+'/OBSERVATIONS.md',text,{flag:'wx',mode:0o600});check();console.log(JSON.stringify({qualified:report.allObservationsQualified,qualificationErrors,runtimeBytes:total,completed:results?.completed,ledger:results?.ledger,observations:observations.map(row=>({id:row.id,status:row.status,cardinality:row.observation?.cardinality,values:row.visibleAsciiValues?.filter(slot=>slot.shellSlotPresent).map(slot=>slot.value)})),manifestSha256:hash(read(own+'/OBSERVATIONS.json')),at:report.at,deadline:preflight.deadline}));process.exitCode=qualificationErrors.length?1:0;
