import * as actual0 from "toolcraft-design-rust/components/color";
import type * as expected0 from "toolcraft-design/components/color";
const reference0:typeof expected0=actual0;
const native0:typeof actual0=null as unknown as typeof expected0;
void [reference0,native0];
const reference0Color:expected0.Color=null as unknown as actual0.Color;
const native0Color:actual0.Color=null as unknown as expected0.Color;
void [reference0Color,native0Color];
import * as actual1 from "toolcraft-design-rust/components/text";
import type * as expected1 from "toolcraft-design/components/text";
const reference1:typeof expected1=actual1;
const native1:typeof actual1=null as unknown as typeof expected1;
void [reference1,native1];
import * as actual2 from "toolcraft-design-rust/components/logger";
import type * as expected2 from "toolcraft-design/components/logger";
const reference2:typeof expected2=actual2;
const native2:typeof actual2=null as unknown as typeof expected2;
void [reference2,native2];
const reference2LoggerOutput:expected2.LoggerOutput=null as unknown as actual2.LoggerOutput;
const native2LoggerOutput:actual2.LoggerOutput=null as unknown as expected2.LoggerOutput;
void [reference2LoggerOutput,native2LoggerOutput];
import * as actual3 from "toolcraft-design-rust/components/index";
import type * as expected3 from "toolcraft-design/components/index";
const reference3:typeof expected3=actual3;
const native3:typeof actual3=null as unknown as typeof expected3;
void [reference3,native3];
const reference3Color:expected3.Color=null as unknown as actual3.Color;
const native3Color:actual3.Color=null as unknown as expected3.Color;
void [reference3Color,native3Color];
const reference3LoggerOutput:expected3.LoggerOutput=null as unknown as actual3.LoggerOutput;
const native3LoggerOutput:actual3.LoggerOutput=null as unknown as expected3.LoggerOutput;
void [reference3LoggerOutput,native3LoggerOutput];
const reference3CommandInfo:expected3.CommandInfo=null as unknown as actual3.CommandInfo;
const native3CommandInfo:actual3.CommandInfo=null as unknown as expected3.CommandInfo;
void [reference3CommandInfo,native3CommandInfo];
const reference3OptionInfo:expected3.OptionInfo=null as unknown as actual3.OptionInfo;
const native3OptionInfo:actual3.OptionInfo=null as unknown as expected3.OptionInfo;
void [reference3OptionInfo,native3OptionInfo];
const reference3FormatColumnsOptions:expected3.FormatColumnsOptions=null as unknown as actual3.FormatColumnsOptions;
const native3FormatColumnsOptions:actual3.FormatColumnsOptions=null as unknown as expected3.FormatColumnsOptions;
void [reference3FormatColumnsOptions,native3FormatColumnsOptions];
const reference3HelpToken:expected3.HelpToken=null as unknown as actual3.HelpToken;
const native3HelpToken:actual3.HelpToken=null as unknown as expected3.HelpToken;
void [reference3HelpToken,native3HelpToken];
const reference3HelpTokenRole:expected3.HelpTokenRole=null as unknown as actual3.HelpTokenRole;
const native3HelpTokenRole:actual3.HelpTokenRole=null as unknown as expected3.HelpTokenRole;
void [reference3HelpTokenRole,native3HelpTokenRole];
const reference3TableColumn:expected3.TableColumn=null as unknown as actual3.TableColumn;
const native3TableColumn:actual3.TableColumn=null as unknown as expected3.TableColumn;
void [reference3TableColumn,native3TableColumn];
const reference3RenderTableOptions:expected3.RenderTableOptions=null as unknown as actual3.RenderTableOptions;
const native3RenderTableOptions:actual3.RenderTableOptions=null as unknown as expected3.RenderTableOptions;
void [reference3RenderTableOptions,native3RenderTableOptions];
const reference3FileChange:expected3.FileChange=null as unknown as actual3.FileChange;
const native3FileChange:actual3.FileChange=null as unknown as expected3.FileChange;
void [reference3FileChange,native3FileChange];
const reference3FileChangeDisplayMode:expected3.FileChangeDisplayMode=null as unknown as actual3.FileChangeDisplayMode;
const native3FileChangeDisplayMode:actual3.FileChangeDisplayMode=null as unknown as expected3.FileChangeDisplayMode;
void [reference3FileChangeDisplayMode,native3FileChangeDisplayMode];
const reference3FileChangeKind:expected3.FileChangeKind=null as unknown as actual3.FileChangeKind;
const native3FileChangeKind:actual3.FileChangeKind=null as unknown as expected3.FileChangeKind;
void [reference3FileChangeKind,native3FileChangeKind];
const reference3FileChangeOutputFormat:expected3.FileChangeOutputFormat=null as unknown as actual3.FileChangeOutputFormat;
const native3FileChangeOutputFormat:actual3.FileChangeOutputFormat=null as unknown as expected3.FileChangeOutputFormat;
void [reference3FileChangeOutputFormat,native3FileChangeOutputFormat];
const reference3RenderFileChangesOptions:expected3.RenderFileChangesOptions=null as unknown as actual3.RenderFileChangesOptions;
const native3RenderFileChangesOptions:actual3.RenderFileChangesOptions=null as unknown as expected3.RenderFileChangesOptions;
void [reference3RenderFileChangesOptions,native3RenderFileChangesOptions];
const reference3CatalogGroup:expected3.CatalogGroup=null as unknown as actual3.CatalogGroup;
const native3CatalogGroup:actual3.CatalogGroup=null as unknown as expected3.CatalogGroup;
void [reference3CatalogGroup,native3CatalogGroup];
const reference3CatalogItem:expected3.CatalogItem=null as unknown as actual3.CatalogItem;
const native3CatalogItem:actual3.CatalogItem=null as unknown as expected3.CatalogItem;
void [reference3CatalogItem,native3CatalogItem];
const reference3CatalogMetric:expected3.CatalogMetric=null as unknown as actual3.CatalogMetric;
const native3CatalogMetric:actual3.CatalogMetric=null as unknown as expected3.CatalogMetric;
void [reference3CatalogMetric,native3CatalogMetric];
const reference3CatalogTone:expected3.CatalogTone=null as unknown as actual3.CatalogTone;
const native3CatalogTone:actual3.CatalogTone=null as unknown as expected3.CatalogTone;
void [reference3CatalogTone,native3CatalogTone];
const reference3RenderCatalogOptions:expected3.RenderCatalogOptions=null as unknown as actual3.RenderCatalogOptions;
const native3RenderCatalogOptions:actual3.RenderCatalogOptions=null as unknown as expected3.RenderCatalogOptions;
void [reference3RenderCatalogOptions,native3RenderCatalogOptions];
const reference3RenderTemplateOptions:expected3.RenderTemplateOptions=null as unknown as actual3.RenderTemplateOptions;
const native3RenderTemplateOptions:actual3.RenderTemplateOptions=null as unknown as expected3.RenderTemplateOptions;
void [reference3RenderTemplateOptions,native3RenderTemplateOptions];
const reference3TemplateEscape:expected3.TemplateEscape=null as unknown as actual3.TemplateEscape;
const native3TemplateEscape:actual3.TemplateEscape=null as unknown as expected3.TemplateEscape;
void [reference3TemplateEscape,native3TemplateEscape];
import * as actual4 from "toolcraft-design-rust/dashboard/line-buffer";
import type * as expected4 from "toolcraft-design/dashboard/line-buffer";
const reference4:typeof expected4=actual4;
const native4:typeof actual4=null as unknown as typeof expected4;
void [reference4,native4];
import * as actual5 from "toolcraft-design-rust/dashboard/output-preview";
import type * as expected5 from "toolcraft-design/dashboard/output-preview";
const reference5:typeof expected5=actual5;
const native5:typeof actual5=null as unknown as typeof expected5;
void [reference5,native5];
import * as actual6 from "toolcraft-design-rust/explorer/events";
import type * as expected6 from "toolcraft-design/explorer/events";
const reference6:typeof expected6=actual6;
const native6:typeof actual6=null as unknown as typeof expected6;
void [reference6,native6];
const reference6Effect:expected6.Effect=null as unknown as actual6.Effect;
const native6Effect:actual6.Effect=null as unknown as expected6.Effect;
void [reference6Effect,native6Effect];
const reference6ExplorerEvent:expected6.ExplorerEvent=null as unknown as actual6.ExplorerEvent;
const native6ExplorerEvent:actual6.ExplorerEvent=null as unknown as expected6.ExplorerEvent;
void [reference6ExplorerEvent,native6ExplorerEvent];
const reference6ConfirmModal:expected6.ConfirmModal=null as unknown as actual6.ConfirmModal;
const native6ConfirmModal:actual6.ConfirmModal=null as unknown as expected6.ConfirmModal;
void [reference6ConfirmModal,native6ConfirmModal];
import * as actual7 from "toolcraft-design-rust/internal/color-support";
import type * as expected7 from "toolcraft-design/internal/color-support";
const reference7:typeof expected7=actual7;
const native7:typeof actual7=null as unknown as typeof expected7;
void [reference7,native7];
const reference7ColorSupportEnv:expected7.ColorSupportEnv=null as unknown as actual7.ColorSupportEnv;
const native7ColorSupportEnv:actual7.ColorSupportEnv=null as unknown as expected7.ColorSupportEnv;
void [reference7ColorSupportEnv,native7ColorSupportEnv];
const reference7ColorSupportStream:expected7.ColorSupportStream=null as unknown as actual7.ColorSupportStream;
const native7ColorSupportStream:actual7.ColorSupportStream=null as unknown as expected7.ColorSupportStream;
void [reference7ColorSupportStream,native7ColorSupportStream];
import * as actual8 from "toolcraft-design-rust/internal/output-format";
import type * as expected8 from "toolcraft-design/internal/output-format";
const reference8:typeof expected8=actual8;
const native8:typeof actual8=null as unknown as typeof expected8;
void [reference8,native8];
const reference8OutputFormat:expected8.OutputFormat=null as unknown as actual8.OutputFormat;
const native8OutputFormat:actual8.OutputFormat=null as unknown as expected8.OutputFormat;
void [reference8OutputFormat,native8OutputFormat];
import * as actual9 from "toolcraft-design-rust/internal/strip-ansi";
import type * as expected9 from "toolcraft-design/internal/strip-ansi";
const reference9:typeof expected9=actual9;
const native9:typeof actual9=null as unknown as typeof expected9;
void [reference9,native9];
import * as actual10 from "toolcraft-design-rust/internal/theme-detect";
import type * as expected10 from "toolcraft-design/internal/theme-detect";
const reference10:typeof expected10=actual10;
const native10:typeof actual10=null as unknown as typeof expected10;
void [reference10,native10];
const reference10ThemeEnv:expected10.ThemeEnv=null as unknown as actual10.ThemeEnv;
const native10ThemeEnv:actual10.ThemeEnv=null as unknown as expected10.ThemeEnv;
void [reference10ThemeEnv,native10ThemeEnv];
import * as actual11 from "toolcraft-design-rust/internal/theme-state";
import type * as expected11 from "toolcraft-design/internal/theme-state";
const reference11:typeof expected11=actual11;
const native11:typeof actual11=null as unknown as typeof expected11;
void [reference11,native11];
const reference11ThemeConfig:expected11.ThemeConfig=null as unknown as actual11.ThemeConfig;
const native11ThemeConfig:actual11.ThemeConfig=null as unknown as expected11.ThemeConfig;
void [reference11ThemeConfig,native11ThemeConfig];
import * as actual12 from "toolcraft-design-rust/prompts/interactive/index";
import type * as expected12 from "toolcraft-design/prompts/interactive/index";
// @ts-expect-error Separate unique cancellation symbols remain a swap gate.
const reference12:typeof expected12=actual12;
// @ts-expect-error Separate unique cancellation symbols remain a swap gate.
const native12:typeof actual12=null as unknown as typeof expected12;
void [reference12,native12];
const reference12TextOptions:expected12.TextOptions=null as unknown as actual12.TextOptions;
const native12TextOptions:actual12.TextOptions=null as unknown as expected12.TextOptions;
void [reference12TextOptions,native12TextOptions];
const reference12PasswordOptions:expected12.PasswordOptions=null as unknown as actual12.PasswordOptions;
const native12PasswordOptions:actual12.PasswordOptions=null as unknown as expected12.PasswordOptions;
void [reference12PasswordOptions,native12PasswordOptions];
const reference12ConfirmOptions:expected12.ConfirmOptions=null as unknown as actual12.ConfirmOptions;
const native12ConfirmOptions:actual12.ConfirmOptions=null as unknown as expected12.ConfirmOptions;
void [reference12ConfirmOptions,native12ConfirmOptions];
const reference12SelectOption:expected12.SelectOption<unknown>=null as unknown as actual12.SelectOption<unknown>;
const native12SelectOption:actual12.SelectOption<unknown>=null as unknown as expected12.SelectOption<unknown>;
void [reference12SelectOption,native12SelectOption];
const reference12SelectOptions:expected12.SelectOptions<unknown>=null as unknown as actual12.SelectOptions<unknown>;
const native12SelectOptions:actual12.SelectOptions<unknown>=null as unknown as expected12.SelectOptions<unknown>;
void [reference12SelectOptions,native12SelectOptions];
const reference12MultiselectOptions:expected12.MultiselectOptions<unknown>=null as unknown as actual12.MultiselectOptions<unknown>;
const native12MultiselectOptions:actual12.MultiselectOptions<unknown>=null as unknown as expected12.MultiselectOptions<unknown>;
void [reference12MultiselectOptions,native12MultiselectOptions];
