// Verify every flat re-export module against the original public declarations.
import * as original0 from "toolcraft-design/brand";
import * as native0 from "toolcraft-design-rust/brand";
const original0Check: typeof original0 = native0;
const native0Check: typeof native0 = original0;
void [original0Check, native0Check];
const original0Brand: original0.Brand = null as unknown as native0.Brand;
const native0Brand: native0.Brand = null as unknown as original0.Brand;
void [original0Brand, native0Brand];
import * as original1 from "toolcraft-design/brands";
import * as native1 from "toolcraft-design-rust/brands";
const original1Check: typeof original1 = native1;
const native1Check: typeof native1 = original1;
void [original1Check, native1Check];
const original1Brand: original1.Brand = null as unknown as native1.Brand;
const native1Brand: native1.Brand = null as unknown as original1.Brand;
void [original1Brand, native1Brand];
import * as original2 from "toolcraft-design/cancel";
import * as native2 from "toolcraft-design-rust/cancel";
const original2Check: typeof original2 = native2;
const native2Check: typeof native2 = original2;
void [original2Check, native2Check];
import * as original3 from "toolcraft-design/color";
import * as native3 from "toolcraft-design-rust/color";
const original3Check: typeof original3 = native3;
const native3Check: typeof native3 = original3;
void [original3Check, native3Check];
const original3Color: original3.Color = null as unknown as native3.Color;
const native3Color: native3.Color = null as unknown as original3.Color;
void [original3Color, native3Color];
import * as original4 from "toolcraft-design/configure-theme";
import * as native4 from "toolcraft-design-rust/configure-theme";
const original4Check: typeof original4 = native4;
const native4Check: typeof native4 = original4;
void [original4Check, native4Check];
import * as original5 from "toolcraft-design/confirm-or-cancel";
import * as native5 from "toolcraft-design-rust/confirm-or-cancel";
const original5Check: typeof original5 = native5;
const native5Check: typeof native5 = original5;
void [original5Check, native5Check];
const original5ConfirmOptions: original5.ConfirmOptions = null as unknown as native5.ConfirmOptions;
const native5ConfirmOptions: native5.ConfirmOptions = null as unknown as original5.ConfirmOptions;
void [original5ConfirmOptions, native5ConfirmOptions];
import * as original6 from "toolcraft-design/confirm";
import * as native6 from "toolcraft-design-rust/confirm";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original6Check: typeof original6 = native6;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native6Check: typeof native6 = original6;
void [original6Check, native6Check];
const original6ConfirmOptions: original6.ConfirmOptions = null as unknown as native6.ConfirmOptions;
const native6ConfirmOptions: native6.ConfirmOptions = null as unknown as original6.ConfirmOptions;
void [original6ConfirmOptions, native6ConfirmOptions];
import * as original7 from "toolcraft-design/create-dashboard";
import * as native7 from "toolcraft-design-rust/create-dashboard";
const original7Check: typeof original7 = native7;
const native7Check: typeof native7 = original7;
void [original7Check, native7Check];
const original7Dashboard: original7.Dashboard = null as unknown as native7.Dashboard;
const native7Dashboard: native7.Dashboard = null as unknown as original7.Dashboard;
void [original7Dashboard, native7Dashboard];
const original7DashboardOptions: original7.DashboardOptions = null as unknown as native7.DashboardOptions;
const native7DashboardOptions: native7.DashboardOptions = null as unknown as original7.DashboardOptions;
void [original7DashboardOptions, native7DashboardOptions];
import * as original8 from "toolcraft-design/create-logger";
import * as native8 from "toolcraft-design-rust/create-logger";
const original8Check: typeof original8 = native8;
const native8Check: typeof native8 = original8;
void [original8Check, native8Check];
const original8LoggerOutput: original8.LoggerOutput = null as unknown as native8.LoggerOutput;
const native8LoggerOutput: native8.LoggerOutput = null as unknown as original8.LoggerOutput;
void [original8LoggerOutput, native8LoggerOutput];
import * as original9 from "toolcraft-design/dark";
import * as native9 from "toolcraft-design-rust/dark";
const original9Check: typeof original9 = native9;
const native9Check: typeof native9 = original9;
void [original9Check, native9Check];
const original9ThemePalette: original9.ThemePalette = null as unknown as native9.ThemePalette;
const native9ThemePalette: native9.ThemePalette = null as unknown as original9.ThemePalette;
void [original9ThemePalette, native9ThemePalette];
import * as original10 from "toolcraft-design/escape-terminal-text";
import * as native10 from "toolcraft-design-rust/escape-terminal-text";
const original10Check: typeof original10 = native10;
const native10Check: typeof native10 = original10;
void [original10Check, native10Check];
import * as original11 from "toolcraft-design/format-columns";
import * as native11 from "toolcraft-design-rust/format-columns";
const original11Check: typeof original11 = native11;
const native11Check: typeof native11 = original11;
void [original11Check, native11Check];
const original11FormatColumnsOptions: original11.FormatColumnsOptions = null as unknown as native11.FormatColumnsOptions;
const native11FormatColumnsOptions: native11.FormatColumnsOptions = null as unknown as original11.FormatColumnsOptions;
void [original11FormatColumnsOptions, native11FormatColumnsOptions];
import * as original12 from "toolcraft-design/format-command-list";
import * as native12 from "toolcraft-design-rust/format-command-list";
const original12Check: typeof original12 = native12;
const native12Check: typeof native12 = original12;
void [original12Check, native12Check];
const original12CommandInfo: original12.CommandInfo = null as unknown as native12.CommandInfo;
const native12CommandInfo: native12.CommandInfo = null as unknown as original12.CommandInfo;
void [original12CommandInfo, native12CommandInfo];
import * as original13 from "toolcraft-design/format-command-not-found-panel";
import * as native13 from "toolcraft-design-rust/format-command-not-found-panel";
const original13Check: typeof original13 = native13;
const native13Check: typeof native13 = original13;
void [original13Check, native13Check];
import * as original14 from "toolcraft-design/format-command-not-found";
import * as native14 from "toolcraft-design-rust/format-command-not-found";
const original14Check: typeof original14 = native14;
const native14Check: typeof native14 = original14;
void [original14Check, native14Check];
import * as original15 from "toolcraft-design/format-command";
import * as native15 from "toolcraft-design-rust/format-command";
const original15Check: typeof original15 = native15;
const native15Check: typeof native15 = original15;
void [original15Check, native15Check];
import * as original16 from "toolcraft-design/format-option-list";
import * as native16 from "toolcraft-design-rust/format-option-list";
const original16Check: typeof original16 = native16;
const native16Check: typeof native16 = original16;
void [original16Check, native16Check];
const original16OptionInfo: original16.OptionInfo = null as unknown as native16.OptionInfo;
const native16OptionInfo: native16.OptionInfo = null as unknown as original16.OptionInfo;
void [original16OptionInfo, native16OptionInfo];
import * as original17 from "toolcraft-design/format-option";
import * as native17 from "toolcraft-design-rust/format-option";
const original17Check: typeof original17 = native17;
const native17Check: typeof native17 = original17;
void [original17Check, native17Check];
import * as original18 from "toolcraft-design/format-usage";
import * as native18 from "toolcraft-design-rust/format-usage";
const original18Check: typeof original18 = native18;
const native18Check: typeof native18 = original18;
void [original18Check, native18Check];
import * as original19 from "toolcraft-design/get-template-partial-names";
import * as native19 from "toolcraft-design-rust/get-template-partial-names";
const original19Check: typeof original19 = native19;
const native19Check: typeof native19 = original19;
void [original19Check, native19Check];
import * as original20 from "toolcraft-design/get-theme-config";
import * as native20 from "toolcraft-design-rust/get-theme-config";
const original20Check: typeof original20 = native20;
const native20Check: typeof native20 = original20;
void [original20Check, native20Check];
import * as original21 from "toolcraft-design/get-theme";
import * as native21 from "toolcraft-design-rust/get-theme";
const original21Check: typeof original21 = native21;
const native21Check: typeof native21 = original21;
void [original21Check, native21Check];
const original21ThemeEnv: original21.ThemeEnv = null as unknown as native21.ThemeEnv;
const native21ThemeEnv: native21.ThemeEnv = null as unknown as original21.ThemeEnv;
void [original21ThemeEnv, native21ThemeEnv];
import * as original22 from "toolcraft-design/help-formatter-plain";
import * as native22 from "toolcraft-design-rust/help-formatter-plain";
const original22Check: typeof original22 = native22;
const native22Check: typeof native22 = original22;
void [original22Check, native22Check];
import * as original23 from "toolcraft-design/help-formatter";
import * as native23 from "toolcraft-design-rust/help-formatter";
const original23Check: typeof original23 = native23;
const native23Check: typeof native23 = original23;
void [original23Check, native23Check];
const original23CommandInfo: original23.CommandInfo = null as unknown as native23.CommandInfo;
const native23CommandInfo: native23.CommandInfo = null as unknown as original23.CommandInfo;
void [original23CommandInfo, native23CommandInfo];
const original23FormatColumnsOptions: original23.FormatColumnsOptions = null as unknown as native23.FormatColumnsOptions;
const native23FormatColumnsOptions: native23.FormatColumnsOptions = null as unknown as original23.FormatColumnsOptions;
void [original23FormatColumnsOptions, native23FormatColumnsOptions];
const original23OptionInfo: original23.OptionInfo = null as unknown as native23.OptionInfo;
const native23OptionInfo: native23.OptionInfo = null as unknown as original23.OptionInfo;
void [original23OptionInfo, native23OptionInfo];
const original23HelpToken: original23.HelpToken = null as unknown as native23.HelpToken;
const native23HelpToken: native23.HelpToken = null as unknown as original23.HelpToken;
void [original23HelpToken, native23HelpToken];
const original23HelpTokenRole: original23.HelpTokenRole = null as unknown as native23.HelpTokenRole;
const native23HelpTokenRole: native23.HelpTokenRole = null as unknown as original23.HelpTokenRole;
void [original23HelpTokenRole, native23HelpTokenRole];
import * as original24 from "toolcraft-design/intro-plain";
import * as native24 from "toolcraft-design-rust/intro-plain";
const original24Check: typeof original24 = native24;
const native24Check: typeof native24 = original24;
void [original24Check, native24Check];
import * as original25 from "toolcraft-design/intro";
import * as native25 from "toolcraft-design-rust/intro";
const original25Check: typeof original25 = native25;
const native25Check: typeof native25 = original25;
void [original25Check, native25Check];
import * as original26 from "toolcraft-design/is-cancel";
import * as native26 from "toolcraft-design-rust/is-cancel";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original26Check: typeof original26 = native26;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native26Check: typeof native26 = original26;
void [original26Check, native26Check];
import * as original27 from "toolcraft-design/light";
import * as native27 from "toolcraft-design-rust/light";
const original27Check: typeof original27 = native27;
const native27Check: typeof native27 = original27;
void [original27Check, native27Check];
const original27ThemePalette: original27.ThemePalette = null as unknown as native27.ThemePalette;
const native27ThemePalette: native27.ThemePalette = null as unknown as original27.ThemePalette;
void [original27ThemePalette, native27ThemePalette];
import * as original28 from "toolcraft-design/log";
import * as native28 from "toolcraft-design-rust/log";
const original28Check: typeof original28 = native28;
const native28Check: typeof native28 = original28;
void [original28Check, native28Check];
import * as original29 from "toolcraft-design/logger";
import * as native29 from "toolcraft-design-rust/logger";
const original29Check: typeof original29 = native29;
const native29Check: typeof native29 = original29;
void [original29Check, native29Check];
const original29LoggerOutput: original29.LoggerOutput = null as unknown as native29.LoggerOutput;
const native29LoggerOutput: native29.LoggerOutput = null as unknown as original29.LoggerOutput;
void [original29LoggerOutput, native29LoggerOutput];
import * as original30 from "toolcraft-design/multiselect";
import * as native30 from "toolcraft-design-rust/multiselect";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original30Check: typeof original30 = native30;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native30Check: typeof native30 = original30;
void [original30Check, native30Check];
const original30MultiselectOptions: original30.MultiselectOptions<unknown> = null as unknown as native30.MultiselectOptions<unknown>;
const native30MultiselectOptions: native30.MultiselectOptions<unknown> = null as unknown as original30.MultiselectOptions<unknown>;
void [original30MultiselectOptions, native30MultiselectOptions];
import * as original31 from "toolcraft-design/note";
import * as native31 from "toolcraft-design-rust/note";
const original31Check: typeof original31 = native31;
const native31Check: typeof native31 = original31;
void [original31Check, native31Check];
import * as original32 from "toolcraft-design/open-external";
import * as native32 from "toolcraft-design-rust/open-external";
const original32Check: typeof original32 = native32;
const native32Check: typeof native32 = original32;
void [original32Check, native32Check];
import * as original33 from "toolcraft-design/outro";
import * as native33 from "toolcraft-design-rust/outro";
const original33Check: typeof original33 = native33;
const native33Check: typeof native33 = original33;
void [original33Check, native33Check];
import * as original34 from "toolcraft-design/parse";
import * as native34 from "toolcraft-design-rust/parse";
const original34Check: typeof original34 = native34;
const native34Check: typeof native34 = original34;
void [original34Check, native34Check];
const original34MdNode: original34.MdNode = null as unknown as native34.MdNode;
const native34MdNode: native34.MdNode = null as unknown as original34.MdNode;
void [original34MdNode, native34MdNode];
import * as original35 from "toolcraft-design/password";
import * as native35 from "toolcraft-design-rust/password";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original35Check: typeof original35 = native35;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native35Check: typeof native35 = original35;
void [original35Check, native35Check];
const original35PasswordOptions: original35.PasswordOptions = null as unknown as native35.PasswordOptions;
const native35PasswordOptions: native35.PasswordOptions = null as unknown as original35.PasswordOptions;
void [original35PasswordOptions, native35PasswordOptions];
import * as original36 from "toolcraft-design/primitives";
import * as native36 from "toolcraft-design-rust/primitives";
const original36Check: typeof original36 = native36;
const native36Check: typeof native36 = original36;
void [original36Check, native36Check];
const original36DesignCommand: original36.DesignCommand = null as unknown as native36.DesignCommand;
const native36DesignCommand: native36.DesignCommand = null as unknown as original36.DesignCommand;
void [original36DesignCommand, native36DesignCommand];
const original36GroupEvent: original36.GroupEvent = null as unknown as native36.GroupEvent;
const native36GroupEvent: native36.GroupEvent = null as unknown as original36.GroupEvent;
void [original36GroupEvent, native36GroupEvent];
const original36EventGroupRow: original36.EventGroupRow = null as unknown as native36.EventGroupRow;
const native36EventGroupRow: native36.EventGroupRow = null as unknown as original36.EventGroupRow;
void [original36EventGroupRow, native36EventGroupRow];
const original36TaskNode: original36.TaskNode = null as unknown as native36.TaskNode;
const native36TaskNode: native36.TaskNode = null as unknown as original36.TaskNode;
void [original36TaskNode, native36TaskNode];
const original36ProgressItem: original36.ProgressItem = null as unknown as native36.ProgressItem;
const native36ProgressItem: native36.ProgressItem = null as unknown as original36.ProgressItem;
void [original36ProgressItem, native36ProgressItem];
const original36InlineNotice: original36.InlineNotice = null as unknown as native36.InlineNotice;
const native36InlineNotice: native36.InlineNotice = null as unknown as original36.InlineNotice;
void [original36InlineNotice, native36InlineNotice];
import * as original37 from "toolcraft-design/prompt-cancelled-error";
import * as native37 from "toolcraft-design-rust/prompt-cancelled-error";
const original37Check: typeof original37 = native37;
const native37Check: typeof native37 = original37;
void [original37Check, native37Check];
import * as original38 from "toolcraft-design/prompt-text";
import * as native38 from "toolcraft-design-rust/prompt-text";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original38Check: typeof original38 = native38;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native38Check: typeof native38 = original38;
void [original38Check, native38Check];
const original38TextOptions: original38.TextOptions = null as unknown as native38.TextOptions;
const native38TextOptions: native38.TextOptions = null as unknown as original38.TextOptions;
void [original38TextOptions, native38TextOptions];
import * as original39 from "toolcraft-design/prompt-theme";
import * as native39 from "toolcraft-design-rust/prompt-theme";
const original39Check: typeof original39 = native39;
const native39Check: typeof native39 = original39;
void [original39Check, native39Check];
import * as original40 from "toolcraft-design/render-catalog";
import * as native40 from "toolcraft-design-rust/render-catalog";
const original40Check: typeof original40 = native40;
const native40Check: typeof native40 = original40;
void [original40Check, native40Check];
const original40CatalogGroup: original40.CatalogGroup = null as unknown as native40.CatalogGroup;
const native40CatalogGroup: native40.CatalogGroup = null as unknown as original40.CatalogGroup;
void [original40CatalogGroup, native40CatalogGroup];
const original40CatalogItem: original40.CatalogItem = null as unknown as native40.CatalogItem;
const native40CatalogItem: native40.CatalogItem = null as unknown as original40.CatalogItem;
void [original40CatalogItem, native40CatalogItem];
const original40CatalogMetric: original40.CatalogMetric = null as unknown as native40.CatalogMetric;
const native40CatalogMetric: native40.CatalogMetric = null as unknown as original40.CatalogMetric;
void [original40CatalogMetric, native40CatalogMetric];
const original40CatalogTone: original40.CatalogTone = null as unknown as native40.CatalogTone;
const native40CatalogTone: native40.CatalogTone = null as unknown as original40.CatalogTone;
void [original40CatalogTone, native40CatalogTone];
const original40RenderCatalogOptions: original40.RenderCatalogOptions = null as unknown as native40.RenderCatalogOptions;
const native40RenderCatalogOptions: native40.RenderCatalogOptions = null as unknown as original40.RenderCatalogOptions;
void [original40RenderCatalogOptions, native40RenderCatalogOptions];
import * as original41 from "toolcraft-design/render-detail-card";
import * as native41 from "toolcraft-design-rust/render-detail-card";
const original41Check: typeof original41 = native41;
const native41Check: typeof native41 = original41;
void [original41Check, native41Check];
const original41DetailCardRow: original41.DetailCardRow = null as unknown as native41.DetailCardRow;
const native41DetailCardRow: native41.DetailCardRow = null as unknown as original41.DetailCardRow;
void [original41DetailCardRow, native41DetailCardRow];
const original41DetailCardSection: original41.DetailCardSection = null as unknown as native41.DetailCardSection;
const native41DetailCardSection: native41.DetailCardSection = null as unknown as original41.DetailCardSection;
void [original41DetailCardSection, native41DetailCardSection];
const original41RenderDetailCardOptions: original41.RenderDetailCardOptions = null as unknown as native41.RenderDetailCardOptions;
const native41RenderDetailCardOptions: native41.RenderDetailCardOptions = null as unknown as original41.RenderDetailCardOptions;
void [original41RenderDetailCardOptions, native41RenderDetailCardOptions];
import * as original42 from "toolcraft-design/render-html";
import * as native42 from "toolcraft-design-rust/render-html";
const original42Check: typeof original42 = native42;
const native42Check: typeof native42 = original42;
void [original42Check, native42Check];
const original42HtmlRenderOptions: original42.HtmlRenderOptions = null as unknown as native42.HtmlRenderOptions;
const native42HtmlRenderOptions: native42.HtmlRenderOptions = null as unknown as original42.HtmlRenderOptions;
void [original42HtmlRenderOptions, native42HtmlRenderOptions];
const original42MdNode: original42.MdNode = null as unknown as native42.MdNode;
const native42MdNode: native42.MdNode = null as unknown as original42.MdNode;
void [original42MdNode, native42MdNode];
import * as original43 from "toolcraft-design/render-inspector-card";
import * as native43 from "toolcraft-design-rust/render-inspector-card";
const original43Check: typeof original43 = native43;
const native43Check: typeof native43 = original43;
void [original43Check, native43Check];
const original43InspectorField: original43.InspectorField = null as unknown as native43.InspectorField;
const native43InspectorField: native43.InspectorField = null as unknown as original43.InspectorField;
void [original43InspectorField, native43InspectorField];
const original43InspectorSection: original43.InspectorSection = null as unknown as native43.InspectorSection;
const native43InspectorSection: native43.InspectorSection = null as unknown as original43.InspectorSection;
void [original43InspectorSection, native43InspectorSection];
const original43RenderInspectorCardOptions: original43.RenderInspectorCardOptions = null as unknown as native43.RenderInspectorCardOptions;
const native43RenderInspectorCardOptions: native43.RenderInspectorCardOptions = null as unknown as original43.RenderInspectorCardOptions;
void [original43RenderInspectorCardOptions, native43RenderInspectorCardOptions];
import * as original44 from "toolcraft-design/render-markdown-html";
import * as native44 from "toolcraft-design-rust/render-markdown-html";
const original44Check: typeof original44 = native44;
const native44Check: typeof native44 = original44;
void [original44Check, native44Check];
const original44HtmlRenderOptions: original44.HtmlRenderOptions = null as unknown as native44.HtmlRenderOptions;
const native44HtmlRenderOptions: native44.HtmlRenderOptions = null as unknown as original44.HtmlRenderOptions;
void [original44HtmlRenderOptions, native44HtmlRenderOptions];
import * as original45 from "toolcraft-design/render-markdown-plaintext";
import * as native45 from "toolcraft-design-rust/render-markdown-plaintext";
const original45Check: typeof original45 = native45;
const native45Check: typeof native45 = original45;
void [original45Check, native45Check];
const original45PlaintextRenderOptions: original45.PlaintextRenderOptions = null as unknown as native45.PlaintextRenderOptions;
const native45PlaintextRenderOptions: native45.PlaintextRenderOptions = null as unknown as original45.PlaintextRenderOptions;
void [original45PlaintextRenderOptions, native45PlaintextRenderOptions];
import * as original46 from "toolcraft-design/render-markdown";
import * as native46 from "toolcraft-design-rust/render-markdown";
const original46Check: typeof original46 = native46;
const native46Check: typeof native46 = original46;
void [original46Check, native46Check];
const original46RenderOptions: original46.RenderOptions = null as unknown as native46.RenderOptions;
const native46RenderOptions: native46.RenderOptions = null as unknown as original46.RenderOptions;
void [original46RenderOptions, native46RenderOptions];
import * as original47 from "toolcraft-design/render-menu";
import * as native47 from "toolcraft-design-rust/render-menu";
const original47Check: typeof original47 = native47;
const native47Check: typeof native47 = original47;
void [original47Check, native47Check];
const original47MenuOption: original47.MenuOption = null as unknown as native47.MenuOption;
const native47MenuOption: native47.MenuOption = null as unknown as original47.MenuOption;
void [original47MenuOption, native47MenuOption];
const original47RenderMenuOptions: original47.RenderMenuOptions = null as unknown as native47.RenderMenuOptions;
const native47RenderMenuOptions: native47.RenderMenuOptions = null as unknown as original47.RenderMenuOptions;
void [original47RenderMenuOptions, native47RenderMenuOptions];
import * as original48 from "toolcraft-design/render-resource-browser";
import * as native48 from "toolcraft-design-rust/render-resource-browser";
const original48Check: typeof original48 = native48;
const native48Check: typeof native48 = original48;
void [original48Check, native48Check];
const original48RenderResourceBrowserOptions: original48.RenderResourceBrowserOptions = null as unknown as native48.RenderResourceBrowserOptions;
const native48RenderResourceBrowserOptions: native48.RenderResourceBrowserOptions = null as unknown as original48.RenderResourceBrowserOptions;
void [original48RenderResourceBrowserOptions, native48RenderResourceBrowserOptions];
const original48ResourceBrowserGroup: original48.ResourceBrowserGroup = null as unknown as native48.ResourceBrowserGroup;
const native48ResourceBrowserGroup: native48.ResourceBrowserGroup = null as unknown as original48.ResourceBrowserGroup;
void [original48ResourceBrowserGroup, native48ResourceBrowserGroup];
const original48ResourceBrowserItem: original48.ResourceBrowserItem = null as unknown as native48.ResourceBrowserItem;
const native48ResourceBrowserItem: native48.ResourceBrowserItem = null as unknown as original48.ResourceBrowserItem;
void [original48ResourceBrowserItem, native48ResourceBrowserItem];
import * as original49 from "toolcraft-design/render-spinner-frame";
import * as native49 from "toolcraft-design-rust/render-spinner-frame";
const original49Check: typeof original49 = native49;
const native49Check: typeof native49 = original49;
void [original49Check, native49Check];
const original49SpinnerFrameOptions: original49.SpinnerFrameOptions = null as unknown as native49.SpinnerFrameOptions;
const native49SpinnerFrameOptions: native49.SpinnerFrameOptions = null as unknown as original49.SpinnerFrameOptions;
void [original49SpinnerFrameOptions, native49SpinnerFrameOptions];
import * as original50 from "toolcraft-design/render-spinner-stopped";
import * as native50 from "toolcraft-design-rust/render-spinner-stopped";
const original50Check: typeof original50 = native50;
const native50Check: typeof native50 = original50;
void [original50Check, native50Check];
const original50SpinnerStoppedOptions: original50.SpinnerStoppedOptions = null as unknown as native50.SpinnerStoppedOptions;
const native50SpinnerStoppedOptions: native50.SpinnerStoppedOptions = null as unknown as original50.SpinnerStoppedOptions;
void [original50SpinnerStoppedOptions, native50SpinnerStoppedOptions];
import * as original51 from "toolcraft-design/render-table";
import * as native51 from "toolcraft-design-rust/render-table";
const original51Check: typeof original51 = native51;
const native51Check: typeof native51 = original51;
void [original51Check, native51Check];
const original51RenderTableOptions: original51.RenderTableOptions = null as unknown as native51.RenderTableOptions;
const native51RenderTableOptions: native51.RenderTableOptions = null as unknown as original51.RenderTableOptions;
void [original51RenderTableOptions, native51RenderTableOptions];
const original51TableColumn: original51.TableColumn = null as unknown as native51.TableColumn;
const native51TableColumn: native51.TableColumn = null as unknown as original51.TableColumn;
void [original51TableColumn, native51TableColumn];
import * as original52 from "toolcraft-design/render-template";
import * as native52 from "toolcraft-design-rust/render-template";
const original52Check: typeof original52 = native52;
const native52Check: typeof native52 = original52;
void [original52Check, native52Check];
const original52RenderTemplateOptions: original52.RenderTemplateOptions = null as unknown as native52.RenderTemplateOptions;
const native52RenderTemplateOptions: native52.RenderTemplateOptions = null as unknown as original52.RenderTemplateOptions;
void [original52RenderTemplateOptions, native52RenderTemplateOptions];
const original52TemplateEscape: original52.TemplateEscape = null as unknown as native52.TemplateEscape;
const native52TemplateEscape: native52.TemplateEscape = null as unknown as original52.TemplateEscape;
void [original52TemplateEscape, native52TemplateEscape];
import * as original53 from "toolcraft-design/render";
import * as native53 from "toolcraft-design-rust/render";
const original53Check: typeof original53 = native53;
const native53Check: typeof native53 = original53;
void [original53Check, native53Check];
const original53MdNode: original53.MdNode = null as unknown as native53.MdNode;
const native53MdNode: native53.MdNode = null as unknown as original53.MdNode;
void [original53MdNode, native53MdNode];
const original53RenderOptions: original53.RenderOptions = null as unknown as native53.RenderOptions;
const native53RenderOptions: native53.RenderOptions = null as unknown as original53.RenderOptions;
void [original53RenderOptions, native53RenderOptions];
import * as original54 from "toolcraft-design/reset-output-format-cache";
import * as native54 from "toolcraft-design-rust/reset-output-format-cache";
const original54Check: typeof original54 = native54;
const native54Check: typeof native54 = original54;
void [original54Check, native54Check];
import * as original55 from "toolcraft-design/reset-theme-cache";
import * as native55 from "toolcraft-design-rust/reset-theme-cache";
const original55Check: typeof original55 = native55;
const native55Check: typeof native55 = original55;
void [original55Check, native55Check];
import * as original56 from "toolcraft-design/reset-theme";
import * as native56 from "toolcraft-design-rust/reset-theme";
const original56Check: typeof original56 = native56;
const native56Check: typeof native56 = original56;
void [original56Check, native56Check];
import * as original57 from "toolcraft-design/resolve-output-format";
import * as native57 from "toolcraft-design-rust/resolve-output-format";
const original57Check: typeof original57 = native57;
const native57Check: typeof native57 = original57;
void [original57Check, native57Check];
const original57OutputFormat: original57.OutputFormat = null as unknown as native57.OutputFormat;
const native57OutputFormat: native57.OutputFormat = null as unknown as original57.OutputFormat;
void [original57OutputFormat, native57OutputFormat];
import * as original58 from "toolcraft-design/resolve-template-partials";
import * as native58 from "toolcraft-design-rust/resolve-template-partials";
const original58Check: typeof original58 = native58;
const native58Check: typeof native58 = original58;
void [original58Check, native58Check];
import * as original59 from "toolcraft-design/resolve-theme-name";
import * as native59 from "toolcraft-design-rust/resolve-theme-name";
const original59Check: typeof original59 = native59;
const native59Check: typeof native59 = original59;
void [original59Check, native59Check];
const original59ThemeEnv: original59.ThemeEnv = null as unknown as native59.ThemeEnv;
const native59ThemeEnv: native59.ThemeEnv = null as unknown as original59.ThemeEnv;
void [original59ThemeEnv, native59ThemeEnv];
import * as original60 from "toolcraft-design/run-explorer";
import * as native60 from "toolcraft-design-rust/run-explorer";
const original60Check: typeof original60 = native60;
const native60Check: typeof native60 = original60;
void [original60Check, native60Check];
const original60ExplorerConfig: original60.ExplorerConfig<unknown> = null as unknown as native60.ExplorerConfig<unknown>;
const native60ExplorerConfig: native60.ExplorerConfig<unknown> = null as unknown as original60.ExplorerConfig<unknown>;
void [original60ExplorerConfig, native60ExplorerConfig];
import * as original61 from "toolcraft-design/select";
import * as native61 from "toolcraft-design-rust/select";
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const original61Check: typeof original61 = native61;
// @ts-expect-error Separate cancellation symbols remain a nominal swap gate.
const native61Check: typeof native61 = original61;
void [original61Check, native61Check];
const original61SelectOptions: original61.SelectOptions<unknown> = null as unknown as native61.SelectOptions<unknown>;
const native61SelectOptions: native61.SelectOptions<unknown> = null as unknown as original61.SelectOptions<unknown>;
void [original61SelectOptions, native61SelectOptions];
import * as original62 from "toolcraft-design/should-use-interactive-dashboard";
import * as native62 from "toolcraft-design-rust/should-use-interactive-dashboard";
const original62Check: typeof original62 = native62;
const native62Check: typeof native62 = original62;
void [original62Check, native62Check];
import * as original63 from "toolcraft-design/single-detail";
import * as native63 from "toolcraft-design-rust/single-detail";
const original63Check: typeof original63 = native63;
const native63Check: typeof native63 = original63;
void [original63Check, native63Check];
const original63Detail: original63.Detail<unknown> = null as unknown as native63.Detail<unknown>;
const native63Detail: native63.Detail<unknown> = null as unknown as original63.Detail<unknown>;
void [original63Detail, native63Detail];
const original63DetailCtx: original63.DetailCtx = null as unknown as native63.DetailCtx;
const native63DetailCtx: native63.DetailCtx = null as unknown as original63.DetailCtx;
void [original63DetailCtx, native63DetailCtx];
const original63DetailItem: original63.DetailItem = null as unknown as native63.DetailItem;
const native63DetailItem: native63.DetailItem = null as unknown as original63.DetailItem;
void [original63DetailItem, native63DetailItem];
const original63Row: original63.Row = null as unknown as native63.Row;
const native63Row: native63.Row = null as unknown as original63.Row;
void [original63Row, native63Row];
import * as original64 from "toolcraft-design/spacing";
import * as native64 from "toolcraft-design-rust/spacing";
const original64Check: typeof original64 = native64;
const native64Check: typeof native64 = original64;
void [original64Check, native64Check];
import * as original65 from "toolcraft-design/spinner-frames";
import * as native65 from "toolcraft-design-rust/spinner-frames";
const original65Check: typeof original65 = native65;
const native65Check: typeof native65 = original65;
void [original65Check, native65Check];
import * as original66 from "toolcraft-design/spinner";
import * as native66 from "toolcraft-design-rust/spinner";
const original66Check: typeof original66 = native66;
const native66Check: typeof native66 = original66;
void [original66Check, native66Check];
const original66SpinnerOptions: original66.SpinnerOptions = null as unknown as native66.SpinnerOptions;
const native66SpinnerOptions: native66.SpinnerOptions = null as unknown as original66.SpinnerOptions;
void [original66SpinnerOptions, native66SpinnerOptions];
import * as original67 from "toolcraft-design/strip-ansi";
import * as native67 from "toolcraft-design-rust/strip-ansi";
const original67Check: typeof original67 = native67;
const native67Check: typeof native67 = original67;
void [original67Check, native67Check];
import * as original68 from "toolcraft-design/symbols";
import * as native68 from "toolcraft-design-rust/symbols";
const original68Check: typeof original68 = native68;
const native68Check: typeof native68 = original68;
void [original68Check, native68Check];
import * as original69 from "toolcraft-design/text";
import * as native69 from "toolcraft-design-rust/text";
const original69Check: typeof original69 = native69;
const native69Check: typeof native69 = original69;
void [original69Check, native69Check];
import * as original70 from "toolcraft-design/typography";
import * as native70 from "toolcraft-design-rust/typography";
const original70Check: typeof original70 = native70;
const native70Check: typeof native70 = original70;
void [original70Check, native70Check];
import * as original71 from "toolcraft-design/widths";
import * as native71 from "toolcraft-design-rust/widths";
const original71Check: typeof original71 = native71;
const native71Check: typeof native71 = original71;
void [original71Check, native71Check];
import * as original72 from "toolcraft-design/with-output-format";
import * as native72 from "toolcraft-design-rust/with-output-format";
const original72Check: typeof original72 = native72;
const native72Check: typeof native72 = original72;
void [original72Check, native72Check];
const original72OutputFormat: original72.OutputFormat = null as unknown as native72.OutputFormat;
const native72OutputFormat: native72.OutputFormat = null as unknown as original72.OutputFormat;
void [original72OutputFormat, native72OutputFormat];
import * as original73 from "toolcraft-design/with-spinner";
import * as native73 from "toolcraft-design-rust/with-spinner";
const original73Check: typeof original73 = native73;
const native73Check: typeof native73 = original73;
void [original73Check, native73Check];
const original73WithSpinnerOptions: original73.WithSpinnerOptions<unknown> = null as unknown as native73.WithSpinnerOptions<unknown>;
const native73WithSpinnerOptions: native73.WithSpinnerOptions<unknown> = null as unknown as original73.WithSpinnerOptions<unknown>;
void [original73WithSpinnerOptions, native73WithSpinnerOptions];
