import assert from 'node:assert/strict';
import fs from 'node:fs';
import { spawn } from 'node:child_process';
import { resolve } from 'node:path';
import { recipe, owned, node, read, fileHash, sha, save, write, authenticatePreparation, reason, inventory, sameInventory } from './common.mjs';
import { requireAuthorization, applyMutant } from './admission.mjs';
import { parseDiagnostics, qualifyType } from './type-trace.mjs';
import { legacyAdapter } from './legacy-transform.mjs';
import { freshControls } from './negative-protocol.mjs';
import { absent } from './supervisor.mjs';
import { archiveEvidence } from './archive.mjs';
import { consumers } from '../public-integration-freeze-v1/types.mjs';
const manifestHash=process.argv[2];const {manifest,binding}=authenticatePreparation(manifestHash);
const run=resolve(recipe,'runs/preparation-controls'),raw=resolve(run,'raw'),work=resolve(recipe,'node_modules/preparation-controls');
assert.equal(fs.existsSync(run),false,'PREPARATION_CONTROL_NO_RETRY');assert.equal(fs.existsSync(work),false,'PREPARATION_CONTROL_NO_RETRY');fs.mkdirSync(raw,{recursive:true});fs.mkdirSync(work,{recursive:true});save(resolve(run,'LOCK.json'),{startedAt:new Date().toISOString(),manifestHash});
const outcomes=[],children=[];
const check=(id,name,execute)=>{try{execute();outcomes.push({id,name,status:'PASS'});}catch(error){outcomes.push({id,name,status:'FAIL',failure:reason(error)});}};
const reject=(id,name,needle,execute)=>check(id,name,()=>assert.throws(execute,error=>error.message.includes(needle)));
const fake={schema:'timeout-public-candidate-binding/1',baseline:binding.baseline,module:binding.acceptedModule,candidate:'1'.repeat(40),preparationSha256:manifestHash,pack:{sha256:'2'.repeat(64)},packageFiles:[{path:'package.json',mode:420,sha256:'3'.repeat(64)}],public:binding.publicReplacementPaths.map(path=>({path})),mutants:['R01','R04','R09','R07','R15','R13','R23','R25'].map((caseId,index)=>({id:`M${String(index+1).padStart(2,'0')}`,caseId,failure:'synthetic-designated'})),runtimeCases:Array.from({length:30},(_,index)=>`R${String(index+1).padStart(2,'0')}`),publicAuthorization:'root-exact-candidate-handoff',runName:'not-executed'};
const args=['--execute-declared-candidate',fake.candidate,'a'.repeat(64)];
check('P01','explicit synthetically valid gate',()=>requireAuthorization(args,fake,args[2]));
reject('P02','no implicit authorization','EXPLICIT_CANDIDATE_AUTHORIZATION_REQUIRED',()=>requireAuthorization([],fake,args[2]));
reject('P03','wrong candidate token','EXPLICIT_CANDIDATE_AUTHORIZATION_REQUIRED',()=>requireAuthorization([args[0],'0'.repeat(40),args[2]],fake,args[2]));
reject('P04','wrong baseline','BASELINE_REQUIRED',()=>requireAuthorization(args,{...fake,baseline:'0'.repeat(40)},args[2]));
reject('P05','missing exact pack','NEW_PACK_REQUIRED',()=>requireAuthorization(args,{...fake,pack:{}},args[2]));
reject('P06','wrong mutant predicate','DESIGNATED_MUTANT_CASE',()=>requireAuthorization(args,{...fake,mutants:fake.mutants.map(row=>({...row,caseId:'R01'}))},args[2]));
check('P07','multiline compiler message/token',()=>{const rows=parseDiagnostics("consumer.ts(2,7): error TS2322: Type 'number' is not assignable to type 'CommandInvoker'.\n  Additional diagnostic detail.\n",consumers[4].source);assert.equal(rows.length,1);assert.equal(rows[0].token,'value');assert.equal(rows[0].line,2);assert.ok(rows[0].message.endsWith('Additional diagnostic detail.'));});
reject('P08','unrelated compiler envelope','UNRELATED_COMPILER_OUTPUT',()=>parseDiagnostics('error TS2688: Cannot find type definition file for node.\n',consumers[4].source));
reject('P09','wrong compiler token location','DIAGNOSTIC_TOKEN_LOCATION',()=>parseDiagnostics('consumer.ts(2,1): error TS2322: wrong\n','\n!\n'));
const packageRoot=resolve(work,'synthetic-package'),consumerPath=resolve(work,'consumer.ts'),configPath=resolve(work,'tsconfig.json'),consumerPackagePath=resolve(work,'package.json');
const spec=consumers[1],metadata='{}',declaration='export {};\n',context={packageRoot,consumerPath,configPath,configHash:sha('{}'),consumerPackagePath,consumerPackageHash:sha('{}'),toolMap:{},compilerHash:'4'.repeat(64),packageFiles:[{path:'package.json',sha256:sha(metadata)},{path:'dist/commands/timeout/index.d.ts',sha256:sha(declaration)}]};
const result={code:0,signal:null,stdout:'',stderr:'',records:[{kind:'actual-commonjs-compile',compileSha256:context.compilerHash},...[{path:consumerPath,sha256:sha(spec.source)},{path:configPath,sha256:sha('{}')},{path:consumerPackagePath,sha256:sha('{}')},{path:resolve(packageRoot,'package.json'),sha256:sha(metadata)},{path:resolve(packageRoot,'dist/commands/timeout/index.d.ts'),sha256:sha(declaration)}].map(row=>({kind:'actual-file-read',...row}))]};
check('P10','leaf-only actual-read receipt classifier',()=>assert.deepEqual(qualifyType(result,spec,context).authenticatedReads,['dist/commands/timeout/index.d.ts']));
reject('P11','wrong required entrypoint','DECLARATION_ENTRYPOINT',()=>qualifyType(result,{...spec,entrypoint:'root'},context));
reject('P12','unbound declaration read','UNBOUND_TYPE_READ',()=>qualifyType({...result,records:[...result.records,{kind:'actual-file-read',path:'/unbound/index.d.ts',sha256:'0'.repeat(64)}]},spec,context));
reject('P13','tampered declaration','DECLARATION_HASH',()=>qualifyType({...result,records:result.records.map(row=>row.path===resolve(packageRoot,'dist/commands/timeout/index.d.ts')?{...row,sha256:'0'.repeat(64)}:row)},spec,context));
reject('P14','missing actual compiler load','ACTUAL_TYPESCRIPT_LOAD',()=>qualifyType({...result,records:result.records.slice(1)},spec,context));
const old=resolve(owned,'repaired-f22-v1/recipe/cases.mjs'),oldBytes=fs.readFileSync(old);
check('P15','exact legacy transformation and no automatic cohort',()=>{const transformed=legacyAdapter(oldBytes,fileHash(old));assert.equal(transformed.sourceSha256,fileHash(resolve(recipe,'legacy-adapter.mjs')));assert.ok(!transformed.source.includes('const allIds'));assert.ok(transformed.source.includes("actual = instance.commands.get('timeout')"));});
reject('P16','wrong accepted legacy hash','ACCEPTED_LEGACY_SOURCE_HASH',()=>legacyAdapter(oldBytes,'0'.repeat(64)));
const before=Buffer.from('before\n'),mutation={path:'src/example.ts',before:'before',after:'after',beforeSha256:sha(before),afterSha256:sha('after\n')};
check('P17','exact scoped synthetic mutant',()=>assert.equal(applyMutant(before,mutation).toString(),'after\n'));
reject('P18','ambiguous mutant refused','UNIQUE_MUTANT_DELTA',()=>applyMutant(Buffer.from('before before'),{...mutation,beforeSha256:sha('before before')}));
check('P19','actual fresh metadata guard controls',()=>assert.equal(freshControls(resolve(work,'fresh')).length,6));
check('P20','unknown empty fresh directory refused',()=>{fs.mkdirSync(resolve(work,'fresh/empty'));try{assert.throws(()=>inventory(resolve(work,'fresh')),/UNLISTED_EMPTY_DIRECTORY/u);}finally{fs.rmdirSync(resolve(work,'fresh/empty'));}});
reject('P21','wrong package mode gate','PACK_MEMBER_MODE',()=>requireAuthorization(args,{...fake,packageFiles:[{...fake.packageFiles[0],mode:511}]},args[2]));
reject('P22','original case omission refused','UNCHANGED_RUNTIME_CASES',()=>requireAuthorization(args,{...fake,runtimeCases:fake.runtimeCases.slice(1)},args[2]));
async function childControl(id,name,argv,environment,expected){
  const record={id,name,args:argv,nodeSha256:fileHash(node),startedAt:new Date().toISOString(),forced:false};const child=spawn(node,argv,{cwd:recipe,env:{PATH:'/usr/bin:/bin',...environment},detached:true,stdio:['ignore','pipe','pipe']});record.pid=child.pid;children.push(record);const stdout=[],stderr=[];let bytes=0;
  const timer=setTimeout(()=>{record.forced=true;try{process.kill(-child.pid,'SIGKILL');}catch{}},10000);
  for(const [stream,rows] of [[child.stdout,stdout],[child.stderr,stderr]])stream.on('data',chunk=>{bytes+=chunk.length;if(bytes>1024**2){record.forced=true;try{process.kill(-child.pid,'SIGKILL');}catch{}}else rows.push(Buffer.from(chunk));});
  await new Promise(done=>{child.on('error',error=>{record.spawnError=reason(error);});child.on('exit',(code,signal)=>{record.exit={code,signal};});child.on('close',(code,signal)=>{record.close={code,signal};clearTimeout(timer);done();});});
  record.stdout=Buffer.concat(stdout).toString();record.stderr=Buffer.concat(stderr).toString();if(record.pid){absent(record.pid);record.reaped=true;}save(resolve(raw,`${id}-child.json`),record);
  check(id,name,()=>{assert.equal(record.forced,false);assert.equal(record.spawnError,undefined);assert.deepEqual(record.exit,record.close);assert.equal(record.close.code,1);assert.ok(record.stderr.includes(expected));});
}
await childControl('P23','executor rejects without handoff before product work',[resolve(recipe,'execute.mjs')],{},'WAITING_EXACT_CANDIDATE_HANDOFF');
const disabled=resolve(work,'disabled-config.json');save(disabled,{executionAuthorized:false,trace:resolve(raw,'must-not-exist.jsonl')});
await childControl('P24','preload rejects disabled product authorization',['--import',resolve(recipe,'preload.mjs'),'-e','throw new Error("must not reach entry")'],{TIMEOUT_CONFIG:disabled,TIMEOUT_CONFIG_SHA256:fileHash(disabled)},'PRODUCT_EXECUTION_NOT_AUTHORIZED');
check('P25','preload rejection produces no product trace',()=>assert.equal(fs.existsSync(resolve(raw,'must-not-exist.jsonl')),false));
check('P26','immutable freeze postguard',()=>authenticatePreparation(manifestHash));
assert.equal(outcomes.length,manifest.preparationControls);save(resolve(raw,'OUTCOMES.json'),outcomes);
const archive=archiveEvidence({run,raw,work,children,remove:outcomes.every(row=>row.status==='PASS')});
save(resolve(run,'RESULT.json'),{schema:'timeout-public-preparation-validation/1',manifestHash,completedAt:new Date().toISOString(),outcomes,passed:outcomes.filter(row=>row.status==='PASS').length,failed:outcomes.filter(row=>row.status==='FAIL').length,children:children.map(row=>({id:row.id,pid:row.pid,reaped:row.reaped,forced:row.forced,exit:row.exit})),archive,actualPublicCases:0,actualPublicTypes:0,actualProductImports:0,actualBuilds:0,native:0,safeJS:0,retries:0});
console.log(JSON.stringify({passed:outcomes.filter(row=>row.status==='PASS').length,total:outcomes.length,children:children.length,reaped:children.every(row=>row.reaped),productExecution:0,manifestHash}));if(outcomes.some(row=>row.status!=='PASS'))process.exitCode=1;
