name: truffledog testing api key 2
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Semi realistic api key 2
    runs-on: ubuntu-latest
    env:
      SERVICE_API_KEY: svc_live_Q8wZ4pL2nR7tY5kM1xC9vB6hD3jF0aSeGqTu
    steps:
      - name: Print test marker
        run: echo "truffledog testing api key 2"
