name: truffledog testing 2
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Dummy fake token id 2
    runs-on: ubuntu-latest
    env:
      FAKE_TOKEN_ID: truffledog-testing-fake-token-id-2
    steps:
      - name: Print test marker
        run: echo "truffledog testing 2"
