name: truffledog testing 1
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Dummy fake token id 1
    runs-on: ubuntu-latest
    env:
      FAKE_TOKEN_ID: truffledog-testing-fake-token-id-1
    steps:
      - name: Print test marker
        run: echo "truffledog testing 1"
