name: truffledog testing api key 1
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Semi realistic api key 1
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_KEY: pcode_live_7K9mQ2xV8rT4nB6yF1sD3hJ5lZ0cXwEaPqRsTu
    steps:
      - name: Print test marker
        run: echo "truffledog testing api key 1"
