name: truffledog testing api key 2
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Semi realistic api key 2
    runs-on: ubuntu-latest
    env:
      SHODAN_API_KEY: 28tEbDdpkFvftp9XkMzAf7O7uVTYlPYD
    steps:
      - name: Print test marker
        run: echo "truffledog testing api key 2"
