name: truffledog testing api key 1
on:
  workflow_dispatch: {}

jobs:
  dummy:
    name: Semi realistic api key 1
    runs-on: ubuntu-latest
    env:
      WEATHERBIT_API_KEY: zqjxo96wmdi1rdcvohnpu0v3bkypbuti
    steps:
      - name: Print test marker
        run: echo "truffledog testing api key 1"
