import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
const root=path.dirname(new URL(import.meta.url).pathname);
const capture=fs.openSync(root+'/ACQUIRE.capture.data','wx',0o600);
const log=row=>fs.writeSync(capture,JSON.stringify(row)+'\n');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const assert=(value,message)=>{if(!value)throw Error(message);};let starts=0;
try{
 log({event:'START',at:new Date().toISOString()});
 const jobs=[['author','8bd170e5465c1253a52231c9cf08b5afef064d81',['tests/compatibility/bash-ere-engine-author-20260829/HANDOFF.md','tests/compatibility/bash-ere-engine-author-20260829/README.md']],['engine','f97fd06024cb63edfd01873d81d84576a22189db',['src/commands/regex-execution/ere']],['design','a2249d466436f1f94ba2976265f4e1cc9d93137b',['tests/compatibility/bash-ere-design-20260829']],['clarification','e2b4823c786a046f928b027225ce321c5af8a60d',['tests/compatibility/bash-ere-design-20260829']]];
 for(const[label,commit,paths]of jobs){const destination=root+'/'+label;fs.mkdirSync(destination);const git=(args,input)=>{starts++;log({event:'ENROLLED',starts,args});const result=spawnSync('/usr/bin/git',args,{input,cwd:'/Users/kjopek/Workspace/safe-bash',env:{PATH:'/usr/bin:/bin',HOME:destination,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null',GIT_OPTIONAL_LOCKS:'0'},timeout:30000,maxBuffer:16*1024*1024});fs.writeFileSync(root+`/${starts}.stderr.data`,result.stderr??Buffer.alloc(0),{flag:'wx',mode:0o600});log({event:'RETIRED',starts,status:result.status,signal:result.signal,error:result.error?.message,stdoutBytes:result.stdout?.length});assert(!result.error&&!result.signal&&result.status===0,'METADATA_STOP');return result.stdout;};const listing=git(['ls-tree','-r','-z',commit,'--',...paths]);fs.writeFileSync(destination+'/inventory.data',listing,{flag:'wx',mode:0o600});const rows=listing.toString('utf8').split('\0').filter(Boolean).map(line=>{const match=/^(100644|100755) blob ([0-9a-f]{40})\t(.+)$/.exec(line);assert(match&&!match[3].split('/').includes('AGENTS.md'),'PATH_ROLE');return {mode:match[1],blob:match[2],path:match[3]};});assert(rows.length>0&&rows.length<=100,'COUNT');const batch=git(['cat-file','--batch'],Buffer.from(rows.map(row=>row.blob).join('\n')+'\n'));let offset=0;for(const[index,row]of rows.entries()){const end=batch.indexOf(10,offset),header=batch.subarray(offset,end).toString('ascii').split(' '),size=Number(header[2]);assert(header[0]===row.blob&&header[1]==='blob'&&Number.isSafeInteger(size)&&size>=0&&size<8*1024*1024,'HEADER');const bytes=batch.subarray(end+1,end+1+size);assert(bytes.length===size&&batch[end+1+size]===10,'FRAMING');assert(createHash('sha1').update(`blob ${size}\0`).update(bytes).digest('hex')===row.blob,'BLOB_HASH');row.bytes=size;row.sha256=hash(bytes);row.capture=`${index}.data`;fs.writeFileSync(destination+'/'+row.capture,bytes,{flag:'wx',mode:0o600});offset=end+size+2;}assert(offset===batch.length,'TRAILER');fs.writeFileSync(destination+'/MANIFEST.json',JSON.stringify({commit,rows},null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({label,files:rows.map(row=>({name:row.path,capture:row.capture,bytes:row.bytes,sha256:row.sha256}))}));}
 log({event:'COMPLETE',starts});
}catch(error){log({event:'STOP',message:error.message,starts});process.exitCode=1;}finally{fs.closeSync(capture);}
